### ISSUE TITLE
Use statically linked protocols with mounts

### ISSUE THREAD

**Issue by stv0g** [warmcat/libwebsockets#1015]
I am confused by the interaction of mounts and statically linked protocols.

I have two mounts:
 - LWSMPRO_CALLBACK: for a HTTP / REST API (POST)
 - LWSMPRO_FILE: for serving some static content

I learned that `protocols[0]` is the the one which handles HTTP requests.
Do I need to add this protocol by using the dummy callback function `lws_callback_http_dummy`?
Can I use protocols[1] for the callback of by LWSMPRO_CALLBACK mounts?

Is there anything I have to care about if combining those two?

Note: I don't want to use the dynamically loaded plugin mechanism because I don't want to link against libuv. I also don't understand why libuv is required for loading the plugins...

Thanks :)

**Comment by stv0g** [comment]
I am asking, because I am experience some strange behaviour with the LWSMPRO_FILE mount.
Sometimes it simply delivers the wrong file from within the provided directory.
I could narrow this problem down to some interaction with my LWSMPRO_CALLBACK mount.

My code is here:

- https://git.rwth-aachen.de/VILLASframework/VILLASnode/blob/839c332813632bca9d3da3fe1a75587071674f0e/lib/web.c
- https://git.rwth-aachen.de/VILLASframework/VILLASnode/blob/839c332813632bca9d3da3fe1a75587071674f0e/lib/api.c

**Comment by lws-team** [comment]
I'm not entirely sure what you are dealing with, but to clarify

 - static-built plugins should be indistinguishable from dynamic ones

 - dynamic plugins require libuv... dynamic plugins make a lot of sense with lwsws, because you can build them standalone and don't have to deal with any non-generic server code.

 - protocols[0] is used to handle http requests by default. But that can be overridden for parts of tge urlspace using the callback mounts

 - you can point protocols[0] to the provided `lws_callback_http_dummy()`... together with the mounts it's designed to remove the need for any special code in protocols[0] callback

 - If you have allocations,`LWS_CALLBACK_HTTP_BIND_PROTOCOL` and `LWS_CALLBACK_HTTP_DROP_PROTOCOL`become important when dealing with callback mounts in a plugin, since they bracket the wsi binding lifetime

 - when using mounts + the dummy callback, generally lws will automatically deal with transaction lifecycle, but when you deal with POSTs in a plugin, you have to manage it.  See the way https://github.com/warmcat/libwebsockets/blob/master/plugins/protocol_post_demo.c uses `try_to_reuse` / `lws_http_transaction_completed()`

If you still have "wrong files" you need to track roughly where that is coming from to get an idea.

**Comment by stv0g** [comment]
Thanks a lot for the explanations. We should probably include them into the documentation.
Several of those newer callback reasons are not documented yet.

I was still using `LWS_CALLBACK_HTTP` which failed to properly initialise my session.

**Comment by lws-team** [comment]
Fair enough, I pushed a patch with the missing descriptions, and added some stuff to README.coding.md.

BTW Plugins need libuv because it's a crossplatform solution that also works on windows.
