### ISSUE TITLE
CMake: documentation is build "in-tree"

### ISSUE THREAD

**Issue by stv0g** [warmcat/libwebsockets#1024]
When doing a CMake build out-of-tree:

```bash
$ git clone https://github.com/warmcat/libwebsockets.git
$ mkdir libwebsockets-build
$ cmake -H libwebsockets -B libwebsockets-build
$ make -C libwebsockets-build
```

A directory called `doc` is created in the source directory.

In my opinion, this should end up in the build directory.

**Comment by lws-team** [comment]
For a release or two the docs did live in the tree and were auto-updated after each commit.

However doxygen adds a huge churn to any patch that touches the api, it creates a ton of files with api hashes and spams sometimes several thousand noise changes to a one-liner patch, so I removed that a few versions ago.  At the moment, if you want to create the docs you do it by `doxygen libwebsockets.dox` and where it produces the docs is defined by libwebsockets.dox.  I run that in a separate script each time I push and update the online docs for the tree being pushed.  **CMake doesn't know that and so neither does the makefile it produces**.

I did this

```
$ cd /tmp
$ git clone https://github.com/warmcat/libwebsockets.git
$ mkdir build
$ cd build
$ cmake ../libwebsockets
$ make
```

(Your example does not work, `cmake -H` prints help and rejects the rest of the args and fails).

There is no `doc` dir created in /tmp, /tmp/libwebsockets or /tmp/build.

**Comment by lws-team** [comment]
Thinking about the history mentioned above, the fact your reproducer is broken, and you won't find "dox" or "doc" in CMakeLists.txt or the generated Makefile from master, I'm going to go out on a limb and guess it's simply because you had a version checked out in your source dir from the Era Of The In-Tree Docs, eg, v2.1.0.

https://github.com/warmcat/libwebsockets/tree/v2.1-stable
