### ISSUE TITLE
How to avoid conflict lws_write

### ISSUE THREAD

**Issue by xmanmax** [warmcat/libwebsockets#1026]
Hi, I met a problem when I have a great amount of  connections.
I have two protocols : http and another one which used websockets, but one thread. 

when I receiving a ws message from a client under LWS_CALLBACK_RECEIVE callback ,I will push response message into a message queue, and invoke lws_callback_on_writable, in the LWS_CALLBACK_SERVER_WRITEABLE I do lws_write below:

//get a messge from msg-queue
do {
        lws_write(wsi, msg, strlen(msg),LWS_WRITE_TEXT);
    } while (!lws_send_pipe_choked(wsi) );

now, i maintained a great amount of connections with different clients, but I found sometimes ,I will get two LWS_CALLBACK_RECEIVE callback with different wsi, and then I will push two response messages into my queue, and when ask for lws_callback_on_writable, it will conflict. 
for example:
1) LWS_CALLBACK_RECEIVE come with **wsi 0x0001**, push **msg1** into message queue 
2) LWS_CALLBACK_RECEIVE come with **wsi 0x0002**, push **msg2** into message queue 
3) ask for lws_callback_on_writable with wsi 0x0002, pop a message from the queue(msg1 if the first ,so msg1 be got), then lws_write will **send to 0x0002 socket with msg1**

how to let  LWS_CALLBACK_RECEIVE and LWS_CALLBACK_SERVER_WRITEABLE  order be enforced.
T&R.

**Comment by xmanmax** [comment]
btw, my version is v2.3-stable, thx.

**Comment by lws-team** [comment]
What does it mean "it will conflict"?  What conflicts?

**Comment by xmanmax** [comment]
I mean I want send to wsi 0x0001 with msg1, and send to wsi 0x0002 with msg2, but now , send to wsi 0x0001 with msg2.

**Comment by lws-team** [comment]
It sounds like your FIFO / queue design isn't enough to do what you want, it's not an lws issue.

You cannot control the order of WRITEABLE messages, because network conditions decide it.

So you must either tag entries in your queue with "routing information" for which wsi should take them, or better have a smaller "queue per output wsi", and when you add an entry, you choose to put it in the correct queue corresponding to the wsi you want to write it.  Other wsi getting WRITABLE first are unaware of entries in some other guy's queue.

Is that what we're talking about or something else?

**Comment by xmanmax** [comment]
yes , thx , Andy , maybe I need a structor to maintain wsi and messages or a smaller "queue per output wsi " as you said.
