### ISSUE TITLE
Context stops giving LWS_CALLBACK_SERVER_WRITEABLE after transmitting for long periods of time

### ISSUE THREAD

**Issue by brendanbates89** [warmcat/libwebsockets#1027]
Our situation is that a client connects to a server streaming live sensor data and subscribes to various data streams.  Once that happens, the client just sits idle and receives data for however long it needs.  Every 100ms or so, the server iterates over each client that has pending data is asked for a writable callback via `lws_callback_on_writable(_connection);`.  Total throughput of data is ~25KiB/s per client.

The issue that I can't seem to trace back is that after ~15 minutes of streaming, suddenly all `LWS_CALLBACK_SERVER_WRITEABLE` callbacks stop arriving on all clients - even newly connected clients!  All clients can still send messages to the server to enable the sensors and subscribe, but they are receiving no messages back due to the lack of writable callbacks.

I'm wondering if perhaps there's something else that needs to be done in the writable callback to avoid this situation, or if this could be a possible bug in the library.  There's nothing fancy really being done threading wise here (single thread where the server is created and ran from).  I currently have the log level set to `LLL_WARN` and there are no errors being presented to the syslog.  Please let me know if more information such as logging or code is necessary - thanks!

**Comment by lws-team** [comment]
Okay... but what can I do about that?

I don't have (or want) your code.  If you can cut up the test apps to show the same problem, I'll be happy to to try to reproduce, if it fails on my platforms.  Or if there's some logs pointing the finger in lws direction, also happy to try to understand it from that.  But you don't have that, or trace what happens when it starts failing vs while it's working.  Or try make it fail faster with more connections or more data.  Or study your system for some resource exhaustion.

WRITEABLE is a matter of POLLOUT enabled on poll() by default (you don't mention platform, event loop, or lws verson), that's unlikely to fail in itself.

**Comment by brendanbates89** [comment]
Got it - currently still testing, wasn't sure if this was a common situation if there is more that needs to be checked before performing a `lws_write()`.  I'll be sure to either close if resolved from my side or post more info if I can get some better logging in.

**Comment by lws-team** [comment]
Well, there is nothing for me to do on this.  If you update with something actionable will look at it / reopen.

**Comment by nixomose** [comment]
we're having the same problem, still sussing out the details, but it takes a while to happen so it's hard to  reproduce or know how to reproduce quickly. will update if we find details, I'm hoping somebody has some suggestions because this is a showstopper for us. Thanks for any help anybody can provide.

**Comment by lws-team** [comment]
This ever happens when the peer is on the server's localhost?

Ever happens with the test apps?

What is your platform on both sides?  Lws version?

**Comment by lws-team** [comment]
> We're using windows client and linux ubuntu on the server side.

Client and server both lws or something else?

Problem is coming if entirely on Ubuntu?

What is the pattern of activity on the connection leading up to the problem?  It goes idle for a long time, something else?

**Comment by nixomose** [comment]
lws 2.23 stable on windows 10 client side and ubuntu 16.04 server side. Same build both sides.

So we think we found it. Just for others who might run into this.

In our case, the client ended up waiting for a response from the server, and the server never sent anything because the client's output buffer (our buffer that we feed lws when we get a WRITABLE callback) was not flushing. We'd call lws_callback_on_writable() when we put something in our buffer to flush, but we'd never get a LWS_CALLBACK_SERVER_WRITEABLE, so our outgoing buffer would never get written and we'd hang on the client side because the server never got anything. There's no error anywhere, because nothing's going wrong, it's just the absence of a LWS_CALLBACK_SERVER_WRITEABLE callback.

So anyway, there were a few places in different threads where we call lws_callback_on_writable.
See this: https://github.com/warmcat/libwebsockets/issues/571   lws-team commented on Jun 28, 2016 

We lock around all lws library calls, but we do that one in a different thread than the service loop and callback thread.

When we stopped doing that, the problem went away.

Instead we send ourselves a note saying "we just put some data in the buffer, and this wsi needs to have a  lws_callback_on_writable()  call made" and then we pick up that note in the service thread.
So absolutely every lws library call happens only ever in that one thread.

When we did that, the problem went away.

Maybe there's some race somewhere else, but that seems to be what did it.

**Comment by nixomose** [comment]
The pattern of activity was sending lots of data, hundreds of gigs. my test was sending 800gig, and somewhere around the 500-600gig mark it would just stop, in the way described above.

**Comment by lws-team** [comment]
> So anyway, there were a few places in different threads where we call lws_callback_on_writable.

Hm... your appeal for help nowhere includes the word 'thread'.  So I dunno what the guy that could have helped you would have looked like.... Gandalf maybe.

You can't do that because although lws can identify cleanly that you are calling it from a foreign thread, it does not defend itself against reentrancy from multiple foreign threads at once.

You need to provide a mutex around your calls into lws_callback_on_writable() to serialize the different guys who want to signal it.

A better way in later lws is just call lws_cancel_service() from the other threads.  This gets you a callback as soon as possible in lws thread context with LWS_CALLBACK_EVENT_WAIT_CANCELLED... you can figure out what needs doing from there in lws thread context.  That call just involves putting a byte in a pipe and is safe against reentrancy.

**Comment by nixomose** [comment]
I do lock around  lws_callback_on_writable() and in fact to protect myself more, we make sure not to ever call it from any thread other than the service loop thread. We've added a mechanism to signal that thread that a given wsi has to have that call made. 
When we deviated from that was when we started running into problems.
No gandalf required.
I was just posting this in case somebody else comes across this problem, I was going to share our solution.
