### ISSUE TITLE
Wrong callback gets called when two protocols are defined

### ISSUE THREAD

**Issue by readysteadygo2006** [warmcat/libwebsockets#1031]
Hi, 

Following on from the question I asked yesterday.

1. When define two protocols, in the protocols array:

enum protocols
{
	PROTOCOL_SERVER = 0,
	PROTOCOL_MOBILE = 1,
	PROTOCOL_COUNT
};

static struct lws_protocols protocols[] =
{
	{
		"server-protocol",
		callback_server,
		0,
		MAX_ECHO_PAYLOAD,
	},
	{
		"mobile-protocol",
		callback_mobile,
		0,
		MAX_ECHO_PAYLOAD,
	},
	{ NULL, NULL, 0, 0 } /* terminator */
};

then even if I make a call of the form:

			web_socket_server = lws_client_connect( /* context = */ context,
			                                 /* address =*/  targetAddress,
			                                 /* port = */ targetPort,
			                                 /* ssl_connection = */ 0,
			                                 /* path = */ "/",
			                                 /* host = */ lws_canonical_hostname( context ),
			                                 /* origin = */ "origin",
			                                 /* protocol = */ server_protocols[PROTOCOL_MOBILE].name,
			                                 /* ietf_version_or_minus_one = */ -1 );

then callback_server is called even thought I never try to connect to the client associated
with this protocol?

I'm working around the issue, by defining two threads, each with a single protocol, then the 
behaviour is correct!

Can you help?

BR
Paul Grant

**Comment by lws-team** [comment]
Some callbacks are always made to protocols[0], because no other protocol has been decided yet.  The actual protocol to use for ws is only known after the upgrade negotiation completes.

In particular, stuff related to HTTP transactions, with no callback mounts applied, will always go to protocols[0].

You can set your protocols[0] stuff to use the (exported) lws_callback_http_dummy() if you don't care about http, and have your two protocols as protocols[1] and [2], which won't get called for default "I don't know what protocol we are using yet" activity.
