### ISSUE TITLE
creating a connection  causes two to be made

### ISSUE THREAD

**Issue by nixomose** [warmcat/libwebsockets#1045]
I make a connection (same as my other issue)

lws_client_connect_info ccinfo;
memset(&ccinfo, 0, sizeof ccinfo);
ccinfo.address = host.c_str();
ccinfo.context = context;
ccinfo.host = host.c_str(); // content of host header
ccinfo.path = "/index.html"; // what url to hit
ccinfo.port = port;
ccinfo.protocol = protocol[0].name;
ccinfo.ssl_connection = 0;

connid = lws_client_connect_via_info(&ccinfo);

And on my server I get two connections. I also see this in the logs of the client. Presumably there are two connections being made?

[2017/10/06 10:44:10:5877] NOTICE: lws_client_connect_2: 006D49A0: address we.example.lan
[2017/10/06 10:44:10:6013] NOTICE: lws_client_connect_2: 006D49A0: address we.example.lan

Again, what am I missing?

**Comment by lws-team** [comment]
No... client connection proceeds asynchronously.  We try the connect...

https://github.com/warmcat/libwebsockets/blob/master/lib/client-handshake.c#L293

... since it's a nonblocking socket, it returns immediately with `EINPROGRESS` and will notify us by changing its poll wait when it succeeded or failed.  At that time, we come back to lws_client_connect_2() to retry the `connect()` and get the result of the connection attempt.
