### ISSUE TITLE
LWS_SERVER_OPTION_EXPLICIT_VHOSTS and lws_service before lws_create_vhost

### ISSUE THREAD

**Issue by sejvlond** [warmcat/libwebsockets#1049]
Hi,
I have a context with `LWS_SERVER_OPTION_EXPLICIT_VHOSTS` option. Then I start a separate thread in which `lws_service` is called in a loop. Then a different thread creates a vhost (when some event is received or so) with `lws_create_vhost`.

I'm getting segfault on line 178 in lws-plat-win.c
```
context->service_tid_detected = context->vhost_list->
			protocols[0].callback(&_lws, LWS_CALLBACK_GET_THREAD_ID,
						  NULL, NULL, 0);
```
Because vhost_list is currently empty (`null`). I understand that lws is not thread safe, but is it forbidden to start polling (lws_service) without any vhost? And what is going to happen when I remove the last existing vhost `lws_vhost_destroy`?

**Comment by lws-team** [comment]
Lws isn't threadsafe... only one thread can call lws apis (with the exception of `lws_callback_on_writable()`).

So what you describe is a problem, you can't have one thread doing service and another thread adding a vhost, because there is no locking in lws.  You can serialize your vhost creation inside the service loop thread, so it's either doing service or creating your vhost, never both at the same time.

The other plats like -unix and -esp32 actually check for `!context->vhost_list` at the top and return the service attempt, -win is missing that.  I added it in on master.  I also eyeballed all other uses of `context->vhost_list` and AFAICT they are safe.

In most cases the last vhost is destroyed when the context is destroyed.  But, it should be legal to destroy the last vhost dynamically too (not from another thread...).  If anything breaks let me know.
