### ISSUE TITLE
Add memory pool or other memory manager?

### ISSUE THREAD

**Issue by xmanmax** [warmcat/libwebsockets#1050]
Hi, I see lws used **_malloc/free_** to manage memory under linux platform(version v2.3 stable). You know , in libc , free will hold memory with it`s "free block list ", not give memory back to OS immediately. so, if we have a mount of ws connections, or high concurrency connections, memory will increase too much ,and will not release(free will be invoked, but memory not give back to OS really) even all connections closed, and this issue can not be found by valgrind memory-check or massif, but can be found by top command.
so, can lws add a memory pool or other memory manager? Do you have any suggestion for this?
T&R

**Comment by lws-team** [comment]
Lws already has the ah pool concept, and you can limit the number of simultaneous fds.

You can replace lws's allocator

https://github.com/warmcat/libwebsockets/blob/master/lib/libwebsockets.h#L5063

Because of the first two reason though, which restrict the max allocation so that it will tend to reuse what was freed before, generally I don't think this will be a problem in most cases.  In the cases that care about it the most like ESP32, they use a heap that returns back memory directly to the system global heap, plus or minus lazy garbage collection.  So I think it's out of scope for lws, and if it makes trouble for you first move should be put your own allocator in place of your libc one.
