### ISSUE TITLE
Problem with client requests to slow servers on windows

### ISSUE THREAD

**Issue by Assert1** [warmcat/libwebsockets#1054]
hi, i am using lws as a client, and have some troubles with slow servers.

Scenario:
1. Client connects and makes a POST request...
2. Server thinking about this request for 10-20 seconds...
3. Then transmits a reply and closes this connection.

Result:
LWS_CALLBACK_RECEIVE_CLIENT_HTTP never called, but the data actually recived (see wireshark log)
LWS_CALLBACK_CLIENT_CONNECTION_ERROR called only sometimes.
In case of invalid content length in the client POST request, LWS_CALLBACK_CLOSED_CLIENT_HTTP is never called.

latest master, msvc2015, os win10

**Comment by Assert1** [comment]
Probably this delay is induced with something inside lws, test server should respond imidiatly...

**Comment by Assert1** [comment]
[log.txt](https://github.com/warmcat/libwebsockets/files/1380768/log.txt)
[lwstest.cpp.txt](https://github.com/warmcat/libwebsockets/files/1380769/lwstest.cpp.txt)
[wireshark.pcapng.txt](https://github.com/warmcat/libwebsockets/files/1380770/wireshark.pcapng.txt)

**Comment by Assert1** [comment]
I am increased context timeout up to 60 sec, but nothing changes.
[wireshark1.pcapng.txt](https://github.com/warmcat/libwebsockets/files/1381170/wireshark1.pcapng.txt)
[log1.txt](https://github.com/warmcat/libwebsockets/files/1381171/log1.txt)

**Comment by lws-team** [comment]
I will look at trying to reproduce this shortly.

**Comment by Assert1** [comment]
Any progress?

**Comment by lws-team** [comment]
No.

**Comment by lws-team** [comment]
So looking at your log, as you say the cause of death is the server hung up on us (closed the connection his side) after we sent the POST.  We responded to that with LWS_CALLBACK_CLIENT_CONNECTION_ERROR as we should.

```
[2017/10/13 02:29:41:8015] DEBUG: lws_set_timeout: 00C2B760: 20 secs
[2017/10/13 02:29:51:8635] DEBUG: Server connection 00C2B760 (fd=488) dead
[2017/10/13 02:29:51:8635] INFO: closing conn at LWS_CONNMODE...SERVER_REPLY
[2017/10/13 02:29:51:8640] INFO: reason: Peer hung up
CLIENT: LWS HTTP client session 00C27CE0, connection error: Peer hung up.
```

Looking at your wireshark log, the server sat there for (exactly) 10s after we sent the POST, before sending a reply okaying it and hanging up on us.

I adapted your test c++ to work on Linux (I do not have windows), which was surprisingly easy (remove windows.h, add `#include "string.h"` and `g++ lwstest.cpp  -lwebsockets`).  At first he always timed out, because the serverside delay has risen to 25s since your tests above.  I added `info.timeout_secs = 40;` and he works fine.  I tried him 10 times in a row and he gets the reply properly every time.

I would guess this is a platform difference around POLLHUP timing, windows does not have a proper `poll()`, we have to fake one up.  I add this in ./lib/client.c on master

```
@@ -350,10 +349,12 @@ client_http_body_sent:
                break;
 
        case LWSCM_WSCL_WAITING_SERVER_REPLY:
-
-               /* handle server hung up on us */
-
-               if (pollfd->revents & LWS_POLLHUP) {
+               /*
+                * handle server hanging up on us...
+                * but if there is POLLIN waiting, handle that first
+                */
+               if ((pollfd->revents & (LWS_POLLIN | LWS_POLLHUP)) ==
+                                                               LWS_POLLHUP) {
 
                        lwsl_debug("Server connection %p (fd=%d) dead\n",
                                (void *)wsi, pollfd->fd);
```

does it make any difference on windows?

**Comment by Assert1** [comment]
I've made some expiriments with timeouts and increased response time on the server, do not notify you and not returned to 10 sec, sorry. But said that the context timeout was increased to 60 sec in test app...

Probably this is a windows only problem, yes, made a change as above. And deployed our software to testers, who can stably reproduce (i can do this only from time to time).

Soon I'll report the results, thank you.

**Comment by lws-team** [comment]
> do not notify you and not returned to 10 sec, sorry.

It didn't make trouble, I mentioned it just because I was trying to note everything I saw.

It seems a race between POLLHUP and last POLLIN data, if the suggested patch doesn't solve it, it will need debugging in that area (and I do not have windows...).  The related windows-specific code in in lws-plat-win.c around line 238, handling the result from `WSAWaitForMultipleEvents()`.  It looks like this code

```
			if ((networkevents.lNetworkEvents & FD_CONNECT) &&
				 networkevents.iErrorCode[FD_CONNECT_BIT] &&
				 networkevents.iErrorCode[FD_CONNECT_BIT] != LWS_EALREADY &&
				 networkevents.iErrorCode[FD_CONNECT_BIT] != LWS_EINPROGRESS &&
				 networkevents.iErrorCode[FD_CONNECT_BIT] != LWS_EWOULDBLOCK &&
				 networkevents.iErrorCode[FD_CONNECT_BIT] != WSAEINVAL) {
				lwsl_debug("Unable to connect errno=%d\n",
					   networkevents.iErrorCode[FD_CONNECT_BIT]);
				pfd->revents = LWS_POLLHUP;
			} else
				pfd->revents = (short)networkevents.lNetworkEvents;
```

EITHER gives you POLLHUP or event indication, it should OR POLLHUP on to the other network events I think...

**Comment by Assert1** [comment]
Thanks, i will check... another guy (who can stable reproduce) was already debugged this problem, but do not find a solution. The result was "a racing condition somewhere"... maybe this can help us...

Another problem, LWS_CALLBACK_CLOSED_CLIENT_HTTP is not called in case of timeout. So it is not possible to detect such situation and test app run for a while. I've made a fix for this before by ourself, but lost it with latest update, need to debug again... ay be it is better to ake another issue about this?

**Comment by lws-team** [comment]
With the patch I mentioned before (on master), if you show lws POLLHUP and POLLIN together, he will just take care of the POLLIN.  POLLHUP state is sticky, the connection will still be dead next time, so he will come back after the next "poll()" just with POLLHUP, and lws will close the connection.

I also added a patch on master modifying the code I pasted above as I suggested, but since the code is windows-specific, I can't test it.  At any rate, both those changes on master together may change the situation, if we understood what the problem is.

Lws is actually calling back about the close, but to LWS_CALLBACK_CLOSED.  I also added some changes on master that fix the callback ordering, you will get a CONNECTION ERROR and CLOSED_CLIENT_HTTP now.

**Comment by Assert1** [comment]
Even first patch resolved the problem, i think because this racing condition exists only in one tick, when the server reply and FIN are recived at once, so connection closure next time (after reply processing) is legal. Second patch looks strange for me, but you know better what to do. We will test current master after the second patch, to be sure if everything is ok. Thank you.

**Comment by lws-team** [comment]
Hmmm if I understood it (admittedly doubtful), the first patch alone, prioritize POLLIN in the case of POLLIN && POLLHUP,  can't fix it, because the windows platform stuff without the second patch never issues POLLHUP and POLLIN at the same time.  Anyway both patches I think are necessary are on master.

**Comment by Assert1** [comment]
By the way, nothing changed after the second patch, so only first patch was enought and fixed this problem. I am really sure. It was stably reproducable on some machines before, and gone after. Anyway it is working with latest master too, so we can close this as resolved. Thank you very much!

**Comment by lws-team** [comment]
Well, good :-)
