### ISSUE TITLE
Writing structs from server using stand-alone plugin?

### ISSUE THREAD

**Issue by GordonMadden** [warmcat/libwebsockets#1055]
I ran across Issue #891 while working on modifying a stand alone plugin, and then found the branch for 2.2-stable, but was not able to find the patch. Where are the patches located?

Also, it looks like it's not possible to write a struct during server callback. All the examples I have seen show a single piece of info being sent. Is it possible to do multiple writes during a callback or are sequential callbacks needed to send out the struct one member at a time? What is the best way to set this up? I have a struct containing GPS data to send out every second.

```
//------------------------------------------------------------------------------
// Send update data to GUI
//------------------------------------------------------------------------------
	case LWS_CALLBACK_SERVER_WRITEABLE:

		// Read GPS info from serial device
		getGpsData();

		// Write GPS data to GUI
		n = lws_snprintf( (char *)p, sizeof(buf) - LWS_PRE, "%f", USE STRUCT HERE? );
		m = lws_write(wsi, p, n, LWS_WRITE_TEXT);
		if (m < n) {
			lwsl_err("ERROR %d writing to di socket\n", n);
			return -1;
		}
		break;
```
Thanks!

**Comment by lws-team** [comment]
Ehhh that's a lot of questions...

 - Any change that is generally useful also goes into master, you don't have to use v2.2-stable to get the patch mentioned in the issue, v2.2-stable or later will have it

 - You can see history on a branch with github by clicking on Code  then xxxx Commits at the top of the page.  If you select v2.2-stable first, you will find this

https://github.com/warmcat/libwebsockets/commit/fe45fe186059519a456e7c4f62bf657eea388cdf

Master branch version has this too

https://github.com/warmcat/libwebsockets/blob/master/plugin-standalone/CMakeLists.txt

 - You say

>  it looks like it's not possible to write a struct during server callback

If you want to write binary data, you can do so with LWS_WRITE_BINARY and prepare the buffer (allowing for LWS_PRE...) with memcpy.  However structs in C if you are unwary will differ between platforms, both native type sizes like int and endianness will depend on the platform.  And, you have to deal with BINARY ws messages differently in the javascript, using ArrayBuffer and typed accessors on that.

For those reasons, unless the struct data is large like audio or video etc, most people encode the struct in JSON and send that as a ws TEXT message, converting native typed data to strings.  JS makes it easy to eat and access JSON elements and arrays.  You can do it how you feel is best but I use JSON for such things if I understood you.

 - It is not legal to do multiple writes per callback, because at any point the kernel may decide it won't accept everything you want to write.  lws will react by buffering the data for you, and conceal any more writable callbacks until the buffer is drained automagically.  If it's already doing that for you because the connection was choked in the first lws_write() and you try to pile on another lws_write(), it will fail the connection.  So just one lws_write() per writable callback.

If your "struct" or JSON you want to write is reasonably small, like a couple of KB, you can just use lws_sprintf() once or sequentially to put it in one buffer, and send that using one lws_write(), job done... even if it happened the kernel wouldn't accept it all at once, lws will deal with it invisibly for you and only call you back as writable again when that was all handled.  If the "struct" or JSON you want to send is kind of open-ended in size, you can use ws CONTINUATION and a small state machine to stage sending the parts of it sequentially.

You can see an example of sending an open-ended list part by part here

https://github.com/warmcat/libwebsockets/blob/master/plugins/protocol_lws_status.c

notice how the single message (it turns up in the JS as one seamless message) is cut into ws fragments using LWS_WRITE_TEXT, LWS_WRITE_CONTINUATION and LWS_WRITE_NO_FIN according to if it's the first fragment of the message, the middle fragments or the last.

**Comment by GordonMadden** [comment]
Thanks for the advice.
I can successfully send an integer or a string, but server init fails (have to restart Linux) when I send a JSON string. The string I am sending is a simple version of the larger, comma delimited one I want to use for sending GPS data:
**{ "counter" : 100 }** (if counter happened to equal 100)

```
strcpy( gpsString, "'{ ");
strcat( gpsString, " \"counter\":");
sprintf( temp, "%d", gpsData.counter );
strcat( gpsString, temp );
strcat( gpsString, " }");
```
**Sending out the string from the standalone plugin:**
```
n = lws_snprintf((char *)p, sizeof(buf) - LWS_PRE, "%s", gpsString  );
m = lws_write(wsi, p, n, LWS_WRITE_TEXT);
if (m < n) { 
    lwsl_err("ERROR %d writing to di socket\n", n);
    return -1;
    }
break;
```

**Receiving the text message in "test.html"** (from libwebsockets files)
```
 var socket_gps,
        gps_string,
        counter;
    
    if (use_lws_meta)
	    socket_gps = lws_meta.new_ws("", "gps-rcvr-protocol");
	else
	    socket_gps = new_ws(get_appropriate_ws_url(""), "gps-rcvr-protocol");
	try {
	    socket_gps.onmessage =function got_packet(msg) {
            gps_string = JSON.parse( msg.data );
            document.getElementById("counter").textContent = gps_string.counter + "\n"
		} 
	} catch(exception) {
	    alert('<p>Error' + exception);  
	}
```

**And then presenting the data on the web page:**
```
<span  style="font-size:12pt;">Counter: <div id=counter style="font-size:12pt;"> </div></span>
```
**I am not sure what is causing the launching of LWSWS to fail. I get this output after ./lwsws:**
```
lwsws[2588]: created client ssl context for localhost
lwsws[2588]: ERROR on binding fd 21 to port 7681 (-1 98)
lwsws[2588]: init server failed
lwsws[2588]: Failed to create vhost localhost
lwsws[2588]: /etc/lwsws/conf.d/test-server(58): parsing error -23: Parser callback errored (see earlier error)
lwsws[2588]: Context creation failed

```
The above blurb mentions the conf.d file, but it doesn't fail any other time (no changes).
From your last post to me, it sounds like I can send a whole struct during a write as long as it is formatted as JSON text. Please let me know where I am going wrong with my set up.

Thank you!

**Comment by lws-team** [comment]
1) If lwsws experiences a fatal signal like a segfault, it spins waiting for you to attach a debugger if it didn't start under one.  Since your plugin code runs in the lwsws process, it means a crash in your plugin will also do this; lwsws itself is pretty stable so this likely means "your plugin segfaulted".

2) Since lwsws in that state never exited, it still holds a socket bound to each vhost listen port.  Starting a second instance of lwsws will fail trying to bind to the same listen ports

```
lwsws[2588]: ERROR on binding fd 21 to port 7681 (-1 98)
```

3) You could nuke the first, crashed lwsws with `killall -9 lwsws` and then the second lwsws could start, since the guy who had the listen ports is then gone.  But the underlying issue is a crash bug in the plugin so that won't help; the second instance will crash for the same reason.

4) See the note at the end of README.lwsws.md about debugging lwsws with gdb.  You can either start lwsws under gdb

```
 $ gdb -ex "set follow-fork-mode child" -ex "run" --args /usr/local/bin/lwsws
```

or you can find out the PID of the hung lwsws by using top and seeing the PID of the process that is at 100%, or depending on your logging it may show the PID on lws log lines.  Then you can dynamically attach gdb with `gdb -p PID`.

5) If you don't have any cross-gdb your choices are a) cross-build it, or b) try to dodge cross-building gdb by debugging your code by sticking lws_notice() liberally in there and seeing how far it gets, then using `killall -9 lwsws` each time you retry.  For simple code 'debug by printf' is usually ok.  But ultimately you likely want to have gdb around.

6) To get debugging symbols in the plugin or lib / lwsws, give `-DCMAKE_BUILD_TYPE=DEBUG` to CMake, opposite is RELEASE.

7) strcpy / strcat is fragile in a few ways but mainly it doesn't take care about buffer overflow.  Somethimes you know it cannot overflow, but still, why use two different methods?  I really reccomend creating the JSON inside one or more `lws_snprintf()` which will never write past what you tell it and will always give you a terminating NUL; it also auto-advances your pointer to how much was written so you can stack them.  Eg

https://github.com/warmcat/libwebsockets/blob/master/plugins/protocol_lws_status.c#L133
