### ISSUE TITLE
In multithread server it will cause CPU usage 100%

### ISSUE THREAD

**Issue by daishenghao** [warmcat/libwebsockets#1056]
I use libwebsockets to create a server.

In multithread server it will cause CPU usage 100% in sometimes.

When I use lws_service, I set the timeout is 2ms.
`lws_service(context, 2);`

If the timeout_ms is to low so the CPU is in high usage?
And what the right timeout_ms value can I use to be a server?
Thanks!

**Comment by lws-team** [comment]
> In multithread server

What does that actually mean?  You can only call lws apis from one thread, since it is a singlethreaded library.

The concept about "service" only applies to the default poll() event loop.  The `timeout` there is the amount of time you will spend idle if nothing in the poll() wait needs any service.  So this timeout number could be quite large, like 500ms... if anything needed service before, it will service it and exit, so a busy system does not wait in poll() at all.  If nothing needed service, your CPU will idle for 500ms.

Why do you need it to be only 2ms?  It will wake up and go around the service loop at 500Hz all the time then.

What platform is this, and lws version?

**Comment by daishenghao** [comment]
I use the  libwebsocket V2.3.0.
And the websocket server running in windows server 2012.

It may most have  5000 connections to my websocket server(use libwebsockets v2.3.0) at the same time.
I am unfamiliar with libwebsockets, and worried about the speed of server. So the set the timeout_ms so low.

I know the libwebsockets is in Cocos2d-x
[https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/network/WebSocket.cpp](url)
It set the timeout_ms to 2ms when use lws_service.
And It is use in client............

Then I realize that I am use it in server, It is different.
So I want to get the right timeout_ms int lws_service.

**Comment by lws-team** [comment]
No, the timeout should be unrelated.

You could set it to 100s, it should work fine... but lws has some jobs it needs to do once per second, so you should make this poll() timeout below 1s.  lws checks to see if it's time to do the jobs every time you re-enter `lws_service()`.  For that reason, 500ms is a good default choice, on an idle system it just means wake up twice a second which is almost nothing.

The point is this timeout only applies on an idle system.  If your system is busy, the poll() exits the moment it sees a connection has an event, it doesn't wait for the timeout at all then.  The timeout only applies when no connection needs service.

If you will have a busy server, you might consider trying libuv event loop (-DLWS_WITH_LIBUV=1 at cmake... if you installed libuv at c:\assets, you would also give cmake -DLIBUV_INCLUDE_DIRS=C:\assets\libuv\include -DLIBUV_LIBRARIES=C:\assets\libuv\libuv.lib ) instead of the default poll() one.  This removes the idea of a "service" loop completely and is more scalable.  But you need to change your code a little bit to follow test-server-libuv.c.
