### ISSUE TITLE
mbedTLS context

### ISSUE THREAD

**Issue by pparadzik** [warmcat/libwebsockets#1057]
After building with mbedtls support, function ```lws_get_ssl``` returns openssl context (of mbedtls wrapper) instead of mbedtls one. Is this intended behaviour? I want to get rid of openssl completely on the client side, but this way I must have dependency on it.

**Comment by lws-team** [comment]
That way the actual backend in use is hidden by lws... it's probably what we want.

There's no dependency on openssl created by that though, unless I miss your point.  That struct is defined by fake-openssl structs coming from the wrapper.

What are you trying to do with it?

**Comment by pparadzik** [comment]
I'm calling functions like ```SSL_get_peer_certificate``` using that context on the client side and everything works well when building with openssl support. On the other hand, when building with mbedtls, I still get the same context, so in order to call ```SSL_get_peer_certificate``` I need to have access to those wrapper functions from the client (which I don't) or include openssl in the client. Am I missing something here?

**Comment by lws-team** [comment]
We can't just export `SSL_` names from lws because we will clash if linked to real OpenSSL by some other lib or the app itself... it's not really a good idea for lws to "become OpenSSL" for the link.

The choices seem to be add an api to get the "real" backend SSL object, or add wrappers that hide everything, like `lws_SSL_get_peer_certificate()`... it calls through to the real OpenSSL one, or the wrapper one depending on how lws was built.  Is this just one or two apis you need or a pile of them?

**Comment by pparadzik** [comment]
This is what I currently use:
```
SSL_get_peer_certificate
SSL_get_verify_result (and return values like X509_V_OK)
X509_get_subject_name
X509_NAME_get_text_by_NID
X509_free
```

**Comment by lws-team** [comment]
I think it's a dead loss exposing the wrapper pieces directly, it requires like an lws_X509 type and there will be no end to it.

Actually what you are doing seems only to be fishing a string from the client cert... that sounds like something we can provide a lws helper for, like lws_ssl_client_cert_get_subject(wsi, buf, len) or so.  Would you be willing to provide a patch that moves your OpenSSL version into lws like that?

In the medium term I think the wrapper will have to be converted into native mbedtls support and will go away... the upstream for the wrapper is ignoring the patch I sent for 5 weeks now and there are several other local fixes we carry on that

https://github.com/espressif/esp-idf/pull/980

The point is it seems not worth adding any more mbedtls support via the wrapper, but currently add it with `#if defined(LWS_WITH_MBEDTLS)` and use mbedtls directly there.

**Comment by pparadzik** [comment]
I agree that exposing the wrapper doesn't make sense. As for the patch, I'll see what can be done.

**Comment by lws-team** [comment]
I just pushed a patch on master adding an lws api to query things from the peer TLS cert, independent of the TLS backend.  Currently it supports fetching

```
       LWS_TLS_CERT_INFO_VALIDITY_FROM,
       LWS_TLS_CERT_INFO_VALIDITY_TO,
       LWS_TLS_CERT_INFO_COMMON_NAME,
       LWS_TLS_CERT_INFO_ISSUER_NAME,
       LWS_TLS_CERT_INFO_USAGE,
```

There's a union to take the results, dates come as a time_t, names as strings and usage flags are an unsigned int.  If this doesn't provide everything, it at least establishes a nice minimal + generic way to add more things.

**Comment by pparadzik** [comment]
That's great news, thanks.

**Comment by lgammo** [comment]
Okay, how do you propose I obtain the public key of the peer certificate? Or information about the chain of certificates?

**Comment by lws-team** [comment]
If there's some other info you want to extract from the certs, extend the api as mentioned on this and send me a patvh that works for both mbedtls and openssl.

**Comment by lgammo** [comment]
I believe I need the entire certificate passed to another library. Something like SSL_get_peer_certificate will work except I don't have access to it according to what you said earlier.

**Comment by lgammo** [comment]
On a separate note: is there a reason why lws_get_ssl() is not defined when LWS_WITH_MBEDTLS is defined? 

In libwebsockets.h it is surrounded by:
#if defined(LWS_OPENSSL_SUPPORT) && !defined(LWS_WITH_MBEDTLS)
...

The actual code in lib/libwebsockets.c has it surrounded by:
#ifdef LWS_OPENSSL_SUPPORT
...

Obviously, using lws_get_ssl() when mbedTLS is enabled causes a warning about an implicit declaration of function.

**Comment by lws-team** [comment]
Take a closer look at how the existing cert query stuff is implemented in lws.  Openssl and mbeftls have completely different apis even for x509 related things, so you need to implement the same query once for openssl down `lib/tls/openssl` and again down `lib/tls/mbedtls`.  There, you have access to everything lws has access to.

Lws uses a thin and patchy compat layer from espressif to make most ssl operations look vaguely like openssl apis.  But even so we have to implement all uses segregated down `lib/tls/openssl` and `lib/tls/mbedtls` because of fundamental differences between the tls libs.

So "why is there no SSL for mbed" is because mbedtls isn't openssl.  It's mbedtls.

**Comment by lgammo** [comment]
Right, I should have said it another way: Should the actual code in lib/libwebsockets.c be surrounded by:
#if defined(LWS_OPENSSL_SUPPORT) && !defined(LWS_WITH_MBEDTLS)
just like the header file?

**Comment by lws-team** [comment]
Well... probably.  It's mainly OK because we typedef `lws_tls_conn` to something other than SSL in case of mbedTLS, so build doesn't blow up.  After some thought during the mbedtls implementation running around trying to fake the mbedTLS pointer to have all apis like OpenSSL is a fruitless task we don't have to get into.  So the api declaration is not available in the .h for mbedtls.  Using that api is explicitly for openSSL builds of lws, it's not recommended even then, since if the usage is generally desirable it's better to add an accessor in lws that acts the same regardless of the tls backend.

As you say not much point having it exist then in an mbedtls build.  I pushed a patch on master following what you wrote above.
