### ISSUE TITLE
Compilation error in tag v2.4.0

### ISSUE THREAD

**Issue by aSebastianMueller** [warmcat/libwebsockets#1061]
I checkout tag v2.4.0 with last commit fcf5b2c25a580189bbad955815adac8dd398b612

Configuration:
 -DLWS_WITH_SSL=0 -DLWS_WITHOUT_DAEMONIZE=0 -DLWS_WITHOUT_TESTAPPS=1 -DLWS_WITHOUT_DEBUG=1 -DCMAKE_BUILD_TYPE=DEBUG -DLWS_WITHOUT_CLIENT=1

Error in file daemonize.c line 129: lock_path = lws_malloc(n);
The second parameter is missing.
Adding any string fixed it. e.g. lws_malloc(n, "HONK");
No other compilation issue found with my configuration.

compile output:
/libwebsockets/lib/server/daemonize.c: In function ‘lws_daemonize’:
/libwebsockets/lib/server/daemonize.c:129:27: error: macro "lws_malloc" requires 2 arguments, but only 1 given
   lock_path = lws_malloc(n);
                           ^
/libwebsockets/lib/server/daemonize.c:129:15: error: ‘lws_malloc’ undeclared (first use in this function)
   lock_path = lws_malloc(n);
               ^
/libwebsockets/lib/server/daemonize.c:129:15: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [CMakeFiles/websockets.dir/lib/server/daemonize.c.o] Error 1

**Comment by lws-team** [comment]
Thanks... well... it's a bug :-)  None of the CI things test with daemonize enabled and I missed it.  lws_malloc() and variants take a reason string now.  When compiled in debug mode, it will send a debug log with the amount and reason whenever it allocates anything. 

I pushed a fix on master and v2.4-stable... since daemonization is off by default I think it's not worth retagging it.  v2.4-stable will eventually produce v2.4.1 etc.
