### ISSUE TITLE
Threading in LibWebsockets

### ISSUE THREAD

**Issue by zhouwangzw** [warmcat/libwebsockets#1076]
Hi,

This is indeed not an issue, but a couple of questions for clarification. I read that libwebsockets is not thread-safe, but would it be possible to use LibWebsockets in the following scenarios:
1) Can a process or a thread (as WS client) opens and maintains multiple WebSocket connections (to the same or different servers)? 
2) Can a client send and receive data simultaneously, or send/receive has to be serialized? The README.coding.md says that "Only send data from the LWS_CALLBACK_SERVER_WRITEABLE callback", and libwebsockets uses a single-threaded event loop. 
3) If a process can have multiple active WS connections, is it possible to have a single call, like lws_service_fd(), to service any waiting events on any active WS connections?

Thanks in advance!

**Comment by lws-team** [comment]
1) Yes, you can be serving to as many clients as you like while also being a client connected to as many servers as you like, all in the same event loop / lws context.

2) "Only send from WRITABLE" is not directly related to receive.  In normal programming, the thing that produces data is the "master" in the system.  But in network programming, the sink for the data is master.  If he or the network between you and him cannot accept any more data at the moment, you should not produce any more data for him, otherwise you are just wasting local memory buffering it.  If the design is that you forward incoming data for him, you should only accept RX when you can produce more data for him; lws provides RX flow control api to allow the state of the guy you are sending to.  The goal is to buffer as little as possible by producing it "just in time".  (see the mirror protocol

https://github.com/warmcat/libwebsockets/blob/master/plugins/protocol_lws_mirror.c )

However notice this is about regulating production of new data to send in lws.  The reason the kernel indicates a connection cannot accept any more TX is usually because the tcp window is already full and as much data as the kernel is willing to buffer is already taken on the connection, ie, it's not that it has run dry of things to send it's that we are full of things that haven't been received by the far end yet.  The buffered data is sent out in the background by the kernel, and the window is consumed by the far end according to network conditions, "truly simultaneously" if your machine is SMP .  When the far end send ACKs, space in the window opens up and lws will be told the connection is writable again and can produce new data to send there.  So typically when sending bulk data, when lws does write more data it is "topping up" the window, not delaying data because everything has run dry.

3) By default lws works with a poll() event loop.  You must enter the poll() loop repeatedly, which you can do with `lws_service()`.  When something wakes it from waiting in poll(), lws will service each of the connections with pending events itself.

However you can also use lws with one of the libev, libuv or libevent event libraries.  These have an "event loop" concept that calls back into lws when something needs servicing.  Notice these event loop libraries all share the single-threaded, nonblocking approach of lws.

**Comment by zhouwangzw** [comment]
@lws-team  Thanks for your prompt response. 
Regrading 2, if not taking flow control into consideration, is it safe that a lws client has one thread that receives data from the server, and the other thread that sends data to the server via the same WebSocket? And is it safe if multiple threads are calling the Send method on the same WebSocket simultaneously? 

Thanks,
Zhou

**Comment by lws-team** [comment]
... no.  What do you think "multiple threads are calling Send method on the same websocket" would even do?  Websockets itself doesn't work like that.  It can only send one message at a time on each socket.

If you mean 'because I have infinite memory (and programming is hard!) I don't care to regulate sending and expect everything to be buffered my end no matter what the receiver does', use a different library.

**Comment by zhouwangzw** [comment]
Thanks for clarification. I just want to understand whether the lws library supports concurrent Send or not. If not, I need to serialize send operations at a higher level.

**Comment by lws-team** [comment]
Websockets itself only supports sending one message at a time.

"I want to send stuff" isn't really the heart of it, it is "I want the peer to receive stuff".  If you think about it that way you'll realize that with a peer on a slow connection, or a peer on a fast connection, or a peer where the throughput fluctuates, you anyway have to decouple what your thread wants to send from the guy sending it.

So you should leave lws alone in one thread, I don't know your exact need but usually your other threads can feed a ringbuffer with your own locking, and the connections in the lws thread use the data in the ring at their own speed, again with your own locking for the ringbuffer.

The mirror plugin I pointed to does this, and uses the `lws ring` abstraction which supports ringbuffers with one head, but as many tails as you like (ie, one tail per connection) to facilitate this.
