### ISSUE TITLE
File Upload times out after 60 seconds

### ISSUE THREAD

**Issue by Brian-Rader-Logikos** [warmcat/libwebsockets#1079]
We are prototyping a fairly simple embedded HTTP server to upload large files.  The prototype was working with v2.3, but broke with v2.4.

Part of the problem appears to be from a hard coded ah timeout on line 1049 of lib/service.c where it checks time elapsed since ah->assigned < 60.  There is a context creation setting called timeout_secs_ah_idle that seems to be what should have been used.

Bigger than that is that it is timing out at all since I can see that it is still receiving and saving the file data right up until the timeout.  It is my understanding that this timeout is for if the client is idle.  If the client is actively sending file data then it is not idle.

**I'm trying to evaluate this for use by a customer and this is a problem.**  It may be possible to stay with v2.3, but there may be other needs to prevent that.

**Comment by lws-team** [comment]
ah can be a scarce resource, so they're protected by a sanity timeout.  (In fact on v2.4 there are new optional PEER_LIMITS where you can restrict connections and ah by IP too.)

I get it that 60s isn't enough for your case.  60s was supposed to be a sanity-check timeout in addition to the settable timeout, which is why it's just a constant.  Occasionally on libwebsockets.org, I get a bot holding an HTTP connection open permanently and unexpectedly tying up an ah that way.  But I guess for large files, or slow systems where it flashes the file as it receives it, it might not be a good choice of being on the insane side of the sanity check.

> timeout_secs_ah_idle that seems to be what should have been used

Yeah... it is used elsewhere.  This 60s check is an additional check on top.

I changed the sanity check to be `timeout_secs_ah_idle + 60`, now if whatever you set `timeout_secs_ah_idle` to is long enough for your uploads, the sanity check won't fire either.  That change is pushed on v2.4-stable and master.
