### ISSUE TITLE
Debugging with GDB while LWSWS is running

### ISSUE THREAD

**Issue by GordonMadden** [warmcat/libwebsockets#1086]
I found your instructions for debugging projects based on LWSWS (plugins, etc.) and got my project to run using this line (path is modified for my build):
```
sudo gdb -ex "set follow-fork-mode child" -ex "run" --args /libwebsockets/build/bin/lwsws
```
But while lwsws is running, there is no "gdb" prompt in the terminal. Once I hit ctrl-C, lwsws is exited, and the gdb prompt shows up, but at that point lwsws is no longer running. **How can I use gdb while lwsws is running?**
GDB does start up (this project is built on the TS-7800-V2 board, not cross-compiled):
```
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /libwebsockets/build/bin/lwsws...done.
Starting program: /libwebsockets/build/bin/lwsws 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Root process is 4308
[New process 4311]
[Thread debugging using libthread_db enabled]
Using host libthreDo I need to make modifications to my lws CMakeList.txt file to include functions and source files?ad_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
lwsws[4311]: lwsws libwebsockets web server - license CC0 + LGPL2.1
lwsws[4311]: (C) Copyright 2010-2016 Andy Green <andy@warmcat.com>
```
And here is the exit of lwsws and the appearance of the gdb prompt:
```
lwsws[4311]:     vhost "localhost", protocol "gps-rcvr-protocol", option "status"
lwsws[4311]:     vhost "localhost", protocol "dumb-increment-protocol", option "status"
lwsws[4311]: getpwuid: unable to find uid 48
^Ckilling service processes

Thread 2.1 "lwsws" received signal SIGINT, Interrupt.
[Switching to Thread 0xb6ff0000 (LWP 4311)]
syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:38
38      ../sysdeps/unix/sysv/linux/arm/syscall.S: No such file or directory.
(gdb) 
```
I am looking into creating debug symbols (table?) which is new to me, and found a question on-line that talked about debug logging and showed some modifications to the cmake list file: https://stackoverflow.com/questions/42535181/how-to-enable-debug-logging-with-libwebsockets
**Do I need to make modifications to my lws CMakeList.txt file to include functions and source files?** I have looked at the current List file and see no mention about the files used for stand-alone plugins (which is what I am trying to debug).
Please let me know what I am missing in my debug setup. I did build lwsws with build_type=DEBUG.

**Comment by lws-team** [comment]
1) For gdb it's okay if some libs have no symbols, it doesn't affect debugging.  You won't get source level debug for them but almost always you don't care because your bug is not related to glibc internals or whatever.

2) Things that are built with debug info (-g on gcc) add it to the elf file (the executable, or .so file) where it's ignored until needed.

3) `cmake .. -DCMAKE_BUILD_TYPE=DEBUG` builds with -g, so if you build lws with that, source level debug stuff is there already in lwsws and the library.  You need to apply it also to your plugin cmake to get symbols there.

4) lwsws consists of two processes, a stub (with no sockets) that retains root and the main process that drops privileges.  This is so it can implement 'reload' functionality.  Normally the processes are created and destroyed together, but if something fatal happens, you may need to clean up any dead bodies manually, with `killall -9 lwsws`.

5) ^C / SIGINT gets sent to both processes, the root stub catches it and exits... the serving process is halted, and can be examined, but if you continue it, he will exit because his parent exited.  That's not very useful... generally I use gdb to debug segfaults and logs to debug everything else, ie, don't use Ctrl-C.
