### ISSUE TITLE
Fragmentation of Websockets

### ISSUE THREAD

**Issue by arunkvnss** [warmcat/libwebsockets#1097]
I am using libwebsockets 1.7.0 Version,And it is working fine for me tooo. I have one confusion regarding the websocket fragmentation, Libwebsocket library will automatically fragment the Application payload or else we should handle in the callback as done in fragle.c file ?

what does that rx_buffer_size meant for,is that anything like the maximum fragment can be retrieved from the tcp stream ?

**Comment by lws-team** [comment]
There are two kinds of fragmentation involved, which is why it is confusing.

 - logical websocket fragmentation.  RFC6455 says that you can mark a frame containing message data as being a CONTINUATION of an earlier, non-FIN part of the message.  In that way, you can actually make literally endless messages, with each ws fragment having a length up to 2^63 - 1.  (Of course receivers like browsers that try to put whole ws messages in memory all at once can't actually receive such things, but ws doesn't disallow it for receivers that can receive the data piecewise).  Notice that the ws link is modal, once you started a huge frame, you cannot send anything else on the link (like PONG... or CLOSE) until the frame is completed.  So huge ws frames are not a good idea.

 - tcp fragmentation.  This is simply that in a real system, you cannot throw arbitrary sized buffers on send() or write()... the OS kernel will accept some and leave the rest for you to retry sending later.  tcp itself has the concept of an MSS for a link and will also restrict what goes out to that size.  And the tcp link has the concept of a window, which shrinks when we send stuff and expands when the receiver ACKs what we sent before.  What the OS will accept to send or not is related to the state of the connection window at that time.

There will always be tcp fragmentation, you can choose whether or not to use ws fragmentation.

Lws is geared towards working closely with the system for the tcp part, with the WRITABLE callback and limits on how much lws will try to send at once (this is an implication of rx_buffer_size, on later lws there is a way to control the send size separately with the member tx_packet_size also in lws_protocols).  The system tells us when we can write some more, but there is no indication of how much we can write.  So the rx_buffer_size / tx_packet_size should be chosen that most times, it succeeds to send everything without additional buffering needed in lws.  On normal x86_64 that seems to mean ~4KB, on weak systems like ESP32 800 or 900 bytes.

In Lws you should generate what you want to write on a connection at the time it can be written on the connection, piecemeal.  This means no space is wasted needlessly buffering locally what could not actually be accepted for send at that time by the OS.

A good way to use ws fragmentation is like this:

https://github.com/warmcat/libwebsockets/blob/master/plugins/protocol_lws_status.c

each WRITABLE we send something small enough we know the OS will accept it whole.  But because we use CONTINUATION (ws fragmentation) we can create arbitrarily large messages with no fixed limit our side.

**Comment by arunkvnss** [comment]
Thanks for your sudden replay.This sounds good :) 👍
