### ISSUE TITLE
Controlling packet output frequency from standalone plugin

### ISSUE THREAD

**Issue by GordonMadden** [warmcat/libwebsockets#1099]
Now that I have LWSWS working with custom plugins, I need to control the output from one plugin that sends motor position data to a motor control board via serial communication. The data needs to go out at 120Hz and the packets are 19 bytes. I can see the packets go out to the board and the packet period is 1.6ms  (625Hz), while I need a period of 8ms (120Hz).

I thought that the uv_timer in the case statement LWS_CALLBACK_PROTOCOL_INIT would change the timing for the plugin, but it doesn't have any effect on writing out the packets.

My question is **how to control the output of the plugin to other devices or software?** I considered using a delay loop, but that is rarely good practice and I didn't want the sending of packets to be dependent on execution time of the program. I usually work with microcontrollers where interrupts can be used to control signals. I did write a separate C file that uses the SIGALRM signal and the setitimer() function from Linux to output the motor control packet at 120Hz, but I am not sure how to incorporate it into the LWSWS project. That timer function doesn't need access to the webserver, but could it be incorporated as a plugin? If not, how would I add the code to LWSWS, or conversely, how could I run the timer as main() and incorporate LWSWS as part of that project?

Thanks for your input!

**Comment by lws-team** [comment]
Well... it's nice to have a problem everything is too fast.  Plugin or not doesn't make any difference, it's not the problem.

> I thought that the uv_timer in the case statement LWS_CALLBACK_PROTOCOL_INIT would change the timing for the plugin, but it doesn't have any effect on writing out the packets.

"timing for the plugin" doesn't really mean anything... you will get a callback to the timer callback at something like the intervals you requested.  If you do your serial write there (and only there) the interval between serial writes will be kinda regulated by the timer.

But there will likely be a lot of jitter that way.  Uv timer events are serialized through the event loop, so if there are other events coming or you get eg a TLS connection that requires computation, latency for the next timer event can potentially exceed 8ms.  Because of that, the uv timer is useful for events that can absorb jitter and need to do things using the service thread context, eg, write on the network.

For a realtime task like motor control, where you are allergic to jitter or missed updates, it's more common to either spawn a dedicated thread to do it, or do it as a kernel driver.  Lws doesn't care if you spawn threads in plugins or anywhere else if they are not going to interact with the service thread or call lws apis.  But even a dedicated thread is running in userland and subject to scheduler jitter, depending on the other system load it may skip updates.  You can understand and adapt to cumulative skipped updates by checking gettimeofday() before you do the write, and if it's later than you hoped, skip sending updates until you line up with the one appropriate for the time it actually is.

If that won't fly, you need to use a kernel driver plus kernel timer to trigger it to write on serial.  Jitter should be low by comparison (although even there, depending on load and other drivers, it still exists).

**Comment by GordonMadden** [comment]
Thanks, Andy!
Great advice, as always. 
I incorporated my "SIGALRM interrupt" scheme into the motor control plugin and it works, but it is untested for all speeds, loads, etc., and I'm sure there is room for improvement.
I will look into dedicated threads and keeping track of elapsed time to make it more robust.
Thanks again for all your help!

**Comment by GordonMadden** [comment]
Thanks, Andy!
Great advice, as always. 
I incorporated my "SIGALRM interrupt" scheme into the motor control plugin and it works, but it is untested for all speeds, loads, etc., and I'm sure there is room for improvement.
I will look into dedicated threads and keeping track of elapsed time to make it more robust.
Thanks again for all your help!
