### ISSUE TITLE
Async DNS resolution

### ISSUE THREAD

**Issue by robertabcd** [warmcat/libwebsockets#1100]
I'm investigating an issue that users reporting communication being blocked for unknown reasons. I suspect it's due to slow DNS and in the library it does synchronized DNS resolution here:
https://github.com/warmcat/libwebsockets/blob/master/lib/client/client-handshake.c#L26
A quick look around in the code, I failed to find support for pluggable async DNS resolution that can replace this synchronized getaddrinfo(). Does this feature exist now or is it planned? I may be able to help building that but I'd like to make sure we're not doing duplicate work.
Thanks!

**Comment by lws-team** [comment]
Yes it does synchronous DNS resolution.

If you would like to contribute async DNS resolution, it'd be welcome.  But it's not that easy to do it in a nice way that works with the different platforms, event libraries, ipv6, and threading that will work on windows etc.

One lowlevel approach that would work everywhere is to add connection states for client (it's only really client that cares) which make the wsi use an lws RAW socket first to go out to the DNS server, cache his result, close the sockfd and then rejoin the existing client open state machine.  This is similar to how lws handles proxy connections, there are extra connection states related to it that get used if you have configured to go out by proxy.

That's probably a bit different than you were thinking, but it has a lot of advantages... platform agnostic, works on all event libraries, does not require threading.  I can help you with the lws state machine part of the implementation but not sure how best to parse the DNS server result.

**Comment by robertabcd** [comment]
Reimplementing whole DNS resolution is a bit out of what I was thinking. I'd expect this to be a huge amount of work, let alone to test it. What I'm thinking is more like providing an interface to do DNS resolution. The library calls into this interface, and implementer returns the result asynchronously (to resume the state machine).
It can default to do synchronous DNS, so platform support can be done incremental. Users can also provide their own implementation if the default one is not suitable for them. I haven't started to look at the state machine part, so I'm currently not sure about the feasibility. I'd like to hear your thought on this approach.

**Comment by lws-team** [comment]
There is at least one library that can do the parsing.  I agree it's a big job when it already has a workable (blocking) solution through the libc, but I wouldn't write it off as the more complex solution yet...

The main problem with what you're suggesting is events on the state machine to trigger it... these would come naturally if lws is also handing the DNS socket; receiving the last bit of the DNS response would be the event that moves to the next state, everything happening serialized on the same event loop.

What happens at the moment (in client-handshake.c lws_client_connect_2()) is the DNS resolution is done synchronously, then we create the socket() and add it to the event loop, and try the connect.  We later get an indication of POLLOUT on the socket telling us something happened with connect().  If it wasn't good, we may retry the connect() using the existing socket.

That flow is attempted the first time before returning from the connect() api, but because the connect() part is asynchronous, it will not get a result until later.  Because the connection mode at that time is LWSCM_WSCL_WAITING_CONNECT, when we get the POLLOUT indicating something happened on the connect(), we come back into lws_client_connect_2() during the service of the POLLOUT (client.c lws_client_socket_service())

You can create the socket and wsi first, so there is a logical connection to bind the async DNS to.  But AFAIK an unconnected client socket (one just returned from socket() alone) can't signal POLLOUT so after the async DNS completes, there is no way to trigger the connection wsi to be aware it should be serviced using normal socket events; the socket is unconnected and not in a state it can produce POLLIN/OUT (AFAIK...).

So it needs a way that the DNS can provoke "forced service", this concept already exists in lws that a wsi may need service even though there is no network event provoking it; it's used for situations like an SSL connection or extension has more data for us buffered inside it.  But if that decision is coming from another thread, which I think is what you are talking about, that somehow needs synchronizing to the main service thread.

I guess it's doable but I hope this explains the attraction of doing the DNS socket activity in the same singlethreaded event loop, even if you still don't like the idea.

**Comment by robertabcd** [comment]
Not sure if I understand it correctly. In short, you are saying the current state machine requires IO events (POLLIN/OUT) to make progress. If going with custom interface for async DNS, it would not be so feasible since it lacks IO events. So making it send DNS request would be more natural under current architecture because there will be IOs.
If that's the case, I need to do more digging on the code. (I wasn't expecting the state machine relies on IO events only.) I prefer less coupling between these protocols; well, DNS is just one protocol that does the name resolution.

**Comment by lws-team** [comment]
Yeah.  Lws also has the concept that some connections are in a state where they must get serviced by the state machine even though there is no IO event; for example if we weren't able to use all the rx from a network packet, either the TLS library and /or the compression extension may be holding buffered rx with no pending IO event associated with it because we read it all from the network but did not consume all of the processed result.  We could add the ongoing dns resolution to the list of things the 'force' service, but we have to serialize that to the event loop thread somehow.

https://github.com/warmcat/libwebsockets/blob/3626ed392d157e2e5dd287cdae889b898453c59c/lib/service.c#L729

You are right dns isn't the only resolution mechanism.  But I think for client, defaulting to blocking libc resolver like today, and then a cmake option for a direct DNS query transaction (perhaps a flag to enable using it per connection) managed and parsed by lws will be enough for most people.

**Comment by lws-team** [comment]
Just a thought... for client, if you pass lws a dotted-quad or ipv6 numeric address... calling the libc resolver should cost nothing.

So maybe we are looking at this wrong trying to make lws do it.  Just resolve the name outside lws how you like and pass a dotted quad or whatever in `lws_client_connect_info` `address`.

**Comment by lws-team** [comment]
It has been two weeks, I will take it that solving it by resolving outside of lws was the solution.
