### ISSUE TITLE
remainig packet payload

### ISSUE THREAD

**Issue by arunkvnss** [warmcat/libwebsockets#1104]
sir,Basically i confused with the amount of memory i can use for the buffer,When the fragmented messages are coming the (lws_remaining packet payload return value + current recvd length) will be ensuring the total size of the buffer to recv ?

**Comment by lws-team** [comment]
... you can continue the thread on a closed issue, I closed it because I answered it.  But it doesn't mean you can't ask a followup there.  I'll also close this when I answered it, because there is nothing for me to do about this issue except answer it, but you can continue to post on this issue and I will see it.

> (lws_remaining packet payload return value + current recvd length) will be ensuring the total size of the buffer to recv ?

It is the right amount of space *for this ws fragment*.

However a ws *message* may consist of an unlimited number of ws fragments.

Each ws fragment may have a size up to 2^63 - 1 bytes.

*Nothing* in the ws message says the length of the whole message in the case there is more than one fragment.  If I send you a FINAL fragment with size 10KB, well, you know the message is 10KB.

But if I send you a NON-FINAL fragment with size 10KB, you have *no clue* how many more fragments I will send before the FINAL one comes to end the message.  You have *no clue* about how big each fragment will be either.  That is how the protocol is designed.

So it is highly preferable to process the message content as it comes in, in whatever size pieces in comes in, and avoid trying to store it all in one place if possible.  Because with ws you don't know the message size beforehand.

If it's just your messages you have to deal with, you can put the total message length if known at the beginning of the first fragment, and parse it out from there when you receive it.  But it is much better if it's possible to process the message as it comes in so you don't need any large "message-sized" buffer.

**Comment by arunkvnss** [comment]
k. Thank you sir
