### ISSUE TITLE
new plugin

### ISSUE THREAD

**Issue by mdmivanov** [warmcat/libwebsockets#1119]
Hi, can you please create a new plugin IdleStateHandler that will support parameters:

readerIdleTime - an event READER_IDLE will be triggered when no read was performed for the specified period of time. Specify 0 to disable.
writerIdleTime - an event WRITER_IDLE will be triggered when no write was performed for the specified period of time. Specify 0 to disable.
allIdleTime- an event ALL_IDLE will be triggered when neither read nor write was performed for the specified period of time. Specify 0 to disable.

This functionality are present in netty.io and are very useful for monitoring connections

Maybe you don't have time to write this plugin, tell me how I can do it myself

Thanks.

**Comment by lws-team** [comment]
... that wouldn't be a plugin but a new api.

What action do you take when these events happen?

**Comment by mdmivanov** [comment]
I want to close the connection when the read time has expired and send a test message when the write time has expired

**Comment by lws-team** [comment]
You can use the existing timeout api to get the close behaviour.  Create a timeout in the future when the connection is established, and keep creating a new future timeout time each RECEIVE callback.  If no receive comes before the timeout expires, it will timeout and close cleanly.  So that half of it exists already.

The general "do something some seconds later unless I countermand it in the meanwhile", I also think it's useful.  I'll take a look at extending the existing timeout stuff for it and reply in the next day or two.

**Comment by lws-team** [comment]
Please have a look at this on master

https://github.com/warmcat/libwebsockets/commit/7d59122b5fcdc6d6339efabee27b7b0325f72708

**Comment by mdmivanov** [comment]
Thank you very much for your help, the timer work perfectly.
