### ISSUE TITLE
How to fix LWSWS slowdown after adding plugin code

### ISSUE THREAD

**Issue by GordonMadden** [warmcat/libwebsockets#1120]
I am using LWSWS in an embedded project with two plugins I created: one that sends out packets for motor control and one that processes gps input. I created both at the beginning of the project and worked on motor control first. It has a thread that spawns at init and runs in an endless loop, grabbing position data and creating packets to send to the motors. This setup works well and is very responsive.

When I added the processing of gps data to the gps plugin, **the system was noticeably slower**. When I operate the motor with the browser controls, there is about a half-second delay for the motor to start or (begin to) stop, where there was no noticeable delay before. I'm guessing that the extra traffic of processing gps sentences and relaying the info to the browser is slowing down the system.

My question is this: **Which part of the system should I try to change to make it as responsive as possible?** 

Should I add a vhost? Both the motor control and gps data are going to the same page on the browser, so it's not a question of multiple "sites". Would adding another vhost to carry only the gps plugin remove the slowdown from the motor operation?

What about processing gps data in a separate thread? It seems to work for the motor packets, but I'm not sure this is the best answer for every scenario.

Searching through the LWS API, I found this (  from lws_create_context()  ):
    _The server created is a simple http server by default; part of the
    websocket standard is upgrading this http connection to a websocket one._
Does this mean the developer is supposed to change the code or is this already something that is handled?

I will be adding to this project and would appreciate advice on how to add functionality without hindering the speed of the web server.

Thank you!

**Comment by lws-team** [comment]
1)

> When I added the processing of gps data to the gps plugin, the system was noticeably slower.

Lws uses a nonblocking, singlethreaded event loop scheme.  If there is user code that blocks, it means other events must simply wait until you return from the callback.

"Relaying the info to the browser" is not going to cause that problem assuming you are asking for the writeable callback and sending the info there... that involves returning to the event loop and the write itself is very fast before it also returns to the event loop.

So you should confirm what blocks the event loop for the missing time... I guess it's your GPS polling code just sitting there for 500ms doing its thing, blocking-style.

Assuming that is so, what you can do about it depends on the exact details of the communication.  You can indeed split it off into another thread, and add locking and triggering lws when something happened.

If it's basically monitoring the serial or waiting for events to be reported, another, better way is make the serial device participate in the lws nonblocking event loop directly using RAW FILE mode.  In your protocol init, open() and configure the serial device and "create a wsi for it" with something like

```
vhd->serwsi = lws_adopt_descriptor_vhost(lws_get_vhost(wsi), LWS_ADOPT_RAW_FILE_DESC, vhd->serial_fd, lws_get_protocol(wsi), NULL);
```

(vhd->serwsi will be NULL if it fails, and should be stored in your protocol vhd or equivalent)

vhd->serwsi acts just like a normal lws socket wsi, except it has its own callbacks to your protocol

```
	LWS_CALLBACK_RAW_ADOPT_FILE				= 63,
	/**< RAW mode file was adopted (equivalent to 'wsi created') */
	LWS_CALLBACK_RAW_RX_FILE				= 64,
	/**< RAW mode file has something to read */
	LWS_CALLBACK_RAW_WRITEABLE_FILE				= 65,
	/**< RAW mode file is writeable */
	LWS_CALLBACK_RAW_CLOSE_FILE				= 66,
	/**< RAW mode wsi that adopted a file is closing */
```

When there is some serial rx appeared, you will get a `LWS_CALLBACK_RAW_RX_FILE` where you can read from vhd->serial_fd and process it.  (This is best done with a bytewise state machine, since it will attempt to notify you as soon as any serial rx is ready).  Likewise, if you want to send something, you can call `lws_callback_on_writable(vhd->serwsi);` and you will get a `LWS_CALLBACK_RAW_WRITEABLE_FILE` callback where you can write to your serial device.

This technique eliminates all the blocking / waiting / spinning and assuming that's the only expensive thing you are doing, it will eliminate all the latencies.

2) Vhosts won't impact this... they are a way to either fold another "site" on to the same listen port cleanly, and select between them by SNI or Host: header, or to add more listen ports bound to separate mounts etc.  All wsi, no matter what vhost they are bound to, run in the one event loop.  So it's not related to blocking the event loop.

The keep everything humming respond to events quickly so you can exit the callback and return to the event loop.  Slower activities must either go outside the event loop in their own thread, or become sequenced also in the common event loop so waiting / spinning is eliminated and other events are handled instead until it's ready to do the next step.

3)

> websocket standard is upgrading this http connection to a websocket one.

Lws handles everything about that.  It's literally termed a protocol upgrade in the standards; it's just noting that as it happens all ws connections start as http and then do that protocol upgrade to transition to ws mode.
