### ISSUE TITLE
lws_http_client_read() calls lws_http_transaction_completed_client() on completed

### ISSUE THREAD

**Issue by lgammo** [warmcat/libwebsockets#1160]
I am doing an HTTP call that returns some html response (850 bytes or so). The lws_http_client_read() is called, and at the end the lws_http_transaction_completed_client() is called. That function returns -1 because I am not using the keep-alive header. However, the response is complete and I have all the data. Since in the callback I test for -1 returned from lws_http_client_read() as an indication of errors (as shown in the example code), I flag this situation as an error and never process the html response.

Perhaps I am doing something wrong, but lws_http_transaction_completed_client() should not blindly return -1 if keep-alive is not set.

**Comment by lws-team** [comment]
I am talking about master, but I think this code has been the same for a while.

> lws_http_transaction_completed_client() should not blindly return -1 if keep-alive is not set.

Hm... lws server supports HTTP/1.1 pipelined transactions, and HTTP/2 multiplexing.

But lws client only supports HTTP/1.0 no-keepalive single-shot connections (patches welcome...)

In fact `lws_http_transaction_completed_client()` is only there as a placeholder for the day pipelining is implemented for client

```
int LWS_WARN_UNUSED_RESULT
lws_http_transaction_completed_client(struct lws *wsi)
{
	lwsl_debug("%s: wsi %p\n", __func__, wsi);
	/* if we can't go back to accept new headers, drop the connection */
	if (wsi->http.connection_type != HTTP_CONNECTION_KEEP_ALIVE) {
		lwsl_info("%s: %p: close connection\n", __func__, wsi);
		return 1;
	}

	/* we don't support chained client connections yet */
	return 1;
...
}
```

It always returns 1, ie, to close the connection.

There shouldn't be a problem treating `lws_http_client_read()` nonzero return as a sign the connection is done.  Because the actual disposition of the payload is managed by `lws_http_client_read()` calling back LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ and LWS_CALLBACK_COMPLETED_CLIENT_HTTP to pass dechunked payload to your code and provide an unambiguous notice of the whole payload having been completely received.

So what actually is the problem?

**Comment by lws-team** [comment]
Well, let me know if there's a problem.
