### ISSUE TITLE
 getaddrinfo failed

### ISSUE THREAD

**Issue by estlesha** [warmcat/libwebsockets#1179]
Hello! When i try to connect your demo server and client(localhost) on i386 everything is fine, but when i try to do the same on my device based on ARMv5TEJ, i have error "getaddrinfo failed". When i try to connect to server on arm from client on i386, everything fine too. I have no idea what to do with it.

**Comment by lws-team** [comment]
Isn't this just a way to say, "name resolution doesn't work on my embedded box"?  You don't explicitly say the command that gives the error, but if it involves "localhost" can anything on the embedded box resolve "localhost", eg, `ping localhost`?  If not add an entry in /etc/hosts.  If no name resolution at all on that box, check /etc/resolv.conf.

**Comment by estlesha** [comment]
If i run testserver(arm5) on my embedded box and use testclient(i386) to connect to it from other ip it works fine.
If i run testserver on embedded box and try to connect testclient(arm5) from box like "testclient 127.0.0.1" or "testclient 192.168.1.10"(box ip), i have error "ERR: getaddrinfo failed"
Same things works fine on i386.From box i have no problem with ping 127.0.0.1, 192.168.1.10, google.com or else.

**Comment by lws-team** [comment]
Do you have a loopback (lo) network device configured on the kernel of the box?

**Comment by lws-team** [comment]
Something seems up with your loopback device on that box.  But that's not a problem with lws.

**Comment by estlesha** [comment]
i switched func getaddrinfo to gethostbyname in your lib and my problem gone

**Comment by lws-team** [comment]
A user had a similar problem with his platform (or platform libc) and contributed this cmake option

LWS_FALLBACK_GETHOSTBYNAME

**Comment by estlesha** [comment]
sorry, idk where to ask another question. so, i ask here...
When i call lws_write(...), how can i understand that writing is complete and new  data can be sent?

**Comment by lws-team** [comment]
This is one of the reasons you can only call lws_write() from the WRITEABLE callback.  If you gave lws_write() more to send than the kernel would accept at one time, lws suppresses WRITABLE callbacks until it has cleared writing the backlog in the background.

If you get a WRITEABLE callback it's only happening because lws sees no reason you shouldn't write something new, and poll() has told it the socket will accept some amount of new write into it.  So just follow the rules a) lws_write() only from WRITEABLE and b) only one lws_write() without returning to the event loop.

Look it READMEs/README.coding.md for more details.
