### ISSUE TITLE
lws_set_timer with external poll

### ISSUE THREAD

**Issue by shenchsh** [warmcat/libwebsockets#1199]
Hi,

I am using libwebsockets with external poll. But I found `lws_set_timer` cannot invoke `LWS_CALLBACK_TIMER`. Is this because I am using external poll? If yes, how could I use `lws_set_timer`?

Thanks

**Comment by lws-team** [comment]
In addition to letting it know when there is some network activity that needs servicing, ws requires that you give it some time around once a second so it can take care of timeouts (and timers, and other things).

For internal polling, lws takes care of it for you, either with event loop timers or each time you enter the service api it checks to see if it was a second yet since the last housekeeping.  But with external polling, lws gets no cpu if no network events, so you have to make time for it around once a second yourself.

For one service thread `lws_service(context, 0);` should be enough, otherwise for each service thread `lws_service_tsi(context, 0, tsi);`

**Comment by shenchsh** [comment]
Cool, thanks. Another question is how to decide the return value of a callback? I know `-1` means the connection should be closed, `0` means ok, but sometimes I see `return 1`, what does that mean?

**Comment by lws-team** [comment]
For almost all callbacks your choice is return 0 or nonzero.  So 1 and -1 have the same meaning.
