### ISSUE TITLE
SPA code to fetch json

### ISSUE THREAD

**Issue by nospamcalfee** [warmcat/libwebsockets#1204]
You have lots of code to handle "spa" sends to the server so arbitrary size POSTs work. But, if the data was POSTed as application/json I just want to get the whole body as text, but would rather let the library do the decoding and accumulating the POST - any suggestions?

**Comment by lws-team** [comment]
The reason the spa stuff is visible is it is optional.

If you look here

https://github.com/warmcat/libwebsockets/blob/master/plugins/protocol_post_demo.c#L123

it's the point the raw POST body content is coming... because it expects multipart encoded body content, it passes it through an spa to decode it into variables and file payloads.  But if that is not what your client is sending, you don't have to pass it through an spa, you can just take the raw data.
