### ISSUE TITLE
Can't reach max transfer speed on laptop+windows10 environment

### ISSUE THREAD

**Issue by ryanking8215** [warmcat/libwebsockets#1208]
I wrote a file transfer application based on libwebsockets which is C/S architecture.
Server is Linux, client can be Windows, macOS or Linux. Client can upload and download files from server.

I test the application in LAN network which is 100Mbps.
There is strange thing that it only gets around 30Mbps if the client uploads on laptop+windows10 environment. 
It is ok for desktop+windows10, and ok for laptop+windows7.
I use iperf to test the TCP bandwidth of laptop, it can reach around 100Mbps. It can't be the OS issue.

I print the interval of invoking "LWS_CALLBACK_CLIENT_WRITEABLE", it got around 16 ms which is too long. 

I have no idea about it. Thanks for your help or advice.

BTW, I use master and 2.4-stable branch both.

**Comment by lws-team** [comment]
I guess you are using the default poll() emulation for windows... what does the service loop look like in your code, in terms of the timeout... eg 	`n = lws_service(context, 50);`?  Does behaviour change if you change the timeout number?

It's also possible to use libuv event loop on windows, this uses a more advanced win32 api for the poll wait backend than `WSAWaitForMultipleEvents()`, maybe it can help.  You need cmake .. -DLWS_WITH_LIBUV=1 and some changes to the outer event loop... see test-server-libuv.c, it's simpler than it looks since you don't need any of the code dependent on foreign_libuv_loop != 0.

**Comment by ryanking8215** [comment]
Thank you for your advice.
Yes, you are right. I found behaviour of `lws_service` was different between linux and windows just now.
Invoking `WRITABLE callback` is  affected by timeout argument on windows.

**Comment by lws-team** [comment]
Hm... microsoft decided they are too special to provide a `poll()` like other Posix OS.

I think libuv might solve this for you (without affecting cpu load).

**Comment by ryanking8215** [comment]
BTW, why not use `select()` as the default implementation? As far as I know, `select()` works ok on windows...

**Comment by lws-team** [comment]
That is how it started out, but select() on windows turned out to have a really bad limitation, it dropped dead at 64 sockets.  What we have now doesn't have that limitation, but libuv is preferred.

Here's a minimal sample showing how to use libuv event loop

https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/server/minimal-http-server-libuv

**Comment by ryanking8215** [comment]
Libuv is supported just for server mode, see `LWS_SERVER_OPTION_LIBUV`, not for client mode.
I tried in client mode, but it crashed.
I will find another way to work around on windows.

**Comment by lws-team** [comment]
> Libuv is supported just for server mode, see LWS_SERVER_OPTION_LIBUV, not for client mode.

No... it's just the naming convention all the options are LWS_SERVER_OPTION.

Can you paste a backtrace for the crash?

Rather than you just hacking to a solution I would prefer to solve this for everybody, including you.

**Comment by lws-team** [comment]
Well, don't strain yourself... pasting a backtrace and helping others is a huge hassle.

Enjoy using the Free Software.

**Comment by ryanking8215** [comment]
I find libwebsockets uses libuv by using `uv_poll_xxx`.
 
From document of libuv:
```
The purpose of poll handles is to enable integrating external libraries that rely on the event loop to signal it about the socket status changes, like c-ares or libssh2. Using uv_poll_t for any other purpose is not recommended; uv_tcp_t, uv_udp_t, etc. provide an implementation that is faster and more scalable than what can be achieved with uv_poll_t, especially on Windows.
```
So there is still issue on Laptop+windows10. 

We can't say  `poll emulation` problem on windows cause this issue. Maybe or maybe not, because desktop+windows10 or laptop+windows7 is ok, and libwebsockets doesn't use `IOCP` implementation of libuv on windows, it still uses the `poll` by libuv. 

I can't figure out what effects the TCP throughput ~~~.
