### ISSUE TITLE
lws_is_final_fragment(wsi) seems to not working properly.

### ISSUE THREAD

**Issue by Triuman** [warmcat/libwebsockets#1226]
lws_is_final_fragment(wsi) returns FALSE even we get the latest fragment. I am using very recent version.

**Comment by lws-team** [comment]
Are you using permessage-deflate?  Because then the rx you are getting is divorced from the fact you may have received the last lump of compressed data from the network.  Only when you are reading the last decompressed chunk from permessage-deflate extension AND the last compressed lump had already arrived, will it tell you it's the final fargment.

**Comment by Triuman** [comment]
Well, probably not. This statement is used in Janus Webrtc Gateway project. There is only one file regarding websockets and I could not find "permessage-deflate" in it. If you would like to check here is the link;

[https://github.com/meetecho/janus-gateway/blob/fc97a5c955d308fa3cad0385cd0b3fc855f9c1b9/transports/janus_websockets.c#L991](url)

**Comment by lminiero** [comment]
Hi @lws-team, @Triuman ended here because he's getting an issue with our usage of libwebsockets here:

https://github.com/meetecho/janus-gateway/blob/fc97a5c955d308fa3cad0385cd0b3fc855f9c1b9/transports/janus_websockets.c#L991

Basically, in `LWS_CALLBACK_RECEIVE` we only process the message if `lws_remaining_packet_payload(wsi)` is 0 and `lws_is_final_fragment(wsi)` is TRUE, and the second condition is always FALSE for him.

Not sure about permessage-deflate, but I don't think we're doing that, as I don't see it being enabled explicitly in any part of the code. Unless it's something that is implicitly enabled with some flags?

**Comment by lminiero** [comment]
As a side note, is it safe to just rely on `lws_remaining_packet_payload(wsi)` to decide if we received all the message data or not? I think we had the final-fragment check for a reason, but if it's not needed we might just drop it.

**Comment by lws-team** [comment]
The code you pointed to seems to disable extensions, so it isn't that.

Exactly what version of lws is it?  I get 'very recent' but what does `git log -n 1` say?

**Comment by Triuman** [comment]
commit 25e5422e857ca608ab795adc9200ee45e201982c
Author: Andy Green <andy@warmcat.com>
Date:   Mon Mar 19 16:37:37 2018 +0800

**Comment by lws-team** [comment]
OK.  It's the evening here I will study it tomorrow morning (+12h) and report back.

It might be worth trying v2.4-stable in the meanwhile... master has had a huge amount of work and is just coming to the point of testing everything again for releasing v2.5, it's possible some things got broken and not noticed yet.

**Comment by lws-team** [comment]
I also added another minimal example

https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/ws-client/minimal-ws-client-pmd-bulk

this is designed to confirm multifragment send and receive at lws rx and tx... when the client is a browser, it will send everything in one fragment, but that is not the only legal way to do it.  In all cases `lws_is_final_fragment()` works correctly.

I noticed the docs for lws_remaining_packet_payload needed updating... they now read

```
/**
 * lws_remaining_packet_payload() - Bytes to come before "overall"
 *					      rx fragment is complete
 * \param wsi:		Websocket instance (available from user callback)
 *
 * This tracks how many bytes are left in the current ws fragment, according
 * to the ws length given in the fragment header.
 *
 * If the message was in a single fragment, and there is no compression, this
 * is the same as "how much data is left to read for this message".
 *
 * However, if the message is being sent in multiple fragments, this will
 * reflect the unread amount of the current **fragment**, not the message.  With
 * ws, it is legal to not know the length of the message before it completes.
 *
 * Additionally if the message is sent via the negotiated permessage-deflate
 * extension, this number only tells the amount of **compressed** data left to
 * be read, since that is the only information available at the ws layer.
 */
```

**Comment by lws-team** [comment]
AFAICS there's no problem with the topic of the issue.

If there's more info coming that does point to a problem, happy to continue looking at it.

**Comment by lminiero** [comment]
Thanks for looking into this @lws-team!
