### ISSUE TITLE
Suggestion: SIO_LOOPBACK_FAST_PATH support for windows

### ISSUE THREAD

**Issue by cempolat** [warmcat/libwebsockets#1228]
I wonder if it is worth to enable the fast path TCP socket option during libwebsockets initialization for the localhost servers in windows platform.

[SIO_LOOPBACK_FAST_PATH](https://msdn.microsoft.com/en-us/library/windows/desktop/jj841212(v=vs.85).aspx)

**Comment by lws-team** [comment]
TBH it sounds useful only under really specialized conditions

> This IOCTL must be used on both sides of the loopback session. The TCP loopback fast path is supported using either the IPv4 or IPv6 loopback interface.

Not only eg lws as a server has to enable it but also the client side.  What exactly are you trying to get out of it?

**Comment by cempolat** [comment]
I'm using libwebsockets server on localhost to send report data to chrome browser on the same PC. The report data is periodically sent to the web browser as websocket messages. I thought this would reduce my websocket traffic latency.
However, I'm not sure if Chrome supports the fast path.

**Comment by lws-team** [comment]
I think this isn't related to the lo "fast path" (which btw looks like a disgusting hack itself, since windows should infer whether to do a good job or not by looking at the source and destination addresses).

For non-windows platforms, lws uses poll() along with a "pipe" that allows it to externally cancel the poll wait asynchronously.  But because microsoft are microsoft and don't want to allow any level playing field, they don't provide poll() or pipe(), both of which are Posix standards.

So we have contributed workarounds in lws that work around it, but don't provide the same latency you would get automatically on linux or bsd / mac, which provide normal posix apis.  If you would like to improve it, patches are super welcome.
