### ISSUE TITLE
RTCDataChannel?

### ISSUE THREAD

**Issue by negativekelvin** [warmcat/libwebsockets#1230]
Hi again, very impressed with h2 and other improvements.  Noticed there was some signs of UDP support and wanted to see what you thought about WebRTC RTCDataChannel.  The idea being that any browser with WebRTC could make a direct P2P connection to a libwebsockets instance across NAT (using ICE first, of course).  So the web app would be public hosted or cached and you would need a signaling server but then you get a direct low latency (in theory) connection. To me it seems very useful.  It is still a "web socket" right?  Thanks.

**Comment by lws-team** [comment]
Thanks for the kind words.

Well, I am not too worried about only supporting ws.  In fact we already support full ssh2 server side over tcp.  My medium term plan if I can still afford to work on this long enough is quic transport

https://datatracker.ietf.org/doc/draft-ietf-quic-transport/

...that is the reason for the udp and hrtimer support (because udp requires timing to be effective).  If you are interested in RTCDataChannel, it's much preferable for me to cooperate to implement it since I already have my hands full at the moment.

The insides of lws need to be refactored to stop these extra protocol layers (because quic creates also, eg, h2-over-quic and ws-over-quic, and while we have server ws-over-h2, we are still missing client ws-over-h2) turning it into unmanageable spaghetti inside lws.  Which leads to the current focus of work starting with today's pushes, isolate the internal wire protocol handling and make it more beautiful and easy to add to... there will be an ops struct per wire protocol (h1, h2, ws, etc) isolating their various prioritizations and quirks.  Wire protocols will be able to express encapsulation of each other (eg, ws-over-h2, h2 over quic) explicitly. 

After the internal refactor is done, new wire protocol addition inside lws will be much less the black magic that it is today.  So please give it a few days and we should discuss again.

**Comment by lws-team** [comment]
So most of the lws refactor is done.  There's a struct now

https://github.com/warmcat/libwebsockets/blob/master/lib/private-libwebsockets.h#L615

that defines a "role", like h1, h2, ws etc.  wsi point to an instance of that struct with "ops" style callbacks to integrate to the main part of lws, which has become more neutral with the bulk of lws core code now migrating into one or another "role".  The much smaller core lws stuff calls into the role ops to get stuff done at key points, eg, the h2 role ops struct

https://github.com/warmcat/libwebsockets/blob/master/lib/roles/h2/ops-h2.c#L1059

https://github.com/warmcat/libwebsockets/tree/master/lib/roles

IIUI the idea boils down to implement SCTP (as a "role" in post-refactor terms)

https://tools.ietf.org/html/rfc4960

which is certainly doable, but it is a huge task; the scope is similar to writing a network stack.  The RFC is 150 pages.

I would be very happy to cooperate with others on it but is that what you're suggesting?

**Comment by negativekelvin** [comment]
Thanks I will review the changes. Implementation of sctp is an option but I wouldn't mind if there are external dependencies for sctp. In fact maybe it would just be better to have external termination/proxy of the sctp stream into lws. The goal is direct socket connection between embedded server and PWA running on a browser with NAT in between. Webrtc seems like the only P2P option with wide browser support in the near future. Embedded server also has to act like a client/peer in this role.  So I will have to think about best  option to connect lws to rtcdatachannel. If there is no other interest we can close the issue.

**Comment by lws-team** [comment]
I guess whatever happened, happened in the meanwhile.

But for googlenauts there is an overview now of how to add roles in ./lib/roles/README.md, including a list of reasons why you might want to go down the road of adding roles to lws.

https://github.com/warmcat/libwebsockets/tree/master/lib/roles
