### ISSUE TITLE
How to distinguish wsi close reason between FIN pkg and keep-alive time out?

### ISSUE THREAD

**Issue by xmanmax** [warmcat/libwebsockets#1232]
Hi, @lws-team 
It was notified with LWS_CALLBACK_CLOSED callback on my ws server when websocket connection closed, you know ,two reason can close the connection,
1) client send FIN package to my ws server to close it.
2) client shundown physical, and ws server set options: ka_time, ka_probes,ka_interval, then after that, ws-server close the connection.

How can I split them within  LWS_CALLBACK_CLOSED callback ?

thx a lot.

**Comment by lws-team** [comment]
You can send a ws CLOSE packet in ws from the remote side, and collect the close reason with `LWS_CALLBACK_WS_PEER_INITIATED_CLOSE`.  So you can know about controlled ws shutdowns vs the socket closing for some reason.

But lws doesn't track the reason the lws closed otherwise.

What is the use-case for that?

**Comment by xmanmax** [comment]
Thanks for your reply.

What is the use-case for that?
---
just for statistics,  and make an initial judgments about close reason of the socket

**Comment by lws-team** [comment]
I think you can do this by handling LWS_CALLBACK_WS_PEER_INITIATED_CLOSE and keeping your stats at the actual CLOSE by seeing if the wsi had been given a LWS_CALLBACK_WS_PEER_INITIATED_CLOSE before the actual close.
