### ISSUE TITLE
use provided_client_ssl_ctx with no LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT

### ISSUE THREAD

**Issue by Guid75** [warmcat/libwebsockets#1240]
Hello,

My lws client handles all SSL initialization and destruction by itself and I would like to use the `provided_client_ssl_ctx` field too.

I saw this in `ssl-client.c` (2.4-stable) :

```C
	if (!lws_check_opt(info->options, LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT))
		return 0;

	if (vhost->ssl_client_ctx)
		return 0;

	if (info->provided_client_ssl_ctx) {
		/* use the provided OpenSSL context if given one */
		vhost->ssl_client_ctx = info->provided_client_ssl_ctx;
		/* nothing for lib to delete */
		vhost->user_supplied_ssl_ctx = 1;

		return 0;
	}
```

Do it mean I cannot use `provided_client_ssl_ctx` if `LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT` is not set in my context options?  
Can it be considered as an issue?

**Comment by lws-team** [comment]
It means if you don't give the flag LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT, lws will understand that you are not using any kind of tls library and won't go near it.

When you say "My lws client handles all SSL initialization and destruction by itself", well, this has been a general problem with openSSL in the past.  But newer openSSL have improved their construction and destruction apis so that they no longer clash with multiple layer in the app performing them.

So.... what is your tls library and exact version, and what is the actual problem you are experiencing?

**Comment by kcbanner** [comment]
I ran into this today - I init OpenSSL outside of LWS, and pass in a `provided_client_ssl_ctx` that I created externally. I assumed that LWS would still use the provided client ctx even though it didn't actually init OpenSSL, but in fact it doesn't.

**Comment by lws-team** [comment]
The flag does what it is documented and intended to do.

The actual problem is presumably with older openssl single processwide init restriction... so what happens if you set this flag?  What's your openssl version?  If you have a recent openssl, lws will automatically use the modern init apis that should avoid problems... what actually happens?

**Comment by Dr-Emann** [comment]
I am on openssl 1.0.2o-fips, and libwebsockets 3.2.

The inability to safely create/destroy a libwebsocket context without unloading openssl is a problem for me. I am unable to move to openssl 1.1 because of FIPS.

**Comment by lws-team** [comment]
@Dr-Emann your comment isn't obviously related to this issue...

**Comment by Dr-Emann** [comment]
It is related mostly by your last reply: The actual problem is with older openssl which I don't believe has the APIs to make init/deinit safe. However, there doesn't appear to be a way to tell libwebsockets "I want to use SSL, but I've initialized openssl before you, and I want it to continue after you"

If there was a way to use a provided ssl_ctx without passing `LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT`, it would be a possible workaround.

**Comment by lws-team** [comment]
Well... feel free to cook up a patch with a slightly different option that does what you need.

**Comment by Dr-Emann** [comment]
Would an option like `LWS_SERVER_OPTION_USE_SSL` (open to naming suggestions) which is implied by `LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT`, but avoids the actual init/destroy of ssl globals be better? Or would you prefer an option like `force_provided_client_ssl_ctx`?

**Comment by lws-team** [comment]
It's not just going to be a matter of client_ssl_ctx, it's used as a big switch in some places in the code.

Unless you find something conflicting the best idea is probably leave LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT as it is, in that you would also use it.  But add another option that can be enabled along with it, that defeats specifically the tls library init part.  Eg, LWS_SERVER_OPTION_SKIP_TLS_LIB_ONETIME_INIT_DEINIT or somesuch
