### ISSUE TITLE
Parallel WRITEABLE events on one wsi

### ISSUE THREAD

**Issue by LabunskyA** [warmcat/libwebsockets#1241]
Let's imagine I have server with 2 lws (set via lws_context_creation_info) threads running and one client. Some client actions meant to call lws_callback_on_writable more than once.

I assume that events is processed in some kind of producer-consumer pattern, so. Could two or more LWS_CALLBACK_WRITEABLE and LWS_CALLBACK_HTTP_WRITEABLE events be triggered for that client at the same time in different working threads? Or are they processed in the way only one such event could be running at a time?

**Comment by lws-team** [comment]
First, this stuff only works properly on master.

The fds table used for poll wait, and the event loop, exists in a per-thread struct (aka pt) that is created for each service thread.

When an incoming connection is accepted, the pt with the least number of wsi is selected and the accepted wsi entered into the pt fds table; for libuv the selected wsi is bound to the event loop of the selected pt.  Subsequently, only that pt can report POLLOUT for that wsi, ie, do the WRITEABLE callback on it.

For performance reasons it's a little bit more complicated at accept time... each pt runs a duplicated listen socket of its own and the pt whose listen socket noticed any particular connection is basically random.  However wsi lifetime isn't random, so we would end up with some pt having too many wsi and some with too few.  For that reason the accept is bound to the least populated pt, which forces lws to do some locking internally to protect pt members since other pts are allowed to add wsi to them asynchronously.  But that's all.

The writeable callback belongs to the lws_protocols the wsi is bound to.  So multiple service threads can have wsi bound to the same protocol and be executing the same WRITEABLE callback code on different wsi simultaneously, just **never the same wsi** since each thread can only service one wsi that was bound to it at a time.  This has locking implications for user stuff the WRITEABLE callback touches.

**Comment by lws-team** [comment]
I pushed some small docs and diagrams here

https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/http-server/minimal-http-server-smp
