### ISSUE TITLE
lws_service will fail if connection is terminated

### ISSUE THREAD

**Issue by ecionis** [warmcat/libwebsockets#1259]
Hi,

New bug was detected. If ws connection is terminated, lws_service will return -1.

I founded problem, because fds_count=1  (must be 0) after detroyed wsi.

Problem at __remove_wsi_socket_from_fds (pollfd.c).

	`if (m != LWS_SOCK_INVALID) {

		/* have the last guy take up the now vacant slot */
		pt->fds[m] = pt->fds[pt->fds_count - 1];
		/* this decrements pt->fds_count */
		lws_plat_delete_socket_from_fds(context, wsi, m);`

here m=0,
but in windows LWS_SOCK_INVALID=0, and function lws_plat_delete_socket_from_fds is never used.

may be `if( m>=0 ){`

**Comment by ecionis** [comment]
Hey, dont forget about this. Push to master before release)

**Comment by lws-team** [comment]
Yeah don't worry.  I won't make the release until I found a way to confirm it's workable and looked at this.

**Comment by lws-team** [comment]
It looks to me like LWS_SOCK_INVALID should be INVALID_SOCKET on windows (which is ~0 apparently).  I pushed a patch with that on master along with a missing part of the hrtimer support for windows... the test app now operates reliably with and without tls for me on Appveyor.

Can you see if this also looks to fix it from your point of view please?

**Comment by ecionis** [comment]
Hi,

As I understand, this code is not about socket handle. m is position_in_fds_table. its offset and always >=0. therefore position offset != handle.

simple code (__remove_wsi_socket_from_fds):
```    
    m = wsi->position_in_fds_table; //get offset
    ...
    if (m != LWS_SOCK_INVALID) {  //offsed!=handle
   //if(m>=0) { //offset>=0
                ...
		/* removed wsi has no position any more */
		wsi->position_in_fds_table = -1; //disable offset
	}
```

**Comment by lws-team** [comment]
Oh... I think I see your point.  Yes m can be -1 specifically, not LWS_SOCK_INVALID.  Although the change I made is also correct I think it's unrelated then.  I'll look again tomorrow.

**Comment by ecionis** [comment]
Oh.. if use INVALID_SOCKET (-1) for LWS_SOCK_INVALID, all functions (****_valid) are invalid.

example:
#define lws_socket_is_valid(x) (!!x)
#define lws_sockfd_valid(sfd) (!!sfd)  

may be change to
#define lws_socket_is_valid(x) (((int64_t)(x))>=0)
#define lws_socket_is_valid(x) (x>=0) <-wrong because type of SOCKET is unsigned

i dont know, need more time for investigate.

**Comment by lws-team** [comment]
Thanks... I pushed a patch on master:

 - introducing a new constant LWS_NO_FDS_POS (-1) for use with position_in_fds_table

 - audit all uses of position_in_fds_table to check against LWS_NO_FDS_POS specifically

 - add asserts to ensure  the only possibilities for position_in_fds_table are LWS_NO_FDS_POS or >= 0 && < pt->fds_count

 - remove lws_sockfd_valid(), convert it to be lws_socket_is_valid, since they were duplicates.  There is only lws_socket_is_valid() now.

 - remove definition of lws_socket_is_valid() from each platform, simply define it as (x!=LWS_INVALID_SOCKET) for all platforms

With these changes, in the original problem, correcting the definition of LWS_SOCK_INVALID from 0 -> INVALID_SOCKET for windows platform solved that I think.

Hopefully that's everything related to this now.

**Comment by ecionis** [comment]
Great job! (sorry, i dont have time to test all changes)
