### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by lalittmt** [warmcat/libwebsockets#1272]
Hi ,
I got error during compilation latest master branch
/lib/plat/lws-plat-unix.c: In function 'lws_plat_set_socket_options':
/lib/plat/lws-plat-unix.c:358:35: error: 'TCP_USER_TIMEOUT' undeclared (first use in this function)
   if (setsockopt(fd, IPPROTO_TCP, TCP_USER_TIMEOUT,
                                   ^

**Comment by lalittmt** [comment]
I want to cross-compile libwebsocket library for MIPS.

**Comment by lws-team** [comment]
Hm... what seems to have happened is when cmake checks for TCP_USER_TIMEOUT, he is looking at your build machine /usr/include.  So he thinks it is there.

When you actually build cross, for MIPS, he is looking in your cross build ./include and in there, there is no TCP_USER_TIMEOUT.  Probably because MIPS is dying and the kernel is old.

So how are you handling the cross build, using the cmake cross stuff?

**Comment by lws-team** [comment]
I can't help you further without more info about what you are actually doing.  My guess is this isn't anything to do with lws but some issue around the cross build.

If you use cmake's cross build arrangements, as discussed in the lws docs, you shouldn't have any problem.

**Comment by taoistcard** [comment]
Hi，
I got the same error. I found `CHECK_C_SOURCE_COMPILES("#include <linux/tcp.h>\nint main(void) { return TCP_USER_TIMEOUT; }\n" LWS_HAVE_TCP_USER_TIMEOUT)` i CMakeList.txt. 
But `<netinet/tcp.h>` is used in `private.h`. 
Should i use conditional compilation  to include `<linux/tcp.h>` ?
