### ISSUE TITLE
How to send the data to server while using as the websockets client?

### ISSUE THREAD

**Issue by sgawarikar** [warmcat/libwebsockets#1276]
Hi,

I am using this library for websockets client, My requirement is to send/receive data within the same thread. I run the test-client and I am able to receive the data in the registered callback but I didn't found anything to send the data on server. How to use this library to send the data while using as the websockets client?

If I use multi-theading, i.e. two different threads for send and receive, then Is the library thread-safe?

**Comment by lws-team** [comment]
> If I use multi-theading, i.e. two different threads for send and receive, then Is the library thread-safe?

Lws itself is single-threaded.  But there are ways to integrate other threads.

If you look at any of the examples you will see you cannot send anything with lws until the WRITABLE callback is coming, on the event loop thread.

In lws, once the wsi is connected, if it is being a server or a client connection doesn't make much difference for how the callbacks work and library capability.

So you can refer to https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/ws-server/minimal-ws-server-threads for how to integrate other threads and it will work the same for client connections.

**Comment by sgawarikar** [comment]
> If you look at any of the examples you will see you cannot send anything with lws until the WRITABLE callback is coming, on the event loop thread.

Does it mean the library triggers the WRITABLE callback? If yes then when?

**Comment by lws-team** [comment]
Read READMEs/README.coding.md if you are unfamiliar with poll(), POLLIUT or nonblocking event loops.

@section writeable Only send data when socket writeable

You should only send data on a websocket connection from the user callback LWS_CALLBACK_SERVER_WRITEABLE (or LWS_CALLBACK_CLIENT_WRITEABLE for clients).

If you want to send something, do NOT just send it but request a callback when the socket is writeable using

    lws_callback_on_writable(wsi) for a specific wsi, or

    lws_callback_on_writable_all_protocol(protocol) for all connections using that protocol to get a callback when next writeable.

Usually you will get called back immediately next time around the service loop, but if your peer is slow or temporarily inactive the callback will be delayed accordingly. Generating what to write and sending it should be done in the ...WRITEABLE callback.

See the test server code for an example of how to do this.

Otherwise evolved libs like libuv get this wrong, they will allow you to "send" anything you want but it only uses up your local memory (and costs you memcpys) until the socket can actually accept it. It is much better to regulate your send action by the downstream peer readiness to take new data in the first place, avoiding all the wasted buffering.

Libwebsockets' concept is that the downstream peer is truly the boss, if he, or our connection to him, cannot handle anything new, we should not generate anything new for him. This is how unix shell piping works, you may have `cat a.txt | grep xyz > remote", but actually that does not cat anything from a.txt while remote cannot accept anything new.

@section oneper Only one lws_write per WRITEABLE callback

From v2.5, lws strictly enforces only one lws_write() per WRITEABLE callback.

You will receive a message about "Illegal back-to-back write of ... detected" if there is a second lws_write() before returning to the event loop.

This is because with http/2, the state of the network connection carrying a wsi is unrelated to any state of the wsi. The situation on http/1 where a new request implied a new tcp connection and new SSL buffer, so you could assume some window for writes is no longer true. Any lws_write() can fail and be buffered for completion by lws; it will be auto-completed by the event loop.

Note that if you are handling your own http responses, writing the headers needs to be done with a separate lws_write() from writing any payload. That means after writing the headers you must call lws_callback_on_writable(wsi) and send any payload from the writable callback.

@section otherwr Do not rely on only your own WRITEABLE requests appearing

Libwebsockets may generate additional LWS_CALLBACK_CLIENT_WRITEABLE events if it met network conditions where it had to buffer your send data internally.

So your code for LWS_CALLBACK_CLIENT_WRITEABLE needs to own the decision about what to send, it can't assume that just because the writeable callback came it really is time to send something.

It's quite possible you get an 'extra' writeable callback at any time and just need to return 0 and wait for the expected callback later.
