### ISSUE TITLE
Multiple Contexts Support

### ISSUE THREAD

**Issue by Babel-Fish** [warmcat/libwebsockets#1282]
I know the topic of multiple context has been discussed in the past (https://libwebsockets.org/pipermail/libwebsockets/2016-June/002626.html) but on v1.7 we were able to obtain this ability by commenting out openssl startup/shutdown within libwebsocket ssl.c. We were controlling that aspect via our application layer as well as the openssl multithreading locking hooks (https://linux.die.net/man/3/crypto_lock). 

We recently upgraded to v2.x and are experiencing issues. There appears to be new usage of static variables that are causing problems (https://github.com/warmcat/libwebsockets/blob/88e4f73c59855690f942db14b948b20755565b48/lib/tls/openssl/ssl.c#L149). Can the static variables be changed to context based (in either v2.x or v3.x)? I am curious if the following changes could be done:
- Make OpenSSL startup/shutdown optional (aka yes do openssl but, no, don't initialize it as it will be done at application layer)
- Change the static variables to be bound to the context instead of global.

Besides those aspects is there anything else that would hinder the ability to allow multiple contexts?

For what its worth, I believe even curl no longer initializes openssl within its libraries: https://curl.haxx.se/libcurl/c/curl_global_init.html See: CURL_GLOBAL_SSL

For background purposes, in our application we have three websockets. One for inbound connections, and two outbound connections to other servers and all in different layers within our server. It would be rather invasive to force those to share a context. 

Thanks in advance

**Comment by lws-team** [comment]
Well, leaving the OpenSSL detail aside, there are other reasons the idea in lws is one context per process, such as the fd map (fds being per-process), and if you use them, plugins are per-process.

If you are dead set on wanting multiple lws contexts in one process, you can try it and I'll consider any patches.  But unless my imagination is not up to the task, n contexts, n event loops, n openssl inits (or none) in one process doesn't sound to me that it's ever going to be the right way.

**Comment by lws-team** [comment]
... on the subject of migrating away from multiple contexts, since I guess you have these things in separate threads, you should take a look at `lws_cancel_service()`.  An external thread can call that and get a callback `LWS_CALLBACK_EVENT_WAIT_CANCELLED` in the service thread context.  See

https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/ws-server/minimal-ws-server-threads

After that it's just a matter of sharing a struct with the stuff you want to serve in each of the three cases.  You can pass in a `void *` "user" pointer when creating the context and get it back from any wsi using `lws_context_user(lws_get_context(wsi));`.  That can be a struct containing or pointing to the information from the other parts of your process.
