### ISSUE TITLE
Load Static Plugins?

### ISSUE THREAD

**Issue by Babel-Fish** [warmcat/libwebsockets#1286]
Do you have the ability to add plugins that are not ".so"? I see the code where you load the ".so" and extract the start/stop functions and add to your plugin list. I am curious if there is a programmatic way (already supported via your api) to add a class as a plugin without having to do the "protocols" method. That way layers beneath the application layer could be passed the context, register their plugin, and then start a listener or ws connection. Benefit would be that it could be performed after the context was spun up already. Thanks in advance.

**Comment by lws-team** [comment]
Going by your title, "yes"... most of the minimal examples, the test server etc statically `#include` the plugins as code so they work on platforms and build environments without plugin support, eg

https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/ws-server/minimal-ws-server-echo

The plugin boilerplate is structed to allow both that strategy and dynamic loading.

Going by your description, with the title "static plugins" I am not 100% what you're asking.  I added the plugin loading to do what it does for lws, which is to enable the concept of lwsws and users only have to deal with writing their protocol plugin, and just configure a generic server app in JSON, not code.  Then it became necessary to share the plugin code for static build case too.

The JSON config stuff is an export of its own from lws, not part of lwsws.  That has the ability to define vhosts fully.

Client connections can be started from protocol init, eg

https://github.com/warmcat/libwebsockets/blob/master/minimal-examples/ws-client/minimal-ws-client-echo/protocol_lws_minimal_client_echo.c#L109

That example also shows how to acquire per-vhost config using per-vhost options, which the JSON config supports declaring.

So there are probably enough pieces available to get what you describe.

**Comment by Babel-Fish** [comment]
@lws-team I see from your example that minimal-ws-server-echo.c imports the .c plugin code via '#include "protocol_lws_minimal_server_echo.c"' and that is passed to the lws context struct via protocols variable. This is added to lws library via lws_create_context. This method differs from plugins which can be imported after the context is created. My question is if there is an api to add '#include "protocol_lws_minimal_server_echo.c"' contents in a similar manner as plugins (aka after context has been created).

**Psuedo code/logic would be:**
App layer, lws context created (Protocols = nullptr)
Pass lws context to lower layers within our server
Lower layers could register their protocols (consisting of name, static callback func, etc) when they are ready
Lower layers would then either invoke lws_client_connect_via_info or vhost apis if needing to listen.

**Comment by lws-team** [comment]
> @lws-team I see from your example that minimal-ws-server-echo.c imports the .c plugin code via '#include "protocol_lws_minimal_server_echo.c"' and that is passed to the lws context struct via protocols variable. 

Yeah, this is "static plugin" build.  If you don't have libuv, or your platform has no concept for dynamic loading like ESP32, you can still use the same protocol code like this.

> This is added to lws library via lws_create_context.

Strictly speaking the protocols struct is bound to the vhost.  By default, creating the context will create you a default vhost.  You can add your own vhosts (and their associated protocols) by hand and add and delete vhosts dynamically later.

> My question is if there is an api to add '#include "protocol_lws_minimal_server_echo.c"' contents in a similar manner as plugins (aka after context has been created).

Hmmm okay.

Assuming that you set info.options LWS_SERVER_OPTION_EXPLICIT_VHOSTS flag when creating the context, what happens when you create the **vhost** is the `info.protocols` you give at that time is copied into an allocated protocol table specific to the vhost, and any plugin protocols that were discovered during context creation are appended to that table.

The point is plugins as a way of discovering struct lws_protcols is secondary to your being able to point to your own at vhost creation time.

So I think what you are asking for is covered either by putting each layer that wants to participate into its own vhost with its own private list of protocols it was created with, or your composing an aggregated list of protocol pointers first from all your layers, and then creating one vhost that can do them all.

Is this lining up with your meaning?

**Comment by Babel-Fish** [comment]
@lws-team ah, yes, it looks like I am half way there. It looks like lws_create_vhost would be covered via `const struct lws_protocols *protocols` but what about lws_client_connect_via_info. That only accepts the char* ptr to an existing list `const char *protocol`. If our app had a "late comer" client ws connect and wanted to specify their own protocol, is that allowed?

**Comment by lws-team** [comment]
No the vhost stuff is the whole solution.

As I said above if you provide LWS_SERVER_OPTION_EXPLICIT_VHOSTS when you create the context, the context is created but has no default vhost along with it.  You can add vhosts to the context immediately after, or later.

Creating your own vhosts is simple, it uses the same context creation info struct for args

https://github.com/warmcat/libwebsockets/blob/master/minimal-examples/http-server/minimal-http-server-multivhost/minimal-http-server.c#L105

Each time you create a vhost, you can provide it with its own relevant list of struct lws_protocols... that argument in the info struct is per VHOST, not the context.

```
	const struct lws_protocols *protocols;
	/**< VHOST: Array of structures listing supported protocols and a protocol-
	 * specific callback for each one.  The list is ended with an
	 * entry that has a NULL callback pointer. */
```

You can bind your client connection to the appropriate vhost that was created knowing the protocol you want to use... which vhost you use for client connections is only otherwise used for tls conditions used on the client connection (eg, client certs).

```
struct lws_client_connect_info {
...
	struct lws_vhost *vhost;
	/**< vhost to bind to (used to determine related SSL_CTX) */
...
```
In this way there is no problem using the protocol name either for protocols discovered by plugins, or built-in ones manually bound to the vhost when it was created.

**Comment by Babel-Fish** [comment]
@lws-team Ah, I was under the impression that vhost was designed for when ports were specified. So I can simply register a new vhost with port = `CONTEXT_PORT_NO_LISTEN` along with the protocols, ext, ssl cert, etcs. Then bind that vhost to the `lws_client_connect_info` and call `lws_client_connect_via_info`. I will try that tomorrow.

**Comment by lws-team** [comment]
Well, I assume it's solved.
