### ISSUE TITLE
lws_write using per-message-deflate with msg > tx buffer crashes if buffer freed

### ISSUE THREAD

**Issue by pcmacdon** [warmcat/libwebsockets#1362]
In large lws_writes, the buf parameters pointer gets saved by extension-permessage-deflate.c:

   case LWS_EXT_CB_PAYLOAD_TX:
    ...
      priv->tx.next_in = (unsigned char *)eff_buf->token;

However if deflate() fails to finish compressing the message, a later call to lws_service() will finish the job.  But by then, my program has already freed this buffer, so it crashes.

There seems to be no way after calling lws_write() to query if deflate is finished so we can safely free buf.  Meaning the only way to effectively use deflate support, is to ensure deflate buffers are predefined larger than the largest message ever to be sent (as in issue #593)?

This seems like a pretty big limitation.  Or am I missing something?

I am using libwebsockets 2.2, but the code in 3.0 looks to be doing the same thing.

Thanks, Peter

**Comment by pcmacdon** [comment]
Update: a workaround is to defer freeing the buf until the next lws_write (in WRITEABLE event) or until the connection closes.   The documentation makes no mention of this.

**Comment by lws-team** [comment]
Yeah... IIUI that is indeed a workaround, but it's not The Way it should work.

It's tricky because lws restricts the inflate and deflate action to a buffer at a time, by default 1KB each, to put a lid on the amount of memory used.  More naive implementations actually allocate for the whole deflate at once.

The main point I think is "large lws_writes"... if you restrict your writes to the deflate buffer size (1KB by default) and do them iteratively, you should avoid this problem: that is how the minimal examples do it

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-pmd-bulk/protocol_lws_minimal_pmd_bulk.c#n116-169

**Comment by pcmacdon** [comment]
Ugh.  that chunking-write implementation is a lot more convoluted than just using lazy-free.  And it hard-codes things like  MESSAGE_SIZE = 1024.

In my case the user is Jsi (jsish.org, a javascript interpreter) meaning the real users are scripts. Jsi  bumps the default size up from 1024 to 4096 (to be the same as Linux sockets) , and allows scripts to modify it from that.  So no I think I'll stick with lazy-free.

The real issue is with the documentation (which BTW is generally quite excellent) where for lws_write it states:

   "LWS will buffer the remainder automatically, and send it out autonomously."

which is clearly not always the case when extensions are involved.

Also in lws_write (while were on the topic) the protocol parameter is being used as an int, not an enum as declared.  So again this muddy's the implementation.

BTW: I've been using libwebsockets for 6+ years, mostly in commercial apps and it's excellent.   This was previously v1.7 but is now v2.2.  Versions beyond that I don't see moving to anytime soon as they  add things like lwsws and virtual mounting that Jsi already provides, so there is little payback for the added complexity in a system where we need to build libwebsockets in using Make rather than CMake.  Nonetheless, I just wanted to say thanks.

**Comment by lws-team** [comment]
> hard-codes things like MESSAGE_SIZE = 1024.

That is just the minimal example... to be "minimal" they have to be minimal.  Previously we had the test
apps that piled on all the options for everything and many users found them impenetrable.

The extension itself allows you to set the chunk size via lws_set_extension_option(), and since your code does that, it can follow suit with the size it set.  But actually in the case the input is not that compressible, 1KiB blocks are probably under your MTU and have the advantage they can always or almost always be written to the network.

> which is clearly not always the case when extensions are involved.

Yeah... it can be made to do it also for pmd, and that would be nicer.  But I personally don't use permessage-deflate; if I had to use it I would do as the minimal example does.  So I don't feel a tremendous sense of urgency to spend my Sunday on it.  Patches are always welcome... it's FOSS...

> Also in lws_write (while were on the topic) the protocol parameter is being used as an int, not an enum as declared. So again this muddy's the implementation.

Since we're in pedantic mode, "muddies".

>  Versions beyond that I don't see moving to anytime soon as they add things like lwsws and virtual mounting that Jsi already provides,

Lws is very flexible.  For example it runs very well on ESP32 https://en.wikipedia.org/wiki/ESP32 , with http/2, the mounts, and many other capabilities like ACME.  How does Java do on ESP32 with usable heap after the network and wifi stack of ~200KiB, and 4MiB serial flash for everything :-) ?  Lws isn't designed around anyone's specific use-case, even mine since it supports many things I don't personally use.

I think you are misunderstanding the situation with old versions and "complexity"... most features in lws are default OFF in cmake.  You can turn off individual roles at cmake.  V3.0+ lws is actually a lot simpler inside, more configurable (you can turn of ROLE_WS at cmake now for example) and more maintainable than what went before.  And although I just fixed something in v2.4, versions older than that I am not spending any time on maintaining so you will be on your own...
