### ISSUE TITLE
On Message > Send String Response Not Working

### ISSUE THREAD

**Issue by mreese3** [warmcat/libwebsockets#1363]
I am trying to set up a configuration server that serves configuration files to a client via websocket. At the moment I will settle for simply sending a hardcoded string back to the client. The problem is, I have zero idea how to do that. I tried to memcpy the string into where the payload would be, but I get gibberish back on the client end and the server says it sent one character when it should be sending a string of 20 characters. Is there ANY way to bypass this ringbuffer and simply send the whole string without a buffer at all? 

     `    case LWS_CALLBACK_RECEIVE:
	    {
		int  len = sizeof("ws://localhost:7575");

		if (((ringbuffer_head - pss->ringbuffer_tail) &
			(MAX_MESSAGE_QUEUE - 1)) == (MAX_MESSAGE_QUEUE - 1)) {
			lwsl_err("dropping!\n");
			goto choke;
		}

		//ringbuffer[ringbuffer_head].payload
		if (ringbuffer[ringbuffer_head].payload)
			free(ringbuffer[ringbuffer_head].payload);

		ringbuffer[ringbuffer_head].payload =
			malloc(LWS_SEND_BUFFER_PRE_PADDING + len +
				LWS_SEND_BUFFER_POST_PADDING);
		ringbuffer[ringbuffer_head].len = len;
		memcpy((char *)"ws://localhost:7575" +
			LWS_SEND_BUFFER_PRE_PADDING, in, len);
		fprintf(stderr, "Openness: recieved %s\n", (char *)ringbuffer[ringbuffer_head].payload);
		if (ringbuffer_head == (MAX_MESSAGE_QUEUE - 1))
			ringbuffer_head = 0;
		else
			ringbuffer_head++;

		if (((ringbuffer_head - pss->ringbuffer_tail) &
			(MAX_MESSAGE_QUEUE - 1)) != (MAX_MESSAGE_QUEUE - 2))
			goto done;

	choke:
		lwsl_debug("LWS_CALLBACK_RECEIVE: throttling %p\n", wsi);
		libwebsocket_rx_flow_control(wsi, 0);`

**Comment by lws-team** [comment]
> memcpy((char *)"ws://localhost:7575" + LWS_SEND_BUFFER_PRE_PADDING, in, len);

The compiler wasn't complaining because it needed casting.  It's complaining because char strings are really const, they go in a section called .rodata which may segfault if you try to write it depending on the OS.  That line is complete junk.

You can just use LWS_PRE; LWS_SEND_BUFFER_POST_PADDING has been 0 and removed from any lws examples for several years too.  Don't base your code on random snippets full of bugs from the Internet, just use the provided minimal examples as the starting point, they are up to date and show the current best way to do things.

> Is there ANY way to bypass this ringbuffer

Yeah... it can't be caused by your own garbage code, can it.

You are certain you will never get another RX coming before you have passed on the previous RX to its destination, or if so, don't mind losing RX as it's overwritten with the latest data before it was sent on?  You don't need a ringbuffer, look through the minimal examples to find working, buildable examples with and without.  Not sure?  You need a ringbuffer.  How convenient there is a working implementation licensed CC0 so you can just cut and paste it as your starting point.  It's okay no need to embarrass me with your gratitude...
