### ISSUE TITLE
Possible bug in libwebsockets/lib/server/server.c:2910

### ISSUE THREAD

**Issue by jgentner2** [warmcat/libwebsockets#1364]
In libwebsockets 2.4-stable:

https://github.com/warmcat/libwebsockets/blob/2b4f54270535f1c7e18d6905b4b3b66a25da1d61/lib/server/server.c#L2910 reads free'd memory when re-enabling transfers after disabling with the rx flow control API.  The buffer it is using was free'd on line https://github.com/warmcat/libwebsockets/blob/2b4f54270535f1c7e18d6905b4b3b66a25da1d61/lib/server/server.c#L2900 moments before feeding the state machine.

This is how I fixed the issue:

```
/* process the byte */
m = lws_rx_sm(wsi, *(*buf)++);
        
if (wsi->rxflow_buffer && wsi->rxflow_pos == wsi->rxflow_len) {
    lwsl_debug("%s: %p flow buf: drained\n", __func__, wsi);
    lws_free_set_NULL(wsi->rxflow_buffer);
    /* having drained the rxflow buffer, can rearm POLLIN */
    _lws_rx_flow_control(wsi);
}

if (m < 0)
    return -1;
len--;
```
The repo code seems to cause occasional application crashes.

**Comment by lws-team** [comment]
Thanks... but I don't really understand how or what this "fixes" from the description.  It looks like you move the check if we completed the rxflow buffer to after the parsing, but if the rxflow_buffer was NULL, it shouldn't be using it anyway.  *buf is pointing into the rxflow buffer somehow?

Do you have a backtrace from one of these crashes lying around?

Assuming your "fix" moves the check for rxflow_buffer drained and doesn't repeat it, I am a bit loathe to just apply it since whatever is touching it should not actually be touching it without checking itself if it
has reached the end... the real problem seems to be there.  A backtrace of what actually blows, from gdb or valgrind will help make sure it's really fixed.  Use `cmake .. -DCMAKE_BUILD_TYPE=DEBUG` to get a useful backtrace.

The code in v3.0+ had all these individual buffer cases reworked into a global per-wsi buflist that can handle multiple buffers pending on the one list for any reason.  So I would guess whatever it is you are fighting on v2.4 has gone away at v3.0.

**Comment by jgentner2** [comment]
Oh, and to answer your question, the problem occurs after removing
backpressure. Whatever data was buffered in the rxflow_buffer is processed
first before accepting new data from the wire. It is in the processing of
the last character that the problem occurs. Rxflow_buffer is freed and then
the last char is processed. My problem began when I added flow control and
it turns out buf is invalid on the last char. So, if some other thread
allocated memory and does something to it, the state machine can get
unexpected data.

**Comment by lws-team** [comment]
Thanks... the bt makes it much clearer, good old valgrind.

> Address 0x3965437d is 781 bytes inside a block of size 782 free'd

`buf` is pointed at the rxflow buffer then, and it isn't going to read outside its bounds if we move the freeing to afterwards.... indeed it looks a bug it was done before.

I pushed a slightly modified version of your change on v2.4-stable.  Thanks for the report and the additional info.

**Comment by jgentner2** [comment]
No problem Andy. Thanks for your help.
