### ISSUE TITLE
How do I get incoming message length or end in LWS_CALLBACK_CLIENT_RECEIVE?

### ISSUE THREAD

**Issue by physiii** [warmcat/libwebsockets#1366]
When receiving a message I see multiple _LWS_CALLBACK_CLIENT_RECEIVE_ callbacks. I get the message input buffer, _(const char *)in_, in chunks of length 10 like:

```
{"test":12
3, "testin
g":456}
```

 and use strcat to build the message but I need to know when to stop building the string.

Is there a way to know when a message has ended or a way to get the size of the incoming message?

**Comment by lws-team** [comment]
a) you can control the chunk size, it's set in the `struct lws_protocols` `.rx_buffer_size` member for your protocol.  The dumb increment example protocol sets it to 10 because it only receives short strings, but you can set it to something more aligned to the size of what you expect to receive.

b) `lws_is_final_fragment(wsi)` will return nonzero if the chunk contains the last part of a ws message.
