### ISSUE TITLE
How to get the complete URL query in WS server

### ISSUE THREAD

**Issue by santosh0705** [warmcat/libwebsockets#1374]
I can get the already parsed url arguments/fragment using `lws_get_urlarg_by_name()` or `lws_hdr_copy_fragment()` but is there any way to get the complete un-decoded query parameters in websocket server?

**Comment by lws-team** [comment]
No.  The args are parsed in situ as part of the header parsing state machine.

**Comment by santosh0705** [comment]
When exactly the headers are parsed? Can we read it somehow before or after it?

**Comment by lws-team** [comment]
They are parsed

> in situ as part of the header parsing state machine.

The parser applies a bunch of sanitizations to the path (it won't allow ../../ to go behind the mountpoint), cuts any ? parameters up into fragments and applies urldecode while rejecting any illegal %-encoded stuff.

Instead of fixating on the original headers, why you don't say what it is you're trying to acheive?

**Comment by santosh0705** [comment]
Doing the same currently.
Thank you..
