### ISSUE TITLE
how to deallocate the momery allocated in lws_protocol_vh_priv_zalloc  ?

### ISSUE THREAD

**Issue by Sleepingbug** [warmcat/libwebsockets#1380]
how to deallocate the momery allocated in lws_protocol_vh_priv_zalloc ?

**Comment by lws-team** [comment]
There's an api to allocate it at vhost protocol init because it's up to the user code how much you want to allocate (usually, sizeof(*vhd) where the vhd struct is private to your protocol).

But at vhost protocol destroy time, if anything was allocated for that it is now definitively going out of scope, lws will take care automatically that the pointer is lws_free()'d without needing any user code in the protocol DESTROY callback.
