### ISSUE TITLE
can't get LWS_CALLBACK_CLIENT_CLOSED or LWS_CALLBACK_CLIENT_CONNECTION_ERROR.

### ISSUE THREAD

**Issue by Sleepingbug** [warmcat/libwebsockets#1384]
After the connection is established, I unplug the network cable  ,
I can't get LWS_CALLBACK_CLIENT_CLOSED or LWS_CALLBACK_CLIENT_CONNECTION_ERROR for a long time.

client demo : minimal-ws-client,
server : echo.websocket.org (port: 443)

**Comment by Sleepingbug** [comment]
client demo : minial-ws-client,
server : echo.websocket.org (port: 443)

**Comment by lws-team** [comment]
https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n314-325

**Comment by Sleepingbug** [comment]
not work.   i do something as mimal-ws-client.c,
step 1, generate message in  a thread ( thead_spam )
step 2, unplug  the network cable
result: lws_write is blocking for a long time .
there is no CLOSE or ERROR event invoked

**Comment by lws-team** [comment]
write() in lws_write() should not be able to "block for a long time" because all the sockets in lws are set to nonblocking mode.  So you should look closer at what actually happens on your platform with this "blocking".

The ping pong stuff closing anything relies on timeouts, so they can only work if you are still periodically leaving the poll wait (ie, going around the service loop).  If you are really stuck in the service loop, nothing can work.  Again then, the "blocking for a long time" needs explaining better...
