### ISSUE TITLE
JWS support for the ECC certificate

### ISSUE THREAD

**Issue by sgawarikar** [warmcat/libwebsockets#1393]
Hi,

I looked into the JWS suppport in the library. It has the HMAC & RSA support. 
Is there any plan to add ECC support as well?

Regards,
Sumedha

**Comment by lws-team** [comment]
I plan to update the ACME plugin to support the newer RFC version at some point.  But last time I looked that was OK with RSA same as the pre-RFC ACME.

If you want to contribute ECC support, patches are welcome.  Note that the JWS / JWK / whole ACME flow works on both openssl and mbedtls backend the same.  Any new features will also need to work on both libs.

**Comment by sgawarikar** [comment]
Yes. I will contribute for ECC support. I will share patch once my code is ready.
Thanks.

**Comment by sgawarikar** [comment]
Can you please share the current design? So I can fit ECC Support in your design.
I looked into the doxygen API docs but need more info how the flow works for JWS.
Thanks

**Comment by lws-team** [comment]
> Can you please share the current design? 

Lws is FOSS, there are no secrets, everything is right there.

I can help explain it but you'll need to ask more narrow questions.

Basically the job is look at lws-genrsa.* and add, eg, lws-ecdsa.*

If I was doing it, the first place to go is the keys

https://libwebsockets.org/git/libwebsockets/tree/lib/misc/jws/jwk.c

Because there is no standard representation for key parameters between openssl and mbedtls (their structs for the keys are completely different), lws provides an abstraction for key parameters in lws, eg for RSA here (this is why the name 'genrsa', it's generic because it hides the differences between mbedtls and openssl)

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-genrsa.h#n35-66

You can see it's there that the abstract key parameters from the enum get converted to the tls backend representation.  So to convert jwk rsa to a tls backend key, the generic (named) rsa key parameters are put into an abstracted `struct lws_genrsa_elements `  first, then passed to a tls backend-specific helper

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-genrsa.h#n95

which is in one of these depending on the backend you are building with

https://libwebsockets.org/git/libwebsockets/tree/lib/tls/openssl/lws-genrsa.c
https://libwebsockets.org/git/libwebsockets/tree/lib/tls/mbedtls/lws-genrsa.c

which maps key operations to the gnarly details of the tls backend in use

So you want the same approach, first add lws-genecdsa.h with a standard, generic representation, then the two lws-genecdsa.c to provide operations that take the generic representation and perform the backend operations on them.

Then teach the jwk code to recognize ecdsa-related json names (like it does for rsa) and provide the conversions to genecdsa similar to how it does for genrsa (the key parameters are different, but jwk standard defines the names).

Finally adapt jws code to alsa recognize the jws is using ecdsa like it recognizes rsa at the moment

https://libwebsockets.org/git/libwebsockets/tree/lib/misc/jws/jws.c#n383

and add support for high-level operations like signing via your genecdsa implementation, same as it does today for rsa by genrsa operations.

**Comment by sgawarikar** [comment]
Ohk Thank you. Let me see into this.

**Comment by sgawarikar** [comment]
I go through the below link for openssl:
https://wiki.openssl.org/index.php/EVP_Signing_and_Verifying#Asymmetric_Key

This shows how to create & verify the signature but this is the same for all algorithms i.e. RSA, ECDSA 
Can we use that for openssl?? However I am not sure that the such method is available for mbedtls backend.

This method choose the algorithm from the provided private keys.

**Comment by lws-team** [comment]
> However I am not sure that the such method is available for mbedtls backend.

What are you expecting me to do about your lack of certainty about that?

**Comment by sgawarikar** [comment]
I mean Will I get the APIs for EC support in mbedtls backend or I need to implement the core functionality as well?

**Comment by lws-team** [comment]
No... you don't have to implement ECC... don't worry.

There is info around if you google it, eg

https://tls.mbed.org/discussions/generic/certificate-ec-public-key-algorithms

but I recommend you get the OpenSSL flow working end to end first.  Then I can try to help on the mbedtls stuff, since it is a headache alright.

**Comment by sgawarikar** [comment]
Yeah.

**Comment by lws-team** [comment]
My spidey sense says this isn't happening... be delighted to be wrong though.
