### ISSUE TITLE
test-server uses compile-time resource path

### ISSUE THREAD

**Issue by pblemel** [warmcat/libwebsockets#1400]
Hi,

This may be more of a personal lack of understanding than an issue, in which case feel free to enlighten me.  It's a trivial issue, but as a new user trying to figure out why things didn't work as described it tripped me up for a little while.

I was at first unable to view the test.html page from my embedded system (QNX Neutrino 6) because of an issue with the resource path. There is a command line argument to change the resource path, however because 'mount' uses the compile time constant rather than the resource path argument, it is not possible to serve up the test.html file without re-configuring and re-building with a new constant.

I tracked the issue down (I believe) to the following :

LOCAL_RESOURCE_PATH is a constant defined as 
#define LOCAL_RESOURCE_PATH INSTALL_DATADIR"/libwebsockets-test-server"

The 'mount' containing test.html is defined as 
static const struct lws_http_mount mount = {
    (struct lws_http_mount *)&mount_post,   /* linked-list pointer to next*/
    "/",        /* mountpoint in URL namespace on this vhost */
    LOCAL_RESOURCE_PATH, /* where to go on the filesystem for that */
    "test.html",    /* default filename if none given */
    NULL,
    ...

This effectively hard codes the mount point to the compile time resource path. 

The solution is to modify this data structure at runtime, near 
    info.mounts = &mount;
    info.ip_limit_ah = 24; /* for testing */
    info.ip_limit_wsi = 105; /* for testing */

adding
   mount.origin = resource_path 

and removing 'const' from 'struct lws_http_mount mount'
    static struct lws_http_mount mount = {
       ...

Respectfully,
Peter

**Comment by lws-team** [comment]
Thanks... there are other mounts that doesn't solve it for and it's not worth adding to the code in there.  I "solved" it by removing -r, I will push the patch later.

You only want to do this because you are building cross, and you didn't establish a repeatable way to do that yet.  If you make a subdir in `./build` like `mkdir staging`, and then use DESTDIR at make install time, eg `sudo make install DESTDIR=staging`, instead of installing on the local machine the directory structure you to cmake to use (default prefix is "/usr/local") will not be installed on your build machine at the prefix, but appear under the "staging" directory at the prefix, so `./build/staging/usr/local/...`.  From there you can package it or rsync `staging/*` into `/` on the target over ssh.  In that way the hardcoded path in the test app is correct, same as it is when you build it non-cross.  This method also gets rid of problems coming because you are copying things piecemeal by hand, ie, old libraries in the wrong place.

Also the test app even when it was the only game in town was intended to be forked into your own app with your own stuff in it.  Now its importance is reduced due to the 30+ minimal examples which are easier to study, try, and fork.  For code simplicity, they take the approach to put their resources in the cwd and leave it to the user to decide how to deal with their resources when they fork it.
