### ISSUE TITLE
Websocket client don't send CLOSE packet

### ISSUE THREAD

**Issue by jcourtat** [warmcat/libwebsockets#1406]
Hello,

i'm using release 3.0.0. I build the minimal-ws-client-rx example program and want to close the connection properly. The program as is doesn't send the close packet after i enter Ctrl-C. I wasn't able to find a close connection packet using wireshark.
If i use wscat as a client, i can see the close packet.
I tryed several things, such as using lws_close_reason(), but it changes nothing.
I think i'm missing something before doing the lws_context_destroy() but i don't see what
Regards,

Julien

**Comment by lws-team** [comment]
> want to close the connection properly.

It's always completely proper to just drop the tcp connection with websockets.  Since that's the reality the ws connection only exists as long as the tcp one does.  All servers and clients have to follow that.

If you send your process (not the library) a SIGINT, you can choose what to do about it by trapping the SIGINT if you like.  lws_close_reason() + force the wsi to close with

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-timeout-timer.h#n73-99

But generally, the signal is telling you the process wants to exit.  It interrupts any event loop, or poll wait or read or write with the signal and says to exit.  That's what it does.

**Comment by jcourtat** [comment]
Thank you for your quick response !
I added a signal handler for SIGUSR1,
`sigusr1_handler(int sig)

{
    interrupted = 1;
    lws_close_reason(client_wsi, LWS_CLOSE_STATUS_NORMAL, "bye", 3);
    lws_set_timeout(client_wsi, PENDING_TIMEOUT_CLOSE_SEND, LWS_TO_KILL_ASYNC);
    lwsl_user("Signal %d\n", sig);
}
`
When i kill -s 10 `ps aux | grep [l]ws | awk '{ print $2 }'` , lws_service() seems to exit immediately and the close_reason and set_timeout seems ineffectives, even if they are called by the handler.

i also tryed to don't use signals to stop the process : 

`    
int cc = 0;
while (n >= 0 && client_wsi && !interrupted) {
lwsl_user("while\n");
n = lws_service(context, 1000);
if (cc++ == 5) {
lws_close_reason(client_wsi, LWS_CLOSE_STATUS_NORMAL, "bye", 3);
lws_set_timeout(client_wsi, PENDING_TIMEOUT_CLOSE_SEND, LWS_TO_KILL_ASYNC);
}
}
`
The process stops, but no CLOSE packet is sent to server.
I think i do something wrong.

**Comment by lws-team** [comment]
Lws doesn't say it's going to behave as you assume... like I said tcp close it completely compliant with ws RFC.

If you want to do that, I'll be happy to look at patches that help it happen.  But for lws close the tcp socket and "exit immediately" is a perfectly correct response to SIGINT.
