### ISSUE TITLE
cannot generate LWS_CALLBACK_CLOSED callback in time

### ISSUE THREAD

**Issue by fevedy** [warmcat/libwebsockets#1408]
Hi, @lws-team
On my Linux device, I use v2.4-stable as the client. Because the server uses wss, I use openssl.
During use, the router connected to my device was powered off, but was powered up immediately. This time my device got a new IP.
However, there is no data exchange between my client program and the server. I also verified this with Wireshark packet capture. But my program has been receiving LWS_CALLBACK_CLIENT_WRITEABLE
and did not receive LWS_CALLBACK_CLOSED. I received LWS_CALLBACK_CLOSED until about 17 minutes.
My question is why did I receive the LWS_CALLBACK_CLOSED callback so long? How can I solve this problem?
Thank you very much

**Comment by lws-team** [comment]
This is a question about tcp/ip.  It's a question about your unnamed platform.

If the socket layer tells lws the connection is dead, lws will do the callback.  It doesn't delay it.

Why do tcp connections sit there for many minutes if they meet a situation no ACKs are coming?

http://blough.ece.gatech.edu/4110/TCPTimers.pdf

Since the OS thinks the socket is connected, it will continue to accept sending new stuff (queueing it in the kernel) until the tcp window is full.  So the OS will report to lws the socket is WRITEABLE for a long time if you send a small amount at intervals.  Timeouts on the write side are ineffective then... the writes are not going anywhere but the OS reports everything is ok and buffers them until the tcp window fills, at which point the WRITABLE callbacks stop, but the tcp timers continue to wait for ACKs that are never coming.

Lws just follows what the OS tells it... what else should it do.

You can detect this condition not by timeout on write, but timeout on read.  The OS cannot lie to you about missing incoming data the way it can accept and buffer tx that is never sent.  So you can adapt your protocol to send 1-byte messages back from server to client every n seconds, and set an lwis timeout from ESTABLISHED for, eg 2n secs, and keep resetting it for 2n secs every time you receive the "I am alive" message.

Lws can do this automatically with

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n314-325

...but I recall that become more solid on 3.0, not sure about 2.4.

**Comment by fevedy** [comment]
Got it. I think I know what to do. 
Once again, I would like to express my heartfelt thanks.
