### ISSUE TITLE
Random issue sending continuous frame with permessage-deflate enabled

### ISSUE THREAD

**Issue by pvub** [warmcat/libwebsockets#1413]
Andy,

I was investigating some random websocket disconnects recently, when using permessage-deflate extension in lws (server uses libwebsockets). After debugging this on the client (a netty application), I traced it to the server sending a bad continuous frame which fails de-compression on the client. Every time this was happening on the client, it was failing to decode a continuous frame, and the length of the payload is either 6 or 7. The previous text frame is always 1019.

After further investigation using the test-server, we realized it was due to the extension not properly handling the case when the deflate() returns with a full buffer, and the next call to deflate() doesn't yeild anything.

This is the code I am referring to in extension-permessage-deflate.c:

```
		if (priv->tx_held_valid) {
			priv->tx_held_valid = 0;
			if (priv->tx.avail_out == 1 << priv->args[PMD_TX_BUF_PWR2])
				/*
				 * we can get a situation he took something in
				 * but did not generate anything out, at the end
				 * of a message (eg, next thing he sends is 80
				 * 00, a zero length FIN, like Authobahn can
				 * send).
				 * If we have come back as a FIN, we must not
				 * place the pending trailer 00 00 FF FF, just
				 * the 1 byte of live data
				 */
				*(--eff_buf->token) = priv->tx_held[0];
			else {
				/* he generated data, prepend whole pending */
				eff_buf->token -= 5;
				for (n = 0; n < 5; n++)
					eff_buf->token[n] = priv->tx_held[n];

			}
		}
```
As you can see, we only copy one byte from tx_held, whereas in the other case, we copy all five. I'm sure this is whats causing the continuous frame to be corrupt, resulting in a failure on the client. 
Since I do not completely understand the reason for this check and the info in the comment, can you help take a look and advise a potential fix?

**Comment by lws-team** [comment]
Sorry this took a long time to get to.

> We are using lws 1.7 on centos (with openssl)

I looked at master... the code is pretty similar but if you still have this problem, you should try master and see if it helps.

> I was trying to reproduce this with test-server, and finding it difficult to get the delfate() call to emit just 1024 (nothing more or less) using some test messages.

I added a minimal example

https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/ws-server/minimal-ws-server-pmd-corner

that makes it possible to meddle around with the deflated data size.  But because of limitations on what information is available from zlib, if zlib filled the output buffer, lws always withholds 5 bytes to make it a fact that a result where it is not known if it is the last emission, is not the last emission... because of that lws will not emit a 1024-byte buffer of deflated data.  (It's 5 bytes because up to 4 bytes may be elided if they are the zlib flush token 00 00 FF FF according to the pmd RFC... we can be sure we withheld at least one that way).

The new minimal example issues 5 packets near, at, and beyond the effective buffer limit of 1019.  And on master, it works OK.

> After further investigation using the test-server, we realized it was due to the extension not properly handling the case when the deflate() returns with a full buffer, and the next call to deflate() doesn't yeild anything.

I noticed that under some conditions, `deflate()` can be called again with 0 length input to produce extra sync bytes in the output stream... these didn't affect the ability to reconstruct the packet at the peer, but I added a patch that skips calling it if there's no new input.

It can still pass Autobahn here and on Travis.

If you still have problems on master, please reopen and if it helps, use the new minimal example to try to make it reproducible.
