### ISSUE TITLE
libcrypto double free memory corruption

### ISSUE THREAD

**Issue by jsveto** [warmcat/libwebsockets#1429]
am i allowed to create multiple libwesockets context from several threads?

I have 10-20 threads which simultaneously call lws_create_context. Sometimes i get segmentation fault or double free memory corruption errors. I do have openssl thread safety callback functions set (CRYPTO_set_id_callback and CRYPTO_set_locking_callback(locking_function).

After further investigation i noticed, that SSL_library_init function is called on each lws_create_context. SSL_library_init is not thread safe and should be called once. https://github.com/openssl/openssl/issues/2809

I use libssl-1.0.0

Should we create global lws_init function from which SSL_library_init is called? Some similar to curl_global_init?

Regards,
jsveto

**Comment by lws-team** [comment]
> I have 10-20 threads which simultaneously call lws_create_context. 

 - lws is not threadsafe

 - the lws_context allocates processwide resources, like fd tables.  You just want one, not 20.  20 contexts, 20 event loops... if you are trying to scale up an lws server, look at https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-smp instead, the model is one lws_context but multiple service threads.

 - later OpenSSL introduced new init apis with improved sanity.  If lws finds those apis, ir uses them.  If you think about it, since lws may be linked with other libraries that will also init OpenSSL, the restrictions they proposed without the newer apis are really fragile.

**Comment by jsveto** [comment]
> the lws_context allocates processwide resources, like fd tables. You just want one, not 20. 20 contexts, 20 event loops... if you are trying to scale up an lws server, look at https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-smp instead, the model is one lws_context but multiple service threads.

I am trying to implement lws client which connects to different websockets. If i understand correctly model is still the same. Single context multiple service threads.? Which reference example should i look at? This one: https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client-multi

> later OpenSSL introduced new init apis with improved sanity. If lws finds those apis, ir uses them. If you think about it, since lws may be linked with other libraries that will also init OpenSSL, the restrictions they proposed without the newer apis are really fragile.

I agree. I tried linking with libssl1.1. segfault error were gone during lws_create_context., but i should still follow the model (single context, multiple threads).

**Comment by lws-team** [comment]
When you create the lws context, he allocates for a lookup table according to the number of fd the process could allocate (`ulimit -n`... it's typically but not always 1024 on most distros by default).  So he has a really quick way to convert any fd, which is ultimately the currency of the wait, be it poll, epoll, whatever libuv is using etc, to a wsi.  But it means lws_contexts are relatively expensive (ulimit -n may be 1M or more), and you just want the one if you can manage it.

So an lws context is intended to be singular, in the same way if you had an event library you would normally have just the one event loop in your application, no matter how many sockets active on it.

One lws context can deal with many client connections ongoing simultaneously.

> Which reference example should i look at? This one: https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client-multi

Yes that is good to look at, then.  Because you will find one lws_context; one thread; and many client connections proceeding asynchronously.

Lws also understands if there is more than one client connection to the same host:port, that it should automatically share any existing connection if possible.  For http/1, it means the connections are queued and take their turn serially using http/1.1 keepalive on a single tcp / tls connection.  For h2, it means lws will automatically broadside n client connections simultaneously on a single h2 master connection, multiplexing them and sharing the bandwidth.  This means you can have n ongoing client connections to a server, but only one tcp connection and one tls tunnel set up at the start.

**Comment by jsveto** [comment]
> Lws also understands if there is more than one client connection to the same host:port, that it should automatically share any existing connection if possible. For http/1, it means the connections are queued and take their turn serially using http/1.1 keepalive on a single tcp / tls connection. For h2, it means lws will automatically broadside n client connections simultaneously on a single h2 master connection, multiplexing them and sharing the bandwidth. This means you can have n ongoing client connections to a server, but only one tcp connection and one tls tunnel set up at the start.

Ah this is interesting. However is there a way to tell lws to use one tcp/tls connection for each websocket connection? I have a case where i connect to same host:port several times. That host:port sometimes randomly closes tcp sockets (probably server side resource problems). I use several connections for redundancy. If all connection will use same tcp/tls session all connections will get killed at the same time.

**Comment by lws-team** [comment]
Study the sources on the example and you'll find your answer.

**Comment by jsveto** [comment]
Thank you for your answers. Keep up the good work!

**Comment by lws-team** [comment]
I stated

> the lws_context allocates processwide resources

and that you should only have one context on the go.

If you think you know better and want 20, that's great... knock yourself out.

**Comment by lws-team** [comment]
> I have single context

That's new then...

> but i create 20 client connections with lws_client_connect_via_info

Presumably 20 x ws connections to different places...

> My application has several threads which send data through websockets.

Lws is not threadsafe.

> This is done by creating msg in ring_buffer

Okie.

> Are my threads allowed to call lws_callback_on_writable simultaneously 

No.

The best way to deal with this is to use synchronization objects to mediade sticking events into your ringbuffer, and call `lws_cancel_service()` to notify lws there is something to do on his service thread.  That will wake him up immediately and make the service thread go to `LWS_CALLBACK_EVENT_WAIT_CANCELLED` callback.  There you can lock the ringbuffer and figure out who needs an on-writeable callback.

In the writable callback lock the ringbuffer and figure out what that specific connection should send.

> Same question for lws_client_connect_via_info and other lws API calls.

LWS IS NOT THREADSAFE

N O T   T H R E A D S A F E

**Comment by jsveto** [comment]
thank you sir, that explains everything :)

To anyone else reading this issue:

> LWS IS NOT THREADSAFE

N O T T H R E A D S A F E

**Comment by lws-team** [comment]
Maybe the putative readers of this thread will actually have taken the time to R the FM (or know by experience what an event loop means) instead of wasting my time.

> Libwebsockets works in a serialized event loop, in a single thread. It supports not only the default poll() backend, but libuv, libev, and libevent event loop libraries that also take this locking-free, nonblocking event loop approach that is not threadsafe. There are several advantages to this technique, but one disadvantage, it doesn't integrate easily if there are multiple threads that want to use libwebsockets.

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.coding.md
