### ISSUE TITLE
Question: Serve single-page application with client-side router

### ISSUE THREAD

**Issue by NIPE-SYSTEMS** [warmcat/libwebsockets#1443]
I'm trying to serve a single-page application (SPA) written with Angular 6 via libwebsockets. The client-side [router](https://angular.io/guide/router) of Angular uses the URL (the path of the URL, not the fragment) to display dynamic page content (route-definition example in [1]). The SPA needs an HTTP server that is capable of rewriting dynamic URLs to the SPA index-file so that an initial request will load the SPA. This means that every first request to the SPA will request the libwebsockets-HTTP-server with an URL that will not result in a valid/existing file-path regarding the mount and therefore leads to an error 404.

I'm trying to find a way to redirect these dynamic URLs to the SPA (which lives in the `index.html`). A possible solution for a HTTP-request handling strategy would be (pseudocode):

```
if( filepath_exists( URL ) ) {
    serve_file( URL );
} else {
    serve_file( index.html );
}
```

Currently I have a working libwebsockets server with a simple mount and websocket server:

```cpp
memset(&m_mount, 0, sizeof(m_mount));
memset(&m_protocols, 0, sizeof(m_protocols));
memset(&m_info, 0, sizeof(m_info));
m_mount.mountpoint = "/";
m_mount.origin = m_root_path.c_str();
m_mount.def = "index.html"; // default target
m_mount.origin_protocol = LWSMPRO_FILE;
m_mount.mountpoint_len = 1; // strlen of mountpoint
m_protocols[0].name = "http";
m_protocols[0].callback = lws_callback_http_dummy;
m_protocols[0].rx_buffer_size = 1024;
m_protocols[1].name = "ws";
m_protocols[1].callback = WebServerInterface::callback_ws;
m_protocols[1].per_session_data_size = sizeof(WebServerInterface::Client *);
m_protocols[1].rx_buffer_size = 1024;
m_protocols[1].user = reinterpret_cast<void *>(this);
// m_protocols[2] is NULL-terminator
m_info.port = m_port;
m_info.protocols = m_protocols;
m_info.gid = -1;
m_info.uid = -1;
m_info.mounts = &m_mount;
m_info.server_string = m_server_string.c_str();
m_context = lws_create_context(&m_info);
```

This libwebsocket server yields 404s when I'm trying to initially load the SPA.

As a workaround I can change the router of the SPA to [use the fragment](https://angular.io/guide/router#appendix-locationstrategy-and-browser-url-styles) of the URL to encode the dynamic part.

**But is there an option to achieve the redirection for dynamic URLs mentioned above without reimplementing vast parts of the libwebsockets HTTP-handling?**

Thanks in advance!

[1] route-definition example:

```ts
import { Routes } from '@angular/router';

const appRoutes: Routes = [
  { path: 'crisis-center', component: CrisisListComponent },
  { path: 'hero/:id',      component: HeroDetailComponent },
  {
    path: 'heroes',
    component: HeroListComponent,
    data: { title: 'Heroes List' }
  },
  { path: '',
    redirectTo: '/heroes',
    pathMatch: 'full'
  },
  { path: '**', component: PageNotFoundComponent }
];
```

**Comment by lws-team** [comment]
Hm... I didn't really understand the point about "single page application".  What made some kind of sense was

> This means that every first request to the SPA will request the libwebsockets-HTTP-server with an URL that will not result in a valid/existing file-path regarding the mount and therefore leads to an error 404.

I met a similar situation in gitohashi's gravatar proxy... gitohashi has generated html with img src into the gravatar proxy, but prefetching the stuff from gravatar happens asynchronously.  So, it's quite possible the browser might try to GET the png before it exists in the gravatar proxy cache.  That's not a failure it just means it should wait a bit.  Look at

https://warmcat.com/git/gitohashi/tree/src/protocol_avatar-proxy.c#n324-379

If it has been seen and fetched already, it serves it; you can see lws provides a public api to make it simple.  If it hasn't appeared yet, it gives it 8 tries at 1s intervals before giving up with a 404.  The code is suitable for what it does but it should be enough you can adapt it for your needs.

**Comment by NIPE-SYSTEMS** [comment]
Thanks for the quick reply.

I think your posted example does not fit my problem, but let me try to explain what I mean by single-page application (SPA):

A non-single-page application would be a webpage that navigates via conventional links (`<a href="/U/R/L">`), each changing the URL and triggering a new GET request to the HTTP server. So the user clicks on a link, the browser changes the current URL to the link's URL and fetches everything via the new URL.

The goal of the SPA is to present the user a webpage/application in the browser that loads once (e.g. via a single initial GET to the HTTP server) and then "runs" infinitely. Later, required resources will be lazy-loaded via e.g. AJAX. The benefit is that there is much more control what resource should be loaded at which point of time by scripting languages like e.g. JavaScript.

SPAs mostly consist of so called *routers* which are little scripts that manipulate 1. the URL-bar in the browser and 2. the fetching of new resources. These manipulation techniques will result in a webpage that acts like a normal/conventional webpage (displays the same things, changes the URL-bar) but there is, as said, much more control via JavaScript. The router that is shipped with Angular also supports this URL-manipulation. So in contrast to a conventional webpage, on a SPA you will see: The user clicks a link, some JavaScript catches the click and prevents the default browser action. The JavaScript will update the URL and initiates, when needed, an user interface change.

Now, imagine the user initially loads the SPA (e.g. `GET http://localhost:8080/`) and clicks around so that the URL changes dynamically (at the end e.g. `http://localhost:8080/some/path/`). At some point the user wants to reload the webpage. This reload is not covered by the router hence the whole SPA gets reloaded. This means the browser issues another initial GET request to the HTTP server (e.g. `GET http://localhost:8080/some/path/`) and the SPA gets displayed afterwards (like in the first case mentioned above). But this time this initial request is different because the second request also consists of the dynamic URL which gets sent to the server. At this point the server needs to know to answer with the SPA-page `/` and not with the URL `/some/path/` sent from the browser.

And here is the connection point with libwebsockets: I want to "redirect" the dynamic path `/some/path/` to `/`. This cannot be a HTTP-redirect (e.g. 301) because this would also change the link in the browser so that the dynamic part of the URL gets lost. What I need is that special paths respond with e.g. the `index.html` and not with the URL-path (because this would lead to a 404). One approach for detecting these special paths on the server-side would be to detect `ENOENT (No such file or directory)`.

**Is there an option to achieve the redirection for dynamic URLs mentioned above without reimplementing vast parts of the libwebsockets HTTP-handling?**

**Is it possible to implement the same HTTP callback that you mentioned in your post to rewrite/manipulate the paths on the server?**

Thanks in advance!

**Comment by lws-team** [comment]
Hum... lws is very flexible there are a lot of ways to come at what you want to end up with.

> And here is the connection point with libwebsockets: I want to "redirect" the dynamic path /some/path/ to /.

That doesn't sound nice.  You know you could:

 -  implement the same thing with `/myapp?state=/my/path` and there is no discontiguity about URL path, it is always "/myapp".  Will you be attacked by a mob of techno-hipsters in fedoras hurling Flat Whites at you because your implementation offends their idea of purity of the latest TLA fad?  Dunno.  Will it work?  Yes.

 - do it as a CGI.  For example `https://libwebsockets.org/mailman/listinfo/libwebsockets` is a cgi, the cgi mount part was "https://libwebsockets.org/mailman/listinfo" and that listinfo cgi used ".../libwebsockets" to understand the virtual URL path inside the cgi it should operate on.  Will you be hounded out of polite society for using a CGI?  Dunno.  Will it work?  Yes.

 - follow the mount scheme here

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-dynamic/minimal-http-server-dynamic.c#n182-222

so the default handler serves files, and only stuff down /dyn or whatever is directed to your handler.  In the handler for /dyn, you can use `LWS_CALLBACK_HTTP` to serve whatever you want for any `/dyn/...` URL.  So he Ctrl-R's `/dyn/some/path/` that was previously generated clientside... you keep the URL with no redirect but serve him `index.html` or whatever that brings in your scripts (the link I sent previously shows how to do that trivially, if index.html is a file somewhere).  When the browser runs its script, it looks at its local clientside URL and renders content for whatever should be shown for `/dyn/some/path/`.  No redirection.

> Is there an option to achieve the redirection for dynamic URLs mentioned above without reimplementing vast parts of the libwebsockets HTTP-handling?

If you want to serve files in a filesystem, lws makes it trivial, and you can even choose which file programatically and provide the mimetype.  Lws also provides simple apis for generating the http headers trivially, in a way that works the same on h1 or h2.  So what is this "vast parts" you talk of?  It's just dealing with on_writable() and sending the next chunk of your dynamic html stuff, isn't it?  Like this if it is dynamic

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-dynamic/minimal-http-server-dynamic.c#n50-166

> Is it possible to implement the same HTTP callback that you mentioned in your post to rewrite/manipulate the paths on the server?

Well... not rewrite in the apache sense.  But at that point in `LWS_CALLBACK_HTTP` you are in control of what the url part means to you and how to respond to it.  It sounds like all you need to do is make that serve `/index.html` for all urls without rewriting anything.

You should use the mounts system to ensure you are in the desired protocol handler callback already (it is not scalable to assume there is just the one callback that can decide by itself that every other url than it knows about must be a static file)... that is why I suggest having a mount specifically for your app like `/dyn`.  The `LWS_CALLBACK_HTTP` for the protocol handler at `/dyn` can make decisions with complete confidence it only got asked because the url is in the relevant part of the urlspace.  And if the application grows ws support or an unrelated cgi or whatever, they can go at their own mountpoints and will never interact.  Anything else will attempt to be served as a static file at the / mounpoint.

**Comment by NIPE-SYSTEMS** [comment]
Thanks for your detailed reply and the examples!

Quote from [Angular Docs](https://angular.io/guide/router#which-strategy-is-best):

> Almost all Angular projects should use the default HTML5 style. It produces URLs that are easier for users to understand.

Therefore `/myapp?state=/my/path` is not ideal because does not comply with the *default HTML5 style*. `/myapp/my/path` would comply with that...

CGI would be an option but your third approach is better: I would write the path handling myself in a callback handler and deliver the corresponding files via the libwebsocket functions (e.g. `lws_serve_http_file()`). With your given examples, this should not be a big deal.

Thanks again for your answers, your time and for providing this great library!
