### ISSUE TITLE
GCC 8.20 compiler errors, FYI

### ISSUE THREAD

**Issue by tewk** [warmcat/libwebsockets#1445]
[  1%] Building C object CMakeFiles/websockets_shared.dir/lib/misc/fts/trie-fd.c.o
/deps/srcs/libwebsockets/lib/misc/fts/trie-fd.c: In function 'lws_fts_search':               
/deps/srcs/libwebsockets/lib/misc/fts/trie-fd.c:380:37: error: 's.ch[0].child_agg' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   s[n].ch[s[n].child - 1].child_agg -= instances;
                                     ^~
/deps/srcs/libwebsockets/lib/misc/fts/trie-fd.c:381:12: error: 's.agg' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   s[n].agg -= instances;            
            ^~                
cc1: all warnings being treated as errors             
make[2]: *** [CMakeFiles/websockets_shared.dir/build.make:388: CMakeFiles/websockets_shared.dir/lib/misc/fts/trie-fd.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:364: CMakeFiles/websockets_shared.dir/all] Error 2
make: *** [Makefile:152: all] Error 2     
[  1%] Building C object CMakeFiles/websockets_shared.dir/lib/misc/fts/trie-fd.c.o
/deps/srcs/libwebsockets/lib/misc/fts/trie-fd.c: In function 'lws_fts_search':
/deps/srcs/libwebsockets/lib/misc/fts/trie-fd.c:380:37: error: 's.ch[0].child_agg' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   s[n].ch[s[n].child - 1].child_agg -= instances;                            
                                     ^~                                      
/deps/srcs/libwebsockets/lib/misc/fts/trie-fd.c:381:12: error: 's.agg' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   s[n].agg -= instances;

**Comment by lws-team** [comment]
Thanks... I have been building it for a while on Fedora 29's gcc 8.2.1 and it builds cleanly there.

Looking at the code, it's not clear to me the compiler is actually in a position to make the claim, although maybe I underestimate modern gcc's ability... 8.1's extra diagnostic smarts caused widespread consternation as real, ancient overlooked bugs were pointed out suddenly.

```
static int
ac_record(struct lws_fts_file *jtf, ... struct wac *s, int sp, ...)
{
...
	/*
	 * deduct this child's instance weight from his antecdents to track
	 * relative path attractiveness dynamically, after we already used its
	 * best results (children are sorted best-first)
	 */
	for (n = sp; n >= 0; n--) {
		s[n].ch[s[n].child - 1].child_agg -= instances;
		s[n].agg -= instances;
	}

	return 0;
}
```

both `s` and `sp` are passed in as parameters.

Looking at the code, it's true in the virtual base of the stack, s[0], we don't initialize agg, because that data from the virtual base isn't actually used... in case that's what it saw I pushed a patch on master changing the stack to use memset() whenever it starts a new level.

FWIW gcc X.Y0 versions are "experimental", the X.Y1 versions are "prerelease during the stabilization period".

https://gcc.gnu.org/develop.html

So please try the patch at current master HEAD... I'm curious if gcc has grown enough static analysis powers to attempt spot this kind of thing now, or if it's a false positive in 8.2.0 that was turned off in 8.2.1.

**Comment by tewk** [comment]
Thanks for fixing them.
I'm using the docker ubuntu:rolling 18.10 image
gcc --version
gcc (Ubuntu 8.2.0-7ubuntu1) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Here are two more

/deps/srcs/libwebsockets/lib/roles/http/client/client-handshake.c: In function 'lws_client_connect_2':
/deps/srcs/libwebsockets/lib/roles/http/client/client-handshake.c:47:9: error: 'port' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  int n, port;
         ^~~~
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/websockets_shared.dir/build.make:427: CMakeFiles/websockets_shared.dir/lib/roles/http/client/client-handshake.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:364: CMakeFiles/websockets_shared.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
[  0%] Building C object CMakeFiles/websockets_shared.dir/lib/roles/http/client/client-handshake.c.o
/deps/srcs/libwebsockets/lib/roles/http/client/client-handshake.c: In function 'lws_client_connect_2':
/deps/srcs/libwebsockets/lib/roles/http/client/client-handshake.c:47:9: error: 'port' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  int n, port;
         ^~~~

**Comment by lws-team** [comment]
In the flow of the code it seems it's always set if it's used, maybe I just miss the point.  I pushed a patch setting it to zero at the start... if the port is 0 or something random when it isn't supposed to be, it would make noticeable trouble.  So I guess it's a false positive... again that warning / error is not coming on gcc8.2.1 on Fedora 29.

If you find any more let me know here, I'll close this in the meanwhile.
