### ISSUE TITLE
Log output is always coloured, even when not connected to a TTY

### ISSUE THREAD

**Issue by thomasthiriez** [warmcat/libwebsockets#1447]
The log colouring is not disabled when stdout is not connected to a TTY.
This was broken by commit e8e448df3e89e4b40acf436979eb0fceb9d2def0 that replaced

`static char tty;`

with:

`static char tty = 3;`

**Comment by lws-team** [comment]
What I was experimenting with here was coloured logs in systemd.  But that did not work reliably, and the timestamp from lws duplicates the timestamp from systemd in the journal.

I reverted it and added an export `lwsl_emit_stderr_notimestamp()` which you can select from `lws_set_log_level()` if you know you're logging to something that already has a timestamp... I also adapted lwsws to use that since it's going to be the normal case that goes to systemd.
