### ISSUE TITLE
lws_config_private.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失

### ISSUE THREAD

**Issue by ll393595574** [warmcat/libwebsockets#1450]
lws_config_private.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失

**Comment by ll393595574** [comment]
v3.0 stable

**Comment by ll393595574** [comment]
build by visual studio 10

**Comment by lws-team** [comment]
Hmmm  "This file contains characters that cannot be represented in the current code page (936). Please save the file in Unicode format to prevent data loss"

936 is simplified chinese.

This is caused by a funky quote char in utf-8... however, on master lws makes intentional use of utf-8 in the sources, eg

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/api-tests/api-test-lws_tokenize/main.c

ie, utf-8 in lws sources is intentional, it is not a bug.  There's no point "fixing" the quote (if you want to hack around it, this will do it:

```
diff --git a/cmake/lws_config_private.h.in b/cmake/lws_config_private.h.in
index 10eea96e5..b7e3ef33a 100644
--- a/cmake/lws_config_private.h.in
+++ b/cmake/lws_config_private.h.in
@@ -22,7 +22,7 @@
 /* Define to 1 if you have the `fork' function. */
 #cmakedefine LWS_HAVE_FORK
 
-/* Define to 1 if you have the `getenv’ function. */
+/* Define to 1 if you have the `getenv' function. */
 #cmakedefine LWS_HAVE_GETENV
 
 /* Define to 1 if you have the <in6addr.h> header file. */
```
...)

The world doesn't all work on cp936 and it doesn't all work on windows... you should be able to use your microsoft toolchain to mark lws as to be interpreted as utf-8... if not, complain to microsoft.  If think it should already support it because the cp situation for Japanese on microsoft stuff is and has always been even more insane.
