### ISSUE TITLE
gzip compression in http /https protocol

### ISSUE THREAD

**Issue by Fedora7** [warmcat/libwebsockets#1455]
Does libwebsocket support gzip compression in http / https protocol ? Thanks

**Comment by lws-team** [comment]
On master, yes, on both h1 and h2.

Configure `-DLWS_WITH_HTTP_STREAM_COMPRESSION=1` at cmake.

If the client signals it also supports it, files with mimetypes "text/*", "application/javascript" and "image/svg.xml" will automatically go gzipped.  Brotli is also supported with `-DLWS_WITH_HTTP_BROTLI=1` additionally... if enabled it's preferred over gzip.

**Comment by vinifr** [comment]
Hello. I am running a websocket client with libwebsockets and I enabled LWS_WITH_ZIP_FOPS and LWS_WITH_HTTP_STREAM_COMPRESSION, but yet the websocket header is not adding  "Accept-Encoding: gzip, deflate". 

I believe this is causing issues and I am not able to receive the gzip data in client side.

**Comment by lws-team** [comment]
@vinifr  You're a bit confused...this issue is about http compression.

Permessage-deflate is a ws thing,not an http thing.

If that's what you want, set `-DLWS_WITHOUT_EXTENSIONS=0` at cmake to build in support for it.

You also have to enable it at runtime, eg

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/ws-client/minimal-ws-client-binance/main.c#n106
