### ISSUE TITLE
Correct way to adopt a raw file descriptor into a websocket?

### ISSUE THREAD

**Issue by pblemel** [warmcat/libwebsockets#1476]
Hi,

This related to [issue 1189](https://github.com/warmcat/libwebsockets/issues/1189). Unlike that poster, my code is establishing a websocket connection to a remote server and subsequently copying data from the fifo fd to the server by adopting the fifo's fd. 

The logic for doing this adopts the fifo's fd in CLIENT_ESTABLISHED, passing the websocket's wsi as the parent wsi.  In callback RAW_RX_FILE I use ```pwsi = lws_get_parent(wsi);``` to retrieve the websocket's wsi, copy data from the pipe to the parent's ring buffer (stored in per_session_data), and finally request ```lws_callback_on_writable(pwsi);``` to write the data to the websocket.  This works great.

My question is about what happens when the websocket is closed and re-established due to a network error.  The [adoption helpers page](https://libwebsockets.org/lws-api-doc-master/html/group__sock-adopt.html) doesn't document lws_adopt_descriptor_vhost.

Q1 : When the parent wsi is closed for any reason, does the adopted 'child' wsi automatically get closed/destroyed or is it my responsibility to un-adopt the descriptor?
Q2 : If not, is there a callback telling the adopted file's wsi that the parent has been closed?
Q3 : If so, does the file descriptor itself get closed by lws when terminating the child's wsi, or is it my job to close it in either the parent's or child's callback?

The reason for the questions is that when the connection is dropped and subsequently re-established because of a network error, the file descriptor will need to be re-adopted by the new client's wsi.  I just want to make sure that I'm cleaning up what I am responsible for cleaning up so that I don't get erroneous behavior.

Thanks
Peter

**Comment by lws-team** [comment]
Apologies for punting this... a lot happening recently.

`lws_adopt_descriptor_vhost()` does have docs, but I had missed the second * from `/**` at the beginning, so doxygen skipped processing it.

```
/**
* lws_adopt_descriptor_vhost() - adopt foreign socket or file descriptor
* if socket descriptor, should already have been accepted from listen socket
*
* \param vhost: lws vhost
* \param type: OR-ed combinations of lws_adoption_type flags
* \param fd: union with either .sockfd or .filefd set
* \param vh_prot_name: NULL or vh protocol name to bind raw connection to
* \param parent: NULL or struct lws to attach new_wsi to as a child
*
* Either returns new wsi bound to accept_fd, or closes accept_fd and
* returns NULL, having cleaned up any new wsi pieces.
*
* If LWS_ADOPT_SOCKET is set, LWS adopts the socket in http serving mode, it's
* ready to accept an upgrade to ws or just serve http.
*
* parent may be NULL, if given it should be an existing wsi that will become the
* parent of the new wsi created by this call.
*/
```

> When the parent wsi is closed for any reason, does the adopted 'child' wsi automatically get closed/destroyed or is it my responsibility to un-adopt the descriptor?

Once lws has adopted a wsi, it owns its lifecycle and will deal with closing it if the remote side closes, or user code decides to close it.  The parent is specified as a wsi, so it's not like you can randomly reference an external fd as the parent... if given, it also is an fd / wsi whose lifecycle is managed by lws.

Parent - child relationship isn't well documented in lws... the basic deal is that children closing detach themselves from the parent and siblings cleanly first, but do not provoke closure of the parent; closure of the parent causes all of the children to close before the parent.  This is used eg in cgi, where the parent is the http connection or stream and it creates three pipe() children for stdin, stdout and stderr to the cgi process... although say stdout closing is a Sign Of The End Times, in fact the parent wsi must stay up to flush whatever output it has and close the http stream nicely, with timing decided by network conditions.

Parents get informed of children closing via a special callback `LWS_CALLBACK_CHILD_CLOSING` in case they care.

> If not, is there a callback telling the adopted file's wsi that the parent has been closed?

The children will be closed before the parent, if the parent closes for any reason.

> If so, does the file descriptor itself get closed by lws when terminating the child's wsi, or is it my job to close it in either the parent's or child's callback?

When lws adopts the fd it treats it the same as if it opened the fd and managed it from the start.  So lws will close any adopted fd itself when the time comes.

In fact internally lws uses the adoption apis to "onboard" fds and socket descriptors it opened internally, there's no difference.

> The reason for the questions is that when the connection is dropped and subsequently re-established because of a network error, the file descriptor will need to be re-adopted by the new client's wsi. I just want to make sure that I'm cleaning up what I am responsible for cleaning up so that I don't get erroneous behavior.

I think you'll find any raw file descriptior will have been closed by lws if it's the child of a network wsi that was closed.  Rather than re-adopted, you'd need to reopen it and adopt the new fd.
