### ISSUE TITLE
why lws_callback_on_writable call __lws_change_pollfd

### ISSUE THREAD

**Issue by zhangpengyf** [warmcat/libwebsockets#1478]
why lws_callback_on_writable call __lws_change_pollfd,
dost it should call lws_change_pollfd with lws_pt_lock in it.
I have a crash in multi thead call to lws_callback_on_writable,
I think this is a bug.

**Comment by lws-team** [comment]
The job of `lws_callback_on_writable()` is to tell the event loop that it wants to hear when POLLOUT is available on the socket.  So it has to call `__lws_change_pollfd()` to make that happen.

The recommended way it to use `lws_cancel_service()` to indicate from other threads that there is something to do.  As shown in the minimal examples, eg

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads/protocol_lws_minimal.c#n116
https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads/protocol_lws_minimal.c#n256

The reason is that although the on_writable processing can be made to detect if it's being called from a non-service thread, actually this only works with poll() event loop (it still has the proviso that only one foreign thread could call it at a time).  With more complex event loops like libuv calling `__lws_change_pollfd()` calls into libuv apis from other threads which blows it up.

Using `lws_cancel_service()` is much more robust, it just has the thread put a byte into a pipe, it's entirely threadsafe.  The pipe having something in it interrupts the event loop, and makes it callback from the event loop context with LWS_CALLBACK_EVENT_WAIT_CANCELLED, where you can figure out what has happened and do any calls to one_writable() or whatever else you need from the service thread context itself.
