### ISSUE TITLE
SSE connection close automatically

### ISSUE THREAD

**Issue by Choxmi** [warmcat/libwebsockets#1485]
The [sse sample](https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/http-server/minimal-http-server-sse) close the connection after some time. (count is around 369) 

This is the es.onerror output:
`error
​
bubbles: false
​
cancelBubble: false
​
cancelable: false
​
composed: false
​
currentTarget: null
​
defaultPrevented: false
​
eventPhase: 0
​
explicitOriginalTarget: EventSource { url: "https://192.168.1.68:8082/sse/Test", withCredentials: false, readyState: 2, … }
​
isTrusted: true
​
originalTarget: EventSource { url: "https://192.168.1.68:8082/sse/Test", withCredentials: false, readyState: 2, … }
​
returnValue: true
​
srcElement: EventSource { url: "https://192.168.1.68:8082/sse/Test", withCredentials: false, readyState: 2, … }
​
target: EventSource { url: "https://192.168.1.68:8082/sse/Test", withCredentials: false, readyState: 2, … }
​
timeStamp: 31603
​
type: "error"`

Is this the normal behavior? Or have I done something wrong? (Actually I didn't change anything)

Please help me with this. Thanks in advance.

**Comment by lws-team** [comment]
It's caused by a separate check in lws for wsi that hold on to the headers a long time

[2019/01/30 14:24:23:9408] NOTICE: ah excessive hold: wsi 0xba5250

I really recommend looking at the lws logs if you feel you don't understand what it's doing, at the least if you paste the logs it gives me a clue and more often than not in the logs, it tells you what it is doing.

For ws connections, the ah is dropped when the connection upgrades, but for SSE there's nothing really to say that it's "entering SSE mode", it's just a convention.  It remains actually an http connection that hangs on to the ah for a long time.

On master, I pushed a patch adding an api `lws_http_headers_detach(wsi)` that lets you drop the ah yourself, and calls it from both SSE minimal examples when the SSE connection is made.  I confirmed it reaches 501 with that, after that it should go on forever (or until a write fails, or the client or something else closes it).
