### ISSUE TITLE
How the server knows that to which client it has to send the response?

### ISSUE THREAD

**Issue by Bharanitharan02** [warmcat/libwebsockets#1493]
Hi I am trying to implement multiple LWS clients with one LWS server? In this case if server wants to send the data to particular client then how the server will knows that to this client only i want to send the data?
Please help me to resolve this issue??

**Comment by lws-team** [comment]
You need to study the provided minimal examples.

In lws each connection or stream has its own `struct lws` instance, usually in a var `wsi` in the code.  When you get a callback, the wsi it applies to is passed as the first argument, eg

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-dynamic/minimal-http-server-dynamic.c#n40

Typically the server realizes it wants to send something to a specific client connection / stream / wsi because it connected, or the client just sent something.  In those cases, the relevant wsi is available from the callback already, you request a callback when it's writable

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-dynamic/minimal-http-server-dynamic.c#n88

When the writable callback comes for that wsi, the server can send the data to it.  To help the server track its own application state for individual connections / streams / wsi, you can attach your own user data to each client wsi, called a `pss` in the code.  You tell the protocol how much space to reserve for your per-wsi pss

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-dynamic/minimal-http-server-dynamic.c#n179

... and lws will automatically attach an all-zeroes one to each new wsi when the incoming client connection using that protocol is accepted...

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-dynamic/minimal-http-server-dynamic.c#n43

If you need to send to a client asynchronously, without a client event triggering it, you need to track client established and close callbacks and keep your own list of active wsi, eg

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads/protocol_lws_minimal.c#n204-215

**Comment by Bharanitharan02** [comment]
Hi, Thank you for your quick response and explanation. May i know is there any variable in the struct lws which is identifying the particular client ?
For eg: my module is sending data to LWS client then it sends to LWS server then it sends to other module. In this case if LWS server gets the response from one Module, then based on the which var in struct lws, it is identifying to which LWS client i have to send data? Please explain me

**Comment by lws-team** [comment]
> May i know is there any variable in the struct lws which is identifying the particular client ?

`struct lws` is deliberately opaque in the user api, ie, what's in it and what it does is private to the library internals.  The public api

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets

defines what you can do with it.

> my module is sending data to LWS client then it sends to LWS server then it sends to other module. In this case if LWS server gets the response from one Module, then based on the which var in struct lws, it is identifying to which LWS client i have to send data?

I already explained this at length.  What I suggest is what I suggested already... pick a minimal example that is close to your scenario and play with it, eg minimal ws server, confirm it works like you want by opening two clients on it and add logs in the callback to see how and why it works.
