### ISSUE TITLE
Could not able to see the HTTP request and Websocket upgrade packets while running LWS client/server with SSL

### ISSUE THREAD

**Issue by Bharanitharan02** [warmcat/libwebsockets#1503]
I am running libwebsocket client and server with SSL like below,
./libwebsocket-test-server --ssl
./libwebsocket-test-client --ssl <server_ip:port>

When i captured the packets using tcpdump i could not able to see any HTTP packets and websocket Upgrade packets. As per assumption when i am running LWS with SSL then it will be act as a WSS. Is my assumption correct?

**Comment by lws-team** [comment]
> When i captured the packets using tcpdump i could not able to see any HTTP packets and websocket Upgrade packets. As per assumption when i am running LWS with SSL then it will be act as a WSS. Is my assumption correct?

Yes... in fact the examples and test app serve JS that enforces that

https://libwebsockets.org/git/libwebsockets/tree/test-apps/test.js#n159-183

if the HTML was served on an `https://` URL then it uses a `wss://` URL for the ws link back.

You can't "see" anything useful on the wire like that because it's all encrypted inside TLS tunnels.
