### ISSUE TITLE
windows client coredump when it is running

### ISSUE THREAD

**Issue by miaohongbiao** [warmcat/libwebsockets#1512]
hi,
i am developing a program by lws, i have a service that develop by lws and it's OK so far, but the client often some err when it's running, the service only send some data to client, and the speed mybe is fast, 
it was normal at first, but soon after, the client crashed, there are some pic for this , please help me. tks.
lws version 3.1.-stable

**Comment by lws-team** [comment]
You seem to be saying it crashes here

https://libwebsockets.org/git/libwebsockets/tree/lib/roles/ws/client-parser-ws.c#n577

... but what actually crashes it?  wsi can't be bad... wsi-> protocol or wsi->protocol->callback is bad?  wsi->protocol seems sane, it can show .name ok, and since that's a const static struct where you set the .callback, that should be sane too.  So it seems actually it crashes somewhere in your protocol callback, despite what your debugger says.

Throwing "something crashes" (esp. In your code I don't have) and some photos on me with "pls help me tks" usually isn't the correct debugging technique.  If I understood it, that your callback code is what blows, not lws, you should put logging in your LWS_CALLBACK_CLIENT_RECEIVE and LWS_CALLBACK_CLIENT_RECEIVE_PONG if you have one and follow in detail what it does before it crashes there.

**Comment by lws-team** [comment]
Any news about the debugging logs?

**Comment by lws-team** [comment]
Well, let's reopen this if something to look at appears.
