### ISSUE TITLE
address 

### ISSUE THREAD

**Issue by ypiker** [warmcat/libwebsockets#1513]
Libwebsocket does not seem to be able to access structural addresses like 127.0.0.1:9651/SomeInfo?

**Comment by lws-team** [comment]
Lws itself wants the various pieces separately... because you may have them separately and then no parsing is needed: it's the smallest memory and code footprint then.

If you have `"a://b:c/d"` then you can use `lws_parse_url()`

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-misc.h#n401-425

to parse it into the pieces.... in-situ so it's still cheap to handle.
