### ISSUE TITLE
maybe bug  when using smp with libevent

### ISSUE THREAD

**Issue by BrentHuang** [warmcat/libwebsockets#1524]
version 3.1.0, on linux

When using smp (multi threads) with libevent, I found the ws-callback only runs in the first thread event loop. It seems to be a bug.

[TRACE  demo_server 0x7f33498fc700 2019-03-19 14:34:46 903.218 thread_center_interface.h:132] ws thread #0 OnThreadStartOK, sink: 0x1fe0c80
[TRACE  demo_server 0x7f33498fc700 2019-03-19 14:34:46 903.364 ws_controller.cpp:132] LWS_CALLBACK_PROTOCOL_INIT
[TRACE  demo_server 0x7f33498fc700 2019-03-19 14:34:46 903.374 ws_controller.cpp:132] LWS_CALLBACK_PROTOCOL_INIT
[INFO   demo_server 0x7f33498fc700 2019-03-19 14:34:46 903.393 ws_threads.cpp:28]    vhost default: cert expiry: -853d

[TRACE  demo_server 0x7f33490fb700 2019-03-19 14:34:46 903.420 thread_center_interface.h:132] ws thread #1 OnThreadStartOK, sink: 0x1fe3c80

in the above log,
0x7f33498fc700 is thread 0，  0x7f33490fb700 is thread 1.  You can see LWS_CALLBACK_PROTOCOL_INIT called twice in thread 0.

And in the struct lws_context_creation_info, .foreign_loops can be an array and point to each libevent event loop, but .user is not an array. If .user is also an array and can point to each of my thread objects, that will be better. So I can get .usr by lws_vhost_user(lws_get_vhost(wsi)) in each thread event loop and then call methods in my thread class.

ps, in minimal-http-server-eventlib-foreign example, change "	set(extralibs ${extralibs} event)" to "	set(extralibs ${extralibs} ${LWS_LIBEVENT_LIBRARIES})"   because libevent may be not installed in system path.

my code: 'https://github.com/Confucius-Mencius/common_component/blob/master/ws_threads/src/ws_controller.cpp'

**Comment by lws-team** [comment]
At the moment there's no smp example for anything except poll event loop... you're slightly ahead of the curve with this.

The smp stuff is designed so each pt has its own event loop, which may be any supported one.  So it should be compatible with this kind of thing.

But I think the first move would be try try to make a `minimal-http-server-eventlib-smp` and see what happens.

> And in the struct lws_context_creation_info, .foreign_loops can be an array and point to each libevent event loop, but .user is not an array. 

I think this won't block you, because what user points to is wholly defined by the user code.  So you can make it point to a struct, containing an a thread id -> thread-specific user data map.  Maybe it does need a separate per-pt void ** in the info for user data bound to the service thread.

> ps, in minimal-http-server-eventlib-foreign example, change " set(extralibs ${extralibs} event)" to " set(extralibs ${extralibs} ${LWS_LIBEVENT_LIBRARIES})" because libevent may be not installed in system path.

Thanks... I think that will only work when building the examples inside lws?  The overriden build paths are not exported atm in lws_config.h... generally the minimal example CMakeLists.txt also allows building outside lws.  Maybe it's enough to export the build paths used for lws in lws_config.h and inherited by the standalone examples, then cmake symbols like LWS_LIBEVENT_LIBRARIES could be used there.

**Comment by lws-team** [comment]
I pushed a start on `minimal-http-server-eventlib-smp` on master.

At least for libevent (`--event`) it broadly seems to work, but has trouble exiting with ^C... you have to kill it with a SIGTERM, like `kill <pid>`, externally.

It can survive `ab -n 100000 -c 100 http://127.0.0.1:7681/libwebsockets.org-logo.svg` OK here.

> I found the ws-callback only runs in the first thread event loop. 

I see he gets up to >300% cpu when ab is running... I think it's balancing on all of them,

**Comment by BrentHuang** [comment]
Thank you very much for reply.

I fetch the master branch and build the minimal-http-server-eventlib-smp example with:

	ZLIB_INSTALL_DIR=/opt/third_party/debug/zlib
	OPENSSL_INSTALL_DIR=/opt/third_party/debug/openssl
	LIBEVENT_INSTALL_DIR=/opt/third_party/debug/libevent

	/usr/bin/cmake -DCMAKE_BUILD_TYPE=Debug \
		-DLWS_WITH_LIBEVENT=ON -DLWS_UNIX_SOCK=ON -DLWS_WITH_HTTP2=ON -DLWS_WITH_MINIMAL_EXAMPLES=ON \
		-DLWS_ZLIB_INCLUDE_DIRS=${ZLIB_INSTALL_DIR}/include \
		-DLWS_ZLIB_LIBRARIES="${ZLIB_INSTALL_DIR}/lib/libz.so" \
		-DLWS_OPENSSL_INCLUDE_DIRS=${OPENSSL_INSTALL_DIR}/include \
		-DLWS_OPENSSL_LIBRARIES="${OPENSSL_INSTALL_DIR}/lib/libssl.so;${OPENSSL_INSTALL_DIR}/lib/libcrypto.so" \
		-DLWS_LIBEVENT_INCLUDE_DIRS=${LIBEVENT_INSTALL_DIR}/include \
		-DLWS_LIBEVENT_LIBRARIES="${LIBEVENT_INSTALL_DIR}/lib/libevent_core.so;${LIBEVENT_INSTALL_DIR}/lib/libevent_extra.so;${LIBEVENT_INSTALL_DIR}/lib/libevent_pthreads.so;${LIBEVENT_INSTALL_DIR}/lib/libevent_openssl.so" ..

	make -j 2


when run it , it print:
[2019/03/21 11:33:23:5872] NOTICE:   Service threads: 1
[2019/03/21 11:33:23:5873] USER: 8   1

The corresponding code is:
lwsl_notice("  Service threads: %d\n", lws_get_count_threads(context));  // your code
lwsl_user("%d   %d\n", info.count_threads, lws_get_count_threads(context));  // I added

you see, "Service threads: 1", not 8.

**Comment by BrentHuang** [comment]
Thank you very much for reply.

I fetch the master branch and build the minimal-http-server-eventlib-smp example with:

	ZLIB_INSTALL_DIR=/opt/third_party/debug/zlib
	OPENSSL_INSTALL_DIR=/opt/third_party/debug/openssl
	LIBEVENT_INSTALL_DIR=/opt/third_party/debug/libevent

	/usr/bin/cmake -DCMAKE_BUILD_TYPE=Debug \
		-DLWS_WITH_LIBEVENT=ON -DLWS_UNIX_SOCK=ON -DLWS_WITH_HTTP2=ON -DLWS_WITH_MINIMAL_EXAMPLES=ON -DLWS_MAX_SMP=100 \
		-DLWS_ZLIB_INCLUDE_DIRS=${ZLIB_INSTALL_DIR}/include \
		-DLWS_ZLIB_LIBRARIES="${ZLIB_INSTALL_DIR}/lib/libz.so" \
		-DLWS_OPENSSL_INCLUDE_DIRS=${OPENSSL_INSTALL_DIR}/include \
		-DLWS_OPENSSL_LIBRARIES="${OPENSSL_INSTALL_DIR}/lib/libssl.so;${OPENSSL_INSTALL_DIR}/lib/libcrypto.so" \
		-DLWS_LIBEVENT_INCLUDE_DIRS=${LIBEVENT_INSTALL_DIR}/include \
		-DLWS_LIBEVENT_LIBRARIES="${LIBEVENT_INSTALL_DIR}/lib/libevent_core.so;${LIBEVENT_INSTALL_DIR}/lib/libevent_extra.so;${LIBEVENT_INSTALL_DIR}/lib/libevent_pthreads.so;${LIBEVENT_INSTALL_DIR}/lib/libevent_openssl.so" ..

	make -j 2


after then, I run it, the result is as you said.

you see, I set "-DLWS_MAX_SMP=100" when build libwebsockets, if not, the LWS_MAX_SMP is 1. So how to decide the LWS_MAX_SMP value? By hand?

**Comment by lws-team** [comment]
> how to decide the LWS_MAX_SMP value?

It's the worst case number of service threads the library is could handle... you can choose a number of service threads to request to use at runtime (-t <threads> in the minimal example).  If what you asked for is more than LWS_MAX_SMP, it's trimmed to LWS_MAX_SMP.  Otherwise that many service threads will be used.  Building lws with LWS_MAX_SMP != 1 causes lws to build in some internal pthreads locking that is eliminated from the build when LWS_MAX_SMP is 1, so LWS_MAX_SMP > 1 and -t 1 is not 100% the same as LWS_MAX_SMP=1.

**Comment by BrentHuang** [comment]
ok， I rebuild with LWS_MAX_SMP=256， and with libevent.   I found my http callback is balancing between two theads,   but my ws callback still runs only in one thread.

**Comment by lws-team** [comment]
> LWS_MAX_SMP=256

These big numbers don't do anything useful... if you have a cpu that can run 8 threads simultaneously, you'll never want more than 8 service threads.  So you can just set it according to that.

> [version 3.1.0]

The SMP stuff with event libraries is not supported on any version atm.  Master is the best bet but it's going to require work there to make it usable on all the event loops lws otherwise supports.

>  I found my http callback is balancing between two theads, but my ws callback still runs only in one thread.

How the balancing works is at incoming fd accept / adoption time, the wsi is attached to the pt with the least active fds already attached to it.  So it doesn't care if that's carrying ws or http.

**Comment by BrentHuang** [comment]
“ I found my http callback is balancing between two theads, but my ws callback still runs only in one thread.”   
-- I mean in version 3.1.0, my http callback runs in two threads, but my ws callback runs only in one thread. They share the same lws_context.  It seems to a bug.  You can look at my code: https://github.com/Confucius-Mencius/common_component/blob/master/ws_threads/src/ws_controller.cpp

I'm looking forward to the new version.

**Comment by lws-team** [comment]
Well, I personally don't have a use for this atm.  So the situation won't magically change before the next release... the smp stuff is a long term goal.  Everything related to libuv especially took weeks to get right.

As I say the wsi levelling is done before lws knows if the connection will upgrade to ws or not.  So while I'm sure there are still bugs, AFAIK that particular one is likely not what you think.

**Comment by BrentHuang** [comment]
ok, I get it.

I print thread id in callback function. if with the same lws_context,  the ws-protocol callback called in different threads just like the http-protocol callback, that will be right.

I don't know why HTTP is right, but WS is wrong in version 3.1.0.

at start time:
![image](https://user-images.githubusercontent.com/2862064/54736153-c1f20080-4be4-11e9-90ae-56f3aa81577e.png)

when request coming: 
![image](https://user-images.githubusercontent.com/2862064/54736101-85260980-4be4-11e9-8584-b2b0b96b05b7.png)

all request handled in thread 0.

**Comment by BrentHuang** [comment]
> 
> > And in the struct lws_context_creation_info, .foreign_loops can be an array and point to each libevent event loop, but .user is not an array.
> 
> I think this won't block you, because what user points to is wholly defined by the user code. So you can make it point to a struct, containing an a thread id -> thread-specific user data map. Maybe it does need a separate per-pt void ** in the info for user data bound to the service thread.
> 

when I set the .user field in struct lws_context_creation_info, my thread has not been created yet, so there is no thread id.

**Comment by BrentHuang** [comment]
> ok, I get it.
> 
> I print thread id in callback function. if with the same lws_context, the ws-protocol callback called in different threads just like the http-protocol callback, that will be right.
> 
> I don't know why HTTP is right, but WS is wrong in version 3.1.0.
> 
> at start time:
> ![image](https://user-images.githubusercontent.com/2862064/54736153-c1f20080-4be4-11e9-90ae-56f3aa81577e.png)
> 
> when request coming:
> ![image](https://user-images.githubusercontent.com/2862064/54736101-85260980-4be4-11e9-8584-b2b0b96b05b7.png)
> 
> all request handled in thread 0.

When doing stress testing, both threads will process the ws request, but not  absolute balanced between two threads.

Thank you very much~

**Comment by lws-team** [comment]
> When doing stress testing, both threads will process the ws request, but not absolute balanced between two threads.

Because connections can end at any time and in any order (on any pt) really trying to truly keep it balanced would require stuff like migrating wsi between pts while the wsi and connections are still alive... AFAIK it's not worth the effort.

It just takes the approach to apply new wsis to the most idle pt at the time of the connection.  On average that takes it in the right direction for whatever the situation was at that time.
