### ISSUE TITLE
How to control lws_callback_on_writable ()?

### ISSUE THREAD

**Issue by Bharanitharan02** [warmcat/libwebsockets#1526]
Hi I am using one thread which is listening on particular port and sends the data to LWS-Client. And lws-client will send that data to lws-server. For this purpose i am using lws_callback_on_writable(). It is working fine but some internal data's are sending between lws-client to lws-server and i don't want that data's. So how should i avoid that internal data's which is writing from lws-client to server. so that i can use only my data's which is coming from particular port and forwarding to lws-client to lws-server. Please help to address this scenario.

**Comment by lws-team** [comment]
>  It is working fine but some internal data's are sending between lws-client to lws-server and i don't want that data's.

What does it mean "internal data"?

I think maybe what you're noticing is that there's not a 1:1 relationship between requests to call the WRITABLE callback and when it actually gets called. 

 - In the case you call `lws_callback_on_writable()` more than once before it's actually writeable, you will only get one WRITABLE callback.

 - And sometimes, you may get extra WRITABLE callbacks you didn't ask for.

 - If you tried to write something larger than the kernel would accept, lws will buffer the remainder and write it for you in the background, concealing WRITABLE callbacks while it does it.

The answer is to maintain state in your code so that the WRITABLE callback first determines what it wants to do with the opportunity to write something.  if it has already written all the valid data, it can just return 0 without writing anything.

For anything nontrivial, you have to keep state about what you want to write to that peer anyway.
