### ISSUE TITLE
HTTP server with persistent connections, i.e. multiple HTTP requests through single TCP connection

### ISSUE THREAD

**Issue by FohlenAFK** [warmcat/libwebsockets#1528]
Hi guys, 

I'm trying to set up an HTTP server to maintain multiple persistent HTTP / 1.1 connections.
For testing, the server receives the POST request from an HTTP client. The server analyzes it and sends back a message. For this I have specified the keep-alive options as follows:

```
// simple http callback
static struct lws_protocols protocols[] = {
  { "http-only",
    callback_http,
    sizeof(struct per_session_struct),
    8196, /* max frame size / rx buffer */
    0,
    nullptr },
  { nullptr, nullptr, 0, 0, 0, nullptr } /* terminator */
};


struct lws_context_creation_info info = {};
info.ka_time     = 60;
info.ka_probes   = 3;
info.ka_interval = 1;
context = lws_create_context(&info);
```
But after transmitting the response:
```
case LWS_CALLBACK_HTTP_BODY_COMPLETION:
{
  std::string response = *pss->response_content;
  lws_write_http(wsi, response.c_str(), response.length());
  if (lws_http_transaction_completed(wsi) != 0)
    return -1;
  return 0;
}
```
libwebsocktes shows the message `LWS_CALLBACK_HTTP_DROP_PROTOCOL`

after another 5 seconds
`LWS_CALLBACK_CLOSED_HTTP` and `LWS_CALLBACK_WSI_DESTROY`

I will send another message from the client within these ~5 seconds. Is the `void *user` or `*pss` not the same as before.

How do I achieve a persistent connection in which the session data is stored in the pss?

**Comment by lws-team** [comment]
That's just not what http is.  It's a "stateless" protocol.

For http, you will still see a pss being used, but that's because a single http transaction may live for many times around the event loop.  The pss is storing state for a single transaction lifetime only.

The application may have a higher level concept of a "session" that encompasses multiple http transactions.  But this is done using a cookie or url token.  The next transaction in the session may come from a different socket or even a different source IP.

Lws can do cookie-based sessions, but yo have to manage the cookie by hand.
