### ISSUE TITLE
Multiple client connection to different server

### ISSUE THREAD

**Issue by arunkvnss** [warmcat/libwebsockets#1549]

**Comment by arunkvnss** [comment]
Hi, is it possible to connect to different server using same lws_client context ?

**Comment by arunkvnss** [comment]
actually i have different license for each server, so using same context there is no way right ?. or else can i run multiple websocket client threads with different context ?

**Comment by lws-team** [comment]
Same lws_context, sure.  By default every client connection is treated as a completely separate one... as a separate optimization step for http/1.1 and h2 ones to the same protocol, peer and port may end up being pipelined or muxed on one h2 connection.

"different license" doesn't mean anything to me.

**Comment by arunkvnss** [comment]
I have different client certificates,and ca certificates for each client. So i should need different context right ?

**Comment by lws-team** [comment]
If you are using client certs, they are done via the tls context as you say.  Actually the client tls context is part of the logical vhost, not the lws_context.  It's not difficult to create multiple vhosts on one context

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-multivhost/minimal-http-server.c#n110
https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-multivhost/minimal-http-server.c#n135-144

each of the vhosts can be given different args related to the client cert.

This is highly preferable to multiple contexts, because the event loop lives in the context.  This way everything can live in one big happy event loop.
