### ISSUE TITLE
Unclear how to send a CLOSE request, or close a connection

### ISSUE THREAD

**Issue by snej** [warmcat/libwebsockets#1573]
I'm having trouble figuring out how to send a CLOSE request message. There's no enum value for it in `lws_write_protocol`; instead it says "`LWS_WRITE_CLOSE` is handled by `lws_close_reason()`". But that function doesn't actually send a message, it just stores the error info in some internal metadata. So how do I send the message itself?

My current guess is that it's sent automatically when I close the client connection ... but I can't find an API call to close a connection. As far as I can tell, none of the minimal WS client or server examples ever close a connection, so I can't use them for reference.

**Comment by snej** [comment]
As often happens, I find answers or clues myself right after asking for help. In this case I noticed something in the doc-comment of `lws_close_reason`: "Set reason and aux data to send with Close packet If you are going to _return nonzero from the callback requesting the connection to close_, you can optionally call this to set the reason the peer will be told if possible." [emphasis mine]

So I take it that I close a connection simply by returning a nonzero value from the protocol callback? Meaning that if some external code wants to close the connection, it needs to do something (?) to trigger a protocol callback?

**Comment by lws-team** [comment]
That's the usual way to do it.... not all callbacks have the same semantics for the return code, but generally all the ones you might discover you want to close from will take nonzero as a request to start the close process for that wsi.

It's not the only way though

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-timeout-timer.h#n79-105

since there are some esoteric cases that also need to able to close things that weren't the wsi you were called back with.

**Comment by snej** [comment]
Thanks! Take this as a request to improve the docs — in particular, it would be good to have a high level overview of how the library works and how to use it. (If such exists, I haven't found it, just the API docs.)
