### ISSUE TITLE
Port in lws_context_creation_info not assigned

### ISSUE THREAD

**Issue by pawcijo** [warmcat/libwebsockets#1591]
Why it's no longer possible to get port number from lws_context_creation_info ?
What is the correct way to get it when you pass 0 and it's determined automatically?

It was changed in https://github.com/warmcat/libwebsockets/commit/7ff8f023d150dfee71e828908d0634f53d16bda0

 //info->port = vhost->listen_port;

**Comment by lws-team** [comment]
The reason was it allowed the context info struct passed to create context and create vhost to be const... on some devices that means it no longer has to take up any ram.

The correct way to do it now is

 - create an explicit vhost... creating a vhost takes the same info struct (also const) so this is a matter of setting LWS_SERVER_OPTION_EXPLICIT_VHOSTS in info.options

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-multivhost/minimal-http-server.c#n110

and then just call lws_create_vhost() on the same info struct, returning the opaque lws_vhost *, or NULL if trouble

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-multivhost/minimal-http-server.c#n140-143

 - get the port number from the vhost *

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n889-895

**Comment by pawcijo** [comment]
Thank you for fast response i got it now :+1:
