### ISSUE TITLE
Payload total length

### ISSUE THREAD

**Issue by nidoro** [warmcat/libwebsockets#1600]
According to the [RFC](https://tools.ietf.org/html/rfc6455#section-5), it is possible to know the total payload length ahead of time in the first fragment. But it seems there is no API to get this value. The documentation of `lws_remaining_packet_payload` says that this returns the unread amount of the current fragment, not the message. Why is that?

Also, it would be nice if this `lws_remaining_packet_payload` function was listed with the other fragment functions (is_first, is_final...) in the docs.

**Comment by lws-team** [comment]
From your link to rfc6455

```
5.4.  Fragmentation

   The primary purpose of fragmentation is to allow sending a message
   that is of unknown size when the message is started without having to
   buffer that message.
```

the **payload** length is the length of the fragment payload.  Only in the case the first fragment has FIN set, does that align with the message length.

**Comment by davehorton** [comment]
Is there an api call such that I can see if the fragment has FIN set?

**Comment by lws-team** [comment]
https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-ws-state.h?h=main#n40-46

**Comment by davehorton** [comment]
ah ok.  I want to make sure I am handling this correctly.  I am facing this scenario:

1. I get the first fragment; i.e. lws_is_first_fragment(wsi) is true
2. The fragment len is 1024 and lws_remaining_packet_payload returns 3058
3. Therefore I allocate a buffer of 4082 to read what I *think* will be the entire message
4. However, I then get successive reads of the following length (without a final fragment): 1024,1024,1024, 1010, 1024,1024,1010,1024,1024
5. That last is the final fragment

Unfortunately, my current code segfaults due to buffer overrun as I made the (faulty?) assumption that I would only be getting a message of length 4082..

**Comment by lws-team** [comment]
> Unfortunately, my current code segfaults due to buffer overrun 

You shouldn't trust what you're being sent that much, it should also check if it is bigger than what you were told and handle it itself if so.

I'm pretty sure there's no bug in fin management.  If you are using permessage-deflate, try turning that off.

**Comment by davehorton** [comment]
yes, so far I have changed the code to do the check as you suggest.  But that leaves me with the problem/question of how I am receiving this.  This so far has only happened in one environment, where the far end websocket server (I am acting as the client) is behind a kubernetes ingress.  Not sure how or why that would have anything to do with it...

I dont think I have permessage-deflate on but will check and turn if off if so.
FWIW I am running version 3.2.3

**Comment by lws-team** [comment]
There is nothing I can do about your problem.  If you think it's a bug, you can dump the traffic with `LWS_TLS_LOG_PLAINTEXT_RX` and find out if it is a bug in what the server sent, or in lws, or if it is all correct, a bug on your side.  I can't know or guess from here.

**Comment by davehorton** [comment]
Understood.  Will do, thanks for the clarifications.

**Comment by davehorton** [comment]
I think I have clarified the issue is my misunderstanding of the value returned by `lws_remaining_packet_payload.`

Here is a screenshot of the network trace:

![image](https://user-images.githubusercontent.com/1884973/149545706-eb5d38a5-4b3a-4aec-a257-481060587de2.png)

I am receiving a long text message from the far end ws server at ip 77.70.114.202 in this case.

The initial frame comes in with an extended payload length of 4082 -- this corresponds to what I get when I call `lws_remaining_packet_payload.` and causes me to allocate a buffer of that size.

However, I then get a lot of further packets (about 55k in all) before I get a frame with FIN set (causing lws_is_final_fragment to return true).

I guess I now understand that I need to allow for lws_remaining_packet_payload returning a number that is smaller than the length of bytes I may get in further reads before lws_is_final_fragment returns true.

**Comment by lws-team** [comment]
Nothing tells you the message size in ws framing.  Messages may literally be endless.  This is a ws thing not an lws thing.

Fragments tell you the fragment size.  If the first fragment is not also the final one of the message, then nobody knows how much more is coming or how many fragments it will come in, before the end of the final fragment.
