### ISSUE TITLE
Proper\recommended way to go about "neatly" making a list of protocols

### ISSUE THREAD

**Issue by Suicosmos** [warmcat/libwebsockets#1605]
Hello, I list my protocols in a seperate .c file and i can use the following

#define CLIENT_PROTOCOLS \
        { \
                "example", \
                example_callback, \
                0, \
                10, \
                0, NULL, 0 \
        }

with no issues by including it into my main .c file, but when i expand the list as such below

#define CLIENT_PROTOCOLS \
        { \
                "example", \
                example_callback, \
                0, \
                10, \
                0, NULL, 0 \
                "example2", \
                example2_callback, \
                0, \
                10, \
                0, NULL, 0 \
        }

I get various syntax errors. I've tried various methods to extend my list. What is the recommended way to do so in a separate .c file as shown in the minimal examples?

**Comment by lws-team** [comment]
Well... there are a couple of C things wrong with what you pasted...multiline #defines must have backslashes at the end of each line to continue the definition.

When you are declaring an array of struct lws_protocols, each struct protocols member of the array must have its own { } around it, they can't just run into each other as you are trying to do there.

But in terms of the "recommended" way, master has a much more convenient way to isolate the definition of each protocol from the "list" part, where you can eliminate the things that are wrong above... you just need to export a symbol for each protocol (not the definition itself) and arrange pointers to those symbols in an array, ending with NULL.  In this example they are all defined in one file, but the advantage of this technique is you only need the symbol for the lws_protocols definitions, they can be completely private in other files otherwise.

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-dynamic/minimal-http-server-dynamic.c#n178-181

Then instead of setting info.protocols as in the old way, you set info.pprotocols to your list of pointers to the protocols.

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-dynamic/minimal-http-server-dynamic.c#n271

**Comment by Suicosmos** [comment]
Thank you ^_^
