### ISSUE TITLE
How to control reconnet?

### ISSUE THREAD

**Issue by jiamuluo** [warmcat/libwebsockets#1627]
I use version 3.1 with libev,simple code like this
```
struct lws_context *context;
int connect_server(void)
{
struct lws_client_connect_info serverInfo;
//init serverInfo
lws_client_connect_via_info(&serverInfo);
}
int webserver_init(void)
{
  //init info
   context = lws_create_context(&info);
}

int main()
{
//something wilh ev
webserver_init()
ev_loop();
}
```
when i get LWS_CALLBACK_CLOSED or LWS_CALLBACK_CLIENT_CONNECTION_ERROR in callback function,i will call lws_cancel_service(lws_get_context(wsi)) and after 2 seconds i will call connect_server.But sometimes i find device will  send two or more tcp sync requests at one moment that i see in wireshark.I think i do something wrong,but I donnot find it.please give some advice or show me some sample code.Thanks.

**Comment by lws-team** [comment]
Although this is for server, it shows how to use libev

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib/minimal-http-server-eventlib.c

There's also this showing how to integrate with a "foreign", ie, already existing ev loop

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib-foreign/minimal-http-server-eventlib-foreign.c

For client reconnect (ie, "nailed up" client connection) including a delay between tries, look at how this does it

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-client/minimal-ws-client-pmd-bulk/protocol_lws_minimal_pmd_bulk.c

**Comment by jiamuluo** [comment]
my libev is ok. problem is reconnet.so sorry ,mybe i donnot find something valueable about reconnect in protocol_lws_minimal_pmd_bulk.c .Now  i am trying to call webserver_init and call lws_connent_distroy if need when i get disconnect message.I think websocket will start from origin status.this way is right?By the hand,i wanna know that how to recycle resource,if i do reconnect,just call lws_connent_distroy ?

**Comment by lws-team** [comment]
You should look closer... it shows how to use the vhost-protocol timer to schedule the retry without trying to do everything back-to-back.  That's good from the point of view otherwise a network problem will make you spin at 100% cpu trying to reconnect.

And if you looked closer you'd see the answer to your question, you cannot reuse the wsi, lws takes responsibility for wsi lifecycle including destroying it (you will get callbacks on your protocol informing you).  As shown in the example, retry means making a new connection.
