### ISSUE TITLE
set socket opts failed

### ISSUE THREAD

**Issue by 1046811284** [warmcat/libwebsockets#1637]
how   to  handle   about  return    "set socket opts failed";    when connect failed;

**Comment by lws-team** [comment]
What's your platform?  Which socket op failed?  What did errno say?

**Comment by 1046811284** [comment]
hi , i am win10 Platform;  And  This is only on a small part of the computer;

error  at 667 line of  client-handshake.c  ==>  "cce = "set socket opts failed";"

sorry ,My English is not good;

i  want to know , how to clean windows evirenment,  Let it Work;   thanks

**Comment by lws-team** [comment]
I don't have or use windows.  So you'll need to debug it a bit to find out what the problem is.

lws has a platform-specific function to set the socket options.

https://libwebsockets.org/git/libwebsockets/tree/lib/plat/windows/windows-sockets.c#n54

He does maybe three things

 - set tcp keepalive
 - set TCP_NODELAY (nagle)
 - set nonblocking

You should edit this to find out which one fails and print errno so we can get an idea of what its problem is.

**Comment by 1046811284** [comment]
thank you very much~

**Comment by lws-team** [comment]
There's nothing for me to do unless there's more info at least about where the problem is.  This stuff works for other windows users AFAIK.

**Comment by kristjanvalur** [comment]
We have a handful of users experiencing this on windows 10, but they are out in the field, so its a bit hard to know what's going on.
Looking at the source, and the fact that nothing is logged, it can only be related to keepalive, since the nagle settings aren't checked for return values.
`lws_plat_set_socket_options(struct lws_vhost *vhost, lws_sockfd_type fd,
			    int unix_skt)
{
	int optval = 1;
	int optlen = sizeof(optval);
	u_long optl = 1;
	DWORD dwBytesRet;
	struct tcp_keepalive alive;
	int protonbr;
#ifndef _WIN32_WCE
	struct protoent *tcp_proto;
#endif

	if (vhost->ka_time) {
		/* enable keepalive on this socket */
		optval = 1;
		if (setsockopt(fd, SOL_SOCKET, SO_KEEPALIVE,
			       (const char *)&optval, optlen) < 0)
			return 1;

		alive.onoff = TRUE;
		alive.keepalivetime = vhost->ka_time * 1000;
		alive.keepaliveinterval = vhost->ka_interval * 1000;

		if (WSAIoctl(fd, SIO_KEEPALIVE_VALS, &alive, sizeof(alive),
			     NULL, 0, &dwBytesRet, NULL, NULL))
			return 1;
	}

	/* Disable Nagle */
	optval = 1;
#ifndef _WIN32_WCE
	tcp_proto = getprotobyname("TCP");
	if (!tcp_proto) {
		lwsl_err("getprotobyname() failed with error %d\n", LWS_ERRNO);
		return 1;
	}
	protonbr = tcp_proto->p_proto;
#else
	protonbr = 6;
#endif

	setsockopt(fd, protonbr, TCP_NODELAY, (const char *)&optval, optlen);

	/* We are nonblocking... */
	ioctlsocket(fd, FIONBIO, &optl);

	return 0;
}
`
I will add logging to figure out exactly what is going on, but my suggestion here, since keepalive really isn't essential (it is superseeded by websocket ping) is that this should be handled as a soft failure.

**Comment by lws-team** [comment]
Although whether you're using ws or not depends on the user, on master there's a new approach called 'connection validity' checking. https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.lws_retry.md which generates PING / PONGs automatically on any protocol that supports them, as well as factoring in user assurances they just saw proof traffic is passing in both directions.  So generally tcp keepalive is superceded by that at least on master... please send a patch to log and ignore the related api fails.

**Comment by kristjanvalur** [comment]
So, added logging revealed that a lone user in china is failing his getprotobyname("TCP") with error WSANO_DATA, 11004
Possibly it should be lower case, such as all the examples I've seen of its use online.
Anyway, I'll fallback to protcol number 6 in this case and continue with a warning.  i'll submit a patch for the added logging and this fallback.
