### ISSUE TITLE
Empty closing frame

### ISSUE THREAD

**Issue by dmitryduka** [warmcat/libwebsockets#1643]
Hello, I'm using libwebsockets 3.1.0 on the server and a different library on the client. On the client side a streaming style API is provided which sends a websocket message broken in frames. Whenever user indicates that the stream is now "finished", the message is closed by sending an empty frame (no payload), with fin set to true. This is demonstrated here in the output from Wireshark. 

![image](https://user-images.githubusercontent.com/1927568/62066764-c1c0dc00-b23a-11e9-8a8f-7d2233a0130e.png)

It seems that on the server side (which uses libwebsockets), LWS_CALLBACK_RECEIVE callback is not called for such a frame. I guess this is due to the fact that technically there is no new data available.

Is there a way to understand that the message is now closed, even if the payload size in the last frame is zero?

Thanks!

**Comment by lws-team** [comment]
> Whenever user indicates that the stream is now "finished", the message is closed by sending an empty frame (no payload), with fin set to true.

That's up to the client implementation.  RFC6455 itself requires you to transmit a fragment to deliver the information on the wire that FIN has come.  Valid and possible ways to do that are in a BINARY or TEXT opcode frame, ie, it was also the first and only fragment; in a CONTINUATION opcode frame, ie, it was the second or subsequent fragment; and either way the fragment may or may not have any payload.

The client code could have set FIN on the last frame it sent with non-NULL payload... it's up to it that it generated basically a NULL fragment to deliver just the FIN.

> Is there a way to understand that the message is now closed, even if the payload size in the last frame is zero?

Unfortunately RFC6455 also supports endless messages with unknown size... while you kept sending CONTINUATION with payload and without FIN, the message is incomplete and you don't know how long it is beforehand.  The worse problem is also that we swallow the "event" where you had a chance to notice FIN had come.

Lws does support zero length EOM handling for permessage-deflate case, since it doesn't know for sure that the decompressor with something in it will actually emit any decompressed bytes before completing.  But looking at the code it's strictly for decompression.

Does this help (on v3.1-stable)?

```
diff --git a/lib/roles/ws/ops-ws.c b/lib/roles/ws/ops-ws.c
index 247977747..02dd46212 100644
--- a/lib/roles/ws/ops-ws.c
+++ b/lib/roles/ws/ops-ws.c
@@ -596,23 +596,16 @@ drain_extension:
 			wsi->socket_is_permanently_unusable = 1;
 			return -1;
 		}
-#endif
-		if (
-#if !defined(LWS_WITHOUT_EXTENSIONS)
-		    rx_draining_ext &&
-#endif
-		    ebuf.len == 0)
-			goto already_done;
 
-		if (
-#if !defined(LWS_WITHOUT_EXTENSIONS)
-		    n &&
-#endif
-		    ebuf.len)
+		if (rx_draining_ext)
+				goto already_done;
+
+		if (n && ebuf.len)
 			/* extension had more... main loop will come back */
 			lws_add_wsi_to_draining_ext_list(wsi);
 		else
 			lws_remove_wsi_from_draining_ext_list(wsi);
+#endif
 
 		if (wsi->ws->check_utf8 && !wsi->ws->defeat_check_utf8) {
 			if (lws_check_utf8(&wsi->ws->utf8,
```

**Comment by dmitryduka** [comment]
Hi Andy, your patch helps, thank you very much. If I understand the patch correctly, it should also handle an empty starting frame. Is that correct?

From my side this is no longer an issue, so this can be closed.
Thanks for the timely response and for keeping the library in a good shape!

**Comment by lws-team** [comment]
Great.

**Comment by dmitryduka** [comment]
> If I understand the patch correctly, it should also handle an empty starting frame. Is that correct?

Since you didn't explicitly confirm it, I assume this is correct? :)

**Comment by lws-team** [comment]
Probably... something else would have to get in the way since this code would allow it.

**Comment by dmitryduka** [comment]
Got it, thanks.
