### ISSUE TITLE
GET and POST method invocation for a single client

### ISSUE THREAD

**Issue by RahulNewbie** [warmcat/libwebsockets#1669]
Hi All,

First of all, many thanks for developing the library. I am a beginner in Libwebsockets library and currently facing an issue.

My application consists of two components, HTTP server, and HTTP client. Client first calls GET method to get some data from Server and then do some operation with the data. Then Client call POST method to send the data(result after the operation) to the server. 

In my http_client application main function, i did something like this as below snippet,
struct lws_client_connect_info i;
struct lws_context *context;
-- some code --
i.path = "/";
i.host = i.address;
i.origin = i.address;
i.method = "GET";
lws_client_connect_via_info(&i);
--some code --
i.method = "POST";
lws_client_connect_via_info(&i);

I used the same lws_client_connect_info and lws_context  in both call.  As per code, GET should get call first and then POST will get invoked. But, while executing, POST is getting called first and leading to a wrong result for my application. It looks like, POST is getting priority over GET method.

Can anyone give me an example code to show, how to implement this. Also, please let me know if i did something wrong in implementation.

**Comment by lws-team** [comment]
It's OK to reuse the same info struct.  It's allowed to be defined on the stack, so the connect_via_info() call either uses or copies everything out of it before returning.

You're doing 'network programming' now, it's different in a few ways from programming a single process in one machine.  You're actually trying to coordinate three machines here and many aspects of that are beyond your control.

Your code is creating the GET first, and then "immediately" afterwards, the POST.  The connect_via_info() call returns after setting up the connection request, which will proceed asynchronously.  In short you have set up a race between the get and post which both started at roughly the same time.  Who finishes first is out of your control... but for sure, eg, the GET hasn't been able to complete before the POST has decided what urlargs to use.  What happens if the GET failed?  So your code won't do what you intended.

What you should do for this is just do the GET.  In the protocol callback for that, handle `LWS_CALLBACK_COMPLETED_CLIENT_HTTP`, at this point you know the GET went well and you have the results of it.  Then set up the POST from there.

Since there's no problem in lws here afaik I will close this, but you can still reply here.

**Comment by RahulNewbie** [comment]
Hi Andy,

Thanks for answering my question.

I have a little question on this. 

As you said, I should just implement the GET method and and handle the callback with LWS_CALLBACK_COMPLETED_CLIENT_HTTP and then I should setup the POST there.

As per my knowledge, I can only invoke POST method using lws_client_connect_via_info in http_client main function. Can I setup POST from callbacks?

Please let me know if my understanding is wrong. Can you please give me an example for this, if possible.

**Comment by lws-team** [comment]
There's no restriction about calling `lws_client_connect_via_info()` only from main().

As I mentioned it sets up the connection logically and then returns, it doesn't wait around.  You can call it from the protocol callback of another connection just fine.

Rather than ask to be shown everything, especially in FOSS, nobody has the time or reason to do it.  Here's an important trick so you can find these things yourself, `git grep lws_client_connect_via_info` will show you every example that uses that api, you can check through them and see how they're making use of it.  You'll see it's also used for connection retry in some examples, triggered from the protocol callback.
