### ISSUE TITLE
about the lws_set_timeout the time set is not work?

### ISSUE THREAD

**Issue by Rey1023** [warmcat/libwebsockets#1672]
dear sir:
     when the ws client connect the server , I use lws_set_timeout to set the timeout interval ,but when the network disconnect (I closed the network), I have test many times, ever I set 30 seconds or 5 seconds , but the lws_set_timeout almost worked about 15 seconds, Is the 15 seconds I can't modify ,or there is some error I set the parameter？ 
    lws_set_timeout(wsi, NO_PENDING_TIMEOUT, 30);

**Comment by lws-team** [comment]
> NO_PENDING_TIMEOUT

Use any reason other than this... it cancels the timeout.

Each connection has a single timeout timer, if you are using eg http, there are many steps during the transaction that lws protects by itself.  From lws perspective, the important thing is that each step has some kind of timeout, and it cannot end up with "immortal" http connections when the peer doesn't respond for some time.  Some of these internally decided timeouts are fixed but many of them are related to the vhost creation time info struct member `timeout_secs`

```
	unsigned int timeout_secs;
	/**< VHOST: various processes involving network roundtrips in the
	 * library are protected from hanging forever by timeouts.  If
	 * nonzero, this member lets you set the timeout used in seconds.
	 * Otherwise a default timeout is used. */
```

If you have a ws connection, it has no timeout once established, since it's designed for long waits.  So you can control it completely from `lws_set_timeout()`.

**Comment by Rey1023** [comment]
sorry,sir ,today I set the timeout_secs to 60 ,but the connection is still closed about 15-17seconds.
	lws_context_creation_info info;
	memset(&info, 0, sizeof info); /* otherwise uninitialized garbage */
	info.port = m_serverPort;
	info.protocols = m_protocols;
	info.pvo = &m_options.Get();
	info.fd_limit_per_thread = m_max_connect+2;
	info.pt_serv_buf_size = 32 * 1024;
	info.timeout_secs = 60;
	info.options = LWS_SERVER_OPTION_VALIDATE_UTF8 |
		LWS_SERVER_OPTION_HTTP_HEADERS_SECURITY_BEST_PRACTICES_ENFORCE;
	if (is_support)
	{
		info.ssl_ca_filepath = m_ca_filepath; //"E:\\ca-cert.pem";//
		info.ssl_cert_filepath = m_server_cert_path; //"E:\\client-cert.pem";//
		info.ssl_private_key_filepath = m_server_private_key_path; //"E:\\client-key.pem";//
		info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT /*| LWS_SERVER_OPTION_REQUIRE_VALID_OPENSSL_CLIENT_CERT*/;
	}
	else
	{
		info.ssl_ca_filepath = NULL;
		info.ssl_cert_filepath = NULL;
		info.ssl_private_key_filepath = NULL;
	}

**Comment by lws-team** [comment]
As I said 24 days ago it seems

>>    NO_PENDING_TIMEOUT
> Use any reason other than this... it cancels the timeout.

If it's a ws connection, you can expect to control the timeout from your sidesince they are defined to stay up forever otherwise.  But http connections tend to have limits on both sides as to how long they will allow idle connections to just sit there.  Telling your side to delay ending the connection doesn't do anything about the other side not being willing to let it stay idle.
