### ISSUE TITLE
Feature Request: Documentation search box

### ISSUE THREAD

**Issue by leventis** [warmcat/libwebsockets#1680]
As a user, it would be nice to more easily search the documentation instead of manually browsing modules, or using an external search engine that has indexed the doxygen site:
https://libwebsockets.org/lws-api-doc-master/html/modules.html

Example [`Doxyfile`](http://www.doxygen.nl/manual/config.html#cfg_searchengine) configuration tag:

```
# When the SEARCHENGINE tag is enabled doxygen will generate a search box for
# the HTML output. The underlying search engine uses javascript and DHTML and
# should work on any modern browser. Note that when using HTML help
# (GENERATE_HTMLHELP), Qt help (GENERATE_QHP), or docsets (GENERATE_DOCSET)
# there is already a search function so this one should typically be disabled.
# For large projects the javascript based search engine can be slow, then
# enabling SERVER_BASED_SEARCH may provide a better solution. It is possible to
# search using the keyboard; to jump to the search box use <access key> + S
# (what the <access key> is depends on the OS and browser, but it is typically
# <CTRL>, <ALT>/<option>, or both). Inside the search box use the <cursor down
# key> to jump into the search results window, the results can be navigated
# using the <cursor keys>. Press <Enter> to select an item or <escape> to cancel
# the search. The filter options can be selected when the cursor is inside the
# search box by pressing <Shift>+<cursor down>. Also here use the <cursor keys>
# to select a filter and <Enter> or <escape> to activate or cancel the filter
# option.
# The default value is: YES.
# This tag requires that the tag GENERATE_HTML is set to YES.

SEARCHENGINE           = YES
```

**Comment by lws-team** [comment]
Unfortunately the Doxygen search thing has inline styles and scripts that are incompatible with modern web security policies.

You can create the same content locally easily enough with `doxygen ./libwebsockets.dox` from the top level search dir.

**Comment by lws-team** [comment]
I had a look into doxygen to fix this, although I can refactor the scripts and styles without too much trouble the gnarly fact is Doxygen html stuff is based around a 2012-era version of jquery, updating it breaks their search stuff and I don't have the time or motivation to fix the problems... there are 105 open PRs on Doxygen, so that doesn't give me the feeling this would go anywhere upstream either.

The alternative solution involve php on the server and I'm not doing that, especially after seeing the situation with the upkeep of the other doxygen web pieces.

So I'm sorry I don't see a way to do this in the short term.

**Comment by leventis** [comment]
Yikes, too bad doxygen is losing relevancy.  Thanks for the consideration.
