### ISSUE TITLE
wss client unable to get local issuer certificate on linux embedded system

### ISSUE THREAD

**Issue by Sarah-Wang** [warmcat/libwebsockets#1712]
I want to run wss client  on linux embedded system, but it failed with error message:
E: SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=1).

I tried to generate ca  and keys according to  https://tripzero.io/general/secure-websocket-server-using-autobahn-and-trollius-asyncio/ , it still failed.

` 
info.client_ssl_cert_filepath = "/usr/keys/client.crt";
info.client_ssl_private_key_filepath = "/usr/keys/client.key";
/* info.client_ssl_ca_filepath = "/usr/keys/client.csr"; */
/* info.client_ssl_ca_filepath = "/usr/keys/client.crt"; */
/* info.client_ssl_ca_filepath = "/etc/ssl/certs/Amazon_Root_CA_3.crt"; */
info.client_ssl_ca_filepath = NULL;

`

I tried to change different CA filepath name, but they all ended up with the same failure(unable to get local issuer certificate ).

I run the same code will on Ubuntu 16.04, but it failed on embedded system.
I tried to put Amazon_Root_CA_3.crt on /etc/ssl/certs/, it seem that i did not work.

By the way, The embedded system does not have a CA except the Amazon_Root_CA_3.crt I put in /etc/ssl/certs.

**Comment by lws-team** [comment]
> I want to run wss client
> I tried to generate ca and keys

No... you are all mixed up.  Following random things off the internet without understanding them or if they apply won't help.

Server: has a public cert, signed by someone else's intermediate and / or CA.  Has a private key used to sign negotiations with the client.

Client: does not have any of that.  Just has a copy of the CA that it trusts and any necessary intermediates not sent by the server, so it can verify the server cert and signings it makes with its key.

When you say you are "generating a CA and keys" for a client it's completely wrong.  Your client just has some trusted public certs so it can verify the signature on the server's cert.  There is no "key" on the client.

> preverify_ok=0;err=20;depth=1

The "depth=1" makes it look like you are missing an intermediate cert.  Typically the server's cert is not signed directly by the CA, because they don't want to make the CA private keys that available.  So they sign an intermediate with the real CA, and then sign the server cert with the intermediate.  If the intermediate leaks out, they cancel it and create a new intermediate with the original CA.

Either the server must send you the intermediate along with its own cert, or you must also store the necessary intermediate in your device along with the CA cert so the tls library can validate each step properly.

You can use this site

https://www.ssllabs.com/ssltest/

to find out how browsers validate the server cert... you'll find there are almost always two steps, one  involving an intermediate that you must also have.

**Comment by Sarah-Wang** [comment]
Thank you for your reply very much! 
I think I should try to copy the necessary certs to my embeded system.
I want to copy them to /etc/ssl/certs/ , would it be OK?

**Comment by lws-team** [comment]
Just copying them there doesn't do anything.

For mbedtls you can see several examples where the CA + intermediate certs for warmcat.com or libwebsockets.org are added at runtime.  Eg

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client/minimal-http-client.c#n236-242

If you look in the provided cert file it's the intermediate and the CA cert pasted together in PEM format.

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client/warmcat.com.cer

When you connect to the server, he sends his cert and trusting the CA one is enough to confirm the server cert.

Doing this should also be enough for openssl if that's the only cert you want to trust.

**Comment by Sarah-Wang** [comment]
Thank you very very much for you kind help! I made mistakes before and you lead to a right way.

I use https://www.ssllabs.com/ssltest/ to find out which intermediate I need. It is DigiCert Global Root CA and search it in my PC. Then I copy it to my embedded linux rootfs and specify it in my client code by info.client_ssl_ca_filepath. How amazing! It work!  I am so happy! Thank you very much!

**Comment by lws-team** [comment]
Nice job :-)

You should also maybe think about a plan to update these certs in the devices, because although the root CA certs tend to have long lifetimes like 10 years, the intermediates have shorter lives.  Although server certs are now 1yr or less, they can be updated at the server easily enough... but if you have devices in the field where the intermediate cert got out of date, the device will become unable to communicate even though the CA is still in date and the server cert is in date (via a new intermediate you don't have).

So you need some kind of update policy that is aware of expiry date of certs on the device you are relying on.

**Comment by Sarah-Wang** [comment]
Thank you for your advice. I will take it into consideration later.
