### ISSUE TITLE
lws_http_client_read buffer requirements unclear

### ISSUE THREAD

**Issue by taviso** [warmcat/libwebsockets#1716]
Hello, is it necessary to guarantee `LWS_PRE` bytes exist before buffers passed to `lws_http_client_read`?

I understand the necessity when using `lws_write`, and this is clearly documented. But `lws_http_client_read()` documentation doesn't mention it, but the examples do that:

https://libwebsockets.org/lws-api-doc-master/html/group__client.html#ga4450c34200bf9dab3beb90ef23221870

```c
 57     case LWS_CALLBACK_RECEIVE_CLIENT_HTTP:
 58         {
 59             char buffer[1024 + LWS_PRE];
 60             char *px = buffer + LWS_PRE;
 61             int lenx = sizeof(buffer) - LWS_PRE;
 62 
 63             if (lws_http_client_read(wsi, &px, &lenx) < 0)
 64                 return -1;
 65         }
 66         return 0; /* don't passthru */
```
(from minimal-http-client.c)

**Comment by lws-team** [comment]
No it's not directly necessary for that.

The LWS_PRE is only used at `lws_write()` to place the protocol headers.

There are various other places it is accounted for so that when it's eventually consumed by sending it on `lws_write()`, the LWS_PRE is already in place without extra copies... lws_buflist adds LWS_PRE in place automatically, and the HTTP proxying stuff also arranges for it when storing rx it will proxy out again.

But I think that particular one is overkill because the rx is ephemeral - it's on the stack, you can't lws_write() it from there directly, it must be copied then to be stored... if you needed LWS_PRE you could arrange your own LWS_PRE on the copy.
