### ISSUE TITLE
DOC: lws_protocols[xxx].rx_buffer_size also affects sendto() limit

### ISSUE THREAD

**Issue by socketpair** [warmcat/libwebsockets#1722]
It was not obvious.....

**Comment by socketpair** [comment]
In my case I want to send really big messages (128 MB) but it's not allowed to receive so big messages. I will explain. I'm creating something like speedtest.net service for my own needs.

I want to send to the browser big chunks, and receive confirmation with 1 byte. In order to make it, I allocate 128MB of data using `calloc()` and don't fill it. This will not eat any memory actually, since `calloc()` with big blocks uses just `mmap()` which is virtually pre-zeroed. XOR in websocket protocol is a separate story.

In order to send data effectively, I have to set `rx_buffer_size` to some big value (i.e. 4 MB).
This mean that malicious user may send from browser 4MB of data that will be allocated on the server. It's not acceptable for me. Don't know how to fix.

**Comment by socketpair** [comment]
I'm not sure, but I guess websocket implementation is half-duplex ?

**Comment by socketpair** [comment]
Also, according to `strace`, libwebsockets allocates big buffers during send operation:

```
write(2, "[2019/10/20 03:05:31:9067] NOTICE: allocating per-websocket send buffer\n", 80) = 80
mmap(NULL, 134221824, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa24aec4000 // it's ok. It's my calloc() which does not eat memory actually.
// all these next mmaps() are not mine!
mmap(NULL, 134221824, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa242ec3000
mmap(NULL, 307200, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa255886000
mmap(NULL, 56913920, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa23f87c000
mmap(NULL, 110477312, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa23c567000
```

**Comment by socketpair** [comment]
It seems, libwebsockets copies not-yet-sent data into internal buffer for background sending. Is there any way to tell it that I will not modify that buffer, so no copying should be done ?

**Comment by lws-team** [comment]
> In my case I want to send really big messages (128 MB) but it's not allowed to receive so big messages. 

Hmmm you are confused between ws messages, ws fragments and packets.

You may send **ws messages** of unlimited size whose length is not known when you started.  However one framed entity in ws is a **ws fragment**.  Ws messages may be composed on an unlimited number of ws fragments, which may be of any size.  ws fragments in turn ultimately go out fragmented into tcp packets.  As tcp packets are received from an incoming ws message, they are passed to user code... the buffer setting in lws_protocols just controls how much can be coalesced into one read.  It does not need to have any relationship at all to the overall message size.

For the second time, if you just naively dump 400KB on send() on Linux, the kernel will not accept such a thing on an internet tcp socket.  It will typically only accept a few KB at a time.  Yes lws runs around cleaning up the mess for you but this naive method is hugely inefficient... not only for the obvious reason of the buffer allocation but also the first time, the kernel side of send() has to copy all 400KB into kernel memory in order to request the send() kernel-side, which is fated to use only a few KB of it.  Why is it like that?  Because POSIX defines POLLOUT to indicate we can send "something" on the socket, but it gives no indication of how much the kernel will accept... it would be a race condition anyway since kernel memory situation is highly dynamic.

So what is the correct way?  Do not dump send buffers on lws that the kernel definitely will not clear in one hit.  Break it down into individual sends so that typically, the kernel will accept them... say, 4KB or 8KB or whatever works on your platform.  What the kernel will accept is related to connection tcp window state which is related to size of tcp packets, it has no idea about your plans for a large ws message.  In this way you can copy your content once piece by piece instead of forcing lws to allocate, buffer and do the same thing in the background.
