### ISSUE TITLE
DOC: it is not clearly documented, that every(?) lws_write will trigger LWS_CALLBACK_*_WRITEABLE

### ISSUE THREAD

**Issue by socketpair** [warmcat/libwebsockets#1723]
I thought that this callback may happen only as a result of previous call of `lws_callback_on_writable()`

**Comment by lws-team** [comment]
No, what is documented is that there may be extra calls to WRITEABLE.

The reason is if you dump more data into lws_write() than the kernel will accept on the send(), lws is forced to clean that up for you by buffering it and concealing the callback_on_writable() and WRITEABLE actions related to it.  You should instead arrange your code to send smaller things that the kernel will always or almost always accept after it signalled POLLOUT.

In the meanwhile, it will lose any callback_on_writable() your code may request since it is also requesting them itself internally to clear your backlog.  For that reason if it had to handle partial sends like this, it always performs a WRITABLE at the end.

Your WRITABLE handler should know its state and just return if nothing to do.
