### ISSUE TITLE
lws_service() blocking in 3.2

### ISSUE THREAD

**Issue by kristjanvalur** [warmcat/libwebsockets#1735]
After migrating to 3.2, UEWebsocket (in unreal engine) now freezes when there is no network activity.  Previously, we would poll the context every frame (on tick) calling lws_service(ctx, 0).  This allows libwebsocket to be used cooperatively in a single-threaded application.
The documentation for 3.2 now states that timeout_ms is ignored, while looking at the source code, it would appear that a negative value would give the same result as previously.  This is how we will work around the issue for now.

Is there a canonical way of doing a non-blocking service in libwebsockets 3.2?

**Comment by lws-team** [comment]
Well... you're not the only project that relies on this kind of hack to coexist with something that doesn't itself has a posix footprint.  But the other event loop libraries don't offer a way to do this, you start their loop and the only way anything happens is via a callback from the event loop... this method only exists with lws internal poll() loop.  It's not ideal because this way creates a granularity in time inbetween service of 16ms or whatever the frame rate is.

Originally I removed the whole idea of controlling the poll wait in the service call in 3.2 as part of the sul work that uses a sorted list of upcoming scheduled events to figure out how long it can sleep.  But after finding this hack was more popular than I imagined, as a compromise you can turn off the poll wait basically by giving it -1 in the service call.

I don't know how your vsync wait is arranged but at least with drm, you can use an ioctl / libdrm api to find out a high resolution estimate of when the vblank will start.  If it's the case you did all the work for the next frame and are just waiting to flip the page, you could set a sul timer to a bit less than the estimate and spend the idle time in lws.  On linux, with poll(), posix specifies that only has ms resolution though.

Another less invasive way is spawn a thread for comms... if there's a case where rx triggers tx, since this will go around the event loop and that is locked to the frame rate atm, decoupling it from the frame rate would improve latency.  You'll be into locking and / or careful layout into rdonly and wronly sides of things to synchronize stuff.

Or just go with the -1, it's definitely not how 99% of users should use lws - they want lws or the event lib to provide the wait sleep -  but under some conditions it simplifies integration and I'm probably stuck supporting it.

**Comment by kristjanvalur** [comment]
Thanks.  To be clear, I'm not the author of UEWebSocket, but I'm maintaining a fork for a production game project and don't want to refactor it too intensively.  I'll go with the "unofficial" workaround then.

**Comment by Egbert8527** [comment]
too stupid design

**Comment by JoTid** [comment]
The search for the hint "_you can turn off the poll wait basically by giving it -1 in the service call_" so that the `lws_service()` is not blocked and the requests are answered as quickly as possible took me several hours. 
At least it works now as I expected, glad to have found this hint here, thanks a lot.

**Comment by lws-team** [comment]
It's worth digging into it a bit deeper

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.event-loops-intro.md

and understanding why doing that is never the right solution.  It might look like it helps you with some other hack, but there are good reasons that is contraindicated by not documenting it.

**Comment by JoTid** [comment]
I agree with you and also see it as a workaround, not an elegant or final solution. 

Unfortunately, I can't find anything in the libwebsockets documentation that fits this topic.

What approach would you recommend to write a "high responsive event triggered websockets" application?
Do you have a tip for me?

**Comment by lws-team** [comment]
Is it possible you're a bit confused about the event loop wait?  If you tell poll() to use a huge timeout, or no timeout, it does not affect latency to notice events on the poll wait fd set if you aren't delaying it in the loop.  It's exactly the same.  For that reason most users don't care about this.

Users that care about it have arranged their app to do something in the spinning outer loop, either mix a completely different wait on another set of fds in there for some other app they grafted on (which is hopeless for latency) or want to do something at intervals outside lws.  For the latter case, you can use lws_sul to schedule events typ at ms actual resolution in the future, search the examples for it if that's your problem.

**Comment by kristjanvalur** [comment]
And the problem I was having was using lws as an add on in an application with its own event loop.  That application doesn"t even want to _wait_ at any point for IO, it uses its wait times for other things.  it is cpu bound.  And even if it did want to stop and wait for IO, then joining the two IO waits, some internal wait in the host application and the lws own, isn't simple or easy.   
Supporting a "polling" mode is a perfectly valid way of doing things if it isn't appropriate to have lws take over the entire application by blocking.  Particularly if latency isn't at a premium (latency lower than the application's "frame rate" makes no sense.   Like: "every frame, check if there has been some lws activity and service that".

**Comment by lws-team** [comment]
> joining the two IO waits

Yes joining two IO waits is always crap.  But you do not have to have two IO waits.

The "event loops intro" README above goes into how to have lws use your own already-existing event loop and not produce another one.

**Comment by kristjanvalur** [comment]
yes.  Still, I see no reason to keep a "polling architecture" as a hidden secret.  It may be most appropriate solution in some cases.
I'm the author of the Poll adapter in hiredis (https://github.com/redis/hiredis/blob/master/adapters/poll.h) which exists precisely for these reasons.   Yes, using the event loop wait is best for latency, but sometimes there is no event loop, or low latency is not what you are shooting for.

**Comment by lws-team** [comment]
> Still, I see no reason to keep a "polling architecture" as a hidden secret. 

Right, you don't get the issue traffic (except when someone necro-bumps your issue) and people using it as a hack to put things in the main loop.  And you don't get questions about why there is no outer loop when they use an event library.  Nor this kind of argument that isn't going to do anything for either of us (except when you're the guy arguing).

**Comment by JoTid** [comment]
> Is it possible you're a bit confused about the event loop wait? 

That is correct and I am afraid that I did not fully understand the use of lws_sul. Thus, I probably applied the lws_sul_schedule() functions incorrectly. 
Currently, these are not called in my client and presumably this is also the cause of the behaviour described above.

I'll have to take a closer look at the examples. 
In any case, thank you for the tips.
