### ISSUE TITLE
LLL_USER log message is invisible on terminals with black backgroud

### ISSUE THREAD

**Issue by zhiwenzheng** [warmcat/libwebsockets#1740]
How about stop using black or white in log messages? they may be the same colour with the terminal background.

**Comment by lws-team** [comment]
I don't see a good way to solve that except disable the colouring and use terminal default foreground, eg `2>&1 | cat`... lws checks if it istty() before doing the colours and pipe through cat defeats it.

On linux, default dark terminal backrounds are dark grey, the colours are selected to work with that and light background (== quite a light grey).  Changing them will make them invisible for Linux case.

I can't find a standardized way to get terminal background colour over ansi escapes either.

**Comment by zhiwenzheng** [comment]
How about let LLL_USER use the same colour with LLL_INFO (or some other loglevel) ?
I think it is better not to assume a default terminal config, since it is a personal flavor, not a platform character, even different linux distributions may have different defaults.
If only the color is neither black or white, there is high chance that it is visible, since black and white are common choice for backgroud color.

**Comment by lws-team** [comment]
I agree it's something the user can set and assuming about it is unfortunate, but practically eg, cross distro consoles like gnome terminal or tilix use off-white or dark grey... that's why the issues thing here is not full of people complaining.  Even the Linux vt (Ctrl Alt Fn x) is dark grey not black IIRC, from memory kconsole too.  If I follow your suggestion and black -> dark grey, I just break a very common case.  I can try move USER just a bit off black but it's barely going to be legible against black.

**Comment by zhiwenzheng** [comment]
Ok. I use the solarized dark theme on urxvt, black is invisible, maybe I can try to let black visible. Thanks.
