### ISSUE TITLE
Connect fail,the target maybe invalid

### ISSUE THREAD

**Issue by futengfei815** [warmcat/libwebsockets#1767]
Hello,In UE4 gameengine project , after run,a sentence in screen,"connect fail,the target maybe invalid".
![1](https://user-images.githubusercontent.com/30932654/68990641-91a45400-0890-11ea-835f-6f66b1894cca.jpg)

after UWebSocketBase::Connect in WebSocketBase.cpp
In "Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp",
the UWebSocketContext::callback_echo function in case 

![2](https://user-images.githubusercontent.com/30932654/68990643-923cea80-0890-11ea-8642-f04642542149.jpg)
LWS_CALLBACK_CLIENT_CONNECTION_ERROR,the variable " strError" value is "set socket opts failed."
can you tell me why the error occur,how can I solve.
Thank you very much.

**Comment by lws-team** [comment]
What version of lws is this?  That string doesn't exist on master.

**Comment by futengfei815** [comment]
> What version of lws is this? That string doesn't exist on master.

MyProject is download from "https://github.com/feixuwu/UEWebsocket".Only added some log in code. The "connect fail,the target maybe invalid" is not my log.

The connectInfo is default,not changed by me.
the connectInfo.address value is echo.websocket.org
the connectInfo.ssl_connection value is 2
the connectInfo.path value is empty
the connectInfo.hostvalue is echo.websocket.org
the connectInfo.originvalue is echo.websocket.org
the connectInfo.ietf_version_or_minus_onevalue is -1
the connectInfo.port value is 443.
![3](https://user-images.githubusercontent.com/30932654/68991167-c3b8b480-0896-11ea-8008-5786a0ad5e44.jpg)

Connect success in other computer.but fail in my computer.

**Comment by futengfei815** [comment]
> What version of lws is this? That string doesn't exist on master.
Where to find the version of lws?

**Comment by lws-team** [comment]
Looking at the project you linked to, it seems to provide "libwebsockets.a" which is not exactly "open source"... it says it is MIT-licensed, master lws is MIT-licensed, it's if they either reference lws via git submodule or they can also include lws tree since it is license-compatible.  Either way it's easier then to understand what lws it is and update it by end user.

The string about "set socket opts failed" appears last in v3.2 lws tree, I guess this problem is related to ipv6 on your platform.  lws master has some important improvements about ipv6 / ipv4 client handling; before then it'll try once and give up, on master it will iterate through all ipv4 and v6 SND results until something works or none left to try.

**Comment by lws-team** [comment]
... at any rate the answer is "try lws master".... you'll need to talk to the maintainer of the other project to do that AFAICS.
