### ISSUE TITLE
per_vhost_data is NULL on LWS_CALLBACK_ESTABLISHED callback on windows

### ISSUE THREAD

**Issue by thefallentree** [warmcat/libwebsockets#1804]
I'm having an very weird issue, I'm using the minimal example as below, 
```
static int callback_minimal_server_echo(struct lws *wsi, enum lws_callback_reasons reason,
                             void *user, void *in, size_t len)
{
  struct per_session_data__minimal *pss =
      (struct per_session_data__minimal *)user;
  struct per_vhost_data__minimal *vhd =
      (struct per_vhost_data__minimal *)
          lws_protocol_vh_priv_get(lws_get_vhost(wsi),
                                   lws_get_protocol(wsi));

switch (reason) {
    case LWS_CALLBACK_PROTOCOL_INIT: {
      lwsl_warn("LWS_CALLBACK_PROTOCOL_INIT\n");

      vhd = reinterpret_cast<per_vhost_data__minimal *>(
          lws_protocol_vh_priv_zalloc(
              lws_get_vhost(wsi),
              lws_get_protocol(wsi),
              sizeof(struct per_vhost_data__minimal)));
      vhd->context = lws_get_context(wsi);
      vhd->protocol = lws_get_protocol(wsi);
      vhd->vhost = lws_get_vhost(wsi);

      vhd->ring = lws_ring_create(sizeof(struct msg), 8,
                                  __minimal_destroy_message);
      if (!vhd->ring)
        return 1;
    }
      break;
    case LWS_CALLBACK_PROTOCOL_DESTROY:
      lwsl_warn("LWS_CALLBACK_PROTOCOL_DESTROY\n");
      lws_ring_destroy(vhd->ring);
      break;
    case LWS_CALLBACK_ESTABLISHED: {
      /* generate a block of output before travis times us out */
      lwsl_warn("LWS_CALLBACK_ESTABLISHED\n");

      lws_ll_fwd_insert(pss, pss_list, vhd->pss_list);    <---- CRASH
      pss->tail = lws_ring_get_oldest_tail(vhd->ring);
      pss->wsi = wsi;

      auto vhost = lws_get_vhost(wsi);
      auto ip = (struct interactive_t*) (lws_vhost_user(vhost));
      ip->iflags |= HANDSHAKE_COMPLETE;
      on_user_logon(ip->ob);
      break;
    }
}

...

```

The same code works under GCC/linux , but fails under mingw64 / windows

And I traced that VHD in this callback is simply NULL  ,  it looks like lws_protocol_vh_priv_get just returns NULL, any idea why? 

The exact same code works under linux 

Thanks

**Comment by thefallentree** [comment]
![image](https://user-images.githubusercontent.com/1256464/71320876-a31be580-2466-11ea-9018-9f345ba73eca.png)

**Comment by lws-team** [comment]
Did `LWS_CALLBACK_PROTOCOL_INIT` that allocates the vhd area actually happen already?

**Comment by thefallentree** [comment]
> Did `LWS_CALLBACK_PROTOCOL_INIT` that allocates the vhd area actually happen already?

Yes, I traced that LWS_CALLBACK_PROTOCOL_INIT is triggered twice and it all succeed!

```

#define LWS_PLUGIN_PROTOCOL_MINIMAL_SERVER_ECHO \
	{ \
		"lws-minimal-server-echo", \
		callback_minimal_server_echo, \
		sizeof(struct per_session_data__minimal), \
		4096, \
		0, NULL, 0 \
	}

static struct lws_protocols protocols[] = {
    { "http", lws_callback_http_dummy, 0, 0 },
    LWS_PLUGIN_PROTOCOL_MINIMAL_SERVER_ECHO,
    { NULL, NULL, 0, 0 } /* terminator */
};
```

Another complications is that I'm creating an context but adopting from an libevent FD . as I said, the same code works fine under linux. So right now I'm actually creating context for each connection, which is not ideal, but I havn't figured out what's the best way to do it yet.

```
  memset(&info, 0, sizeof info); /* otherwise uninitialized garbage */

  void* foreign_loops[1] = {base};

  info.foreign_loops = foreign_loops;
  info.mounts = &mount;
  info.port = CONTEXT_PORT_NO_LISTEN_SERVER;
  info.protocols = protocols;
  info.extensions = extensions;
  info.pt_serv_buf_size = 32 * 1024;
  info.options = LWS_SERVER_OPTION_LIBEVENT |
      LWS_SERVER_OPTION_VALIDATE_UTF8 |
      LWS_SERVER_OPTION_HTTP_HEADERS_SECURITY_BEST_PRACTICES_ENFORCE;
  info.user = (void *) user;

  context = lws_create_context(&info);

  if (!context) {
    lwsl_err("lws init failed\n");
    return nullptr;
  }

  auto lws = lws_adopt_socket(context, fd);
```

**Comment by lws-team** [comment]
> Yes, I traced that LWS_CALLBACK_PROTOCOL_INIT is triggered twice

Normally this should only happen once... I assume "twice" is because you have two lws_contexts atm

>  So right now I'm actually creating context for each connection

That's not the right way as you seem to be aware already... if you made two different threads, that won't fly... lws is not threadsafe except for one api basically.  libevent won't be threadsafe either.  If stuff gets mapped on to Thread Local Storage in windows maybe that's something to do with it.

There should be one context on the foreign loop and it should handle libev fd needing adopting from inside the event loop.  One you have set up the one lws context and joined it to the foreign event loop, you can call lws_adopt_...() from any callback / event handler that is operating in libevent thread context... any of the libevent-managed code that's on the same event loop as lws can just interoperate with lws apis directly if it knows the lws_context.

**Comment by thefallentree** [comment]
The first init is triggered by dummy http protocol, while the second one
should be for this protocol. The application actually only have one thread
.

Can you give an rough outline on how single context works with Libevent? Is
it just lws_create_context() with options? Do I need to call service() ?

I also couldn’t figure out an way to store an global context without having
an global variable somewhere, because by the time I need to adopt, I
already lost the handle to lws context.

**Comment by lws-team** [comment]
The foreign loop http server example is similar to the model I'm suggesting:

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib-foreign/minimal-http-server-eventlib-foreign.c

The libevent loop is running already... one time, create one lws_context from inside the libevent loop... it's OK to store it in a global for now if you don't have a better place

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib-foreign/minimal-http-server-eventlib-foreign.c#n289

You don't have to enter lws_service() because in this configuration, the pre-existing libevent loop is doing the service.  Later you can also destroy the lws_context from inside a libevent callback leaving the libevent loop continuing untouched:

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib-foreign/minimal-http-server-eventlib-foreign.c#n301

Then from some other libevent callback, you can do the adoption using the saved lws_context pointer.  Basically in this configuration, all your libevent-managed callbacks are in the same "family" as lws callbacks since all on the event loop, you can use any lws api there.

**Comment by thefallentree** [comment]
So, I managed to refactor my code to create context and  then do lws_adpot_socket on an libevent callback, 

However, how do I initialize some user data after the adoption? I tried this but it seems the user data is just nullptr after adoption.

![image](https://user-images.githubusercontent.com/1256464/71328103-3d5f4600-24c6-11ea-83f8-74a8a42c4036.png)

**Comment by lws-team** [comment]
There are a lot more options possible at adoption time

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-adopt.h#n116-148

The one you're calling is a helper

https://libwebsockets.org/git/libwebsockets/tree/lib/core-net/adopt.c#n375-383

https://libwebsockets.org/git/libwebsockets/tree/lib/core-net/adopt.c#n313-329

If you call the form in the first and last link above directly, you can set the wsi `.opaque_user_data` member at creation time.  There are very cheap accessors to get and set that if necessary

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-misc.h#n419-423

These work on adopted wsi even when they're not bound to a specific protocol.

**Comment by thefallentree** [comment]
Thanks! I can confirm that once I switched to an global context and create per-session data in the callbacks things start to work correctly.

I can close this issue now and I will send patches for compiling under mingw. 

I do have an few follow questions:

1. In my situation I need to buffer websocket output, there is no built in support in lws,  I had to maintain an linked list manually , as seen in minimal example, or I found there is this lws_buflist and some functions to manipulate it , but no function to create one. I ends up using evbuffer from libevent, because the convince. 

Is LWS_WRITE_BUFLIST working yet? If I could just stick my write data to the buflist I don’t need this evbuffer anymore. 

2. How do I know how much I can write? It seems lws mentioned it has internal buffering to handle truncated writes, but in my case looks like it just create two layer of buffering .

3. Is there an way to close WSI outside of callback?  I think I had to have an flag somewhere in the per session data , and trigger an write immediately after setting it, and have the write callback to return -1 in that case. Is there an better (built in) way? 


Thanks for your fast replies and happy holiday!

**Comment by lws-team** [comment]
Great.  Once you get your head around it, this situation is very clean with lws fully and natively participating on your original libevent event loop with no threads, locking, tricks or magic.  Other callbacks from the same libevent loop directly are all 'in the family'.

It doesn't seem LWS_WRITE_BUFLIST is implemented, I am not sure what's up there.  It's intended for your case and reuse the built-in output side buflist. I'll take a look tomorrow.

With POSIX, you are only told that you may write (POLLOUT is set), you are not informed by the OS at any time how much you may write... this value is dynamic, it's related to connection tcp window and kernel memory pressure.  For some protocols like http2 there is also a protocol transmit credit value that limits what you could write... if it falls below zero, it should conceal WRITEABLE from you completely until the credit is renewed by the peer.  You can find the value if any for a wsi here

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-writeable.h#n225

The reality on Linux anyway is the OS send() can truncate how it likes, but typically it will accept writes sized to one or two mtu, I recommend sending something like 1400 which translates to one ethernet frame.  Some network interfaces like lo will typically accept much larger single writes, but that doesn't reflect how real connections act over the Internet.  The lws internal buflist is always there to conceal anything unexpected like only accepted one byte, which is allowed by POSIX.

If you have the wsi, you can close it either synchronously, ie, before return from the call, or asynchronously like this

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-timeout-timer.h#n77-101

You can't kill a wsi synchronously from a callback that is related to the same wsi... otherwise when you return, lws would touch the wsi you have destroyed.  So LWS_TO_KILL_SYNC is restricted to times you know for sure that isn't the case, eg cb from non-lws libevent object, or callback for related wsi that cannot be the same as the one you want to kill.  Async variant doesn't have any restriction.

**Comment by thefallentree** [comment]
> The reality on Linux anyway is the OS send() can truncate how it likes, but typically it will accept writes sized to one or two mtu, I recommend sending something like 1400 which translates to one ethernet frame. Some network interfaces like lo will typically accept much larger single writes, but that doesn't reflect how real connections act over the Internet. The lws internal buflist is always there to conceal anything unexpected like only accepted one byte, which is allowed by POSIX.

In that case, why not have lws completely conceal the buffering nature of the underlaying FD? just like libevent's bufferevent / evbuffer , having an interface where *all* user write goes into internal buffers (and never fails except oom.) and have it write out as soon as underlaying socket allows would be nice. 

Truth be told, I kinda biased towards libevent's design because I have been using it for so long and its data structure are super useful for anything that deal with an file or network socket.   lws_buflist is kinda of the same idea with evbuffer, except I couldn't find an new() and free() functions to create one :-)

**Comment by lws-team** [comment]
Lws works great on systems where that kind of buffering approach won't even get off the ground, like rtos-based esp32 or cortex-M with 350KB shared between 802.11 / BT stack and lws / user application.  Data needs to get into lwip packet buffer as soon as generated on the stack.  Heap usage is agonized over like a miser counting grains of rice.  Lws is very flexible and goes places event lib approach can't follow.

You just start with a ptr to NULL buflist ptr, append to it and it's set to an allocated one

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-misc.h#n45

"use" data from it and when it's emply, its automatically destroyed and ptr set NULL.  There is no new and free function needed then.

**Comment by thefallentree** [comment]
Thanks for all the great information! 

So if I have an main libevent loop, and an network libevent loop, it looks like it is not possible to call lws_callback_on_writeable() in an thread safe way?  

from the document here


4) For multithreaded apps, this corresponds to a need to be able to provoke the lws_callback_on_writable() action and to wake the service thread from its event loop wait (sleeping in poll() or epoll() or whatever). The rules above mean directly sending data on the connection from another thread is out of the question.

Therefore the two apis mentioned above that may be used from another thread are
> 
> For LWS using the default poll() event loop, lws_callback_on_writable()
> For LWS using libuv/libev/libevent event loop, lws_cancel_service()
> If you are using the default poll() event loop, one "foreign thread" at a time may call lws_callback_on_writable() directly for a wsi. You need to use your own locking around that to serialize multiple thread access to it.
> 
> If you implement LWS_CALLBACK_GET_THREAD_ID in protocols[0], then LWS will detect when it has been called from a foreign thread and automatically use lws_cancel_service() to additionally wake the service loop from its wait.
> 
> For libuv/libev/libevent event loop, they cannot handle being called from other threads. So there is a slightly different scheme, you may call lws_cancel_service() to force the event loop to end immediately. This then broadcasts a callback (in the service thread context) LWS_CALLBACK_EVENT_WAIT_CANCELLED, to all protocols on all vhosts, where you can perform your own locking and walk a list of wsi that need lws_callback_on_writable() calling on them.
> 
> lws_cancel_service() is very cheap to call.

for external loop case, beside calling cancel_service() and force check every wsi (which is not really acceptable, if only want to write to 1 connection), I think it maybe possible to schedule an event on the network evet loop  (using libevent) and use that callback to execute lws_callback_on_writeable() on callback

**Comment by lws-team** [comment]
Why have two event loops... it kind of defeats the point.

Lws_cancel_service() is the recommended way for letting lws know something happened from another thread.  There's no requirement to 'check every wsi', you can instead keep a lock-protected linked-list of events created from another thread and the wsi they relate to.

In your case anything on the same libevent loop as lws can interoperate with lws safely.  So libevent event on that can be safe if libevent will let you do it from another thread.

**Comment by thefallentree** [comment]
You are right. In my case libwebsocket is not the only network framework in use, I have some other hand written protocol handling , including integration with https://github.com/seanmiddleditch/libtelnet . libwebsocket could have potential to become the sole framework, however, I still kinda of need an generic event loop for timer and deferred callbacks, that's why I couldn't ditch libevent yet.

**Comment by lws-team** [comment]
There's no problem to use lws + libevent.  The strange thing is to have two separate loops (If I understood it)... they can just be one and everything can use each others' apis from a single event loop thread contect.  At least lws isn't stopping you doing that.

Notice lws has an ssh2 client plugin https://libwebsockets.org/git/libwebsockets/tree/plugins/ssh-base

**Comment by thefallentree** [comment]
My project( github.com/fluffos/fluffos ) , is single threaded game engine with an interpreter VM , an user can submit commands to run some program in the VM and interact with other user. This single threaded model works okay-ish for a long time. VM calls can take a while to run and the output are only flushed at the end of the command with internal buffering. 

I've always want to support streaming output, and I ask the same question on libevent https://github.com/libevent/libevent/issues/936 ,  The two framework all built with idea that event loop will be running all the time and all handlers are very fast, however that is certainly not my case. where an command could take >1s to execute and during that time sockets may already became writable, but neither framework offers ways to yield to eventloop specific to outputs stuff.

**Comment by lws-team** [comment]
I don't really know what you're doing there but if it's serving stuff on a connection that may need its own thread but sync to event loop for IO, maybe look at threadpool

https://libwebsockets.org/git/libwebsockets/tree/lib/misc/threadpool
https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threadpool

Eg, the lws gitweb those links point to, gitohashi, is itself implemented using lws threadpool.

**Comment by lws-team** [comment]
At any rate the original problem was solved a while ago so I'll close this since nothing for me to do.  Patches for any mingw adaptation welcome when you have the time.
