### ISSUE TITLE
lws_write too slow.

### ISSUE THREAD

**Issue by caobug** [warmcat/libwebsockets#1809]
Hello, I am transferring other IO data to websocket, I called lws_write (), but writing data is too slow.

1. recv data from other IO:
```
static void recv_cb(EV_P_ ev_io *w, int revents) {
    ....
    printf("recv_cb len: %zd\n", len);
    data_write(session, data, len);
    ....
}
```
2. add to queue.
```
int data_write(struct session *pss, char *buf, uint16_t len) {
    struct buffer *buffer = buffer_new(buf, len, LWS_PRE);
    if (cork_ring_buffer_add(pss->send_ring, buffer) == -1) {
        printf("The send ring is full\n");
        buffer_free(buffer);
        return -1;
    }
    if (pss->send_ring->size == 1) {
        lws_callback_on_writable(pss->wsi);
    }
}
```
3. write callback
```
static int service_callback(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len) {
    struct session *pss = (struct session *)user;
    switch (reason) {
        ...
        case LWS_CALLBACK_SERVER_WRITEABLE:
            if (pss->writing) {
                buffer_free(cork_ring_buffer_pop(pss->send_ring));
                pss->writing = 0;
            }
            struct buffer *buffer = cork_ring_buffer_peek(pss->send_ring);
            if (buffer != NULL) {
                int flags = lws_write_ws_flags(LWS_WRITE_BINARY, 1, 1);
                int sent = lws_write(pss->wsi, ((unsigned char *)buffer->data) + LWS_PRE, buffer->len, flags);
                LOGI("lws_write sent: %d\n", sent);
                if (sent < buffer->len) {
                    return -1;
                }
                pss->writing = 1;
                
                lws_callback_on_writable(pss->wsi);
            }
            break;
        ...
    }
    return 0;
}
```
4. sending all data takes a lot of time:
```
[2019/12/30 16:46:15:7495] N: recv_cb len: 1524
[2019/12/30 16:46:15:7502] N: recv_cb len: 8192
[2019/12/30 16:46:15:7502] N: recv_cb len: 8191
[2019/12/30 16:46:15:7525] N: recv_cb len: 8192
[2019/12/30 16:46:15:7525] N: recv_cb len: 8191
[2019/12/30 16:46:15:7547] N: recv_cb len: 8192
[2019/12/30 16:46:15:7547] N: recv_cb len: 8191
[2019/12/30 16:46:15:7562] N: recv_cb len: 8192
[2019/12/30 16:46:15:7563] N: recv_cb len: 8191
[2019/12/30 16:46:15:7572] N: recv_cb len: 8192
[2019/12/30 16:46:15:7573] N: recv_cb len: 8191
[2019/12/30 16:46:15:7578] N: recv_cb len: 8192
[2019/12/30 16:46:15:7578] N: recv_cb len: 8191
[2019/12/30 16:46:15:7995] N: recv_cb len: 8192
[2019/12/30 16:46:15:8002] N: recv_cb len: 8192
[2019/12/30 16:46:15:8002] N: recv_cb len: 7386
[2019/12/30 16:46:15:9410] N: lws_write sent: 1524
[2019/12/30 16:46:15:9411] N: lws_write sent: 8192
[2019/12/30 16:46:15:1367] N: lws_write sent: 8191
[2019/12/30 16:46:15:3293] N: lws_write sent: 8192
[2019/12/30 16:46:15:5214] N: lws_write sent: 8191
[2019/12/30 16:46:16:7145] N: lws_write sent: 8192
[2019/12/30 16:46:16:9066] N: lws_write sent: 8191
[2019/12/30 16:46:16:0998] N: lws_write sent: 8192
[2019/12/30 16:46:16:2921] N: lws_write sent: 8191
[2019/12/30 16:46:16:4851] N: lws_write sent: 8192
[2019/12/30 16:46:17:6773] N: lws_write sent: 8191
[2019/12/30 16:46:17:8695] N: lws_write sent: 8192
[2019/12/30 16:46:17:0620] N: lws_write sent: 8191
[2019/12/30 16:46:17:2545] N: lws_write sent: 8192
[2019/12/30 16:46:17:4465] N: lws_write sent: 8192
[2019/12/30 16:46:18:6388] N: lws_write sent: 7386
```
If I don't use a queue, calling lws_write in data_write will be very fast. But sometimes the data is incomplete.

What advice do you have? 

Thanks.

**Comment by lws-team** [comment]
> I called lws_write (), but writing data is too slow.

Hm... "too slow"...

> sending all data takes a lot of time

Doubt that sending the data itself takes any real time.

> If I don't use a queue, calling lws_write in data_write will be very fast.
> But sometimes the data is incomplete.

You can only use lws_write() inside WRITEABLE callback.  That in turn only gets called when it knows the kernel will accept another send() on the socket.

On even a weak machine lws has no problem sending several MB/sec per connection over the internet on many connections simultaneously.

> recv data from other IO:

What are your arrangements for integrating lws on the event loop / calling lws_service()?

**Comment by caobug** [comment]
Thanks for your reply, I am listening to other IO data and need to transfer data through websocket. Integrate libev without calling lws_service ().

if without the lws_write () function, I would be able to:
```
static void recv_cb(EV_P_ ev_io *w, int revents) {
    ssize_t sent = send(client_fd, in, len, 0);
    if (sent == -1) {
        if (errno == EAGAIN || errno == EWOULDBLOCK) {
            client->idx = 0;
            client->len = len;
            ev_io_stop(loop, &recv_ctx->io);  // pause recv
            ev_io_start(loop, &send_ctx->io);  // dequeue
        } else {
            free_client()
        }
        return;
    } else if (sent < len) {
       client->idx += sent;
       client->len = len - sent;
       ev_io_stop(loop, &recv_ctx->io);  // pause recv
       ev_io_start(loop, &send_ctx->io);  // dequeue
    }
    // continue recv more data and send to client_fd.
}
```

**Comment by lws-team** [comment]
> Integrate libev without calling lws_service ().

Lws itself is called from the foreign event loop, like this example?

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib-foreign

It seems to take 200ms between WRITEABLE callbacks from your logging... lws_write adds some framing behind your data and otherwise does the same flow as you sketch out on the same event loop if it's set to use it properly and nothing delays the loop.  Anything blocking the loop?  Back-to-back WRITEABLE should be about 200us between them on even an RPI3, if it's actually writeable.  It seems something is having to do some work somewhere in your setup to sleep or block or spin for 200ms, lws isn't doing it.

**Comment by lws-team** [comment]
Just a thought, 200ms is reminiscent of Nagle

https://en.wikipedia.org/wiki/Nagle%27s_algorithm

At least on *nix, lws disables Nagle on sockets it opens... if you opened the fd and didn't disable Nagle, you may get this kind of issue.  Use TCP_NODELAY to turn it off.

https://libwebsockets.org/git/libwebsockets/tree/lib/plat/unix/unix-sockets.c#n160

**Comment by caobug** [comment]
Thank you.
I set TCP_NODELAY in LWS_CALLBACK_ESTABLISHED but still have a delay of close to 200ms.
```
int fd = lws_get_socket_fd(wsi), opt = 1;
setsockopt(fd, IPPROTO_TCP, TCP_NODELAY, &opt, sizeof(opt));
```
If the websocket server is deployed to local computer, there will be no delay, only the remote server will have this problem.

**Comment by lws-team** [comment]
It's maybe worth checking setsockopt return value and confirm using getsockopt that you really set it.  Because Nagel is a really good story to explain your problem, and at least on some platforms, it's disabled on loopback / lo / 127/8.

**Comment by lws-team** [comment]
... also what about the case the server is just on the local subnet rather than the same machine or Internet... still 200ms or less then?

**Comment by caobug** [comment]
Hello, I tried install the service in local subnet and everything worked fine. I also tried to switch to another remote server and there was still a ~200ms delay.

and I tried to send data directly using socks and it was very fast.

**Comment by lws-team** [comment]
Lws doesn't know or care if it's on the local subnet or not.  If something acts differently then the problem is coming from that.

The "200ms delay" seems to be for lws to hear about POLLOUT on the socket.  Lws doesn't have any msleep(200) or timers that care about 200ms.

> and I tried to send data directly using socks and it was very fast.

Can you reproduce this on the examples without any of your code?  I'll be happy to take a close look at it if I can reproduce it using lws pieces.  Otherwise, if "using socks" whatever that means is "very fast" just "use socks".

**Comment by caobug** [comment]
Thank you, I will provide an example soon.

**Comment by caobug** [comment]
fix the issues.
1. enable Nagle
2. change `lws_protocols.rx_buffer_size` to `128 * 1024`(fill  50Mbps bandwidth).
3. lws_write cut to multiple 2048 bytes packet.

Just don't understand rx_buffer_size is global or per conn?

**Comment by lws-team** [comment]
Nagle being needed if you don't open things with lws (which already takes care of it for you) seems to make sense and fits the 200ms behaviour.

I don't really understand what rx_buffer_size is doing for you... that has some "history", originally it was also used to control the max tx packet size as well, but since you're restricting that to <2 mtu anyway, that part of it shouldn't make any difference.  You can set the tx limit separately now, but it doesn't seem relevant since you send 2KB chunks.

> Just don't understand rx_buffer_size is global or per conn?

It's per connection, because you're allowed to set rx flow control at any time and leave RX data pending in this buffer without consuming it.  If you don't set it and leave it at 0, lws uses `pt_serv_buf_size`, which defaults to 4KB.  But if you're sending stuff out in 2KB chunks, it shouldn't make trouble to receive it in 4KB chunks if it's there rather than 128KB chunks.

Anyway it seems you solved your original problem from your side, on your side.

**Comment by caobug** [comment]
@lws-team  
I repeatedly modified the `rx_buffer_size` parameter on the server side:

rx_buffer_size=4k, bandwidth: 64KB/s
rx_buffer_size=64k, bandwidth: 1M/s
rx_buffer_size=128k, bandwidth: 4M/s

data just from server send to client, why need these big buf?
If I server have 100Mbps, I need setting to 256k?

```
struct lws_protocols protocols[] = {
    {
        "ws",
        service_callback,
        sizeof(struct session),
        128 * 1024,
        0, NULL, 2048
    },
    { NULL, NULL, 0, 0 }
};
```

Thanks.

**Comment by lws-team** [comment]
As I say...

> I don't really understand what rx_buffer_size is doing for you
