### ISSUE TITLE
TCP connection timeout not honoured

### ISSUE THREAD

**Issue by ohierro-verimatrix** [warmcat/libwebsockets#1822]
I'm writing a websockets client on iOS, using a recent lws snapshot from the master branch. For a test case I want to test my client error'ing out when connecting to some server that would be offline, eg. ws://localhost:12345. The default TCP connection timeout value seems to be set to 20 secs in lws, as that's the time it takes for the `LWS_CALLBACK_CLIENT_CONNECTION_ERROR` callback to be issued. That makes my test case take way longer to execute than I'd like, and so I'd expect to be able to reduce this default value during testing by setting the `timeout_secs` member of the context creation info structure, but unfortunately that doesn't seem to be honoured for the TCP connection phase.

Peeking at the lws source code I found this default timeout value to be defined as `#define AWAITING_TIMEOUT 20`, and `timeout_secs` is initialised with it if no other custom value has been set in the context creation info. However [on this line of code in client-handshake.c](https://github.com/warmcat/libwebsockets/blob/673f90d076f300b1240304fb53cf0857343ad6b0/lib/roles/http/client/client-handshake.c#L562) lws uses `AWAITING_TIMEOUT` directly instead of `wsi->context->timeout_secs`, which would have honoured whatever timeout value I've created the context with (I've tested that and it works).

So essentially the TCP connection timeout seems to be hardcoded at 20 secs currently. I'd hope this is a bug and not the intended behaviour but searching through the past issues here on github I found that someone had already suggested [the same fix on issue #570](https://github.com/warmcat/libwebsockets/issues/570#issuecomment-228115763) and it was kinda ignored. So I guess my question is, is there any chance such fix could be merged in or is there a good reason not to?

**Comment by lws-team** [comment]
Looking at 570, it has 32 comments and is about windows, his problem was something else which was patched.  Once his actual problem was fixed he went away happy.  I didn't patch the timeout but that wasn't his real problem...

If your server is down, your client connect will fail immediately since the tcp connect is assertively rejected at the server side... this is really about if the port is firewalled off and dropping connects rather than closed... it's not crazy to deal with that by a 20s timeout.  570 was about on windows, he didn't get immediate connection refused behaviour but fell into this timeout unexpectedly as a catchall.  Like you he's still operational just not what he expected for when it failed.

However no reason to not clean out AWAITING_TIMEOUT usage in favour of the context var, which defaults to AWAITING_TIMEOUT if not set anyway.  I pushed a patch on master to change all the instances.

**Comment by ohierro-verimatrix** [comment]
That was an incredibly fast turn around, thank you! 👍 

And you're right that I'm most likely dealing with a firewalled port, rather than just closed. I assume iOS filters out all the unused ports even for the localhost interface (or at least the iOS simulator does, which is where I'm actually running my test cases).
