### ISSUE TITLE
[question] How to "force" writeable callbacks?

### ISSUE THREAD

**Issue by andranik-s** [warmcat/libwebsockets#1825]
Basically what I am trying to do is to write a function of this sort
```status send_all(ws_connection*, msg_queue*)```
which sends all the data that is in a message queue using libwebsockets library.

I understand that using libwebsockets that way somewhat contradicts the idea behind the library, but unfortunately I am forced to do that due to external restrictions.

My current solution looks like this:
```
send_all:
    lws_callback_on_writable(wsi);
    while(!empty(msg_queue))
        lws_service(context, some_small_timeout);
```
```
callback:
    ...
    case LWS_CALLBACK_SERVER_WRITEABLE:
        int n = lws_write(wsi, get_msg_from_queue(msg_queue), ...);
        ...
        if(!empty(msg_queue))
            lws_callback_on_writable(wsi);
    ...
```

Are there other (better) ways to do that and are there any major pitfalls with this approach?

**Comment by lws-team** [comment]
I thought this was going to be something awful but it's not so crazy.  The problem will be events occur outside of what you expect or want, like timeouts or error on other side closing that must be cleaned up.

> I am forced to do that due to external restrictions.

I guess the restriction is you basically want to block until it's sent... there are other ways to achieve that.  Eg, you can put lws in his own thread, arrange locking for the shared objects and use a mutex to block the thread that's waiting.  You can see how to wake lws to the fact another thread has something for him here

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads/protocol_lws_minimal.c#n120

lws will "wake up" here and can lock and check your shared objects to figure out what you want, and start sending it from there in the event loop thread context

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads/protocol_lws_minimal.c#n262

**Comment by andranik-s** [comment]
Thank you for your prompt reply.

> I guess the restriction is you basically want to block until it's sent...

Yeah, that's a much better way to put it.

One more question:
The documentation for lws_service says that
> Since v3.2 internally the timeout wait is ignored, the lws scheduler is smart enough to stay asleep until an event is queued.

So does that mean I can use `some_small_timeout = 0` for v3.2 and what should I use for earlier versions of the library (will 0 timeout result in active waiting)?

**Comment by lws-team** [comment]
Earlier lws needs it to be around or below 1s so it can handle timeouts.  In v3.2 and above it's ignored.

**Comment by andranik-s** [comment]
> Earlier lws needs it to be around or below 1s so it can handle timeouts.

That's a little confusing to me.

The docs for v3.1 say that "you would call it with a timeout_ms of 0, so it returns immediately if nothing is pending, or as soon as it services whatever was pending". Timeout handling is not mentioned there. 

I've also seen it used with 0 timeout here (for v3.1): https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib/minimal-http-server-eventlib.c?h=v3.1-stable#n112.

Am I missing something?

(Sorry if those are silly questions I'm quite new to this library)

**Comment by lws-team** [comment]
> The docs for v3.1 say that "you would call it with a timeout_ms of 0, so it returns immediately if nothing is pending, or as soon as it services whatever was pending".

It's correct.  But normally you don't want that, you want it to spend most of its time asleep if it is idle.

The difference with older and new versions is you would call the old one with, eg, 1000 so it could wake once a second and check timeouts.  The newer one, the timeouts schedule themselves on a central sorted link-list, this value is ignored.  lws will take care of sleeping according to the interval between now and the earliest scheduled event on that list.  If none, it'll just stay asleep.

In both cases, any network event will wake it immediately to deal with it.

In the v3.1 example, it's 0 but as far as I know, it's not good for idle on that version.  v3.2+ 0 is fine since it's ignored.

**Comment by andranik-s** [comment]
Well, the problem is that I don't want it to spend any more time than necessary to send all the data. That's why 1s timeout is too big for me. I guess I'll need to do a bit of experementing to figure it out.

Thanks anyways. I really appreciate your help.

**Comment by lws-team** [comment]
1s timeout **if everything is IDLE and no network events** (incoming data, or able to send something / WRITEABLE).  Otherwise it wakes immediately and handles the event (WRITEABLE is a POLLOUT event...)

**Comment by andranik-s** [comment]
Ok, got it. Thank you.

**Comment by andranik-s** [comment]
One last question:
In the context of this issue, is there a way to tell libwebsockets that I'm currently interested in POLLOUT events **only**?

**Comment by lws-team** [comment]
> One last question:

Experience tells me whenever somebody says this, the chances of ever getting any contribution from them is zero.

> In the context of this issue, is there a way to tell libwebsockets that I'm currently interested in POLLOUT 

http is half-duplex, transactions consist of the client sending stuff to you and then separately, you sending stuff back to the client.  At the time you are wanting to do POLLOUT then, there isn't any POLLIN coming related to the transaction.  There's pipelining possible with http/1.1 but discarding that isn't the right thing to do.  The only other thing it cares about is error conditions, which you have to pay attention to.  So asking this question suggests your problem is elsewhere.
