### ISSUE TITLE
SSL host-name check disabled if OpenSSL method not found

### ISSUE THREAD

**Issue by vaind** [warmcat/libwebsockets#1827]
If `X509_VERIFY_PARAM_set1_host` is not defined (for whatever reason), LWS will still happily compile (that's good) and verify certificates. However, it will just skip hostname validation, regardless of the `LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK` flag passed during setup.

I think this poses a potential security issue and would have expected the client setup or connection to fail if LWS can't check SSL domain names while "skip-hostname-check" is FALSE. If user doesn't pass the skip flag, it means he *does* want to validate domain names (since not doing so is insecure in a public environment).

**Comment by lws-team** [comment]
I see the point.  Actually that api was only introduced in OpenSSL 1.0.2, 0.9.8 is still quite widely used due to Ubuntu LTS and old RH... it adapts at cmake-time to use what's available in the tls lib or not.

But I guess few users chose the tls lib with the careful consideration about exactly what apis it has or not for security... we should do better about it failing safe and putting it in their face as you say.

I pushed a patch on master and v3.2-stable that lets it build but blows an lws_err describing the situation and killing the connection if you try to bring up tls-based client connection without the api in your lib and didn't explicitly allow it with `LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK`, please give that a try.

**Comment by vaind** [comment]
> please give that a try.

Sorry, won't be able to replace that in our dependency/build setup but I've had a look at the code and the changes look good to me. Closing the issue.
