### ISSUE TITLE
Server crashes on Windows when port is in use by another application

### ISSUE THREAD

**Issue by Xmire** [warmcat/libwebsockets#1839]
I got these errors prior to crash, when using RELEASE version:
```
ERROR on binding fd 884 to port 8888 (-1 10048)
init server failed
Failed to create default vhost
Failed to find fd -1 requested for delete in hashtable
no wsi for fd -1325626582 pos 0, pt->fds_count=-1
```

And with the DEBUG version it breaks at `core-net\pollfd.c:377`:
```
Assertion failed: m == LWS_NO_FDS_POS || (m >= 0 && (unsigned int)m < pt->fds_count),
```

The issue can be reproduced using `test-server.c`. You only need to remove option `LWS_SERVER_OPTION_EXPLICIT_VHOSTS` and use port that is already taken by another application.

Problem goes away when I remove this code at `core\context.c:779`:
```
	for (n = 0; n < context->count_threads; n++)
		lws_destroy_event_pipe(context->pt[n].pipe_wsi);
```

But this adds a memory leak, I assume.

**Comment by lws-team** [comment]
Thanks for the detailed info... on Linux, it doesn't make the problem hacking test-server.c as described.  But that makes sense since the pipe wsis do have a valid fd provided by pipe() or pipe2(); on windows that's done using a WSA event and there isn't any valid fd, which creates the conditions for the problem.

I think it's enough just to check there's a valid fd associated with the "pipe" wsi before trying to remove the mapping for the fd.

```
diff --git a/lib/core-net/vhost.c b/lib/core-net/vhost.c
index d4273a5df..2c801f4dc 100644
--- a/lib/core-net/vhost.c
+++ b/lib/core-net/vhost.c
@@ -934,7 +934,9 @@ void
 lws_destroy_event_pipe(struct lws *wsi)
 {
        lwsl_info("%s\n", __func__);
-       __remove_wsi_socket_from_fds(wsi);
+
+       if (lws_socket_is_valid(wsi->desc.sockfd))
+               __remove_wsi_socket_from_fds(wsi);
 
        if (!wsi->context->event_loop_ops->destroy_wsi &&
            wsi->context->event_loop_ops->wsi_logical_close) {
```

I also added this on master, please give it a try.

**Comment by Xmire** [comment]
Thanks for the quick response. After this patch problem is solved.
