### ISSUE TITLE
Problems with last versions of the library

### ISSUE THREAD

**Issue by EMZAMS** [warmcat/libwebsockets#1842]
We have a server developed in C that runs using the libwebsockets library in an ARM Cortex-A53 processor. Meanwhile everything runs perfectly when using old versions of the library (such as v1.7), we are experiencing very long delays when using latest versions, as v3.0 or v3.2. It seems that sometimes, when the function lws_service is called, the software stays there for a few seconds (about 5 seconds) without doing anything (apparently) nor sending anything. Is it possible that latest versions have some issues when run in ARM processors?

**Comment by lws-team** [comment]
No, this is related to changes at v3.2 with how lws uses the poll wait.

Previously it would wake once a second and poll whatever needed doing.  Since v3.2 everything that depended internally on that behaviour shifted to using the lws_sul scheduler, see here -->

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.lws_sul.md

Lws will now stay asleep until there's something to do, either a network event, a scheduled event (lws_sul) or lws_cancel_service() from another thread.

If you have stuff that sometimes wants to run, you should move to adding an lws_sul for it as described in the article above.
