### ISSUE TITLE
use-after-free when calling lws_cancel_service() on LWS_CALLBACK_CLOSED_CLIENT_HTTP

### ISSUE THREAD

**Issue by oscahie** [warmcat/libwebsockets#1847]
I'm seeing this crash after updating lws from an already pretty recent snapshot from master (taken at around January 10th) to the most recent commit as of today. As shown in the minimal-http-client example, I'm calling `lws_cancel_service(lws_get_context(wsi));` when receiving an `LWS_CALLBACK_CLOSED_CLIENT_HTTP` callback, in order to interrup the servicing loop and proceed to destroy the lws context. This has been working fine so far, with daily runs of an extensive test suite. However after some recent changes in lws (I'm guessing [this changeset](https://github.com/warmcat/libwebsockets/commit/529a4d3af8105b4748175199e55df7c5dad47d1a)), doing this results in a use-after-free crash within `pws_plat_pipe_signal()` while destroying the lws context, which triggers an `LWS_CALLBACK_CLOSED_CLIENT_HTTP` event.

I'm attaching an image of the crashed thread's stack trace.

![image](https://user-images.githubusercontent.com/851717/75054697-dbc25480-54d3-11ea-8fa8-b1494dab8c73.png)

It could well be that I'm doing something funky with lws, though this particular implementation is pretty similar to the minimal example.

**Comment by lws-team** [comment]
Right... I updated the patch you pointed to with a couple of extra lines that should fix it, please fetch current master (eg, `git fetch https://libwebsockets.org/repo/libwebsockets +master:q && git reset --hard q`) and give it a try.

**Comment by oscahie** [comment]
The fix seems to work, thank you.

Rewriting history for all the commits since that patch was a bit unnecessary though, IMHO ;)

**Comment by lws-team** [comment]
For me, adding more and more patches to fix what's wrong with the original patch, then patches to fix or revert other things is worse... the problem is in the patch so fix it there.  CI makes this particularly stark since it only tells me something's wrong after the original patch is pushed.  It just took a bit longer to realize than usual is all.

If the fix is a complex separate issue from the original patch, if it's from a long time ago, or if it's not master branch then use a patch-on-top...if none of those then there is no reason to respect the history of master.
