### ISSUE TITLE
Confused about NO_PENDING_TIMEOUT

### ISSUE THREAD

**Issue by Unit2Ed** [warmcat/libwebsockets#1856]
I've inherited some code that does `lws_set_timeout(Wsi, NO_PENDING_TIMEOUT, 0);` on these callbacks:
`LWS_CALLBACK_CLIENT_ESTABLISHED`
`LWS_CALLBACK_CLIENT_RECEIVE`
`LWS_CALLBACK_CLIENT_WRITEABLE`
`LWS_CALLBACK_ESTABLISHED`
`LWS_CALLBACK_RECEIVE`
`LWS_CALLBACK_SERVER_WRITEABLE`

What's the effect of this `lws_set_timeout` call; I'm struggling to understand it from the documentation, examples, issues and source.

Overall, I'm trying to figure out why occasionally our websockets very occasionally just stop transmitting (or stop receiving; I'm not sure which). It feels like the connection should've dropped, but this hasn't happened (or hasn't been detected by lws), and it feels like a problem that the `lws_set_timeout` call could be suppressing, or that `ws_ping_pong_interval` could help with.

I apologise for the slightly vague question!

**Comment by lws-team** [comment]
It cancels any pending timeout on the wsi.  The timeout protects against some expected step never happening and immortal zombie logical connections piling up.  They're applied by lws at many stages of the connection, getting a connection at all, establishing tls, getting a response from the server etc.

For ws, lws cancels anything pending at ESTABLISHED by itself already.  It sounds like the original author had problems with timeouts killing him and performed black magic ceremonies everywhere in his code to try to suppress the evil.  Unless he sets timeouts on his own protocol actions, since it's ws in fact lws won't kill his connection by itself because of these kind of timeouts once it has been established.

In master and I think v3.2 there's a separate connection validity time aimed at confirming idle connections have passed traffic in both directions successfully within that time.

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.lws_retry.md
