### ISSUE TITLE
Assigning to 'struct per_vhost_data__minimal *' from incompatible type 'void *'

### ISSUE THREAD

**Issue by rajhlinux** [warmcat/libwebsockets#1857]
Im trying to build the example "minimal-ws-server" on Xcode 11.4 Beta 2 and I get the following error:

Cannot initialize a variable of type 'struct msg *' with an lvalue of type 'void *'
and
Assigning to 'struct per_vhost_data__minimal *' from incompatible type 'void *'

What is causing the issue?
See the picture below,

Thanks.

![Screen Shot 2020-03-09 at 7 43 29 PM](https://user-images.githubusercontent.com/61344181/76266888-54990e80-623f-11ea-8a67-0892cbb659f5.png)

**Comment by lws-team** [comment]
Your toolchain wants to see explicit casts from void *, on the basis it's possible to introduce silent bugs since in C void * is allowed to be compatible with any pointer type.

So like `struct msg *msg = (struct msg *)_msg;`... are you telling it to build it as c++?  Because in C that's perfectly legal without casts AFAIK.

**Comment by rajhlinux** [comment]
Yes I was compiling it as C++, changing the source file as "C" solved the above issue. 

But now having a new weird issue...

![Screen Shot 2020-03-09 at 10 13 31 PM](https://user-images.githubusercontent.com/61344181/76273069-5240af80-6253-11ea-8ca7-8bf06ce94d22.png)

**Comment by lws-team** [comment]
That's nothing to do with lws... ask your proprietary toolchain vendor.
