### ISSUE TITLE
v4.0.0 won't compile due to unused variable

### ISSUE THREAD

**Issue by tsl0922** [warmcat/libwebsockets#1858]
```
[ 36%] Building C object CMakeFiles/websockets.dir/lib/tls/openssl/openssl-client.c.o
/tmp/tmp.1SeZZ4XkW7/libwebsockets-4.0.0/lib/tls/openssl/openssl-client.c: In function ‘lws_tls_client_connect’:
/tmp/tmp.1SeZZ4XkW7/libwebsockets-4.0.0/lib/tls/openssl/openssl-client.c:372:12: error: variable ‘en’ set but not used [-Werror=unused-but-set-variable]
  int m, n, en;
            ^
cc1: all warnings being treated as errors
```

https://github.com/tsl0922/ttyd/pull/281/checks?check_run_id=496758062

**Comment by lws-team** [comment]
I pushed a patch on master and v4.0-stable that fixes a few problems building in RELEASE mode including this, please give it a try.  It's better to pin to `v4.0-stable` rather than point releases, especially .0 releases since most people take the approach to only start to care about it "once it is released" and every major release gets their testing afterwards, not before...

**Comment by tsl0922** [comment]
Thanks. Although I can change it to branche in my ci script, but package managers usually use release tags (for example: homebrew/openwrt/...), thus I only test upon tags.

**Comment by lws-team** [comment]
OK... this is bad enough I'll wait until the CI completes my side and tag out 4.0.1 (it won't be exactly that commit because I have to bump the version in CMakeLists.txt to match).

**Comment by lws-team** [comment]
It's tagged out.
