### ISSUE TITLE
simple http get post

### ISSUE THREAD

**Issue by smalls12** [warmcat/libwebsockets#1874]
Hello,

I've been scanning some of the examples you have but I have been unable to find an example which just minimally handles HTTP GET/POST.

Ideally where the server just provides the URL and Data without any routing or form presentation for processing somewhere else.

I'm certain this is possible, just hoping to be pointed in the right direction.

Sorry if this is something that is obvious and I'm just cant see it.

Thanks,

**Comment by lws-team** [comment]
The example is being a client or a server?

**Comment by smalls12** [comment]
Whoops, a server.

**Comment by lws-team** [comment]
The http server examples are handling stuff using the mounts, because by far the most common usecase involves serving files and often it's useful to map more than one thing into the url space.

The closest example is probably http-server-dynamic

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-dynamic/minimal-http-server-dynamic.c

and for post related stuff

https://libwebsockets.org/git/libwebsockets/tree/plugins/protocol_post_demo.c

it's not quite what you're asking for but you should be able to chop down and ,ix and match.

**Comment by smalls12** [comment]
Ok I will take a look, thanks.

**Comment by gupta05** [comment]
Hi @smalls12 , were you able to get simple server/client working? I am looking for something similar. If yes, can you please share your code. Thank you

**Comment by smalls12** [comment]
I have not taken this any further.
