### ISSUE TITLE
some problems about h2 and websocket over h2.

### ISSUE THREAD

**Issue by jackim** [warmcat/libwebsockets#1876]
1 websocket over h2 
nghttp -v -H ":method: CONNECT" -H ":protocol: websocket" -H "sec-websocket-version: 13" https://127.0.0.1:7961/

the `lws_get_socket_fd` can not get real fd.

2 http2 
char[] tmp = "hello world";
lws_write(lws, tmp , sizeof(tmp) , LWS_WRITE_HTTP )
will be error ，calls Out of memory ,  because in http2.c i found this code below:
unsigned char *p = &buf[-LWS_H2_FRAME_HEADER_LENGTH];

**Comment by lws-team** [comment]
1) I don't understand what you think you're telling me... you can get rfc8441 client connection using https://libwesockets.org/testserver if your browser is enabled for it

2) look into how LWS_PRE is used, eg

https://libwebsockets.org/git/libwebsockets/tree/plugins/protocol_dumb_increment.c#n48

**Comment by jackim** [comment]
2 not websocket  。 http2 server.   see  LWS_WRITE_HTTP

**Comment by lws-team** [comment]
Doesn't matter, you need LWS_PRE preamble in your buffer if you will work with h2.

With h1, you can get away without it, but h2 also uses it for h2 frame same as ws uses it for ws frame behind the payload with additional copying.

Refer to the http examples, they're set up to do this since they work with h1 or h2 interchangeably, eg

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-dynamic/minimal-http-server-dynamic.c#n44

**Comment by jackim** [comment]
1  in callback LWS_CALLBACK_ESTABLISHED, call lws_get_socket_fd
LWS_VISIBLE lws_sockfd_type
lws_get_socket_fd(struct lws *wsi)
{
    if (!wsi)
        return -1;
    if (wsi->desc.sockfd != INVALID_SOCKET) // in websocket over h2 , this is INVALID_SOCKET
        return wsi->desc.sockfd;
    if (wsi->h2.parent_wsi != NULL)   // in websocket over h2 , this is realy fd
      return wsi->h2.parent_wsi->desc.sockfd;
}

**Comment by lws-team** [comment]
Yes, in http2 many streams / wsi can share one network connection.

So the network connection wsi that owns the fd is separate from any stream / transaction wsi.

There isn't a 1:1 relationship any more between stream / transaction wsi and fd.

Consider client connect 1 starts the socket link and tls tunnel, then stream 2 starts sharing it, and stream 1 completes.  The socket fd is still alive even after stream 1 is destroyed, since it has work to do for stream 2 and whatever else might start using it.

**Comment by jackim** [comment]
about point 2 . in  file lws-write.h  enum lws_write_protocol no description for  LWS_WRITE_HTTP, only for LWS_WRITE_TEXT or LWS_WRITE_BIN and may use LWS_H2_FRAME_HEADER_LENGTH be better.  so......
