### ISSUE TITLE
Compile time option for symbol visibility?

### ISSUE THREAD

**Issue by dzakarias-verimatrix** [warmcat/libwebsockets#1884]
I can see LWS_VISIBLE in libwebsockets.h, however it has a fixed value. It would be useful to have a config option in CMakeLists.txt to enable/disable visibility. Thanks!

**Comment by lws-team** [comment]
Well, it's a library, it's job is to expose some exports.

What's actually the problem you're seeing?

**Comment by dzakarias-verimatrix** [comment]
In case of building a static library, typically there's no need for the symbols to be visible.

**Comment by lws-team** [comment]
So it's enough to just #define it to nothing if building the static lib?

**Comment by dzakarias-verimatrix** [comment]
Or, to be more explicit, __attribute__ ((visibility ("hidden"))) in case of a Unix build (nothing is fine in case of Windows)

**Comment by lws-team** [comment]
I don't think explicitly telling it hidden is needed, since that's the default.

**Comment by TheRealSaluki** [comment]
You're right, in CMakeLists.txt there's the -fvisibility=hidden flag already. Defining it to nothing as you suggested above would be perfect then.

**Comment by dzakarias-verimatrix** [comment]
OK, I can see in CMakeLists.txt, you have -fvisibility=hidden set. So your suggestion above (defining it to nothing) will be perfect.

**Comment by lws-team** [comment]
> In case of building a static library, typically there's no need for the symbols to be visible.

This has taken a while... basically it's mildly advantageous to not export these symbols, since the compiler and linker consuming them can understand they can be directly consumed and optimize its arrangements for creating and consuming them.  I think it's only going to be a few bytes but it may be a net positive when building a static lib for, eg, RTOS build.  But for that minor advantage, it means we have to show the compiler that they're definitely local-only, that means messing with the visibility attribute according to if we're building the lib static or shared, or not building the lib.  The decision to take up more space or not when using the symbols is happening at compile time and it can't be undone at link-time by just removing the symbols.

That's not so simple to do that as it turned out... there's a patch on master today that should provide this, if you're still interested in this please give it a try and let me know if any problem.
