### ISSUE TITLE
SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=1) on CentOS 8

### ISSUE THREAD

**Issue by mohabouje** [warmcat/libwebsockets#1902]
First of all, thanks for this amazing library.

I've recently decided to use this library to connect to external websocket. I've tried it on Mac OS X, and it works perfectly fine.

Now, I'm trying to run the code on CentOS 8, and I'm running into this issue:

```cpp
[2020/04/30 12:19:01:9235] E: SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=1)
```

This is the code I'm using to setup the socket:

```cpp

lws_context_creation_info info;
lws_client_connect_info i;

memset(&info, 0, sizeof info);
info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
info.port = CONTEXT_PORT_NO_LISTEN;
info.protocols = protocols;
info.fd_limit_per_thread = 1 + 1 + 1;
info.gid = -1;
info.uid = -1;
info.user = this;

context = lws_create_context(&info);
if (!context) {
    logger::debug("lws init failed"_f);
    return;
}

memset(&i, 0, sizeof i);
i.context = context;
i.port = 443;
i.address = std::data(uri);
i.path = "/";
i.host = i.address;
i.origin = i.address;
i.ssl_connection = LCCSCF_USE_SSL | LCCSCF_ALLOW_SELFSIGNED;
i.protocol = protocols[1].name;
i.pwsi = &client_wsi;
lws_client_connect_via_info(&i);
```

I've tried to manually download the certificate from the website: 

```bash
curl --cacert certificate.crt -v ws-feed.pro.coinbase.com
```
or 
```bash
echo | openssl s_client -servername ws-feed.pro.coinbase.com -connect ws-feed.pro.coinbase.com:443 |\
  sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > certificate.crt
```

and then use if in the configuration:

```cpp
memset(&info, 0, sizeof info);
info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
info.port = CONTEXT_PORT_NO_LISTEN;
info.protocols = protocols;
info.fd_limit_per_thread = 1 + 1 + 1;
info.gid = -1;
info.uid = -1;
info.user = this;
info.ssl_ca_filepath = "./certificate.crt";
```

But It does not fix the issue.

**Comment by lws-team** [comment]
Your platform doesn't seem to trust their cert stack as it is.

> LCCSCF_ALLOW_SELFSIGNED

You don't want to do that.

That site has a stack of 3 certs, the CA is this

Baltimore CyberTrust Root   Self-signed	
Fingerprint SHA256: 16af57a9f676b0ab126095aa5ebadef22ab31119d644ac95cd4b93dbf3f26aeb
Pin SHA256: Y9mvm0exBk1JoQ57f9Vm28jKo5lFm/woKcVxrYxu80o=
RSA 2048 bits (e 65537) / SHA1withRSA 

The server won't send you that because it expects you to have it and trust it already.

Then there is an intermediate (which this server is sending)

CloudFlare Inc ECC CA-2
Fingerprint SHA256: 6172d7a1996cbef71a0182dd44b99e9c035742a9ebd0311aa73aa4733344c5a6
Pin SHA256: 3kcNJzkUJ1RqMXJzFX4Zxux5WfETK+uL6Viq9lJNn4o=
EC 256 bits / SHA256withRSA 

finally there's the actual server cert, which it sends you as you would expect.

pro.coinbase.com
Fingerprint SHA256: ecf2fab2b0f02179fb003ab345c90fc0d36ecdc1524cd0e8aaaca29c7104994d
Pin SHA256: 6fIb9+8yvAVdlIhPJjl/fjYdYdqpcnso+C6tgk6gGTE=
EC 256 bits / SHA256withECDSA 

You need to trust the first one mentioned there, the CA public cert. You can get it here

https://censys.io/certificates/16af57a9f676b0ab126095aa5ebadef22ab31119d644ac95cd4b93dbf3f26aeb/pem

Download that and do what you're trying to do at the moment with the wrong (intermediate) cert.

**Comment by mohabouje** [comment]
Thank you for the detailed explanation, I've updated the certificate, everything works fine =)
