### ISSUE TITLE
http1.1 client request timeout

### ISSUE THREAD

**Issue by TryAgain2019** [warmcat/libwebsockets#1907]
Hi,

  Every http/1.1 client request i make seems to drop + close after some 5 seconds. The server where i send the requests states it keeps the connection alive for 90seconds. Since i might send more requests and reuse the old connection i would like to change this 5 seconds timeout. Can you please tell me where it is?
I blindly tried to do this in LWS_CALLBACK_ESTABLISHED_CLIENT_HTTP:

                lws_set_timeout(wsi, PENDING_TIMEOUT_CLOSE_ACK, 90);
                lws_set_timeout(wsi, PENDING_FLUSH_STORED_SEND_BEFORE_CLOSE, 90);
                lws_set_timeout(wsi, PENDING_TIMEOUT_CLOSE_SEND, 90);

and this in the context creation part:

     lws_context_creation_info info = {};
     info.timeout_secs = 90;
     info.timeout_secs_ah_idle = 90;
... 

But without success. Can you please tell me how to change this so the connection remains open?

2) Can i instruct the server i don't eat cookies so that it doesn't send me cookie info in the response?

thank you

**Comment by lws-team** [comment]
> Since i might send more requests and reuse the old connection i would like to change this 5 seconds timeout.

This is the time lws would hang around after the last h1 transaction completes in case the connection could be reused.  It's not related to timeouts you might set on your transaction activity, because your transaction has finished and now lws is managing keeping the connection "warm", not your code.

Lws' idea for that at the moment is to just literally give you a fixed 5s

https://libwebsockets.org/git/libwebsockets/tree/lib/core-net/wsi.c#n801

> Can i instruct the server i don't eat cookies

That's not really an lws thing... AFAIK there's no standardized way to tell a server that.  It will just notice the cookie isn't coming back.

**Comment by TryAgain2019** [comment]
I see, will rebuild the lib with my 90 fixed value then. But i think the ability to input this from user code might be useful for other people too.

**Comment by lws-team** [comment]
I added a patch on master for this.
