### ISSUE TITLE
Function create_context() randomly crashed 

### ISSUE THREAD

**Issue by lonelybeansprouts** [warmcat/libwebsockets#1919]
LOG:  "E: Unable to open random device /dev/urandom -1"

**Comment by lws-team** [comment]
Recent versions of lws show the errno if it meets that situation

https://libwebsockets.org/git/libwebsockets/tree/lib/plat/unix/unix-init.c#n129-130

you should do the same to get a clue.

This during unix plat init, whatever it is, it's going to be something related to your code or more likely your platform.  Just saying, "hey this happens to me on my platform" doesn't give me any way to guess what you actual underlying issue is... you are going to have to debug your problem on your platform, not me.

**Comment by lonelybeansprouts** [comment]
Ok, thanks.
