### ISSUE TITLE
How to send data from the server

### ISSUE THREAD

**Issue by stevedanOgochu** [warmcat/libwebsockets#1934]
I am using the websocket server example and I am trying to find a way to send data from the server and not only receive and send the data received. Is there a way to know if a connection have being made, not destroy the connection yet until I have send data from the server?

Thank you very much

**Comment by lws-team** [comment]
It's not clear what you are asking...

> not destroy the connection yet until I have send data from the server?

ws connections will stay up until one side or the other decides to drop them or applies some kind of timeout policy to them being idle.

If you want to send, eg, canned data to everyone who connects, you'd

 - create a struct pss and mention it in the struct protocols as being the "user" type... every guy that connects gets one of those, initially zeroed down, associate with his wsi.

 - in the protocol callback cast the `user` parameter to your struct pss type.  That's "the wsi's" user object

 - in the _ESTABLISHED callback, initialize your stuff in your pss and ask for a writeable callback for that wsi.

 - in the _WRITEABLE callback, look in the pss to find out what you need to write.  Change the state of the pss members to reflect what you have written.  If there is more to write, ask for another writeable callback.

 - optionally if you want to close the connection to the client, return -1 from the callback.  Otherwise return 0 and it will stay up.

Is this what we are talking about?

**Comment by stevedanOgochu** [comment]
More or less that is what i has in mind
If I create a struct pss as a global variable and I did something like this to check whether the user has indeed connected,
struct per_session_data__minimal myuser;


In the main function can I do this like to make sure I get a connection, then later send the data
```
	while (n >= 0 && !interrupted)
	{
		if (myuser.wsi)
		{
			printf("GOOOOOD!!![][] Got a connection\n");
			break;
		}

		n = lws_service(context, 0);

	}
```

After this, i  can write to all the clients like this 
......

```
lws_callback_writable( myuser.wsi);
while (n >= 0 && !interrupted)
		
		n = lws_service(context, 0);
```


in the callback function 
For the casting, it should look like this right?

myuser = (struct per_session_data__minimal *)user;

**Comment by lws-team** [comment]
> If I create a struct pss as a global variable

No the meaning of this "pss" stuff is that just like lws will create you a wsi automatically for each client, lws will also create you a pss for each wsi automatically.  Then if you have multiple connections, and they are all accepting the data that you are sending at different speeds, you must track how far you got in sending each one the data individually, you can use the pss for that.  So you do not want a single static global var, you want a pss per client wsi, which lws wants to give you.

You must tell lws the size of the pss struct to allocate in the protocol definition, like this

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server/protocol_lws_minimal.c#n151

> 			printf("GOOOOOD!!![][] Got a connection\n");

No do that instead in the `_ESTABLISHED` callback, like here

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server/protocol_lws_minimal.c#n84

That is coming when a new client connection reaches your protocol.

> lws_callback_writable( myuser.wsi);
> while (n >= 0 && !interrupted)
> n = lws_service(context, 0);

No... forget that service loop for adding code, it's like the heart of the event loop but you have to add your code on its events, not deal with it directly.

You would do the ` lws_callback_writable(wsi);` also in the `_ESTABLISHED` callback.  When you get a new connection, if it succeeds to make the ws upgrade, you will get an `_ESTABLISHED` callback with its wsi.  It's all the same if one, ten or a thousand connections come, if they come immediately or hours later, they each cause an `_ESTABLISHED` with their new wsi when they succeed to connect at ws level.  So that is the place to ask the connection to do something to get started like `lws_callback_writable(wsi);`.

**Comment by stevedanOgochu** [comment]
Perfect, thank you very much, I will implement that now.
