### ISSUE TITLE
undefined reference to `lws_json_dump_context'

### ISSUE THREAD

**Issue by GuoDangLang** [warmcat/libwebsockets#1943]
Hi, 
    When I call lws_servcie(context, 0),  the app would get segmentation fault, so I use lws_json_dump_context and lws_json_dump_vhost in my code to see context and vhost stats. But, I got the problem just as the title described.
    So, why do I get this error? 
    And by the way, If I get 2 vhost on 2 different ports using same protocols and libevent, then Are they sharing the same event loop? Can I send messages from one port to another port by writing messages received into ring buffer and call lws_callback_on_writable in the same protocol?

**Comment by lws-team** [comment]
> So, why do I get this error?

You have the sources, and you have the error.  You can debug it a bit yourself, right?

It takes me 30 seconds to read your problem and another 20 seconds to grep to find the function in the sources and look back up to see it's dependent on

`#if defined(LWS_WITH_SERVER_STATUS)`

because, eg, people building this for RTOS do not want all the optional stuff built in every time.  That's probably quicker result than your firing up github and writing the description.

> And by the way, If I get 2 vhost on 2 different ports using same protocols and libevent, then Are they sharing the same event loop? 

Yes, the event loop is instantiated in the per-thread struct, those in turn are instantiated by the `lws_context`.  Vhosts also exist inside your `lws_context` and use the event loop(s) from the same context per-threads.  By default, with LWS_MAX_SMP = 1, there is one per-thread in your context and so one event loop for everything.
