### ISSUE TITLE
What's the pros & cons of using sing head multiple tails ringbuffer?

### ISSUE THREAD

**Issue by GuoDangLang** [warmcat/libwebsockets#1945]
When do we need using single-head-multiple-tails ringbuffer while we can have a lot of single-head-single-tail ringbuffers created for each one of the sessions?

**Comment by lws-team** [comment]
You don't "need" to do anything, you can write your own implementation... the ringbuffer stuff is a completely standalone helper for user code, it doesn't have any special meaning to lws compared to your own code.

You have to reference what does your server want to achieve... if it wants to "broadcast" sequences of data to many clients, the multiple-tail ringbuffer scheme is efficient, since it only has to store one copy of the data while any client hasn't had it yet.

If that's not really what your server wants to do, and rather than "seeing" a "shared world" the clients live in their own little world, multi tail isn't necessary.  You can also look at a linked-list to hold data that only gets used for one client, eg the lws_dll2 stuff.

https://warmcat.com/2020/03/25/libwebsockets-lws_dll2.html
