### ISSUE TITLE
crash after LWS_CALLBACK_PROTOCOL_INIT on arm_linux

### ISSUE THREAD

**Issue by ljcNaruto** [warmcat/libwebsockets#1959]
here , I cross compile libwebsockets library on Arm linux platform, and handle lws_callback_function with reason  LWS_CALLBACK_PROTOCOL_INIT below where nothing to do : but crash after return                      

case LWS_CALLBACK_PROTOCOL_INIT:
			{
			    printf("LWSCallback protocol init do nothing ");
			}
			break;

**Comment by lws-team** [comment]
> crash after return

... telling me "crash" without a backtrace or some other info is completely non-actionable... it's great you have a high opinion of my debugging skills... but... what exactly do you think I can do with this information :-) ?

**Comment by ljcNaruto** [comment]
your log suggests below :
W: lws_create_context: LWS_WITHOUT_EXTENSIONS but extensions ptr set

**Comment by ljcNaruto** [comment]
I create context s below :       

lws_context_creation_info info = { 0 };

	info.vhost_name = m_lwsParam.Ip;                    
	info.port       = m_lwsParam.Port;                
	info.protocols  = protocols;                     
	info.options    = LWS_SERVER_OPTION_VALIDATE_UTF8; 

	m_lwsContext = lws_create_context(&info);

**Comment by lws-team** [comment]
It doesn't mean anything.

You have a crash, so you should have a backtrace... post that.

**Comment by ljcNaruto** [comment]
I pull a new code and problem disappered , anyway thank for your patient guidance very much !

**Comment by ljcNaruto** [comment]
but I'm confused about a new problem , described as below :

when I call lws_cancel_service_pt() on work thread , and in  lws_callback_function , handle case with 
LWS_CALLBACK_EVENT_WAIT_CANCELLED event , but this callback wsi is different from  lws_cancel_service_pt() param  where I called ,  I want to call lws_callback_on_writable in case LWS_CALLBACK_EVENT_WAIT_CANCELLED  to make assigned wsi which is same as lws_cancel_service_pt  become writeable , I don't know how to realize it

**Comment by lws-team** [comment]
Most things that happen in a protocol are specific to a wsi, for example you received data, or the socket underneath it closed.

But some things are notifications that don't actually have a relationship to a specific wsi, for example PROTOCOL_INIT is coming when a vhost is being created and instantiating protocols bound to it... we want to call back to the protocol callback because the code for it belongs there, but it's about a vhost / protocol combination... the event has no relationship to any wsi.

Since there is a lot of code out there in user protocol callbacks that assumes the wsi is valid at the top of the callback, eg, to get the context pointer from it every time, we cannot call it back with wsi = NULL in these circumstances.  So lws maintains a "fakewsi", it sets the context, vhost and usually protocol pointer in this empty wsi and uses it to call the callback when there's no real wsi to use, so the user code is not surprised.

The EVENT_WAIT_CANCELLED callback is the same deal, actually it applies to the event loop as a whole, it broadcasts these callbacks to notify the protocols, and does it by using the fakewsi since no real wsi is related to the activity.

`lws_cancel_service_pt(wsi)` takes a wsi, but it only does so in order to target the event wait cancel to the pt that the wsi uses, for the case LWS_MAX_SMP > 1 and there are multiple event loops in the process.  It does NOT remember the wsi or inform anyone about it or use the wsi in the callback.  It can't safely do so as I explain later.

When you are using `lws_cancel_service()` the approach is to have a mutex protecting a shared memory area

 - Other thread: lock the mutex + prepare an object in the shared memory area that indicates what you want (eg, add something to a queue) + unlock the mutex
 - Other thread: call lws_cancel_service()
 - LWS thread: handle in EVENT_WAIT_CANCELLED: lock the mutex
 - LWS thread: study the shared object to find out what to do, if simple do it right away
 - LWS thread: unlock the mutex

When everything runs in the lws thread context, you can be certain lws will not close and destroy a wsi while you are working on it, because everything is serialized in a single thread... if you are using the thread to dereference the wsi, the close action must wait to use the thread until you finished what you are doing, so there is never any race or conflict.

But if you gave an lws wsi to another thread, you can no longer be certain that the lws thread has not closed and destroyed the wsi and the other thread just did not hear about it yet.  If the other thread hands the dead wsi back to the lws thread to use, eventually it will crash.  Basically by sharing the wsi, you created a race between the threads about when the wsi is invalidated.

So you cannot safely directly do what you're trying to do there, at least you must maintain some list on lws side of living wsi and check any wsi you are told about from another thread and confirm it's still alive before using it on lws side.  Better is do not tell the other thread about any wsi pointer, instead pass it a pointer to your own lws-thread object associated with the wsi that has a reference count, and contains a pointer to the wsi that is set to NULL by lws thread when the wsi closes.

Even better is don't use threads...

**Comment by ljcNaruto** [comment]
so , there is no way to notify assigned wsi to  be writable from other thread ?  lws_callback_writable can not be called from other thread yet . this business circumstance maybe very usual .

**Comment by ljcNaruto** [comment]
I reference to your demo in protocol_lws_minimal.c , and add a writable flag related to wsi , just as below : 
case LWS_CALLBACK_EVENT_WAIT_CANCELLED:
		if (!vhd)
			break;
		/*
		 * When the "spam" threads add a message to the ringbuffer,
		 * they create this event in the lws service thread context
		 * using lws_cancel_service().
		 *
		 * We respond by scheduling a writable callback for all
		 * connected clients.
		 */
		lws_start_foreach_llp(struct per_session_data__minimal **,
				      ppss, vhd->pss_list) {
			lws_callback_on_writable((*ppss)->wsi);
		} lws_end_foreach_llp(ppss, pss_list);
		break;

here , iterate all wsi  to make assigned wsi writable according to writable flag changed by other thread

**Comment by lws-team** [comment]
I described how to do it above.  You cannot share wsi pointers between threads without some plan for handling the lws thread freeing the wsi.

**Comment by lws-team** [comment]
Yes, we do not share the wsi to the other thread in the example, so there is no problem.

**Comment by ljcNaruto** [comment]
yeah , I get your mind , acctually , maybe 2 solutions is workable ： 

1, do not share wsi to other thread , just use lws_cancel_service to notify and decide whether to make wsi writable according to other shared and thread safe variable 

2, thread safe about wsi must be considered  if directly use wsi shared to other thread

**Comment by lws-team** [comment]
You don't describe what you're doing but if it's a worker thread for a connection type situation, threadpool is designed to handle the wsi lifecycle problem internally.

https://libwebsockets.org/git/libwebsockets/tree/lib/misc/threadpool

**Comment by lws-team** [comment]
Yes, it depends on exactly what you try to do.  If you can leave wsi as a private thing for lws thread, this problem goes away.

If you wrap or abstract the connection instead of directly giving the wsi, you can manage the problem, this is how threadpool works.
