### ISSUE TITLE
No access to "code" and "reason" from close frame

### ISSUE THREAD

**Issue by davidgaleano** [warmcat/libwebsockets#196]
The WebSocket protocol supports sending a two byte "code" and a string "reason" as part of the closing frame, but I have not seen any way with the existing API to get that information, you can send it but on the receiving side it seems to not be accesible.

Looking at the code it seems the closing code is stored on an internal variable called "close_reason" but I have not find an official way to retrieve it. A public API could be provided in a similar way to "libwebsocket_is_final_fragment", for example "libwebsocket_get_close_code".
The close reason string could be passed as the "in" parameter for "LWS_CALLBACK_CLOSED".

**Comment by asari-fd** [comment]
> Actually, I have just remembered that libwebsocket_close_and_free_session is no longer public, so I don't know how to send a specific close code or reason to properlly test an implementation...

I'm also in trouble for I don't know how to send codes and a messages to client. (+1)

**Comment by geekhckr** [comment]
I am also facing the same issue. Are there any patches available?

**Comment by p0fi** [comment]
Im also having the same issue, I'd like so send a close code to the client once the connection is closed. Any news on this topic?

**Comment by jochenschoellig** [comment]
+1

**Comment by warmcat** [comment]
Looks like a lot of people want this but nobody sending patches (including me...)

Although +1 begins with a + it's not actually a patch...

**Comment by lws-team** [comment]
Guys... after a long time training in the mountains a hero rose up and made patches.

**Comment by JoakimSoderberg** [comment]
Nice! However I think removing the `LWS_CLOSE_FRAME` from being used is kind of drastic. It will break a lot of peoples code for no good reason. Also API changes like these makes it really hard to try to use a dynamic version of this lib on a system.

Still allowing the old way of closing, and simply adding this as an option would be better. But then again I have no patch to fix this. Just an opinion :)

**Comment by lws-team** [comment]
Hm no it's LWS_WRITE_CLOSE.  With it the only thing you could format and send your own raw close frames.

The code that implemented it was the only code that relied on there being POST buffering for lws_write() in user code.  That was also eliminated today.

With the other features here, it can be done instead using an api.

I think you find the number of people running *stock* lws who implemented their own close frame using that is zero, because eg LWS would have proceeded to send his own, and in any event the hacky code in output.c that is now gone trampled the return code in both case.

I agree it needs careful treading to have a stable distro library but I don't think this is a case that makes trouble for that.  Or, I am happy to hear why you think it'll "break a lot of peoples' code" if I missed the point.

**Comment by JoakimSoderberg** [comment]
Maybe I used too strong language. I did not meant that I have any statistics that proves this fact. If the use of this is very limited I guess it does not make much harm.

But I did a quick code search on github, the 3 top hits are not libwebsocket internal code, and they explicitly use this: https://github.com/search?q=LWS_WRITE_CLOSE&ref=searchresults&type=Code&utf8=%E2%9C%93

So they will have to rewrite their code because of this change.

I think the new API is nice. But more in a general sense I'm of the school of keeping old public APIs around at least for a while, deprecating it, and then finally removing it.

**Comment by lws-team** [comment]
Yes, actually removing it will clearly be a net negative on the harm front.

There's no argument about motherhood / apple pie / don't break things: also in the last 24h I pushed the patch to remove the POST padding completely from lws except leaving it defined to 0 exactly for compatibility.  So this is an active consideration already.

LWS_WRITE_CLOSE is a whole other thing though.  It only got into the public header in the first place because it was part of an enum that had other members like LWS_WRITE_TEXT that are public business.  We never used LWS_WRITE_CLOSE ourselves outside of the library internals nor encouraged it to be used, and it's clearly told the only way to close connections is return nonzero from the callback.

I can see only one project from your search (I checked the first two pages of results) that ill-advisedly use it in actual lws user code.

https://github.com/MickeMakaron/TypeTwo

```
void Connection::close()
{
    unsigned char* message = new unsigned char();
    libwebsocket_write(mWebSocketInstance, message, 0, LWS_WRITE_CLOSE);
}
```
and
```
unsigned char* derp = new unsigned char[1];
                libwebsocket_write(webSocketInstance, derp, 1, LWS_WRITE_CLOSE);
```

Both of these snippets are already completely broken - as in crash and burn - prior to today's patches lws will write not only beyond the end of it by 1 char but several chars behind it since he didn't take care of the PRE padding.

There looks like a second candidate...

https://github.com/felixdae/mycode

...but it's not so: that uses it in frame.c as a rewrite of lws in cpp, it **IS** internal library code not user code.  It's not even lws any more.

So there is one guy who must rewrite his code anyway because it's broken even with lws before these patches.  He will be happy I should think when his stuff stops crashing because he updated to the new official api.

I'm to blame for that guy's confusion by not providing the close management stuff until today and accidentally letting him get the bad ideas from leaving LWS_WRITE_CLOSE in the public header.  The new patches fix both those problems, and that's the right way in this special case.  Other things, yes, we should continue to deal with them to make them abi neutral like POST deprecation also today.

**Comment by JoakimSoderberg** [comment]
Ok you sold me :+1:  :)

**Comment by Arun19921991** [comment]
Currently am using libwebsockets 1.6 version,

**Comment by Arun19921991** [comment]
Is there any way to close Websocket client connection?
Currently am using libwesockets 1.6 c library,Now the implementation is like, client can close the connection on the callback by returning a negative value.But i need to wait for a callback to close the connection.In some cases the callback is not getting.

**Comment by lws-team** [comment]
This is improved in master / what will be 1.7.
