### ISSUE TITLE
ws client within external libev loop

### ISSUE THREAD

**Issue by parihaaraka** [warmcat/libwebsockets#1966]
Hello. Could you please explain the way to utilize existent libev loop? libwebsockets has libev helper but I can't get all together to find out the idea :( `minimal-http-client-multi.c` has libev option, but this example ends with its own loop `while (!intr && !lws_service(context, 0));`. What should I do with `lws_service()`? I would expect to pass a loop pointer to `lws_create_context` before `ev_run(loop, flags)` - and that's all.
I need simple things:
1) get everything in my loop;
2) handle signals myself (i need to set dummy handler now to avoid default handler (why it exists by default?));
3) log myself.

**Comment by lws-team** [comment]
It sounds like you didn't find this yet

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib-foreign

it exists to demonstrate how to integrate with separate, already-existing event loop, so that the lws context is created and destroyed entirely on the pre-existing loop, without stopping or affecting that loop.  Bonus is the lws side of the code is the same regardless of the loop, you just enable the one you want in the context options.

**Comment by parihaaraka** [comment]
> https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib-foreign
Is it ok to destroy a loop right after `lws_context_destroy(context)` call? What about
```C
  struct lws_context **pcontext;
  /**< CONTEXT: if non-NULL, at the end of context destroy processing,
   * the pointer pointed to by pcontext is written with NULL.  You can
   * use this to let foreign event loops know that lws context destruction
   * is fully completed.
   */
```

**Comment by lws-team** [comment]
Yes after the context destroy exits it's not going to refer to the loop any more.
