### ISSUE TITLE
How to use lws_client_connect_via_info() to build client connection in vhost.

### ISSUE THREAD

**Issue by mhy12345** [warmcat/libwebsockets#1968]
I want to connect multiple websocket servers in one process and be able to support manual reconnection of a single server (for example, use `lws_context_deprecate()` to close an old connection and then reconstruct a new one).

Here is my solution (not work):

1. Use `struct lws_context *context=lws_create_context(&info);` to construct a context with LWS_SERVER_OPTION_EXPLICIT_VHOSTS option.
2. Use `struct lws_vhost *vhost=lws_create_vhost(context, &info));` to construct a vhost for each service
3. Use `lws_client_connect_via_info(client_info);` to allow a single vhost to establish a connection with the server's websocket.

I encountered a problem in step 3, because I could not find a suitable interface, to get vhost->context and pass it into client_info.context. The definition of `struct lws_vhost` is in a private header file `lib/core-net/private-lib-core-net.h`.

```
error: invalid use of incomplete type ‘struct lws_vhost’
     client_info.context = vhost->context;
In file included from .../include/client/client.h:6:0,
                 from .../src/client/client.cpp:5:
/usr/local/include/libwebsockets.h:533:8: error: forward declaration of ‘struct lws_vhost’
 struct lws_vhost;
```

Is there any solution to this problem, thank you!

**Comment by lws-team** [comment]
> I want to connect multiple websocket servers in one process 

Okay....

> use lws_context_deprecate() to close an old connection 

That's not quite what that does, it is designed to manage the situation you changed your server configuration but don't want to disconnect existing users by stopping and restarting your server... instead you can use that to kill the listening sockets on the existing context, leave every accepted connection up so existing connections continue to be serviced, and reimplement the listening sockets on a new server process using the new config, that attracts any new connections.  When the old, deprecated server instance's count of clients eventually drops to 0, that deprecated process is terminated and only the new one is left running using the new config.

It sounds like you just want to create and destroy vhosts dynamically, for which there are apis.

> because I could not find a suitable interface, to get vhost->context and pass it into 

Hm... you have the context pointer from step 1.  You can just use that... the vhost object does keep a private copy of it but since you already have it... you don't need it.  The pointer returned from lws_create_context(), and the vhost->context pointer... are the same thing.  You shouldn't need to touch anything in lws_vhost other than a handful of provided apis for eg, recovering the vhost name or getting its user pointer.

**Comment by mhy12345** [comment]
I use `lws_client_connect_via_info(&client_info)` multiple times to create several connections.

I didn't find any apis or mini-examples shows how to close a single connection. 

`lws_context_destroy(struct lws_context *context);` destroy all connections, but I don't want to destroy all of them but the one.

**Comment by lws-team** [comment]
You can do it from the wsi if you have to

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-timeout-timer.h?h=master#n77-101

it depends on what you are doing, but often the realization you want to drop the stream is happening in the callback, you can, eg, return -1 from the rx callback to have it closed cleanly for you.  If your logic to close it is basically unrelated to callback activity, you can close it usually asynchronously with the api linked above.
