### ISSUE TITLE
Support the fuzzing server/client test for AutobahnTestSuite

### ISSUE THREAD

**Issue by JoakimSoderberg** [warmcat/libwebsockets#198]
It would be a good idea to create a test client/server that can pass the [AutobahnTestSuite](https://github.com/tavendo/AutobahnTestsuite): http://autobahn.ws/testsuite/#

http://autobahn.ws/testsuite/#reports

Example of a test report:
http://autobahn.websocketpp.org/clients/

Example of a client that runs this using my own (alpha) libws websocket lib:
https://github.com/JoakimSoderberg/libws/blob/master/test/autobahn/autobahntest.c

Example test client for WebSocket++:
https://github.com/zaphoyd/websocketpp/blob/master/examples/testee_client/testee_client.cpp

**Comment by lws-team** [comment]
After training in the mountains for a long while I finally got support for this implemented and documented in current HEAD.

https://github.com/warmcat/libwebsockets/blob/master/README.test-apps.md#autobahn-test-suite

We pass everything I expect we should

https://libwebsockets.org/reports/clients/index.html

The remaining failures are

 - 2.10 / 2.11 are spamming 10 PINGs without waiting for PONGs, we pass it sometimes because we happen to serve each PONG before we get the next PING.  But since on a single connection with only the two peer endpoints we never expect to get back to back queue of PINGs, this seems to not bring any value to support it.  Anyone think it's actually useful?

 - 6.* we don't check any UTF-8 as it is.  So we pass the ones that expect nothing special to happen and fail the rest.

 - 7.5.1 is actually a check for invalid UTF-8 in CLOSE, we don't check anything related to UTF-8

 - 12.* + 13.* claim compression "unimplemented" I didn't look at it yet.

**Comment by JoakimSoderberg** [comment]
Cool! The 2.10 one is not according to the spec as the comment says.

Regarding the UTF-8 one, I think that could be added quite easily, I've used this myself: http://bjoern.hoehrmann.de/utf-8/decoder/dfa/

https://github.com/JoakimSoderberg/libws/blob/master/src/libws_utf8.c

**Comment by lws-team** [comment]
That guy's scheme is good, but if we only need to validate it can be done in 6% of the table space (23 bytes vs 416) and only a tiny bit of code.

```
			static const unsigned char e0f4[] = {
				0xa0 | ((2 - 1) << 2) | 1, /* e0 */
				0x80 | ((4 - 1) << 2) | 1, /* e1 */
				0x80 | ((4 - 1) << 2) | 1, /* e2 */
				0x80 | ((4 - 1) << 2) | 1, /* e3 */
				0x80 | ((4 - 1) << 2) | 1, /* e4 */
				0x80 | ((4 - 1) << 2) | 1, /* e5 */
				0x80 | ((4 - 1) << 2) | 1, /* e6 */
				0x80 | ((4 - 1) << 2) | 1, /* e7 */
				0x80 | ((4 - 1) << 2) | 1, /* e8 */
				0x80 | ((4 - 1) << 2) | 1, /* e9 */
				0x80 | ((4 - 1) << 2) | 1, /* ea */
				0x80 | ((4 - 1) << 2) | 1, /* eb */
				0x80 | ((4 - 1) << 2) | 1, /* ec */
				0x80 | ((2 - 1) << 2) | 1, /* ed */
				0x80 | ((4 - 1) << 2) | 1, /* ee */
				0x80 | ((4 - 1) << 2) | 1, /* ef */
				0x90 | ((3 - 1) << 2) | 2, /* f0 */
				0x80 | ((4 - 1) << 2) | 2, /* f1 */
				0x80 | ((4 - 1) << 2) | 2, /* f2 */
				0x80 | ((4 - 1) << 2) | 2, /* f3 */
				0x80 | ((1 - 1) << 2) | 2, /* f4 */

				0,			   /* s0 */
				0x80 | ((4 - 1) << 2) | 0, /* s2 */
				0x80 | ((4 - 1) << 2) | 1, /* s3 */
			};

			if (!wsi->u.ws.utf8) {
				if (c >= 0x80) {
					if (c < 0xc2 || c > 0xf4)
						goto utf8_fail;
					if (c < 0xe0)
						wsi->u.ws.utf8 = 0x80 |
								 ((4 - 1) << 2);
					else
						wsi->u.ws.utf8 = e0f4[c - 0xe0];
				}
			} else {
				if (c < (wsi->u.ws.utf8 & 0xf0) ||
				    c >= (wsi->u.ws.utf8 & 0xf0) + 0x10 +
					 ((wsi->u.ws.utf8 << 2) & 0x30))
					goto utf8_fail;
				wsi->u.ws.utf8 = e0f4[21 + (wsi->u.ws.utf8 & 3)];
			}
```

With that we pass everything except the 2.10 / 2.11 we reject and "compression".

I think this is a new compression scheme that just recently got an RFC, we support different perframe deflate for now.  At any rate that's a different subject so I'll close this issue now.
