### ISSUE TITLE
CSP, 415

### ISSUE THREAD

**Issue by 8vasu** [warmcat/libwebsockets#1991]
Example used: minimal-ws-server-ring

Issues:

- Was unable to serve MathJax over http due to CSP.

- Was unable to serve a pdf over http; got 415 Unsupported Media Type. During the experiment, this actually happened with any file that was not a png, jpeg, html, or js; however, only pdfs are of interest at the moment.

I acknowledge that these are by design, and I have worked around them. However, I wish to know if there is a right workaround.

**Comment by lws-team** [comment]
CSP is voluntary, there's a shortcut very restrictive "best practices" version you can apply with a vhost option flag

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n181-196

if you need to customize it, you can turn that off and add your own headers, there's a .headers pvo linked-list you can set at context / vhost creation time for that

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n285

point it at a set of pvos with the headers like this

```
 static const struct lws_protocol_vhost_options pvo_hsbph[] = {{
	NULL, NULL,		"referrer-policy:", "no-referrer"
}, {
	&pvo_hsbph[0], NULL,	"x-xss-protection:", "1; mode=block"
}, {
	&pvo_hsbph[1], NULL,	"x-content-type-options:", "nosniff"
}, {
	&pvo_hsbph[2], NULL,	"content-security-policy:",
				"default-src 'self'; "
				"img-src https://www.gravatar.com 'self' data: ; "
				"script-src 'self'; "
				"font-src 'self'; "
				"style-src 'self'; "
				"connect-src 'self'; "
				"frame-ancestors 'self'; "
				"base-uri 'none'; "
				"form-action  'self';"
}};

...

	info.headers = &pvo_hsbph[3];
```

Similarly you can provide a linked-list of pvos listing additional mime types vs suffixes for each http_mount in its `.extra_mimetypes` member, eg

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-mimetypes/minimal-http-server-mimetypes.c#n22
https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-mimetypes/minimal-http-server-mimetypes.c#n36

**Comment by 8vasu** [comment]
That's perfect! Thank you so much!

Is there any way I can make a small donation to lws?

**Comment by lws-team** [comment]
Patches with fixes or new features are always welcome, although new features are best discussed first.

**Comment by 8vasu** [comment]
I was actually talking about a small $2-5 donation, but the opportunity to contribute code works as well!

**Comment by lws-team** [comment]
I understand your feeling, but there are people who will sell you an expensive license for proprietary libraries that do somewhat similar stuff to lws, you can put a dollar number on that I guess north of $100000 for each user who ships in any kind of volume.  I sincerely doubt the quality and maintenance of any proprietary solution is better than lws.  The cost of duplicating lws in proprietary code would far exceed those kind of numbers.  The lost opportunity cost of spending my time over the years on lws is a lot of money, I am a very experienced engineer in a number of different fields.

Leaving me a tip doesn't pay my rent or feed my family, but accepting it encourages the widespread delusion that because FOSS is free in dollar terms, the time of the people working on it must be worth nothing, or close to nothing.  I see this in action every time some low-level engineer with a deadline dumps his code here on a Friday evening and asks me to fix it for him, since my time is worth less than his... no.

So for those reasons lws has never accepted cash donations.  If you want to donate useful code or fixes instead, you're directly repaying the implicit moral debt of using FOSS in-kind, increasing the usefulness of the original work, and helping others.

**Comment by 8vasu** [comment]
I just want you to know that I love lws! Big fan. I am not aware of any commercial libraries [ do not care ], and of all the open source libraries that I tested, lws is hands down the most sophisticated one.

I am not an engineer; I am a math PhD student. I have been working on my hobby project for the past two months, and it is not a secret to anyone using lws that there are way too many of those code-fixing requests that you mentioned earlier; most of them are very painful to read. I also came across quite a few products by big tech companies that are lws-based. That is why I felt like I should donate in $s.

However, now I get what you mean. Code contribution >>> $ because this community thrives on code.
