### ISSUE TITLE
Terminated connection when accessing https://libwebsockets.org/testserver/ with non-browser client

### ISSUE THREAD

**Issue by mostroverkhov** [warmcat/libwebsockets#1993]
Hi

I am implementing websockets-over-http2 (rfc 8441) library with java/netty, and use https://libwebsockets.org/testserver/ to check its client part.

When accessing `dumb-increment-protocol` endpoint on https://libwebsockets.org/testserver/ , the connection gets terminated.
Client and server of the library can talk to each other, as well as firefox connecting library server part.

Server Http2 settings
```
HEADER_TABLE_SIZE=65536
ENABLE_PUSH=0
MAX_CONCURRENT_STREAMS=24 
INITIAL_WINDOW_SIZE=0 
MAX_HEADER_LIST_SIZE=4096
SETTINGS_ENABLE_CONNECT_PROTOCOL=1
```
Client Http2 settings
```
INITIAL_WINDOW_SIZE=100000
MAX_HEADER_LIST_SIZE=8192
```

Request (contains some custom headers to mimic firefox)
```
:method: CONNECT 
:protocol: websocket 
:scheme: https 
:authority: libwebsockets.org
:path: / 
sec-websocket-version: 13 
sec-websocket-extensions: permessage-deflate;client_max_window_bits 
sec-websocket-protocol: dumb-increment-protocol
user-agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0 accept: */*
accept-language: en-US,en;q=0.5
accept-encoding: gzip, deflate, br 
origin: https://libwebsockets.org 
pragma: no-cache
cache-control: no-cache
```

Any pointers are greatly appreciated.

**Comment by lws-team** [comment]
Rfc8441 is pretty rare so far but obviously it's a very useful piece of the puzzle.

It's worth looking for a GOAWAY from the server and see if any clue / string in there.  Lws rfc8441 works fine with chrome and firefox.

If not, hexdump the unencrypted data in both directions and look how far it gets.  Note there are common h2 servers or reverse proxies that get tx credit max limit off by one, exceeding the legal max, so pay attention to that.  Lws passes h2spec and some of those tests require us to fail various limit problems.

**Comment by mostroverkhov** [comment]
@lws-team Had a look into this recently - and libwebsockets closes connection with tcp rst as soon as `:protocol=websocket` pseudo-header is not last pseudo-header. I updated my client implementation so It writes `:protocol` after other pseudo-headers, and was able to handshake websockets successfully. Reading RFC7540 It seems the order of pseudo-headers should not matter as soon as they appear before regular headers, this peculiarity may be confusing for other implementors who will likely use https://libwebsockets.org/testserver/ to check their clients.

**Comment by lws-team** [comment]
> as soon as :protocol=websocket pseudo-header is not last pseudo-header.

AFAIK it should not care about the order... did you look at the GOAWAY?

**Comment by mostroverkhov** [comment]
I did not receive goaway before close.

**Comment by lws-team** [comment]
Dunno... I guess it's possible chrome and firefox both just happen to do RFC8441 :protocol as the last pseudoheader, but they work OK.  The other tests around pseudoheader correctness both send a GOAWAY, either "Pseudoheader checks", "Unknown pseudoheader" or "Duplicated pseudoheader".

Otherwise lws should not have a way to care about order, it parses out hpack completely and then look at what's there.

**Comment by lws-team** [comment]
I woke up in the middle of the night and realized what this is... in h2 it's required that pseudoheaders cannot appear after the first nonpseudoheader, and :protocol is not an RFC7540 pseudoheader.  So it works only as the last psuedoheader because of that, it's accounted for as a non-pseudoheader and the stream is dropped if another pseudoheader appears after it.

I pushed a patch on master adding :protocol to the list of pseudoheaders which should solve it, libwebsockets.org will update with it some time later.
