### ISSUE TITLE
[discussion] Should custom header names be case sensitive ?

### ISSUE THREAD

**Issue by BeatIdo** [warmcat/libwebsockets#2002]
Hi,
I realised that whenever I use capital letters in custom header names I cannot get them through lws_hdr_custom_length.

I use curl to send the request and check with wireshark capital letters are passed in the request.

`curl -H abc:1` would be OK with `lws_hdr_custom_length(wsi, "abc:", 4)`
but not `curl -H Abc:1` with  `lws_hdr_custom_length(wsi, "Abc:", 4)`

Is this expected behavior ?

**Comment by lws-team** [comment]
Is this actually "header names are converted to lower case"?  Ie, if in the second example you ask for `"abc:", 4`, is that working?

Because in http/2, headers are all lower case and upper case is forbidden.

https://tools.ietf.org/html/rfc7540#section-8.1.2

and given the scope for random case / confusion, the custom headers takes the same approach, forcing the names to lower case, I think you find.

**Comment by BeatIdo** [comment]
Indeed parsin for lower-case, i.e. "abc" insecond works. Makes sense with RFC indeed. 👍
Thanks for your explanations.
