### ISSUE TITLE
Can't compile libwebsockets with libev support when building static library

### ISSUE THREAD

**Issue by pavelxdd** [warmcat/libwebsockets#2033]
event lib plugins require linking with 
libwebsockets_shared.so, which is not created when building static library.

**Comment by lws-team** [comment]
Do event lib plugins make sense if you're building static?

If not you can probably work around it by also setting `-DLWS_WITH_EVLIB_PLUGINS=0` to get the old behaviour of built-in event lib support.

**Comment by pavelxdd** [comment]
Thanks, it was my mistake. 

I thought `LWS_WITH_EVLIB_PLUGINS` are mandatory for libev support now.

**Comment by lws-team** [comment]
No everything should build just like before if you set `-DLWS_WITH_EVLIB_PLUGINS=0`, there are a number of users with various complicated setups integrating lws to other things that may break or become even more complicated otherwise.  And EVLIB_PLUGINS=1 is only the new default on unix, where it makes sense for packaging reasons.

I will push a patch in a bit that helps it realize it has to defeat the evlib plugins if no LWS_WITH_SHARED available to avoid anyone else running into this.
