### ISSUE TITLE
"SSL_accept" failing in Libwebsocket running on QNX 6.5.0

### ISSUE THREAD

**Issue by SCRockz** [warmcat/libwebsockets#2034]
Hi,
I was trying to port the libwebsocket into QNX 6.5.0. After some modifications to the "CMakeList.txt" , the libwebsocket was building for QNX . The modifications  in the "CMakeList.txt" are due to"pthread" and "ldl" flag, in QNX both the libs are part of the "libc" and explicitly specifying those flags will throw error . I am sharing the modified "CamkeList" .
[CMakeLists.txt](https://github.com/warmcat/libwebsockets/files/5159585/CMakeLists.txt)

 After building the libwebsocket library , I was able to build and run the minimal WS server examples without using "-s" option in QNX platform , Whenever I used -s ( encrypted ) option  the server was not responding and browser was throwing "ERR_SSL_PROTOCOL_ERROR". On debugging I found that the SSL_accept( in the file "openssl-server.c") is failing. I tried some debug prints and found that ,  2 times the failure is happening , first with "SSL_ERROR_SSL"and second with "SSL_ERROR_SYSCALL" , surprisingly the error number(errno) was "0" in both occasions. I have used the same minimal example in linux(-s ,secure mode)  and its's working without any issue there  but  in QNX  its failing . I am using the " libwebsockets-v4.0-stable " version and  the openssl library version is "1.1.1g".  
It will be very helpful, If somebody can look it to the issue. 
Regards
SC

**Comment by lws-team** [comment]
> I am sharing the modified "CMakeLists.txt"

Thanks... it seems to be the v4.0-stable one... some of the changes seem to duplicate what should already happen via testing for "QNX" build target, like this

```
@@ -2444,7 +2442,7 @@
        if (UNIX AND LWS_WITH_PLUGINS)
                set(CMAKE_C_FLAGS "-fPIC ${CMAKE_C_FLAGS}")
                if(NOT((${CMAKE_SYSTEM_NAME} MATCHES "FreeBSD") OR (${CMAKE_SYSTEM_NAME} MATCHES "QNX")))
-                       target_link_libraries(websockets dl)
+                       #target_link_libraries(websockets dl)
                endif()
        endif()
```

It means on your build platform, `${CMAKE_SYSTEM_NAME}` is something other than "QNX"?  If you are building cross, you should `set(CMAKE_SYSTEM_NAME QNX)` in your cross toolchain file, so that cmake and lws CMakeLists.txt can understand what is going on.  I think if you do that, most or all of your CMakeLists.txt changes won't be needed, eg, test for if (UNIX) won't wrongly match any more, even though your build machine native platform may be UNIX.  Can you try it?

> SSL_ERROR... errno 0
> It will be very helpful, If somebody can look it to the issue.

QNX is proprietary, although I can get 6.0 from their site for a "30 day evaluation" I can't download 6.5 even if I wanted to look at it.  So it can't become a supported CI platform, I can't "look at it" etc.  And I feel I don't want to spend my day working on some proprietary thing I will never license or use.

Different platforms and ip stacks + libc behave differently, _SYSCALL is openssl's way of passing that back up to the caller saying, "something happened but you need to figure it out".  I would guess you can check if it's QNX platform, check errno 0 (at least, on ssl_accept), and then just treat it as either _WANT_READ or success.

**Comment by SCRockz** [comment]
Thanks for the quick replay, 
I was trying with the build option "set(CMAKE_SYSTEM_NAME QNX) " from the beginning , I was always  getting the error mentioned in the earlier message.  I have made clean "CMakeList.txt " for QNX, sharing along with the reply.
[CMakeLists.txt](https://github.com/warmcat/libwebsockets/files/5164941/CMakeLists.txt)

Regarding the "SSL_accept" error. I have ignored the error and allowed execution to continue. On enabling the debug prints, lws server is displaying the connection to client success message, however the remote browser is throwing “ERR_SSL_PROTOCOL_ERROR" error.  Ultimately ignoring the “SSl_accept “error is not working for me. 
I have the following doubts 
1. Is the arguments to the "SSL_accept" API  is the issue?
2. Is it because of the structure padding/structure member size difference in linux /QNX is causing the issue?
3. Is there any alternate way/approach  to debug and find the issue?
Any pointers will be helpful. 

Note:
 1.Since QNX is proprietary and licensed OS, I completely understand the limitations from your side. 
 2.The "SSl_accept" is throwing SSL_ERROR_SSL"and "SSL_ERROR_SYSCALL" errors. 

Regards
SC

**Comment by lws-team** [comment]
Thanks, I'll look at the updated modifications in the morning.

> Is it because of the structure padding/structure member size difference in linux /QNX is causing the issue?

Where did your openssl lib come from?  Presumably you also cross-built it using the samr qnx / sdk toolchain.  There should not be any 'linux' toolchain-built code seen by qnx so it could differ, right?

Openssl is pretty portable in the end it's presumably just another generic armv7 or whatever cross toolchain build.

What can go wrong with cross is accidentally build using cross build machine native headers, eg, /usr/include/openssl/ from the build machine.  But if you have the same stuff as in contrib/cross-linkit.cmake you should be able to make those kind of accidents impossible.

> Is there any alternate way/approach to debug and find the issue?

What I'd do is build lws master branch with -DCMAKE_BUILD_TYPE=DEBUG and set the logging mask to eg 1039 or 1151 to get verbose logs.  Master will log the openssl error stack then

https://libwebsockets.org/git/libwebsockets/tree/lib/tls/openssl/openssl-server.c#n652

**Comment by SCRockz** [comment]
Thanks for the follow up.

I have changed debug level and got complete log. On quick look,I can see some errors, posting them below .
 " SNI: Unknown ServerName
    openssl error: error:02015016:system library:ioctl:Invalid argument
    openssl error: error:1427D044:SSL routines:construct_stateless_ticket:internal error
"
The openssl error is throwing from " lws_tls_err_describe_clear(); "  function after the "SSL_accept".  
PFA Complete Debug log.
[linwebsocket_server_debug.log](https://github.com/warmcat/libwebsockets/files/5165431/linwebsocket_server_debug.log)

Is it indicating that the arguments to the "SSL_accept "is having some issue?

It will be great , if you can look to the debug logs and give some pointers.
 
Regards
SC

**Comment by lws-team** [comment]
This doesn't sound anything to do with lws... are you using ENGINE crypto acceleration?  You may have eg, forgotten to init the hw.

Otherwise you need to debug by following the trail in openssl.  As you saw on linux, lws knows how to work openssl just fine.  This 'internal error' seems entirely a platform or build issue.

**Comment by lws-team** [comment]
Looking into openssl `ssl/statem/statem_srvr.c` where `construct_stateless_ticket()` lives 

https://github.com/openssl/openssl/blob/master/ssl/statem/statem_srvr.c#L3900

there are several ways to exit with the error you're seeing... eg OOM during HMAC sequence but also if `RAND_bytes()` fails...  I would stick printfs in there and track down exactly where it exits and why to get a clue.

But this seems like platform build or integration issue for openssl not related to lws.

**Comment by lws-team** [comment]
If there's something for lws to do please continue this issue, but it seems to be a problem on OpenSSL build side.
