### ISSUE TITLE
websocket client receive "invalid frame header"

### ISSUE THREAD

**Issue by zhang852774731** [warmcat/libwebsockets#2038]
libwebsockets version: 4.0
config code:
```
        struct lws_context_creation_info info;
	struct lws_context* context;

	struct lws_protocols protocols[] = {
		{
		"preview",
		ws_service_callback,
		sizeof(struct per_session_data),
		0
		},
		{NULL,NULL,0,0}
	};
	signal(SIGINT, sigint_handler);
	memset(&info, 0, sizeof info);
	info.port = 8000;
	info.iface = NULL;
	info.protocols = protocols;
	info.pt_serv_buf_size = 1024*1024*7;
	info.extensions = NULL;
	info.ssl_cert_filepath = NULL;
	info.ssl_private_key_filepath = NULL;
	info.gid = -1;
	info.uid = -1;
	info.options = 0;
```
websocket server send 100K (more or less) data every time，but the frequency of sending data is very fast. the websocket client will receive data normally for a while, and then closed by "invalid frame header"!

**Comment by lws-team** [comment]
So how can I see one of the minimal examples act like that?  You're following the ways they do things, like only call lws_write() from WRITEABLE one time each, only ask to write something that the OS will accept in one go (typ 2 mtu for linux), lws_callback_on_writable() every time...

**Comment by zhang852774731** [comment]
you means I need to call lws_callback_on_writable every time before i call lws_write. the invocation of lws_write should be written in "LWS_CALLBACK_SERVER_WRITEABLE" callback function. the data which to be send should be store in lws_ring?

**Comment by lws-team** [comment]
Yes you must ask for the writeable callback every time there is something to write.  Depending on the network conditions, you may get it immediately or some time later.  And you can only use lws_write() from inside the WRITEABLE callback.  This way, your production of data is regulated by the network conditions and rate that the peer is receiving it.

If you produce the data, it's better to not store it at all, but produce the next block each time in WRITEABLE callback just when it is needed.  If you can't control when the data is produced, or receive the data from somewhere and are forwarding it, yes you need some kind of ringbuffer to hold data while you cannot yet write it (because the peer may not be receiving it that quickly).
