### ISSUE TITLE
libwebsocket not report LWS_CALLBACK_WSI_DESTROY when network disconnected on iOS platform

### ISSUE THREAD

**Issue by lixiaotur** [warmcat/libwebsockets#2041]
when libwebsocket client was running on iOS platform, i disconnected the iOS device network but no LWS_CALLBACK_WSI_DESTROY event is reported and still reported LWS_CALLBACK_CLIENT_WRITEABLE?
I have no idea what's wrong. Maybe I had set some config params with wrong values.
Could someone give me some guide or help? Thanks in advance!

**Comment by lws-team** [comment]
> disconnected the iOS device network

That does not close all open connections that may have been routing over that network interface.

**Comment by lixiaotur** [comment]
Thanks for your quick reply.
If the connections can not be closed on iOS device when network is disconnected, so I can't use libwebsocket to tell if the Internet is down or not, am i right? when the network is down, libwebsocket has nothing to do on iOS device?
By the way, the same case running on Windows platform, libwebsocket will report LWS_CALLBACK_WSI_DESTROY immediately  when the network is disconnected.

**Comment by lixiaotur** [comment]
libwebsocket running is MacOS device has the same behavior with it runs on iOS devices

**Comment by lws-team** [comment]
Lws is a userland app that uses posix sockets apis to do its thing.

What each platform does with its network stack for things not defined in posix is up to them.

You seem to be confusing "the network" and one network interface up or down though.  If you turn off wifi, lo (127.0.0.0/8) is still up, right?  Should lws kill everything on every network interface because you turn off wifi?

**Comment by lixiaotur** [comment]
i see, thanks so much for your detailed explanation.
