### ISSUE TITLE
libwebsockets not linking against libdl

### ISSUE THREAD

**Issue by neheb** [warmcat/libwebsockets#2058]
Certain configurations of glibc need -ldl to LDFLAGS to be passed. First noticed here: https://github.com/openwrt/packages/pull/12222

I don't see any find_library calls to dl.

**Comment by lws-team** [comment]
For lws own use of dl, for plugins, he adds it to the dependent libs for lws library link-time.

How are you thinking we should determine if we should always link against dl because the libc wants it?

**Comment by neheb** [comment]
I would guess to do so unconditionally. I don't know how other projects do it.

**Comment by neheb** [comment]
Or this: https://cmake.org/cmake/help/latest/variable/CMAKE_DL_LIBS.html

**Comment by lws-team** [comment]
> edit: hmmmmm..... https://github.com/warmcat/libwebsockets/blob/master/CMakeLists.txt#L543

Yes as I said if lws is using plugins itself and needs libl, it will link with it.

I can't just add -ldl because it's perfectly possible to build for, eg, cross freertos and no libdl concept.

I didn't understand what the openwrt error is about either, it seems to be for another package that brings in libwebsockets... so - I am asking rather than trying to dodge it - why is it a lws issue?

**Comment by neheb** [comment]
The original report seems to be wrong. Closing.
