### ISSUE TITLE
how to not use lws_service to keep the callbackfun receive message

### ISSUE THREAD

**Issue by JCYAO-gz** [warmcat/libwebsockets#2065]
in all minimal-examples ,lws_service is used as :
```
	while (n >= 0 && !interrupted)
		n = lws_service(context, 0);

```
but my program not alow  repeat without sleep，it will affect  other module work。so my code is:
```
	while (1)
	{ 
		lws_service(context, 0);
		usleep(50000);
	}

```
but it will afect the perfaormance of sending data。
how can I not run lws_service by myself，and callback message can receive immediately

**Comment by lws-team** [comment]
> it will affect other module work

Why is that?  Because it does other work in the same thread or some other thread?

I think your problem is something to do with the answer to that.  Because lws_service() will sleep for a long time if there are no network or scheduled events.  If he is 99% asleep, but has to do two things in succession around the loop, it should make no effect on work in another thread, unless you have locking or other problems around the work.

**Comment by JCYAO-gz** [comment]
"if there are no network or scheduled events. If he is 99% asleep,"
however lws_service is not block，even if no network or scheduled events， the while{} is always loop。

**Comment by lws-team** [comment]
>  the while{} is always loop

Please try eg, the minimal-http-server example on Linux, and put logging in the loop.  He may wake eg, once a second.  But he is otherwise blocked.

**Comment by JCYAO-gz** [comment]
ok ,Thank you very much。I try lws-minimal-http-client,it is about once a second  when network is free.
so i can remove sleep from my code.
Thanks again!
