### ISSUE TITLE
lws ping pong questions

### ISSUE THREAD

**Issue by Ripple-qin** [warmcat/libwebsockets#2078]
Sorry to disturb you agian  and sorry to ask the question through issue.

I would like to ask about the usage of the two parameters of secs_since_valid_ping and sec_since_valid_hangup. 
In the demo of lws, secs_since_valid_ping=3 and secs_since_valid_hangup = 10 are set, 
which means whether to send a ping request every 3 seconds and wait for the server the longest response time is 10-3 = 7 (or should be 10?) seconds?

eg：
Precondition ----- secs_since_valid_ping=3 and secs_since_valid_hangup = 10

---------------------------------------------------------------------------
- 2020-10-09 17:11:00  （client send ping）
- 2020-10-09 17:11:08  （client receive pong，is this a timeout situation?）
---------------------------------------------------------------------------
- 2020-10-09 17:11:00  （client send ping）
- 2020-10-09 17:11:11   （client receive pong，is this a timeout situation?）
---------------------------------------------------------------------------

If I change my test code to secs_since_valid_ping=3, secs_since_valid_hangup = 3, the lws connection will directly return a close message. 

Currently I want to use this feature to detect network abnormalities。

Thanks in advance for your answers。

**Comment by lws-team** [comment]
The example is using 3 and 10 so the we can easily test the ping / pong is happening.  It's not a recommendation, you'd normally want to balance you long you can cope with a dead connection vs the extra bandwidth if the connection is idle for a long time.

`_ping` says how long to wait since last time we were told the connection is valid before issuing our own PING to probe the connection.  In the example, 3s since last validity confirmation.

`_hangup` says how long to wait since last time we were told the connection is valid before hanging up the connection.  Receiving a PONG tells us the connection is valid.  In the example, we wait 10 - 3 == 7s for the PONG to come before hanging up.

Setting `_ping` the same as `_hangup` is pointless, there is no time for the PONG to come back and you will hangup.

You can tell lws the connection is valid yourself, if you see it passing data in both directions, so it does not have to issue PINGs while it's otherwise working.  See 

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-timeout-timer.h#n329-349

On master, for linux-based systems, it now has netlink support that can detect losing an interface, or gateway route on ipv4 or ipv6 and hang up affected connections immediately.

**Comment by Ripple-qin** [comment]
Thank you very much for your answer，you are so nice. I will try it.

**Comment by Ripple-qin** [comment]
Sorry to disturb you again, I tried the retry solution, but after a few minutes, lws will return an error
```
static const lws_retry_bo_t retry = {
    .secs_since_valid_ping = 3,
    .secs_since_valid_hangup = 8,
};

connectInfo->retry_and_idle_policy = &retry;
```
A few minutes later，receive the close state code of 75.

Post part of the log
```
EXTENSION: lws_ws_client_rx_sm:    This RX frame Final 1
INFO: lws_ws_client_rx_sm: client 0x6180000abc80 received pong
INFO: _lws_validity_confirmed_role: wsi 0x6180000abc80: setting validity timer 3s (hup 0)
EXTENSION: lws_ws_client_rx_sm: +++ passing 0 0x631000140810 to ext
EXTENSION: Ext RX returned 0
EXTENSION: lws_ws_client_rx_sm: post inflate ebuf in len 0 / out len 0
EXTENSION: lws_ws_client_rx_sm: removing from draining ext list
INFO: Client doing pong callback
Running time start is: 4800ms
WebSocketWrapper (0x6130000d0280) Unhandled websocket event: 9
INFO: lws_validity_cb: wsi 0x6180000abc80: scheduling validity check
INFO: rops_handle_POLLOUT_ws: issuing ping on wsi 0x6180000abc80: ws  h2: 0
INFO: lws_issue_raw: ssl_capable_write (6) says 6
INFO: lws_validity_cb: wsi 0x6180000abc80: validity too old
INFO: __lws_close_free_wsi: 0x6180000abc80: caller: validity timeout
Running time start is: 5401.52ms
WebSocketWrapper (0x6130000d0280) Unhandled websocket event: 75
onConnectionClosed, WebSocketWrapper (0x6130000d0280) is closing by server.
WebSocketWrapper (0x6130000d0280) onConnectionClosed DONE!
```

This bug can be reproduced 100%, is there a problem with my usage?
