### ISSUE TITLE
[v4] can not disable ws ping-pong

### ISSUE THREAD

**Issue by atoppi** [warmcat/libwebsockets#2090]
Hi,
we use lws in Janus as ws server and one of our users noted that since lws v4 the ping-pong mechanism is on by default.
This is expected since in the changelog is mentioned that:
```
- NEW: Connection validity tracking, autoproduce PING/PONG for protocols that support it
if not informed that the connection has passed data in both directions recently enough
```

However this revealed to be an issue in case of **clients not supporting ws ping/pong** for two reasons:
1) AFAIU it's impossibile to disable the mechanism. Not setting any value in `retry_and_idle_policy` will make lws fall back to default values (`300` seconds). So we're not able to just disable the ping/pong from lws user code in Janus. We can at most post pone it at the max field value.
2) lws seems to ignore the fact that an application level keep-alive is being used. It is mentioned in the docs that
```
"Connection validity" is proven when one side sends something and later receives a response 
that can only have been generated by the peer receiving what was just sent. This can happen 
for some kinds of user transactions on any stream usingthe connection, or by sending PING / PONG 
protocol packets where the PONG is only returned for a received PING.
```
so maybe generic application-level traffic is not considered as a valid "user transaction" to reset the timer.

As a consequence, user connections are being torn down after 5 minutes because of the (not true) inactivity.

So the questions are:
- is there any way to disable the ping/pong through user code or configuration?
- should lws reset its validity timer when generic user traffic is being sent ?

**Comment by lws-team** [comment]
> in case of clients not supporting ws ping/pong

These clients are broken then, since PING/PONG is literally a MUST in RFC6455

https://tools.ietf.org/html/rfc6455#section-5.5.2

> so maybe generic application-level traffic is not considered as a valid "user transaction" to reset the timer.

The issue is that there may appear to be traffic in both directions from lws perspective, but actually the outgoing route has failed and for a long time (maybe 15 minutes or whatever) the kernel will accept small outgoing data from lws and let it pile up kernelside, from userland side this looks like the write syscall went through OK.  The rx traffic may be real but does not indicate that the "conection is valid", just that depending on the user protocol, it can still receive things.  What you want in this situation is to fail the connection ASAP.

User code can call `lws_validity_confirmed(wsi)` when it sees something that means the connection is almost certainly working both ways and is valid, for example transmit a message with a random cookie or ordinal and see it come back from the peer in rx.  You can couple that with setting the `secs_since_valid_hangup` and `secs_since_valid_ping` to 0xffff (65K secs == 18 hours) if you have broken clients that don't know what the mandatory PING/PONG is.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n728-731
