### ISSUE TITLE
html include other source 

### ISSUE THREAD

**Issue by asd617140123** [warmcat/libwebsockets#2099]
Hi 
    I want to use a js library,
so I need add below code in my index.html
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

but I can watch some error on my browser.
![螢幕擷取畫面 2020-10-22 142013](https://user-images.githubusercontent.com/18673071/96832710-c5f59c80-1471-11eb-8aee-d3c73d8084bc.png)

**Comment by lws-team** [comment]
This is a feature, not a bug.  You can read about Content Security Policy, eg, here

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

In the examples, they all have a vhost flag `LWS_SERVER_OPTION_HTTP_HEADERS_SECURITY_BEST_PRACTICES_ENFORCE` that causes lws to issue strict CSP headers that forbids bringing in scripts or css from other servers... this is very powerful defence because it means even if attackers manage to inject html or DOM into the page, they can't build on that attack to run external scripts and attack the user.

You can remove the related flag, so you or an attacker can run arbitrary scripts from third parties, but you should at least read the flag docs for other options first

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n181-196
