### ISSUE TITLE
Can LWS work on μC/OS-II RTOS

### ISSUE THREAD

**Issue by chrimsonite** [warmcat/libwebsockets#2101]
Hi, our team is currently evaluating an embedded device running on μC/OS-II RTOS (https://www.micrium.com/rtos/). Our other devices which runs on Linux are using libwebsockets for communicating with our websocket based backend service. So, we wanted to verify if the device can be communicated with the same backend service.

Given the fact that LWS has been ported to FreeRTOS, we were curious if it can also be ported to other RTOS like μC/OS-II. 

Kindly, advise us regarding, if such a port can be done (i.e. if this OS provides all the features required by LWS) and if yes, what level of effort will be required for accomplishing the task of porting it. 

Clarification of above mentioned points will greatly help to us, in the evaluation process of the device.

Thank You

**Comment by lws-team** [comment]
Probably... it has its own tcp/ip stack instead of lwip, but that should make limited trouble since POSIX/BSD sockets are designed for portability.  You will need to check they have a working select() or poll() with high resolution timeout (preferably us resolution), I can't find their code to look at.

The biggest potential issue will be they apparently also rolled their own tls stack.  You'd want replace it with mbedtls which is directly supported by lws.

Otherwise the approach would be cut and paste ./lib/plat/freertos directory and ./include/libwebsockets/lws-freertos.h named ./lib/plat/ucrtos or whatever, and copy the corresponding cmake bits that are interested in _FREERTOS to do the same thing for this.

There are some other annoyances immediately apparent, it says it's apache-licensed but no simple link to sources, the site is set up to sell you a product.  Examples are only set up to use proprietary toolchains

https://www.micrium.com/downloadcenter/download-results/?searchterm=ft-book-project&supported=true

It's like they realized their proprietary rtos is not competitive against FOSS and relicensed it, from FOSS perspective it looks halfhearted; if you were ready to pay $$$ for it anyway then I guess you don't mind paying for IAR.  But they have not really adapted their business model

```
Using Micrium Projects
Example projects are intended for evaluation use only. Developers seeking to use Micrium products commercially must contact Micrium sales to obtain the proper license(s).
```

https://www.micrium.com/downloadcenter/download-results/?searchterm=ft-book-project&supported=true

```
The latest step in the evolution of the µC/ software family represents not a technical improvement but a licensing change. The µC/ components are now offered under a permissive, open-source license model. Under this new model, developers seeking to use the components for commercial purposes will no longer need to purchase a license— the software will be available at no cost.
```

https://www.micrium.com/rtos/licensing/

If you want any questions answered porting it you'll need to clarify their license grant with them and provide a link where I can download apache licensed sources.

**Comment by lws-team** [comment]
Not sure what the relationship with Silabs is but they have pushed Apache-licensed pieces to github

https://github.com/SiliconLabs/uC-OS2
https://github.com/SiliconLabs/uC-TCP-IP

**Comment by lws-team** [comment]
Feel free to continue here but closing this since nothing for me to do.
