### ISSUE TITLE
mqtt client

### ISSUE THREAD

**Issue by qq1033731787** [warmcat/libwebsockets#2110]
hi,
There are some questions about libwebsocket in mqtt.
In the mqtt example, when we publish a message with qos = 1, it will call the LWS_CALLBACK_MQTT_RESEND if we don't reveive the puback in 3s. But the message doesn't resend in real action. If i should resend the message by myself when call the LWS_CALLBACK_MQTT_RESEND ?

Thank you.

**Comment by lws-team** [comment]
Yes lws approach is to leave it to user code to either regenerate or stash and bring out the message again.  Depending on what you're doing and your platform, which can be a microcontroller, you may not have heap to always keep a copy of any pending qos >= 1 message, especially since multiple messages may be pending acks at once.  Messages may be quite large and the content may already / still exist in ringbuffers or storage, or be simple to recreate otherwise, meaning heap is not required to recreate it.

Server isn't supported atm.

**Comment by qq1033731787** [comment]
Well，it seems like lws save the pkt_id and state unacked_publish to judge which message has received its own ack, so in the lws, it is clear which message has to resend and which message is sent successful. But when i receive a LWS_CALLBACK_MQTT_ACK or LWS_CALLBACK_MQTT_RESEND in qos=1 when publish, how can i know which message it is responsing? If some message saving in  _wsi_ or _user_  in minimal-mqtt-client.c 159 line, so we can get the pkt_id to manage the copy message in local or directlt get the previous lws_mqtt_publish_param_t or message in _wsi_ or _user_?

I try
`lws_mqtt_publish_param_t *pub_ack = (lws_mqtt_publish_param_t *)in;`
but it is not successful.

**Comment by lws-team** [comment]
Unlike the rest of lws roles I didn't write this one, it was contributed.

It looks like it takes the approach that there can only be a single qos >=1 message in flight per wsi, so MQTT_RESEND in a wsi context implies it needs to resend the last thing it tried to send.

**Comment by qq1033731787** [comment]
Yes，but how can i do when i try to process more than one messages？It is inevitable that i have to get the ack_pck_id or something else which can let me know which message i should resend now. Can lws help it? Or should i analysis puback message by myself?

**Comment by lws-team** [comment]
As it is, you can process more than one message just fine, but only sequentially, ie with one in flight at a time.

Lws is FOSS, there's the option to help improve it if there's something that should be better.

The problem seems to start that at the moment, the qos1 timeout is done with one sul `sul_qos1_puback_wait` in the wsi's `struct _lws_mqtt_related`, it makes a situation there's only one qos timeout per wsi, similarly `pkt_id` is in there one time per wsi as well.  

It looks like those members need to come out into a small "in flight" struct and use lws_dll2 to allow a linked-list of those to bind to the `struct _lws_mqtt_related` instead.  You'll need to take care about freeing that list on mqtt role wsi close handling.  And you'll need to put a struct lws * to the wsi in the "in flight" struct so the sul timeout callback can understand which one fired and get the associated wsi.

Does it make sense and sound feasible?

**Comment by qq1033731787** [comment]
Thanks a lot and i will try it.

**Comment by qq1033731787** [comment]
In lib/roles/mqtt/mqtt.c line 1080
> 			case LMQCP_PUBACK:
				lwsl_info("%s: cmd_completion: PUBACK\n",
						__func__);

				/*
				 * Figure out which child asked for this
				 */

				n = 0;
				lws_start_foreach_ll(struct lws *, w,
						      wsi->mux.child_list) {
					if (w->mqtt->unacked_publish &&
					    w->mqtt->ack_pkt_id == par->cpkt_id) {
hi，as the discussion yesterday， I found there is a linklist in a wsi. If lws  has saved the waiting_pkt_id in wsi->mux.child_list ?

**Comment by lws-team** [comment]
These are different things... in lws, MQTT maps on to the connection multiplexing support also shared with http/2... although MQTT doesn't have explicit connection multiplexing like h2, in fact if two different mqtt client connections are created to the same endpoint, they can be handled with one connection + tls tunnel, and lws will take care of that transparently.

The mqtt client implementation keeps track of which mux child subscribed to what and passes the incoming messages through to the right children; underneath, all the subscriptions are made on one connection.  The "mux.child_list" list you found is tracking children bound to and sharing the same underlying tcp + tls connection.

It doesn't change the actual problem, each wsi using the connection including the original, as it stands can only have a single message in-flight, ie, in the code you pasted above `w->mqtt->ack_pkt_id` can only understand a single pending ID for that wsi.  What we have been discussing is moving that out into its own linked-list of pending ack objects, as part of that the code you pasted above would change so inside the linked-list loop that exists at the moment, for each wsi it also walks this new linked-list of pending ackable messages.

**Comment by qq1033731787** [comment]
Got it . Thanks for your reply ~

**Comment by qq1033731787** [comment]
Well, if lws has some interfaces to assign _dup_ and _pkt_id_ in mqtt message because mqtt_resend_message should set the same _pkt_id_ of the previous publish message and set _dup=1_ .
