### ISSUE TITLE
lws_set_log_level / context

### ISSUE THREAD

**Issue by dev31337** [warmcat/libwebsockets#2123]
Hi,

lws_set_log_level() sets the logging function for the whole libwesockets.

It does not seem possible to set it per context (lws_context_creation_info), is it ?

If not, is it possible to completely disable logging for a specific context ?

Regards.

**Comment by lws-team** [comment]
Generally code using lws only has one context, there's no point passing the context in every log call and bloating the code.  And it wants to log during context creation and during creating and destruction too, which would make trouble.

Having two contexts / event loops is usually worse than just having one, as well.

So as it is, logs don't go through a context.  If the other context is in another process, you can set its logging mask separately.  Or if you cpuld static-link a separate build of lws without exports, eg, link a sub-lib against that, you can disable logging on that build.

**Comment by dev31337** [comment]
I understand, personally I have more than one context, because for the same application one context is a HTTP(S)/WS server and the other context is a HTTP/HTTPS client.

The idea was to use libwesockets for HTTP(S) requests (instead of using libcurl) since it's already there for the web server part.

My goal was just to disable the logging for the HTTP(S) client requests while leaving it for the server.

But I will try to find another way :)

**Comment by thefallentree** [comment]
i second this request:  in my application I also need to dynamically create/destroy  lws context,  but they can of course share an single event loop (through socket_adpot())  making this easier will be good

**Comment by lws-team** [comment]
I am not sure if some things are getting mixed together a bit... lws logging apis, used throughout lws itself, don't take the context as an argument.  There are a lot of these and the bloat of building with the context added to each as a C function arg will be very noticeable on, eg, the RTOS case, where there are guys waiting to complain about even +100 bytes of .text; this would be several KB.  And for every example in lws, which do a lot of things, they all only need one context and work fine with the logging as it is.

I can imagine adding the context arg and then using preprocessor magic to use the process scope log filter by default and snip the context arg back out again at buildtime, and modify every single existing log to come up with a context pointer even when none is currently available, keeping the non-context version for before and after context exists... it's surely doable, but it is a lot of work that doesn't buy anyone anything in the recommended, typical case of one context.

I think before that, we should look harder about why multiple contexts... 

>  for the same application one context is a HTTP(S)/WS server and the other context is a HTTP/HTTPS client.

There's no problem in lws mixing http/s client and server wsi in the same context and even the same vhost.  It might be they are in different threads or something in which case they would have to exist in the one context / thread / event loop to unify them, which may or may not make trouble.

>  in my application I also need to dynamically create/destroy lws context,

There is no problem doing this, you can see the -foreign minimal examples which act out creating a native, eg, libuv event loop, letting it run, creating the lws_context on this "foreign" loop, letting that run, destroying the context, and letting it run alone for a bit before exiting.  You can just bring up the lws_context when it's useful to have it on the loop and don't need it when not.  But you don't need two contexts then and I don't really understand what the log mask coming from the context is doing for you.

Multiple context in one process are also definitely a  bloat problem, the contexts contain things like fd tables for every possible fd the posix apis may return.

**Comment by dev31337** [comment]
Just to be sure, do you see any potential issue in having multiple threads running libwebsockets with in each thread its own context/loop ?

**Comment by lws-team** [comment]
No it should largely work OK, since almost everything is dereferenced through the lws_context.

Some things are inherently process-wide though... for example, library / plugin binding into the process... you can work around it by statically linking the event lib support in and not using protocol plugins.  Older openssl blew up if initialized multiple times inside the same process, but recent openssl does reference counting and works OK with it.  I think mbedtls is OK but didn't try it for this.

With two contexts, if the connections will interact at all, you have to add locking on any shared data and use lws_cancel_service() to alert the other context there's something to do.  With one context and loop, you can always be sure nothing is changing behind your back, since the (only) thread is doing whatever you have it doing and cannot be doing anything else concurrently.  With this any interactions must be protected and carefully considered what the other loop could be doing.

You double the pt / fds table allocations and the pt_serv_buf allocation, on a linux class machine with a low ulimit -n you may not care but on an rtos class machine, this is already a good reason to prefer a single context.

**Comment by dev31337** [comment]
Thank you for the clarification.
