### ISSUE TITLE
lws_write performance

### ISSUE THREAD

**Issue by ktb92677** [warmcat/libwebsockets#2135]
I am sure this has been addressed somewhere but searching the questions already posted has not yielded me any good results... so apologies if I am being redundant.

I am creating a sort of live streaming service and I wanted to use libwebsockets as a base to transmit image data to a web client. I am noticing some significant latency and I have tracked it down to libwebsockets.

Some info on the bandwidth: frames are transmitted from the server to the client at 60 FPS. Each frame ranges from 1000 bytes to 4000 bytes depending on how well the visual data is able to be compressed. Usually for every frame that the encoder is able to produce there is one subsequent flag triggered on "LWS_CALLBACK_SERVER_WRITEABLE". However every once in a while (maybe once after a few hundred frames) the encoder produces two frames in the time "LWS_CALLBACK_SERVER_WRITEABLE" is triggered once. I only have one "lws_write" per "LWS_CALLBACK_SERVER_WRITEABLE" so if it misses one it doesn't ever seem to be able to catch up. So as time progresses the latency gets worse and worse and worse.

I can confirm that I am calling "lws_callback_on_writable_all_protocol" every time after my encoder produces a frame. Is there anything else I should watch out for? Is there anything I could be doing wrong here? My code base mocks pretty closely the code written here: https://medium.com/@martin.sikora/libwebsockets-simple-websocket-server-68195343d64b (except obviously "lws_callback_on_writable_all_protocol" is called in a different thread).

**Comment by lws-team** [comment]
There's no such api feature that if you ask for writeable n times you will get n WRITEABLE callbacks.

You will get one callback as soon as possible.

> am noticing some significant latency and I have tracked it down to libwebsockets.

You're tracked it down to your user code using lws...

> the encoder produces two frames in the time "LWS_CALLBACK_SERVER_WRITEABLE" is triggered once. I only have one "lws_write" per "LWS_CALLBACK_SERVER_WRITEABLE

The issue is not lws but your expectation about what happens if you ask for writeable isn't related to what event loops do... it boils down to enabling a bit for POLLOUT next time in the event loop.  If that bit is already set indicating you already asked for writeable, asking again is a NOP.

The usual approach, found in the examples, is figure out what you need to do when the happy momet comes you could write something.  And if at the end of the WRITEABLE callback you find there is still more to do, eg, already a second frame already pending, it's fine to ask for the next writeable callback right there before leaving.

**Comment by ktb92677** [comment]
so during one "LWS_CALLBACK_SERVER_WRITEABLE" can I call lws_write multiple times? Is there anything I can do to make "LWS_CALLBACK_SERVER_WRITEABLE" available quicker? Is the sheer amount of data I am sending out a problem at all?

**Comment by lws-team** [comment]
> so during one "LWS_CALLBACK_SERVER_WRITEABLE" can I call lws_write multiple times?

No, what I said is

>> And if at the end of the WRITEABLE callback you find there is still more to do, eg, already a second frame already pending, it's fine to ask for the next writeable callback right there before leaving.

On an otherwise idle system with sufficient bandwidth to the peer, you'll typically come back the next time around the event loop, which is something like 250us latency.

>  Is the sheer amount of data I am sending out a problem at all?

What are you actually asking?  You seem to have a specific behaviour caused by not issuing more writeable requests outside the 60Hz when already more to write, you can fix that in a few seconds.

**Comment by ktb92677** [comment]
*facepalm* literally adding "lws_callback_on_writable_all_protocol" to my "LWS_CALLBACK_SERVER_WRITEABLE" if there is more data waiting fixed the issue. Everything is perfect now. Thank you for the quick responses.

**Comment by lws-team** [comment]
No worries...
