### ISSUE TITLE
Receiving Payload in fragments in lws_callback

### ISSUE THREAD

**Issue by aish84** [warmcat/libwebsockets#2137]
Dear Developers,

Recently I am moving from Ubuntu 16.x to Ubuntu 20.x with my websocket server which was originally working with Ubuntu16 + libwebsocket 1.7.0.
Now on Ubuntu 20.x the libwebsocket version is 3.2.0. The issue I am facing is that when the client send a large byte packet (28000bytes), on server lws callback I receive the payload in fragments. Same size payload was received as a full single frame in libws1.7.0. 

As an application, I am expecting that the library should to the assembly and give me the entier 28k bytes payload. 

Is there any configuration needed to be done to receive a single frame?
======
static struct lws_protocols protocols[] = {
 {
    "lws-gw-protocol",
    callback_lws_server,
    0 , //Using defaults as well as tried with 65535 size of rx and tx buf size
    0,
    0,
    NULL,
    0
 },
  { NULL, NULL, 0, 0, 0, NULL,0 } /* terminator */
};
In the callback handler:

  case LWS_CALLBACK_RECEIVE:
      printf("DEBUG %d:%s LEN =======  %d\n", __LINE__, __func__, len); //Len comes is parts of 4096 bytes for a 28K byte size packet.

      msg = (struct gw_message *)in;
====

Regards,
Aishwarya

**Comment by lws-team** [comment]
> As an application, I am expecting that the library

For better or worse I have not been able to find a compiler that compiles user expectations into code.

We are still stuck in the Dark Ages where some guy writes specific code with an approach he picked, and people who want to use it must check their expectations at the door until they looked at the reality of how the code works.

In this case, lws has always taken the approach to pass through what it gets when it gets it, this is so lws can handle any size messages on any size hardware, eg, endless streaming video on microcontrollers via ws.

Depending on network conditions and other factors, you may get any size chunks coming at the RECEIVE callback because it may have been chopped into any size tcp fragments; with tls the fragments are reassembled by the tls library to be <= 16KB.

If you want them turned back into atomic messages, you can do it yourself, you can use the helpers listed here to understand how what you received fits in the larger message.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-ws-state.h#n40-54

**Comment by aish84** [comment]
Hi,
If we have many clients that are connecting to the server. Then all the algo needs to be done to do the proper assembly per client. 
Also lws_is_final_fragment() api returns true for a  packet that is entirely accomadated in a single frame as well as the last frame of the fragmented packet. Is there any API to tell if the frame was fragmented or not? (Like hasFrames() sort of api) ?

**Comment by lws-team** [comment]
> If we have many clients that are connecting to the server. Then all the algo needs to be done to do the proper assembly per client.

Yeah... look through the examples at how they use a "pss" struct to bind a user object to each wsi.  Eg

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server/protocol_lws_minimal.c

tcp fragments are a transparent fact of life for tcp-based transfer, you cannot control them because what is received may have been refragmented since it was sent.  So you cannot take this kind of interest in trying to get meaning from the received tcp fragment size.

ws defines a "ws message" which is the only thing you can treat as atomic.  ws messages do not need to tell their size up front, and you can have an "endless" ws message that consists of an unlimited number of ws fragments (not the same as tcp fragments).  If it's notto be endless, then the last ws fragment frame is marked with FIN.

ws knows the ws fragment length and if it has FIN.  `lws_is_final_fragment()` is only true for the last tcp fragment of the last ws fragment in a message, than had been marked with FIN.

See RFC6455 for more about how ws fragments work

https://tools.ietf.org/html/rfc6455#section-5.4
