### ISSUE TITLE
Debian repo

### ISSUE THREAD

**Issue by ktb92677** [warmcat/libwebsockets#2138]
Hi, I hope this isn't too far off topic here...

But for reasons a bit more complex then I'd like to go into here I have to use the libwebsockets instance that is currently hosted on the main debian repo. You can view that here: https://packages.debian.org/buster/libwebsockets-dev.

Unfortunately this version is so old that it doesn't let me tune pt_serv_buf_size from within lws_context_creation_info. Was there a way to tune this in the older version? I'd also like to adjust RX_BUFF_LEN if possible (are these effectively the same thing?)

Thanks again for your time!

**Comment by lws-team** [comment]
The meaning of using a distro package is you can only use what's provided, and the meaning of using a stable release is no abi changes are possible as updates.  So that is how that is.  Sid is better at 4.0.20.  Many entire distros base off debian and exist more or less simply to release faster to bridge the gap between buster and sid.

In ancient versions there were more build-time configs, in a package it's already built and you can't choose any more.  The last years lws moved to almost all runtime configs to avoid this.

If you aren't building something that has to follow distro packaging policy itself, later lws is MIT, you can use git submodule or just bring the whole thing in as /thirdparty or whatever and sub-build / static link etc if your config step discovers distro version of lws is below some threshold.

**Comment by ktb92677** [comment]
Fair enough, closing out this issue.
