### ISSUE TITLE
Slowloris / Question ?

### ISSUE THREAD

**Issue by dev31337** [warmcat/libwebsockets#2154]
Sorry to open an issue while it is a simple question.

Is there a built-in protection in libwebsockets against slowloris ?

If not, is there some timeouts that you can tweak in libwebsockets to prevent/minimize it ?

Thanks.

**Comment by lws-team** [comment]
Various steps in the connection process have timeouts, for example 10s to complete the tls handshake.  Other steps have timeouts, usually 5s each step.  While data is being sent, timeouts are extended to allow for slow links.

Lws also has `LWS_WITH_PEER_LIMITS` that restrict the number of simultaneous connections from one peer, that will be effective against slowloris.  But it won't do anything about a botnet DDoS.

**Comment by dev31337** [comment]
Thanks for the clarification, one last question, if the HTTP request data is received in small chunks (slowloris sends one header line at a time to slow down), is the timeout reset at each chunk ?

**Comment by lws-team** [comment]
This is FOSS... you have the code and a huge number of examples.  If you build auto-build them with `-DLWS_WITH_MINIMAL_EXAMPLES=1` it takes maybe 30s to get a server to test with, another few seconds to open telnet on 127.0.0.1 7681 and type GET / HTTP/1.1, then keep pasting x: y every second and see what happens.

You can get the answer in a minute instead of the time taken to post the question and wait 5 hours for me to wake up and stop what I would be doing to explain to you how to get your own answer.
