### ISSUE TITLE
stop uv loop when running it in lws_service() and context is destroyed in the callback

### ISSUE THREAD

**Issue by aleqs** [warmcat/libwebsockets#2174]
Disclaimer: as you suggested, I switched to using foreign loops, so this no longer directly applies to me. I just thought this suggestion could make the library better. So please feel free to close the issue if you don't think this is relevant.

Earlier, I found it strange that when I use libuv and destroy the context from the callback running within the libuv loop hidden inside lws_service(), the loop can keep going. I think it's safe to say that if you call lws_service(), your sole purpose is to use lws. And if the context is destroyed, the loop is no longer of use and should exit. So perhaps something along the lines of this pseudo code:
```
if (context.is_dead()) {
    uv_stop(&loop_uv);
}
```
could be added on callback return when running lws_service() in libuv mode without using foreign loops.

**Comment by lws-team** [comment]
After the last patches from Tue to the eventlib stuff, this shouldn't be possible, it doesn't happen on lws-minimal-http-server-eventlib anyway.

libuv is unique in that its close actions are also asynchronous, unlike the other event loops you can't just close everything and exit cleanly, you must close things then keep going on the event loop until all the closes are finalized some time later.  This causes fingertraps like failed context creation that started to add things to the loop can't just fail, because they can't back out what the did on the loop before returning... they have to return a half-baked context that has already started the destroy process and runs the loop to extract itself cleanly before exiting.

The internal loop object lives in the pt (per-(service)-thread) that is part of the context object.  Stopping the loop does happen in the libuv eventlib plugin during the staged context destroy, there are many steps to that,it's done after refcounting that all lws objects on the loop have completed their asynchronous libuv handle destroy. And exiting lws_service happens too.

It is very complex, I would like at some point to get rid of the internal event loop since it adds a lot more work for me keeping it unbroken, and just offer "foreign". The overhead for users is just a few lines and it's a lot more flexible.
