### ISSUE TITLE
esp32 basic instruction

### ISSUE THREAD

**Issue by FredrikFornstad** [warmcat/libwebsockets#2179]
Andy,
I fully understand that your focus is not on ESP32, but is it possible for you to "just" give a simple step by step instruction on how to install/compile the current libwebsocket with your minimal example for the Wrover-kit for someone with an esp32 to take libwebsocket for a test drive? 

I have the esp-idf environment on a windows machine which I think you do not use, but a instruction for a linux machine would be of great help to.

Regards,
Fredrik

**Comment by lws-team** [comment]
The best reference is the Sai CI build, this is cross-built and then flashed on an actual wrover and executed with the logs captured

(the link is ephemeral but eg this is the current main Ci build)
https://libwebsockets.org/sai/index.html?task=d4025b87346623f1f12456ec77845eba216ebce28d311c4c7f5eee03081a780f

In the lws `.sai.json` file the section for espidf platform has this (later in the file, ${cpack} is set to "esp-wrover-kit" for that build), it's the name of the esp32 example to build

```
rm -rf ebuild ;
mkdir ebuild;
cd ebuild;
cp -rp ../minimal-examples/embedded/esp32/${cpack} . ; 
cd ${cpack} ;
. /opt/esp/esp-idf/export.sh ;
ln -sf ../.. libwebsockets ;
idf.py set-target esp32 &&
cp libwebsockets/minimal-examples/embedded/esp32/${cpack}/sdkconfig . &&
cp sdkconfig.h build &&
idf.py ${cmake} build size size-components size-files &&
cd build &&
/usr/local/bin/sai-device ${cpack} ESPPORT=0 ctest --output-on-failure
```

This is with esp-idf from like a month ago or so.

If you can build and flash it, you will be rewarded by a picture on the wrover kit lcd of my ex-neighbour's cat, known by us as Ghengis Khat being trolled by a magpie he thought he was going to catch up a tree, dynamic pwm on the rgb, screensaver timer and smooth pwm transitions on the backlight on -> dim -> off, and if you wire a pushbutton from GPIO14 to 0V, a way to wake the screensaved backlight.

Unlike the last attempt all of the features, including the wlan pieces, go through a generic lws layer instead of just use esp-idf, so it is portable to other SDK.

Notice you have to enable a little hack to get your credentials in the nvm one time atm since no UI pieces

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/embedded/esp32/esp-wrover-kit/main/devices.c#n185-206

**Comment by FredrikFornstad** [comment]
Thanks.
I have a DevC, not a wrover with a lcd, so I will only see what the idf.py monitor shows...

I just did a quick compile (without fixing the WiFi credentials) and it seems working with the latest esp-idf in the master branch. 

I noted that the size of the compiled bin file is 1271728 bytes (776317 compressed), which is a considerable increase since the days of the factory-app if I remember right. But maybe that can be optimized by disabling stuff that I might not need.

With this working, now I can start to play around with it. Great!

For future reference in case someone else wonder here is a short description:

On a native Windows 10 (not using MSYS2) do the following:

Make sure you have installed the esp-idf environment (including git) as described at https://github.com/espressif/esp-idf.
Open the "ESP-IDF Command Prompt” shortcut in the Start Menu.

Check that you have a working openssl installation by typing 'openssl --version' at the command prompt.
If it did not work, you can use the openssl.exe that you already have in your Git installation. Just add \Program\Git\usr\bin to the Windows Path.

In the command window, make sure you are in the esp-idf directory, then: 
```
mkdir esp-wrover-kit
cd esp-wrover-kit
git clone https://github.com/warmcat/libwebsockets.git
xcopy libwebsockets\minimal-examples\embedded\esp32\esp-wrover-kit /E/H
idf.py set-target esp32
idf.py menuconfig  (make sure the partition table setting says it is using the custom partitions.csv file and that main task stack is 6584), save and quit
idf.py build
idf.py -p COM7 flash monitor  (change to the port that your esp32 uses)
```

**Comment by lws-team** [comment]
Glad you can build it ok.

This test example has an uncompressed lcd bitmap in it, it's aimed at testing various new pieces like secure streams, lws_device layers... it's not trying to be comparable to or compatible with the old esp32 projects.
