### ISSUE TITLE
Issues binding to a specific IP in Janus Gateway

### ISSUE THREAD

**Issue by Symbiatch** [warmcat/libwebsockets#2180]
Janus Gateway uses libwebsockets internally and I'm having issues getting it to bind to a specific IP address. There's something very weird going on with it that I don't really understand.

It's using libwebsockets 4.0.20 which is included in Debian (testing), AMD64.

When Janus asks the websockets to bind to a specific interface/ip (10.0.1.1/eth1:0) I get this:

> bind(19, {sa_family=AF_INET6, sin6_port=htons(8188), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::ffff:10.0.1.1", &sin6_addr), sin6_scope_id=0}, 28) = -1 EINVAL (Invalid argument)

In debug logs libwebsockets says

> [libwebsockets][DEBUG] lws_interface_to_sa: uplevelling ipv4 bind to ipv6
[libwebsockets][ERR] ERROR on binding fd 16 to port 8188 (-1 22)
[libwebsockets][INFO] _lws_vhost_init_server: lws_socket_bind says -1
[libwebsockets][DEBUG] deferred iface: adding vh default
[libwebsockets][ERR] VH default: iface eth1:0 port 8188 DOESN'T EXIST

If I don't set a specific IP/interface I get the bind correctly to any IP address/interface, *but* no IPv4 connections are accepted, only IPv6 for some reason.

They said to ask here since it might be some internal issue with the library, their code doesn't seem to be doing anything weird and connections and data traffic works in IPv6 normally. 

~~Also the function `lws_create_vhost` returns a struct even though the bind failed and no vhost could be created. Not sure if this is fixed in some newer version or if this is somehow expected behavior? Janus therefore claims everything is fine since libwebsockets says everything went fine.~~ This was due to them not using `LWS_SERVER_OPTION_FAIL_UPON_UNABLE_TO_BIND`

**Comment by lws-team** [comment]
What does `ifconfig eth1:0` look like?

**Comment by Symbiatch** [comment]
> 
> 
> What does `ifconfig eth1:0` look like?

> # ifconfig eth1:0
eth1:0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.1.1  netmask 255.255.255.0  broadcast 10.0.1.255
        ether 00:15:2d:f7:5a:03  txqueuelen 1000  (Ethernet)

**Comment by Symbiatch** [comment]
I did a test with this: https://github.com/iamscottmoyers/simple-libwebsockets-example/blob/master/server.c

If I add `info.iface = "eth1";` for example, running it in Windows Subsystem for Linux (Ubuntu 20.20, libwebsockets16:4.0.20) still works fine:

> bind(5, {sa_family=AF_INET6, sin6_port=htons(8000), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::ffff:192.168.56.1", &sin6_addr), sin6_scope_id=0}, 28) = 0

But if I run the same code on the Debian x64 system I get the original error:

> bind(5, {sa_family=AF_INET6, sin6_port=htons(8000), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::ffff:10.0.1.1", &sin6_addr), sin6_scope_id=0}, 28) = -1 EINVAL (Invalid argument)

So I'm a bit confused why it would work on one system and not on another.

**Comment by lws-team** [comment]
I don't know if it's the same issue but when I updated my server that runs everything based on lws from fedora 32 -> 33, I saw something similar to this, the vhosts have ipv6 enabled and it was reachable by ipv6 only (my home ISP does not support ipv6 so it's not easy to check it).

I set the vhosts to only use ipv4 (with lejp-conf JSON settings, `"noipv6": true`, with code set vhost creation info options `LWS_SERVER_OPTION_DISABLE_IPV6` when creating it), it bound OK to ipv4 and it seemed to be accessible by ipv6 that way too.

Since it worked like that for years I guessed something changed in the kernel or firewalld and put it on my whiteboard to look into it (maybe end up with multiple bindable ipv4/v6 listen sockets or something).  You might try the above and see if it helps.

**Comment by Symbiatch** [comment]
> 
> 
> I don't know if it's the same issue but when I updated my server that runs everything based on lws from fedora 32 -> 33, I saw something similar to this, the vhosts have ipv6 enabled and it was reachable by ipv6 only (my home ISP does not support ipv6 so it's not easy to check it).
> 
> I set the vhosts to only use ipv4 (with lejp-conf JSON settings, `"noipv6": true`, with code set vhost creation info options `LWS_SERVER_OPTION_DISABLE_IPV6` when creating it), it bound OK to ipv4 and it seemed to be accessible by ipv6 that way too.
> 
> Since it worked like that for years I guessed something changed in the kernel or firewalld and put it on my whiteboard to look into it (maybe end up with multiple bindable ipv4/v6 listen sockets or something). You might try the above and see if it helps.

Using `LWS_SERVER_OPTION_DISABLE_IPV6` does fix the issue and if I could make that easily into Janus I'd send a PR to support it, but it's really weird that this kind of a thing is happening. I agree it probably is something in the kernel that's causing this (Debian is running 5.10, I could probably try the code on another machine...)

Currently I patched the code locally to disable IPv6 so I could get it to work, it is an option but always would be nicer to not patch things myself.

**Comment by lws-team** [comment]
Ideally we can understand what goes on exactly and decide from that, but I don't have time to dive into it atm.  My general plan is as I say get around to refactor to allow separate listen sockets, with discrete binding, from how it acts it seems that would clear whatever it is.

The workaround pieces are publicly exposed in lws for many versions if Janus want to add a user flag, it's fair to say it is a hack since we don't know the root cause yet, but it also worked around it here reliably, whatever it is.
