### ISSUE TITLE
async dns cache invalidation

### ISSUE THREAD

**Issue by parihaaraka** [warmcat/libwebsockets#2192]
1) successful connection
2) disable network -> `ipv6 lws_getaddrinfo46 failed` on first reconnect attempt, then `lws_async_dns_query: using cached, c->results (nil)`
3) enable network -> unable to connect any more with permanent `lws_async_dns_query: using cached, c->results (nil)`

**Comment by lws-team** [comment]
I have some patches around this that improve robustness against broken network and startup with no network, but I can't push them until something else is solved, hopefully tomorrow.

**Comment by lws-team** [comment]
I pushed some changes around this on main now, one patch adds a -l option to lws-api-test-async-dns, if given instead of running the normal tests, he just sits there trying to lookup "warmcat.com" every 5s on a sul timer.  This makes it simpler to test how it reacts to not having any network and getting connectivity later.

Other patches make it no longer freak out if no dns server available when it starts, since it will notice it later, and allow dumping of cache and ongoing query lists when built with _DEBUG.  It seems to work well now for your scenario, please give it a try.

**Comment by parihaaraka** [comment]
It looks ok at first glance. Thanks a lot 🤝🏻
