### ISSUE TITLE
error: ‘lws_vhost_user’ was not declared in this scope

### ISSUE THREAD

**Issue by ktb92677** [warmcat/libwebsockets#2194]
Hi! I am using an older version of libwebsockets and I noticed that this function is not declared in the libwebsockets.h file I have installed locally. For reasons a bit more complex then I would like to go into now I cannot upgrade my libwebsockets install... is there anyway to mock this functionality here? I want to pass in specific user data per vhost without the use of the lws_vhost_user function. I also noticed that lws_vhost_destroy was not declared either, is there a way to replicate this functionality as well on the older library?

**Comment by lws-team** [comment]
Basically you have two choices, backport what you want on to your old version, or update to later lws.

Nobody is looking after your old lws version, it generally makes sense to update to later lws to get your newer features rather than backport.

You can read about lws release policy here

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.release-policy.md
