### ISSUE TITLE
Can lws_callback_on_writable_all_protocol_vhost be called outside of callback function?

### ISSUE THREAD

**Issue by ktb92677** [warmcat/libwebsockets#2195]
Can lws_callback_on_writable_all_protocol_vhost be called outside of callback function? If so what should I put for the protocol? Just passing in an address to the correct lws_protocols results in the following error: [2021/02/03 19:45:25:8171] E: lws_callback_on_writable_all_protocol_vhost: protocol 0x55a02f758060 is not from vhost 0x55a02f758610 (0x55a02f7736b0 - 0x55a02f758680). I only have one vhost right now. And I have also confirmed that the address is the same as the one passed into protocols in lws_context_creation_info

**Comment by lws-team** [comment]
Complicated answer first... although you provide the context a list of protocols, each vhost assembles it own private list of protocols that apply to the protocol used on that vhost.  These are called "vhost-protocols".  When you create a wsi bound to a vhost, eg, a client connection, it's the protocol listed in the vhost's private protocol table that is used.

This is to deal with various useful situations, you may have multiple vhosts but only want a protocol to be available on one of them.  Protocols may have been discovered at runtime from protocol plugins and not appear in your original list.

There's also the need to point different vhost-protocol instantiations to different trees of per-vhost options, or pvos, so that you can configure the same protocol differently depending on which vhost it is bound to.

Now, having understood that, the simple answer, you can get the vhost-protocol pointer you need by an api that is aware of all that

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-protocols-plugins.h?id=8ea59a162b9e519d9fe19c1d16e44854d6bd1076#n89-98
