### ISSUE TITLE
Unable to compile with LibreSSL

### ISSUE THREAD

**Issue by WSLUser** [warmcat/libwebsockets#2198]
It seems LibreSSL support was dropped at some point in this project's life. I requested LibreSSL support for ttyd and when the ttyd maintainer tried compiling it failed. See this comment: https://github.com/tsl0922/ttyd/issues/524#issuecomment-753250685

**Comment by lws-team** [comment]
As far as I recall lws has never supported libressl, rather than "dropping support" for libressl it's more likely it diverged from any actually supported openssl version or some other problem.

(Supporting it isn't zero cost, there's no libressl package for Fedora I can install and use alternatives or whatever, like boringssl it wants to be the "openssl" package with .../include/openssl etc and conflict with the build machine's native openssl.)

The error mentioned on the ttyd issue is because libressl doesn't seem to support the tls 1.3 api `SSL_CTX_set_ciphersuites()` openssl and lws does.  However, the lws cmake is testing for its existence, in `./lib/tls/CMakeLists.txt`

```
CHECK_FUNCTION_EXISTS(${VARIA}SSL_CTX_set_ciphersuites LWS_HAVE_SSL_CTX_set_ciphersuites PARENT_SCOPE)
```

... and at the error...

```
#if defined(LWS_HAVE_SSL_CTX_set_ciphersuites)
	if (info->tls1_3_plus_cipher_list)
		SSL_CTX_set_ciphersuites(vhost->tls.ssl_ctx,
					 info->tls1_3_plus_cipher_list);
#endif
```

... so I guess the problem is caused by cmake finding the build host openssl pieces, as I say libressl and boringssl make it very hard to use them on a typical Linux distro build machines because they conflict with openssl "by design".

**Comment by WSLUser** [comment]
Can you provide support for TLS 1.3 and get those other SSLs able to compile within a cmake environment? It should be possible to compile without allowing references to the built-in OpenSSL, for Fedora or otherwise.

**Comment by lws-team** [comment]
> Can you provide support for TLS 1.3

That's not the problem, lws supports tls 1.3 with openssl just fine.

I looked further into it, CHECK_FUNCTION_EXISTS() in cmake is fooled by the actual libressl headers into thinking tls1.3 is enabled when it isn't in libressl.  I changed it to CHECK_SYMBOL_EXISTS() and it solved the problem.

Since Janurary lws has stricter typing warnings by default, it needed some other small adaptations for options api types, after that it worked fine.

I added a README about libressl

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.libressl.md

and it's also built in CI now

https://libwebsockets.org/sai/index.html?task=2bd78afe4cfe261a3569db388389dbd9172e9a8541fac2170e21bac354304856
