### ISSUE TITLE
lws_service() timeout value

### ISSUE THREAD

**Issue by bdonduprey** [warmcat/libwebsockets#2199]
Hi,
I have some questions regarding lws_service() routine and the timeout parameter posed in v3.2.
On the libwebsockets.org documentation(https://libwebsockets.org/lws-api-doc-v3.2-stable/html/group__service.html#gaf95bd0c663d6516a0c80047d9b1167a8), and the lws-service.h comments  the timeout_ms parameter says “Set to 0; ignored; for backward compatibility”. Also: “Since v3.2 internally the timeout wait is ignored, the lws scheduler is smart enough to stay asleep until an event is queued.”

However, if you look at the code, lws_service gives the timeout_ms value to lws_plat_service and then to _lws_plat_service_tsi. In this function, this timeout value is converted to either 0, if less than 0, or to 23 days, if greater than or equal to 0. (See https://github.com/warmcat/libwebsockets/blob/f04cc95a455e4d4201a70211dc9f91b7ddc10ab2/lib/plat/windows/windows-service.c#L87) 

My questions are…

1. How is this 0- or 23-day timeout value used? Why even convert it to 23 days and simply just ‘ignore’ the value?

2. If this function is called with a negative timeout value, forcing the timeout to be converted to 0, how does this affect the behavior of the lws_service() function?

3. In the client and server code examples provided, there are no instances of a negative value being used.  Are all these examples using a 23 day ‘timeout’?  

4. Do you recommend to NOT use a negative timeout value?  If not, shouldn’t everything just use a value of 23 days (even if it is negative)?

The reason I ask is, I have a Windows based device where the lws_service() function is called, providing a negative 1 timeout value.  This dramatically increased the CPU usage to 100% according to the Windows Task Manager.  However, when that same value is changed to be greater than or equal to 0, the CPU usage went back to about 5% to 10%.

Consequently, on a different Windows based device when performing an upload and download via a websocket connection a transfer of data took about 3 to 5 mins to complete when a value of negative 1 was used.  However, when the 23-day timeout was used the upload and download increased by a factor of 10 to about 30 – 50 mins.

Thanks in advance for any information you can provide!

**Comment by lws-team** [comment]
Well this is a few different things, rather than answer your subquestions in a way that doesn't really leave you understanding what happened first a spoiler, you actual problem is caused because the windows WSA stuff doesn't work properly for all conditions before current main branch.  So use current main branch, it should broadly just work the same as 3.2 otherwise in terms of apis.

The background for the timeout thing is that when there are no scheduled or network events, lws should stay completely asleep.  The stuff introduced on 3.2 about lws_sul allows that to work by keeping a sorted list of scheduled events, and trimming the actual sleep to only last long enough to get us to the earliest scheduled event.

At the same time, event library support (using libuv / event / ev / glib / sdevent as the event loop) does not have any service loop you can externally put things into... when you start the event lib loop, you typically don't come back from the api until the process is exiting.  Eventually the default poll loop will work the same, you won't come back from entering lws_service but the loop is happening inside that.  So the other goal of the changes is to inform people who hacked their own stuff into the lws service loop in the user code that this approach will eventually go away in order to have lws work compatibly with or without an event lib doing the event loop.  People who rely on that hack complained and so there is this uneasy, undocumented get-out at the moment that passing -1 as the "timeout" causes the lws service to return without waiting, whether there was something to do (it will do it) or not, to enable this loop sharing hack code to keep working for now.

You should just use main branch and your should find it works as you expect now.

**Comment by bdonduprey** [comment]
@lws-team Okay, thanks for the quick response! This clears things up a lot. We do have a plan to update to the latest libwebsockets code but since we have multiple devices with varying OS platforms, we haven't done so quite yet. We will make sure to do this sooner than later.

As always, your help is greatly appreciated and the quick responses are very helpful!
