### ISSUE TITLE
Building with IPV6 and -Werror=format-extra-args doesn't build

### ISSUE THREAD

**Issue by claudiucismaru** [warmcat/libwebsockets#2209]
The problem is in line, where %s is missing, for the error message:

lib/libwebsockets.c: In function 'lws_get_addresses':
lib/libwebsockets.c:645:4: error: too many arguments for format [-Werror=format-extra-args]
    lwsl_err("inet_ntop", strerror(LWS_ERRNO));
    ^

**Comment by lws-team** [comment]
This is already fixed in at least the last two releases and main, it moved to live in `./lib/core-net/network.c`

main: https://libwebsockets.org/git/libwebsockets/tree/lib/core-net/network.c#n61
v4.1-stable: https://libwebsockets.org/git/libwebsockets/tree/lib/core-net/network.c?h=v4.1-stable#n61
v4.0-stable: https://libwebsockets.org/git/libwebsockets/tree/lib/core-net/network.c?h=v4.0-stable#n60

Maybe use a more recent lws?

**Comment by claudiucismaru** [comment]
Sorry. I didn't pay attention and the code checked from repo was with an old tag. You can close this.
