### ISSUE TITLE
lws_service timeout takes 30 seconds if not set to -1 

### ISSUE THREAD

**Issue by codingtrack** [warmcat/libwebsockets#2212]
since v3.2 the timeout is ignored by lws_service, when I use 4.1.2 the timeout seems like 1 second, but 4.1.6 is 30 senconds, and I send msg every 5 seconds in lws_service thread not work because this, It will delay to 30 seconds to send. So is there any way to speed up lws_service?

**Comment by lws-team** [comment]
The changes from v3.2 are documented here

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.lws_sul.md?h=main

The poll wait delay is removed, because it does not exist when using event libs.  You should not write your user code to care about it, trying to share event loops always results in higher latencies and isn't the way to do it.

The change on v4.1-stable that stopped the 1Hz waking is this, to disable WITH_SEQUENCER by default, which on v4.1 runs a 1Hz "heartbeat" whether you have any active sequencers or not

https://libwebsockets.org/git/libwebsockets/commit?id=5f4ced47d8812f59e6d0797c94cfc935435466c8

If your user code unwisely depends on those wasted wakes just add -DLWS_WITH_SEQUENCER=1 at cmake to get them back.

If you have things you want to run at intervals, you should better make your own explicit lws_sul in user code as described in the README link above and schedule it as its own thing at the rate it wants.  And remove any code inside the default service while loop.
