### ISSUE TITLE
callback has not been called from lws thread after main thread call lws_cancel_service

### ISSUE THREAD

**Issue by hqfrank** [warmcat/libwebsockets#2222]
In my program:

```
static int
callback_protocol(struct lws *wsi, enum lws_callback_reasons reason,
                           void *user, void *in, size_t len){
    printf("%s\n", __func__);
    printf("callback_reason is %d\n", reason);
    switch (reason) {
      case LWS_CALLBACK_PROTOCOL_INIT:
        printf("LWS_CALLBACK_PROTOCOL_INIT");
        break;
      case LWS_CALLBACK_EVENT_WAIT_CANCELLED:
        printf("LWS_CALLBACK_EVENT_WAIT_CANCELLED");
        break;
      default:
        break;
  }
  return 0;
}

#define TSS_PROTOCOL \
    { \
      "tss_protocol", \
      callback_protocol, \
      sizeof(struct customized_buf), \
      128, \
      0, NULL, 0 \
    }

static struct lws_protocols protocols[] = {
    TSS_PROTOCOL,
    { NULL, NULL, 0, 0, 0, NULL, 0 }
  };

...

// I also define a function to create lws:
struct lws_context  *context;
int interrupted;

void
create_lws() {
  struct lws_context_creation_info  info;
  lwsl_user("%s: tid %d\n", __func__, std::this_thread::get_id());
  memset(&info, 0, sizeof info);
  info.pss_policies_json   = default_ss_policy;
  info.options             = LWS_SERVER_OPTION_EXPLICIT_VHOSTS |
                               LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
  info.fd_limit_per_thread = 1 + 6 + 1;
  info.port                = CONTEXT_PORT_NO_LISTEN;
  info.protocols           = protocols;
  context = lws_create_context(&info); // context is defined as a global variable
    if (!context) {
      lwsl_err("lws init failed\n");
    }
  while (!interrupted) {
      if (lws_service(context, 0)) {
        interrupted = 1;
      }
    }
   lws_context_destroy(context);
   return;
}

//=========my main program==============
int main() {
  thread evntloopThObj(create_lws);
  chrono::milliseconds dura(3000);
  this_thread::sleep_for(dura);
  lws_cancel_service(context);
  while(1) {
  }
  return 0;
}
```

In my opinion, after lws_cancel_service() is called, callback_protocol() should be called in the lws thread. However, there is no printout shown in the terminal. I suppose the callback_protocol() is not called. Any idea about whether I used the lws_cancel_service and the callback correctly?

**Comment by lws-team** [comment]
By default, for backwards compatibility when you create the context, lws creates a single default vhost automatically, and instantiates all the protocols you give on that vhost automatically too.  This was how lws worked 10 years ago when that was its only mode.

When you use `EXPLICIT_VHOSTS`, necessary for Secure Streams since the policy creates vhosts, lws no longer creates the default vhost, it's saying you will explicitly create your own vhosts.  So that's the first thing, you need to create a vhost too like this

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-multivhost/minimal-http-server.c?h=main#n159-170

Since context and vhost creation use the same struct, you can prepare what you want and just create the vhost after the context with the same struct.

Since there can be many vhosts, eg, https://warmcat.com and https://libwebsockets.org are two vhosts served by lws on the same server, it's necessary to also specify which protocols are enabled on which vhosts.  Protocols can also be picked up at runtime by loading protocol plugins.  You list which protocols you want on your vhost by giving it a linked-list of "pvo"s, per-vhost options naming the protocols you want enabled on it:

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads/minimal-ws-server.c?h=main#n79
https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads/minimal-ws-server.c?h=main#n116

The tree of options in the .child member are passed to the protocol at PROTOCOL_INIT, when it's bound to a vhost.  That allows you to instantiate the same protocol on multiple vhosts, with different options.  But in this case, you can leave .child NULL, just listing your protocol name in the pvo is enough to enable it.

From a server perspective, lws provides the ability to define all this using JSON to configure vhosts and what protocols are enabled, so adminning it doesn't need code.  https://libwebsockets.org and its other vhosts, cgi and reverse proxying for other services are all defined in JSON.

From Secure Streams perspective, most users aren't going to go down a level to the lws pieces like this, in fact SS is basically designed to conceal the gnarly detail... it might be better for lws add a way to get an arbitrary C callback on cancel service at the context for that.
