### ISSUE TITLE
Reconnecting with multiple connections

### ISSUE THREAD

**Issue by xCuri0** [warmcat/libwebsockets#2241]
Hi I'm using libwebsockets with multiple connections and I need to reconnect ones that disconnect (not all). I've looked at the examples for reconnecting and there doesn't seem to be a way to know which connection is getting disconnected afaik.

**Comment by lws-team** [comment]
In lws, streams are identified by their wsi.

The callbacks that relate to a stream, like CLIENT_CONNECTION_ERROR or CLOSE, all have the stream they apply to specified in the wsi given to the callback.

If you mean not "which wsi" but "which stream does this wsi represent for my purposes", you must mark the stream at client connection creation time, so you can tell what it is later.  You can either set the "user_data" at creation time, or the "opaque_user_data" and take a look at it when trying to understand which wsi is which.  You can point to a related object, put an ordinal in there or whatever is useful.

**Comment by xCuri0** [comment]
@lws-team I'm using the same context for all connections. I looked at the examples and it seems like the reconnect works by calling a method which has the connection server/path hardcoded in it which won't work for me.

**Comment by lws-team** [comment]
>  I looked at the examples and it seems like the reconnect works by calling a method which has the connection server/path hardcoded in it which won't work for me.

... they are called, "minimal examples".  They prove that the lws end of the functionality works, and you can use it as a building block.  Where the address comes from in the example (it's often able to be passed in from a commandline option) is not telling some limitation, it's telling you the example is "minimal" so you can understand how it fits together quickly and can adapt it / cut and paste it for what you want to do.

Your app is still YOUR app and your problem to architect.  Lws should just make it possible to build on cleanly and that's the end of what you can expect from me.

wsi only live for the lifetime of a connection, if you have a task with a larger lifetime or states that go beyond one connection, you must create your own object to represent that, and bind any connections you make on behalf of your object to the object, eg, in the client connection info

```
    ino.opaque_user_data = myobject;
```

in the callback for the client connections

```
    myobject_t *myobject = (myobject_t *)lws_get_opaque_user_data(wsi);
```

Now if your wsi gets a _CLOSE or _CLIENT_CONNECTION_ERROR you not only know the wsi / ephemeral connection, but you have a pointer to the longer-lived task object it represented, you can schedule a retry later in that object using an lws_sul.  And nothing stops you getting the address that guy wants to connect to also from the myobject_t rather than "hardcoded strings".
