### ISSUE TITLE
minimal-ws-server-pmd-bulk example working

### ISSUE THREAD

**Issue by CVVDN-S** [warmcat/libwebsockets#2242]
Hi, Im trying to send a bulk data through libwebsocket. So i got this examples in the folders. How can i test this example. i have Simple websocket client extension in chrome. How can i test this example binary?
I tried running this binary as :./lws-minimal-ws-server-pmd-bulk -c
how can i get the client?

**Comment by lws-team** [comment]
To build and run the example, first build and install lws, if you care about permessage-deflate then with at cmake with `-DLWS_WITHOUT_EXTENSIONS=0`.  The `make && sudo make install`.

If you don't care about permessage-deflate, look at the simpler example ./minimal-examples/ws-server/minimal-ws-server instead.  I use that below.

Enter the xample dir, like `cd ../minimal-examples/ws-server/minimal-ws-server`

`make . && make && ./lws-minimal-ws-server`

> How can i test this example binary?

I dunno how to test your extension because I don't know what it is or does.  But there is how to run the lws example.
