### ISSUE TITLE
SSL_new fails with WolfSSL for IMX6

### ISSUE THREAD

**Issue by Juno-Explorer** [warmcat/libwebsockets#2252]
## Description: 

- I'm using LWS with WolfSSL. My application seem to work fine with LWS v3.2.3 for my devices that are using imx6 and i686. As soon as I have updated my LWS to v4.1.6 it doesn't seem to work with imx6 based devices and keep complaining about: 
```
 E: SSL_new failed: Please supply a buffer for error string
 E: Client connection failed: bio_create failed
```

- The code flow in through: lws_client_connect_via_info() -> lws_client_create_tls() -> lws_ssl_client_bio_create() -> SSL_new() which reports failure. 

- The WolfSSL version I have is v4.6.0, the same version of LWS is working on i686. 

Any inputs to resolve this are welcomed.

**Comment by lws-team** [comment]
>  it doesn't seem to work with imx6 based devices 

It has no idea if your device is iMX.6 or not... It's tested in CI on aarch64 and works fine, eg current main

https://libwebsockets.org/sai/index.html?task=26d0e44c9f3c51de6af21a5a7b3b26b31bff4a48bc18be6a2b684224c3435be5

It's also build-tested against wolfssl in CI.

This string "Please supply a buffer for error string" seems to be coming out of wolfssl's ERR_error_string

```
...
	wsi->tls.ssl = SSL_new(wsi->a.vhost->tls.ssl_client_ctx);
	if (!wsi->tls.ssl) {
		const char *es = ERR_error_string(
#if defined(LWS_WITH_BORINGSSL)
	(uint32_t)
#else
	(unsigned long)
#endif
	lws_ssl_get_error(wsi, 0), NULL);
		lwsl_err("SSL_new failed: %s\n", es);
		lws_tls_err_describe_clear();
		return -1;
	}
...
```

... if you can give me something I can reproduce on a platform I have, eg, aarch64 / rpi4, I can look into it.  Otherwise I would guess it is something related to your toolchain, or integrations, on the basis the same versions of everything work OK for you on x86.
