### ISSUE TITLE
TLS notify errors

### ISSUE THREAD

**Issue by fusionJose** [warmcat/libwebsockets#2265]
Is there a way where libwebsockets, as a websocket client, notifies that it hasn´t validated server certificate in TLS connections?

And if server has an older TLS version or only allows SSL?

**Comment by lws-team** [comment]
There's an info level log with the reason for the problem.

LWS_WITH_SYS_METRICS can collect this information.

In the CLIENT_CONNECTION_ERROR callback, in should have a string describing the problem.

**Comment by fusionJose** [comment]
Okey thanks

**Comment by fusionJose** [comment]
I have a question. I forced an SSL cert error, and I can see it on lws log: 

E: SSL error: self signed certificate (preverify_ok=0;err=18;depth=0)

But in CLIENT_CONNECTION_ERROR callback it only reports: 

connect SSL err 1: error:00000001:lib(0):func(0):reason(1)

And there is no more information.

How can i collect that error 18 with LWS_WITH_SYS_METRICS? Is there an example?

Thanks in advance

**Comment by lws-team** [comment]
> But in CLIENT_CONNECTION_ERROR callback it only reports:

What does it mean "it only reports"... that's what is in the 'in' parameter, or you are trying to dump the openssl error stack?

> LWS_WITH_SYS_METRICS example

If you enable LWS_WITH_SYS_METRICS, then lws-minimal-http-client-multi will dump metrics to the logs.

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client-multi/minimal-http-client-multi.c#n351-373
https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client-multi/minimal-http-client-multi.c#n531-533

You can see the kind of output you will get here

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.lws_metrics.md

|tag|meaning|
| -- | --|
| tls/invalidca | Peer certificate CA signature missing or not trusted|
| tls/hostname | Peer certificate CN or SAN doesn't match the endpoint we asked for|
| tls/notyetvalid | Peer certificate start date is in the future (time wrong?)|
| tls/expired | Peer certificate is expiry date is in the past|
| dns/badsrv | No DNS result because couldn't talk to the server|
| dns/nxdomain | No DNS result because server says no result|

**Comment by fusionJose** [comment]
Thank you very much.

Is there an example where they report events as they happen? I don´t know exactly how to configure that.

**Comment by lws-team** [comment]
Metrics is designed for collecting a periodic overview of what has been happening, asynchronous to any specific connection.

Even if it reported it immediately, you're not going to be able to tie it to which connection caused it.  If you want to understand what went wrong with a specific connection, CLIENT_CONNECTION_ERROR is the way.

If you want to know it immediately for some other reason, please explain so I can understand what you're trying to do.

**Comment by fusionJose** [comment]
What i am trying to do is to be able of collecting the reason of the problem when something fails with TLS, immediately. Because I need to report it by other way.

I mean, I need to know for example if there is a SSL error due to self signed certificate. If server certificate isn´t valid. If server TLS allows an older version of TLS, or only allows SSL...

And I need to know it inmediately, in CLIENT_CONNECTION_ERROR will be okay. But now, CLIENT_CONNECTION_ERROR only reports for self signed certificate error:

CLIENT_CONNECTION_ERROR: connect SSL err 1: error:00000001:lib(0):func(0):reason(1)

**Comment by fusionJose** [comment]
Is there a way at CLIENT_CONNECTION_ERROR to explore the lws_metric_pub_t struct with event measurements that have occurred?.

I mean as the explore loop:
       do {
                if (lws_metrics_format(mp, &sub, buf, sizeof(buf)))
                        logi("%s: %s\n", __func__, buf);
        } while ((mp->flags & LWSMTFL_REPORT_HIST) && sub);


I can´t get access mp struct in CLIENT_CONNECTION_ERROR callback.

**Comment by lws-team** [comment]
No, you shouldn't mix the two.  You should get enough data at the `in` param of the CLIENT_CONNECTION_ERROR.

I will look at it, but today I have no time.

**Comment by fusionJose** [comment]
Okey, I need to report it in a display, the reason which make TLS fail. When connection fails.

Also I need to downgrade from TLS to unsecure websocket connection and report server the problem reason.

Thank you.

**Comment by lws-team** [comment]
I pushed a patch on main that improves that... the issue is the better explanation exists inside the validation callback only.  I gave it a way to come out to the CCE.
