### ISSUE TITLE
No proxy in WS client

### ISSUE THREAD

**Issue by moidroid** [warmcat/libwebsockets#2276]
Hi,
I am trying to figure out how to disable so that my WS application does not try to go through our proxy.
The only related config I can find is the lws_set_proxy() function.

[2021/04/15 14:02:51:2819] ERR: ERROR proxy: HTTP/1.1 403

**Comment by lws-team** [comment]
In Linux, the convention is for apps to look at the `http_proxy` env var to learn about proxying requirement.

If you have an explicit proxy set like that, you can zap that just for your app process before running your it, eg `http_proxy=  myapp`

If you have a proxy that operates at the network level, that forces all :80 and :443 traffic to go through it captive portal style, you can try moving your server to a different port or using ssh tunnels.  But that kind of thing is a question for whoever runs the proxy rather than me.

**Comment by moidroid** [comment]
Yes it is on Linux and I am running the server and client on the same dev computer so I am only using localhost, but still it insists of going through proxy. In curl  there is for example the flag  --noproxy which makes it skip the proxy. So I figure there is no such possibility.

I will try changing the http_proxy temporarily because it does not seem to care about no_proxy flag having localhost in it.

**Comment by lws-team** [comment]
AFAIK doing as I suggest above has the same effect as --noproxy.

**Comment by moidroid** [comment]
Thanks for the answer!
Works very well! :-)
