### ISSUE TITLE
WebSocket test client

### ISSUE THREAD

**Issue by moidroid** [warmcat/libwebsockets#2282]
Hi,
I have tried out the minimal-ws-client and I am able to connect to my WebSocket server using my server details.
I also tried the example on this page and it looks to me very much the same as the minimal-ws-client but I cannot understand why the WebSocket callbacks are not hit.
https://github.com/iamscottmoyers/simple-libwebsockets-example/blob/master/client.c

The only message I get on the server is:
[2021/04/21 08:00:00.0000] NOTICE: lws_http_to_fallback: vh default, peer: 192.168.1.1, role raw-skt, protocol http-only, cb 62, ah (nil)

So it does seems like I am opening an http only connection but I don't understand why that is happening in the example in the link.

**Comment by lws-team** [comment]
This is not my code, but it works as far as it goes (tested on main) against lws-minimal-ws-server running unchanged.

The example needs to be pointed to port 7681, and the example protocol name changed to "lws-minimal" to match what the minimal ws server example offers.

So I don't think the problem is, "it doesn't work", the problem is something else.

**Comment by moidroid** [comment]
Thanks!
Yes, I am aware that it is not your code.
I am trying to run the example found in the link towards my own server so not an example server.
Your example provided in the installation works fine after changing path and so on, but I am trying to understand why that particular code in the link is not working.

Also, I have been using python WebSocket clients before without problem against my server.

Is there anything special in the WS client that makes the difference between a regular HTTP connection and one for WebSocket?
The code works and it seems to be using the same procedure as your examples but for some reason does not establish a WebSocket connection as your examples does against my server.

**Comment by lws-team** [comment]
To be clear I tested the client code in your link, with the two changes mentioned, it works fine connecting to lws-minimal-ws-server.

It's good you have faith in my deductive abilities but rather than ask me why the client example I didn't write won't connect to your webserver I didn't write :-) with one line of log, why don't you turn up the logging (like -d1151 equivalent) and at least provide the clue about what the client thinks happened?  If no tls, you can tcpdump the link as well.

**Comment by moidroid** [comment]
Yes, I agree and don't expect that from you.
Thanks for testing with your test server.

I guess I was hoping that there was something that was obviously wrong :-)

I will continue testing with the increased logging level.

Thanks!
