### ISSUE TITLE
lejp does not NUL terminate STR_CHUNK

### ISSUE THREAD

**Issue by alexeadem** [warmcat/libwebsockets#2307]
```
	if (reason & LEJP_FLAG_CB_IS_VALUE) {
		
		if (ctx->ipos) {

		}
			
		ctx->buf[ctx->npos]=0; /* workaround needed when ctx->npos = 254 otherwise ctx->buf is not null terminated */
		p += lws_snprintf(p, end -p, " = %s ", ctx->buf);
		printf("%s\n", buf);

	
		(void)reason_names; /* NO_LOGS... */
		return 0;
	}
```
I see there is room in the buffer for the null character but it is not used when it is a chunk.
`char buf[LEJP_STRING_CHUNK + 1];`
For all values that are not chunked `< LEJP_STRING_CHUNK`, they are `NULL-terminated` properly

**Comment by lws-team** [comment]
This is intentional... `ctx->npos` says how much is in the chunk of string that was parsed out.

As a convenience, in the common case the string is less than `sizeof(ctx->buf) - 1`, it only emits `LEJPCB_VAL_STR_END`, it also adds the additional NUL there.  Then you can treat it casually for strcmp or atoi or whatever.  Even in the case the STR_END comes after some STR_CHUNK, it's still logical to add the NUL since it is the end of the whole string.  This means the issue title is not quite right, the situation is "lejp does not NUL terminate STR_CHUNK".

When the string won't fit in the lejp buffer, so it is chunked and it's emitting `LEJPCB_VAL_STR_CHUNK`, what's in the ctx->buf ends in the middle of a larger string, by definition.  The larger string has not been terminated yet, so no NUL.  Because it is just a part of a larger string, you anyway can't use it with normal libc NUL-terminated string apis unless you reassemble the whole string.

So the situation is use `ctx->npos` to understand the length of the `VAL_STR_CHUNK` piece.

If that makes some big trouble we can discuss it, but I think it's OK AFAIK.

**Comment by alexeadem** [comment]
I hear you. Why should we add a null character for a string that hasn't terminated yet?

From an usability perspective that prevents me from using  `printf(...`, ` lws_snprintf(...`, l`wsl_notice(...`  directly without checking for` if (reason == LEJPCB_VAL_STR_CHUNK) {` for values `>` sizeof(ctx->buf) - 1 or else Valgrind with of course complain that ctx->buf is undefined.  Or maybe checking to see if it a LEJPCB_VAL_STR_CHUNK is always the safe way to go....

From a consistency perpective, I know for example that the buffer `in` with size `len` in callbacks is never null-terminated so I know not to use any function before setting the size with `len`. In the case of ctx->buf it is terminated only for strings fitting in the buffer...

And last one. If there is room in the buffer to add a null character why not use it? This doesn't prevent me to use something like this
```
                        value = (char *)realloc(value, value_len + ctx->npos + 1);
			memcpy(&(value_len]), ctx->buf, ctx->npos);
			value_len += ctx->npos;
			value[value_len] = 0;
```
to rebuild the chunks and gives me the opportunity to log and print without being worried about valgrind

I'm either way. thanks, Andy!

**Comment by lws-team** [comment]
I also agree it's arguable.

I think I should leave it as it is because I don't see anything in the ECMA standard to rule out `\u0000`, ie, NUL in the string body.

> Any code point may be represented as a hexadecimal escape sequence. The meaning of such a hexadecimal
number is determined by ISO/IEC 10646. If the code point is in the Basic Multilingual Plane (U+0000 through
U+FFFF), then it may be represented as a six-character sequence: a reverse solidus, followed by the
lowercase letter u, followed by four hexadecimal digits that encode the code point.

https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf

... that can only be correctly handled as pointer + length, not with NUL termination., lws has transformed the escapes by then.

They also say

> A conforming JSON text is a sequence of Unicode code points that strictly conforms to the JSON grammar
defined by this specification

With escapes, the JSON would be conformant encoding binary strings that may include NUL.

**Comment by alexeadem** [comment]
sounds good.
