### ISSUE TITLE
check_function_exists doesn‘t work on macOS

### ISSUE THREAD

**Issue by caobug** [warmcat/libwebsockets#2315]
Sorry, I'm here to interrupt again.

When I cross-compile macOS via https://github.com/leetal/ios-cmake, the "check_function_exists" report can find some symbols, but these symbols do not exist. maybe should use "CheckSymbolExists" instead.

https://github.com/libsdl-org/SDL/issues/3467
https://github.com/libgit2/libgit2/pull/5898

https://cmake.org/cmake/help/v3.8/module/CheckFunctionExists.html

```
-- Looking for SSL_CTX_load_verify_file
-- Looking for SSL_CTX_load_verify_file - found
-- Looking for SSL_CTX_load_verify_dir
-- Looking for SSL_CTX_load_verify_dir - found
```
```
-- Looking for clock_gettime
-- Looking for clock_gettime - found
```

For example, I changed `CHECK_FUNCTION_EXISTS(clock_gettime LWS_HAVE_CLOCK_GETTIME)` to `CHECK_FUNCTION_EXISTS(abcdefg LWS_HAVE_CLOCK_GETTIME)`, it still prompts that it can be found
```
-- Looking for abcdefg
-- Looking for abcdefg - found
```

**Comment by lolgear** [comment]
@caobug
Could you check that the solution that I added in [PR](https://github.com/libgit2/libgit2/pull/5898) works?

```cmake
enable_warnings(error)
check_symbol_exists(clock_gettime "sys/header.h" HAVE_CLOCK_TIME_FUNCTION)
IF (HAVE_CLOCK_TIME_FUNCTION)
  # do whatever you want
endif()
disable_warnings(error)
message(FATAL_ERROR)
```

**Comment by lws-team** [comment]
@lolgear enable_warnings() doesn't seem to be a cmake thing, I guess it's a macro from elsewhere in libgit2.

The canonical way to do what you're doing is `set(CMAKE_REQUIRED_FLAGS ${CMAKE_REQUIRED_FLAGS} " -Werror")`

I don't think it will help CHECK_FUNCTION_EXISTS, because a) it seems to not generate any warning to promote, and b) it generates a non-meaningful link-time warning.

```
Determining if the function clock_gettime exists passed with the following output:
Change Dir: /Users/sai/jobs/0-0.0/libwebsockets/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_69710/fast && /opt/Xcode-beta.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_69710.dir/build.make CMakeFiles/cmTC_69710.dir/build
Building C object CMakeFiles/cmTC_69710.dir/CheckFunctionExists.c.o
/usr/bin/clang -DKEYWORD=__inline  -fembed-bitcode -DCHECK_FUNCTION_EXISTS=clock_gettime -arch arm64 -isysroot /opt/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.2.sdk   -o CMakeFiles/cmTC_69710.dir/CheckFunctionExists.c.o   -c /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_69710
/usr/local/Cellar/cmake/3.16.4/bin/cmake -E cmake_link_script CMakeFiles/cmTC_69710.dir/link.txt --verbose=1
/usr/bin/clang -fembed-bitcode -DCHECK_FUNCTION_EXISTS=clock_gettime -arch arm64 -isysroot /opt/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.2.sdk -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_69710.dir/CheckFunctionExists.c.o  -o cmTC_69710 
ld: warning: -headerpad_max_install_names is ignored when used with -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES)
```

@caobug  If changing some things to `CHECK_SYMBOL_EXIST` helps, please send or paste a patch with what you need.  I think it's going to be difficult to change all instances in one step, because the include path may differ by platform and things are going to break on one platform or another.

**Comment by caobug** [comment]
I did some tests.

```
CHECK_FUNCTION_EXISTS(clock_gettime22222 LWS_HAVE_CLOCK_GETTIME)

-- Looking for clock_gettime22222
-- Looking for clock_gettime22222 - found
```
```
CHECK_SYMBOL_EXISTS(clock_gettime22222 time.h LWS_HAVE_CLOCK_GETTIME)

-- Looking for clock_gettime22222
-- Looking for clock_gettime22222 - not found
```
```
CHECK_SYMBOL_EXISTS(clock_gettime time.h LWS_HAVE_CLOCK_GETTIME)

-- Looking for clock_gettime
-- Looking for clock_gettime - found
```

However, this function "clock_gettime" only works on macos 10.12. When I set `CMAKE_OSX_DEPLOYMENT_TARGET` to 10.10, it prompts that it can be found. Therefore, `CHECK_SYMBOL_EXISTS` and `CHECK_FUNCTION_EXISTS` are not compatible with `CMAKE_OSX_DEPLOYMENT_TARGET`.

**Comment by lws-team** [comment]
... hm... how about you are building cross without enforcing disabling cmake looking at your build system includes?  That is definitely going to break the empirical api detection because it will look at your build machine /usr/include by default... are you using the provided cmake toolchain file on this one?

**Comment by caobug** [comment]
Yes, I'm using this toolchain. regarding `CHECK_FUNCTION_EXISTS` not working, I think I found a new solution(https://github.com/leetal/ios-cmake/commit/9966ec67cbddb9788a32fba2b9d89640e54b091b). although this method works, I personally recommend `CHECK_SYMBOL_EXISTS` as an alternative. if you have planned changes, I can help with testing to verify that `CHECK_SYMBOL_EXISTS` can work normally on macOS/iOS/Windows/Android.

About the function `lock_gettime` is always found, I may need to install a lower version of the Apple SDK or determine the system version in code, or find other solutions. the current simple method is to delete this check through "sed". however, this is not elegant.

**Comment by lws-team** [comment]
I already build all those in CI.  I can see the rest of my Sunday disappearing on iteratively fixing everything that breaks, and I have other things to do.  So if you have some specific ones you need, send a patch, otherwise it is going to have to wait.

> However, this function "clock_gettime" only works on macos 10.12. When I set CMAKE_OSX_DEPLOYMENT_TARGET to 10.10, it prompts that it can be found.

CMakeLists.txt, or unix-misc.c are places that can contain this knowledge... again if you want it solved put the solution in one of those and send a patch.

**Comment by lws-team** [comment]
Thanks for the patch, it's pushed now.
