### ISSUE TITLE
[request] libuv + lws websocket client example

### ISSUE THREAD

**Issue by naveenvhegde** [warmcat/libwebsockets#2341]
is there any simple websocket client example with libuv ? i referred to http-server-eventlib-foreign and binance example. tried to assemble and run. 

it does not seem to work. it stops at websocket client connecting callback. but with lws event loop. binance example working fine.

**Comment by lws-team** [comment]
libuv + client works fine, the problem is going to be whatever changes you hacked on.

There is an example minimal-http-server-eventlib-foreign showing any foreign loop, mainly for serving but that now also spawns a client connection.

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib-foreign/minimal-http-server-eventlib-foreign.c#n134
