### ISSUE TITLE
Handling HTTP data during websocket negotiation?

### ISSUE THREAD

**Issue by youmych** [warmcat/libwebsockets#2348]
Hello, this is not an issue, more a question.

The `minimal-ws-client` connects to my own server. The server returns an error, for example:

```
HTTP/1.1 400 Bad request
Content-Type: application/json

{ "error": 42, "message":  "I always thought something was fundamentally wrong with the universe." }
```
In the case the `callback_minimal` is called with LWS_CALLBACK_ESTABLISHED_CLIENT_HTTP and in logs I'd watched
```
[2021/07/14 13:07:19:4705] W: lws_client_handshake: got bad HTTP response '400'
```
I can access the HTTP code and headers in the callback. 
But how to get the data from the reply? Is there a way to get them?

**Comment by lws-team** [comment]
I think for normal http, you will get the body coming.

But the errors you mention are specific to ws upgrade, it understand the context of the transaction in the sense it was trying to upgrade to ws and the server said "no".  So it takes that not only as the end of the http transaction, but the end of the connection (since it would have upgraded away from http) and the end of the ws upgrade attempt and closes the connection and fails.
