### ISSUE TITLE
lws_spa_create() without knowing names of parameters

### ISSUE THREAD

**Issue by rexx-org** [warmcat/libwebsockets#2353]
I've been using lws for a number of years; wrapping lws to enable it to be used in the Rexx programming language. I've mainly used it for websocket capabilities and it works very well.

I now want to expand the httpd capabilities and in particular the ability to process form data.

I've looked at all the minimal-http-server-form examples that use the spa interfaces, but they all assume you know the names of the form fields you are expecting from the client.

How does one use these interfaces in a generic http server where you accept form data from multiple forms without knowing what the names of the form fields will be?

**Comment by lws-team** [comment]
Handling POST body, and lws_spa are two different layers, you always have access to the raw POST body to handle how you want, with or without lws_spa.  So it's optional.  But the mime parser and file upload stuff are not that easy to safely and correctly do in user code casually without it.

lws_spa was done to provide an easy way users can handle parsing forms emitted in embedded devices, and deal with mime handling for file upload; it's aimed at eg router settings page and browser firmware update.  So it has some assumptions that the logical things in the form and the logical things the handler wants to process in code are aligned.

However internally, it sees everything (and since you can have it use lwsac, it can store everything you have memory for) and just filters on a list the caller provided of named form items it is interested in.

https://libwebsockets.org/git/libwebsockets/tree/lib/roles/http/server/lws-spa.c#n514

At the moment it indexes the responses in an array that's indexed the same as the incoming list of names.  A patch that enhanced it to also do what you want want would need to

- allow the incoming array of `param_names` at creation time to be NULL,
- accept everything if it's NULL, and
- add an api to query the parameters after parsing by parameter name string.

The indexing of recovered params could be improved to either be done as a linked-list in the lwsac, so there's no restriction on how many, or continue to follow count_params to allocate the results even if the incoming param_names is NULL

https://libwebsockets.org/git/libwebsockets/tree/lib/roles/http/server/lws-spa.c#n591-597

**Comment by rexx-org** [comment]
Thanks for the explanation Andy.  I'll have a look at the lws-spa.c code and see if I can add a patch. It won't happen soon; too many other higher priorities. I have a workaround for my needs at the moment, but it is a bit limited.
