### ISSUE TITLE
lws_rx_flow_control infinite loop

### ISSUE THREAD

**Issue by caobug** [warmcat/libwebsockets#2360]
Hello, I received a lot of data in `LWS_CALLBACK_CLIENT_RECEIVE`, but because I cannot process all the data at once, I called `lws_rx_flow_control(wsi, 1)` on the way to suspend the acceptance, and call `lws_rx_flow_control(wsi, 0)` at the appropriate time to resume the acceptance . This sometimes works well, but more often it will fall into an infinite loop, and the CPU will occupy 100%.

I used the tool to detect that it has been trying to store data in the cache. Usually when I stop monitoring data, `uv_poll_io` should not continue to work.

I always think `lws_rx_flow_control` is equivalent to `uv_poll_stop` and `uv_poll_start`, but it is not.

Is this expected?

CPU 100%:
<img width="379" alt="QQ20210724-022726@2x" src="https://user-images.githubusercontent.com/7737673/126825586-53d840db-df97-411e-893b-d0d8774669a4.png">

**Comment by lws-team** [comment]
Someone noticed they could make this happen on libwebsockets.org recently using the mirror protocol example, after I updated it to recent main. I added a patch that reduces the spin behaviour to closing the affected connection as a workaround, it sounds like it can be the same issue

https://libwebsockets.org/git/libwebsockets/commit/minimal-examples/ws-client/minimal-ws-client-tx?id=c11311ff5a00f0db013059da907bdb688e21e518

> I always think lws_rx_flow_control is equivalent to uv_poll_stop and uv_poll_start, but it is not.

It is, but if you only do this, then you only stop the next read, there is the issue of the pending data that was already read into lws but not yet given to the user code.  So lws has to take extra steps to stash read-but-undelivered rx so that when you apply flow control, no more data is delivered at all until you unapply it.  There is some flaw in the consumption logic that wants to spin later if additionally, there is more packets waiting to be read at the tls layer.  If you are interested to look at it, it's in the code the above patch modifies to break the spin as a workaround.

**Comment by caobug** [comment]
Thank you for your reply, this is indeed the same question.

It is indeed a good way to discard the existing connection via `LWS_HPI_RET_PLEASE_CLOSE_ME` after 10 retries. However,  I cannot tell whether this connection has gone wrong or is normal.  If it is shut down normally, I will ignore it, but if it shuts down accidentally, I will have via `lws_client_connect_via_info` to reconnect.

Yesterday I modified the code to: `lws_rx_flow_control(wsi, LWS_RXFLOW_REASON_APPLIES_DISABLE);` and it seems to work.

**Comment by lws-team** [comment]
Spring cleaning old issues
