### ISSUE TITLE
Exactly the same project doesn't send data to server properly on a new Archlinux installation

### ISSUE THREAD

**Issue by sudoLife** [warmcat/libwebsockets#2372]
I was developing a project on my Arch install. Everything was fine. 

After I bought a new SSD and installed Arch on it, the project still compiles fine. However, it manages to send data like once in a minute or even slower. It seems as if most of the time the server is not "writeable". There are no errors as far as I can see.

It gets to this place:

```
    lws_start_foreach_llp(SessionData **, ppss, vhd->pss_list)
    {
        lws_callback_on_writable((*ppss)->wsi);
        printf("\t\tAdding callback\n");
    }
    lws_end_foreach_llp(ppss, pss_list);
```
But callback_minimal gets called very rarely => no data is being sent.

The binary that I compiled on the previous system works fine & fast on the new system as well. Library versions are the same (latest) on both systems.

Cmake is newer, but it produces exactly the same Makefile, and make version is the same.

The problem is driving me insane, and I would really appreciate any tips on how to catch the cause.

**Comment by lws-team** [comment]
> However, it manages to send data like once in a minute or even slower. It seems as if most of the time the server is not "writeable".

What does the process do during these pauses?  Stay in the event loop wait?  It's the default event loop wait or an event library?

Are there other threads involved?

**Comment by sudoLife** [comment]
> What does the process do during these pauses? Stay in the event loop wait? It's the default event loop wait or an event library?
> 
> Are there other threads involved?

If I understand your question correctly, the program continues executing the code part I showed above (adding callbacks) and moves on. The library does not output any log messages during that time.

main.cpp simply calls function SendData() in server.cpp .

Here are two files that I think could help you.
https://hastebin.com/azusoweqeg.cpp - server.cpp (where SendData() is defined)
https://hastebin.com/saxusomohe.cpp - protocol.h (where the callback_minimal is defined).

**Comment by lws-team** [comment]
> Here are two files that I think could help you.

None of this is going to help me :-)  You are asking me to help you.

Your pastes seem to show you're putting lws in one thread and then presumably calling SendData(), which uses lws apis, from another.

You can't do that if so, lws is not threadsafe.  You can only call its apis (except lws_cancel_service()) from the same thread lws event loop uses.

**Comment by sudoLife** [comment]
> > Here are two files that I think could help you.
> 
> None of this is going to help me :-) You are asking me to help you.
> 
> Your pastes seem to show you're putting lws in one thread and then presumably calling SendData(), which uses lws apis, from another.
> 
> You can't do that if so, lws is not threadsafe. You can only call its apis (except lws_cancel_service()) from the same thread lws event loop uses.

I am sorry if I offended you. 

So you are saying I should rewrite the thing? I'd still like to find out more. It worked previously for some inexplicable reason, so it could be the problem is somewhere else. Maybe it's a bug that's going to bite both of us in the end.

Would you like anything else from me to investigate the issue? I could provide the whole code, though i have to change it first to avoid disclosing my company's project.

**Comment by lws-team** [comment]
...

> So you are saying I should rewrite the thing?

You can do what you like... it's the same to me either way.

If you want it to work, follow the advice above.

**Comment by sudoLife** [comment]
Quick question. It is said on the lws website that `lws_callback_on_writable()` is thread-safe. Is `lws_start_foreach_llp` safe too?

If so, I see no reason so far why my code is not thread-safe, as the only thing done in another thread is adding those callbacks.

**Comment by lws-team** [comment]
>>  You can only call its apis (except lws_cancel_service()) from the same thread lws event loop uses.

>  It is said on the lws website that lws_callback_on_writable() is thread-safe.

It used to be, but as lws supported more platforms and event libs, what that actually calls through to in order to change the fd wait became itself not threadsafe.  On some BSDs including OSX, you cannot change the fd wait while in poll() either, when it exits the poll() wait it overwrites the .event field with what it originally entered the wait with, wiping out your changes made from the other thread.  So for several years now the only recommended way is via lws_cancel_service().  Someone pointed out a few days ago there's some cruft in an old README, I will remove it.

>  I see no reason so far why my code is not thread-safe

... I get it you don't want to change your code, but it doesn't work and even if you hack it to work (eg, by adding an lws_cancel_service() after the writeable request to force the wait to wake) it is non-portable, and will crash if built on other platforms.  Shouldn't you just take the author's word for it?

**Comment by sudoLife** [comment]
Thank you for the thorough explanation. I believe you, and very value your time and feedback.

I do agree that I have to remake this part of the project. I need some way of passing data from another parts of the project.

Say, when some calculation is ready and I now which protocol I need to send it through, I call some Send() and it does...what? This is the part I have not come up with. I would greatly appreciate a pointer here. 

Best case scenario: I send the data and immediately go on calculating.

**Comment by lws-team** [comment]
The best approach is just don't have other threads.  Sometimes the thread is doing something that really needs it, but most of the code I see doing this, the stuff in the other thread can be folded to directly use the lws event loop thread.  Then this issue doesn't even exist, you can call lws apis directly everywhere without locking or other otherhead, portably and reliably.

Otherwise, the approach is make a struct or memory region that is only accessed when locked under your app locking.

Lock it, prepare it with the information you want the lws thread to deal with, a list of wsi that need writing to, or the info struct for client connections that need creating or whatever.  Then unlock the shared area and call lws_cancel_service() to notify the lws thread something to do.

The lws thread will call LWS_CALLBACK_EVENT_WAIT_CANCELLED in your protocol, from there you can lock the shared area, look at what it wants, and do it then unlock, in this case call `lws_callback_on_writable()`, and in WRITEABLE, get the pending data from the shared thing too.

**Comment by sudoLife** [comment]
> The best approach is just don't have other threads. Sometimes the thread is doing something that really needs it, but most of the code I see doing this, the stuff in the other thread can be folded to directly use the lws event loop thread. 

I keep flashing to the seemingly impossible to escape service loop:
```
while (n >= 0 && !interrupted)
    n = lws_service(context, 0);
```
I have gone through the minimal examples, and they all show the whole logic implemented right in the callback. What if there's a lot more going on? How can I start lws in the same thread as other calculations without being stuck in the loop?

I understand that this must be obvious for you as the creator (and getting on your nerves), but it's not for me.

**Comment by lws-team** [comment]
These are not questions about lws, but about the science of "singlethreaded event loops" in general.  lws came along a long time after these were established as a good way to implement things that can work on them.  Chromium browser uses libevent inside https://libevent.org/, node.js uses libuv https://libuv.org/, systemd uses sdevent, openwrt uses uloop, all of these event libs are also supported directly by lws instead of the default poll loop.

By default most of the examples show the default platform loop that lws arranges for you, but you can tell it to use an explicit foreign loop in any of the supported libraries, and it will cooperate with that without the while loop the default one needs.  See

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib-foreign

If you can combine loops and how to do it depend on exactly what you are doing in the other pieces.  If the other pieces decide to do things because of file or socket descriptor events (and on linux, things like input devices or sound are file descriptors), or things that can become file or socket descriptor events, they should be able to be combined into a single loop.  Then, there is no need for more threads or the related locking.

If the other pieces operate in a foreign, interrupt context world or somesuch, they can't be directly combined and have to be synchronized somehow.
