### ISSUE TITLE
"Minimal" examples are too complicated

### ISSUE THREAD

**Issue by Zipdox** [warmcat/libwebsockets#2373]
I think the minimal examples are still way too complicated for newcomers, and greatly hinder the understanding of how the library works. There's absolutely no reason to use multithreading and ringbuffers in minimal-ws-client-tx, and still call it "minimal".

A minimal example should be the absolute minimum amount of code to perform a simple task. Adding complication hinders people from understanding the basic concepts of the library.

**Comment by lws-team** [comment]
You are offering to go through the 100 or so examples and make them even more minimal?

Great... perhaps if you do a good job, a particularly intelligent dog can learn to use it.

**Comment by Zipdox** [comment]
You didn't address my point. Of course there is no problem with having sophisticated examples that show how to do certain things with a library. But if this goes at the cost of basic examples that demonstrate basic usage and concepts, it becomes a problem. The amount of examples available doesn't making figuring things out any easier if they're all too sophisticated.

Do you understand where I'm coming from?

**Comment by lws-team** [comment]
Yeah, you observed and described some perceived deficit.

If you're doing that because you're going to roll up your sleeves and contribute a solution for the thing that's bothering you, that's awesome.  I will be delighted to get your patches so that others can benefit from it.  Particularly because in this case, the work is only being done so that others can benefit from it, not yourself... it's really in the spirit of giving back to FOSS and to be applauded.

If not, it boils down to an invitation to stop what I am doing and do work on something they think is important.  Then I ask myself, a) are they paying me?  If we are being paid by the same company, hit me up on my company email and we can discuss what the background is for this and what resources you will pitch in.  b) do they have any patches in their hands or just trying to be generous with my time instead of theirs?  c) in the big list of things I would like to do but have to just pick one to do at a time, do I anyway want to block everything else to work on that one thing right now.

Given the massive amount of time those examples took to create, I am not motivated to revisit them atm.

But, patches are welcome.
