### ISSUE TITLE
lws_service ignoring timeout

### ISSUE THREAD

**Issue by alien999999999** [warmcat/libwebsockets#2376]
I read that lws_service is ignoring timeout, but i kinda want it to relatively fast on interrupts.

Can i just use lws_service_cancel inside a interrupt handler? i doubt that?

The websockets are part of a bigger application, and will be in a seperate thread, and often will not be not active for long periods, in which case this thread will hang when i want it to exit...

**Comment by lws-team** [comment]
Lws supports a lot of event libraries now, and they do not return at all once you start the loop.  So this just aligns the behaviour of the default loop with the event library loops,

> Can i just use lws_service_cancel inside a interrupt handler? i doubt that?

"interrupt handler" means literally a handler in interrupt context?  You can't use any libc stuff in there, it's not a restriction for lws.  Naturally you can't call lws stuff if you can't even call printf yourself there.

> The websockets are part of a bigger application, and will be in a seperate thread, and often will not be not active for long periods, in which case this thread will hang when i want it to exit...

Yes if lws is idle, it will sleep.

You can wake it up with lws_cancel_service(), even from another thread, just not from interrupt context.

**Comment by alien999999999** [comment]
right, so i just need to handle the interrupting in a different thread, then set the ending bool to true and cancel the service.

thanks for the very quick response :-)

**Comment by alien999999999** [comment]
wait, how do i know that i'm not canceling a busy request? when using cancel_service?

**Comment by lws-team** [comment]
There are a few things mixed together.

 - how to interact with interrupt context at all?  Use a platform-specific scheme like a semaphore to get the event out of interrupt context, so you can handle it from a normal user thread.

 - how to wake the lws thread if it is idle?  lws_cancel_service()

 - how to understand we woke because of an event passed through interrupt context?  lws_cancel_service() just wakes the wait forcibly, by itself it doesn't cause the context to exit the loop or destroy itself.  If you don't handle it, it will just reenter the wait until something else happens.  `LWS_CALLBACK_EVENT_WAIT_CANCELLED` callabck reason is broadcast on wake after lws_cancel_service(), you can handle that and look in there to see if you should exit.

**Comment by lws-team** [comment]
There's some more background here you may or may not find interesting

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.event-loops-intro.md?h=main

**Comment by alien999999999** [comment]
thanks for the detailed and fast responses

**Comment by alien999999999** [comment]
one more small question on this topic, i see that lws_service() in the minimal examples seems to need to have a higher-than-zero return value? in the api there is no documentation on the return value of this. which kind of cases have lws_service return zero (or less?)

Is that for ending (allthough i was planning to use an external variable for ending), or unrecoverable errors, or just when cancel is called?

**Comment by lws-team** [comment]
No... that there is a visible loop at all is just a feature of the default event loop.

Every other event library has its own loop runner inside a ...run() type api in the event library.

You should just look at the while (...) lws_service_...(); loop as a hack for the default loop, and it's all over the examples because for almost all of them, I don't want to introduce a dependency on an event library.

Despite the name lws_cancel_service() does not break that loop, it just forces the wait to wake (and then continue the event loop if no other action taken).

**Comment by alien999999999** [comment]
ah, no, that's not what i meant...

I had been looking at the examples, (because i have my own event loop), i'm just wondering what i should do about the return value of the lws_service() function, the examples check the return value and break the loop if the return value is zero or less?

specifically, if the return value is zero because ending is requested through that callback; i do need to exit and break the loop. but if it is zero because errors happened, i need to keep the loop, because i would want to retry after x time if something was preventing it to work on the system...

**Comment by lws-team** [comment]
If you're using an event library loop you don't need to call lws_service() at all.  Just create the lws_context using the foreign loop flow from inside the foreign event loop, and return to the foreign loop.  lws internal callbacks will get automagically called from your foreign event loop for the rest.

**Comment by alien999999999** [comment]
i'm not using any event library... so i think i need to call the lws_service() function in a while loop (like the examples), but i'm wondering on it's return value; i'm assuming it returns zero or less; when something is wrong on the OS level. what would be the best way for me to handle this? Should i destroy the context and recreate the context if lws_service() fails? (as a retry of sorts)?

also the lws_callback_function, i see all examples returning zero, should i in some cases need to return something else than zero?

**Comment by lws-team** [comment]
You should have a look at option 3 in the doc mentioned above then, especially the example.

**Comment by alien999999999** [comment]
Since there was threading already, i had kinda given up and went with option 4, do you think the following code is ok for handling event_service() failures?
