### ISSUE TITLE
certificate chain

### ISSUE THREAD

**Issue by juanjo75es** [warmcat/libwebsockets#239]
When I call a websockets server implemented with libwebsockets form an android App and using SSL, the SSL handshake fails. It seems the cause is that Android doesn't have the intermediate certificates for my CA. When accessing an HTTP server, the problem is solved making the server to send also the intermediate certificates. Is there any way to make libwebsockets send the certificate chain including intermediate certificates?

**Comment by warmcat** [comment]
This seems to be the guy

https://www.openssl.org/docs/ssl/SSL_CTX_add_extra_chain_cert.html

If you can arrive at some working code by patching the related lws pieces I'll be happy to look at it.

**Comment by DYefimov** [comment]
According to ssl.c:
> /* openssl init for server sockets */
> 
> /* set the local certificate from CertFile */
> n = SSL_CTX_use_certificate_chain_file(context->ssl_ctx, info->ssl_cert_filepath);

libwebsockets using SSL_CTX_use_certificate_chain_file to set server certificate.

According to http://linux.die.net/man/3/ssl_ctx_use_certificate_chain_file
> "SSL_CTX_use_certificate_chain_file() loads a certificate chain from file into ctx. The certificates  must be in PEM format and must be sorted starting with the subject's certificate (actual client or server > certificate), followed by intermediate CA certificates if applicable, and ending at the highest level >(root) CA . There is no corresponding function working on a single SSL object."

So I assume you can just attach a chain after your subject certificate.

Am I misunderstood this?
Seems it fixed similar problem with my Android App handshake.
Also, firefox, before this fix, treated my certificate as untrusted.

**Comment by juanjo75es** [comment]
I decided to implement a TrustManager wrapper in the client and pass it to SSLContext.init. The wrapper then can trust any authority that you want. But I will explore both alternatives for the final version. DYefimov, could I know at what place you added the call to this function? I think you should pass it to warmcat to be added to the release version.
Thanks

**Comment by DYefimov** [comment]
Actually it's already in there.
Consider this:
https://github.com/warmcat/libwebsockets/blob/master/lib/ssl.c#L176

**Comment by warmcat** [comment]
Yes you usually get intermediate certs along with your actual cert.  Only the guy who signed the intermediate cert is preinstalled in os or browsers as trusted.  So you must send the intermediate cert as well and let the other end see A signed B and then B signed C, so if he trusts A he should accept C.

**Comment by DYefimov** [comment]
Sorry, It's a bit off-topic, but..
For completeness sake, I had to notice:
Https request for libwebsockets server completes successfully now.
But on wss upgrade stage, our android phonegap based app failed to accept valid chain of certificates. It just drops connection without any prior notice.
Latest phonegap (cordova) builds rely on webview, so I assume the problem is in the implementation of wss upgrade stage in there.
Browser version works just fine.
For now we ended up packing chrome into our app, which solves our problem.
Pros: we don't have to rely on dozens of possible variants of webview
Cons: app size 3Mb=>20Mb

In first place back then, I was a bit confused, why cordova decided to bring webview onto the stage? I chose phonegap, to be independent of target device. If I knew that later they will bring webview, maybe I've been considering about native development.

**Comment by warmcat** [comment]
Sorry I don't know anything about these frameworks.  But I'm glad to hear lws is working as it's supposed to on the browser.

**Comment by rauldenia** [comment]
Hello.
I have a client in android implement with AndroidAsync.
In the other side, I have a server implement with libwebsockets.
When I use android emulator, all works well, but when I test with the real mobile, something wrong pass.
The client and the server continues running but nothing happens. When the server sends the certificate, all finish (I know that because I capture the packets)

Any idea?

Thanks
