### ISSUE TITLE
How to build libwebsocket for iOS platform?

### ISSUE THREAD

**Issue by ziaurrehman** [warmcat/libwebsockets#240]
Hi,
I am unable to build libwebsocket for iOS platform.
I use 
cmake -DCMAKE_TOOLCHAIN_FILE=/Users/Apple/Downloads/cmake-ios-master/Toolchain/iOS-Device.cmake ../

/////OUTPUT START

-- CMAKE_TOOLCHAIN_FILE='/Users/Apple/Downloads/cmake-ios-master/Toolchain/iOS-Device.cmake'
fatal: Not a git repository (or any of the parent directories): .git
Git commit hash: 
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.1/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.1/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-3.1/Modules/FindZLIB.cmake:110 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:467 (find_package)

-- Configuring incomplete, errors occurred!

////OUTPUT END

It would be good if i get step to build it.

Thanks in advance.

**Comment by warmcat** [comment]
Sorry I don't use any Apple anything.  However thanks to Joakim we do build-test lws against OSX at least.

From the look of it if you are building cross you'll need your cross zlib headers and cross zlib library somewhere, or maybe try disabling building extensions in cmake.

**Comment by JoakimSoderberg** [comment]
You need zlib for your cross compilation environment as @warmcat says. The error is because it's not finding it... I haven't tested to cross compile for IOS myself either.

Have you tried this project, from you errors it looks like that's what you're using?:
https://code.google.com/p/ios-cmake/wiki/HowTo

As it says on that page:

> NOTE: Since this toolchain by default builds both arm6 and arm7 fat libraries and applications, you need to use the Xcode generator. Makefiles currently do not work.

**Comment by foocraft** [comment]
What's the status on this right now?

**Comment by JoakimSoderberg** [comment]
@foocraft Are you getting the same error or what? The problem is clearly that zlib cannot be found. Since it is a cross compilation some extra paths might be needed so that cmake can find it, these are specified in the toolchain file (not a part of libwebsockets in this case).

This seems to be a related issue which might help: http://stackoverflow.com/questions/14171740/cmake-with-ios-toolchain-cant-find-threads

Note that I have not attempted to do this cross compilation for ios myself...
