### ISSUE TITLE
what's wrong with the benchmark here? is libwebsockets so bad?

### ISSUE THREAD

**Issue by superdolt** [warmcat/libwebsockets#2419]
https://www.researchgate.net/publication/348993267_An_Analysis_of_the_Performance_of_Websockets_in_Various_Programming_Languages_and_Libraries

what's wrong with the benchmark here? is libwebsockets so bad?

**Comment by lws-team** [comment]
> what's wrong with the benchmark here? is libwebsockets so bad?

The guy (a student it seems) also finds Go and Python are so slow on his tests due to using singlethreaded event loop.

That's an architectural decision that has advantages and disadvantages, the author seems to think if its not using all his threads, its trash.

Actually lws does have LWS_MAX_SMP mode where it can use n threads for serving.  But it seems the guy didn't look into that either.
