### ISSUE TITLE
An HTTP connection gets dropped after a ~360 seconds of work.

### ISSUE THREAD

**Issue by ezlo-sergs** [warmcat/libwebsockets#2426]
Hello!

We use a libwebsockets library as an http server in our devices. A client establishes an http connection and after a ~360 seconds it gets dropped.

Looking at the code we've found that the lws library iterates over ah list (ah_list) and closes ahs which exceeded this ~360 seconds bound.

It looks like a client connection gets in this list that's why the lws closes it after the ~360 seconds timeout...

Client establish an http connection with a single PUT request with a "forever" (more than 360 seconds)  message body, may it be a reason of the issue? Should the client split its big PUT request to several small requests to handle this issue or there can be some other way?

**Comment by lws-team** [comment]
The ah is detachable from the http connection, you can explicitly detach it

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-http.h#n876-884

that will remove your wsi from this ah blocking tracking and it should be able to go on as long as you like then.

You'll want to process or stash any headers you care about first, because they'll be gone after you call this.

**Comment by ezlo-sergs** [comment]
Thanks for the answer!

Sorry, forgot to say that we use a 3.1.0 version of the lws library.... It's kinda hard and will take a lot of time to update the lws library and we are requested to go with this 3.1.0 library as much as possible....

It looks like there's no such function available on a 3.1.0 version of the lws library, but this function is a wrapper for a **lws_header_table_detach** one, is it safe to use it (it looks like it's "private" function....)?

**Comment by lws-team** [comment]
Probably... I don't support older versions.
