### ISSUE TITLE
lws_tls_cert_updated doesn't work for mem_cert + mem_privkey mode

### ISSUE THREAD

**Issue by pavelxdd** [warmcat/libwebsockets#2431]
If a lws context was initialized with server_ssl_cert_mem + server_ssl_private_key_mem, lws_tls_cert_updated function doesn't work. Internally it only applies the new cert if a certpath and keypath were set before.

**Comment by lws-team** [comment]
I assume we're talking about this

https://libwebsockets.org/git/libwebsockets/tree/lib/tls/tls-network.c?h=main#n184

would you like to propose a patch?

**Comment by pavelxdd** [comment]
I failed to compile the main branch, I get this error:

````
libwebsockets/lib/core/context.c:786:2: error: expected expression
        lwsl_notice("LWS: %s, %s%s\n", library_version, opts_str, s);
        ^
libwebsockets/include/libwebsockets/lws-logs.h:273:26: note: expanded from macro 'lwsl_notice'
#define lwsl_notice(...) do {} while(0)
                         ^
1 error generated.
````

I use arm-linux-gnueabihf-gcc 11.2.0 with these build flags:
````
-DBUILD_SHARED_LIBS=OFF
-DDISABLE_WERROR=ON
-DLWS_WITH_STATIC=ON
-DLWS_WITH_SHARED=OFF
-DLWS_WITH_SSL=ON
-DLWS_WITH_LIBEV=ON
-DLWS_WITH_EVLIB_PLUGINS=OFF
-DLWS_WITH_ZLIB=ON
-DLWS_WITH_BUNDLED_ZLIB=OFF
-DLWS_IPV6=ON
-DLWS_WITHOUT_CLIENT=ON
-DLWS_WITHOUT_TESTAPPS=ON
-DLWS_WITHOUT_EXTENSIONS=OFF
-DLWS_WITHOUT_BUILTIN_GETIFADDRS=ON
-DLWS_WITH_HTTP_BASIC_AUTH=OFF
-DLWS_WITH_HTTP_STREAM_COMPRESSION=ON
-DLWS_WITH_NO_LOGS=ON
-DLWS_WITH_DIR=OFF
-DLWS_WITH_LEJP_CONF=OFF
-DLWS_WITH_JOSE=ON
-DLWS_WITH_LWSAC=OFF
-DLWS_WITH_EXPORT_LWSTARGETS=OFF
-DLWS_WITH_SEQUENCER=OFF
-DLWS_WITH_UDP=OFF
-DLWS_WITH_CONMON=OFF
-DLWS_LOGS_TIMESTAMP=OFF
-DLWS_LOG_TAG_LIFECYCLE=OFF
-DLWS_HAVE_LIBCAP=OFF
````

Anyway, I tried to do some tests on v4.2.2, would this be a proper patch? I can't see a reason why there should be a comparison with `tls.alloc_cert_path` and `tls.key_path`

---

````
diff --git a/lib/tls/tls-network.c b/lib/tls/tls-network.c
index b2038d537..be5549f56 100644
--- a/lib/tls/tls-network.c
+++ b/lib/tls/tls-network.c
@@ -180,17 +180,9 @@ lws_tls_cert_updated(struct lws_context *context, const char *certpath,
 
 	lws_start_foreach_ll(struct lws_vhost *, v, context->vhost_list) {
 		wsi.a.vhost = v; /* not a real bound wsi */
-		if (v->tls.alloc_cert_path && v->tls.key_path &&
-		    !strcmp(v->tls.alloc_cert_path, certpath) &&
-		    !strcmp(v->tls.key_path, keypath)) {
-			lws_tls_server_certs_load(v, &wsi, certpath, keypath,
-						  mem_cert, len_mem_cert,
-						  mem_privkey, len_mem_privkey);
-
-			if (v->tls.skipped_certs)
-				lwsl_notice("%s: vhost %s: cert unset\n",
-					    __func__, v->name);
-		}
+		lws_tls_server_certs_load(v, &wsi, certpath, keypath,
+								  mem_cert, len_mem_cert,
+								  mem_privkey, len_mem_privkey);
 	} lws_end_foreach_ll(v, vhost_next);
 
 	return 0;

````

**Comment by lws-team** [comment]
The reason it is like it is, is because you may have many vhosts being served, some of which used that cert and some of which used others.  For example, there are a few vhosts on libwebsockets.org that use the cert for that, and the same server instance has vhosts for warmcat.com, which use those certificates.

The idea of this api is to annouce you are rotating a specific cert, and all vhosts using that cert can take action about it.  The filepath is the obvious way to differentiate between vhosts that need to care and need to ignore the cert rotation, if there is no vhost, there will need to be a different way for vhosts to figure out if they should take the new cert or not.  Just assuming that there is only one vhost and one cert flying around is not going to cut it.

**Comment by pavelxdd** [comment]
Okay, I'll stick with cert and keys filepaths for now, not going to use mem_cert and mem_privkey.
