### ISSUE TITLE
lws_get_peer_addresses() is broken for client-side connection with built-in IPV6 support

### ISSUE THREAD

**Issue by stv0g** [warmcat/libwebsockets#2433]
`lws_get_peer_addresses()` uses the statement `LWS_IPV6_ENABLED(wsi->a.vhost)` to check if the connection is IPv6 enabled.
However the vhost part `wsi->a.vhost` is a nullptr for a client-side connection and therefore causes a segfault.

See:
https://github.com/warmcat/libwebsockets/blob/9975de3445b9cfff6716af5b85e9fe70b01f9683/lib/core-net/network.c#L169

**Comment by stv0g** [comment]
Possibly related to #1713

**Comment by lws-team** [comment]
> wsi->a.vhost is a nullptr for a client-side connection

... that does not actually follow, you can set the vhost to bind to in the client connection info.  If NULL, it ought to pick one for you and set it to that.

What kind of client connection is it (h1, ws etc)?

**Comment by lws-team** [comment]
Does this help?

https://libwebsockets.org/git/libwebsockets/commit?id=b66bd74aba318dc8e2bf5287d13087ccd5845ae6

**Comment by stv0g** [comment]
Yes, this indeed solves my issue. Thanks a lot.

I fixed the issue by switching to lws_peer_simple() which does not touch vhost.

**Comment by lws-team** [comment]
Thanks... generally, anything that wants tls must bind to a vhost to bind to the SSL_CTX, for both client and server.  So although you can dodge the bug in your case by avoiding other things that might dereference the vhost, most use cases want tls nowadays so that wouldn't be enough.  The patch is on main and should solve the root-cause.
