### ISSUE TITLE
LWS cannot detect if a client closes connection for HTTP SSE

### ISSUE THREAD

**Issue by barbarost** [warmcat/libwebsockets#2455]
Hi,

I'm trying minimal examples `lws-minimal-http-server-sse` and `lws-minimal-http-server-sse-ring` with LWS 4.3.0 and if the client closes the connection it cannot be detected by LWS.

Per my debugging, `wsi` stays in `LRS_DOING_TRANSACTION` state after header is sent for HTTP SSE connection and it cannot handle connection closure in this state. If I disable setting `wsi` state to `LRS_DOING_TRANSACTION`, it seems as it is working OK, but of course I'm sure that's not the correct way to fix this issue.

Thanks.

**Comment by lws-team** [comment]
> Per my debugging, wsi stays in LRS_DOING_TRANSACTION

Right...  basically SSE is a hack on http where a single transaction becomes immortal... it should stay in that state, so it doesn't start trying to look in the payload for headers for a new transaction in the way of http/1.1 pipelining.

The problem is coming because when the client goes, instead of signalling OOB HUP event on the socket, some platforms make that visible by jamming POLLIN on and wait for us to read a zero-length result on the socket, to understand that it is gone.  But DOING_TRANSACTION isn't on the list of states we're willing to check that for, actually in spins then on a HUP'd socket we don't read from.

For non-SSE the transaction will complete; we will send something and detect the socket HUP'd then; we will timeout; or we are not in DOING_TRANSACTION so we can handle it.  I pushed a one-line patch on main + v4.3-stable adding DOING_TRANSACTION to the list of states to read on that should solve it.

https://libwebsockets.org/git/libwebsockets/commit/include/libwebsockets?id=73f01d835044142790ea01ed05a8bfe1af626e15
