### ISSUE TITLE
How to trigger LWS callback from foreign event loop

### ISSUE THREAD

**Issue by ronf** [warmcat/libwebsockets#2475]
I have an application where I'm using LWS with libuv as a foreign event loop. This is working nicely, but I have a need to trigger some I/O on an unrelated FD when I finish receiving the HTTP request body before generating the HTTP response. I'd like to manage this I/O directly in libuv, but I need some way to trigger the LWS HTTP callback when this other  I/O is completed.

My thinking here was that I could create a uv_poll_t when handling the LWS_CALLBACK_HTTP_BODY_COMPLETION callback in LWS, with appropriate refcounting using lws_libuv_static_refcount_add/lws_libuv_static_refcount_del, but I'm not clear on what call I can use when the I/O is complete to get back into the LWS callback to do the actual write of the HTTP response. This seems like it might be a good use of LWS_CALLBACK_USER as the callback reason, but what API would I call from inside the libuv poll handler to actually schedule this user callback?

Another thought I had was to call lws_callback_on_writable() from within the libuv poll handler when it's time to write the HTTP response. Even though the HTTP socket is writable even before that, it looks like LWS doesn't actually trigger a writable callback until you explicitly ask for one. Is lws_callback_on_writable() safe to call from a foreign event loop handler?

Thread safety shouldn't be an issue here, as I'm running libuv single-threaded with LWS using it as its (foreign) event loop. For scalability I'm running multiple instances of this, but they are in separate processes with no shared state.

**Comment by lws-team** [comment]
> Thread safety shouldn't be an issue here, as I'm running libuv single-threaded with LWS using it as its (foreign) event loop.

Yes this is the key point.  In fact it doesn't matter if lws pulled the strings to get the event loop thread to call something, or the foreign event loop got the same thread to execute some code itself.  The benefits of the single event loop thread serialization guarantee are all the same, so you can call any lws apis from any native callback of the same event loop thread as lws was told to share.

> My thinking here was that I could create a uv_poll_t when handling the LWS_CALLBACK_HTTP_BODY_COMPLETION callback in LWS

I think you can eg, send a response headers part with a content-length plumbed in, then defer sending the promised amount of body to complete the response, by putting off the lws_callback_on_writeable(), and just returning from the _WRITEABLE without doing anything while waiting.

In your native libuv handler for your fd and event, which doesn't have to be counted as lws event loop usage or introduced to lws, you set a flag to say the fd event happened, and there directly call lws_callback_on_writeable() on the http wsi.  You also have to handle the http wsi _CLOSE to detach any pending fd event from the http wsi, because after that point it will have been destroyed and the later fd completion can no longer write on it.

In the normal flow, the http wsi _WRITEABLE will see the fd completion flag set now and issue the body to complete the response.

**Comment by ronf** [comment]
Thanks so much for the quick response!

> I think you can eg, send a response headers part with a content-length plumbed in, then defer sending the promised amount of body to complete the response, by putting off the lws_callback_on_writeable(), and just returning from the _WRITEABLE without doing anything while waiting.

That makes sense. In my case, the response body data will be pretty small (a few KB at most, but generally more like a few hundred bytes). So, I'll probably want to hold off on writing even the HTTP response headers until the other I/O completes. That way I have the option of sending an HTTP error response if the other operation doesn't complete successfully. I think this same basic strategy with the completion flag should work here, though.

> In your native libuv handler for your fd and event, which doesn't have to be counted as lws event loop usage or introduced to lws, you set a flag to say the fd event happened, and there directly call lws_callback_on_writeable() on the http wsi. You also have to handle the http wsi _CLOSE to detach any pending fd event from the http wsi, because after that point it will have been destroyed and the later fd completion can no longer write on it.

At what point does the memory associated with the "user" pointer in the LWS callback get freed? Is this triggered only on a call to lws_http_transaction_completed() and is this also when "wsi" becomes invalid, or are there other ways in which the wsi and/or the user pointer memory can be released when a connection closes? I'm trying to figure out if I can keep the user memory around (even if the corresponding socket is closed) until my other I/O completes and clean everything up then or if I need to allocate some other shared memory to hold the wsi pointer that I can null out on connection close to prevent it from being used after close when the libuv callback wakes up.

Also, if I understand right, you're saying I don't need to worry about using lws_libuv_static_refcount_add/() and ws_libuv_static_refcount_del(), which I guess makes sense if I'm explicitly setting up and running a foreign event loop myself. Were these calls only intended to be used when LWS sets up the event loop and you want to add your own events in its loop?

**Comment by lws-team** [comment]
> At what point does the memory associated with the "user" pointer in the LWS callback get freed?

It's during the internal wsi close processing... after returning from _CLOSE it should be understood to be gone.  libuv is unique that handle closes are also staged around the event loop... actually in libuv case, bits of the wsi get destroyed then (I think the user allocation among them) but the main wsi object is only destroyed later when libuv indicates the related handle close completion has occurred.

> Also, if I understand right, you're saying I don't need to worry about using lws_libuv_static_refcount_add/() and ws_libuv_static_refcount_del(), which I guess makes sense if I'm explicitly setting up and running a foreign event loop myself. Were these calls only intended to be used when LWS sets up the event loop and you want to add your own events in its loop?

The scenario we have to support cleanly is lws joining a long-lived foreign loop as some kind of bit-player, it must create itself on to an existing loop, and then perfectly cleanly and without leaks, no matter what was going on, stage unpicking itself from the loop, destroying its own objects at the right moment.  It cannot change the loop state at all, it's just a temporary guest.  Since libuv objects only actually detach and close from the loop after more times around the event loop, that is nontrivial to do right.  There are both static handle refcounts (for eg, pipe, or listen socket handles) and dynamic handle refcounts (for wsi staged handle close and destroy) needed.  vhost destroy is triggered when the last handles bound to it finalize via libuv handle closure completion events, pt destroy when no more vhosts, context destroy when no more pts, all going via the event loop, to get everything right.

In this case, you can own the fd handles on the loop outside of lws, although they must initially associate with an http wsi, it must be possible for your fd handles to survive the wsi closure, since the fd can close at any time around the event loop (hold down F5 on the browser or whatever), and your fd too since a libuv one, cannot complete its handle close without return to the event loop.  The state of one of your fds still pending to complete or close itself, but no longer associated to any live http wsi is a normal situation you must deal with anyway.  So IIUI, you have to take some care, but you can leave your fds out of the book-keeping that lws has to do to stage its destruction and account for them yourself.

**Comment by ronf** [comment]
Thanks again - I've got this working quite nicely now!
