### ISSUE TITLE
Got error when I tried to send body in LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER callback

### ISSUE THREAD

**Issue by qdztxc** [warmcat/libwebsockets#2494]
Hi Andy,
I'm using lws as http client.

I did benchmark and listed lws latency in my environment:
lws_cancel_service ~ LWS_CALLBACK_EVENT_WAIT_CANCELLED callback: around 55us.
LWS_CALLBACK_EVENT_WAIT_CANCELLED ~ LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER: around 60us.
LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER ~ LWS_CALLBACK_CLIENT_HTTP_WRITEABLE: around 60us.

I'd like to reduce the latency thus I call 
lws_write and lws_client_http_body_pending(wsi, 0) in LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER callback.
But I got 400 bad request error. 
My code is similar with https://github.com/warmcat/libwebsockets/issues/1358
if (LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER == reason) {
        println("LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER");
        
        uint8_t** up = (uint8_t**) in;
        uint8_t* uend = *up + len - 1;
        
        const char contentType[] = "text/xml";
        const char userAgent[] = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36";
        
        if (lws_add_http_header_by_token(
                socket, 
                WSI_TOKEN_HTTP_USER_AGENT, 
                (uint8_t*) userAgent, strlen(userAgent), up, uend
           )) {
            return 1;
        }
        
        if (lws_add_http_header_by_token(
                socket,
                WSI_TOKEN_HTTP_CONTENT_TYPE,
                (uint8_t*) contentType, strlen(contentType), up, uend
           )) {
            return 1;
        }
        
        lws_add_http_header_content_length(socket, 84, up, uend);
        
        //lws_client_http_body_pending(socket, 1);
        //lws_callback_on_writable(socket);
        
        char buffer[LWS_PRE + 2048] = {};
        const char xml[] = 
        R"(<?xml version="1.0"?>
                <methodCall>
                <methodName>help</methodName>
                </methodCall>
         )";
        
        strcpy((char*)*up, xml);
        println((char*)*up);
        lws_client_http_body_pending(socket, 0);
        lws_write(socket, (unsigned char*) *up, sizeof(xml), LWS_WRITE_TEXT);
}
Is there any hint why this usage is failed? I think the protocal I used to connect to http server I try to connect is H2.

Besisdes I also noticed there is another issue 
https://github.com/warmcat/libwebsockets/issues/1256
the code pasted in this issue doesn't have lws_write. Is it correct?
case LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER: 
{ char *&p = (char*&)(*(char**)in); p += sprintf(p, "content-length: %d\r\n" "content-type: application/x-www-form-urlencoded\r\n\r\ntext=1234&send=Send+the+form" , 28); break; }

Thanks and regards.

**Comment by lws-team** [comment]
No you shouldn't do the lws_write().

Older github issues are not good guidance since the apis may have changed over the years.

The best way is git grep the tree and look in the examples that are contemporary with your lws version, eg

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/http-client/minimal-http-client/minimal-http-client.c?h=main#n113-139

**Comment by qdztxc** [comment]
Yes. I'm using the standard usage now.
1. call lws_cancel_service in differenct threads
2. call lws_client_connect_via_info in LWS_CALLBACK_EVENT_WAIT_CANCELLED
3. add header in LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER. then call 
      lws_client_http_body_pending(wsi, 1);
      lws_callback_on_writable(wsi);
4. call lws_write and lws_client_http_body_pending(wsi, 0); in LWS_CALLBACK_CLIENT_HTTP_WRITEABLE.
It works well but I want to reduce the latency this procedure. I noticed lws use event_fd for internal wait/notify. Though eventfd 
 is the fastest way for inter procedure communication it still requires user kernel mode switch which will bring latency.

Is there a hack to reduce the latency of 1~4? I can dedicate 1 or 2 CPU core for lws usage (isolate and bind core).
Never mind if lws drives core to 100% usage. 

Thanks and regards

**Comment by lws-team** [comment]
Typcial usecases don't care about 60us latency when RTT between client and server is measured in tens or hundreds of ms.  60us is something you can fit 16,000 of in a second.  There are many other concerns that most lws users do care about that have to be balanced.

There is also a tradeoff delaying entry to the wait, increases the latency for servicing other fd events accordingly.  So "latency" has to be very carefully understood what you are trying to optimize for and what's OK to burn to achieve it.

> eventfd

eventfd is not making this situation, it's the entry and exit to the generic kernel wait, the default one is poll().

If this is h2, then the WRITEABLE callback is not just coming because POLLOUT is signalled, but because the h2 layer decided it's your stream's turn to write on the shared connection too, again the way it is everything works well when there are multiple streams active.  Again because it's h2, you can't make assumptions about the writeability state, since other stream(s) on the same connection may be busy using it up behind your back.

> Never mind if lws drives core to 100% usage.

For new connections, the tcp window is some size and you're typcially going to be able to write some or all of that from the start.  You could adapt the platform service loop to understand that and basically force POLLOUT on and avoid entering the real wait until it had used up your "new connection" budget of write payload.

Another way to consider is don't use http, use ws.

**Comment by qdztxc** [comment]
> For new connections, the tcp window is some size and you're typcially going to be able to write some or all of that from the start. You could adapt the platform service loop to understand that and basically force POLLOUT on and avoid entering the real wait until it had used up your "new connection" budget of write payload.
> 
Thanks for your explanation. Could you please add more detail for how to fore POLLOUT? Is there an option to achieve this or should I change code logic for this?
