### ISSUE TITLE
Is the lws_protocols list should be matching on both client and server?

### ISSUE THREAD

**Issue by rajendra-adimulam** [warmcat/libwebsockets#2498]
Team,
I wanted to understand if the protocols used by client and server should be the same? I mean having the same name?
My belief is that protocol is just for call back invocation by the lws library, And user has the option to specify a different protocol for separate connections.. Please help to clarify

**Comment by lws-team** [comment]
If you are using ws protocol, the lws_protocols name is used to negotiate with the server which of the ws protocols (aka "subprotocols") the server may offer you actually want to use.  Otherwise, a server could only offer exactly one ws subprotocol.

https://datatracker.ietf.org/doc/html/rfc6455#section-1.9

You can bind client connections to arbitrary local lws_protocols using `client_info.local_protocol_name`

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h?h=main#n162-168

but the name field in the lws_protocols will be used to start any ws upgrade negotiation with the server.
