### ISSUE TITLE
Allow listen port + SSL client context

### ISSUE THREAD

**Issue by kolis** [warmcat/libwebsockets#250]
I want to use a server context with a listening port, but still I want to be able to use this context to connect , as a client, to another SSL server. But in ```lws_context_init_client_ssl``` I see this 
```
	if (info->port != CONTEXT_PORT_NO_LISTEN)
		return 0;
```
which does not give the context an ssl_client_ctx. Is there a reason why this should not be allowed?

**Comment by warmcat** [comment]
I think its main idea is that if you're being a client typically, you don't want a useless listening socket hanging around, rather than to "disallow" something.

I dunno what will happen if you try to enable it, I think with a little hacking it could work.

Basically server listening ssl is a special one-off in the context, but client ssls are inside wsis, so they do not need to inherently conflict, multiple client connections should be OK etc.

**Comment by kolis** [comment]
It is the other way around. The code does not prevent a client context from having a listening socket, it prevents a server context from having an client SSL context.

Anyway, I tried removed the test so all contexts get an client SSL context, and I have not experienced any problems, that seems to work for me at least.

**Comment by warmcat** [comment]
OK.  I was noting whatever way around, the two things shouldn't conflict.  I'm glad it worked out for you.
