### ISSUE TITLE
callback event reason LWS_CALLBACK_EVENT_WAIT_CANCELLED always has NULL user pointer

### ISSUE THREAD

**Issue by chill1n** [warmcat/libwebsockets#2504]
Even though the userdata field of ccinfo is defined, upon the callback with event reason LWS_CALLBACK_EVENT_WAIT_CANCELLED the "user" pointer is always NULL.
There is no reason why this field does not hold a pointer to userdata. This behavior limits the functionality.

I think this may be considered a bug.

**Comment by lws-team** [comment]
No, it's not a bug.

Although most reasons for calling an lws_protocols callback are in the scope of a specific wsi, there are several reasons that have different scopes.  Eg, PROTOCOL_INIT has the scope of the vhost-protocol instantiation, it is called once for each vhost that offers the protocol; other reasons have lws_context scope.  For these, a "fakewsi" is used that has, eg, the context, vhost and perhaps protocol pointers prepared for the scope of the call.  Such calls do not have a particular wsi's userdata, because they are not about any particular wsi.

EVENT_WAIT_CANCELLED's scope is the per-thread (== the context when LWS_MAX_SMP is at the default of 1).  As a convenience, it "broadcasts" that notification to each vhost-protocol instantiation in the context with that callback, so you have access to the vhd.  Again since that is not about any specific wsi, there is no wsi userdata related to it.

Vhosts, lws_protocols and the lws_context also allow you to set an opaque "user" pointer that can be recovered from the fakewsi (always the lws_context one, if the others are valid depend on the reason scope).

**Comment by chill1n** [comment]
I understand the scope reasoning. However, it is still an implementation choice to not wsi-specific user data to a callback.
Another choice could be to trigger an EVENT_WAIT_CANCELLED for each wsi in the scope of the context (of the associated lws_cancel_service()). That would provide the user with more data to act on. If both behaviors are deemed useful, then put it behind a (dynamic/static) switch.

To give an example, in my case I'm setting up several separate ws channels for different functions towards the same remote ws server. How would that work with the proposed vhd method and EVENT_WAIT_CANCELLED? I'm identifying each ws channel (and its associated wsi) via an enum for each function category that I'm passing as userdata.

**Comment by lws-team** [comment]
Some users have 150K connections ongoing (and want 1M), it can't just broadcast to all wsi.  lws can't know which (if any) existing connections should care... your code knows that after it locks your intra-thread shared data.  So it's not an lws level problem but for user code.

> How would that work with the proposed vhd method

Your vhd can hold, or point to, the related channels wsi array, and EVENT_WAIT_CANCELLED can get the vhd.  It also can lock the area shared between threads and find out what you want to happen.  And it can call any lws api on any of the wsis.

**Comment by chill1n** [comment]
What are the semantics of a vhost in a client application context? I'm not using a vhost at this moment.

**Comment by lws-team** [comment]
You are using a default vhost if you didn't explicitly do something different, one is created along with the context by default.

Vhosts are mainly useful for serving, but one of their jobs is they hold the tls contexts for client and server.  For server, it means you can have n vhosts prepared with different tls cert + keys, and bind them to different hostnames via alpn.  For client, you might want different mutual auth cert and keys for different connections, at client connection creation time you can name a specific vhost to bind the client connection to.

vhds are storage created per-vhost that enabled serving a protocol.  Depending on the vhost, you might configure the same protocol to act differently.  They're useful for clients too because their definition and usage is close to the protocol callback, usually it's all in the same file.

**Comment by chill1n** [comment]
The access function to vhd being lws_protocol_vh_priv_get(lws_get_vhost(wsi), lws_get_protocol(wsi)), only depends on parameters vhost and protocol. At this moment I'm using the vhost that is assigned implicitly. So the only selection parameter is "protocol" (assuming that the implicitly assigned vhosts will be seen as equivalent). But as I am also using a single static protocol (with dynamic userdata), I will always get the same vhd back for each connection.  You're suggesting the protocol (name) should be made specific for each remote host, or was my assumption about the implicit vhost wrong?

**Comment by lws-team** [comment]
>  The access function to vhd being lws_protocol_vh_priv_get(lws_get_vhost(wsi), lws_get_protocol(wsi)), only depends on parameters vhost and protocol.

Yes, it's an object that represents that protocol on a specific vhost.  If you had more vhosts that used the protocol too, they would each have a different vhd specific to the vhost-protocol instance.  So the protocol instantiation on a.com would have its own vhd different from the same thing served on b.com, even though it's all handled by the one lws_context.

>  But as I am also using a single static protocol (with dynamic userdata), I will always get the same vhd back for each connection.

Yes.  Even if there's only one of them, it's still useful and a good way, because there is an object private to your protocol instantiation, with a type you control declared in the source file for your protocol and all uses also in there, and it will be destroyed along with the vhost-protocol instantiation cleanly too (with an LWS_CALLBACK_PROTOCOL_DESTROY cb for that event if you have secondary allocations inside the vhd to clean up).

> You're suggesting the protocol (name) should be made specific for each remote host

No... wsi lifecycles are completely independent, you may feel you have a group of wsi, but underneath they are individual sockets that can fail or close according to their own personal experience.  So if you have an object common to or representing the group, you must take care about its lifecycle and how to deal with some or finally all wsi failing to connect or disappearing.  You can't just store wsi in a list or array from when you started them up, because any time around the event loop a wsi may close and the pointer be invalidated, you have to monitor wsi _CLOSE callback and prune the list.  You may still need the group object after the last member of the group has _CLOSEd, or the group object may be able to go away before the closure of all of its wsi is processed.

Instead, you need a group object that is bound to something longer-lived than a wsi, a good place for that is in the vhd, eg, hold in the vhd a lws_dll2_t linked-list of groups, each of which has a lws_dll2_t list or array of live wsi.  So not one group per vhd, but use the vhd as the place to list all current groups.  That is what I meant with

>> Your vhd can hold, or point to, the related channels wsi array,

**Comment by chill1n** [comment]
Thanks for the clear explanation.
So the designated way to handle this is via a vhd construct. In the _PROTOCOL_INIT event I should use lws_protocol_vh_priv_zalloc() to allocate memory for this. I like symmetry, so I would expect that in _PROTOCOL_DESTROY I would need a call to a "free memory" function. If this is not needed, where is that taken care of?

**Comment by lws-team** [comment]
When the vhost is destroyed, PROTOCOL_DESTROY is sent to all protocols it had instantiated, so they can destroy private allocations in the vhd struct, then shortly after all those are done, the vhds owned by the vhost are freed

https://libwebsockets.org/git/libwebsockets/tree/lib/core-net/vhost.c#n1509

It's fine to ignore PROTOCOL_DESTROY if no private allocations.  If you don't destroy the vhost at runtime (it is a thing useful for, eg, serving on dynamic interfaces) then destroying the lws_context will do it.

> designated

There's no requirement to use the vhd, you can use a filescope object, one passed in as the lws_context's user pointer or whatever.  But from experience it's a good, clean, extensible way for this kind of thing and typically does the right things if you find yourself with multiple vhosts.

**Comment by chill1n** [comment]
Thanks. So there's no need to worry about leaking memory if using lws_protocol_vh_priv_zalloc().
I prefer to use standard patterns instead of (slightly) optimized customized patterns if there is no performance penalty; the benefits of better test coverage and better support usually outweighs other considerations.

**Comment by gdevillele** [comment]
Thank you, I had the same question and this discussion was very helpful 😊
