### ISSUE TITLE
Questions regarding foreign thread API calls (doc update needed?)

### ISSUE THREAD

**Issue by chill1n** [warmcat/libwebsockets#2505]
In documentation file READMEs/README.coding.md the text states:

```
4) For multithreaded apps, this corresponds to a need to be able to provoke the
`lws_callback_on_writable()` action and to wake the service thread from its event
loop wait (sleeping in `poll()` or `epoll()` or whatever).  The rules above
mean directly sending data on the connection from another thread is out of the
question.

Therefore the two apis mentioned above that may be used from another thread are

 - For LWS using the default poll() event loop, `lws_callback_on_writable()`

 - For LWS using libuv/libev/libevent event loop, `lws_cancel_service()`
```

Questions:
1. Is calling lws_callback_on_writable() from a foreign thread still allowed in v4.3-stable?
2. Is calling lws_cancel_service() from a foreign thread allowed with the default event loop, because this text suggests otherwise?

**Comment by lws-team** [comment]
Yes this was true but has became cruft.  I updated the docs on main

https://libwebsockets.org/git/libwebsockets/commit?id=00e24e11ee5efceb519dcc508d03154ec02ae6ac

Any thread can call lws_cancel_service(), multiple threads doing so simultaneously is also OK.

**Comment by chill1n** [comment]
Any chance of getting lws_callback_on_writable() back because because that would make the client code significantly simpler. Also, I think (but this stil needs to be validated) that the latency between triggering the write request sequence and the actual lws_write() between lws_callback_on_writable() and lws_cancel_service() is significantly in favor of lws_callback_on_writable(). My test case shows a latency between lws_cancel_service and getting the LWS_CALLBACK_EVENT_WAIT_CANCELLED event of about 60 ms (with lws_lib v4.3-stable debug build). Can you confirm this?

**Comment by lws-team** [comment]
No, if the event loop is idle, `lws_cancel_service()` will wake it 'immediately', it depends on the platform but it's something 50-250us typically.  If the connection is already writeable, the cb will come a similar time later.

The state of your onward tcp connection though, as to when the network stack tells us we could write something more, means the writeable callback can always delay getting the WRITEABLE indefinitely, since if no space in the tcp window, it is not writeable (from any thread).

Likewise if you block the event loop, with blocking fds, or with sync object waits that are busy elsewhere for 60ms, any further activity on the event loop thread is stalled for 60ms or whatever since you forced its thread to sleep...
