### ISSUE TITLE
server only (no tls, no roles, etc)

### ISSUE THREAD

**Issue by parihaaraka** [warmcat/libwebsockets#2541]
Too many dependent options lead to inability to disable them. Finally I had to enable a single role and set -Wno-unused-label to build my empty project (i need to implement a custom protocol).

**Comment by lws-team** [comment]
> Too many dependent options lead to inability to disable them.

That may be the case for some specific option sets, but "no client", `-DLWS_WITH_CLIENT=0` eg

https://libwebsockets.org/sai/index.html?task=9ea406a2d06f99dc82315e064a098e13e42251ad68e26c1dbe392c318998cd66

and "no server", `-DLWS_WITH_SERVER=0` eg

https://libwebsockets.org/sai/index.html?task=9ea406a2d06f99dc82315e064a098e13ae9e799b9a4ae7f529f4fb16100a7e79

are explicitly confirmed in CI for every push.  So I do not believe there's any general problem.

CMake is a bit tricky to work with, because your options are cached and apply even when you stop giving them on a cmake commandline, you have to either nuke your CMakeCache.txt or explicitly countermand anything you ever gave since deleting it last to make sure you are not actually trying a build a mixure of things from your past attempts.
