### ISSUE TITLE
debug Commands

### ISSUE THREAD

**Issue by madhanreddy433** [warmcat/libwebsockets#2545]
could you please let us know what are the debug options we have to debug the LWS code for any issue?

**Comment by lws-team** [comment]
Debugging means different things for problems at different layers.

The main tool to understand what happened is the logs.  Build with `-DCMAKE_BUILD_TYPE=DEBUG` and increase the logging bitmap usually to 1151, in the examples add `-d1151`.

If you are debugging your network traffic, there are some helpful options `LWS_TLS_LOG_PLAINTEXT_RX` and `LWS_TLS_LOG_PLAINTEXT_TX` that hexdump the network traffic just after and just before the tls layer.  So you can see your protocol headers and whole payloads.

If there are unexpected crashes or leaks, valgrind is your friend.  Lws is developed under valgrind and is valgrind-clean itself, so the first sign of problems there are likely to be a huge clue.  If there are crashes, running under gdb can also be useful.

Otherwise, more specific info needed.
