### ISSUE TITLE
minimal build option for http and ws client

### ISSUE THREAD

**Issue by qdztxc** [warmcat/libwebsockets#2550]
Hi Andy,

I'm using lws as http and ws client. I don't need server functionality.
May I undef LWS_WITH_SERVER to just build a client version?

Besides, I only need basic functionality of http and ws client. No UDP or proxy related required.
May I turn off following options?
LWS_WITH_NETLINK
LWS_WITH_UDP
LWS_WITH_UNIX_SOCK
LWS_WITH_UPNG
LWS_WITH_EVLIB_PLUGINS
LWS_HAVE_RTA_PREF
LWS_WITH_CACHE_NSCOOKIEJAR
LWS_ROLE_RAW_FILE
LWS_WITH_HTTP_UNCOMMON_HEADERS
LWS_WITH_SYS_STATE
LWS_WITH_SYS_SMD
LWS_WITH_DLO
LWS_WITH_LEJP
LWS_WITH_JSONRPC
LWS_WITH_DIR
LWS_WITH_LEJP_CONF
LWS_LOGS_TIMESTAMP
LWS_LOG_TAG_LIFECYCLE

Thanks and regards.

**Comment by qdztxc** [comment]
Another two questions:
What's the functionality of LWS_WITHOUT_EXTENSIONS?

If I want to use wolfSSL to replace openssl.
I need to turn on LWS_WITH_WOLFSSL with LWS_WOLFSSL_LIBRARIES and LWS_WOLFSSL_INCLUDE_DIRS. In this case, LWS_WITH_SSL should set to on or off?

Thanks and regards.

**Comment by lws-team** [comment]
Cmake caches options, making iterative changes easily lead to non-reprodicible results, since the last commandline options just modify CMakeCache.txt.  So you should delete CMakeCache.txt each time when selecting options to be sure what's on your cmake commandline is enough to get the result alone.

LWS_HAVE_ should usually not be modified, they are discovered at build time.

You should look through ./CMakeLists.txt options that default to ON and force the ones you don't want to 0 on the commandline, and check the build.

Library file size is typically not the problem, the issue is how much is linked into your build.  So, eg, megabytes of debuginfo in the library costs nothing.  You should use `-ffunction-sections` on your app link to strip out apis built into the lib, that nobody calls... this can have a dramatic effect very cheaply.

WITH_SSL is on by default just leave it.  Refer to cmake options used in wolfssl build in CI, eg

https://libwebsockets.org/sai/index.html?task=da682ab84a186a73a17ef39911f81cc2a2e4c0352b917d21f740619a6ba554e4

LWS_WITHOUT_EXTENSIONS disables ws permessasge-deflate support.

**Comment by qdztxc** [comment]
Thanks for you description.
I noticed another option LWS_HAVE_MALLOC_USABLE_SIZE. It seems account allocated memory. If I don't care about heap memory usage, may I turn it off?

Thanks and regards.

**Comment by lws-team** [comment]
With LWS_HAVE cmake is uing the symbols to track if you have that on your build system.  You can override these discovered apis from the cmake commandline using the same syntax as options, but you are basically overriding the discovery (cmake then feels like it already has the result you forced cached from a previous discovery).
