### ISSUE TITLE
why define a static varable in function LWS_VISIBLE void _lws_logv(int filter, const char *format, va_list vl)

### ISSUE THREAD

**Issue by windflowerly** [warmcat/libwebsockets#2566]
why define a static varable in function LWS_VISIBLE void _lws_logv(int filter, const char *format, va_list vl)

source code 
-------------------------------------------------
LWS_VISIBLE void _lws_logv(int filter, const char *format, va_list vl)
{
	static char buf[256];    // here, a static varible
	int n;

}
-------------------------------------------------

**Comment by lws-team** [comment]
Since only one thing can log at a time by default, the goal of it is to reduce the minimum required stack allocation, for embedded / freertos case.

Logs are likely to occur in any function including the deepest stack of functions the program has, so having this on stack is going to increase the stack requirement by whatever size it is.  Having it in BSS avoids that.
