### ISSUE TITLE
connect LWS client to nodejs websocket server

### ISSUE THREAD

**Issue by danflu** [warmcat/libwebsockets#2572]
Hi,

Im trying to use latest libwebsocket to connect a client (written with LWS library) to my local nodejs websocket server (javascript)

The client C code is pasted here:

https://pastebin.com/KGrReX7v

I think I'm doing something fundamentally wrong, because it looks like my code is behaving like a server, not a client...
I looked everywhere and could not find a way to make this work, so I would really appreciate any help...

Sorry about this lame question... But I really need to figure this out.

This is the sequence of callbacks I receive...

reason = LWS_CALLBACK_LOCK_POLL (35)
reason = LWS_CALLBACK_ADD_POLL_FD (32)
reason = LWS_CALLBACK_UNLOCK_POLL (36)
reason = LWS_CALLBACK_LOCK_POLL (35)
reason = LWS_CALLBACK_CHANGE_MODE_POLL_FD (34)
reason = LWS_CALLBACK_UNLOCK_POLL (36)
reason = LWS_CALLBACK_CONNECTING (105)
reason = LWS_CALLBACK_LOCK_POLL (35)
reason = LWS_CALLBACK_CHANGE_MODE_POLL_FD (34)
reason = LWS_CALLBACK_UNLOCK_POLL (36)
reason = LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED (19)

And this is the log produced by libwebsocket:

N: LWS: 4.3.0-2022.02.02-98-gf54a7b001, NET CLI SRV H1 H2 WS ConMon IPV6-on
N:  ++ [wsi|0|pipe] (1)
N:  ++ [vh|0|default||-1] (1)
N:  ++ [wsicli|0|WS/h1/default/danflu.ip.tv] (1)
W: lws_plat_set_socket_options_ip: not implemented on windows platform

Thanks,
Daniel

**Comment by lws-team** [comment]
The minimal examples are provided as the starting point for this kind of thing.  Eg try minimal-examples-lowlevel/ws-client and afterr seeing it work without changes, start to adapt it.

**Comment by lws-team** [comment]
Glad you're working.

> This string "lws-minimal-client" has any effect ? I tried to put this NULL but this cause crash.

This is the local name of your lws_protocol that's also used for matching explicit subprotocols on the server.  It's better to use subprotocol names rather than the default nameless one, because you can only have one nameless ws protocol per vhost on your server.  But that's a choice the server operator makes and as the client you just have to follow along.

You indicate you want to negotiate to use the server's nameless subprotocol by `i.protocol = NULL`.  It should be fine to leave the `i.local_protocol_name = "lws-minimal-client";` because presumably that's what you end up binding to "by accident" anyway, since the default is to bind to the first local user protocol.
