### ISSUE TITLE
cannot establish connection from  node client

### ISSUE THREAD

**Issue by reallynyn** [warmcat/libwebsockets#2581]
i've setup a loop server with following settings:

`
```
static struct lws_protocols test_protocols[] =
{
    {
        "test-protocol",
        my_lws_service_callback,
        0, //size_t per_session_data_size
        0, //size_t rx_buffer_size
        2, //unsigned int id;
        NULL, //void *user;
        0, // size_t tx_packet_size
    },
    { NULL, NULL, 0, 0, 0, NULL, 0 } /* terminator */
};

```
    struct lws_context_creation_info info;
    memset(&info, 0, sizeof(info));
    
    const char *interface = NULL;
    info.port               = 8964;
    info.pt_serv_buf_size   = 65536*16;
    info.protocols          = test_protocols;
    info.extensions         = NULL;
    info.options            = LWS_SERVER_OPTION_PEER_CERT_NOT_REQUIRED;
    info.options           |= LWS_SERVER_OPTION_DISABLE_OS_CA_CERTS;
    info.options           |= LWS_SERVER_OPTION_UNIX_SOCK;
    info.options           |= LWS_SERVER_OPTION_SKIP_PROTOCOL_INIT;
    info.options           |= LWS_SERVER_OPTION_IGNORE_MISSING_CERT;
    info.options           |= LWS_SERVER_OPTION_ALLOW_HTTP_ON_HTTPS_LISTENER;
    
    // Not using ssl
    info.ssl_cert_filepath = NULL;
    info.ssl_private_key_filepath = NULL;
    info.gid = -1;
    info.uid = -1;
    
    info.timeout_secs = 3600 * 72;
    
    struct lws_context* test_context = lws_create_context(&info);

    test_context->account_lws_writable = true;
    while(1) { lws_service(test_context, 0); }
`

When I connected from my client, it disconnected in 30 seconds with following log:

`accepted new conn port 25665 on fd=18
lws_get_idlest_tsi: 2 65534
_realloc: size 832: new server wsi
new wsi 0x3131170 joining vhost default, tsi 0
lws_vhost_bind_wsi: vh default: wsi none/none, count_bound_wsi 2
lwsi_set_state(0x3131170, 0x20000200)
lws_role_transition: 0x3131170: wsistate 0x20000016, ops h1
__lws_set_timeout: 0x3131170: 259200 secs, reason 3
__insert_wsi_socket_into_fds: 0x3131170: tsi=0, sock=18, pos-in-fds=2
***user log: lws_callback_function reason [19]
_realloc: size 976: ah struct
_realloc: size 4096: ah data
_lws_change_pollfd: wsi 0x3131170: fd 18 events 1 -> 1
__lws_set_timeout: 0x3131170: 10 secs, reason 25
Attached ah immediately

... 30 seconds later

__lws_close_free_wsi: real just_kill_connection: 0x3131170 (sockfd 18)
_lws_change_pollfd: wsi 0x31330d0: fd 16 events 1 -> 1
lwsi_set_state(0x3131170, 0x20000020)
__lws_close_free_wsi_final: wsi 0x3131170: fd 18
_lws_change_pollfd: wsi 0x31330d0: fd 16 events 1 -> 1`

From the log I can't find anything helpful indicating the close reason.
Is there any idea that I can find why lws just_kill_connection?

**Comment by lws-team** [comment]
`just_kill_connection` is part of the close processing, it doesn't get called by itself.

Before that log, the outer close function should log a reason string.

But I think your problem is just timeouts, an internet server cannot afford to just let things happen forever and exhaust all its resources uselessly, each step of the lifecycle of a connection is protected by timeouts.  It reuses the same timeout for each step.  Just before the connection reaches ESTABLISHED or similar, lws has put one last default timeout on it.  After that, you can put your own timeout there.

If you open the connection and leave it idle, you normally very much want a limit on how long it will just sit there.  If you think you know better, you can mark the wsi with `lws_http_mark_sse(wsi)` to cancel any timeout and wait for something else to kill the connection.  You can do this, eg, at `LWS_CALLBACK_HTTP`

**Comment by reallynyn** [comment]
This problem occurs when i update my lws from 2.3 to 4.3.
As in lws 2.3, these codes run without any trouble.
While in lws 4.3, the connection hangs on "Attached ah immediately" which should be continues until I get a service_callback with the reason LWS_CALLBACK_ESTABLISHED.
I wonder why the procedure cannot work again? 
I just open up a connection in nodejs like
`var ws = new WebSocket('ws://192.168.0.149:8964');
ws.send("test");`

**Comment by lws-team** [comment]
Can I suggest you look at, eg, https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/ws-server/minimal-ws-server and confirm that is working?  Then align your code to what that does.

**Comment by reallynyn** [comment]
I guess I've found the reason.

LWS_VISIBLE LWS_EXTERN int
lws_service(struct lws_context *context, int timeout_ms);
 *  Since v3.2 internally the timeout wait is ignored, the lws scheduler is
 *  smart enough to stay asleep until an event is queued.
 
In lws 2.3 I made 2 lws_contexts looping accepting scks from 2 diff ports in a single thread.
As in lws4.3, the loop blocks until 30 seconds or receiving an event. Meanwhile the other queue is blocked.
I'm not planning to change my program to multi-thread this time. Is there anyway I can break the lws_service block if nothing happens. So I can get lws events in a very short loop for each lws_context?

**Comment by lws-team** [comment]
> In lws 2.3 I made 2 lws_contexts looping accepting scks from 2 diff ports in a single thread.

Hmmm you don't need to do that.  One context supports as many vhosts as you like.

Each vhost can listen on its own port or share a port if you like.

See, eg, https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/http-server/minimal-http-server-multivhost

Then you just have one lws_context, two vhosts on it, be happy that it is idle when nothing to do.

**Comment by lws-team** [comment]
When you design something using an event loop, you have to put your work on the event loop one way or another.  Or you find yourself in the situation you are in.

Clearly, half your problem is the two contexts hack you can dispense with by just using available lws features.

Whatever else you have going on in one thread must join the event loop one way or another, the best way depends on what it is doing.

If you want a quick hack (something tells me...) then look at lws_sul

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.lws_sul.md

**Comment by reallynyn** [comment]
seems I've to do some refactor work.

btw I've switched lws to 3.1, the client frequently disconnect with following logs:

accepted new conn port 30119 on fd=20
_realloc: size 544: new server wsi
new wsi 0x34da3a0 joining vhost default, tsi 0
lwsi_set_state(0x34da3a0, 0x200)
lws_role_transition: 0x34da3a0: wsistate 0x20000015, ops h1
__lws_set_timeout: 0x34da3a0: 259200 secs (reason 3)
new wsi wsistate 0x20000015
__insert_wsi_socket_into_fds: 0x34da3a0: tsi=0, sock=20, pos-in-fds=2
_realloc: size 960: ah struct
_realloc: size 4096: ah data
_lws_change_pollfd: wsi 0x34da3a0: fd 20 events 1 -> 1
__lws_set_timeout: 0x34da3a0: 10 secs (reason 25)
Attached ah immediately
rops_handle_POLLIN_h1: 0x34da3a0: wsistate 0x20000015
lws_read_h1: h1 path: wsi state 0x15
lwsi_set_state(0x34da3a0, 0x20000209)
__lws_set_timeout: 0x34da3a0: 0 secs (reason 0)
lws_role_transition: 0x34da3a0: wsistate 0x20000117, ops ws
lws_ensure_user_space: 0x34da3a0 protocol pss 0, user_space=(nil)
_realloc: size 200: ws struct
lws_ensure_user_space: 0x34da3a0 protocol pss 0, user_space=(nil)
lws_ensure_user_space: 0x34da3a0 protocol pss 0, user_space=(nil)
lwsi_set_state(0x34da3a0, 0x20000117)
lwsi_set_state(0x34da3a0, 0x20000117)
_realloc: size 16777236: rx_ubuf
Allocating RX buffer 16777232
ws established
lws_h1_server_socket_service: consumed 227
*** user data recv
_lws_change_pollfd: wsi 0x34da3a0: fd 20 events 1 -> 5
_lws_change_pollfd: wsi 0x34da3a0: fd 20 events 5 -> 1
lws_handle_POLLOUT_event: 0x34da3a0: non mux: wsistate 0x20000117, ops ws
*** user data recv
_lws_change_pollfd: wsi 0x34da3a0: fd 20 events 1 -> 5
_lws_change_pollfd: wsi 0x34da3a0: fd 20 events 5 -> 1
lws_handle_POLLOUT_event: 0x34da3a0: non mux: wsistate 0x20000117, ops ws
lws_read_h1: h1 path: wsi state 0x117
lws_parse_ws: received 1728 byte packet
*** user data recv
_lws_change_pollfd: wsi 0x34da3a0: fd 20 events 1 -> 5
lws_ws_rx_sm: ws fragment length exhausted
rops_close_via_role_protocol_ws: sending close indication...
lwsi_set_state(0x34da3a0, 0x20000119)
__lws_set_timeout: 0x34da3a0: 5 secs (reason 24)
_lws_change_pollfd: wsi 0x34da3a0: fd 20 events 5 -> 5
sending close packet

Is there any idea why lws 
`rops_close_via_role_protocol_ws: sending close indication...`
to close the connection?

**Comment by lws-team** [comment]
Lws is foss, you can do what you like consistent with the license.

But you're on your own if you use a version older than the current stable release.

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.release-policy.md

If you're the only guy with your code, you're on your own anyway.  That's why you received the good advice to align your code to a modern example.
