### ISSUE TITLE
connect3.c crash at connect(wsi->desc.sockfd, NULL, 0)

### ISSUE THREAD

**Issue by apcui** [warmcat/libwebsockets#2596]
Recently, I build libweboskcet to win app. But it always crash at srcjDDLL. 
If run in console, everything is noraml. 
I move  minimal-ws-clinet example into a empty win app which just created by VS2017 Windows Desktop Application, it still crash.
it crash at
`switch (lws_rops_func_fidx(wsi->role_ops, LWS_ROPS_handle_POLLIN).
					       handle_POLLIN(pt, wsi, pollfd)) {`
It happend on second call of this branch.
thia crash cause by connect3.c `if (!connect(wsi->desc.sockfd, NULL, 0))
		return LCCCR_CONNECTED;`
I change the code as `if (!connect(wsi->desc.sockfd, (const struct sockaddr *)&wsi->sa46_peer.sa4, 0))
		return LCCCR_CONNECTED;`， and then, everything is noraml.
I don`t kow why.

Below is the context :
libwebsockets version v4.3-stable.
opensll version 3.0.0 alpha 2
pthread version  win32 2.9.1 x86
libwebsocket build command :
`cmake .. -DOPENSSL_ROOT_DIR="E:\openssl" -DOPENSSL_INCLUDE_DIR="E:\openssl\include" -DOPENSSL_LIBRARIES="E:\openssl\lib" -DLWS_HAVE_PTHREAD_H=1 -DLWS_EXT_PTHREAD_INCLUDE_DIR="E:\pthreads-w32-2-9-1-release\Pre-built.2\include" -DLWS_EXT_PTHREAD_LIBRARIES="E:\pthreads-w32-2-9-1-release\Pre-built.2\lib\x86\libpthreadGC2.a" -DLWS_WITH_MINIMAL_EXAMPLES=1`

**Comment by lws-team** [comment]
I don't know why you crash there either, windows 10 here is OK with it.

It's normal to use connect() like that with nonblocking sockets to check if an ongoing async connection succeeded yet.

Maybe on that machine, something hooks the network connection, like a third party firewall app, that doesn't understand how to handle nonblocking connects and it crashes in there.

But I think giving it the address like you're doing isn't wrong.  Address being NULL is just a convenience since it is no longer supposed to care about the address after the initial connect().  We do have it in the wsi now.  So I think it's better to just use your workaround.

I added it here on main and will push it later also on v4.3-stable

```
Author: apcui <apcui@user.github.invalid>
Date:   Sat Apr 2 09:26:31 2022 +0100

    windows: avoid NULL addr on connect check
    
    https://github.com/warmcat/libwebsockets/issues/2596

diff --git a/lib/core-net/client/connect3.c b/lib/core-net/client/connect3.c
index 7b7be5f7af..6498ff0633 100644
--- a/lib/core-net/client/connect3.c
+++ b/lib/core-net/client/connect3.c
@@ -108,7 +108,7 @@ lws_client_connect_check(struct lws *wsi)
 
 #else
 
-       if (!connect(wsi->desc.sockfd, NULL, 0))
+       if (!connect(wsi->desc.sockfd, (const struct sockaddr *)&wsi->sa46_peer.sa4,>
                return LCCCR_CONNECTED;
 
        en = LWS_ERRNO;
```
