### ISSUE TITLE
How to receive a whole message instead of ws fragments?

### ISSUE THREAD

**Issue by renzibei** [warmcat/libwebsockets#2601]
In my codes, I handle the receive message when there is a readable event. However, I found that sometimes the received bytes are not a whole ws message (sometimes it is only the first byte of the ws message).
Is there any way to get the event when the message is completed received?

**Comment by lws-team** [comment]
This is deliberate, in order to not have to buffer what may be endlessly huge messages in memory, lws just passes through what it gets as it gets it.

You can use apis in the receive callback to find out if what you are being given is the start, middle, or end of a message and keep it until you have the whole thing yourself if you must.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-ws-state.h
