### ISSUE TITLE
Support with linux namespaces

### ISSUE THREAD

**Issue by rvishpr** [warmcat/libwebsockets#2614]
When I need to run my binary in a linux server with multiple network namespaces, I can use the setns system call to move the thread to the right namespace. Once I'm done establishing the socket, I move the thread back to the default namespace. When I need to do this with libwebsockets, at what points do I need to invoke the setns() system call? 

Should I just do this around a call to lws_client_connect_via_info()? Or do I keep the event thread in the needed namespace until a callback is received?

**Comment by lws-team** [comment]
Due to retries and eventually multipath speculative connections, opening the socket fd may not be a single event, so it's not enough to bracket it around the connect_via_info().  Setns() is a platform-specific thing too.  And as you say it has thread scope, since multiple client connections may be ongoing you'd need to refcount application of the ns to the thread.

It could be supported by lws in that you could pass the ns fd and flags in the client connect info and it'd take care of it (patch welcome).  Otherwise, I think applying the ns to the thread via a refcount before the client creation, and unreffing / undoing the ns change on CLIENT_CREATION_ERROR or ESTABLISHED or similar callback should work.

**Comment by rvishpr** [comment]
Thanks for the quick response. I'll start with the refcount approach to begin with. If I have a clean patch for your suggestion to add to connect info, I will submit it for review.
