### ISSUE TITLE
libwebsockets calls libev's ev_break() on SIGINT

### ISSUE THREAD

**Issue by wonder-mice** [warmcat/libwebsockets#264]
Hi,

libwebsockets is just a library and in my opinion it should behave properly and be a good citizen inside a hosting process. Obviously, event loop is used by other components.
It looks like libwebsockets was born as a standalone web server (or something) and only then decided to evolve into the library. That's understandable and appreciated. But once it decided to be a library it's better to minimize the interference with global process state, like calling ev_break(), setuid() or setgit() (I was shocked when discovered that the _transport_ library tries to call setuid()).

If you are agree with such thinking, I will provide patches to remove hostile calls.

**Comment by warmcat** [comment]
"hostile calls"... I think you have gotten the wrong idea a bit too easily.

First it was a library from the very start, five years ago.

Setuid etc have to be opted into by the user code, they are provided as an optional convenience for the common case a low port < 1024 must be listened on, but otherwise root is not needed.  Formalizing that only enhances security and they are not called unless user code wants it.  So 'hostile' is completely backwards.

Libev support was contributed later, and it's clearly workable for his and others' usecases.  If you feel using a specific libev api is wrong for you, a patch to reduce it, make it smarter or select what to do as a runtime server option can be considered.  But unless it's an out-and-out bug please understand the library has been covering many different use-cases for five years and changes need to be smart enough not to disrupt every use-case but yours...

**Comment by wonder-mice** [comment]
Ok, may bad I pulled setuid/setgid into the discussion. It's a separate topic. Just wanted to know your general line of thinking regarding such things.

Regarding ev_break(). I think that a transport library should not control the event loop. Event loop must be controled only by the app (or a specific library that provides process life cycle services). libwebsockets is just a transport library that is only a small part of some larger application. It doesn't know how to manage the event loop correctly any way.

I can come up with the only use case for that - smaller example applications. If you could explain where else it could be useful, I would appreciate it. But otherwise, I would like to ask you to consider removing ev_break() call. As I said, I can provide patch for that.

**Comment by warmcat** [comment]
I originally wrote the library for headless embedded case.  So a device has no display, but it has network, then it can have a very rich UI via a browser.  That's why conveniences like the http serving logic and the optional daemonization are part of what it does.  You can link a small user code to this and get the rich UI in about 50KB or so of userland binary.

However there have been many users with completely different uses for it, including mass (250,000 connection) lightweight serving, the same approaches that are good for embedded turn out to be very good for removing thread and other language overhead considered normal in the server world.  And now it's in or headed into Debian, Ubuntu, Fedora, and Gentoo.  So we have to be careful about compatibility.

Looking at ev_break, basically he is there for SIGINT / ^C handling.  I agree that's not a good thing for all cases and right now it's enabled for all cases.  So if you can confirm moving that out of the library into the user code (looks like you can do it after the conext init in user init code if you want it) is equivalent it looks OK to me to get rid of it and add a changelog about what's needed for backward compatibility.

**Comment by wonder-mice** [comment]
Sounds good, I'll work on a patch then.

> I originally wrote the library for headless embedded case
Yeah, when I first found that library I was like "Wow! What a great library! Single thread! Pure C! Can provide my own SLL context! No bullshit!". But then I started to discover setuid/setguid, ev_break(), daemonization and other things that are (in my opinion) are completely unrelated to websockets. And that made me sad. Maybe I like single responsibility principle too much.

Btw, I think you need to consider changing branding from "Lightweight, portable C library" to "Portable C framework for writing web servers" :)

**Comment by warmcat** [comment]
Don't be sad ^^  Daemonization is a CMake option.  Lots of people don't want libev... it too is a build (and runtime, to cover the distro case) option.  setuid is a runtime option.  Actually it's pretty strict about bloat, part of websockets is the HTTP negotiation, and once you have that there are some knock-ons like URI path handling that are also part of websockets.  So a webserver is completely in scope, although the "business logic" of it is in user code.

**Comment by wonder-mice** [comment]
Created a push request for this one.

**Comment by andrew-canaday** [comment]
Here's a patch that _doesn't_ break existing applications: https://github.com/warmcat/libwebsockets/pull/277/

**Comment by wonder-mice** [comment]
This is just a network library. It should not try to solve any problem that a hypothetical web server could have. This wiki article explains what I mean:
http://en.wikipedia.org/wiki/Separation_of_concerns

All this daemonization, setuid/setgid, SIGINT, etc. could be in a separate utility library (on top of libwebsocket) and libwebsocket will lose nothing, in contrary it will become simpler, more maintainable and will better serve its purpose.

I can't imagine any sane program that relies on SIGINT handling in networking library. It's like having thesaurus unicode support library (like ICU). "Why not" or "because it's a common pattern" are bad arguments for adding some unrelated things.

It's why Unix is so cool - because each tool does only one job and does it perfectly well. It's impossible to to do daemonization, setuid/setgid, SIGINT handling inside LWS correctly for any complex application. It is good only for examples and small demo applications. Please, don't increase library complexity with more useless runtime configurations.

**Comment by andrew-canaday** [comment]
At the New York Times, we currently use libwebsockets +libev to dispatch
*all* browser notifications to end-users. The built-in sigint handling *is*
sanely incorporated into our application and nets us exactly the runtime
behavior that is required for our services - though, I *understand your
objection*. Philosophically, it makes sense. :)

However, as Andy has pointed out, there are already *many* users utilizing
libwebsockets in a variety of production environments. *Not breaking the
product for them is critically important.* My guess is that some people in
the embedded world, in particular, *are* leveraging the built-in
daemonization and are happy about it.

*As was indicated earlier*, you can *opt out of any/all of the features you
find offensive* - including ev_break utilizing either one of our patches.
 What you say makes perfect sense, but we have to be pragmatic about the
product in order to be good to the users. :)
At present, libwebsockets *is* a little more than a networking library, as
evidenced by the functionality which is provided *and* leveraged.

Thanks!
-Andrew

**Comment by wonder-mice** [comment]
> At the New York Times, we currently use...

Let's don't get personal. It makes no kind of argument and without code review it's hard to tell how sane anything is.

This "functionality" was never documented and never was a part of public contract. The only people who rely on it, either the authors of that change or found it while hacking through the sources. It's an undocumented detail of internal implementation, it's not safe to rely on it. Library shouldn't even try to maintain all internal junk for some miracle "compatibility".

Also, making a world a better place takes an effort from both sides. Sometimes you have to break your clients to evolve in right direction. Cocoa (from Apple) is a good example, each time they release a new version, a lot of things break. But their API and library design is very clean and simple (well, mostly) and constantly improving. Compatibility shouldn't sacrifice long term goals and justify bad design.

Another example (sorry, I'm guilty). Why libev is so badass? Besides other reasons, because they don't allow ANY garbage and unrelated stuff into the library. It's a tool sharp as a knife. Wouldn't it be nice to have sharp-as-a-knife tool for websockets as well?

**Comment by andrew-canaday** [comment]
I didn't take anything personally, and certainly didn't intend my response
to seem personal either. Overall, I think this is a constructive and
healthy dialog. A lot is lost in the ambiguity of e-mail. :)

I'd like to reiterate that I *completely agree with you*, in pinciple. From
my perspective, replacing the default interrupt handling in our client code
is trivial. In fact, the inclusion of the SIGINT handling in canonical
libwebsockets *at all* is *entirely accidental in the first place*: the
introduction of the libev code occurred when another github user cloned a
fork I had created for prototyping *only* and submitted a pull request.

That being said, I don't know how many production instances in the wild
rely on the undocumented feature. I'm merely trying to be cautious about
breaking code, as a courtesy to other end-users of the library. I'm
certainly not advocating that it be left in on my behalf. I have no real
stake in the matter.

However, Andy had expressed some trepidation about breaking functionality
for existing users - one of the unwritten guidelines of the project
evolution to date, and leaving the functionality in with an opt-out
mechanism seems a reasonable way to satisfy you sensible objection in a
manner that is also safe for other users.

Would documenting the feature as deprecated with an explicit sunset period
be amenable to you? At the end of the day, it's really up to Andy. Frankly,
I don't really care.

Be well,
-Andrew
