### ISSUE TITLE
Where to find the sources for the ‘Simple demo server’ example.

### ISSUE THREAD

**Issue by symbolix** [warmcat/libwebsockets#2644]
Hi,
I would like to study the example provided here, on the landing page of the project:
[Simple demo server](https://libwebsockets.org/testserver) 

I would like to see how the front-end and the back-end is implemented. Is that available somewhere?

Thank you!

**Comment by lws-team** [comment]
Everything is in the lws tree... I implement that using lwsws

https://libwebsockets.org/git/libwebsockets/tree/lwsws?h=main

and various protocols

https://libwebsockets.org/git/libwebsockets/tree/plugins?h=main

because I use lwsws to serve or reverse-proxy everything.

But you can also find the same protocols built to serve in libwebsockets-test-server

https://libwebsockets.org/git/libwebsockets/tree/test-apps?h=main
