### ISSUE TITLE
http client timeout issue

### ISSUE THREAD

**Issue by ManojKumarChauhan** [warmcat/libwebsockets#2646]
I am getting http connection error (LWS_CALLBACK_CLIENT_CONNECTION_ERROR) for http client if there is some delay between lws_client_connect_via_info and lws_service.

Using following functions:

lws_create_context();
lws_client_connect_via_info();

// delay of 15 seconds

lws_service(context, 0);

But if there is no delay then the connection established successfully.

Can someone suggest how to handle the case of delay? Whether delay is 15 seconds or 1 minute the connection should not be closed.

**Comment by lws-team** [comment]
> Whether delay is 15 seconds or 1 minute the connection should not be closed.

You will have to explain your theory about that to the server you're talking to as well, because that also is not going to wait long for you to get on with what you're doing before hanging up on you.  It's like you are ringing someone on the phone but not saying anything for 15 seconds, the recipient of your call is just going to hang up.

Connections from both sides are subject to timeouts, you can adapt it on lws side but the problem here is you think you can go away from the event loop for 15s and that's perfectly OK... it isn't.  Do your 15s thing either before trying to arrange the connection or in its own thread without blocking the event loop.

**Comment by ManojKumarChauhan** [comment]
The issue is on client side as the connection is broken by client.  Please reopen this issue. OR should I create a new issue? I will share the code.
