### ISSUE TITLE
delayed response from libwebsockets-test-server-extpoll

### ISSUE THREAD

**Issue by tetti-de** [warmcat/libwebsockets#2662]
With the original source code  (4.3.2) after  calling http://localhost:7681/ the first GET response (200) comes after 13 seconds. Browser timed out. No display in the Browser firefox 101

Changing line test-apps/test-server.c:694 from

n = lws_service_adjust_timeout(context, 5000, 0);
to
n = lws_service_adjust_timeout(context, 2000, 0);

the response time changed from 13 seconds to 6 seconds and the app starts in the browser.

I think the response time should be independent of this timeout parameter.

**Comment by lws-team** [comment]
1) Since v3.2 the way idle is handled changed in lws, if nothing to do it no longer spins in the service loop but does nothing.

2) Don't use extpoll, it's off by default for a while and there's a better replacement, option 3 in this list

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.event-loops-intro.md

I can't get rid of it because users have used it but it is deprecated for years in all but name.
