### ISSUE TITLE
lws_callback_on_writable one second delay 

### ISSUE THREAD

**Issue by Arenoros** [warmcat/libwebsockets#2738]
I encountered a problem with multi-threaded message processing in windows. If I call lws_callback_on_writable in a separate thread, there is a 1 second delay between calling lws_callback_on_writable and when LWS_CALLBACK_*_WRITEABLE actually happens.
The question is, am I using the library incorrectly or is it a bug of working on windows?

On linux the same example works correctly.
Tested on versions 4.3.0 and 4.3.2

**Comment by lws-team** [comment]
This is not supported.

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.event-loops-intro.md

**Comment by Arenoros** [comment]
I apologize for the possibly dumb question, but is it possible to implement the required behavior through another event loop like libev or libuv?

**Comment by lws-team** [comment]
You can use libev or libuv OK, but event loops want to operate in a single thread.

The problem is you want to modify the (possibly sleeping) wait from another thread, what happens with that depends on the platform and event library, and the "phase of the moon" without locking.  It is the cooperation between threads on the wait that makes trouble, not the flavour of the event loop.

You can do it but you must wake the lws event loop thread using lws_cancel_service() and do the change to the wait using lws apis from there.  Eg this kind of thing

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/ws-server/minimal-ws-server-threads/protocol_lws_minimal.c

**Comment by Arenoros** [comment]
Thanks for the quick response
