### ISSUE TITLE
Connection to different websocket servers

### ISSUE THREAD

**Issue by mattermat** [warmcat/libwebsockets#2759]
Is it possible to connect to and receive data from different websocket servers at the same time?

If yes, do I need to have a `struct lws *` for each server I want to connect to or have I simply to create one `struct lws_client_connect_info` for each server and then connect via`lws_client_connect_via_info()`?

If the right way is the second one and if I want to use the same protocol for each server, is there a way to know from inside the callback function which is the server sending the message?

Thanks.

**Comment by lws-team** [comment]
Yes.

struct lws is opaque in lws, you can't directly create them since the type isn't public.

Instead one is created for each connection by the other apis like `lws_client_connect_via_info()`.

You can tag the client connection with your own object or pointer at creation time

```
        void *opaque_user_data;
        /**< This data has no meaning to lws but is applied to the client wsi
         *   and can be retrieved by user code with lws_get_opaque_user_data().
         *   It's also provided with sequencer messages if the wsi is bound to
         *   an lws_seq_t.
         */
```
https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n185-190

Later when you are getting callbacks from it, you can use ` lws_get_opaque_user_data()` as mentioned there to get your pointer back from the wsi and find out whatever you have in there (eg, string of the server name).

**Comment by mattermat** [comment]
It works perfectly fine when receiving data. Now I can know from which servers the message is coming from.

But is there a similar approach for `lws_write`? How can I tell lws to which server send my message?
It looks like with `lws_write` I cannot choose the recipient (and currently the online documentation is unreachable).

Thanks!

**Comment by lws-team** [comment]
You may only use lws_write() from WRITEABLE callback.  So the wsi peer you may write to is already decided by the wsi the WRITEABLE callback came in on.  And that was ultimately targetted to a particular wsi by lws_callback_on_writeable(wsi).

If you want to track wsi, eg to direct writes at them from other callback events, you must take care to understand their connection can close and their be destroyed any time around the event loop, invalidating the wsi object you are keeping a pointer to.  Because, eg, the other side may hang up on you at any time.  They won't be deleted from under you while you're in a callback but after you return to the event loop.

You must handle the CLOSE cb on any wsi you track like that to remove it from your wsi list before the wsi object is dedtroyed, so you cannot keep touching it after it's gone.

**Comment by mattermat** [comment]
So, basically I will call lws_callback_on_writeable(wsi) as soon as I need the WRITEABLE callback and then check that the wsi that is actually writeable is the connection I'm targeting. If not, I would have to call again lws_callback_on_writeable(wsi) until the writeable connection is the one I want to target.
Ok, makes sense.
My only doubt is if calling lws_callback_on_writeable(wsi) over and over until the connection I need is available could generate a backlog on the messages that I'm receiving. Is my doubt valid or am I missing something?

**Comment by lws-team** [comment]
> So, basically I will call lws_callback_on_writeable(wsi) as soon as I need the WRITEABLE callback and then check that the wsi that is actually writeable is the connection I'm targeting. I

No.  You ask for the callback on writeable **for the wsi of the connection you are interested to write to**.  You will get a callback on that connection, with its wsi, when there's space for you to write something more, or never if the connection is dead or closes before it becomes writeable.
