### ISSUE TITLE
Integrate filedescriptor into eventloop

### ISSUE THREAD

**Issue by miket-82** [warmcat/libwebsockets#2762]
Hi,

I am using libwebsockets to run an http server. It is required to forward received data to libcurl.

For several reasons, the best way seems to be integrating libcurl's multi socket interface into libwebsockets' eventloop.

Basically this interface looks like this:
- libcurl provides a filedescriptor
- libcurl provides information on when to call `curl_multi_perform()` next: POLLIN/POLLOUT/POLLERR/timeout
- libcurl reads data from socket by itself during `curl_multi_perform()` call

First, the adopt mechanism (`lws_adopt_descriptor_vhost`) looked suitable. Unfortunately it turned out that a POLLIN event apparently leads to libwebsockets  reading the data and passing it to the callback.

Is there a way to hook a foreign filedescriptor into libwebsockets' eventloop (i.e. its poll calls) and get a callback once something happens (POLLIN/POLLOUT) on this fd?

Many thanks in advance!

**Comment by lws-team** [comment]
>  POLLIN event apparently leads to libwebsockets reading the data and passing it to the callback.

Yes, it has "adopted" the socket into lws using that api.  If that's what you wanted. it's what you want.

As you say what you want is integration at the event loop level.  I would guess what will give best results is instead of giving libcurl or lws primacy over the event loop, use eg a libevent foreign loop that your app owns and lws and libcurl participate on.  You can look at the "foreign" event loop examples to see how that would work, lws is just a participant on your loop then and presumably that's something libcurl can deal with too.

**Comment by miket-82** [comment]
Thank you for the very fast reply.

Technically it makes perfect sense and I was thinking about this as well. Background of my approach was to avoid the need for an additional dependency.
