### ISSUE TITLE
Mailing list broken

### ISSUE THREAD

**Issue by MartyMcFlyInTheSky** [warmcat/libwebsockets#2779]
I wanted to join the mailing list at https://libwebsockets.org/mailman/listinfo/libwebsockets but it doesn't seem to work. The site is not reachable. I would like to join the mailing list because our company requires assistance with certain aspects of the build process. Is the mailing list still available?

**Comment by lws-team** [comment]
Mailman requires python 2 and that seems to be dead.  I could put off updating my server arrangements forever because of that or update everything else and not have mailman any more.  So after dragging my heels a long time I could not put it off any more and modernized everything else, losing mailman2.

I don't want to serve and admin mailman 3 which is some ghastly new web stack I would have to serve too, the alternatives I looked at seem even worse.

Honestly I don't know what to do about it and I feel kind of lumbered with this problem.... it wasn't enough to do the work on the project, I have to lie awake worrying about mailman for my sins.  Googling around many other projects have had to give up their ml for the lack of any good way to do it themselves.  I run my own email stack it's not like I am a shrinking violet.

You can ask here but tbh I don't care if your company "requires assistance", if I can answer it quickly or there's some advantage for the project I will look at it if not, I have other things to do I like more than free support.

**Comment by MartyMcFlyInTheSky** [comment]
I understand your concern. Of course we're willing to add value to the project where we will see fit, however for that we first need to get our feets wet. Our only concern is that we can get libwebsockets up and running in time. Looking good so far however. I will keep posting here, don't worry about mailman.
