### ISSUE TITLE
Building libwebsockets for OP-TEE

### ISSUE THREAD

**Issue by WatetKhetHor** [warmcat/libwebsockets#2809]
I've been trying to build libwebsockets for OP-TEE running on a TI AM437x HS (an arm platform). I'm using Yocto to build; here's the version string for OP-TEE, which is displayed on boot:

```
I/TC: OP-TEE version: ti2019.05-rc1-dev (gcc version 8.3.0 (GNU Toolchain for the A-profile Architecture 8.3-2019.03 (arm-rel-8.36))) #1 Tue Nov 29 17:49:12 UTC 2022 arm
```

I'm using libwebsockets version 4.3.2.

OP-TEE support is documented for libwebsockets:

https://libwebsockets.org/lws-api-doc-main/html/md_READMEs_README_build.html#optee

I'm specifying `-DLWS_PLAT_OPTEE=1` to CMake, but a number of libwebsockets source files include `errno.h`, which is not provided by OP-TEE's minimal libc. I have tried specifying an additional `-I`/`-isystem` option to pick up the `errno.h` that comes with the toolchain (gcc) but this causes further problems with headers included by it, and I think it should only by used with GNU's libc.

Is OP-TEE still a supported platform for libwebsockets? If so, how should I resolve the issue with `errno.h`?

Thank you for your help!

**Comment by lws-team** [comment]
I haven't built lws for OPTee for several years.

errno.h should normally be a toolchain thing afaik, to the point the toolchain understands it's targeting a particular OS or libc.  For OPTee afaicr it's built bare metal and doesn't really have a posix errno concept itself.  I think lws wants it only because of extern int errno and POSIX names like EAGAIN for networking.

At the time I used lws with it, OPTee did not have its own syscalls to passthru a posix-like environment for networking to the normal world helper, I had to make my own set of syscalls and write the normal world helper code as well.  Some time after that I think they added an offical syscall set so that part should be easier now.

There should be a way included with that stuff in OPTee to enumerate the posix-ish return values that can come from socket() etc systcall I would expect.
