### ISSUE TITLE
Mailing list down?

### ISSUE THREAD

**Issue by jin-eld** [warmcat/libwebsockets#2818]
Hi,

@lws-team sorry if this is the wrong place to ask about this, but the link to the mailing list does not seem to work (tried last week, tried just now):
https://libwebsockets.org/mailman/listinfo/libwebsockets

I have an issue (assertion) which I wanted to discuss there, but I can not reach the mailing list page, so I can not subscribe. Is this a temporary issue, or was the list abandoned in favor of github issues?

**Comment by lws-team** [comment]
I don't have a way to run mailman at the moment.  Any reasonable OS no longer has python 2.  Mailman 3 has a stack I don't want to run.  I put off upgrading my server for a long time because of that, but eventally I realized for me, it's just not worth the sleep I was losing about it, and updated everything else and wait for some other solution for mailman.  The archives are up since they're static html.

For now we just have github.
