### ISSUE TITLE
Reload TLS certificate while server is running

### ISSUE THREAD

**Issue by thefallentree** [warmcat/libwebsockets#2890]
How to reload TLS certificate for a websocket context while the server is running?

**Comment by lws-team** [comment]
If you really really have to do it, it might be the the simplest way is to look at how lwsws handles "deprecation".  This allows arbitrary changes in the server without upsetting any existing connections, by allowing old and new to run in parallel.

An existing lws process / lws_context is marked as "deprecated", leaving it running but making it drop its listen sockets.  When the number of connections it is servicing reaches zero, because people close their browser tab or whatever over time, the process exits.

After the initial deprecation step, you can start a new lws process / lws_context with the changes (the new cert).  It can grab the listen sockets OK since the deprecated guy dropped them.  The server app must be able to handle more than one process, eg, accessing the backend while the deprecated one continues to exist.

**Comment by thefallentree** [comment]
Hi Andy, i don’t think it’s necessary to close the listening socket or
creating new context: to reload the cert, we just need to recreate the SSL
context and start to use it on next “accept event” swap. ( that process
will re-read the cert on disk).  There is no need to reopen any existing
sockets.

**Comment by thefallentree** [comment]
here is a example , we just need a function that does the same for lws 
```
    auto *ctx = tls_server_init(port->tls_cert, port->tls_key);
    if (ctx == nullptr) {
      error("Failed to reload TLS context for port %d\n", port->port);
    }
    // no race condition here since connection listener operates on main thread() ,so does this function
    auto *old_ctx = port->ssl;
    tls_server_close(old_ctx);
    port->ssl = ctx;
```
