### ISSUE TITLE
is event LWS_CALLBACK_CLIENT_WRITEABLE called only when lws_callback_on_writable called?

### ISSUE THREAD

**Issue by bethebest0622** [warmcat/libwebsockets#2900]
In my understanding, `LWS_CALLBACK_CLIENT_WRITEABLE `will be received when i call `lws_callback_on_writable`.

but in some siutations:

after I called, `lws_callback_on_writable`.

`LWS_CALLBACK_CLIENT_WRITEABLE `called more than once.

could you let me know why it called twice, and how shall i handle it, just ignore it is ok?

**Comment by lws-team** [comment]
Under some conditions, eg, if the underlying write() or send() on the socket only partially accepts what you're trying to write (because it is longer than the socket will allow), lws has to so some work in the background to stash the remainder and ask for another write when it take any more.  Writing huge things is counterproductive because of this since lws can only clear in one time around the event loop what the underlying socket will take, and we don't control that; it's to do with link bandwidth and how the tcp window is managed on the connection.

When it has to do this partial send management, since it's going to swallow the next WRITEABLE(s) to clear the backlog, it is no longer sure if you asked for a WRITEABLE too during that.  So after clearing the backlog, it asks for one extra WRITEABLE at the end in case you had been expecting one.

If you take the approach that WRITEABLE is just an indication you can write something now, and you look at the connection state (in the examples, it means the contents of the pss associated with the wsi, that you define and control) to understand what you should write next, and nothing if nothing to do, you will also cover this case.
