### ISSUE TITLE
Change service thread

### ISSUE THREAD

**Issue by uis246** [warmcat/libwebsockets#2941]
I want my WS server app to accept sockets on one thread, do handshake, do authentication and if authentication succeeds, then forward socket to another thread that handles authenticated clients.
Is it doable and how?

Edit: tls is also used

**Comment by lws-team** [comment]
This isn't a good way because the key point in lws is the event loop... that must be a single thread.  You're better off leaving it as it is to do its job.

There are two ways I can think to approach it

1) Do what you're planning, but drop this idea of a separate thread in favour of all in one event loop thread.  The state of the connection holds a bool (in what the examples call the pss) saying if it's authenticated or not.  In the connection callback, you can switch early to two separate subhandlers depending on if authenticated or not to remove the possibility of authorized actions coming on unauthorized connections because you forgot an if () somewhere.

2) Personally  I use lwsws effectively as a reverse proxy, that gets the connection content from separate processes over a unix socket.  This is cleanly extensible, since lwsws only needs to know the unix socket that binds to which bit of the url space, and works with h2 + ws.  If I am developing a service, or the service crashes, the downtime only extends to that one service and lwsws can show an error page for accesses while it's down.  At the same time, the server processes don't know about the frontend and their job ends at providing http or ws services over a unix socket. I don't use it with central auth (the services handle their own auth if they need it in my usecase).  I think basic auth would work at lwsws frontend stage but I am not sure about anything more complicated.

**Comment by lws-team** [comment]
... oh also

3. lws supports JWT

**Comment by uis246** [comment]
I want to do it so any load created by unauthenticated clients won't affect processing of authenticated clients. So no matter how many connections will flood server, no matter how expensive authentication, known-good clients will be processed in near-realtime.

It seems lws already supports almost what I want with `int
lws_service_tsi(struct lws_context *context, int timeout_ms, int tsi)`. Now somehow struct lws needs to be moved to another `context->pt`

**Comment by uis246** [comment]
Also is there a way for LWS periodically call some function for server? Or maybe some callback? Basically call tick function.

**Comment by lws-team** [comment]
https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.lws_sul.md
