### ISSUE TITLE
Where is  the file of libwebsockets.so

### ISSUE THREAD

**Issue by TDCQ886** [warmcat/libwebsockets#2950]
I cannot find the file named libwebsockets.so. I make the file by  cygwin.  
cmake -D CMAKE_BUILD_TYPE="Debug" -G "Unix Makefiles" -DLWS_WITH_SSL=0 -DLWS_WITH_ZIP_FOPS=0 ../
make

after i do it ,everything is ok ,and no error happened,but i can only find same files  such as libwebsockets.a libwebsockets.dll.a cygwebsockets-9.dll libwebsockets-test-client.exe and so on . I want to get the file of libwebsockets.so.where is it?

**Comment by TDCQ886** [comment]
I search everywherer in my computer. The Resulut is that I can't find a file with the suffix so

**Comment by TDCQ886** [comment]
Settings:  (For more help do cmake -LH <srcpath>)
---------------------------------------------------------------------
 LWS_WITH_STATIC = ON
 LWS_WITH_SHARED = ON
 LWS_WITH_SSL = 0 (SSL Support)
 LWS_SSL_CLIENT_USE_OS_CA_CERTS = 1
 LWS_USE_WOLFSSL = OFF (wolfSSL/CyaSSL replacement for OpenSSL)
 LWS_WITHOUT_BUILTIN_SHA1 = OFF
 LWS_WITHOUT_BUILTIN_GETIFADDRS = OFF
 LWS_WITHOUT_CLIENT = OFF
 LWS_WITHOUT_SERVER = OFF
 LWS_LINK_TESTAPPS_DYNAMIC = OFF
 LWS_WITHOUT_TESTAPPS = OFF
 LWS_WITHOUT_TEST_SERVER = OFF
 LWS_WITHOUT_TEST_SERVER_EXTPOLL = OFF
 LWS_WITHOUT_TEST_PING = OFF
 LWS_WITHOUT_TEST_ECHO = OFF
 LWS_WITHOUT_TEST_CLIENT = OFF
 LWS_WITHOUT_TEST_FRAGGLE = OFF
 LWS_WITHOUT_EXTENSIONS = OFF
 LWS_WITH_LATENCY = OFF
 LWS_WITHOUT_DAEMONIZE = ON
 LWS_USE_LIBEV =
 LWS_USE_LIBUV =
 LWS_IPV6 = OFF
 LWS_UNIX_SOCK = OFF
 LWS_WITH_HTTP2 = OFF
 LWS_MBED3 = OFF
 LWS_SSL_SERVER_WITH_ECDH_CERT = OFF
 LWS_MAX_SMP = 32
 LWS_WITH_CGI = OFF
 LWS_HAVE_OPENSSL_ECDH_H =
 LWS_HAVE_SSL_CTX_set1_param =
 LWS_WITH_HTTP_PROXY = OFF
 LIBHUBBUB_LIBRARIES =
 PLUGINS =
 LWS_WITH_ACCESS_LOG = OFF
 LWS_WITH_SERVER_STATUS = OFF
 LWS_WITH_LEJP = OFF
 LWS_WITH_LEJP_CONF = OFF
 LWS_WITH_SMTP = OFF
 LWS_WITH_GENERIC_SESSIONS = OFF
 LWS_STATIC_PIC = OFF
---------------------------------------------------------------------
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    LWS_WITH_ZIP_FOPS


-- Build files have been written to: /home/NINGMEI/libwebsockets-v2.1.0/BuildLinux

the debug info from cmake . LWS_WITH_STATIC = ON
 LWS_WITH_SHARED = ON .

**Comment by lws-team** [comment]
> cygwin
> exe
> .so

... when you feel that frustrated feeling, the universe is helping you by telling you there's something wrong with your model of what's going on.  It's best to understand that so you can stop "trying to prove the earth is flat" or whatever is wrong with your internal idea of how things are, and learn about how things actually are so you can succeed with reality.

Dynamic libs are an OS / loader-specific thing... for example on mac they're called .dylib, windows they're .dll and linux .so.  They're doing the same job but appropriate for each OS and are not interchangeable or compatible.  There is no ".so for windows".

If you use cygwin, it's cross-building for windows, the .dll is correct for that instead of .so.

You should back up and reexamine why you thought you needed a .so for that case.

**Comment by TDCQ886** [comment]
Thank you for your answer. I am Doing a cross-platform project that base on the libwebsocket. on windows they are called .dll,then on linux they are called .so However I Hand no virtual machine of linux on my computer.  I install the cygwin and work on it. This is my first time using it and thus not understanding it ,I thought it would generate something for linux and same as compiled in a virtual machine of linux. thanks a lot
