### ISSUE TITLE
Handling Misdirected Requests (HTTP Status 421)

### ISSUE THREAD

**Issue by nidoro** [warmcat/libwebsockets#2975]
Recently I came across a curious "feature" of HTTP/2 that I'm not sure how to handle on libwebsockets. As far as I can understanding it, after performing a request A to server A.example.com, the connection used for that request can be reused to perform request B to server B.example.com if:

1. HTTP/2 is used
2. A.example.com and B.example.com point to the same IPv4
3. Both servers share a wildcard TLS certificate

This "feature" means that the request may be misdirected if servers A and B are not "interchangeable", i.e., if it actually _does_ matter the host to which the request is directed to. If that happens, the server is supposed to return status [421 Misdirected Request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/421), which hints to the client (e.g. browser) that they should not have reused the connection and maybe should retry it.

There is an extensive discussion on this topic here: https://bugzilla.mozilla.org/show_bug.cgi?id=1420777

It so happens that I'm in this situation now. I have two libwebsockets vhosts listening on port 443 and they share a certificate. I serve HTML pages that fetch resources from both vhosts. On Firefox, sometimes connections get reused, and when it does, my server doesn't know how to handle the request. I believe I'm supposed to detect, somehow, that the request has been misdirected, and return 421. But I don't know how this detection can be done using libwebsockets. So I ended "disabling" HTTP/2 on those vhosts (setting `lws_context_creation_info.alpn` to `"HTTP/1.1"`), which makes everything work again.

How can I properly handle that case?

**Comment by lws-team** [comment]
> Both servers share a wildcard TLS certificate

This is a client bug, not a server problem.

The connection should NOT have been tagged at the client as good for *.xyz.com because that was the cert it was validated by, but as good for the hostname used for DNS lookup, eg, a.xyz.com, ONLY.

b.xyz.com may have completely different dns arrangements and need to go to a different IP altogether.  Skipping the DNS resolution for b.xyz.com because the existing connection saw a cert with *.xyz.com is completely wrong at the client.

Source: wrote this code myself for lws client connection folding.

**Comment by nidoro** [comment]
I see. That's too bad. I can't use HTTP/2 with major browsers bugged like that. Thanks for the answer.

Out of curiosity, if that's a bug, do you know what is the actual situation in which 421 Misdirected Request should be returned by the server?

**Comment by lws-team** [comment]
The server can notice that any host: header from the client coming on the tls-validated connection does not match the vhost name used when the connection was validated, and choose to reject it.  In other words the server may detect an insane client and deal with it by sending 421 instead of trying to do whatever it was asking.

But that isn't the same as fixing the client to not ask the wrong server, it's just forcing the client to fail.

**Comment by nidoro** [comment]
> b.xyz.com may have completely different dns arrangements and need to go to a different IP altogether

That's guaranteed by condition number 2:

> 2. A.example.com and B.example.com point to the same IPv4

So, it is assumed that the client already has performed DNS lookup and knows the IP of both hostnames.

Does that make any difference in your answer?

**Comment by lws-team** [comment]
... when the connection (tcp + tls) is validated on lws, it's bound to a specific vhost.

You can't use one validated connection, validated on one vhost's cert, wildcard or no, for multiple vhosts.

**Comment by lws-team** [comment]
> might permit

Lws binds to a vhost on connection validation as I desctibed.

You might be getting paid to worry furthrt about it, but I'm not :-)

**Comment by nidoro** [comment]
No problem. Thanks again. Honestly, I wish I could help support libwebsockets, and hope will be able to in the future.
