### ISSUE TITLE
Query about lws_write

### ISSUE THREAD

**Issue by jongsun89** [warmcat/libwebsockets#2994]
Hello @lws-team.
I have query about lws_write.
I have made a server with libwebsocket to real-time stream video data by websocket.
I have met some issues , when network connection is slow between server and client.
server side kernel send buffer is always full.
So, i put the code in lws_writeable callback to check and calculate SO_SNDBUF and TIOCOUTQ to get size of free buffer.
If the size of free buffer is more than data to be sent in one time, then send. if not, drop the data .
I have another issue here. SO_SNDBUF is so small, then data is always dropped .
In this case, if i just send the data by lws_write, how lws_write manage this ?
(case: SO_SNDBUF is smaller then the size of the data to be sent at once)
Does lws_write handle all the data to be written , and then lws_write returned ?

Thank you.

**Comment by lws-team** [comment]
lws_write() never blocks, in lws the socket fds are all nonblocking.

It will add protocol-specific headers behind what you gave it, and try to send() it all.

The send() may return an error that nothing could be sent due to hangup on the connection etc, a sent length which was all of it, or a "partial send" length that the kernel side actually accepted.

(Notice that the way the send syscall works, the data you are trying to send is ALL copied into kernelspace before the send attempt.  So if you set this buffer huge, send() will become very cpu intensive and slow, even if it's not able to send any of the buffer once it tries.  So trying to send huge amounts each time is not the solution.)

If a partial send happens, the remainder is buffered on the heap by lws and it will not let your code see any further WRITEABLE callbacks for that connection until lws itself has iteratively drained this partial buffer itself, by swallowing WRITEABLEs, sending what it can, and asking for new ones.  So in this way lws will take responsibility for making it work transparently and concealing the partial via the heap, but obviously that is more expensive.

Partial sends are not good, but since POSIX only indicates an event on the socket that it can be written to, not by how much (TIOCOUTQ is only supposed to apply to ttys and isn't going to be very portable)  and this can change dynamically kernelside, the middle way is only try to send one or two ethernet frames' worth (~1400) a WRITEABLE.  If you got a WRITEABLE indication, that much is probably going to be accepted on Linux anyway.

You can try anothe SO_SNDBUF option to preset the output buffer size kernelside.  But I think no guarantee the kernel will listen to your request and again behaviour won't be portable.

Many video sending schemes use UDP packet writes on a timer instead.

**Comment by pppaulpeter** [comment]
> The send() may return an error that nothing could be sent due to hangup on the connection etc, a sent length which was all of it, or a "partial send" length that the kernel side actually accepted.
> 
> (Notice that the way the send syscall works, the data you are trying to send is ALL copied into kernelspace before the send attempt. So if you set this buffer huge, send() will become very cpu intensive and slow, even if it's not able to send any of the buffer once it tries. So trying to send huge amounts each time is not the solution.)
> 
> If a partial send happens, the remainder is buffered on the heap by lws and it will not let your code see any further WRITEABLE callbacks for that connection until lws itself has iteratively drained this partial buffer itself, by swallowing WRITEABLEs, sending what it can, and asking for new ones. So in this way lws will take responsibility for making it work transparently and concealing the partial via the heap, but obviously that is more expensive.
> 
> Partial sends are not good, but since POSIX only indicates an event on the socket tha
Hi Andy,

If a partial send occurs, lws internally buffers the unsent portion of the data on the heap (dynamic memory allocation), correct? Could you point out where the source code for this is? thanks a lot!
