### ISSUE TITLE
[Question] How to trust multiple custom CA certificates without using the system default CA store?

### ISSUE THREAD

**Issue by PJ2501** [warmcat/libwebsockets#2997]
Hi:
I'm trying to create a tls client and trust multiple custom ca certificates, and I notice that I can register the ca file to ssl context in the LWS_CALLBACK_OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS callback.
I want to know if it's the right way, and if there is a better way?
Thanks!

**Comment by lws-team** [comment]
It's "a way", it's not wrong.  Its drawback is that it exposes the native tls library context, so your user code has to be specific to, eg, openssl or mbedtls or whatever.  All the other times lws is a point of contact with the tls library, it conceals the actual tls implementation so the user code doesn't change or have to know.  On the plus side, using this, lws doesn't have to understand whatever it was you wanted the tls context for since you can just deal with it in your user code.

Have you tried giving a cert bundle (concatenated PEMs) as the CA file to the vhost at vhost or context creation time?

**Comment by PJ2501** [comment]
Thank you for your reply.
My project is based on openssl, so this drawback is acceptable to me. I think I understand how to do it.
