### ISSUE TITLE
How to reduce memory usage of libwebsockets?

### ISSUE THREAD

**Issue by tanhangbo** [warmcat/libwebsockets#2998]
Currently, I have **one libwebsockets client instance** connecting to a server for data transmission. While debugging with Visual Studio, I noticed that the function lws_plat_init, which is related to the macro **FD_HASHTABLE_MODULUS, allocates 3840K** of memory at the beginning of the function. Could you please explain the purpose of FD_HASHTABLE_MODULUS and the impact of reducing its value? Additionally, are there any other macros that I can optimize?

**Comment by lws-team** [comment]
That only exists for windows... a good optimization then is don't use windows.  lws in esp32 for example fits wholly in 100K.

It will take it longer to match the socket to its wsi if you reduce it, if you have few connections, you're not going to notice it.

Almost everything configurable defaults to modest numbers, because most users are not using lws on windows.
