### ISSUE TITLE
Use of possibly uninitialized variable body_chunk_len in lib/roles/h2/http2.c

### ISSUE THREAD

**Issue by schuettecarsten** [warmcat/libwebsockets#3004]
Use of uninitialized variable in lib/roles/h2/http2.c.
`lws_filepos_t body_chunk_len` is declared in line 2819 and used later, but might not be initialized.

Is it safe to simply initialize this with 0?

**Comment by lws-team** [comment]
Thanks... we only try to use `body_chunk_len` if `lws_h2_parser()` returns 0 or 2.  Going through `lws_h2_parser()`, every way out of it returning 0 or 2, sets `body_chunk_len` (it's passed in pointed-to by `inused` arg to lws_h2_parser()).  So I believe this is a false positive.

FWIW F39 gcc 13.2 did not blow any errors AFAIK.

Of course, in terms of an error coming out of the compiler and killing the build, it doesn't make much odds, it still emits an error rightly or wrongly the same.  But since it's wrong, we only need to help the compiler see it's wrong so just zeroing should be fine.

I pushed a patch doing that (and moving the declaration scope inside the loop) on main + v4.3-stable.
