### ISSUE TITLE
How to get http response header when using secure stream?

### ISSUE THREAD

**Issue by gn01642884** [warmcat/libwebsockets#3007]
Hi, I'm implement my code on embedded device(lws-ss client side), and I'm using secure stream APIs to get something on my https server.
I need to get https response header (like context-length or response code)
may I know how to get that?

**Comment by lws-team** [comment]
This kind of information about the transaction is "metadata" in SS, it doesn't want to tie you down to using http so these are defined as metadata symbols in the policy, and you can read them using get_metadata(...).  In the examples it uses "ctype" as the metadata name for Content-Type header...

```
                        "metadata": [
                                { "ctype":              "Content-Type:" }
                        ],
```

and in the state callback

```
        const char *ct;
        size_t ctl;

...

        case LWSSSCS_QOS_ACK_REMOTE: /* server liked our request */

                if (!lws_ss_get_metadata(g->ss, "ctype", (const void **)&ct, &ctl))
                        lwsl_ss_user(g->ss, "get_metadata ctype '%.*s'", (int)ctl, ct);
                else
                        lwsl_ss_user(g->ss, "get_metadata ctype missing");

```

You can also set metadata when preparing the stream transaction, which for http sets the related header, eg

```
        switch ((int)state) {
        case LWSSSCS_CREATING:
                if (lws_ss_set_metadata(lws_ss_from_user(g), "ctype",
                                    "multipart/form-data;boundary=\"boundary\"",
                                    39))
                        return LWSSSSRET_DISCONNECT_ME;

```

See https://libwebsockets.org/git/libwebsockets/tree/lib/secure-streams for a list of things usable in the policy.

Rather than use http response codes directly, that are specific to http, ss first breaks the code down into treating the transaction as successful (2xx) which will lead to an LWSSSCS_QOS_ACK_REMOTE state on the SS, or an error, which will give ...NACK and allow you to retry.  The exact information is logged and added to the metrics info.

**Comment by gn01642884** [comment]
Thank for response,  for my system for some reason I can't use Json file.
instead, I'm using static policy like below

`
static const lws_ss_metadata_t my_obj1 = {
	.name = "host",
	.value__may_own_heap = (void *)"host:",
	.value_length = 0x5,
	.length = 0,
	.value_is_http_token = 0xff,
},`
`
my_obj2 = {
	.next = (void *)&my_obj1 , 
	.name = "reqhead",
	.value__may_own_heap = (void *)"access-control-request-headers:",
	.value_length = 0x1F,
	.length = 1,
	.value_is_http_token = 0xff,
},
...
`
on my test seems I need to setup "value_is_http_token" value to mapping index under ".../roles/http/lextable-strings.h"

may I know how to set the "value_is_http_token" via API?
I found "lws_http_string_to_known_header" can know the value of that but seem no public API on secure stream

**Comment by lws-team** [comment]
> may I know how to set the "value_is_http_token" via API?

There's no way to do it... you must define this attribute in your policy, be it static (by setting .value_is_http_token) or JSON (by making it a header string).

You can then set the value of it using, eg, set_metadata( ... "reqhead"... ) as usual
