### ISSUE TITLE
You have all of these great secure stream client examples but no tagged release to go with them

### ISSUE THREAD

**Issue by mdeneen** [warmcat/libwebsockets#3046]
Hi,

Are there any plans on tagging a release which includes "modern" features, like the LWS_SS_USER_TYPEDEF macro and friends?

There's been a huge amount of activity and some fantastic examples, I can't be the only person building with Yocto who would rather have a tagged release instead of selecting a random commit from the main branch.

Some of the secure stream examples are over two years old and they can't realistically be used as a starting point because no Linux or BSD release is going to include untagged software.

**Comment by lws-team** [comment]
Hm... it's like it is because unlike the rest of lws, I was paid to do the SS-related work.

And SS is used in Echo and Kindle devices, not sure how many that is but well over 7 figures; despite how it may seem, it's hardly overlooked in some unreleased repo.

I agree a new release would make sense but it requires various things be addressed I am not ready to deal with atm.  You can just pin your recipe in the meanwhile if you want to use it.
