### ISSUE TITLE
External polling is utterly broken on Windows

### ISSUE THREAD

**Issue by emptyVoid** [warmcat/libwebsockets#305]
Version 1.4 (3ae1badae7a05e0982e0dfbcb078da3d4b92a81d)

Due to some crazy macros in lib/private-libwebsockets.h:
```c++
#define LWS_POLLHUP (FD_CLOSE)
#define LWS_POLLIN (FD_READ | FD_ACCEPT)
#define LWS_POLLOUT (FD_WRITE)
```
libwebsocket_pollargs event fields contain some non-cross-platform garbage instead of normal POLLIN, POLLOUT flags.

PS: and as expected libwebsockets-test-server-extpoll.exe does not work at all

**Comment by emptyVoid** [comment]
Moreover ```libwebsockets_serve_http_file``` does not work with large files at all.
Since ```lws_ssl_capable_write_no_ssl``` sets ```sock_send_blocking``` flag, and the only code-path clearing it is in ```libwebsocket_service``` which should not be used with external polling (at least if ```test-server-extpoll``` sample is still correct).

**Comment by warmcat** [comment]
Well on the one hand, I don't use Windows and everything about that is contributed, since I can't test anything.

On the other hand.. the macros you point out are insane alright.  The came in on b47f87b04b6fc83a7fea3a504ea2029768e43847.

If you or somebody else wants to improve them, please send a patch.
