### ISSUE TITLE
Website libwebsockets.org is down, so no examples can be gotten.

### ISSUE THREAD

**Issue by kenkopelson** [warmcat/libwebsockets#3054]
Can you please move the examples into Github, so if your website goes down, or you abandon it, the examples will still be available for people? Really, everything should be under Github, because the repo will stay forever, and it is free, so the repo will not disappear if and when you stop paying.

**Comment by lws-team** [comment]
I have gone to the trouble of running my own for 13 years because I don't want my project to rely on Microsoft.

If you feel entitled to a higher QoS level for the examples than I can provide for free, the best thing is run your own local or public servers, from the examples in-tree, or propose patches to mirror the services elsewhere, not explain to me I 'should' run around making services easier for you to leech for free.  Is there some advantage I have been enjoying from providing you free services to leech I don't know about?  Nothing is coming to mind.

**Comment by kenkopelson** [comment]
I was just letting you know the .org site is down. I don't care if you
bring it up or not. If you did not put that out as a service to the world,
then why? In the README you sure did tout all that you were doing to make a
good tool for others to use. You said the site had hundreds of examples, so
all I wanted to do is look at those. If you have no desire to be of help to
others, you really should just take it all down. You are sending the wrong
message of your motives and intent. Open Source is about creating a world
where software is freely available. And, if you put something out there in
a public repo, it is not LEECHING to make use of what you did. You put it
there, and made it available. If you no longer want to have people blessed
by your efforts, you really should just take it all down. And, for your
information, there IS an advantage that you have been enjoying. Whenever I
use projects that people make available, I always have positive thoughts
towards them, and I say a prayer that they would be blessed for their
efforts. Maybe you don't care about that, but in the end, everyone will
learn just how powerful that is. Who knows what calamities you have avoided
because people like me prayed for your blessing. Also, did you put that
project out there because you wanted something back? What did you expect?
Did you make that known?

Many thanks Andy. Your work has been appreciated, even if nobody actually
said so.


*Sincerely,Ken Kopelson*

**Comment by jotaen** [comment]
I’m certainly not going to involve myself into this conversation, but just as a meta level note, and for potentially helping you @lws-team to put things into perspective, let me say thank you for maintaining and providing this project. I also ended up here due to the website being down, but it’s really no big deal and I can easily work around it. Let me know if you need a hand in regards to hosting, I’m happy to help.
