### ISSUE TITLE
delayed in LWS_CALLBACK_CLIENT_CLOSED  from libwebsocket

### ISSUE THREAD

**Issue by sush126** [warmcat/libwebsockets#3088]
Hi @lws-team ,
                       I am using libwebsocket 4.3.2 version for client application , if i disconnect server and when i am trying to send any packet from client it is taking time to receive LWS_CALLBACK_CLIENT_CLOSED event from libwebsocket . So could you please help me here ? do you have any configure parameters from libwebsocket so that it can reduce this time ?

**Comment by lws-team** [comment]
If your peer or an intermediary 'goes silent', eg because battery died, ethernet cable was removed, there's typically no indication of this from the OS at the server, nothing was transmitted so there's no 'event'.  This is different from taking a server-local network interface down which if it's linux, lws will notice via netlink, and close any ongoing connections that routed through it immediately.

Some tcp timeout waiting for write ACK may catch it, but these can extend to minutes.

If you want faster response look at the connection validity probing, which uses protocol ping/pong and a separate pong wait timeout.

https://github.com/warmcat/libwebsockets/blob/main/include/libwebsockets/lws-retry.h#L25
https://github.com/warmcat/libwebsockets/blob/main/minimal-examples-lowlevel/ws-client/minimal-ws-client/minimal-ws-client.c#L44
https://github.com/warmcat/libwebsockets/blob/main/minimal-examples-lowlevel/ws-client/minimal-ws-client/minimal-ws-client.c#L72

**Comment by sush126** [comment]
Thanks for reply . 
If i use probing using api **lws_client_connect_via_info** it is sending ping/pong after configured timeout . If i need on need basis at runtime is there any lws Api to trigger ping/pong ?

**Comment by lws-team** [comment]
There's an api which lets you do the opposite... you can inform lws that you have seen the connection prove that it's valid by other traffic on it, this resets the timer for sending a PING.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-timeout-timer.h#n276-296

if it's continuously calling this api showing that the connection is "proving itself by other means" more often than the PING time in the lws_retry, then it understands it doesn't need to send a synthetic PING at all.

**Comment by sush126** [comment]
Thanks @lws-team this will resolve my issue.
