### ISSUE TITLE
error when call lws_client_connect_via_info ()?

### ISSUE THREAD

**Issue by bethebest0622** [warmcat/libwebsockets#3097]
I have 50 processes running in one server, each process build two websockets connection, then I got this error:

```
[2024/03/20 09:29:01:9295] N: lws_create_context: LWS: 4.3.99-v4.3.0-314-g8d407988, NET CLI SRV H1 H2 WS SS-JSON-POL ConMon IPv6-absent
[2024/03/20 09:29:02:2434] E: lws_plat_init: OOM on alloc lws_lookup array for 1000000 conn
[2024/03/20 09:29:03:2462] E: ZERO RANDOM FD
```

i think i didnt create 1million connections, is this mean i forgot to release space somewhere?

could you provide some tips or where i shoud pay attention to?

Thanks

**Comment by lws-team** [comment]
By default, contexts set up a map for all possible fds they may use in the process.  The max fds on *nix is set by `ulimit -n` and on Linux, some other layered settings.  So each context is allocating to handle up to the maximum fds it might meet, which seems to be a million on your systemd.  You can check it with`ulimit -n` from your shell, on my Rocky system it returns 1024.

You should be able to tell the context to use a different fd map that doesn't need this map allocation by setting something like `info.fd_limit_per_thread = 20;` or whatever.

It's usually better to have one process with one lws_context, and 50 or 100 connections or whatever on the one lws_context.

**Comment by lws-team** [comment]
No.... when you call open() or socket(), you get an fd returned.  On *nix, you don't know what you will get, but it will be an int between 0 and `uname -n` - 1.  The fd choice is a processwide thing, so although it is deterministic, the actual fd number depends on anything your process and any libraries it may have open.  So lws may only use a couple of sockets, but something else in the process may open hundreds of files, the fd returned may be in the hundreds, not 3 or 4.

For the best speed when your process has a lot of fds open, on *nix lws by default allocates an array that maps the fd number as an index to the wsi it belongs to.  So you can get the wsi just by looking up `map[fd]`.  That is the huge allocation done for each context in the case your process max fd is 1000000.  You can defeat that by setting the context info option mentioned above, it will use a restricted map instead of the given size, and walk it looking for the fd index in there.

**Comment by lws-team** [comment]
Lws works for server as well.  This opens a new socket / fd per connection to the listen socket.  So you may get very large numbers of connections happening, it's good to have the map for doing wsi lookups then since it takes a very small constant time.

In your case you don't care much since only two or so fd expected in use.  It has this smaller array (eg 20) and searches for the fd in that.  It's slower but only a couple of things to search.

The OOM is coming because you have 50 maps / contexts not just one.
