### ISSUE TITLE
can libwebsockets add websocket protocols dynamically?

### ISSUE THREAD

**Issue by cppbitman** [warmcat/libwebsockets#318]
Can I add new websocket protocol to a running  server?
I have tried to enlarge the protocol array (struct libwebsocket_context.protocols). It failed.
How can I realize that ? Help !

**Comment by JoakimSoderberg** [comment]
This is not possible with the current implementation, the way protocols are handled would need to be rewritten, and some API to add additional protocols added. Trying to hack it by enlarging the protocol array I don't think is a good way to do it...

However, what exactly is the use case to be adding extra protocols during runtime anyway? Maybe what you want to do can be solved in some other way? 

I mean, websocket subprotocols intially at least are meant to be some quite stable things, even to the point where registering them is recommended in the RFC: https://tools.ietf.org/html/rfc6455#section-1.9

**Comment by cppbitman** [comment]
I have found the way to solve my problem. Thanks very much.

**Comment by ericblade** [comment]
Sorry to necro an ancient thread, BUT...

When you are implementing WebSocket support into something yourself, but ultimately, it's up to other people who aren't going to be building the binary, to handle defining the services, one or more of those users might find themselves needing to declare a subprotocol, sometime after initial context creation.  

@JoakimSoderberg particularly, in my case, I am adding libwebsockets to use with a game engine, and the ultimate end user of libwebsockets might need to add subprotocol support at any point after they have already done something else with the library, and there's not really a good method to even construct the protocols dynamically to begin with, let alone actually add one to it after the fact.

@cppbitman i know we're talking an ancient necro post here, but if you have any tips for what you ended up doing instead, please lmk :-)

**Comment by lws-team** [comment]
Wow 2015... everything here is long out of date... it'd've been better to ask fresh.

It depends what you mean by 'dynamically'.  If you mean at init, yes you can do it.

Lws has supported plugins for years now... some can be built as part of lws like ssh2 server and demo ones

https://libwebsockets.org/git/libwebsockets/tree/plugins

but lws supports external standalone plugins too

https://libwebsockets.org/git/libwebsockets/tree/plugin-standalone

These are collected at runtime (by walking a plugin dir) at init if you provide a path to the plugins dir at context creation time.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n374-376

If you have explicit vhosts, you have to create a pvo on each protocol name you actually want to allow for each vhost to enable it (the convention is "status" "ok" but any pvo on a named protocol will enable it).  If you just have the default vhost from context creation time, any plugin that was found is enabled for use on it automatically.

Until recently lws used specifically libuv to get the plugins handled in a crossplatform way.  But on master, I removed nearly all the instances where libuv is needed... for *nix platforms plugin support no longer needs it.  It's still required for windows.  If that's a bother, please look at tge *nix implementation and send me a patch on windows plat stuff that does it natively and we'll all be happy.

**Comment by ericblade** [comment]
:) Thanks for the info, but I don't know (I am new to this) if that particularly addresses the point that I came looking for -- wanting to be able to declare a subprotocol name at runtime, at some point after initialization.  As the system is basically a glorified scripting language, it's not easily possible, without saying "OK, if you want to use a websocket subprotocol, you have to define it somewhere at startup", to determine if the user will at some point open a websocket server at all.  I was just hoping to be able to implement the ability to declare a websocket server with a subprotocol sometime after init.  It's not a major loss if I can't. Thanks! :)

**Comment by lws-team** [comment]
Notice "init" means "initializing the lws context".

> declare a subprotocol name at runtime, at some point after initialization

Well, a protocol in lws does have the name, but it needs code as well: it has to point to the callback that will handle it.  Since code does not typically turn up partway through execution except by plugins, lws only supports tacking on external code / protocols that way at lws context creation time.

> to determine if the user will at some point open a websocket server at all.

Why don't you defer creating the lws context until he seems to want to use ws?  You can arrange for the lws create_context stuff to look in an appropriate dir to find his desired plugin(s) by then as well since he knows who is his and what he wants to do.  I don't know what your event loop situation is but lws supports having an event loop whose lifecycle is unrelated to the lws context... it just joins it and leaves it according to when the lws context is created and destroyed.

**Comment by mhoeben** [comment]
One reason (at least in my application) why you would want to be able to dynamically define a protocol is when you implement a generic client WebSocket API as defined for browsers. The constructor of a WebSocket in the browser is;

`new WebSocket(url [, protocols]);`

Protocols can be anything, even comma separated protocols like `foo, bar`. It ultimately only sets the `Sec-WebSocket-Protocol` header field and does nothing for the semantics of the data sent or received. This is, AFAIK, currently not possible to implement using libwebsockets. A "default" protocol and some way to set the `Sec-WebSocket-Protocol` header field would help. But maybe this is already possible and I just have not figured out how to do it?

**Comment by mhoeben** [comment]
Just for clarification why it doesn't work; you can add a default protocol using a `nullptr` protocol name. LWS will happily send a header without the `Sec-WebSocket-Protocol` field and I can add the `Sec-WebSocket-Protocol` field manually using the `LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER` callback. However, LWS will segfault in `lws_client_ws_upgrade` because the `wsi->protocol->name` field is a nullptr when trying to match a callback for the upgrade.

**Comment by lws-team** [comment]
I think everybody on this thread is meaning something different with "dynamically define a protocol"... I don't have much idea about what you're trying to do.

With ws the server selects a protocol for your connection based on the list the client sent, or didn't send, and whether it's willing to work with that.  So protocol selection is always negotiated and "dynamic".

In the end you have to have some code to implement whatever the protocol is, so you are only selecting between a finite amount of ones you have code to support.

If you mean you somehow place information about the protocol structure in the name, what's the point of doing that?  If you control the protocol, you can just have the client inform the server of the structure it wants inside the protocol (or whatever else it is you are trying to do) as the first thing sent.

**Comment by mhoeben** [comment]
I'm sorry to have hijacked the thread if everyone else is trying to do something different. I am trying to implement the W3C WebSockets API, using LWS. Specifically, the WebSockets constructor (https://html.spec.whatwg.org/multipage/web-sockets.html#dom-websocket) allows one to specify a `protocols` string that ends up in the `Sec-WebSocket-Protocol` header field of the request. As I said, this can be anything the Javascript API user desires (for example `"foo, bar"`), because the protocol is implemented in the Javascript domain. The W3C WebSocket API allows one to send (non fragmented) messages or receive (non fragmented) messages - irrespective of the value of the negotiated protocol.

In LWS, the value of the `Sec-WebSocket-Protocol` header field is directly related to the defined protocols and the protocol specified for the client connection. In other words, if you want to support the W3C API you either have to "dynamically" create an LWS protocol for each protocol the Javascript user specifies, or you have to have a generic protocol that implements the semantics of sending and receiving non fragmented messages and be able to specify the HTTP GET Requests's `Sec-WebSocket-Protocol` header field prior, or during connection setup.

**Comment by lws-team** [comment]
Well, you can give your arbitrary protocol string here when making a client connection

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n81-82

... that's what should go out on `Sec-Websocket-Protocol` for the server to select one or reject the negotiation.

At the same time, you can bind the activity on the client connection to a different, specified protocol name using `.local_protocol_name`

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n119-125

... so you can do things like be a client that offers protocols a, b, c but actually they all have the one implementation set in `.local_protocol_name` as d.

IIUI you want to specify a, b or c or whatever the guy wanted but truly all have it appear on d implementation which is your "javascript".

You can find out by querying the http response header `WSI_TOKEN_PROTOCOL` what the name of the logical negotiated protocol was, but everything's happening at d.

That's what you are asking or there are missing pieces?

**Comment by mhoeben** [comment]
But wouldn't that set `Sec-WebSocket-Protocol: a, b, c`, while the W3C API requires you to just output `Sec-WebSocket-Protocol: <protocol-argument-from-the-constructor>`?

**Comment by lws-team** [comment]
Hmmm maybe I am just not following you but are you sure you have the right idea about what that document is trying to tell you?

JS support in browser and the wire protocol were defined to complement each other... protocol js string "a,b" is a valid js string and valid to appear on the ws header... what's exactly the "protocol-argument-from-the-constructor"?

**Comment by mhoeben** [comment]
From https://html.spec.whatwg.org/multipage/web-sockets.html#dom-websocket:

`socket = new WebSocket(url [, protocols ] )`

Creates a new WebSocket object, immediately establishing the associated WebSocket connection.

url is a string giving the URL over which the connection is established. Only "ws" or "wss" schemes are allowed; others will cause a "SyntaxError" DOMException. URLs with fragments will also cause such an exception.

protocols is either a string or an array of strings. If it is a string, it is equivalent to an array consisting of just that string; if it is omitted, it is equivalent to the empty array. Each string in the array is a subprotocol name. The connection will only be established if the server reports that it has selected one of these subprotocols. The subprotocol names have to match the requirements for elements that comprise the value of Sec-WebSocket-Protocol fields as defined by The WebSocket protocol. [WSP]

**Comment by lws-team** [comment]
So if you gave it ["a", "b" ] in js and translate that to "a,b" and give it to lws, what's the point at which that doesn't do what you want?

**Comment by mhoeben** [comment]
The point is that, as far as I know and have seen, lws wants to have an `lws_protocols` specification that matches "a,b", however, I cannot know in advance what the javascript will pass me. (It can also be "c, d", or anything else...). If I pass "a,b" in `lws_client_connect_info.protocol`, but don't have a matching `lws_protocol` specification with name "a, b", lws will not connect.

As I said above, I see two solutions;

1. Add an `lws_protocols` specification with matching name the moment I get a (new) protocols argument passed in the Javascript WebSocket object constructor.
2. Define an `lws_protocols` specification where the `lws_protocols.name` is a NULL pointer and add the appropriate `Sec-WebSocket-Protocol` header field manually in the `LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER` callback. (lws does not add that header field if the lws_protocols.name structure member is NULL).

1. is not possible, AFAIK. lws_protocols are defined when creating the context or vhost.
2. works, until lws tries to find the appropriate protocol to callback in the `lws_client_ws_upgrade` function, specifically line 422 of client-ws.c; `strcmp(wsi->protocol->name, wsi->vhost->protocols[n].name) == 0` because both protocol names are NULL.

I think I can make solution 2 work with a patch, if you agree that would be a way to make this work.

**Comment by lws-team** [comment]
> If I pass "a,b" in lws_client_connect_info.protocol, but don't have a matching lws_protocol specification with name "a, b", lws will not connect.

That's not how it is defined to work in ws.  If you're the client and you pass "a,b" as the subprotocol list, it's an invitation to the server to pick its preferred protocol and reply back with that one (alone).

Again for client, as mentioned above, you can use `.local_protocol_name` in the client connection info to bind the client to use a completely different local protocol implementation regardless.

Please put a finger on your detailed disposition you're suggesting, and make sure we get to the bottom of why these two points are not enough to solve it.  If anything broken on lws side, happy to fix it, but these should do it AFAIK.

**Comment by mhoeben** [comment]
I must miss something then and will go back and see what you mean.

In the meantime, may I ask you it this way; how would I implement the W3C Javascript WebSocket specification, where the script determines what ends up in `lws_client_connect_info.protocols`?

**Comment by lws-team** [comment]
lws is just presenting what RFC6455 demands to be able to pass in the subprotocol header, one string which may have comma-separated parts.

https://tools.ietf.org/html/rfc6455#section-4

None of that is an lws invention it's in the standard.  So you must convert js [ "a", "b" ] to "a,b" whether you use lws or something else, it's not stopping you doing what you want.

**Comment by mhoeben** [comment]
Ok, I see my problem. Before I knew about `.local_protocol_name`, I worked on solution #2 that would manually add the `Sec-WebSocket-Protocol` header field. Apparently, during testing with `.local_protocol_name` that code was active, and I saw the `Sec-WebSocket-Protocol` twice; once from `.local_protocol_name` and once from my test code and dismissed the solution assuming that you didn't understand my problem. Apparently you did, and you made the right suggestion. Sorry for taking your time and thanks for helping.
