### ISSUE TITLE
compilation problem libwebsockets 1.4 with libev-4.20 ( last but same with tried with 4.15 or 4.19)

### ISSUE THREAD

**Issue by piaff33z** [warmcat/libwebsockets#321]
Hello I tried to compile libwebsockets 1.4 from source and linking it with libev-4.20. Below steps that I followed

**cd /tmp/libwebsockets-1.4-chrome43-firefox-36**
**mkdir build**
**cd build**

//# sets for path about libev//
export CFLAGS=-I/opt/system/libev/include
export LDFLAGS=-L/opt/system/libev/lib
export CPPFLAGS=$CFLAGS

**cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/network/libwebsockets-1.4 -DLWS_USE_LIBEV:BOOL=ON -DLWS_IPV6:BOOL=ON ..**
....
....
 LWS_WITH_SSL = ON  (SSL Support)
 LWS_SSL_CLIENT_USE_OS_CA_CERTS = 1
 LWS_USE_CYASSL = OFF (CyaSSL replacement for OpenSSL)
 LWS_WITHOUT_BUILTIN_GETIFADDRS = OFF
 LWS_WITHOUT_CLIENT = OFF
 LWS_WITHOUT_SERVER = OFF
 LWS_LINK_TESTAPPS_DYNAMIC = OFF
 LWS_WITHOUT_TESTAPPS = OFF
 LWS_WITHOUT_TEST_SERVER = OFF
 LWS_WITHOUT_TEST_SERVER_EXTPOLL = OFF
 LWS_WITHOUT_TEST_PING = OFF
 LWS_WITHOUT_TEST_CLIENT = OFF
 LWS_WITHOUT_TEST_FRAGGLE = OFF
 LWS_WITHOUT_DEBUG = OFF
 LWS_WITHOUT_EXTENSIONS = OFF
 LWS_WITH_LATENCY = OFF
 LWS_WITHOUT_DAEMONIZE = OFF
 LWS_USE_LIBEV = ON
 LWS_IPV6 = ON
 LWS_WITH_HTTP2 = OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /images/programmation/libwebsockets-1.4-chrome43-firefox-36/build

**make**

Scanning dependencies of target websockets
[  2%] Building C object CMakeFiles/websockets.dir/lib/base64-decode.c.o
[  4%] Building C object CMakeFiles/websockets.dir/lib/handshake.c.o
[  6%] Building C object CMakeFiles/websockets.dir/lib/libwebsockets.c.o
[  8%] Building C object CMakeFiles/websockets.dir/lib/service.c.o
[ 10%] Building C object CMakeFiles/websockets.dir/lib/pollfd.c.o
[ 12%] Building C object CMakeFiles/websockets.dir/lib/output.c.o
[ 14%] Building C object CMakeFiles/websockets.dir/lib/parsers.c.o
[ 16%] Building C object CMakeFiles/websockets.dir/lib/context.c.o
[ 18%] Building C object CMakeFiles/websockets.dir/lib/sha-1.c.o
[ 20%] Building C object CMakeFiles/websockets.dir/lib/alloc.c.o
[ 22%] Building C object CMakeFiles/websockets.dir/lib/client.c.o
[ 25%] Building C object CMakeFiles/websockets.dir/lib/client-handshake.c.o
[ 27%] Building C object CMakeFiles/websockets.dir/lib/client-parser.c.o
[ 29%] Building C object CMakeFiles/websockets.dir/lib/ssl.c.o
[ 31%] Building C object CMakeFiles/websockets.dir/lib/lws-plat-unix.c.o
[ 33%] Building C object CMakeFiles/websockets.dir/lib/server.c.o
[ 35%] Building C object CMakeFiles/websockets.dir/lib/server-handshake.c.o
[ 37%] Building C object CMakeFiles/websockets.dir/lib/extension.c.o
[ 39%] Building C object CMakeFiles/websockets.dir/lib/extension-deflate-frame.c.o
[ 41%] Building C object CMakeFiles/websockets.dir/lib/extension-deflate-stream.c.o
[ 43%] Building C object CMakeFiles/websockets.dir/lib/daemonize.c.o
Linking C static library lib/libwebsockets.a
Copying OS X content lib/Headers/libwebsockets.h
Copying OS X content lib/Headers/lws_config.h
[ 43%] Built target websockets
Scanning dependencies of target test-client
[ 45%] Building C object CMakeFiles/test-client.dir/test-server/test-client.c.o
Linking C executable bin/libwebsockets-test-client
lib/libwebsockets.a(service.c.o): In function `lws_handle_POLLOUT_event':
service.c:(.text+0x264): undefined reference to `lws_libev_io'
lib/libwebsockets.a(pollfd.c.o): In function `remove_wsi_socket_from_fds':
pollfd.c:(.text+0x1ed): undefined reference to `lws_libev_io'
lib/libwebsockets.a(pollfd.c.o): In function `libwebsocket_callback_on_writable':
pollfd.c:(.text+0x6e9): undefined reference to `lws_libev_io'
lib/libwebsockets.a(pollfd.c.o): In function `libwebsocket_callback_on_writable_all_protocol
pollfd.c:(.text+0x7d7): undefined reference to `lws_libev_io'
lib/libwebsockets.a(context.c.o): In function `libwebsocket_create_context':
context.c:(.text+0x181): undefined reference to `lws_feature_status_libev'
lib/libwebsockets.a(ssl.c.o): In function `lws_server_socket_service_ssl':
ssl.c:(.text+0x72c): undefined reference to `lws_libev_io'
ssl.c:(.text+0x893): undefined reference to `lws_libev_io'
ssl.c:(.text+0x94b): undefined reference to `lws_libev_io'
lib/libwebsockets.a(lws-plat-unix.c.o): In function `lws_plat_insert_socket_into_fds':
lws-plat-unix.c:(.text+0x14a): undefined reference to `lws_libev_io'
lib/libwebsockets.a(lws-plat-unix.c.o): In function `lws_plat_init_fd_tables':
lws-plat-unix.c:(.text+0x325): undefined reference to `lws_libev_init_fd_table'
lib/libwebsockets.a(lws-plat-unix.c.o): In function `lws_plat_service':
lws-plat-unix.c:(.text+0x66c): undefined reference to `lws_libev_run'
lib/libwebsockets.a(server.c.o): In function `lws_server_socket_service':
server.c:(.text+0x405): undefined reference to `lws_libev_io'
server.c:(.text+0x544): undefined reference to `lws_libev_accept'
collect2: ld returned 1 exit status
make[2]: * [bin/libwebsockets-test-client] Error 1\\
make[1]: * [CMakeFiles/test-client.dir/all] Error 2\\
make: * [all] Error 2\\

If i try to compile without libev support by removing option  -DLWS_USE_LIBEV:BOOL=ON, I have no issue...

I think it is a linking problem. After some investigations I found in file CMakeFiles/test-client.dir/link.txt

content is :

/usr/bin/cc  -Wall -Werror -O3 -fvisibility=hidden -I/opt/system/libev/include    -L/opt/system/libev/lib CMakeFiles/test-client.dir/test-server/test-client.c.o  -o bin/libwebsockets-test-client -rdynamic lib/libwebsockets.a -lz -lssl -lcrypto -ldl -lm

If I try to run this command from build directory I have exactly same error...

**Comment by JoakimSoderberg** [comment]
Hello, yes. That is not the way you tell CMake where libev is located. CMake might compile multiple executables or whatever with different CFLAGS, so that's not a good idea in any case.

Normally CMake will find the lib automatically. Here's a link on how libraries are found in CMake: https://cmake.org/Wiki/CMake:How_To_Find_Libraries

But your lib seems to be in a non-standard location, so libwebsockets lets you set the paths manually also using these variables:
https://github.com/warmcat/libwebsockets/blob/master/CMakeLists.txt#L95

**Comment by JoakimSoderberg** [comment]
Regarding the linking you are correct it is a linking issue.

 CMake won't know it's supposed to link libev at all since it never finds it. It will happily add the include/library dirs that you passed on via the CFLAGS. But it won't add libev to the list of libraries that libwebsockets should link against internally, so when it generates the linking stuff it's not there.

Specifically here it where it adds libev to the list of libs to link against. This code is never hit with your CFLAG thingie solution:
https://github.com/warmcat/libwebsockets/blob/master/CMakeLists.txt#L559

Note that CMake is a multiplatform build tool, it can generate build files for many project types, Make files being only one, so it uses other mechanisms for stuff than you might be used to.

**Comment by piaff33z** [comment]
About your remark 

**...That is not the way you tell CMake where libev is located.CMake might compile multiple executables or whatever with different CFLAGS, so that's not a good idea in any case.**

Yeah, I know that is not official position in my system for libev :-). But by this way i can have more librairies or tool of a project and change easly a version by changing a simple link... I use this method with lot of projects with no problem ;-)

**Comment by piaff33z** [comment]
Hi, i succeed to compile by changing just on thing on CMakeCache.txt generating by first
**cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/network/libwebsockets-1.4 -DLWS_USE_LIBEV:BOOL=ON -DLWS_IPV6:BOOL=ON ..**

After running this command, i have
....
 LWS_WITH_SSL = ON  (SSL Support)
 LWS_SSL_CLIENT_USE_OS_CA_CERTS = 1
 LWS_USE_CYASSL = OFF (CyaSSL replacement for OpenSSL)
 LWS_WITHOUT_BUILTIN_GETIFADDRS = OFF
 LWS_WITHOUT_CLIENT = OFF
 LWS_WITHOUT_SERVER = OFF
 LWS_LINK_TESTAPPS_DYNAMIC = OFF
 LWS_WITHOUT_TESTAPPS = OFF
 LWS_WITHOUT_TEST_SERVER = OFF
 LWS_WITHOUT_TEST_SERVER_EXTPOLL = OFF
 LWS_WITHOUT_TEST_PING = OFF
 LWS_WITHOUT_TEST_CLIENT = OFF
 LWS_WITHOUT_TEST_FRAGGLE = OFF
 LWS_WITHOUT_DEBUG = OFF
 LWS_WITHOUT_EXTENSIONS = OFF
 LWS_WITH_LATENCY = OFF
 LWS_WITHOUT_DAEMONIZE = OFF
 **LWS_USE_LIBEV = ON**
 LWS_IPV6 = ON
 LWS_WITH_HTTP2 = OFF

But strangely in file CMakeCache.txt we can see 2 references of LWS_USE_LIBEV variable, at begining the reference of number line
 ...
    216        //No help, variable specified on the command line.
    217        LWS_USE_LIBEV:BOOL=ON
....
    264        //Compile with support for libev
    265        LWS_WITH_LIBEV:BOOL=**OFF**
.....
If i pass this second variable to ON, make command compile with no problems 

But commands below will have to be executed before 

//# sets for path about libev//
export CFLAGS=-I/opt/system/libev/include
export LDFLAGS=-L/opt/system/libev/lib
export CPPFLAGS=$CFLAGS

as you can see after installation, system linking is ok :-)

ldd libwebsockets.so.5
        linux-vdso.so.1 =>  (0x00007fff4c3ff000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f653d948000)
        libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007f653d6dc000)
        libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007f653d2fb000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f653d0f7000)
        **libev.so.4 => /opt/system/libev/lib/libev.so.4 (0x00007f653cee9000)**
        libm.so.6 => /lib64/libm.so.6 (0x00007f653cc64000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f653c8d0000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f653c68c000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f653c3a5000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f653c1a1000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f653bf75000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003100c00000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f653bd69000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f653bb66000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f653b94c000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f653b72e000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f653b50f000)

About usage of **LWS_LIBEV_INCLUDE_DIRS** and **LWS_LIBEV_LIBRARIES**, by settings them with command below has no effect...  

**cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/network/libwebsockets-1.4 -DLWS_USE_LIBEV:BOOL=ON -DLWS_LIBEV_LIBRARIES:PATH=-L/opt/system/libev/lib -DLWS_LIBEV_INCLUDE_DIRS:PATH=-I/opt/system/libev/include -DLWS_IPV6:BOOL=ON ..**

I got 
...
 LWS_WITH_SSL = ON  (SSL Support)
 LWS_SSL_CLIENT_USE_OS_CA_CERTS = 1
 LWS_USE_CYASSL = OFF (CyaSSL replacement for OpenSSL)
 LWS_WITHOUT_BUILTIN_GETIFADDRS = OFF
 LWS_WITHOUT_CLIENT = OFF
 LWS_WITHOUT_SERVER = OFF
 LWS_LINK_TESTAPPS_DYNAMIC = OFF
 LWS_WITHOUT_TESTAPPS = OFF
 LWS_WITHOUT_TEST_SERVER = OFF
 LWS_WITHOUT_TEST_SERVER_EXTPOLL = OFF
 LWS_WITHOUT_TEST_PING = OFF
 LWS_WITHOUT_TEST_CLIENT = OFF
 LWS_WITHOUT_TEST_FRAGGLE = OFF
 LWS_WITHOUT_DEBUG = OFF
 LWS_WITHOUT_EXTENSIONS = OFF
 LWS_WITH_LATENCY = OFF
 LWS_WITHOUT_DAEMONIZE = OFF
 LWS_USE_LIBEV = ON
 LWS_IPV6 = ON
 LWS_WITH_HTTP2 = OFF
-- Configuring done
-- Generating done
CMake Warning:
  **__Manually-specified variables were not used by the project__:**
    LWS_LIBEV_INCLUDE_DIRS
    LWS_LIBEV_LIBRARIES
-- Build files have been written to: /images/programmation/libwebsockets-1.4-chrome43-firefox-36/build

During linking phase I got exactly the same error :-)

My conclusion for to compile libev with another location on my linux system :-)

Settings CFLAGS, LDFLAGS and CPPFLAGS which are necessary before to use cmake. After we must modify file CMakeCache.txt generating by previous cmake and by setting second LWS_WITH_LIBEV:BOOL from OFF to ON...

vic

**Comment by JoakimSoderberg** [comment]
Good thing you got it compiling! However what you're describing is a set of hacks, not a proper solution to you problem.

Some notes:

> Yeah, I know that is not official position in my system for libev :-). But by this way i can have more one librairies or tool for a project given and change easly a version by changing a simple link... I use this method with lot of projects with no problems ;-)

The important part in the remark I made was not that you're using a non-default location for your libs (that's totally ok), but rather that the way you're trying to tell CMake where to find them.

1. The libwebsockets CMake project is not the cleanest around. Some variables are quite redudant. There is both an **option** `LWS_WITH_LIBEV`, this is what you're supposed to set. Internally in the cmake project and the source code `LWS_USE_LIBEV` will then be set and used. If you instead incorrectly set the wrong variable as you did, other logic will not work properly. To see the list of cmake *options* you can use `cmake -L ..`

2. I realise you're using the official *1.4.* release, which is over a year old. The issue with CMake not being able to find a lib in a non-default location was fixed in a commit after that:
https://github.com/warmcat/libwebsockets/commit/f1b125442be619c43bff45791a3f6fd5726099b5#diff-af3b638bc2a3e6c650974192a53c7291R95
That's why setting `LWS_LIBEV_INCLUDE_DIRS:PATH` and `LWS_LIBEV_LIBRARIES:PATH` had no effect for you.

3. `LWS_LIBEV_INCLUDE_DIRS:PATH`, and any CMake variable with `:PATH` at the end, takes a path as input and nothing else. You gave it `-DLWS_LIBEV_LIBRARIES:PATH=-L/opt/system/libev/lib` (that is, you're including the **-L**, which is a linker specific command line option). So even if you had a newer libwebsockets version this would not work.

Right now @warmcat the maintainer of this project has been missing for several months, so I don't know when the next release will be out. But there are a lot of bug fixes since the last release, so I'd suggest you use the latest master instead.

**Comment by piaff33z** [comment]
Thanks for you help Joakim, your advices were very useful. I'll try later again complitation with the later master branch of libwebsockets...
I think I can close this thread now...
