### ISSUE TITLE
Can lws_client_connect_info bind several lws_context?

### ISSUE THREAD

**Issue by bethebest0622** [warmcat/libwebsockets#3213]
`lws_client_connect_info `need to specify a `lws_context`, then the connection event was monitored by `lws_service(ctx, 0)`.

in my case. I need several processes. Among these processes, there is one connection needed for every process.

currently, i build the same connection for each processes, which is duplicated and wastey.

Is there any methods in `libwebsockets `layer can share the connections between processes?

Thanks

**Comment by lws-team** [comment]
You need to think differently about what you're doing... lws is doing your whole upstream ws connection fine already and that's all you can ask for one step.

If you want to distribute the data that's coming locally, that is a different architectural piece.  You want to run a server on a vhost, perhaps on a unix socket, that n processes can locally connect to in order to receive their own personal copy of the received data from the local server.  That's unrelated to the ws piece, although lws can also do the serving and client sides.
