### ISSUE TITLE
file upload problem whe using custom eventlib

### ISSUE THREAD

**Issue by gmfcd128** [warmcat/libwebsockets#3219]
When I want to want to send a medium size file onto my embedded HTTP server with custom eventlib enabled, the upload will make the system hang for a bit and not finish(server not respond to TCP), and it is fine when I run the application in normal mode.
I suspect the problem is in the function lws_tls_fake_POLLIN_for_buffered, since the system log showed that the situation in lib/core-net/service.c had occurred many times while doesn't under normal situation, I tried to modify the code a little, but the problem still persists.
![圖片](https://github.com/user-attachments/assets/4848f3de-5ee3-445d-a094-edda889cd866)
![圖片](https://github.com/user-attachments/assets/d922cf2d-5095-447a-b2fe-138fea1524cf)

**Comment by lws-team** [comment]
The job of this is to synthesize an "event" for buffered data, so we won't go to sleep in the wait, waiting for an event that won't be coming to wake us... there won't be any more network events for it, because we already have had more incoming data than we could deal with from the network already and have buffered it.  Eg, we receive a big tls frame but can't deal with it all at once and want to continue next time around the event loop.

At the same time, apps can use rx flow control to modulate when they can deal with new incoming data, to essentially silence the incoming rx and hold it buffered until they can process more, it's commonly like this if the incoming data is being forwarded and we filled up the onward pipe, we have to return to the event loop frequently so it can all work.

If it's only happening with a custom event loop, I would wonder if although it understands it has pending rx data left buffered to consume, for some reason when it goes around to do that, it does not actually consume anything.  Then it spins and eventually times out.

**Comment by gmfcd128** [comment]
OK, I referened the _lws_plat_service_tsi code, basically the point is when using fake pollin event, the returned event of that pollfd will be manually set and therefore we should skip the poll() in the custom event loop, part of user code problem. However the status of external pollfd array currently seems to be modified using additioal code as well

**Comment by lws-team** [comment]
Given your understanding, what do you think I should do for this?

**Comment by gmfcd128** [comment]
maybe add an opertaion into struct lws_event_loop_ops for the external pollfd status changing part

**Comment by lws-team** [comment]
I don't understand what the name or function of this new function pointer would be, can you suggest something and maybe show the kind of code it would contain?

**Comment by gmfcd128** [comment]
1.the content of lws_tls_fake_POLLIN_for_buffered can check if context->event_loop_ops exists in pt->context, the original behavior will be bypassed then call the implementation in pt->context like pt->context->event_loop_ops->fake_pollin(pt), then
2.make the custom evlib implementation change the pollfd, and the synthesized pollin will take effect when the outer loop poll on these pollfds
![image](https://github.com/user-attachments/assets/c0bbc437-67e4-42f4-8a1f-ba7c6b9174e2)
![image](https://github.com/user-attachments/assets/e4f4b95e-f06d-4b58-9121-7b9ce0546cf0)

**Comment by lws-team** [comment]
I pushed a patch on main which implements the new, optional callback which allows the custom event loop to choose to do the "POLLIN" setting itself, if provided.  Otherwise it works as before.

Is that capturing your meaning?
