### ISSUE TITLE
(websocket server)should i wait at LWS_CALLBACK_ESTABLISHED or LWS_CALLBACK_RECEIVE when the working thread prepare the data? Then call lws_callback_on_writable to trigger the websocket data send?

### ISSUE THREAD

**Issue by pppaulpeter** [warmcat/libwebsockets#3244]
Hi Andy,

may i know what is the best practise? shoud i use a mutex and a condition variable to wait at the LWS_CALLBACK_RECEIVE (wait the send data ready ,the working thread need search the database and read the sending data from disk which will cost a little time ), this block code(mutex ) in lws event callback  will cause the websocket server can't response the request in realtime, correct? but without the block code, how the working thread trigger the lws to know the data is ready and going to case LWS_CALLBACK_SERVER_WRITEABLE to send data? now i using the block code and it seems it could work, but i am worried it will decrease the lws websocket server's performace @lws-team

**Comment by lws-team** [comment]
If the database is local, the maximum delay to read it is likely to be small.  You should measure the delay before deciding to do anything about it, because below some duration, it's not going to matter to just wait for it, say, 5ms.

The choice is to read the database synchronously as you do now, or essentially make the read asynchronous.  That is, the lws thread starts the read process and then have the lws thread return to the event loop.  At the end of the async read action when you have the result, you want to indicate to the lws thread that there is "something to do".  `lws_cancel_service()` can be called from any other thread and wake the lws thread and make it call `LWS_CALLBACK_EVENT_WAIT_CANCELLED`.  Here you can lock the data shared between the threads and examine what it is the other threads want to be done.

Bear in mind at any time you return the lws thread to the event loop, the connection can be seen to have closed and the wsi will be destroyed.  You have to handle the CLOSE callback for it on the lws thread and be ready to notice that the wsi you want to return the result on is already dead when the async database thread completes.

**Comment by pppaulpeter** [comment]
thanks, it just make me feel unsafe to use mutex in lws callback event loop. i mean the dead lock will make the webscoket service unavaliable. 
 is that ok i save the wsi in the user structure for every websocket connection and call this in the data preparing thread?
```
printf("Worker thread finished work, signaling LWS thread...\n");
lws_cancel_service(lws_get_context(wsi));  // Wake up the LWS event loop
```

**Comment by lws-team** [comment]
If you want threads, you must lock.  And if you want to lock, it has blocking semantics that your thread is forced to sleep until you get the mutex.  So threads == narcolepsy for your thread.

If the delay for the database lookup is short compared to the kind of delay that makes a problem, it's perfectly reasonable to to not use threads, or locking, and just block in the lws thread while you do the database lookup instead.  Then when you have the database result, you are still in the lws thread and can call `lws_callback_on_writable()` directly before returning to the event loop.
