### ISSUE TITLE
undefined reference to lws_ss_create

### ISSUE THREAD

**Issue by hermestrimegistus** [warmcat/libwebsockets#3290]
If I include -DLWS_SS_USE_SSPC in the compile line, gcc further complains: "undefined reference to lws_sspc_create".
I am following "libwebsockets/minimal-examples/client/hello_world" main.c . But I am not compiling it or the lws library from there because my linux distribution has already installed libwebsockets library; I am just following it line by line to be able to create a client to connect to a "wss" server running somewhere.

**Comment by lws-team** [comment]
Nah... you can't use a distro build if you want special things like SSPC.

Distro builds include default and specially constructed options like event lib support.

For SSPC, the library has to be specially built with the requisite options.  Deciding unilaterally you don't need to care because distro lib is just wong.

**Comment by hermestrimegistus** [comment]
> Nah... you can't use a distro build if you want special things like SSPC.
> 
> Distro builds include default and specially constructed options like event lib support.
> 
> For SSPC, the library has to be specially built with the requisite options. Deciding unilaterally you don't need to care because distro lib is just wong.

All right! I try now with git build (cmake . && make && make install). Thanks
