### ISSUE TITLE
Connection Timeout For  lws HTTP Client

### ISSUE THREAD

**Issue by Ajuz369** [warmcat/libwebsockets#3292]
When establishing the connection, timeout to determine how long a connection should be active in case idle , after connection being established in server can be set by keep_warm_secs variable in connect_info object. So to set a configurable timeout for  waiting client to connect to server , from the time of calling to lws_connect_via_info to a connection established state , how will i set this timeout. ?
Now in my call ack function  case LWS_CALLBACK_CLIENT_CONNECTION_ERROR is hitting every 5 seconds i think if my server is offline. so this connection timeout can be configured. how will i do that?

what iam thinking is use a lws_set_timeout in case LWS_CALLBACK_CONNECTING in my call back function with desired timeout . is my approach correct. any other ways to do it?

**Comment by lws-team** [comment]
This is a bit more complicated since the connect() posix call (and before that, the DNS lookup) has its own timeout ideas.  Over time lws supported async DNS lookups, and more intricate connect waits, where we can decide the behaviours instead of a combination of the libc and kernel.

Many of these core timeouts are referenced to whatever is set in the vhost (I think it falls back in most cases to the same context / vhost info that was used to create the context, if the value in the vhost is 0).  Eg

```
	unsigned int timeout_secs;
	/**< VHOST: various processes involving network roundtrips in the
	 * library are protected from hanging forever by timeouts.  If
	 * nonzero, this member lets you set the timeout used in seconds.
	 * Otherwise a default timeout is used. */
	unsigned int connect_timeout_secs;
	/**< VHOST: client connections have this long to find a working server
	 * from the DNS results, or the whole connection times out.  If zero,
	 * a default timeout is used */
```
