### ISSUE TITLE
LWS HTTP: Sending multiple post request via a single connection

### ISSUE THREAD

**Issue by Ajuz369** [warmcat/libwebsockets#3297]
Hi in my lws http client requirement is to send multiple post req with header and body , and client should reuse the same connection taht was created  for sedning other requests ,unless a connection termination requested by server. in that case next POST operation will create new connection.
i use lws http 1.1 (check in wiresharks header tag), and it uses below api to send the new post requests  asynchronusly from lws thread.
prefilled ccinfo is passed as argument where the user context is set having reference for payload.

lws_client_connect_via_info((struct lws_client_connect_info*) &ccinfo)

i was expecting that it will be reusing same connection.but case LWS_CALLBACK_CLOSED_CLIENT_HTTP is reached after POST ing each requested , which alter my expectation. 
is it approach correct?
 lws_client_connect_via_info- This function creates a connection to a remote server using the
 information provided in ccinfo.
 i have seen like this , so if i m thinking to write new post request by just calling lws_write(). In that case  how can i know the wsi if its depend on server choice of preserving connection
 can u help me to solve this doubt?

**Comment by lws-team** [comment]
Two things you should mention that you don't mention.

1) LCCSCF_PIPELINE (which is or-d on to client_info->ssl_connection) is required that you want to use pipelining at all on the client connection

2) http1 POST without any content-length is not compatible with pipelining, the length of the post body must be known

As you say the server side has to be willing to play ball otherwise it defaults to http/1.0 non-pipelined additionally.

**Comment by Ajuz369** [comment]
NO , pipelining is not really needed in my usecase. My use case is simple .
I need to post http requests (xml body with headers  )  after lws event loop get started. for that i am using  api lws_client_connect_via_info((struct lws_client_connect_info*) &ccinfo) wuth prefilled ccinfo and user context.

so is this approach is suitable for generating multiple requests in single connection? i have seen in documentation that "lws_client_connect_via_info- This function creates a connection to a remote server using the
information provided in ccinfo.". this makes me doubtful. so each time i use connect_info ap if a new connection is created  by closing previous connection in that case , how i deal to make post request by reusing the previous connection without closing it.

**Comment by lws-team** [comment]
> http 1.1
> Actually pipelining is not really needed in my usecase. My use case is simple .

You seem to be misunderstanding something basic.

Original http 1.0 did not have pipelining, and it was restricted to a single transaction per connection.  You had to bring up the tcp connection again and a new tls tunnel if you were trying to do things securely, and wanted another transaction.

That remains the default situation for http/1.1 unless the server indicates it will support pipelining.  If both sides are willing to support pipelining, it's possible to use a single tcp connection + tls tunnel for multiple transactions, with pipelining.

In h2, this was improved again to support arbitrary multiplexing of different streams concurrently inside a single tcp connection + tls tunnel.  You can introduce new transactions on an ongoing connection easily and it's much preferred to use h2.

Your "simple use case" is h1 pipelining so you are talking nonsense trying to establish you don't need pipelining because it's "simple" - it isn't.

**Comment by Ajuz369** [comment]
Sorry taht i have been misunderstanding the concept .. thanks for making it clear
