### ISSUE TITLE
UNIX domain socket support

### ISSUE THREAD

**Issue by bprodoehl** [warmcat/libwebsockets#359]
I'm adding support for UNIX domain sockets, so that the server can listen on a sock file rather than a network port.  Would something like this be welcome upstream?  If so, are there any preferences on how that should be implemented?  The options in my mind would be to either add a field for a sock file path to lws_context_creation_info, or to add a field there for an already-created server socket file descriptor.  The difference there being that in the former, the job of creating the UNIX domain socket lives in libwebsockets, and in the latter, that job belongs to the server implementation.

**Comment by lws-team** [comment]
Yes it'd be welcome thanks.

Client may also want to do this eventually so passing the path is better I think.  The guy listening on it should create it, unless I missed the point somewhere.

If it sounds okay to you, you can declare a new enum lws_context_options flag to tell you want unix domain, and re-use the existing info struct member const char *iface for the path -- unix domain has no network interface concept.

One quirk you should protect the implementation with #if LWS_POSIX since we also support mbed3 now that builds the server bits but has no use for this.

**Comment by lws-team** [comment]
Please reopen this or send a PR when you have something.

**Comment by bprodoehl** [comment]
@lws-team I've been working on this here: https://github.com/bprodoehl/libwebsockets/commits/unix_domain_sockets

Not ready for a PR, but I'll send one once I feel it is.  Thanks for the advice on how to integrate it.
