### ISSUE TITLE
There are some failures in Autobahn Test Suite with the latest release

### ISSUE THREAD

**Issue by dumganhar** [warmcat/libwebsockets#388]
Thanks for creating this awesome websocket library in C. :)

As title said, there are some failures in the Autobahn Test, could you please take a look?
I used `v1.6.0-chrome48-firefox42` to test it, but got many `failures`. :(

**Comment by dumganhar** [comment]
Update:

With the latest code at master branch, Autobahn like it. :)

Please refer to http://182.254.241.97/runtime-test/websocket-report/index.html

There are still 4 failures, please check.

There are some `Unimplemented` tests, are there any plans to support those extensions like `permessage-deflate`?

**Comment by lws-team** [comment]
Yeah it's not coincidence we suddenly pass most of Autobahn.

http://ml.libwebsockets.org/pipermail/libwebsockets/2015-December/002108.html

I have been quiet the last days because I found we need permessage-deflate, the older extensions we support are going away now permessage-deflate has been standardized.  Implementing that itself is not hard because we already almost have it as deflate-frame extension.

But the existing scheme for deflate extension is too dumb to deliver what Autobahn tests.  It has a restriction atm you must give it the plaintext message to compress in one piece, and it must inflate the result in one giant malloc'd piece.

I have improved the lws infrastructure around client and server extension handling and removed the exponential malloc junk from the permessage-deflate, so that you can both feed it fragments for inflate and have the inflated fragments get a user callback with the service loop inbetween (it means your user callback can perform interleaved wait-for-writeable-and-tx on the decompressed data as it comes, without needing the whole thing at one time, and the tx may also send compressed incrementally).  Here, both the test server and client can work again with chrome with permessage-deflate.  But it still needs more work on fragmentation handling to pass all the Autobahn stuff.  It passes the simple compression tests.

This is some heavy engineering and difficult to debug or push it until it all works.

**Comment by dumganhar** [comment]
Hey,@lws-team,
Thanks for the quick reply.

Yep, the master branch have passed most Autobahn Test.

May I ask that is the master branch stable enough for being used if I don't care about the 'permessage-deflate'?
Or shall i wait a while for a new release?

I used an old release version `v1.3-chrome37-firefox30` and there are some issues of receiving fragment message. 

What're your opinions?

**Comment by lws-team** [comment]
Yeah what is pushed should be stable.  The other work shouldn't affect the user apis except some new way will be needed to control compression options like inflate / deflate fragment buffer size.

**Comment by dumganhar** [comment]
@lws-team , got it, thanks.

**Comment by lws-team** [comment]
Just a FYI yesterday I pushed the patch I mentioned I was working on, HEAD passes ALL Autobahn ws fuzzingserver tests now except 2.10 ping spamming which we don't support (and is not specified in the ws standard either).
