### ISSUE TITLE
Manually hand socket off to LWS

### ISSUE THREAD

**Issue by asherkin** [warmcat/libwebsockets#405]
What I'm after is the ability to pass a fd off to LWS that it will then take as it's own, exactly as if it had accept'd it itself. Similar to libmicrohttpd's [`MHD_add_connection`](https://www.gnu.org/software/libmicrohttpd/manual/html_node/microhttpd_002dinit.html#index-MHD_005fadd_005fconnection), which I currently use but would like to switch to LWS for a new project. Preferably, this would work alongside `CONTEXT_PORT_NO_LISTEN` to avoid having an extraneous port.

For non-SSL I gather that it would involve moving [these lines](https://github.com/warmcat/libwebsockets/blob/9666e1d43869fe0eafa8047ff5925d31c8042582/lib/server.c#L812-L866) out to a public function - but I have no idea what SSL support would take and don't want to make a bodge job of a patch (FWIW, I only need non-SSL).

**Comment by lws-team** [comment]
Should be doable... what you're saying sounds good, move most of the section to a subroutine, call it from the old place and from your api.

But there are quirks... we have a pool of HTTP header processings structs and when all busy, we flowcontrol the listen socket to stop new accept processing until a header processing struct becomes free.  This stops uncontrolled dynamic mallocs in a connection storm; the choice of pool size regulates the rate of new accepts instead.

That will have to change to always allowing the 'accept' (since now they may randomly come via this new api) but flowcontrolling (disable POLLIN) any new wsi in the http serving state and putting it on a linked list in the context until it can get a header processing struct from the pool, at which point his POLLIN is enabled again.  I think it'll be easier if I look at that bit, if you are not using up the header struct pool the rest should work without that change.

**Comment by lws-team** [comment]
I've written this but it has become part of the multithreaded server stuff.  I am still testing and making that stable.  So it may be a day or two.

**Comment by asherkin** [comment]
Wow, speedy turnaround! I'm still a way out from needing to test without a separate listening socket, even weeks would be excellent news :+1:.

**Comment by lws-team** [comment]
I added an api on HEAD

```
LWS_VISIBLE struct lws *
lws_adopt_socket(struct lws_context *context, lws_sockfd_type accept_fd)
```

please have a look since I am not 100% sure it's what you need.  It's used inside the library but untested being used externally.

Because it's the same code that accepts SSL connections natively, I think this should also work transparently if the foreign connection is starting an ssl connection from scratch.

**Comment by asherkin** [comment]
It appears to work great for non-SSL at least (both Win32 and Linux), thanks! (I'll have a shot at testing SSL in the future as it would be a nice to have for this project, but it may be a way out.) I am getting a lot of debug spew fwiw: `NOTICE: load:        0 (    1),`.

**Comment by lws-team** [comment]
Great.  Yes it dumps some per-thread stats once per second atm.  I'll remove it shortly.

Just changing this

https://github.com/warmcat/libwebsockets/blob/master/lib/service.c#L439

To 0 should get rid of it for now.
