### ISSUE TITLE
libpthread dependency?

### ISSUE THREAD

**Issue by karlp** [warmcat/libwebsockets#408]
Hi,  With libwebsockets 1.5, built with "CMAKE_OPTIONS += -DLWS_WITHOUT_TESTAPPS=ON" the resulting libwebsockets.so had no dependency on libpthreads.  With 1.6.1, this is now a new dependency.  Is this intended?

**Comment by lws-team** [comment]
1.6[.x] has libwebsockets-test-server-pthreads, but no pthreads in the library itself.  So it shouldn't be needed.  However on Fedora, you can't get away from pthreads with or without an explicit dependency due to dependent libs wanting it.

Please give this a try

https://github.com/warmcat/libwebsockets/commit/e04f4c9ced6434a0f3081b58ef5e5fc8d4f0e44b

If it helps I'll bump the version and tag it.

**Comment by karlp** [comment]
Yep, that works, thanks a lot

**Comment by lws-team** [comment]
It's tagged v1.6.2
