### ISSUE TITLE
Use CC_SHA1() on Apple OS X and iOS?

### ISSUE THREAD

**Issue by MacGritsch** [warmcat/libwebsockets#412]
Hi there,

would it make sense to use CC_SHA1() for OS X and iOS?

`#define lws_SHA1 CC_SHA1`

It is available since OS X 10.4

https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/CC_SHA1.3cc.html

**Comment by lws-team** [comment]
It sounds reasonable, but can you send a pull request with it falling back to the current way if the os is too old?  I have no way to test it otherwise.

**Comment by JoakimSoderberg** [comment]
In my opinion this should not be set by OS version. Rather there should be an explicit test in CMake if it exists, and a define in the `config.h` file for it `HAS_OSX_CC_SHA1` or something.

**Comment by JoakimSoderberg** [comment]
This can be done using the CMake `CHECK_FUNCTION_EXISTS` function: https://cmake.org/cmake/help/v3.0/module/CheckFunctionExists.html

```cmake
CHECK_FUNCTION_EXISTS(CC_SHA1 LWS_HAS_OSX_CC_SHA1)
```

Then in https://github.com/warmcat/libwebsockets/blob/master/lws_config_private.h.in

```cmake
#cmakedefine LWS_HAS_OSX_CC_SHA1
```

And then:

```cmake
#ifdef LWS_HAS_OSX_CC_SHA1
#define lws_SHA1 CC_SHA1
#else
...
```

Read the documentation for the cmake function. Since this requires a special header you also need to include that when doing the check for the function:
(Btw your URL above was broken because the dots were removed):

https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/CC_SHA1.3cc.html

It needs `#include <CommonCrypto/CommonDigest.h>`

**Comment by lws-team** [comment]
There are three sources of SHA1 then... lws internal one, this OSX one and SSL lib one.

Atm there is CMake LWS_WITHOUT_BUILTIN_SHA1 to force using OpenSSL one for distros who don't want proliferating implementations.

It might be worth checking if OSX OpenSSL actually uses native OSX SHA1, if so LWS_WITHOUT_BUILTIN_SHA1 and build with SSL would be enough.

**Comment by MacGritsch** [comment]
OpenSSL is deprecated on OS X and will be removed in one of the next releases.

**Comment by lws-team** [comment]
Well, OpenSSL particularly isn't the point, all the compatible ssl libs provide SHA1() the CMake define controls whether lws will define SHA1() for its build or expect something it is linked to to provide it.  Whether that is OpenSSL, BoringSSL, WolfSSL or whatever they will bring a SHA1() to the party that will be used if lws references were not satisfied internally.

**Comment by JoakimSoderberg** [comment]
But you will still need OpenSSL for SSL support on OSX, regardless what Apple decides about including it in the OS distribution. Unless someone ports it to some other SSL lib. Or some other OpenSSL compatible lib of course.

So should there be a choice between:

* OpenSSL SHA1
* libwebsockets provided SHA1
* System SHA1 (CC_SHA1 on some OSX versions, something else on others, requires system introspection as I suggested)

**Comment by MacGritsch** [comment]
> But you will still need OpenSSL for SSL support

Yes, but only if you need SSL support in libwebsockets.

I am also ok with the SHA1() function provided by libwebsockets, it was only an idea to support CC_SHA1 ;-)

**Comment by lws-team** [comment]
Lws has been ported to work with WolfSSL and CyaSSL as well as OpenSSL.  As you say if whatever else it is walks and talks like OpenSSL enough, it should just work too.

What I was suggesting is the system SSL library for OSX might already use the CC_SHA1 where that is available on the OS.  If so, "just use the SSL library SHA1" solves this with no other action needed, since the OS SSL library already knows if he's recent enough to use the OS SHA1 or not.

If not, yes it needs to adapt at configure / build time according to what system it's built for.

Or fuggetaboutit is also an option, I think the SHA1 in lws is pretty reasonable.

**Comment by lws-team** [comment]
It seems we pushed the fuggetaboutit button since nothing happened for a week.  Please reopen if a patch is forthcoming.
