### ISSUE TITLE
lws_write: how to handle incomplete sent

### ISSUE THREAD

**Issue by stv0g** [warmcat/libwebsockets#421]
The API reference of `lws_write` says:

> `int lws_write (struct lws * wsi, unsigned char * buf, size_t len, enum lws_write_protocol protocol)`
>
> Return may be -1 for a fatal error needing connection close, or a positive number reflecting the amount of bytes actually sent. This can be less than the requested number of bytes due to OS memory pressure at any given time.

How should I handle the case that not everything has been sent?
Can I issue multiple calls to `lws_write` in the same invocation of my protocol callback?

**Comment by alexhultman** [comment]
I'm also wondering this but from looking at the example server it is handled as an error. So I don't think you need to handle it, just report it as an error.

**Comment by lws-team** [comment]
This differed according to the version of the library.... it's kind of broken until current master.

1.6 and before: if no extension munged the data, it can return less than the data sent.  The idea is you would handle it by getting a callback when you could write more and write another chunk.  But this doesn't work for all cases.

After 1.6: the library will deal with it for all cases, by malloc-ing up a buffer to hold the remaining data and draining it automatically as the socket becomes writeable.

You can't deal with it by multiple lws_write() because the fact it didn't accept everything implies it is blocked now.

The underlying issue is while we get notified we can write to the socket, we don't get notified how much it will accept.  So the way to avoid this is reduce the amount we send() on the socket at one time.

**Comment by stv0g** [comment]
Okay thanks for the insight. I will switch to the master branch for now..

Btw: do ensure the ordering of `lws_write()`'s when there's still outstanding buffered data?

Let's say my socket fails to send everything during a `LWS_CALLBACK_WRITABLE` cb.
The remaining data will be send when the socket gets writable again.
But at the same time, the user already sends the next junk of data..
Or are the user callbacks suppressed as long there is something in the buffer?

Thanks :-)
