### ISSUE TITLE
Add link to API documentation for more releases to official website

### ISSUE THREAD

**Issue by stv0g** [warmcat/libwebsockets#423]
I find those URLs quite helpful to get the latest API reference:

- https://rawgit.com/warmcat/libwebsockets/master/libwebsockets-api-doc.html

Here's another example for the 1.6.2 release:

- https://rawgit.com/warmcat/libwebsockets/v1.6.2/libwebsockets-api-doc.html

Maybe you want to include them to the official website?

**Comment by lws-team** [comment]
When cmake runs, he locally generates current api docs in ./doc that match whatever tree you were configuring.

The main page will have to be redone for 1.7, the distros have 1.6 stable packaged we will have to start to differentiate features based on branch, v1.5-stable (last release with old api names, deprecated), v1.6-stable (distro, current release), and v1.7-stable (putative next release, currently in master).  Rather than using tags for -stable urls it's better to use the branch so it's automatically up to date.

**Comment by stv0g** [comment]
I agree.

I just got confused a couple of times because I was using the API doc from the main page (1.6?) with the current master branch.

**Comment by lws-team** [comment]
I got most of the way through this, my push script will now auto-update the public libwebsockets.org api docs on a per-branch basis when they're updated.

The site now has the table I mentioned before with individual links to trees, changelogs and api docs, so I will close this now.

**Comment by stv0g** [comment]
Thanks :-)
