### ISSUE TITLE
Changelog for point releases

### ISSUE THREAD

**Issue by mulander** [warmcat/libwebsockets#424]
Hi,

I am currently the maintainer of the libwebsockets package for OpenBSD.

Since v1.6.0-chrome48-firefox42 there have been the following releases:
 - 1.6.1
 - 1.6.2
 - 1.6.3
 - 1.5.1

The changelog doesn't list those specific releases. Some commits make me think that the changes are listed as part of existing releases like 1.6.0. For example this [commit](https://github.com/warmcat/libwebsockets/commit/f9267170a3ee403e8f4e6a9c36004093cde7dc91) which happened 2 days ago and changes the changelog for 1.6.0.

Additionally the [main website](https://libwebsockets.org/index.html) keeps lagging in pointing out the current release (right now it's pointing at 1.6.2).

This situation makes it really hard for packagers to determine what changed between point releases and how serious it is to package ASAP. I have no way to tell (except going through the logs) to see if 1.6.1, 1.6.2 and 1.6.3 were minor bug fixes, breaking bugs or security issues.

Could those point releases get their own entries in the changelog file?

**Comment by lws-team** [comment]
Yes, sorry.

The changelog existed to list what had happened since the last release, which it does well, and that's very useful.

But we only just introduced the stable branches and servicing them is erratic atm, not just changelog needed for ease of package maintenance but also bumping versions here and there and other business.

I plan to add a 'checklist' file to formalize 'how to release' that will help with this.  I'll leave this issue open until that's done.

**Comment by lws-team** [comment]
I added a file ./release-checklist with the steps I can remember I plan to follow.

If you or someone else think something different should go on, send a PR modifying this file and we can discuss.

**Comment by mulander** [comment]
Looks great, thank you for the change & for your great work on the project.
