### ISSUE TITLE
Connection shows error logs

### ISSUE THREAD

**Issue by Arun19921991** [warmcat/libwebsockets#428]
I have connected to the Webserver using latest library (1.7.0)
But before the Connection established callback am getting the below mentioned error.But i can connect to the webserver.

[1455618508:8584] ERR: header assign - free time 10

**Comment by lws-team** [comment]
It's not actually an error... basically if a connection hogs a header processing struct from the pool for >3s, this is printed as a diagnostic.  I used it as a debugging aid to make sure that we give the header processing struct back to the pool quickly and don't end up with it permanently.  The test server only has 1 of these structs in the pool and that should work reasonably well if many connections are not expected at once.

We learned yesterday your server can be very slow, so this is flagging it as holding the header processing struct for a long time.

I pushed a patch on master (also on v1.7-stable, but I'll wait for more problems before tagging it, since this is just cosmetic) reducing this to lwsl_notice() and another debugging spew candidate that was lwsl_err() to lwsl_info().  You can follow v1.7-stable this will only have patches in that fix things on v1.7 and will become v1.7.n as we go on.

**Comment by Arun19921991** [comment]
Okay.Some times i am not getting callback when i call callback on writable

**Comment by Arun19921991** [comment]
On the 1.6.0. library.But ineed to verify the same is happening in 1.7.0 or not
