### ISSUE TITLE
WinCE

### ISSUE THREAD

**Issue by ondraco** [warmcat/libwebsockets#444]
I tested the LWS (1.7-stable) on WinCE and want to share with you the obstacles that i found (all quite easy solvable) so if you want you may use `_WIN32_WCE` to make the compilation easier.

1 - Function `localtime` does not exist on WCE so In `libwebsockets.c` in `lwsl_emit_stderr()`

```
#ifndef _WIN32_WCE
   #ifdef WIN32
       ptm = localtime(&o_now);
   #else
       if (localtime_r(&o_now, &tm))
          ptm = &tm;
   #endif
#endif
```

2 - `stricmp` does not exist on WCE  os In `libwebsockets.h`:

```
#ifdef _WIN32_WCE
#define strcasecmp _stricmp
#else
#define strcasecmp stricmp
#endif
```

3 - `<fcntl.h>` does not exist on WCE. I have just replaced it with (not really sure if this is the correct way to handle such problem): 

```
#ifndef _WIN32_WCE
#include <fcntl.h>
#else
#define _O_RDONLY       0x0000
#define O_RDONLY        _O_RDONLY
#endif
```

4 - I found out that the `getprotobyname()` (used in `lws-plat-win.c`) is on WCE but for some reason does not work. Not sure if i do something wrong or its just one of "Microsoft specials". So i just replaced the `getprotobyname("TCP");` with constant 6 for WCE case.

**Comment by lws-team** [comment]
Alright they're pushed on both branches, thanks.

It's more certain I get everything right first time if you send a patch, especially since I cannot actually test these changes.  So long as it survive intact how you send it isn't critical, eg cut and paste in a comment here with backticks, although if its nontrivial it is much better to push your changes and then do a pull request.
