### ISSUE TITLE
fatal error: openssl/ecdh.h: No such file or directory

### ISSUE THREAD

**Issue by mapx** [warmcat/libwebsockets#457]
`libwebsockets-1.7.3/lib/ssl.c:28:26: fatal error: openssl/ecdh.h: No such file or directory`

`openssl` needs to set `enable-ec_nistp_64_gcc_128` in config process to install `ecdh.h`, but the switch is disabled by default and considered to be unstable ( see [Gentoo's Bugzilla – Bug 469976 - dev-libs/openssl-1.0.1e w/enable-ec_nistp_64_gcc_128 breaks ECDSA keys](https://bugs.gentoo.org/show_bug.cgi?id=469976) )

Proper bypass is appreciated :)

**Comment by JoakimSoderberg** [comment]
As I understand it, openssl provides a set of `OPENSSL_NO_*` macros applications can define to turn things off.

So I guess somehow `OPENSSL_NO_EC_NISTP_64_GCC_128` should be involved, but I am not sure how?

http://osxr.org:8080/openssl/source/include/openssl/opensslconf.h

```c
0042 /* The OPENSSL_NO_* macros are also defined as NO_* if the application
0043    asks for it.  This is a transient feature that is provided for those
0044    who haven't had the time to do the appropriate changes in their
0045    applications.  */
0046 #ifdef OPENSSL_ALGORITHM_DEFINES
0047 # if defined(OPENSSL_NO_EC_NISTP_64_GCC_128) && !defined(NO_EC_NISTP_64_GCC_128)
0048 #  define NO_EC_NISTP_64_GCC_128
0049 # endif```

**Comment by lws-team** [comment]
Older openssl just doesn't have this header either.  Isn't it enough if cmake looks for openssl/ecdh.h and if it's not around disable all ecdh-related include or usage?

**Comment by JoakimSoderberg** [comment]
Yes, after the `find_package` call for OpenSSL we can do this:

Note we need to let the macro know that it should search in the Openssl include dir as well, since `check_include_file` actually tries to compile a small program that includes the file.

```cmake
set(CMAKE_REQUIRED_INCLUDES ${OPENSSL_INCLUDE_DIRS})
check_include_file(openssl/ecdh.h LWS_HAVE_OPENSSL_ECDH_H)
```

And then add a `#cmakedefine LWS_HAVE_OPENSSL_ECDH_H 1` to https://github.com/warmcat/libwebsockets/blob/master/lws_config_private.h.in

and replace this:
https://github.com/warmcat/libwebsockets/blob/0a3d31b8a61f286220636e18d33964bb8c73f8aa/lib/ssl.c#L27

with `#ifdef LWS_HAVE_OPENSSL_ECDH_H` instead... and any other place where it is required I guess?

I guess this option https://github.com/warmcat/libwebsockets/blob/master/CMakeLists.txt#L89 should be turned `OFF`, or produce an error if it does note exist:

```cmake
if (LWS_SSL_SERVER_WITH_ECDH_CERT AND NOT LWS_HAVE_OPENSSL_ECDH_H)
    message(FATAL_ERROR "Missing openssl/ecdh.h, so cannot use LWS_SSL_SERVER_WITH_ECDH_CERT`)
endif()
```

**Comment by lws-team** [comment]
Thanks Joakim, I pushed that on master and v1.7-stable since it doesn't add any new stuff.

I tried to check it by mv the ecdh.h out of the way, but my openssl's includes themselves want the file.  @mapx, please give it a try we can meddle with it if it's not enough.

**Comment by mapx** [comment]
Nice!

No error occurs any more. `master` and `v1.7-stable` both work with `openssl-1.0.2g` on Gentoo Linux x86_64 now.

Thanks!

**Comment by lws-team** [comment]
Great.
