### ISSUE TITLE
Sending new, pending truncated ...

### ISSUE THREAD

**Issue by rikvdh** [warmcat/libwebsockets#458]
Hi,

I'm trying to integrate libwebsockets in our application but I keep running into the 'Sending new, pending truncated ...' message, and since I use the static-library within our C++ application the assert(0) (https://github.com/warmcat/libwebsockets/blob/v1.7-stable/lib/output.c#L112) is removed.

As described in issue #123, i've already tried incrementing the buffer-size to 4KB. But it still occurs.

I can reproduce it very easy in my application. But I can't seem to sort it out by looking at the code. I don't understand the if-statement at https://github.com/warmcat/libwebsockets/blob/v1.7-stable/lib/output.c#L108-L110,

My application is single-threaded (for now) and on incoming data it performs an HTTP-requests (which takes some time) and replies to the client. When I don't read the reply at the client-side it occurs almost immediately. When I read the messages directly on the client-side with reading, the problem is not reproducible with the 4K buffers.

My client is in my test-script a php-script which I run from the command-line. Via Google-Chrome I cannot reproduce it with the 4K buffers (normally it occurs after sending a few consecutive messages as fast as possible). But fd-polling/reading in browsers is not controllable and the library should not crash.

I am willing to look further into this issue, but I need some more information on how this occurs to point me in the direction to look (e.g. what do the variables in the 'if' represent, when do I reach this case)

Thanks!

Rik

**Comment by lws-team** [comment]
It's simpler than you're maybe thinking.

1) you sent something with lws_write() that was bigger than the kernel could accept in one bite.

2) lws buffers the remainder, and disables WRITABLE callbacks to user code

3) he uses internal WRITABLE processing to drain the buffered data transparently, as the socket can accept more

4) when it's all sent, WRITABLE callbacks to user code are enabled again

Somewhere between 2 and 4, you cause the error by performing another lws_write().

 - you should only do lws_write() from the user WRITABLE callback
 - after one lws_write(), the socket may no longer be writeable, either because it would block now, or the last write is partially buffered
 - you can do multiple lws_write() in one writable callback, but you must protect them with do { lws_write(); } while (!lws_send_pipe_choked(wsi)) or so and not rely on being able to do more than one.

**Comment by rikvdh** [comment]
I understand, I've changed my application to only write in the writable-callback.

Still, the assert (https://github.com/warmcat/libwebsockets/blob/v1.7-stable/lib/output.c#L112) is a bit odd, perhaps returning -1 or something else is better than asserting the complete application. Also, in my case the asserts are removed (C++ compiler, static libwebsockets). I don't think you can rely on the application to stop after the assert. Better error handling on this place is better I suppose.

**Comment by lws-team** [comment]
It's an assert because it means your user code is broken.  It's not a legit runtime situation that is possible and it should take the app down since that app is malfunctioing and sending insane out-of-order data on the wire.

People should create their app in DEBUG mode anyway to get logging below NOTICE, then they'll get the assert.
