### ISSUE TITLE
no close when socket recv 0

### ISSUE THREAD

**Issue by justinchen00** [warmcat/libwebsockets#475]
version: libwebsockets-1.6.0-chrome48-firefox42-android with default build parameters

When the network is weak, library will lead program in endless circles.
0  0xf76e9430 in __kernel_vsyscall ()
1  0xf76bc458 in recv () from /lib32/libpthread.so.0
2  0x0858f61a in lws_ssl_capable_read_no_ssl ()

\# strace -p 1232
recv(27, "", 1, 0)                      = 0
recv(27, "", 1, 0)                      = 0
recv(27, "", 1, 0)                      = 0
recv(27, "", 1, 0)                      = 0
recv(27, "", 1, 0)                      = 0

My solution:
output.c
> lws_ssl_capable_read_no_ssl(struct lws *wsi, unsigned char *buf, int len)
> {
> 	int n;
> 	n = recv(wsi->sock, (char *)buf, len, 0);
> 	if (n >= 0)   // change to <b>n > 0</b>
> 		return n;

Could you review it?

**Comment by lws-team** [comment]
Wah.... this only just appeared as an open issue but it says "opened 16 days ago".

recv() is ambiguous about the meaning of a zero-length return...

```
RETURN VALUE
       These  calls  return the number of bytes received, or -1 if an error occurred.  In the event of an error, errno is set to
       indicate the error.

       When a stream socket peer has performed an orderly shutdown, the return value will be 0  (the  traditional  "end-of-file"
       return).

       Datagram  sockets  in  various  domains  (e.g., the UNIX and Internet domains) permit zero-length datagrams.  When such a
       datagram is received, the return value is 0.

       The value 0 may also be returned if the requested number of bytes to receive from a stream socket was 0.
```

I guess there is no legit reason to send a zero length tcp packet on the wire.  And we should never ask for a zero length max read length.

So I pushed this change on master, v1.7-stable and v1.6-stable since that's what you're using.
