### ISSUE TITLE
Test-Server closes connection when receiving long data.

### ISSUE THREAD

**Issue by lucasterra** [warmcat/libwebsockets#480]
Hello,

On the test server, if you send a long string from the browser:
```javascript
socket_di.send(/* Long string here, tried 9KB string */);
```

The test-server will close the client connection, and even crash at sometimes.

Client was Google Chrome 49.0.2623.110 (64-bit), Mac OS X
Server was running on Mac OS X. No SSL.

**Comment by lws-team** [comment]
Thanks for the report: I can reproduce it.

It's related to a mismatch in the permessage-deflate output buffer size selection (default 1024) and the protocol rx buffer size selection (in this case, for dumb-increment, 10).  If you disable permessage-deflate (leave info.extensions at NULL), there's no problem you get as many 10-byte RX callbacks as needed to deliver the payload.

I have pushed a patch making permessage-deflate check the protocol's rx_buf_size for being >=128 that is needed for normal operation, and refuse permessage-deflate on that protocol if not.

If the rx_buf_size of the protocol is big enough to work with zlib at all, then it further now restricts the decompression stream buffer size to the nearest power of two <= the protocol rx_buf_size.

You can confirm this works because I left the dumb-increment protocol rx_buf_size at 10, so permessage-deflate is automatically disabled on connections using that protocol.  And there is an extra "junk" button in the html that sends 9KB back on dumb-increment for testing.

**Comment by lucasterra** [comment]
Thanks a lot for your fast reply, Andy.
I'm sorry I haven't had the time to test your patch yet (I was on the road). I shall give you feedback as soon as I try it out. But I'll take your word on it and just believe it works, hehe.

Once again, thanks a lot for the patch and all the work you've put on to libwebsockets!

Kind regards,
Lucas
