### ISSUE TITLE
'lws_remaining_packet_payload' doesn't work with 'permessage_deflate' enabled.

### ISSUE THREAD

**Issue by lucasterra** [warmcat/libwebsockets#486]
As the title says. ```lws_remaining_packet_payload``` doesn't seem to be working when ```permessage_deflate``` is enabled.

**Testing conditions:**
_Server:_ test-server
_Protocol:_ dumb_increment_protocol with rx_buffer_size = 512 (so we can have permessage_deflate enabled
_Client:_ use the send_junk button

**Code:**
```c++
case LWS_CALLBACK_RECEIVE:
    printf("Len: %d IsBinary: %d Remaining: %u, IsFinal: %d\n", (int)len, lws_frame_is_binary(wsi), (unsigned int)lws_remaining_packet_payload(wsi), lws_is_final_fragment(wsi));
    /* ... */
    break;
```

**Log:**
```
...
Apr  5 13:18:54 MyComputer.local lwsts[10848] <Error>:    ok
	Len: 511 IsBinary: 0 Remaining: 0, IsFinal: 0
Apr  5 13:18:56 MyComputer.local lwsts[10848] <Error>: lws_rx_sm: doing draining flow
	Len: 511 IsBinary: 0 Remaining: 0, IsFinal: 0
Apr  5 13:18:56 MyComputer.local lwsts[10848] <Error>: lws_rx_sm: doing draining flow
	Len: 511 IsBinary: 0 Remaining: 0, IsFinal: 0
Apr  5 13:18:56 MyComputer.local lwsts[10848] <Error>: lws_rx_sm: doing draining flow
	Len: 313 IsBinary: 0 Remaining: 0, IsFinal: 1
```

Thank you.

**Comment by lws-team** [comment]
In the case what was sent got heavily compressed (junk button is one character repeated 9000 times) the ws-level message is sent completely in one packet, since it's a few bytes.  It's inflated back to 9000 bytes in the extension.  Then the permessage-deflate extension is 'drained' in many goes around the event loop delivering a buffer size at a time.

The ws packet was fully sent before the first inflated buffer.  At the ws level, it is correct there is no data remaining even at the time of the first inflated buffer delivery.

**Comment by lucasterra** [comment]
All right. Thanks! Closing the issue then.

**Comment by tmarrinan** [comment]
Hello.
I am having a similar issue. I understand that `lws_remaining_packet_payload` returning 0 is expected behavior since there is no more data needing to be transferred over the network. However, how can I determine the size of the overall message up front so that I can allocate an appropriately sized buffer to copy the chunks into? Also, how can I determine which portion of that overall message is currently being processed?

**Comment by lws-team** [comment]
ws itself does not know the "size of the overall message up front" even without per-message deflate.

All it knows at any one time is the size of the current message fragment (that is, the size of the compressed data itself with permessage-deflate) and whether that is the final message fragment in the message.  If it is not the final fragment, the whole message could be any size including endless... ws does not cover transferring the message size upfront at all.

If you've been taking the fragment size as the message size, be aware ws allows intermediaries to refragment ws messages.  So a fragment of 8K that has FIN set can be mangled into several smaller fragments only the last one of which has FIN set.

If the sender happens to know what his whole message size will be, he can put it at the start of the message as part of the message... you can pick it out and do your allocation from that.

**Comment by tmarrinan** [comment]
Ok... so when the native WebSocket handler in JavaScript receives as large message, it must internally be concatenating buffers dynamically in a way hidden from the developer, and not triggering a callback until the last chunk arrives.
It is then my responsibly to mimic this behavior using libwebsockets, correct?

JavaScript:

```
var ws = new WebSocket("ws://" + window.location.hostname + ":" + window.location.port);
ws.binaryType = "arraybuffer";

ws.onopen = (event) => {
    console.log("websocket connection open!");
};
ws.onclose = (event) => {
    console.log("websocket connection closed");
};
ws.onmessage = (event) => {
    if (event.data instanceof ArrayBuffer) {
        // receives full buffer (even very large: >> 1 MB)
    }
    else {
        // receives full string (even if very long)
    }
};
```

**Comment by lws-team** [comment]
Yes, or choose to deal with the incoming data as it comes because you don't need the whole message in memory at one time.  That approach can be really efficient for lightweight systems.

For example if the 'message' content is actually streaming audio, you can play it as it came with just a small jitter buffer, not buffer megabytes and megabytes until you had a complete message and then play it.  Likewise if you process the message and forward it on the network, you can forward it as packets of  it comes (and use rx flow control to create backpressure according to the onward receiver link performance) without any huge buffer, even for huge messages.

Lws exposing the content piecemeal is more flexible than the JS approach, then.
