### ISSUE TITLE
Crash in _lws_change_pollfd

### ISSUE THREAD

**Issue by kcunningham** [warmcat/libwebsockets#506]
I am seeing a crash in _lws_change_pollfd on this line:

pfd = &pt->fds[wsi->position_in_fds_table];

In the case when it crashes, the wsi_listening that gets passed into the function seems to have invalid members that have already been freed. The wsi->context->pt appears to have 1 entry in the array, but the entry is pointing at freed memory. It is possible that the entire wsi->context has already been freed. The attempt to access pt->fds gives a bad memory access error and causes the crash.

This is using version 1.7.0. If you think this has already been addressed in one of the more recent releases, please let me know.

**Comment by lws-team** [comment]
1) you should use either v1.7-stable or the last tag like v1.7.6, rather than v1.7.0, there are a lot of fixes and improvements.

2) This problem can be seen on the test server or test client?  Or just your own app?

3) As in the test apps, the context cannot be freed until we left the service / event loop.  So a backtrace might help understand your situation.  We're running one service thread?  Are there other threads?

4) Whether we're being the client or server, and what platform, is always helpful to know.

**Comment by lws-team** [comment]
I can't move this on without a reply: please reopen if something more to discuss.

**Comment by kcunningham** [comment]
Sorry, I have not had a chance to test against 1.7.6 yet to see if this is still an issue. I will reopen this if I am still seeing the issue with the latest.

To answer your other questions:

So far, I have only seen the problem in our app. I have not reproduced it with the test server. The crash occurs in the websocket server. There are other threads in the app, but only one service thread for the websocket server. I will update later if still seeing the problem.

Thanks
