### ISSUE TITLE
External poll() unusable since commit 44e0b088fa9b

### ISSUE THREAD

**Issue by jmillan** [warmcat/libwebsockets#510]
Hi,

I'm using *libwebsockets* in server mode only.
I'm using external poll() (externally handled `libevent`) for a long time.

Trying to upgrade to version 7, I've found that connections (HTTP or HTTPS) are not stablished, being the last working commit: f05167dee6f.

I'm not getting a response to the HTTP request, and the POLLIN callback to the newly created **fd** (which calls `lws_service_fd()`) is executed in an infinite loop.

This is the flow for an incoming HTTP request to the server:

* callback_http. reason: 17 (LWS_CALLBACK_FILTER_NETWORK_CONNECTION)
* lws_allocate_header_table: wsi 0x7f44e4000fb0: ah (nil)
* lws_allocate_header_table: wsi 0x7f44e4000fb0: ah 0x18f98d0: count 1 (on exit)
* callback_http. reason: 29 (LWS_CALLBACK_WSI_CREATE)
* callback_http. reason: 19 (LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED)
* accepted new conn  port 51283 on fd=520
* callback_http. reason: 35 (LWS_CALLBACK_LOCK_POLL)
* callback_http. reason: 32 (LWS_CALLBACK_ADD_POLL_FD) // fd=520, events=POLLIN
* adding POLLIN callback for new fd
* callback_http. reason: 36 (LWS_CALLBACK_UNLOCK_POLL)
* POLLIN callback called for new fd. calls lws_service_fd() with *pollfd* object:
 `{ lws_sockfd_type:520, events:0, revents:POLLIN }`
* last point repeats in an infinite loop

Looking at the changes in commit 44e0b088fa9b , I made the following patch which makes it work for that revision:

**NOTE**: Please, don't consider it as any kind solution as I made it almost blindly. 

Such patch though does not work for more recent revisions. I'm just hoping that this information will help for a deeper debug.

````
diff --git a/lib/server.c b/lib/server.c
index c60405e..2b6ae3c 100644
--- a/lib/server.c
+++ b/lib/server.c
@@ -698,7 +698,7 @@ int lws_server_socket_service(struct lws_context *context,

                /* any incoming data ready? */

-               if (!(pollfd->revents & pollfd->events && LWS_POLLIN))
+               if (!((pollfd->revents | pollfd->events) & LWS_POLLIN))
                        goto try_pollout;

                len = lws_ssl_capable_read(wsi, context->serv_buf,
diff --git a/lib/service.c b/lib/service.c
index 8d5c2d5..f138d92 100644
--- a/lib/service.c
+++ b/lib/service.c
@@ -524,7 +524,7 @@ lws_service_fd(struct lws_context *context, struct lws_pollfd *pollfd)
                /* any incoming data ready? */
                /* notice if rx flow going off raced poll(), rx flow wins */
                if (wsi->rxflow_buffer ||
-                   !(pollfd->revents & pollfd->events & LWS_POLLIN))
+                   !((pollfd->revents | pollfd->events) & LWS_POLLIN))
                        break;
 read:
                eff_buf.token_len = lws_ssl_capable_read(wsi,
````

Any other test I can do or any info I can provide, please let me know.

Best regards,

**Comment by lws-team** [comment]
Just trying libwebsockets-test-server-extpoll on master, he seems fine.

That's broken for you?

**Comment by lws-team** [comment]
v1.7.7 version of libwebsockets-test-server-extpoll also works well here.

If either of the extpoll test servers are broken for you, it'll be good to know more about your platform.

If they work okay, then either aligning your app with what the test servers do, or adding a hack on the test server to align it with what your app is doing (that makes the symptom come) and send me the patch should move us forward.

**Comment by jmillan** [comment]
Hi,

The test is working for me too. I'll check its code and see what I'm missing in my server side. I didn't spot any required change on the changelog related to the external poll.

I'll come back with whatever I see, a bit later.

Thanks.

**Comment by jmillan** [comment]
Found!

It works if I call `lws_service_fd()` with a `pollfd` object which `events` value equals the `events` value of the lws_pollargs (*in) received on the `http_callback` called with reason `LWS_CALLBACK_ADD_POLL_FD`.

If I do it that way, the connection is stablished. Otherwise I get an infinite loop as described.

Before the commit  44e0b088fa9b, calling `lws_service_fd()` with a pollfd.events value of 0 worked. There was no need to store such value form the `LWS_CALLBACK_ADD_POLL_FD` callback.

Is it the expected behaviour? Thanks for any explanation.

**Comment by jmillan** [comment]
Hi,

Sadly, I cannot reproduce it in libwebsockets-test-server-extpoll.

Please, let me show how I'm doing it in case you spot why is it now necessary to pass the `events` value to `lws_service_fd() function.

On new connection:

1. callback_http. reason: LWS_CALLBACK_ADD_POLL_FD
2. given the `lws_pollargs` in the previous callback. I get `pa->fd` (fd) and `pa->events` (events)
3. set the libevent callbacks on the `fd` given the `events`:
  * if `events & POLLIN`; then I set a read event to fd
  * if `events & POLLOUT`; then I set a write event to the fd

The read and write event callbacks are the function, and it works as follows, being it's arguments (int fd, short what)

1. I create a new empty `pollfd` (tmp_pollfd) object.
2. tmp_pollfd.fd = fd
3. if `what & EV_READ`; then `tmp_pollfd.revents |= POLLIN`
4. if  `what & EV_WRITE`; then `tmp_pollfd.revents |= POLLOUT`
5. I call `lws_service_fd()` with `fd` and `pollfd` as arguments.

This has been working for a long time, up to the commits I've previously indicated.  In order to make it work with the newest libwebsockets versions I need to store `pa->events` from LWS_CALLBACK_ADD_POLL_FD callback and copy the value to the `pollfd.events` that I pass to `lws_service_fd()`

Any comment that helps me understand it is very appreciated.

**Comment by lws-team** [comment]
The only place that calls ADD_POLL_FD sets pa->events to a canned value of POLLIN

```
	pt->fds[pt->fds_count].events = LWS_POLLIN;
	pa.events = pt->fds[pt->fds_count].events;
...
```

So the workaround is just a way to force the pollfd events to have POLLIN active.

The feature that's different in lws about this is the ah (Header processing struct) pool.  If an incoming connection arrives with no free ah left in the pool, lws now adds the wsi to a waiting list, and flowcontrols it by disabling his POLLIN.  When an ah is freed, the next guy in the waiting list gets it and his POLLIN is enabled so we can get his header data and start processing it.

This means your event loop handling has to deal with pending rx being there, but POLLIN disabled in the pollfd events.  In that case we don't want to hear about it, since lws has suppressed it because it's not ready to handle it yet.

```
POLLIN callback called for new fd. calls lws_service_fd() with pollfd object: { lws_sockfd_type:520, events:0, revents:POLLIN }
```

From what you describe, your setup can find itself with the pollfd.events with POLLIN disabled, but an active POLLIN event it passes to lws.  Lws rejects to deal with it because it disabled POLLIN, leaving your event unserviced and still there next time around and 100% cpu coming.  Actually a POLLIN event with POLLIN not enabled in the events is wrong in itself.  So we need to understand how that comes about... is the library failing to update the extpoll code that events became zero or your extpoll code is not reacting to it?

**Comment by dosvald** [comment]
Just to jump in if it may help - I believe I encountered a problem similar to this one a while ago. I resolved it, I just needed to make sure that, when `struct pollfd` is forwarded to libwebsockets, its `revents` member contains the proper events (tracked via FD mode callbacks). In addition to that I also had to set ( `|=` ) both `POLLERR` and `POLLHUP` flags into the `revents` member.

**Comment by lws-team** [comment]
I think his problem is the socket does have pending POLLIN, but because POLLIN is not enabled in the .events, he shouldn't continuously report it in the .revents.

If you compare it to the test server EXTPOLL, he's doing it with a real poll().  In that case poll() responds with the .events that were active at the time he started the poll().  So if .events for POLLIN was enabled originally, but was later disabled, he might one time do service for POLLIN while .events doesn't have POLLIN enabled.

But the next time he enters poll(), the modified events, with POLLIN disabled, is seen and is active.  So subsequent poll() will not tell about any POLLIN, and no problem is coming.

So at least the part of the problem we can see is either we don't report POLLIN dynamic enable / disable properly using EXTPOLL callbacks, or the user code handling it isn't taking the right amount of care dealing with with dynamic changes reported on LWS_CALLBACK_CHANGE_MODE_POLL_FD.

(and I think or-ing POLLERR on .revents will cause it to think every connection has died)

**Comment by dosvald** [comment]
> (and I think or-ing POLLERR on .revents will cause it to think every connection has died)

Sorry for the confusion, you're right. On second look at my code, that or-ing only happens on real error case, not always, as is proper. Otherwise nothing would work.

So the conclusion as you wrote is correct, to solution should be to more closely take care of MODE_POLL_FD callbacks and forward correct values in both `events` (reflecting the events LWS last set via MODE_POLL_FD cb) and `revents` (those which actually happened) to lws.

**Comment by jmillan** [comment]
Hi everyone,

Thanks a lot for your comments. This statement is the key:

````
So the conclusion as you wrote is correct, the solution should be to more closely take care of MODE_POLL_FD callbacks and forward correct values in both events (reflecting the events LWS last set via MODE_POLL_FD cb) and revents (those which actually happened) to lws.
````

`lws_service_fd()` does expect now the `events` value that it previously posted via MODE_POLL_FD cb. 

I previously used to consider the `events` value posted by MODE_POLL_FD to set the corresponding callback on the fd, but later only pass to `lws_service_fd` the `revents` representing the events that actually happened for that fd.

The following changes made in 44e0b088 actually reflect it:

`````
@@ -522,11 +522,11 @@ lws_service_fd(struct lws_context *context, struct lws_pollfd *pollfd)
                }

                /* any incoming data ready? */
-
-               if (!(pollfd->revents & LWS_POLLIN))
+               /* notice if rx flow going off raced poll(), rx flow wins */
+               if (wsi->rxflow_buffer ||
+                   !(pollfd->revents & pollfd->events & LWS_POLLIN))
                        break;
`````

`````
@@ -733,7 +698,7 @@ int lws_server_socket_service(struct lws_context *context,

                /* any incoming data ready? */

-               if (!(pollfd->revents & LWS_POLLIN))
+               if (!(pollfd->revents & pollfd->events && LWS_POLLIN))
                        goto try_pollout;
`````

Thanks a lot for the clarifications.

**Comment by lws-team** [comment]
Glad you're working again.
