### ISSUE TITLE
[Question] How to handle WebSocket connections with no protocol specified?

### ISSUE THREAD

**Issue by emptyVoid** [warmcat/libwebsockets#514]
Suppose we have protocols 'v1' and 'v2' on the server side:
```c++
lws_protocols Protocols[] =
{
    /* first protocol must always be HTTP handler */
    { "http-only", HttpCallback, sizeof( HttpSession ), 15 * 1024 },
    { "v1",        WsV1Callback, sizeof( WsV1Session ),  4 * 1024 },
    { "v2",        WsV2Callback, sizeof( WsV2Session ), 10 * 1024 },
    /* terminator */
    { }
};
```

And we want to support client connections with no protocol specified:
```javascript
if (typeof MozWebSocket != "undefined") {
    websocket = new MozWebSocket(wsUri);
} else {
    websocket = new WebSocket(wsUri);
}
```

How do we tell ```libwebsockets``` to use 'v1' in this case?

**Comment by lws-team** [comment]
Those guys with no protocol header are accepted and bind to protocols[0].

**Comment by emptyVoid** [comment]
So how do we differentiate between normal HTTP request and a WS connection?

**Comment by lws-team** [comment]
The callbacks used for activity are different, eg LWS_CALLBACK_HTTP_WRITEABLE vs LWS_CALLBACK_SERVER_WRITEABLE / LWS_CALLBACK_CLIENT_WRITEABLE.

In fact you can have one callback used for http, ws server and ws client.

**Comment by emptyVoid** [comment]
Oh, that's great!
Thanks!

**Comment by lws-team** [comment]
It should solve it for now, but actually there's a missing piece here now protocol plugins exist... a vhost needs a way to select a protocol as the default then.  Because the protocol callback is in his own generic plugin and the server no longer controls the callback directly.

**Comment by lws-team** [comment]
I added a patch on master + v2.0-stable that lets a vhost tag a protocol with the option "default".

https://github.com/warmcat/libwebsockets/commit/f6585285cbe248901866dbd36e2b85c723b8f4c6

It's simple to do in JSON on lwsws but it's also possible to do it in code if you create the vhost separately.

Interestingly because it allows a linked-list of name/value pairs in the vhost already to declare per-vhost protocol options, this does not impact the library api, even though it would traditionally have been a new member in a public struct.
