### ISSUE TITLE
[Question] Is it possible to disable nonessential error messages on the server side?

### ISSUE THREAD

**Issue by emptyVoid** [warmcat/libwebsockets#520]
At the moment when client passes a nonexistent protocol name on connection, I see the following string in the server log:
```No protocol from list "test" supported.```

Is it possible to disable error messages originating from improper client's actions? (I don't want server's log to be spammed due to client's errors or bad intentions)
I would still like to be informed of critical and unexpected server-side errors.

**Comment by lws-team** [comment]
I do think there's probably something to do here, but 'Nonessential' is a bit of a fluid concept.... for example if nothing was working because your client was using the wrong protocol name accidentally, that message might save you a lot of time.

In terms of traditional server-type logging, you can get apache compatible logs now by enabling LWS_WITH_ACCESS_LOG at cmake and info.set log_filepath at context (actually vhost, but they are combined by default) creation time.  That gets you down to this

```
121.211.128.237 - - [09/May/2016:11:22:50 +0800] "GET /warmcat-trac.png http/1.1" 304 133 Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
```

If you can give more examples of 'nonessential' logging I can look at reducing its log level to info or below so it's off by default.

**Comment by emptyVoid** [comment]
I do agree the message is helpful during development, though not so much on a production instance. 
So far I've seen only the "No protocol" message in our logs. However there're some similar messages  in the LWS source code, here's the ones I've found:
```
lwsl_err("Unknown upgrade\n");
lwsl_err("missing http2_settings\n");
lwsl_err("h2c upgrade...\n");
```

PS: thanks for the hint on `LWS_WITH_ACCESS_LOG`!

**Comment by lws-team** [comment]
The four instances you mention are downgraded to info.... info is off by default (with 7 as the default log level) and is only compiled in at all when cmake is in DEBUG build (-DCMAKE_BUILD_TYPE=DEBUG)

If you see some more that fall into that category and have their logging too strong, a patch is welcome.
