### ISSUE TITLE
lws_protocols - rx_buffer_size

### ISSUE THREAD

**Issue by ondraco** [warmcat/libwebsockets#522]
Hello,

I have just run into something which I believe to be bug or wrong documentation. The documentation of `struct lws_protocols` states that the `rx_buffer_size` should be the size of the biggest legal frame and that the padding is automatically allocated but that does not seem to be case. 

I have used 4096 (biggest frame size that I support) as `rx_buffer_size ` but the `lws_write` of 4096 bytes always ends up with truncated send because it requires buffer of size 4104 (4096 + 8 pre). This led to a huge slow down until i made the `rx_buffer_size` larger.

```
 * @rx_buffer_size: if you want atomic frames delivered to the callback, you
 *		should set this to the size of the biggest legal frame that
 *		you support.  If the frame size is exceeded, there is no
 *		error, but the buffer will spill to the user callback when
 *		full, which you can detect by using
 *		lws_remaining_packet_payload().  Notice that you
 *		just talk about frame size here, the LWS_PRE
 *		and post-padding are automatically also allocated on top.
```

Thank you,
Ondrej

**Comment by lws-team** [comment]
There is something to fix here, but there are two different 'overloads' of this member's meaning at work.

In the original meaning of it for rx, it's after all 'rx_buffer_size', the comment is correct, from ./lib/server.c

```
		n = wsi->protocol->rx_buffer_size;
		if (!n)
			n = LWS_MAX_SOCKET_IO_BUF;
		n += LWS_PRE;
		wsi->u.ws.rx_ubuf = lws_malloc(n + 4 /* 0x0000ffff zlib */);
```

Since cea07d6f1f0bec0d1a4eb56027281b4cb57153ed it got overloaded as also being the max chunk for tx.  That came out of a realization that it's not zero-cost to excessively 'send' data on a socket that will only accept something much smaller, in the original bug he's trying to send() 100MB on a real socket, clearly it will only take a fraction of it but it turned out the kernel has to sit there dealing with the whole 100MB each time just in case, wasting many seconds.

The relationship between what a network interface might accept for tx and rx_buffer_size is a bit nonobvious but in most cases there's probably some relationship between expected rx packet size and reasonable estimate of atomic tx size on the same socket.

So I pushed a patch on master + v2.0-stable also making the tx chunk size limit include LWS_PRE + 4 as the original comment suggests.
