### ISSUE TITLE
Can I open multiple lws contexts which listen on different port?

### ISSUE THREAD

**Issue by cppbitman** [warmcat/libwebsockets#523]
I have an application scenario, in which multiple lws context listening on different port are created and triggered for callback in single lws_service loop. Additionally more contexts can be added to the loop dynamically? 
Can I realize that with libwebsockets?
Can some mechanic like external poll support this?

**Comment by lws-team** [comment]
Yeah... but there is only ever one context.  In v2.0 and above, you may have multiple vhosts, and each vhost may listen on a port.

In code, you do that by creating the context with the info.options flag LWS_SERVER_OPTION_EXPLICIT_VHOSTS.  Without that flag at context creation time, one default vhost is created along with the context.  With that flag, only the context is created, and you can use lws_create_vhost() as many times as needed, also using struct lws_context_creation_info to describe the vhost.  Look at the definition in libwebsockets.h to see which members apply to the context, and which to the vhost.

If you have a generic 'webserver' type application, you should look at using lwsws instead

https://github.com/warmcat/libwebsockets/blob/master/README.lwsws.md

You can configure the vhosts using JSON, and use lws protocol plugins to do the ws part.  An example of a real syatem with 11 vhosts using lwsws is https://libwebsockets.org itself.

**Comment by cppbitman** [comment]
Thanks, I can now have multiple vhosts, and each vhost listen on a port. 
Another problem is I want to add another vhost when lws_service() loop is already running.
In my thoughts, I can trigger some protocol callback in some way. In the protocol callback, I will call lws_create_vhost() to create a vhost, and then that vhost will join in the loop with callback of which triggered like other vhosts. 
Can libwebsockets support this?

**Comment by lws-team** [comment]
It's not designed for it exactly.

Thinking about libuv case, you can randomly add vhosts after context creation, and the loop (in the case something else owns the loop) may be running.

However at some point in the init, we drop privileges, because we have the concept we do all the things requiring them (listen on ports <1024, open logs in restricted dirs) in some init phase.

Then we formally bind to the libuv loop and instantiate per-vhost protocols.

So if you added a vhost later, it couldn't listen on a privileged port, and something would need to be done about instantiating his protocols, otherwise it can work.

But... it's pretty strange.  Is there some reason you settled on this idea?

**Comment by cppbitman** [comment]
In my application, I have used libevent for network data transport. In my implementation, the libevent event main loop runs in a thread. In another thread, I can trigger a callback that will be executed in the same thread as that of  event main loop. In the callback, a network endpoint is created and bind to some port. I can add network endpoint dynamically. This make me consider if libwebsocket can act in the same way.

**Comment by lws-team** [comment]
An event loop library is just a generic thin wrapper over the os assets, that's not what lws is.

In a real system randomly opening listening ports has implications for, eg, firewalling.

Possibly it's my lack of imagination, but every way I could think of it's better to establish one 'well-known' listen port and use, eg, the uri namespace to map different uses (ie, via lws mounts).

**Comment by eludar** [comment]
Hi,
I'm using the library version 2.0 and I'm not able to get multiple lws contexts working. I have two servers listening on 2 different ports and each server has its own lws context. Both servers are using TLS (SSL). When I try to connect to the server which is created second, I get no problems. However, when I try to connect to the server which was created first, I get the **segmentation fault**.
I have identified the failure point to be in the `lws_ssl_server_name_cb()` callback function. The trouble is caused by the global variable `openssl_SSL_CTX_private_data_index`. This variable is initialized by calling the function `SSL_CTX_get_ex_new_index()` within `lws_context_init_ssl_library()`. Since I create 2 lws contexts, `lws_context_init_ssl_library()` is called twice and `openssl_SSL_CTX_private_data_index` is finally fixed to `1` (each call to `SSL_CTX_get_ex_new_index()` returns index incremented by 1). Now, when I try to connect to the first server, the `SSL_CTX_get_ex_data()` returns `NULL`, since `openssl_SSL_CTX_private_data_index == 1`. When I change the lws code so that `openssl_SSL_CTX_private_data_index` is fixed to `0` (in other words `SSL_CTX_get_ex_new_index()` is not called) both servers seem to work fine.
I have also tested my code with libwebsockets version 1.7.0 and it seems to work fine.

**Comment by lws-team** [comment]
You should have one context.

You can create multiple vhosts in that context as described in the second comment on this issue.  You need to change your code to that scheme.

**Comment by eludar** [comment]
OK, I will adapt my code to that scheme. However, when the callback with reason `LWS_CALLBACK_ESTABLISHED` fires, how can I know on which port a client is connected? Or in other words - how do I know to which vhost this new connection belongs?

**Comment by lws-team** [comment]
There's an api lws_get_vhost(wsi); that lets you get hold of a pointer to the wsi's vhost; some other apis need that.

**Comment by eludar** [comment]
Oh, I tried to find such a function, but I guess I didn't try hard enough :-)  In the branch I'm on (v2.0-stable) it is called lws_vhost_get()...
Thank you very much for superb support!
