### ISSUE TITLE
Bind socket to a spcific IP address

### ISSUE THREAD

**Issue by minghuadev** [warmcat/libwebsockets#538]
Hi, Is binding to an IP address something can be done already? 

From my reading you can only select an interface. When running on the openshift.com online version a gear does not have access to the information of available interfaces. You only get an assigned IP address and port that your application should bind to. I'm looking at running mosquitto on openshfit, and it failed to bind. 

If there is already a way of doing it, that would be great! But can someone advise how? 

If not done already, can this be a new feature to be added? I can suggest a patch for further review, or create a pull request. 

Thanks.
-Minghua

**Comment by lws-team** [comment]
This already works, at least on *nix, just give the dotted-quad IP address of the interface in info.iface.  I just tried it on my local box with lwsws, `"interface": "192.168.2.233"` gives this in netstat

```
tcp        0      0 192.168.2.233:7681      0.0.0.0:*               LISTEN      -        
```

the default of not setting "interface" gives

```
tcp        0      0 0.0.0.0:7681            0.0.0.0:*               LISTEN      -        
```

Did you try it?

**Comment by lws-team** [comment]
Well, please reopen if some problem exists.

**Comment by minghuadev** [comment]
Hi, Thanks for the quick response! 

Just tried on a local machine. Yes, it works! 

Will see on openshift shortly.

**Comment by minghuadev** [comment]
Yes, it works on openshift too. Thanks a lot!

**Comment by lminiero** [comment]
Not sure if something changed in the API, but setting the `iface` property to the dotted IP address doesn't seem to work for me (although I think it worked for me in the past?). The documentation also seems to only mention interface names: https://libwebsockets.org/libwebsockets-api-doc.html

Is this expected, or a bug? I'm admittedly a bit behind with my installed version (commit 477df670cf654c686d2f7a65b06ec84eb5c362ee), and I guess so was the other person who tried (v2.0.2), so not sure if this is an actual issue in master.

**Comment by lws-team** [comment]
What's your platform?  It just calls the platform api and does whatever that does.

Why don't you try master.

**Comment by lminiero** [comment]
Both me and the other user are on linux.

I haven't tried master yet as I'm "afraid" there may be breaking changes that could break my code too: considering I'm using websockets support in a few projects, and at the moment I don't have the cycles to update the core part to address changes that may be needed, for the moment I'm stuck with that. As soon as I have some more time I'll definitely check the latest version.

For the time being I think I'll add an external method myself, one that checks what interface a provided IP is associated with, so that I can feed an interface name to libwebsockets.
