### ISSUE TITLE
Linking error on windows using latest libuv and latest libwebsockets master 

### ISSUE THREAD

**Issue by meiry** [warmcat/libwebsockets#539]
Hello 
checkout today the latest lws and using the latest libuv on windows 
also include manually the missing lib's:
advapi32.lib
iphlpapi.lib
psapi.lib
userenv.lib
im getting this linking error :
```
1>------ Build started: Project: test-server, Configuration: Debug Win32 ------
1>libuv.lib(util.obj) : error LNK2019: unresolved external symbol _GetAdaptersAddresses@20 referenced in function _uv_interface_addresses
1>libuv.lib(util.obj) : error LNK2019: unresolved external symbol _GetProcessMemoryInfo@12 referenced in function _uv_resident_set_memory
1>libuv.lib(util.obj) : error LNK2019: unresolved external symbol __imp__GetUserProfileDirectoryW@12 referenced in function _uv__getpwuid_r
1>g:\dev\cpp\server\libwebsockets\libwebsockets\libwebsockets_libuv\build\bin\Debug\libwebsockets-test-server.exe : fatal error LNK1120: 3 unresolved externals
========== Build: 0 succeeded, 1 failed, 3 up-to-date, 0 skipped ==========
```
every thing used to work , week ago .

**Comment by lws-team** [comment]
Well, normally I couldn't say much since I don't use windows.

However I got current master with all features working on appveyor recently.

There are no such special treatments about *.lib needed there, whatever cmake does builds without errors (and without warnings, if we discount some problem with libz getting included twice).

Appveyor is using MSVC 14.

You can see for yourself, this is with lwsws, libuv, sqlite3 now as well.  The libuv is quite recent, from a few weeks ago IIRC.

https://ci.appveyor.com/project/lws-team/libwebsockets/build/job/fimi4xxa8qsh5s5n

The missing symbols are not to do with lws either.  So I think this is some problem with your build config and / or libuv (eg, bits of different libuv getting used in different places).

**Comment by meiry** [comment]
Hey , again thanks for yor fast replay 
it can be something in my build , im not sure as im checking it now 
every thing is woring now , as i added :
iphlpapi.lib
psapi.lib
userenv.lib

on top of the lib's list so it looks like this now ,
```
iphlpapi.lib
psapi.lib
userenv.lib
kernel32.lib
user32.lib
gdi32.lib
winspool.lib
shell32.lib
ole32.lib
oleaut32.lib
uuid.lib
comdlg32.lib
advapi32.lib
lib\Debug\websockets_static.lib
lib\$(Configuration)\zlib_internal.lib
g:\dev\cpp\server\libuv\libuv\Debug\lib\libuv.lib
ws2_32.lib
```
Very strange ..

**Comment by lws-team** [comment]
I'm pretty sure it's not normal to have to inform it by hand that you need things like kernel32.lib.

Anyway I think it's not related to lws because of appveyor, so there's nothing I can do about it.  If something does point to lws, please reopen.

**Comment by meiry** [comment]
Thanks!
