### ISSUE TITLE
Request: Raise Max_HTTP_Header_Data

### ISSUE THREAD

**Issue by bdkjones** [warmcat/libwebsockets#550]
### Summary:
I propose raising the maximum size of HTTP headers that libwebsockets can process before it fails to handle the request.

### Context:
The `lws_context_creation_info` struct currently has a property named `max_http_header_data` which is  a `short`. As such, the max value for this is 32,767 or about 32kb. If an HTTP request comes in with more header data than that, libwebsockets spits out a message about running out of room to handle header data and then destroys the connection.

### Reason For Change:
While 32kb *seems* like it would cover every possible HTTP request, that's actually not the case. I use libwebsockets to provide browser-refreshing for a separate HTTP server that my app runs. The websocket server runs in the same domain as the other HTTP server, so requests sent from the browser to libwebsockets' server include cookies for that domain. I have some users who set relatively obscene amounts of data as cookies. Since there's no way to stop the cookies from being added to the HTTP request that's going to libwebsockets, I need to either:

1. be able to handle more than 32 kb of data in headers, or: 
2. somehow "pre-process" the incoming request to strip away the unneeded cookie header values before libwebsockets attempts to upgrade the connection to `ws://`.

While I understand that libwebsockets runs in many places where memory is severely constrained, it also runs in lots of places where memory is not constrained at all. Unless there are other side effects, changing the `max_http_header_data` to a standard `int` instead of a `short` would give me plenty of headroom.

**Comment by lws-team** [comment]
I take the point... actually the guys who care about that are the context, of which there is only one, and the ah, which are restricted in a pool, default 16.  So the impact of promoting the types should be just a few tens of bytes for people who will never get fat headers.

I pushed a patch on master, for compatibility he leaves the existing short in the info struct alone.  However if that short is 0, he will check a new unsigned int info struct member max_http_header_data2... if that's also 0, all is as before.  Otherwise max_http_header_data2 is used.

In the private header the context member for this is upgraded and the offset in lws_fragments also must become unsigned int from short.  I think that's enough in the headers but there may be some shorts in the code that also need updating, at least there are no related shorts in parsers.c where I'd expect to find them, so maybe OK already.  At least it still works as before without using max_http_header_data2.

Please try it with max_http_header_data = 0 and max_http_header_data2 set, and see what happens.

**Comment by lws-team** [comment]
@bdkjones: this helped?  Or made trouble?

**Comment by bdkjones** [comment]
Thanks for the fast response! I'll grab master and test the changes this afternoon. I'll report back in a few hours.

**Comment by lws-team** [comment]
Well, if there's anything further needs doing, feel free to reopen.

**Comment by iblender** [comment]
Where is the file with this parameter stored?

**Comment by lws-team** [comment]
You can decide it at context creation time

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n363
