### ISSUE TITLE
Bind vhost to IPv6 without IPv4

### ISSUE THREAD

**Issue by dosvald** [warmcat/libwebsockets#551]
Regarding the IPv6 support and IPv4 mapping that lws uses, I think there might be room for improvement here. As it is, there is no occurrence of `setsockopt` with `IPV6_V6ONLY` in lws, which means that depending on the value of `/proc/sys/net/ipv6/bindv6only` the IPV6-capable sockets of lws will sometimes be v6only and sometimes not. That means that two vhosts on same port that are ipv4 and ipv6 can't be made at the same time. Perhaps lws could adopt some options per socket (vhost) which would mean either: disable v6only (use mapping), enable v6only (don't use mapping) or use OS default.

I'm not sure how other projects handle the v6only and sockets, but this option would enable to have separate vhosts for ipv4 port 80 and ipv6 port 80.

I'm guessing that would entail adding two bits of creation info `option` flags, or a separate field.

**Comment by lws-team** [comment]
This seems superceded by #552

**Comment by dosvald** [comment]
Not really.
That issue says: I want to listen on `0.0.0.0:4444` on vhost 1, and `[::]:6666` on other vhost.

This issue says: I want to be able to control whether listening on `[::]:6666` means "listen for IPv6 and IPv4 via mapping" or "listen for IPv6 only and let other vhost / daemon / whatever occupy "0.0.0.0:6666".

**Comment by lws-team** [comment]
Well I assure you on this Friday evening where I am, there are not three of me to take care of your multi-spawning problems.  So it is better to pick one for me to worry about.

**Comment by dosvald** [comment]
Okay, sorry for upsetting you, the previous comment may have come out a bit harsh with the "I want" this and that. Also, thanks for providing the great library!

Do you want to work on those tickets or should I do that?

**Comment by lws-team** [comment]
No I understand the general question (although to be honest, ipv6 is somewhat mysterious to me) and would like to support it.  It's just that I don't get 3x as muscular solving it because you file three issues about the same thing in a hour, I'm more likely to get 3x as depressed and go to bed.

I can migrate the ipv6-fulness flag to vhost by myself easily but is that really going to solve your problem?  My knowledge about it is I can either put ipv6 modules / driver in the kernel or not; depending on that ifconfig tells me ipv6 addresses or not.

**Comment by dosvald** [comment]
Let's continue discussion in #552 then
