### ISSUE TITLE
Unix -Werror problem

### ISSUE THREAD

**Issue by markrad** [warmcat/libwebsockets#563]
I notice that you pass the -Werror to the compilation. I'm wondering if you would entertain the idea of being able to turn that off on demand. When I use your library in certain cross compilation scenarios I unable to avoid certain insignificant warnings being generated. Unfortunately the -Werror flag causes the build to fail.

Thanks.

**Comment by lws-team** [comment]
-Werror has been good to have... when you build with a lot of parallel processes it's quite easy to miss warnings otherwise.  And it's painful to only find problems after it's pushed in Travis or so, when they actually existed before.

What are the "unavoidable warnings"?  We should probably see if they can be "avoided" somehow first.

**Comment by lws-team** [comment]
If you want to discuss the "unavoidable" warnings, please reopen.

**Comment by lws-team** [comment]
Okay... I appreciate being able to understand your problem... your workaround sounds pretty reasonable.
