### ISSUE TITLE
buffer length limit

### ISSUE THREAD

**Issue by jageee** [warmcat/libwebsockets#564]
Is there any limitation of buffer size?
I'm trying to send 22kB and get failed.
Thanks.

**Comment by lws-team** [comment]
What version of lws is it and exactly 'fails'?

If not all the data can be written on the socket, lws will buffer any remaining data internally and complete the send automatically.  Only when that's all used up will it let the user code see another writable callback (so it can send something else).

**Comment by jageee** [comment]
> What version of lws is it and exactly 'fails'?
I use 1.6.0

> Only when that's all used up will it let the user code see another writable callback 
So , before each sending (lws_write) should i check is write available?

>  lws will buffer any remaining data internally and complete the send automatically
the max expected buffer length is 128k, should support anyway?

Thanks

**Comment by lws-team** [comment]
Yeah... you should only send data when you get a WRITEABLE callback.  Look at how the test server handles it.

At v1.6, lws will try to write() all 128KB to the socket... if that was all accepted then no problem.  Otherwise whatever was left over will be buffered and auto-sent, it has no fixed limit to that buffer size.

Obviously it's inefficient if you expect remote clients will never accept 128KB at the write() it's more efficient to send smaller chunks in multiple WRITABLE callbacks, to eliminate the extra buffering in lws.  But it will work ok either way if you regulate it using the WRITABLE callback.

**Comment by jageee** [comment]
Thanks
