### ISSUE TITLE
[Question] Is there a way to trigger user callback from another thread?

### ISSUE THREAD

**Issue by emptyVoid** [warmcat/libwebsockets#571]
Suppose we have a dedicated thread (1) for LWS with infinite loop calling ```lws_service```. Another thread (2) has some data ready to be sent to WS clients.
Is there a thread-safe way for the thread (2) to trigger a user callback invocation on the thread (1)?

**Comment by lws-team** [comment]
Yes, the other thread is OK to call lws_callback_on_writable() or one of the variants.

You need to add some locking on the other thread around that call, and in the service thread at LWS_CALLBACK_WSI_CREATE in order to LWS_CALLBACK_WSI_DESTROY to make sure there are no races around which wsis are live or wsi disappearing underneath you.

Additionally to get it serviced immediately if you are using poll(), you can call lws_cancel_service(context) afterwards on the non-service thread to force the poll() loop to end early if it was idle, so it will do a new poll() wait with the callback on writable active.

**Comment by emptyVoid** [comment]
Thanks!
I guess I would just call ```lws_cancel_service(context)``` from thread (2) and handle new data in the main loop of thread (1) right after ```lws_service``` terminates.

**Comment by lws-team** [comment]
If what you want it to do has side effects including writing ws data, you'll need to specifically do that via lws_callback_on_writable() or a variant of that.  Because there is otherwise no relationship between whatever happened in your second thread and the state of the connection to the remote peer.

If you're not going to write anything you can hack the service thread.  But the official way also works on, eg, libuv event loop.

**Comment by emptyVoid** [comment]
I do not plan to share ownership of the buffers (which are submitted to LWS for delivery) between threads: thread (2) would write new data to a buffer and transfer its ownership to thread (1) in a thread-safe manner.
The only reason why I prefer ```lws_cancel_service``` over ```lws_callback_on_writable``` is publisher-subscriber pattern we use to deliver the same data to multiple clients. This way I would only need to lock the global data queue (once to push data on thread (2) and once to pop it on thread (1)), and let the service thread (1) manage per-client data queues.

**Comment by lws-team** [comment]
OK... but when you do deliver the data to a particular connection, it must be done using lws_callback_on_writable().
