### ISSUE TITLE
Handle handshake refused from server

### ISSUE THREAD

**Issue by stefanobider** [warmcat/libwebsockets#576]
Hi everyone, I write again for help. I am using libwebsockets in my c++ application to implement both a server and a client. I have an issue with the **client** side: I try to connect to a Nodejs server that uses the `ws` module (https://github.com/websockets/ws/blob/master/doc/ws.md). On the server, some checks are performed to accept or refuse the handshake. ATM the checks only focus on the *Authorization* header which I set from the callback on `LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER`. It works very well except for one thing: if the authentication fails (e.g. expired token) I only get `LWS_CALLBACK_CLIENT_CONNECTION_ERROR` with no additional information. I really need to detect this case in order to request a new token or at least give a feedback to the user. Am I doing something wrong or missing some details? I read again all the available LWS docs but I could not find a reference...
Thank you very much

Stefano

**Comment by lws-team** [comment]
I see... at least I think I see... so the server did not agree to upgrade the connection to ws basically, and you want to understand that is what happened rather than, eg, connection refused type of CLIENT_CONNECTION_ERROR.  Obviously ws close indications are out of the question since it didn't upgrade.

Does it return a specific HTTP response code for that?  You can take a look with, eg, tcpdump.

**Comment by stefanobider** [comment]
All correct. The server does return a 401 code.

**Comment by ajsetter** [comment]
Part of the security model I'm currently working with does the same thing i.e. rejecting upgrade requests without the correct auth headers (libwebsocket client, python autobahn server). 

However in our server implementation, we have complete control of the nature of the rejection response, including the response status code. We also are unable to detect a rejection instead of generic error, but we don't have it as one of our priorities at the moment.

Therefore, I'd like to request that any solution coming of this not be dependent on the status code of the response/rejection, but rather be solely dependent on the fact that the response was NOT a "switching protocols"/"accept" response.

**Comment by lws-team** [comment]
I just pushed https://github.com/warmcat/libwebsockets/commit/b1f3942b079ab4775d123589dd5396b69d67f4bc on master, this adds 36 canned reason strings that may now be passed to user code with the in parameter of CLIENT_CONNECTION_ERROR.

And that patch also adds a pwsi member to the client connect info struct that optionally lets you pass a pointer to a *wsi that should get set to the new wsi before the client connect api returns.  That ensures your user code can know which wsi that may come in the callback is which.

Let me know if that is scratching the two different itches here.

**Comment by stefanobider** [comment]
Thanks Andy, I will try this ASAP. So to get this straight: on
`CLIENT_CONNECTION_ERROR` I need to test `in` against one of those strings
("HS: Server did not return 200" or more likely "HS: ws upgrade response
not 101" depending on what the server does behind the curtains) ? I deeply
appreciate your incredibly swift solution, but perhaps we should keep the
topic open? I think that a dedicated reason would make sense in this case
(something like *CLIENT_HANDSHAKE_REFUSED* or *CLIENT_CONNECTION_REFUSED*)
because many ws server implementations rely on handshake refusal for
filtering unauthorized connections. Let me know what your thoughts on the
matter are. Thank you again!

**Comment by lws-team** [comment]
The implementation there's potentially a human-readable diagnostic on the in parameter for CLIENT_CONNECTION_ERROR predates this issue.

While I understand about different error codes being useful sometimes, actually the event that needs telling in every case is that the connection attempt has permanently failed: that's true for all these 36 cases, so it's useful to have one reason cb covering them.  It's also needed for backwards compatibility since we don't have a blank slate, this reason code has been used for these situations for a long time.

Since all the hs-related errors begin "HS:" jif you want to class all hs errors just look for that, if we can simplify classification of other interesting errors by prepending other things or otherwise meddling the strings that would be fine.

If you think it's better done another way that doesn't create backwards-compatibility problems or bloat the code, you're welcome to propose a patch.  But I think this now provides the missing info and solves your problem...

**Comment by lws-team** [comment]
Well, if there's anything more to do about it, please reopen.
