### ISSUE TITLE
Can't close client connection (through lws pointer), needed for proxy-implementation.

### ISSUE THREAD

**Issue by Paul-Ver** [warmcat/libwebsockets#583]
I'm trying to create an WebSocket Server, that acts like a proxy between the incoming WebSocket client and an other connection.
I've got a server listening, and upon connection by a client, it creates an outgoing connection to another server. (I'm planning to add some logic to the C-project, to switch between targets)

Basically I'm testing this:
PythonWSClient <---> C(libwebsockets) project <---> PythonWSServer

The incoming & outgoing connections are linked through session data.

Now, when the incoming connection gets terminated (to our server), I would like to terminate the outgoing (client) connection as well.

For example:
`
case LWS_CALLBACK_CLOSED:

	printf(KYEL"[Main Service] Incoming closed connection.\n"RESET);

	if(pss->client != null)

		lws_close(pss->client,LWS_CLOSE_STATUS_GOINGAWAY,NULL,0);

	break;
`

Though, `lws_close_reason()` or returning not null won't work for closing, since I want to close another connection.

Is it possible to implement this behaviour using your library? Or do you have any other recommendations?

**Comment by Paul-Ver** [comment]
`lws_close_free_wsi()` seems inaccessible to me, though it might be an interesting option.

Version is: v2.0.0-110-g35aa31c

**Comment by lws-team** [comment]
There's no direct, public way to do that atm.

What will work is if you simply return nonzero from the client connection's callback, for something like WRITABLE.  So gratuitously ask for a callback on writable for the client and notice in there he wants to close.

Actually lws has a parent-child concept for wsi that might fit better.  Because there are corner cases to consider like the client connection closed early (invalidating the child wsi) for its own reasons, remote side dropped it, etc.  But this also is private atm (used to bind stdin/out/err wsi to a cgi wsi).

**Comment by lws-team** [comment]
Please try setting struct lws_client_connect_info .parent_wsi to your serving wsi when you create the client wsi.

That should be enough to auto-close the child wsi when the parent one closes, if it still exists.

**Comment by Paul-Ver** [comment]
Thanks for the quick and clear response!

Setting the incoming connections as it's parent did work.
When I close the incoming connection, the outgoing connection will also be closed cleanly.

Though now, if the outgoing connection gets closed (by the other server), I will receive a notice:
`NOTICE: lws_close_free_wsi: detach 0x65d060 from parent 0x65af20`

And I should kick the incoming connection from my serving wsi.
Is there also something built in for this?

**Comment by lws-team** [comment]
Good...

The notice is just some left-over debugging, I'll dilute it so it's not visible by default.

What does "kick the incoming connection" mean to you?  The serving wsi does have a copy of the outgoing wsi, so if it takes care about noticing if it closed, it can do things to it.  But I dunno what you mean by "kick".

**Comment by Paul-Ver** [comment]
"kick" as in close the connection.
In my example:

PythonWSClient <---> C(libwebsockets) project <---> PythonWSServer

With the adjustments you proposed, I can now close the PythonClient and the connection to the PythonServer will also get closed.
However, if I close the PythonServer, the PythonClient will still be connected to my C-project.
I want to disconnect the PythonClient (kick) if I lose connection to the PythonServer.

**Comment by lws-team** [comment]
"Kick" usually means signal a generic event... anyway I understand your meaning now.

I think it makes sense in lws to auto-cull children when the parent is closing, just based on the relationship.  But it doesn't make sense to give a child closing the relationship that it implies closing the parent.  Consider if

 - you extend your proxy to support n onward client connections, or

 - you want to handle problems with that connection by retrying the connection so it's "nailed up", or 

 - you dynamically open and close the onward connection based on inactivity etc.

You can know that the outward client connection has ended because he will receive a CLOSE callback for it.

In there, you may get the parent wsi

```
/**
 * lws_get_parent() - get parent wsi or NULL
 * \param wsi: lws connection
 *
 * Specialized wsi like cgi stdin/out/err are associated to a parent wsi,
 * this allows you to get their parent.
 */
LWS_VISIBLE LWS_EXTERN struct lws * LWS_WARN_UNUSED_RESULT
lws_get_parent(const struct lws *wsi);
```

Of course the client will get a CLOSE callback in the event the parent is closing and he is being culled.  So I think the safe way to deal with it is request on_writable callback to the parent, and notice there that the overall state is the client / child has closed and the parent being called back should then close himself by returning nonzero.

**Comment by Paul-Ver** [comment]
I'm sorry, "to kick a client from the server" (in games) often means disconnecting the client from the server ;). My biggest experience with networking code is with writing game client/servers.

I believe I'll be able to handle it from here, thanks for the quick and elaborate responses.
