### ISSUE TITLE
lws_write() (non/)blocking policy explanation

### ISSUE THREAD

**Issue by eladn** [warmcat/libwebsockets#610]
Can you provide a basic explanation of blocking&scheduling policy, with respect to the following:
1. Does calling `lws_write()` from inside of a protocol callback (on *_WRITABLE case) block the current service thread until the buffer is sent/copied? When does the function return? What is the exact meaning of its return value?
2. Who is responsible to free the sent buffer (to `lws_write()`) and when can it be done?
3. What is the meaning of a `writable` socket? What makes a socket writable? When, for instance, is it not writable?

**Comment by lws-team** [comment]
1.  No.  It returns after one OS write().  The return value will be negative on error otherwise always the amount you asked to write.  In the event not everything could be written, lws will buffer it and take care of draining and deallocating the buffer itself.  But this is only intended for unexpected situations (see 3)

2.  Caller.  Immediately on return.  (So stack buffers are legal).

3. These are questions whose answer is defined by the OS, not me.  If you call poll() on the socket, and POLLOUT revent is set, posix says the OS will accept some amount of data from write() without blocking.  Conversely if POLLOUT is not set, it's a sign from the OS attempting to write() any additional amount on the socket would just block.  Notice you get one bit of information from the OS about this.  It does not tell you how much data will be accepted on the connection, only if anything would be.
