### ISSUE TITLE
Explanation request: multithreading, lws_service() call, events

### ISSUE THREAD

**Issue by eladn** [warmcat/libwebsockets#611]
1. Where in the code of the library is socket fds being polled? (I couldn't find the use of p/poll() *nix syscall in the source code).
2. As for working with multiple threads, how does the polling is distributed between threads?
3. How is the events concept represented in the library? What kind of events are there? When is an event immediately handled and when is it queued? What kind of scheduling policy is applied for pending events?
4. I understand that the call `lws_service()` is responsible for handling pending events. Can you provide a schematic explanation for the responsibilities of `lws_service()` routine?
5. How is the work (of the service routine from 4) distributed between threads via `lws_service_tsi()`?
6. What kind of 'hidden-costs' does `lws_service_*()` have?
7. What are the primary possible return values of `lws_service()`?

Thanks a lot. Elad.

**Comment by lws-team** [comment]
0.  The multithreaded support is kinda experimental.  Afaik it works and has enough locking.  It relies on a Linux-specific feature.

1. Lws supports poll() in lws-plat-unix.  But it also supports event loops like libuv that don't have a poll(), just fires events at us.  So we should better talk about "service" meabing handling poll events or handling externally fired event loop activity.

2. Service for n possible fds for the process is evenly distributed between m threads.  When you init the context with INFO logging enabled it details exactly what it has done.

3. Dunno what you mean by 'event'.  Lws has complex state machines to handle all kinds of multi-step transactions that persist between service events, and even under some conditions synthetic event generation to allow continuation of service when no network event will trigger us to continue, we still have work to do, but we return to the event loop to service other things in the meanwhile.

4. If you use the default poll() event handling, lws_service...() calls poll().  If you use libuv or ev event loops, you don't call it, since the external event loop does that job, and lws returning from the individual handler returns to the event loop.

5.  During context creation, the set of n possible fds was partitioned between the m threads.  In terms of how incoming connections choose which thread / set of fds take the accepted socket, all the threads open listen sockets on the same port, and use a linux-specific attribute that causes the OS to distribute visibility of the incoming connection between the competing threads.

6. ... not sure what you mean, but eg, once a second every socket on the 'waiting for timeout' linked-list gets checked to see if it timed out.

7.  If you use libuv / ev etc you don't even call lws_service.  If you think of it as a wrapper for poll() otherwise, he'll return an error only when poll() would.
