### ISSUE TITLE
v2.0.2 not listed in changelog

### ISSUE THREAD

**Issue by karlp** [warmcat/libwebsockets#613]
It's tagged, it's released, and it's in the ABI compat table, but it's not in the changelog?

**Comment by lws-team** [comment]
You're right, v2.0.2 isn't listed in v2.0.2's changelog, it was an oversight on my part.

However that's been out too long, and this is too minor to reissue the tag.

You can easily see the 13 patches on there since v2.0.1 in git

https://github.com/warmcat/libwebsockets/commits/v2.0.2

So... you are correct, but WONTFIX.

**Comment by karlp** [comment]
It didn't need anything to be retagged, you can still edit the changelog file in the v2.stable branch and it's still useful to be the changelog for v2.0.2 right?  I mean, the front page has a link to "changelog" under v2-stable, and it makes no mention of the most recent stable release.  I'm only asking for the changelog file to mention the release.

**Comment by lws-team** [comment]
Yes for v2.0-stable, it's no problem updating it, and I have done that.  But when you talk about "the changelog" it means the changelog in the v2.0.2 tree to me.  I left that as it is because I don't want to retag that.

**Comment by karlp** [comment]
Ok, sorry, poor choice of wording on my half.  Thanks for updating the changelog file itself, totally agree with not retagging anything.
