### ISSUE TITLE
`user_space` field in `struct lws_context`

### ISSUE THREAD

**Issue by eladn** [warmcat/libwebsockets#618]
1. Is there a certain purpose for the `user_space` field in `struct lws_context`?
Can I assign it for my own needs?
2. In the callback function, when I get the lws `wsi` pointer, can I assume that wsi->protocol points to the same instance of protocol given in the context init? (or it may be copied?)
3. In the callback function, when I get the lws `wsi` pointer, can I assume that wsi->context is assigned and correct?

**Comment by lws-team** [comment]
1) Yes, you can set it at context creation time using info.user.  As it says in the docs for that

https://github.com/warmcat/libwebsockets/blob/master/lib/libwebsockets.h#L1610

you can then recover it from the context pointer with lws_context_user()

https://github.com/warmcat/libwebsockets/blob/master/lib/libwebsockets.h#L1874

As it says in the docs the idea is you can make your struct available throughout your user code without globals.  Lws doesn't know or care what it points to, if anything.

2) If you use plugins, before the first service lws creates a copy of only the enabled protocols for each vhost.  Vhosts have to list which plugins they want to allow, and in addition can set pvo s, 'per-vhost options' that only apply to that vhost on the vhost's instance of the protocol.  The pvos are arbitrary name:value pairs that the user code in the protocol can check to configure itself, per-vhost.

For example the server-status plugin can be configured, per-vhost, via a pvo as to how often it refreshes the status info

https://github.com/warmcat/libwebsockets/blob/master/plugins/protocol_lws_server_status.c#L101

https://libwebsockets.org/server-status/

The per-vhost copy of active plugin protocols, tagged with the vhost's pvo linked-list, is a compatible way of implementing this while keeping const user protocol structs. Protocols in lws match by the name string rather than the pointer where they need to work across vhosts.

3) Yes, where no wsi was available, a fake one with valid .context and if possible .vhost is provided by the caller to make the context consistently available in the user callback, eg

https://github.com/warmcat/libwebsockets/blob/master/lib/context.c#L133
