### ISSUE TITLE
Heap corruption on Windows. lws_plat_inet_ntop calls winapi incorrectly

### ISSUE THREAD

**Issue by cshu** [warmcat/libwebsockets#619]
In lws-plat-win.c, function lws_plat_inet_ntop, the bufferlen passed to `WSAAddressToStringW` is incorrect.

`buffer = lws_malloc(bufferlen);`
should be
`buffer = lws_malloc(bufferlen*2);//WCHAR needs 2 bytes`

Read about WSAAddressToStringW at https://msdn.microsoft.com/en-us/library/windows/desktop/ms741516(v=vs.85).aspx

> The length is represented in bytes for ANSI strings, and in WCHARs for Unicode strings.

**Comment by lws-team** [comment]
I get it, but in every usage case I could see bufferlen is coming from a user parameter outside of the library

 - lws_get_peer_simple(..., int namelen);  ---> lws_plat_inet_ntop(...., cnt) ---> bufferlen = cnt

 - lws_get_addresses(..., int rip_len); ---> lws_plat_inet_ntop(...., cnt) ---> bufferlen = cnt

 - lws_get_peer_addresses(... , int rip_len); ---> lws_plat_inet_ntop(...., cnt) ---> bufferlen = cnt

If the library defines those lengths to be in bytes, then the problem is that the *2 is not there in the code outside the library, right?

**Comment by lws-team** [comment]
Oh never mind... I see it explicitly uses WSAAddressToString**W** in there....

**Comment by lws-team** [comment]
How about this?

```
diff --git a/lib/lws-plat-win.c b/lib/lws-plat-win.c
index cdf37e9..0a37eab 100644
--- a/lib/lws-plat-win.c
+++ b/lib/lws-plat-win.c
@@ -465,7 +465,7 @@ LWS_VISIBLE const char *
 lws_plat_inet_ntop(int af, const void *src, char *dst, int cnt)
 {
        WCHAR *buffer;
-       DWORD bufferlen = cnt;
+       DWORD bufferlen = cnt / 2;
        BOOL ok = FALSE;
 
        buffer = lws_malloc(bufferlen);
```

That way the meaning of the api paramter remains a count of bytes in the buffer regardless of the platform.

**Comment by cshu** [comment]
The value passed to `lws_malloc` must be twice as big as the last parameter passed to `WSAAddressToStringW`.

Because you should pass "size in bytes" of buffer to `lws_malloc` and then pass "size in WCHARs" of the same buffer to `WSAAddressToStringW`.

---

In my case, the value of `cnt` is constant `INET_ADDRSTRLEN`, which is 22.
Suppose for UTF-8 (usually `char *`), 22 is big enough for storing an address.
But for UTF-16 (`WCHAR`), I guess 44 is safe.

**Comment by lws-team** [comment]
OK.  I saw it converts / copies it into the output array afterwards anyway.  So I just push your suggested fix.

Thanks a lot for reporting it.
