### ISSUE TITLE
GPL2.1?

### ISSUE THREAD

**Issue by Alex-Vaduva** [warmcat/libwebsockets#629]
Hi,

I see that /lwsws/main.c it is stated that the license in GPL2.1. This license doesn't exist.
Also the same info ls found in License:
**4) lwsws (Libwebsocket web server) is a bundled application that is not
part of the libwebsockets library, it's a separate application that uses
the library.  The related sources are in a separate directory.  If you don't
distribute lwsws, you do not need to observe its license.

  - lwsws/lejp.c        - LGPL2.1
  - lwsws/lejp.h        - LGPL2.1
  - lwsws/[all else] - GPL2.1**

Can you please clarify this?
Do you mean GPL-2.0 or LGPL-2.1?

Thnak you

**Comment by lws-team** [comment]
Thanks for bringing it up... you're right... it's originally intended to be GPL2.0, and included the config system etc.

But gradually most of lwsws moved into the library itself where it is LGPL2.1 same as the rest of lws.  (That's quite convenient since you can basically have the whole lwsws function inside your app the same way, including the JSON config system, without any big work.)

Now lwsws is just one little file with main() in it that calls lws library functions for pretty much everything else.  It's the same as a test app, showing how to use the lwsws library functions in lws.  The test apps are CC0 to simplify reusing them as the basis of your own app.

I pushed a patch on master that 

1) makes the rump of lwsws CC0, and updates LICENSE accordingly.

2) fixes the GPLlicense text on ./lib/lejp-conf.c to be LGPL-2.1

3) updates LICENSE to match
