### ISSUE TITLE
Extra SERVER_WRITABLE callback on partial send complete

### ISSUE THREAD

**Issue by geekhckr** [warmcat/libwebsockets#630]
Extra "LWS_CALLBACK_SERVER_WRITEABLE" callback is generated on completing partial send (truncated data).  

Find below Logs:
level: 16, msg: fd=8, revents=4
level: 16, msg: lws_calllback_as_writeable: 0x80c1a00 (user=0x80b36f8)
level: 4, msg: 0x80c1a00 new partial sent 4116 from 95980 total
level: 32, msg: written 95980 bytes to client
level: 16, msg: _lws_rx_flow_control: no pending change
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 91864)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 87748)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 83632)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 79516)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 75400)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 71284)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 67168)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 63052)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 58936)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 54820)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 50704)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 46588)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 42472)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 38356)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 34240)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 30124)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 26008)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 21892)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 17776)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 13660)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 9544)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 4116 (vs 5428)
level: 16, msg: fd=8, revents=4
level: 8, msg: 0x80c1a00 partial adv 1312 (vs 1312)
level: 8, msg: ***** 80c1a00 partial send completed
level: 16, msg: fd=8, revents=4
level: 16, msg: lws_calllback_as_writeable: 0x80c1a00 (user=0x80b36f8)

Can we stop the POLLOUT after completing partial send completion, so that we can avoid this callback? 
I can see lot of this kind of callbacks, in my setup.
Is there any other way to avoid this extra callback?

**Comment by lws-team** [comment]
The additional writable callback isn't really the problem here.  Your handler for writable should maintain state about that connection's situation and know what the connection needs sending.  Different connections may be in different states, and you have to generate an appropriate packet at the writable callback anyway.  So it should be able to know nothing to do if nothing to do.

If lws can't send everything you ask at once, he will buffer it and send it later for as you see.  But this is meant to be a backup system for unexpected corner cases, not the normal way of sending big things.  It's expensive to allocate and copy the buffer.

On master anyway this send size restriction is happening before the OS gets it

```
	/* limit sending */
	n = wsi->protocol->rx_buffer_size;
	if (!n)
n = context->pt_serv_buf_size;
```

If you leave the protocol rx_buffer_size at zero, it restricts the send size it tries each time to something you can change in the context creation info struct

```
unsigned int pt_serv_buf_size;
	/**< CONTEXT: 0 = default of 4096.  This buffer is used by
	 * various service related features including file serving, it
	 * defines the max chunk of file that can be sent at once.
	 * At the risk of lws having to buffer failed large sends, it
	 * can be increased to, eg, 128KiB to improve throughput. */
```

Cranking this up at context creation time should reduce or eliminate the need for the buffering behaviour.

**Comment by lws-team** [comment]
If it needs discussing further, please reopen.
