### ISSUE TITLE
TCP Connection Timeout

### ISSUE THREAD

**Issue by Arun19921991** [warmcat/libwebsockets#633]
I am using libwebsocket 1.7 version Library and it works pretty well for me too.I have one query in the tcp connection part of websocket.
I know that the entire websocket handshake connection time out can be set from the user space using **info.timeout_secs**
Is it possible to set the actual **websocket tcp connection** timeout ? 
currently what is it default value?

**Comment by lws-team** [comment]
I think maybe two different kinds of timeout are getting confused here.

When establishing the connection, there are many cases where the next step requires a network roundtrip or at least action from the peer.  In lws, these are protected by a timeout that you can set in the info struct.  You might set it to 5s or 20s, on the basis that if the remote peer didn't do whatever is required by then, it probably never will and drop the connection.

What you seem to be talking about is some kind of idle timeout once the ws connection is made.  lws doesn't have that for ws upgraded connections.  The connection will stay up forever.  You can make your own timeout in the user code (using the lws timeout function), or you can enforce ping / pong checking controlled also from the info struct at context creation time, that will time the connection out if it doesn't PONG back to us in a reasonable period.  Otherwise it will stay up.

In the real word intermediaries may time the connection out, eg routers, according to their own decision, lws can't control that..

**Comment by lws-team** [comment]
If that didn't answer your question, please reopen.
