### ISSUE TITLE
TCP Connection Timeout 

### ISSUE THREAD

**Issue by Arun19921991** [warmcat/libwebsockets#634]
( #633 )Yes i know about the info struct case,But i wanted to know the raw tcp connection timeout before starting the ssl or websocket handshake?

**Comment by lws-team** [comment]
I still don't really understand what you're asking then.

Are we talking about lws as client or lws as server?

As client, initiating the connection, the tcp level connection attempt happens asynchronously.  It's up to the OS how long it will allow, but we will also apply the lws timeout on it, so whichever happens first.

As the server, again it's up to the OS how long it will wait for the tcp hs to complete.  Lws doesn't hear about the tcp connection until the tcp hs has completed, if it never completes we never hear about it.  And again this happens at the OS tcp stack asynchronous to lws.

Is that what you are asking, or something else again?

**Comment by Arun19921991** [comment]
Yes am asking about the same.So the raw tcp connection timeout is the TCP/IP Stack default value,we are not setting that using any api.so will we get any callback to the user space if the tcp connection didnt get due to poor link?

**Comment by lws-team** [comment]
I don't think there is any such userland api per-socket.  When you say "not setting that using any api", what api is it you think we should be using?

At the system level, you can change the whole OS tcp connection timeout down /proc on Linux and who knows how on windows.  That's not lws business to meddle with.

This is outside what posix lets you control using the socket api I think you find.  Which is why your question has been quite confusing.

**Comment by Arun19921991** [comment]
i guess using select(),or setsockopt() we can set a timeout,Anyway we never get the lws callback if didnt get the tcp connection right? or will we get the callback with reason CONNECTION_ERROR_OCCURED ?

**Comment by lws-team** [comment]
> i guess using select(),or setsockopt() we can set a timeout,

Yeah?  Please let me know which option...

https://linux.die.net/man/7/socket
https://linux.die.net/man/7/tcp

> Anyway we never get the lws callback if didnt get the tcp connection right?

As I said if the tcp handshake could not complete, as the server we never hear about the connection at all.  There is no socket representing the connection and no wsi to give an error on.  So nothing lws can do about that, or any other userland tcp server can do about it.

As the client, we initiated the connection so we do have a logical wsi and socket for it.  You should always get a CLIENT_CONNECTION_ERROR callback if that timed out.

**Comment by Arun19921991** [comment]
Okay am running with wsi client.So i will get the callback even if the TCP Connection does not get.Some sample Code
*************

 struct timeval timeout;      
    timeout.tv_sec = 10;
    timeout.tv_usec = 0;

    if (setsockopt (sockfd, SOL_SOCKET, SO_RCVTIMEO, (char *)&timeout,
                sizeof(timeout)) < 0)
        error("setsockopt failed\n");

    if (setsockopt (sockfd, SOL_SOCKET, SO_SNDTIMEO, (char *)&timeout,
                sizeof(timeout)) < 0)
        error("setsockopt failed\n");

**Comment by Arun19921991** [comment]
int status;

    struct timeval  timeout;
    timeout.tv_sec = 10;
    timeout.tv_usec = 0;

    addr.sin_port = htons(port);
    sock = socket (AF_INET,SOCK_STREAM,0);
    inet_pton(AF_INET,serverIP,&addr.sin_addr);

    fd_set set;
    FD_ZERO(&set);
    FD_SET(sock, &set);

    fcntl(sock, F_SETFL, O_NONBLOCK);

    if ( (status = connect(sock, (struct sockaddr*)&addr, sizeof(addr))) == -1)
    {
        if ( errno != EINPROGRESS )
            return status;

    }
    status = select(sock+1, NULL, &set, NULL, &timeout);

    return status;

**Comment by lws-team** [comment]
Supposedly -->

http://stackoverflow.com/questions/13556972/how-is-it-possible-to-have-send-timeout-on-a-non-blocking-socket

that doesn't work on noblocking sockets.  But the guy could be wrong.

If you want to test it in lws directly, you can just add the setsockopt to the other ones in ./lib/lws-plat-unix.c at lws_plat_set_socket_options().  That gets called before the connect() attempt when making the client connection.... so you should be able to see what happens cheaply from inside lws.

**Comment by Arun19921991** [comment]
Okay. i have gone through that parts also but did not added any code,Do we use LIBEV or LIBUV ? after connect we are registering the handlers for libev callback write?

**Comment by Arun19921991** [comment]
There we can call a timer callback for handling the tcp connect event to get and handle this issue,and inform to the user space to inform that the TCP Connection failed.

**Comment by lws-team** [comment]
Hm what exactly is the problem for you today?  As it is, for client, you should **always** get some error from lws about timeout or client connection error, or close.

You shouldn't need any of this because the lws connection timeout will show us something fatal happened if nothing else does.

What exactly is happening that makes the problem as it is?

**Comment by Arun19921991** [comment]
Ya i should get..But i just wanted to know that the lws client is setting any kind of timeout in the tcp level.
Suggestion
***********
Using libev we can register for a call back timer which handles the tcp connection timeout.

**Comment by Arun19921991** [comment]
From this discussion i understood that the lws timeout will handle the entire thing safely.

**Comment by lws-team** [comment]
There is no use or need for another timer to "handle tcp connection timeout".

If whatever is supposed to happen doesn't happen before the lws timeout is up, lws will close the logical connection and the socket connection, and do the right callbacks.  If it does happen, it will cancel the lws timeout and go on OK.

So there is nothing missing here, plus or minus possible gaps / bugs in the implementation.  Which is why I was asking what is the actual problem that has put this topic in play   If there is a specific problem that doesn't call back right or even doesn't time out (doubt it) then we should talk about reproducing / fixing that.

**Comment by lws-team** [comment]
I guess there is no problem here, at least, no actual problem got reported, and it's a misunderstanding.  Lws timeouts should already cover every case userland can know about cleanly.  If there's an actual problem, always interested to hear how to reproduce and / or find and fix it.
