### ISSUE TITLE
formdata parsing doesn't work, if the file ends with a odd number of <CR><LF>

### ISSUE THREAD

**Issue by neo9903** [warmcat/libwebsockets#641]
If a file is uploaded which ends with <CR><LF> oder <CR><LF><CR><LF><CR><LF>, ... the the parser doesn't call with "LWS_UFS_FINAL_CONTENT" at the end. A even number of  <CR><LF> works fine.

The following 4 test-files can reproduce the bug at https://libwebsockets.org/testserver . The _fail files show (null) at upload.

[test2_ok.txt](https://github.com/warmcat/libwebsockets/files/505779/test2_ok.txt)
[test3_fail.txt](https://github.com/warmcat/libwebsockets/files/505780/test3_fail.txt)
[test4_ok.txt](https://github.com/warmcat/libwebsockets/files/505778/test4_ok.txt)
[test1_fail.txt](https://github.com/warmcat/libwebsockets/files/505777/test1_fail.txt)

**Comment by lws-team** [comment]
Thanks, a nice find.  I can reproduce it with your files.

It's related to the parsing action somehow but not sure why that ends up with this particular, narrow symptom.

I'll study it tomorrow.

**Comment by lws-team** [comment]
What's going on is the parser misses the terminating boundary line (like ------WebkitFormBoundaryxxx) in the failing case.  It then treats that missed boundary and the remaining content as part of the file until the next boundary line, where it recovers as if nothing bad happened).

The problem was the boundary begins with CRLF, if it then didn't continue with - it gave up on it being a boundary and simply emitted the matched boundary until then and the new char.  The patch I just pushed makes it emit the matched boundary but then retry the new character as a new start of a boundary.... that fixes it here.

**Comment by neo9903** [comment]
Thank you for the fast bugfix. It seems to work now.

**Comment by lws-team** [comment]
Great.
