### ISSUE TITLE
Question about whether lws_write() will send out duplicated messages in a short period of time?

### ISSUE THREAD

**Issue by feishengfei** [warmcat/libwebsockets#647]
Dear warmcat,

Although not locally reproduced yet, our customer(coding on server side) report that they will occasionally receive 1000+ packets of duplicated contents while the client(build on  v1.6.0-chrome48-firefox42 release of libwebsockets) with 5 minutes. The normal period of the receive of the message should be 50 seconds. Generally speaking, wss based on SSL/TCP is connection oriented, and I believe that lws_write() will guarantee that we could send out message completely or failed for network or other reason. 

I try to reproduce this BUG on my MIPS cross-compiled client. It seems that nothing abnormal at all by tcpdump messages. Based on the reality the conversation is by SSL and I can only judge by the content length. I could capture re-transmission packets but I haven't reproduce the burst of messages at all.

BTW, this issue is reported that only ten out of thousands of devices can burst out messages during a short period of time.

I just wonder whether similar issues happened before, if not, please close this issue. Or could you tell me which release could fix it. Any way, your project & team do us a great fever in the pasted few years and it proved to be a great mid ware.

**Comment by feishengfei** [comment]
BTW, I'm still watching on closed issue and changelog / git patches. Hope any clue can be figured out.

**Comment by lws-team** [comment]
There's no such problem with lws I think you find.

The user code alone is responsible for sending user content.

I suggest you look closely at your code in the WRITABLE callback for your protocol.

Another possibility is the bug is at the receiver; you should find out if the bug is happening via a huge spam of network traffic or just the same buffer repeatedly handled..  It seems you had the same idea but you can't reproduce it yourself, and I don't even have you code, so pointless asking me.

As I say no way to trigger such a thing in lws now or at any time in its 6 years it has been going as far as I know.

**Comment by feishengfei** [comment]
Your confirm helps me a lot and thanks.
I think I should debug this issue from server side instead.
