### ISSUE TITLE
Why is SO_REUSEADDR disabled for Windows?

### ISSUE THREAD

**Issue by MacGritsch** [warmcat/libwebsockets#65]
Hi,

also under Windows SO_REUSEADDR is needed, otherwise you can not bind if you are restarting a crashed service.

http://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t

	2341c2341
	< #ifndef WIN32
	---
	> //#ifndef WIN32 //needed for windows too
	2351c2351
	< #endif
	---
	> //#endif
![filemerge](https://f.cloud.github.com/assets/364551/2237385/f04f3c80-9ba5-11e3-96a1-71e808746604.png)

**Comment by camkego** [comment]
Hi, been researching this intently, for another reason.
I understand REUSE is popular under *nix because it prevents re-binding process restart errors for processes stuck in TIME_WAIT.
Supposedly Windows does not have this issue of preventing socket binding for socket addr/port combinations in TIME_WAIT.
Apparently there is little value to using REUSE under Windows except in cases where you are using multicast.

**Comment by warmcat** [comment]
Well if it makes trouble and is happy without it, provide a patch to disable ifdef WIN32... all the windows stuff is contributed.  The thing is if another windows guy says that patch makes trouble I can't judge it since I don't use it.
