### ISSUE TITLE
Receiving HS: ACCEPT missing often

### ISSUE THREAD

**Issue by sjames1958gm** [warmcat/libwebsockets#659]
Using the test client as a guide (building client code into my app) I am trying to connect to 
wss://stream.watsonplatform.net/speech-to-text/api/v1/recognize
For most attempts I am receiving error HS: ACCEPT missing
Sometimes I get a completed connection.
Any clues as to why?
https://github.com/sjames1958gm/test/blob/master/sj.pcap
I added a pcap file from attempt to connect.

**Comment by lws-team** [comment]
The pcap was a good idea, but the connection is ssl encrypted, so I can't tell anything useful from it.

The error is telling you that no Accept HTTP header came back in the response.

Crank up the logging on the lws side:

 - cmake .. -DCMAKE_BUILD_TYPE=DEBUG
 - if your app still has the switches from the test app template, do -d65535 otherwise in the code something likie lws_set_log_level(65535, lwsl_emit_syslog);

That will dump every character of the headers, get a run where it says Accept is missing and paste / upload the log here.

**Comment by sjames1958gm** [comment]
https://github.com/sjames1958gm/test/blob/master/capture.txt
Here is a capture with that logging turned on.

**Comment by lws-team** [comment]
The remote server is telling you "400 Internal Server Error", and is indeed not giving you the Accept.

**Comment by sjames1958gm** [comment]
Can you tell, or can I get to any content for these rejections? Seems there might be some error text in the content that might help me.

**Comment by lws-team** [comment]
Another header it sent back says

`X-Backside-Transport: FAIL FAIL`

At the moment lws just considers the connection failed and discards any http body.

I would guess this is a problem that is wholly on the server side, due to balancing or capacity problems.  How about just auto-retry to make the wss connection again when you see this?

**Comment by sjames1958gm** [comment]
Looks like that is the best strategy - thanks for your help
