### ISSUE TITLE
multithread

### ISSUE THREAD

**Issue by rollen1960** [warmcat/libwebsockets#665]
I read the #566 . 
It's right that i can have two (or more) threads that create two unrelated context (lws_create_context) and have two unrelated loop (lws_service) ?
Where can I say which is the right context for process the lws_callback_function ? info.user ?

Thank you.

**Comment by lws-team** [comment]
You can have multiple contexts, but almost every time (possibly, actually, every time) that's not the right answer.

There is no such concept as "which is the 'right' context" for a connection.

Ultimately communication is happening at the socket level, a socket fd in the process is belonging to one thread or another by happenstance already.

What are you actually trying to achieve with the multiple context thing?

**Comment by rollen1960** [comment]
I write a server that has a group of clients in plain socket, another group in HTTP, another in HTTPS, another in WS, another in WSS. Each of these group can receive data in JASON format or in FIX format.
For example:
on port 80 I receive WS and respond in JSON
on port 81 I receive WS and respond in FIX
...
so I make one thread for each group, with a context and a service.

It work  ?  Must I do actention or is perfectly legaly in your library ?

**Comment by lws-team** [comment]
Lws holds the state of all its connections including what they upgraded away from http[s] or not.

But it always expects them to start off with http[s].  The client may or may not upgrade to ws, otherwise it will be dealt with as http.  In the end it's called 'libwebsockets' not librandomwhatever.

If you really want raw socket support, you can write your own networking code (because that is what you are saying) and lws can join its poll() loop using external poll support.  Then you split it into raw socket support that is your problem and http[s] / ws[s] that lws can cope with.

**Comment by rollen1960** [comment]
All right. But:
I have a class with a context (lws_create_context) and a method (lws_service)
The question: can my program have two or more thread that make a instance of such class ?

Thank you

**Comment by lws-team** [comment]
Who knows.  lws is a C library,

OpenSSL, a dependency of lws, can't even keep two instantiations straight in one process.

BTW my faith in C++ lapsed 16 years ago... might be just me of course.

**Comment by rollen1960** [comment]
thank you
Mario
