### ISSUE TITLE
lwsws server: Problem on upload image

### ISSUE THREAD

**Issue by tejendrasingh** [warmcat/libwebsockets#668]
Sir
i run lwsws server, after that i was trying to post image using XMLHttpRequest. but server is not receving
server side console--
lwsws[10315]: lws_spa_create: Created SPA 0x21a7540
lwsws[10315]: lws_server_socket_service: wsi 0x21a6270 read 4096
lwsws[10315]: lws_server_socket_service: wsi 0x21a6270 read 4096
lwsws[10315]: lws_server_socket_service: wsi 0x21a6270 read 4096
lwsws[10315]: lws_server_socket_service: wsi 0x21a6270 read 4096
lwsws[10315]: lws_server_socket_service: wsi 0x21a6270 read 2664

on server console when i use application/x-www-form-urlencoded in header instead of multipart/form-data 
lwsws[9175]: lws_spa_create: Created SPA 0x1a22e60
lwsws[9175]: Name too long

and when i am post with html form tag. server is successfully uploaded. and on server console
lwsws[10315]: lws_server_socket_service: wsi 0x21a6270 read 4096
lwsws[10315]: file_upload_cb: write 1023 says 1023
lwsws[10315]: file_upload_cb: write 1023 says 1023
lwsws[10315]: file_upload_cb: write 1023 says 1023
lwsws[10315]: file_upload_cb: write 1023 says 1023
lwsws[10315]: lws_server_socket_service: wsi 0x21a6270 read 4096
lwsws[10315]: file_upload_cb: write 1023 says 1023

**Comment by lws-team** [comment]
You can only 'upload' files in http with multipart/form-data AFAIK.  The post demo provided in lws (and on https://libwebsockets.org/testserver ) can upload files that way from any browser.

Your question seems to be about formatting the payload of XMLHttpRequest so it looks like multipart/form-data properly, not lws.  I am not entirely sure because you just dump out your status and don't actually ask any question.

Are you preparing the payload properly like this?

https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects
