### ISSUE TITLE
LWS_WRITE_HTTP

### ISSUE THREAD

**Issue by rollen1960** [warmcat/libwebsockets#689]
It's possible that a HTTP respons (lws_write(...   LWS_WRITE_HTTP*) send the header HTTP (for example "HTTP/1.1 200 Push Service\r\n\r\nOK\r\n") before may data ?

It's possible that, after a lws_write(... LWS_WRITE_HTTP*) , the socket remain open and I continue to send other data and after more time close  I the socket ?

Thank you

**Comment by lws-team** [comment]
I don't really understand what you are asking me in terms of it being an "lws issue".

If your code calls lws_write with disordered things, or you are doing things from multiple threads, you can get disordered things.  Otherwise no.

If you think lws is malfunctioning and disordering things, please debug it to find some evidence and show me how to reproduce it with the test apps, I will certainly look at it and if it should be solved I will work to solve it.  Only you can debug it since only you have the problem.

But not to put too fine a point on it, I am not a free debugging service for user applications.

**Comment by rollen1960** [comment]
Ok. Thank you
