### ISSUE TITLE
Partial write

### ISSUE THREAD

**Issue by annaseufert** [warmcat/libwebsockets#692]
I set up a websocket client that sends messages. Depending on the message size it should split the payload into several chunks. 

I based the implementation on the test-echo.c file. There I was a bit confused about whether the content of LWS_CALLBACK_CLIENT_WRITEABLE or LWS_CALLBACK_SERVER_WRITEABLE (do_tx) would be called in that case.
At the moment I use the content of LWS_CALLBACK_CLIENT_WRITEABLE, but that only works for small messages that do not need to be split. 

Or should I take a closer look at test-fraggle.c for that topic.

At the moment I am pretty confused and would really appreciate some help!

**Comment by lws-team** [comment]
1) if it's being a client, then the CLIENT callbacks apply, surprisingly enough.  It's like that so one protocol handler can be both client and server.

2) just like tcp may split a datagram into many packets at any intermediate router, ws can split a single logical ws message into logical ws fragments.  When it receives a fragment with the FIN bit set, it understands it will have received a complete message when it receives all of that fragment.  Until then, ws will let you send as many non-FINal fragments as you want - infinite sized messages are supported in ws, somewhat uselessly.

3) lws_write() sends TEXT or BINARY ws data in a single ws fragment every time.

4) By default, those fragments have FIN set.  So one send is one ws fragment and that's one ws message each time.

5) You can selectively suppress the FIN bit using the lws_write flag LWS_WRITE_NO_FIN.  Then you are sending a fragment each time, but one that does not finish the message.

6) To send messages of arbitrary length then, you apply LWS_WRITE_NO_FIN to every call to lws_write() except the last one of the message.

**Comment by lws-team** [comment]
7) The first fragment of a message must go out with either LWS_WRITE_TEXT or ..._BINARY.  Subsequent fragments must use LWS_WRITE_CONTINUATION.  The LWS_WRITE_NO_FIN flag can be or-ed on to any of those as needed.

**Comment by lws-team** [comment]
Well, there seems nothing for me to do here.

**Comment by annaseufert** [comment]
I have to split the message myself? I tried to do so, but still my applications crashes...

What is the max. Payload Size I could send via Libwebsockets? If I wouldn't NEED TO split the messages, that would be a solution aswell ;)

In case I have to split: Maybe you have an idea what I should change:

This is my per_session struct:

    #define MAX_PAYLOAD 1024
    struct per_session_data
    {
        // standard stuff
        size_t rx, tx;
        unsigned char buf[LWS_PRE + MAX_PAYLOAD];
        unsigned int len;
        unsigned int index;
        int final;
        int continuation;
        int binary;
        // custom stuff
        websocket_data *message_data;
    };

This is the "responsible" callback:

    case LWS_CALLBACK_CLIENT_WRITEABLE:
            lwsl_notice("Client writable\n");

            // Get message from message data object
            message_tx = session_data->message_data->get_message_tx();

            // Check if message (or rest of message) needs to be split
            if(std::strlen(message_tx) > 1024) {
                session_data->final = 0;
            } else {
                session_data->final = 1;
            }

            // Find write mode
            n = LWS_WRITE_CONTINUATION;
            if(!session_data->continuation)
            {
                if(session_data->binary) {
                    std::cout << "binary" << std::endl;
                    n = LWS_WRITE_BINARY;
                }
                else {
                    std::cout << "text" << std::endl;
                    n = LWS_WRITE_TEXT;
                }
                session_data->continuation = 1;
            }
            if(!session_data->final) {
                std::cout << "non final" << std::endl;
                n |= LWS_WRITE_NO_FIN;
            }

            // Copy (first part of) the message
            session_data->len = snprintf((char *)&session_data->buf[LWS_PRE], 1024,
                                         message_tx);

            lwsl_notice("+++ test-echo: writing %d, with final %d\n", session_data->len, session_data->final);

            // Delete first part of the message
            if(std::strlen(message_tx) > 1024) message_tx = message_tx + 1024;


            session_data->tx += session_data->len;
            n = lws_write(wsi, &session_data->buf[LWS_PRE], session_data->len, static_cast<lws_write_protocol>(n));
            if (n < 0) {
                lwsl_err("ERROR %d writing to socket, hanging up\n", n);
                return 1;
            }
            if (n < (int)session_data->len) {
                lwsl_err("Partial write\n");
                return -1;
            }

            session_data->len = -1;
            if (session_data->final)
                session_data->continuation = 0;
            
            lws_rx_flow_control(wsi, 1);

            if (!session_data->final) {
                lws_callback_on_writable(wsi);
            }

            break;


This is the output:

    [2016/11/28 15:40:18:0417] NOTICE: Client writable
    text
    non final
    [2016/11/28 15:40:18:0421] NOTICE: session data -1
    [2016/11/28 15:40:18:0422] NOTICE: +++ test-echo: writing -1, with final 0
    [2016/11/28 15:40:18:0423] NOTICE: +++ test-echo: writing 64
    Segmentation fault (core dumped)

**Comment by lws-team** [comment]
I dunno, your code seems broken.

Your code being broken is not in itself an "issue in lws", and not my problem.

At a minimum if you get a segfault, your first thought should be to reach for gdb (NOT github!) so you can get a backtrace and get an idea of where and why that happened.  If the test apps + lws segfault, send me a backtrace I will be happy to study it.  If your code + lws segfault, by all means make the case that's a problem in lws if that's what it suggests, if so I will assess it and fix it if needed.

Otherwise I can waste my whole life away uselessly fixing each person's broken code.  I respectfully decline.

**Comment by annaseufert** [comment]
Okay, that's legit. But maybe you could answer the two open questions?

I have to split the message myself? There is no built-in functionality that takes care?

What is the max. Payload Size I could send via Libwebsockets? If I wouldn't NEED TO split the messages, that would be a solution aswell.

**Comment by lws-team** [comment]
Well if your code is segfaulting, you must debug it, usually with gdb.  That is unrelated to your two questions, but it seems the most pressing issue.

Your first question is answered by the detailed explanation I gave before.  Yes, the only primitive at your disposal is to send a ws fragment.

Lws works by sending stuff when the kernel can accept some more on that connection.  We get a notification that 'we can send more', that is not accompanied by any information about how much more.  It's only when we try to send() your fragment the OS will let us know how much it accepted.  To manage this, lws will transparently buffer any remainder and subsequently finish sending it silently before letting the user code see any more notifications the connection is writable.

So for the second question there is no fixed limit on fragment size[1], but if the OS doesn't accept everything immediately you get the overhead of lws transparently malloc-ing the buffer and copying the unsent data into it.  (Notice this means this is not the cause of your problems, since it is handled transparently).  The larger the fragment size you asked to send, the less likely it's all accepted at once, and the more overhead buffering it.  Therefore it's best to relate the fragment size to the MTU (eg, 1450 bytes typ for ethernet), which on Linux usually is wholly accepted.

[1] actually the struct lws_protocols .rx_buffer_size restricts how much can be sent at once.  So you should make sure this reflects the size of what you hope to send at one time (if left at 0, it defaults to 4KB)
