### ISSUE TITLE
Ability to read X-Forwarded-For header

### ISSUE THREAD

**Issue by pvub** [warmcat/libwebsockets#702]
Hi,

Not an issue, but more a question on which headers are supported.

I have my server sitting behind a proxy, and I want to read the 'X-Forwarded-For' header passed on by the proxy. I checked the token enum definition, and didn't find a corresponding header enum for this. Is this header not supported by the lib?

I noticed X_REAL_IP enum value instead. Not sure if this is what I need to use.

Also is there a way to read custom http headers without changing the token indices enum?

Thanks in advance for your time.

**Comment by lws-team** [comment]
The token enum reflects a set of http/1 token strings listed here

https://github.com/warmcat/libwebsockets/blob/master/lib/lextable-strings.h

a helper app in minilex.c can recook those strings into a very efficient lexical parser, which lives in

https://github.com/warmcat/libwebsockets/blob/master/lib/lextable.h

So although you must keep the enum list in sync with the strings, it's not really the point... the lexical parser is the point.  Unless it's recooked with the new string, lws can't identify it as a header.

I added a patch on master (currently at https://github.com/warmcat/libwebsockets/commit/64ee08a895208d65e5869a9f413da67c09fa3ac8 ) to add it.  But because it affects the other non-string enums, it can't really be backported.

**Comment by pvub** [comment]
@lws-team Andy, thank you for the quick response. Very well explained. I'll pick up this change.
