### ISSUE TITLE
Breaking change to struct layout

### ISSUE THREAD

**Issue by alanconway** [warmcat/libwebsockets#703]
basic_auth_login_file was added in the middle of struct lws_mount in commit 123b449705d.
This breaks existing code that initializes a mount using a struct initializer, as shown in the test-server examples. Adding the member at the end would work with JSON config and would not break existing code.

**Comment by lws-team** [comment]
Yes, you're right, thanks... I left off the ABI reminder comment at the bottom and placed it for best struct packing rather than compatibility.  (Ordering the members by size makes a surprising difference in struct size and is the default way it's done in the private header).

I added the ABI comment, moved the member to the end and added a couple of buffer void *, this trick lets unchanged user code still work if there are only additions with 0 default, which is almost always the case.

Notice I continuously rewrite history on master if the patches are recent.  That is why there are very few fix patches on active development, they are fixed in the original patch.  If you're following master, you should use like

`git fetch https://github.com/warmcat/libwebsockets +master:m`

This will force-update your local branch "m" to be current remote master, without affecting any currently checked out branch.  Then you can add or rebase your patches on top.
