### ISSUE TITLE
Strange global variable in context.c

### ISSUE THREAD

**Issue by AdrianEddy** [warmcat/libwebsockets#708]
Hello,
I was looking through the sources and stumbled upon this strange global wsi in context.c:559:
https://github.com/warmcat/libwebsockets/blob/master/lib/context.c#L559

The only code accesing this variable is https://github.com/warmcat/libwebsockets/blob/master/lib/context.c#L707-L708
which also seems pointless because the result is never used anywhere.

Is this a mistake or am I missing something?

**Comment by lws-team** [comment]
Yes it's just cruft... as some point between v2.0 and v2.1 the line migrated out of the context_init function and into the wilderness accidentally... it kept the indent but otherwise didn't make any error.  (I have a nice mouse, but sometimes it powers up with strange ideas about the meaning of touches on its "touchpad" type surface mean... it looks like while scrolling around this picked the line up and deposited it randomly...)

Also after v2.0 the code using it was (this time, deliberately) moved into its own function.  So the whole strange declaration and the usage are just pure cruft.

I pushed a patch on v2.1-stable and master cleaning it up, thanks for pointing it out.
