### ISSUE TITLE
apache user

### ISSUE THREAD

**Issue by HiAlisaYang** [warmcat/libwebsockets#714]
I am running the demo lwsws  on suse with  `-DLWS_WITH_LWSWS=1 -DLWS_WITH_GENERIC_SESSIONS=1`. 
      I run: chown root:apache /var/www/sessions to prepare the db directory. It failed with the error chown: invalid group: `root:apache'.
      Is it means I need install a tomcat?I have no idea about it. Thank you in advance.

**Comment by lws-team** [comment]
No.

Actually although this isn't really a SuSE thing, I can tell you about SuSE and lwsws because https://libwebsockets.org is running on aarch64 SuSE on an RPi3 since the last few weeks.  So there are no big problems.

There is no fixed requirement about the user lwsws runs under; it doesn't have a special meaning.  I wrote to use "apache" because that is a common user and group that is already on Linux boxes.

What I did on SuSE was add my own user and group "lwsws" instead, using eg

```
# groupadd -r -g 48 lwsws
# useradd -r -g 48-u 48 -M lwsws
```

Then set lwsws to run under uid/gid 48 in /etc/lwsws/conf

```
   "uid": "48",
   "gid": "48",
```

and you will want to chown directories like the database one for lwsgs, to "lwsws:lwsws" then, since these are the credentials that lwsws is running under.

**Comment by HiAlisaYang** [comment]
I got it. Thank you very much.
