### ISSUE TITLE
about LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK

### ISSUE THREAD

**Issue by kjnoh77** [warmcat/libwebsockets#715]
Dear lws-team,

Some our client prepare to use v2.0.3.
Their ssl connection is not working diffrent with 1.7.9.
I solved this problem blocking next code only for test purpose.
lws_ssl_client_bio_create(struct lws *wsi)
{
        #if 0//defined LWS_HAVE_X509_VERIFY_PARAM_set1_host
	param = SSL_get0_param(wsi->ssl);
	/* Enable automatic hostname checks */
	X509_VERIFY_PARAM_set_hostflags(param,
					X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS);
	X509_VERIFY_PARAM_set1_host(param, hostname, 0);
	/* Configure a non-zero callback if desired */
	SSL_set_verify(wsi->ssl, SSL_VERIFY_PEER, 0);
      #endif
}

Yes, Our client is to connect server which has diffrent host name its cert file shows.
I found that v2.1 is fixed as like next providing user option.
#if defined LWS_HAVE_X509_VERIFY_PARAM_set1_host
	X509_VERIFY_PARAM *param;
	(void)param;

	if (!(wsi->use_ssl & LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK)) {
		param = SSL_get0_param(wsi->ssl);
		/* Enable automatic hostname checks */
		X509_VERIFY_PARAM_set_hostflags(param,
						X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS);
		X509_VERIFY_PARAM_set1_host(param, hostname, 0);
		/* Configure a non-zero callback if desired */
		SSL_set_verify(wsi->ssl, SSL_VERIFY_PEER, 0);
	}
#endif

Could you also apply option for v2.0.3?
I know "LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK" is not defined in v2.0.3.
So, if you can fix as like that it check with type of number (1 << 2), our client also can setting as like next to skip host name check.
connect_info.ssl_connection = (1 << 2);

Thank you.

**Comment by lws-team** [comment]
Hum this is a bit difficult to decide what to do.

I have chopped out the API changes from 675c349cc592b0d84df02382fac5617293a2965a and pushed it on v2.0-stable.

That means there is no way to turn off the strict checking on v2.0-stable after this patch.  Basically this patch enforces hostname checking; the v2.1 patch enforces it by default but you can turn it off.

But I think rather than change v2.0 api, it's OK to say if you want to turn it off, use v2.0-stable before this patch, revert this patch, or use v2.1+.  

Can you check it and see if it is enough?

**Comment by kjnoh77** [comment]
OK,
I will find diffrent way as you said.
Thank you!
