### ISSUE TITLE
memory check

### ISSUE THREAD

**Issue by kjnoh77** [warmcat/libwebsockets#719]
Dear lws-team,

When I checked PSS with memps, it always shows increase of memory which server sent to client with most large size.
For example, If we sent datas to client which has next size with lws_write()
3MB, 2MB, 7MB, 1MB....
after all sent finished, PSS is increased 7MB comparing with basic PSS use.
It's not continously increase, but just size we ever sent most big.
It may not due to by user code, because we don't use static buffer but use instant new alloc memory for every sent, so if user code has some problem(not free) it must be increased continuously.
This is known and no problem? Or could you check this p​henomenon with your server?
Now, I study inside of lws_write() reviewing our user code repeatedly.

Thank you.

**Comment by lws-team** [comment]
Mmm it's intended, but it's because you're not using lws_write efficiently for memory.

lws_write wants to just give your data to write() of the OS.  If the OS accepts it, then we finish.

But in a real system, the OS will only accept a certain amount to write on the socket.  We get told that the connection will accept "something" by POLLOUT on the fd.  But there is no way to know what that amount is, except do the write.  lws takes care about buffering the remaining data and sending it afterwards automatically.  It keeps the largest buffer it ever had to use on the connection, because it expects you will send more like that.

This buffering is only meant for emergencies, where the OS only accepted an unreasonable amount like 1 byte (there is no formal lower limit).  lws will cover for it and there is no problem.

If you have large ws messages to send, you should break them up into smaller fragments.  I wrote about it recently on another question:

1) just like tcp may split a datagram into many packets at any intermediate router, ws can split a single logical ws message into logical ws fragments. When it receives a fragment with the FIN bit set, it understands it will have received a complete message when it receives all of that fragment. Until then, ws will let you send as many non-FINal fragments as you want - infinite sized messages are supported in ws, somewhat uselessly.

2) lws_write() sends TEXT or BINARY ws data in a single ws fragment every time.

3) By default, those fragments have FIN set. So one send is one ws fragment and that's one ws message each time.

4) You can selectively suppress the FIN bit using the lws_write flag LWS_WRITE_NO_FIN. Then you are sending a fragment each time, but one that does not finish the message.

5) To send messages of arbitrary length then, you apply LWS_WRITE_NO_FIN to every call to lws_write() except the last one of the message.

6) The first fragment of a message must go out with either LWS_WRITE_TEXT or ..._BINARY. Subsequent fragments must use LWS_WRITE_CONTINUATION. The LWS_WRITE_NO_FIN flag can be or-ed on to any of those as needed.

7) Inbetween sending each fragment, ask and wait for another WRITABLE callback

You can tune the fragment size as convenient, either small enough it's almost always all accepted, or trade off it being buffered sometimes for better throughput.

**Comment by kjnoh77** [comment]
OK,
I understood what you said.
And will fix our user code referring source of test server.
Thank you!
