### ISSUE TITLE
Creating a libwebsockets client for Windows? Source example/project available?

### ISSUE THREAD

**Issue by skycipher** [warmcat/libwebsockets#727]
It seems there are countless server examples but the handful of client examples are always incomplete for a Windows implementation. Swapping headers is no problem and insuring that calloc pointers are cast to the proper type of pointer for building in a stricter environment is tedious, but finding out that some files must be generated or others required files just missing from the example is frustrating. 
Is there a clean build and headers for including libwebsocket in a Windows Visual Studio 15 C/C++ project?

**Comment by lws-team** [comment]
lws provides one example for client

https://github.com/warmcat/libwebsockets/blob/master/test-server/test-client.c

Personally, I have not used windows since 2002... all of the support on lws for windows is contributed.

However...

 - lws uses cmake, which works equally well for windows

 - lws gets CI via appveyor, which builds it under windows.

So I keep it building OK on windows.

I can tell you something else that's "frustrating"... getting an issue that handwaves about "some files must be generated" or "other required files just missing"... what exactly are you talking about?  Which files are like that with lws test-client.c sample?

**Comment by skycipher** [comment]
Think of your "in" files. Catch 22. You need a successful build on Linux before the .h counterparts are generated. 
I have written hundreds of projects , most of which cross platform and never had to battle a build like this one. It is sad when you have to google for manifest constants because it is only defined in the middle of a file used for a write feature. 
Your client code assumes a Linux client and uses features in code and includes  unique to Linux. You know that you can abstract in C too and do code isolation. Add the unsafe use of types forcing a developer who must develop using secure coding practices to cast away the day or add yet one more special header to those scattered around the Internet. I dislike #ifdefs as most do but by pushing platform specific functions down to the C file while keeping the function signatures in the header makes the project easier to build an maintain.
Then add the use of non standard or deprecated Linux/Posix naming close vs _close and deprecated and  unsafe string, copy and memory functions. strcpy  for example among dozens of others. Your code is at least 10 years behind what would be acceptable to my big Linux clients. 
Thank you for the pointer to the client code. 
It doesn't matter if you don't support Windows, but most of us who design and deliver code for billions of customers, yes, billions of paying customers, would like to see some attempt at good programming practice, even for freeware.







Best,
Tomas Palmer

**Comment by lws-team** [comment]
Yeah.

Well, you have "issues" alright, but they are not related to any code, and I'm afraid nobody can help you with those.

So, closing.
