### ISSUE TITLE
The ping-pong does not take effect

### ISSUE THREAD

**Issue by HiAlisaYang** [warmcat/libwebsockets#729]
I set `info.ws_ping_pong_interval = 5;` and `info.timeout_secs = 5;`.But I recive the callback reason LWS_CALLBACK_RECEIVE_PONG per 50 seconds.And I can not capture the ping-pong packets with WireShark.How is that?

**Comment by lws-team** [comment]
Is the connection idle?

If there is any traffic on the connection, there is no need to send the ping / pong since clearly the connection is working.

So it would send them in your case after the connection has been idle for 5s.

What version of lws is this?

**Comment by HiAlisaYang** [comment]
The connection is idle without sending massages.

My version is a master branch at Dec 12th.

Thanks a lot.

**Comment by lws-team** [comment]
There was already a way to test this in test-client (-P secs), I pushed a small patch on master to also add -P secs to the test server.

Run the test server like this

```
 $ libwebsockets-test-server -P 5 -d31
```

Then open your browser on `http://localhost:7681`

You'll see a lot of junk about the dumb increment fly by, but every 5s you will see this:

```
lwsts[17943]: requesting ping-pong on wsi 0x1af1c10
lwsts[17943]: lws_set_timeout: 0x1af1c10: 5 secs
lwsts[17943]: requesting ping-pong on wsi 0x1aae1a0
lwsts[17943]: lws_set_timeout: 0x1aae1a0: 5 secs
lwsts[17943]: fd=11, revents=4
lwsts[17943]: issuing ping on wsi 0x1af1c10
lwsts[17943]: lws_set_timeout: 0x1af1c10: 5 secs
lwsts[17943]: fd=10, revents=4
lwsts[17943]: issuing ping on wsi 0x1aae1a0
lwsts[17943]: lws_set_timeout: 0x1aae1a0: 5 secs
lwsts[17943]: fd=11, revents=4
lwsts[17943]: lws_calllback_as_writeable: 0x1af1c10 (user=0x1aaea30)
lwsts[17943]: _lws_rx_flow_control: no pending change
lwsts[17943]: fd=10, revents=4
lwsts[17943]: lws_calllback_as_writeable: 0x1aae1a0 (user=0x1aae510)
lwsts[17943]: _lws_rx_flow_control: no pending change
lwsts[17943]: fd=11, revents=1
lwsts[17943]: lws_read: incoming len 6  state 5
lwsts[17943]: received pong
lwsts[17943]: 
lwsts[17943]: received expected PONG on wsi 0x1af1c10
lwsts[17943]: lws_set_timeout: 0x1af1c10: 0 secs
lwsts[17943]: Doing pong callback
lwsts[17943]: _lws_rx_flow_control: no pending change
lwsts[17943]: lws_read: read_ok, used 6
lwsts[17943]: fd=10, revents=1
lwsts[17943]: lws_read: incoming len 6  state 5
lwsts[17943]: received pong
lwsts[17943]: 
lwsts[17943]: received expected PONG on wsi 0x1aae1a0
lwsts[17943]: lws_set_timeout: 0x1aae1a0: 0 secs
lwsts[17943]: Doing pong callback
```

There are two idle connections (mirror and server status) and their PING and PONG processing is pipelined together.  But there is no problem there.

Can you update to master and check this also works for you or not with the test server?

There's no problem in the pingpong stuff, but after Dec 12th someone found a bug with same protocol in vhost linked list management only in the case your ws protocol was NULL https://github.com/warmcat/libwebsockets/commit/ad99232f8c007178a2916a08cb2b6f8ce010a384  I think this is probably the cause, the test apps use named ws protocols since they support multiple protocols, so they never had a problem.  That patch was backported to the other stable branches as well at the time.

In that case just update to lws master will fix this for you.

**Comment by HiAlisaYang** [comment]
OK,I will hava a try.Thanks very much.You are so nice.

**Comment by HiAlisaYang** [comment]
I find  that I recive the callback reason LWS_CALLBACK_RECEIVE_PONG per 50 seconds is because my lws_service is set to 50 seconds.

Does the callback reason LWS_CALLBACK_RECEIVE_PONG mean pong packets?

**Comment by lws-team** [comment]
It means someone sent you a PONG.  But you don't need to do anything in the callback.  Because lws already saw it.

If you tell lws_service to stay in poll() a long time, he can't take care of timeouts or pingpong faster.  So you should set it to like 1s, then it can handle timeouts and pingpong at the right time.

**Comment by HiAlisaYang** [comment]
Thank you very much for you response.
Merry Christmas Eve.
But I am still a little confused.When I received the callback reason LWS_CALLBACK_RECEIVE_PONG,I only captured TCP packets per 10s.There was no ws pingpong packets.(ws_ping_pong_interval is 5,timeout_secs is 5,lws_service time is 3.)
And I ever accidentally captured ws pingpong packets.

**Comment by lws-team** [comment]
Yes I think you may just be confused.

 - automatic pingpong in lws does not need the user code to do anything.  The connection stays up or gets closed.  That's it.  You shouldn't care about the PONG callback... I think this is the main confusion point.

 - in ws nobody sends a pong without first receiving a ping.  If someone sends you a pong, it really really implies you sent them a ping.

 - if using tcpdump or some other pcap app, it does not guarantee to capture 100% of the packets.  Make the app log what it's doing and what it received.

 - Why don't you set the service time to 1s?  It's cheap to do timeout processing.

**Comment by HiAlisaYang** [comment]
OK，I got it. Thanks very much.And merry Christmas !Have a nice day!
