### ISSUE TITLE
keep LWS_PRE bytes of memory behind or before the text?

### ISSUE THREAD

**Issue by hellochenwang** [warmcat/libwebsockets#736]
https://libwebsockets.org/lws-api-doc-master/html/group__sending-data.html

it says 

> LWS_WRITE_TEXT 	
Send a ws TEXT message,**the pointer must have LWS_PRE valid memory behind it**. 

it also says

> buf	The data to send. For data being sent on a websocket connection (ie, not default http), **this buffer MUST have LWS_PRE bytes valid BEFORE the pointer**. This is so the protocol header data can be added in-situ.

does that mean it need LWS_PRE bytes of memory both before and after the text buffer? or is it a typo?

**Comment by hellochenwang** [comment]
i guess it only needs LWS_PRE bytes before the pointer.

**Comment by lws-team** [comment]
Yes, only before.

Actually the English is consistent, 'behind' and 'before' the pointer have the same meaning.

Behind - pointer - "in front of"
Before - pointer - after

But your question confused me because Lws got started 6 years ago when ws was still being defined.  Earlier versions of ws had trailer bytes after the packet and for that you also needed to allocate padding at the end.  That was removed from lws some yesrs ago.

**Comment by hellochenwang** [comment]
Thanks!

**Comment by matthiasg** [comment]
fell into this myself. maybe the documentation should be more clear on this point

**Comment by lws-team** [comment]
Well, it also says in the lws_write() docs

```
 * So for example you need this kind of code to use lws_write with a
 * 128-byte payload
 *
 *   char buf[LWS_PRE + 128];
 *
 *   // fill your part of the buffer... for example here it's all zeros
 *   memset(&buf[LWS_PRE], 0, 128);
 *
 *   lws_write(wsi, &buf[LWS_PRE], 128, LWS_WRITE_TEXT);
```

I don't think it is ambiguous.  All the minimal examples do the right thing as well.  However I added some ASCII art in there by popular demand.

```
 * start of alloc       ptr passed to lws_write      end of allocation
 *       |                         |                         |
 *       v  <-- LWS_PRE bytes -->  v                         v
 *       (----------------  allocated memory  ---------------)
 *              (for lws use)      [====== user buffer ======]
```

**Comment by KabeerSadiq123** [comment]
Hi @lws-team ,
I am calling lws_write 2-3(actually random number) times from LWS_CALLBACK_SERVER_WRITEABLE.
I can't do marshaling as suggested by you, because I have different types of information in every call.
I mean I can't simply add the data, to call it once.  
I tried lws_partial_buffered to wait until network buffer is free, but it stuck in while loop. 
   while(lws_partial_buffered(wsi) >= 1)
        {
                continue;
        }
// I am calling lws_write after this while loop
this loop is running infinitely. So I am not able to call lws_write after 2nd call. 
lwsts[23249]: 0x7fd968003540 new partial sent 16218 from 18566 total
Above log is also coming, sometime after first call, sometime after second call. after that server stop working.
Below logs: 
lwsts[4983]: 0x7f90f8e32be0 new partial sent 2864 from 21994 total
lwsts[4983]: ****** 0x7f90f8e32be0: Sending new 22094 (▒~VJ{"status": 0, "), pending truncated ...
       It's illegal to do an lws_write outside of
       the writable callback: fix your code
kws-websocket-server: /output.c:123: lws_issue_raw: Assertion `0' failed.
Can you please help? 
Thanks.

**Comment by lws-team** [comment]
> I am calling lws_write 2-3(actually random number) times from LWS_CALLBACK_SERVER_WRITEABLE

Don't do that... just do it exactly once.

If afterwards you see you want to send more, then call lws_callback_on_writable() and wait to get another callback.  Look at how the minimal examples keep state in a pss to keep track of what you're trying to do.

**Comment by KabeerSadiq123** [comment]
> If afterwards you see you want to send more, then call lws_callback_on_writable() and wait to get another callback. Look at how the minimal examples keep state in a pss to keep track of what you're trying to do.
It is not possible to call all the data once, because its like a vector of string, and if the size of the string is 5, then I have to call lws_write 5 times that is must for my algorithm. 
So, should i call    lws_callback_on_writable() from LWS_CALLBACK_SERVER_WRITEABLE after every call.

**Comment by lws-team** [comment]
Not "every call" or you will spin forever at 100%... but while you have something else to transmit, ask to be called back when you may send it.  After the fifth time in your example, you don't have anything else to transmit at the moment... don't ask for another callback until you do.  Then lws can become idle until something else to do.

Look at how the examples use a pss to track state, ie, "I am on the third send in my sequence" or whatever, over multiple times around the event loop.
