### ISSUE TITLE
permessage-deflate options

### ISSUE THREAD

**Issue by dpeacock** [warmcat/libwebsockets#765]
What is the correct way to pass options for the permessage-deflate options?

I'm trying to add support for client_no_context_takeover and server_no_context_takeover the following way:

```
 struct lws_extension exts[] = {
                {
                        "permessage-deflate",
                        lws_extension_callback_pm_deflate,
                        "permessage-deflate; client_no_context_takeover; server_no_context_takeover; client_max_window_bits"
                },
                {
                        "deflate-frame",
                        lws_extension_callback_pm_deflate,
                        "deflate_frame"
                },
                { NULL, NULL, NULL /* terminator */ }
        };
        info.extensions = exts;
```

I'm running a libwebsockets server, and trying to connect a client (websocketsharp).  On the negotiation websocket sharp is passing in the following extensions:

```
Sec-WebSocket-Extensions: permessage-deflate; server_no_context_takeover; client_no_context_takeover
```

Libwebsockets is replying with the following:

```
Sec-WebSocket-Extensions: permessage-deflate
```

The result is the connection is failing because websocketsharp does not support context switching with permessage-deflate.

From the spec it sounds like the options such as 'server_no_context_takeover' should be passed back on the negotiation back to the client assuming it's supported.  (https://tools.ietf.org/html/rfc7692#section-7.1.1.1)

Is there another way these options should be getting initialized on the libwebsockets side so they are passed back in the negotiation or does libwebsockets not support the no context takeover options?

**Comment by lws-team** [comment]
The `.client_offer` member in the extensions struct is used to control what lws sends for that extension **when lws is the client**.  So it does nothing in your case lws is the server.

lws permessage-deflate knows all the RFC7692 options

```
const struct lws_ext_options lws_ext_pm_deflate_options[] = {
	/* public RFC7692 settings */
	{ "server_no_context_takeover", EXTARG_NONE },
	{ "client_no_context_takeover", EXTARG_NONE },
	{ "server_max_window_bits",	EXTARG_OPT_DEC },
	{ "client_max_window_bits",	EXTARG_OPT_DEC },
	/* ones only user code can set */
	{ "rx_buf_size",		EXTARG_DEC },
	{ "tx_buf_size",		EXTARG_DEC },
	{ "compression_level",		EXTARG_DEC },
	{ "mem_level",			EXTARG_DEC },
	{ NULL, 0 }, /* sentinel */
};
```

and indeed the lws server passes Autobahn strict testing of all the options including no_context_takeover.

https://libwebsockets.org/reports/clients/index.html

In the RFC section it says

```
By including this extension parameter in an
   extension negotiation offer, a client informs the peer server of a
   hint that even if the server doesn't include the
   "client_no_context_takeover" extension parameter in the corresponding
   extension negotiation response to the offer, the client is not going
   to use context takeover.
```

Looking at the code, lws client stuff parses what the server sends but lws server side just replies with the extension name... this works fine with browsers etc but in the case that the client can't function without the options, it'll blow up.

Since there is only one extension in the ws world, if you want to try solving it with a quick hack on lws look at server-handshake.c:147

```
				LWS_CPYAPP(*p, "\x0d\x0aSec-WebSocket-Extensions: ");
			*p += sprintf(*p, "%s", ext_name);
```

Just add the tokens you want to return in the sprintf... if that solves it we can think about a better solution.

**Comment by dpeacock** [comment]
Thanks for the details.  I can confirm if I pass the options back on the server handshake as recommended it connects and behaves as expected.

Let me know if you need anything else from my end, would really like to see a better more permanent solution for this one.

**Comment by lws-team** [comment]
I pushed a patch on master that should solve this, I tested it with client_no_context_takeover using the lws test client and the test server now accepted the option and copied it on to the Sec-Websocket-Extensions response.
