### ISSUE TITLE
WebSocket: Server Initiated Data

### ISSUE THREAD

**Issue by hiharsh** [warmcat/libwebsockets#771]
Hi, I would like o achieve following

1) Start a websocket server on C++
2) Listen for messages from client
3) Send response for messages based on some processing in my custom code.
4) SEND SERVER INITIATED text message/string to client when something changes on my custom code.
For # 1 to 3 I can use the echo server for 1 to 1 message handling (but that would be blocking to since I will be filling the response to the send string after I have processed the request from client). 
I looked at the telemetry and broadcast example but couldn't interpret/adapt for my requirements. 
How do I achieve the above ? Any example code?

here is what I believe pseudo code look like (This could be completely wrong, please advise accordingly ). 
```
//main 
//start a websocket server //The existing code does this
//start a thread to listen for asynchronous messages to be sent to client.  (I don't know how to achieve this)
 //register Accept, onConnection, onMessage, onError method //Existing code could do this
  //Upon message reception from client invoke onMessage method parse the message and invoke custome code
//Later the custom code should send message to thread who is waiting for the message to be sent to client using send message to client. 
```

**Comment by lws-team** [comment]
Lws is a singlethreaded, nonblocking C library... you can use it with C++ since they are fundamentally compatible.

But since you want to use a threaded, blocking style you might want to look around for a native C++ library instead.

If not, then you should look at chopping down the test server app to do what you want.  That already works end to end as a http[s] and ws[s] server, so if you cut it down carefully you are guaranteed your reduced version will work.

Lws uses singlethreaded callback semantics.
