### ISSUE TITLE
new partial

### ISSUE THREAD

**Issue by d30jeff** [warmcat/libwebsockets#775]
I'm getting about 700 lines of 
`lwsws[19185]: 0xc5d640 new partial sent 1044 from 4096 total`

I have changed the value in *context.c*
`context->pt_serv_buf_size = 4096;` to `3000000`

and in my protocol
    
```
#define LWS_PLUGIN_PROTOCOL_STATS_STREAMER \
 { \
   "protocol-stats-streamer", \
   callback_stats_streamer, \
   sizeof(struct per_session_data__stats_streamer), \
   3000000, /* rx buf size must be >= permessage-deflate rx size */ \
 }
```

I noticed that the number of lines reduced from 700+ lines to 29 lines, but I'd still prefer if I could make it disappear.

Please point me to the right direction, thanks

**Comment by lws-team** [comment]
Basically you should not try to not just fire big buffers at the network.

Lws approach is to commit your write buffer fully, immediately, and be done.  Hence it allows tx buffers on the stack.  However on a real network and system, the kernel has his own ideas about how much he will accept to write on a given connection, depending on the tcp window and memory pressure.

If lws sees the kernel only ate some of your tx buffer when it tried to write() it, he prints the message you see and conceals the problem by copying the remaining data into a malloc'd temp buffer as an emergency solution.  He then disables WRITEABLE notifications reaching your code while he drains the saved buffer, re-enabling them when nothing more to clear.

Rx buf size also limits how much lws will send at one time, that is why tuning it to match the size of your tx action helped reduce these complaints.

You should note the tcp window and throughput on the connection play a part in how much the kernel will accept.  If your peer is a 300baud modem or guy on dodgy gsm link, the window will fill and each time there will only be a little space to send more.  So even though on a local link you mainly can send everything of your big buffers now, it's not going to be true in the general internet.

There's no perfect solution, but since lws will catch the problem it just has to be better.  Ws has a 'fragment' concept where an arbitrary-sized ws message may be sent in smaller ws fragments.

 - When a ws peer receives a fragment with the FIN bit set, it understands it will have received a complete message when it receives all of that fragment. Until then, ws will let you send as many non-FINal fragments as you want - infinite sized messages are supported in ws, somewhat uselessly.

 - lws_write() sends TEXT or BINARY ws data in a single ws fragment every time.

 - By default, those fragments have FIN set. So one send is one ws fragment and that's one ws message each time.

 - You can selectively suppress the FIN bit using the lws_write flag LWS_WRITE_NO_FIN. Then you are sending a fragment each time, but one that does not finish the message.

 - To send messages of arbitrary length then, you apply LWS_WRITE_NO_FIN to every call to lws_write() except the last one of the message.

 - The first fragment of a message must go out with either LWS_WRITE_TEXT or ..._BINARY. Subsequent fragments must use LWS_WRITE_CONTINUATION. The LWS_WRITE_NO_FIN flag can be or-ed on to any of those as needed.

**Comment by lws-team** [comment]
If some other question please continue the issue, but closing for now since nothing for me to do.
