### ISSUE TITLE
RAW PROTOCOL

### ISSUE THREAD

**Issue by rollen1960** [warmcat/libwebsockets#778]
it's possible to implement a plain socket protocol ?
if the server receive a non HTTP frame, semplicy pass it to the callback, with LWS_CALLBACK_RECEIVE_SOCKET
e for writing the write with LWS_WRITE_SOCKET

Thank you

**Comment by lws-team** [comment]
Not without a little bit of work... lws tracks connection state on the understanding that is progresses from tcp connection / accept and then HTTP processing for everything.

If it's being a server, there's the issue of how should it know if it wants to accept RAW?  Just accepting any trash by an HTTP server doesn't sound satisfying.  Maybe mark a vhost, on its own port, as only receiving raw frames?

**Comment by rollen1960** [comment]
Yes all right. But i think that if on port (for example) 80 the server receive a byte sequence that can not be interpreted as WS and not as HTTP it call the callback with LWS_CALLBACK_RECEIVE_SOCKET. If you want to make an option like LWS_SERVER_OPTION_ACCEPT_RAW that shall be very nice. The important is that I can take on the same port not only WS/WSS/HTTP/HTTPS but WS/WSS/HTTP/HTTPS and RAW.

Thank you for your patient.

**Comment by lws-team** [comment]
You don't need to worry about ws because all ws connections begin as http.

But already in the shared http/https mode lws is interpreting the incoming data and making a decision.  When ssl comes 'it's a byte sequence that cannot be http'.  Therefore you cannot have arbitrary bytes interpreted as something else too.

If you can send a fixed header on the binary connection you can at least assertively declare what it is.  If it's just anything, 1/256 connections will be misinterpreted as tls and dropped.

Honestly it sounds like a bad idea if no management of it at all.

**Comment by rollen1960** [comment]
I thinked that the server recognize id the input stream is HTTP because receive "POST / GET HTTP" and recognize WS if because receive a bytes sequense of the websocket encoding. So if the server response is 
[2017/02/08 12:30:03:3977] NOTICE:  forbidding on uri sanitation and i receive
"HTTP/1.0 403 Forbidden\r\nserver: libwebsockets\r\ncontent-type: text/html\r\ncontent-length: 38\r\n\r\n<html><body><h1>403</h1></body></html>"
is because the server don't recognize the input stream. In this case I auspice that the server make the callback RAW . If you prefer it's possible sent to the server a initialization stream, like the tree byte "RAW" or another string. And I hope that all work.

What do you think ?

**Comment by rollen1960** [comment]
I found this
http://stackoverflow.com/questions/20953505/detect-ssl-protocol-in-c

**Comment by lws-team** [comment]
The ssl detect code in lws was contributed a while ago... it looks for one byte at or near the start of the stream that is always expected to be a particular non-ascii value if it's the ssl handshake.  If the http/https hack is enabled, seeing something other than that byte value in the right place diverts processing away from https handshake and forces it to assume it's http.

All ws connections start as http and perform an upgrade handshake using http headers.  No connection starts off already in ws mode.  It's like that because there are many http proxies and filters that will not pass stuff on port 80 that doesn't look like valid http to them.

If your raw protocol always starts with a valid one-line http header with some special method name, eg, "`RAW / HTTP/1.1\r\n\r\n`" that is a much better fit.  The existing parser can be modified to accept it.  And you would be able to also do "raw-inside-ssl", same as https is "http-inside-ssl".

**Comment by rollen1960** [comment]
Well, very well for me. How can I see that the http connection is RAW HTTP (in wich callback reason / in ) ?
Thank you very much for all, and say me when the new parser is enable.
Thank Mario

**Comment by lws-team** [comment]
Current master has a new api for socket adoption that's a lot more flexible

```
typedef enum {
	LWS_ADOPT_RAW_FILE_DESC = 0,	/* convenience constant */
	LWS_ADOPT_HTTP = 1,		/* flag: absent implies RAW */
	LWS_ADOPT_SOCKET = 2,		/* flag: absent implies file descr */
	LWS_ADOPT_ALLOW_SSL = 4		/* flag: if set requires LWS_ADOPT_SOCKET */
} lws_adoption_type;

typedef union {
	lws_sockfd_type sockfd;
	lws_filefd_type filefd;
} lws_sock_file_fd_type;

/*
* lws_adopt_descriptor_vhost() - adopt foreign socket or file descriptor
* if socket descriptor, should already have been accepted from listen socket
*
* \param vhost: lws vhost
* \param type: OR-ed combinations of lws_adoption_type flags
* \param fd: union with either .sockfd or .filefd set
* \param vh_prot_name: NULL or vh protocol name to bind raw connection to
* \param parent: NULL or struct lws to attach new_wsi to as a child
*
* Either returns new wsi bound to accept_fd, or closes accept_fd and
* returns NULL, having cleaned up any new wsi pieces.
*
* If LWS_ADOPT_SOCKET is set, LWS adopts the socket in http serving mode, it's
* ready to accept an upgrade to ws or just serve http.
*
* parent may be NULL, if given it should be an existing wsi that will become the
* parent of the new wsi created by this call.
*/
LWS_VISIBLE struct lws *
lws_adopt_descriptor_vhost(struct lws_vhost *vh, lws_adoption_type type,
			   lws_sock_file_fd_type fd, const char *vh_prot_name,
			   struct lws *parent);
```

Normal operation (HTTP) with and without SSL is tested and raw file descriptor is tested, but not raw socket yet (type LWS_ADOPT_SOCKET).

**Comment by lws-team** [comment]
This is now done as you originally requested it.  From README.coding.md

@section rawsrvsocket RAW server socket descriptor polling

You can also enable your vhost to accept RAW socket connections, in addition to
HTTP[s] and WS[s].  If the first bytes written on the connection are not a
valid HTTP method, then the connection switches to RAW mode.

This is disabled by default, you enable it by setting the `.options` flag
LWS_CALLBACK_RAW_ADOPT_FILE when creating the vhost.

RAW mode socket connections receive the following callbacks

```
        LWS_CALLBACK_RAW_ADOPT
        LWS_CALLBACK_RAW_RX
        LWS_CALLBACK_RAW_WRITEABLE
        LWS_CALLBACK_RAW_CLOSE
```

You can control which protocol on your vhost handles these RAW mode
incoming connections by marking the selected protocol with a pvo `raw`, eg

```
        "protocol-lws-raw-test": {
                 "status": "ok",
                 "raw": "1"
        },
```

The "raw" pvo marks this protocol as being used for RAW connections.

`protocol-lws-raw-test` plugin provides a method for testing this with
`libwebsockets-test-server-v2.0`:

Run libwebsockets-test-server-v2.0 and connect to it by telnet, eg

```
    $ telnet 127.0.0.1 7681
```

type something that isn't a valid HTTP method and enter, before the
connection times out.  The connection will switch to RAW mode using this
protocol, and pass the unused rx as a raw RX callback.

The test protocol echos back what was typed on telnet to telnet.


Please open another issue if you find any problem.
