### ISSUE TITLE
using keep alive with clients

### ISSUE THREAD

**Issue by dreum** [warmcat/libwebsockets#788]
This isn't as much an issue as a question. I'm interested in using the keep alive functionality for a client (my server side can disappear without notice), but was failing to see any effect when changing the ka parameters. Looking through the source code it appears that these options are only being set when creating a vhost. Is it intended for all clients to create a vhost instance or is keep alive only for the server side? The sample client isn't using a vhost, though it's not using the keep alive functionality.

I ended up setting the ping_pong interval and this seems to get me the functionality I wanted, but was still interested in knowing how keep alive is supposed to work with clients (if at all).

**Comment by lws-team** [comment]
The tcp keep-alive stuff was implemented first... even for client-only, by default a dummy vhost is created along with the context.  So I dunno what the problem is but it shouldn't be what you're thinking.

In any event doing it at the ws layer with the explicit ping / pong and timeouts is available now, for both client and server sides, and doesn't need tcp keepalive support in the tcp stack.

**Comment by dreum** [comment]
Thanks for the info. I might play around with this a little bit longer to see if I missed anything, but will probably just use the ping/pong functionality. Thanks again.
