### ISSUE TITLE
When I set system time，I could not receive ping-pong any more. 

### ISSUE THREAD

**Issue by HiAlisaYang** [warmcat/libwebsockets#826]
I was running websockets on suse on 2017-3-7.
Then I set my system time to 2021-8-3. Webscokets ping-pong was still available.
And The I set my system back to 2017-3-7. I could not receive ping-pong any more.  And after 5 minites, my browser get the notification of websocket was closed with the errcode 1006.

**Comment by lws-team** [comment]
... is this over ssl?

What is the expiry date on your server cert?

**Comment by HiAlisaYang** [comment]
Without ssl.  I just tried to set system time 2 minites earlier, then pingpong was not available util  two minites passed.

**Comment by lws-team** [comment]
Changing the system time will break scheduled events in lws... the events are scheduled for now + whatever, if "now" becomes radically different it will affect when they happen.

But are you expecting to do a lot of time travel?  Generally people use ntpd to manage time tracking, this gradually applies time offsets in small steps over long periods.

**Comment by HiAlisaYang** [comment]
Thank you for your response.
Yes，ntpd could deal with most problems.  But time travel is Unavoidable, such as Daylight Saving Time.  Websockets may do not work normally for an hour.Is there any way to deal with  Daylight Saving Time?

**Comment by lws-team** [comment]
Hum... to be honest I dunno what happens during DST type changes.  If you change the TZ, it changes how the time is reported for formatting but doesn't change the UTC time in the system clock.  I think DST will be the same, because DST or not is a matter for TZ (another TZ will not observe the same DST changes).  Either way, UTC time did not change.

I'll study it later and reply again.

**Comment by lws-team** [comment]
http://man7.org/linux/man-pages/man2/gettimeofday.2.html and http://man7.org/linux/man-pages/man2/time.2.html

together specify `getimeofday` returns seconds from a fixed epoch in UTC.  So I think you find this is unaffected by TZ-based  DST, which is a variable offset against UTC.

It is affected by step changes in system time.  But I think that's probably OK in the real world.

**Comment by mmilata** [comment]
@lws-team fyi you might be able to avoid this behavior by using `clock_gettime(CLOCK_MONOTONIC, ...)` on platforms that support it. See e.g. https://blog.habets.se/2010/09/gettimeofday-should-never-be-used-to-measure-time.html

**Comment by lws-team** [comment]
Well, this only makes a problem if someone changes the actual system time UTC time.  Not timezone / locale changes, which only affect presentation offsets, and not ongoing ntpd adjustments which are rate-limited to well below a second a go.

I dunno about you but I have never applied that kind of manual UTC system time change to any of my server machines.  I have embedded devices that have no RTC and update the time fom 1970 to current a little after boot... perhaps because it's so early and ssl certs can't even validate without correct time, this has never caused a problem for me either.  So I think it's alright.

If someone worries about it more than I do and wants to send a nice patch that checks in cmake and uses clock_gettime() instead if available, I'll be happy to try it.

**Comment by HiAlisaYang** [comment]
@lws-team Without ping-pong will cause the error 1006?I find that When thare is no ping-pong the websocket connection will not be closed with 1006 until  my browser send a message to websocket. The websocket connection would be closed with 1006 after browser  sent a message and five minites passed.

**Comment by lws-team** [comment]
Lws does not issue 1006, so you need to look at the remote peer to find out why he closed with 1006.

In fact 1006 is banned from being sent, it is defined to be a locally generated error only.  So don't ask me to guess, have a look in the logs / js console of the remote peer as to what it felt happened.

**Comment by HiAlisaYang** [comment]
@lws-team Thanks a lot for your help. As we known, if someone changes the actual system time UTC time,the ping-pong will be unavailable.I hope you can provide a patch. I known I have other ways to solve this problem.（such as add another keepalive message）. I just think that if someone changes the actual system time UTC time, the ping-pong still is ok is a better way.
Anyway，Thanks very much.
