### ISSUE TITLE
lws_write changes buffer

### ISSUE THREAD

**Issue by tmarrinan** [warmcat/libwebsockets#827]
Hello.
To improve performance I am wanting to reuse a buffer for a binary message that is sent multiple times, rather than allocating/freeing a new buffer for each send. However, it appears as though the actual contents of the buffer are altered by calling lws_write.

```
int n;
long length = 1024;
unsigned char *internal = (unsigned char*)malloc((length + LWS_PRE) * sizeof(unsigned char));
unsigned char *buffer =  internal + LWS_PRE;

// fill buffer

n = lws_write(wsi, buffer, length, LWS_WRITE_BINARY);

// check contents of buffer here - they are different from when they were filled!
```

At some later point, I would like to call `n = lws_write(wsi, buffer, length, LWS_WRITE_BINARY);` again, but this ends up just sending junk since the contents have changed

**Comment by lws-team** [comment]
Yes, it's by design in two ways

 - lws_write() will prepare up to LWS_PRE bytes behind the payload with ws protocol header and send it as one block with they payload.  This is not too onerous since the next write will overwrite that region too.

 - ws standard requires 'masking', XORing the payload with a random nonce to make it unpredictable.  We do it in-place since we don't limit the buffer size, most callers don't reuse the payload buffer.

Because of the second one, someone has to memcpy the data in each time... in lws since you're the only guy who fills the payload your code must do it.
