### ISSUE TITLE
Libwebsockets Bayeux/CometD support

### ISSUE THREAD

**Issue by GhostGumm** [warmcat/libwebsockets#836]
Hi everyone,

I made serveral Clients and Servers in C code using Libwebsockets for WS support and as allways all went good. 
Lately i needed to conform to the WebSocket Bayeux protocol.
I knew that LWS didn't have such support. 
I went fetching the web and found nothing relevant or as powerfull as LWS with Bayeux support. Weirdly enough the CometD community seem to be in need of one but no implementation yet. 
At last i came with the idea of adding a Bayeux protocol support to the great Libwebsockets. 
Here are my questions : 
- Is LWS open to such modifications ? 
- Do you think it is the best approach ? 
- If it is, where do you think should i begin  ?

Hopefully my message here will not bother.
Thank you for your time and work.

**Comment by lws-team** [comment]
As far as I can see from a quick google, lws itself probably doesn't need much change since as you mention cometd says it can already use ws as a transport... otherwise it seems to be about passing lumps of JSON around (a gross simplification no doubt).

The cleanest way from lws perspective is make a protocol plugin that implements everything specific.  These can be developed outside of lws itself and bound at runtime, eg

https://github.com/warmcat/libwebsockets/blob/master/plugin-standalone/protocol_example_standalone.c

If it's useful I'd be happy to include it in lws but the standalone plugin scheme is convenient to develop for you and hopefully architecturally clean.

The first step would be find docs on how the cometd ws transport is supposed to work (eg, ws subprotocol name), and a client + server using it... you can look at how they communicate and start to try to replace the server with your implementation, so the client connects to it and extend your implementation until the client works with it the same as the original server.  If things seem missing to support it on lws side we can discuss when we get an idea what they are.

**Comment by GhostGumm** [comment]
Thank you for your answer,

i'll get back to you as soon as i have something relevant to discuss/present.

Have a great day.

**Comment by lws-team** [comment]
OK good luck, I am curious how it goes.  But since nothing for me to do about this (yet), I'll close this for now.
