### ISSUE TITLE
ssl and non ssl

### ISSUE THREAD

**Issue by tejendrasingh** [warmcat/libwebsockets#837]
my websocket server running on both ssl and non ssl on different ports using lwsws/conf.d/localhost file.
without ssl on console server printing 
lwsts[13917]: lws_server_socket_service: wsi 0x7f9ebc001e90 read 1442
lwsts[13917]: lws_server_socket_service: wsi 0x7f9ebc001e90 read 1442
lwsts[13917]: lws_server_socket_service: wsi 0x7f9ebc001e90 read 926
lwsts[13917]: 192.77.120.133 - - [16/Mar/2017:07:40:40 +0000] "PUT /english http/1.1" 200 586 curl/7.52.1
lwsts[13917]: lws_header_table_detach: wsi 0x7f9ebc001e90: ah held 5s, ah.rxpos 191, ah.rxlen 191, mode/state 0 0,wsi->more_rx_waiting 0
lwsts[13917]: lws_server_socket_service: wsi 0x7f9ebc001e90 read 0

and with ssl--

lwsts[13917]: lws_server_socket_service: wsi 0x7f9ebc001e90 read -2
lwsts[13917]: lws_server_socket_service: wsi 0x7f9ebc001e90 read -2
lwsts[13917]: lws_server_socket_service: wsi 0x7f9ebc001e90 read -2
lwsts[13917]: lws_server_socket_service: wsi 0x7f9ebc001e90 read -2
lwsts[13917]: lws_server_socket_service: wsi 0x7f9ebc001e90 read 4096
lwsts[13917]: lws_server_socket_service: wsi 0x7f9ebc001e90 read 4096
lwsts[13917]: lws_server_socket_service: wsi 0x7f9ebc001e90 read 4096
lwsts[13917]: lws_server_socket_service: wsi 0x7f9ebc001e90 read 4096
lwsts[13917]: lws_server_socket_service: wsi 0x7f9ebc001e90 read -2
lwsts[13917]: lws_server_socket_service: wsi 0x7f9ebc001e90 read -2
lwsts[13917]: lws_server_socket_service: wsi 0x7f9ebc001e90 read 1094
lwsts[13917]: 192.77.120.133 - - [16/Mar/2017:07:41:04 +0000] "PUT /english http/1.1" 200 587 curl/7.52.1
lwsts[13917]: lws_header_table_detach: wsi 0x7f9ebc001e90: ah held 6s, ah.rxpos 191, ah.rxlen 191, mode/state 0 0,wsi->more_rx_waiting 0
lwsts[13917]: lws_server_socket_service: wsi 0x7f9ebc001e90 read -1

Why server is reading -2 and in last -1 with ssl??

**Comment by lws-team** [comment]
Well, I guess having an issue "everything is working" is not so bad.

When you use SSL, we still watch the socket and hear about incoming data there.

But because it is encrypted, we don't use the data we read from the socket, OpenSSL "does something" to it and then we read that.

Sometimes, data comes on the socket, but it is not enough to produce decrypted output for us.  OpenSSL needs to write something back to the other side, or he needs to read a bit more before he has a full block he can decrypt or whatever magic it is.

In those situations we serviced network activity on the socket, but we got no payload... this is the -2.  There is no error, no data yet and OpenSSL wants to do something before data will come.  We return to the event loop and get on with other stuff in the meanwhile.

The -1 is our learning the other side closed the SSL connection.
