### ISSUE TITLE
Building v2.2.0 with buildroot fails

### ISSUE THREAD

**Issue by BoardSemiRigid** [warmcat/libwebsockets#848]
Hi,
As you suggested on a previous issue I had, I have upped from v2.1.0 to v2.2.0
I am building/testing both on both host ( x86) and target ( arm ).

I have just attempted to up the version used by buildroot from v2.1.0 to v2.2.0, and aside from the usual problems with buildroot and hash verification ..which I have already  resolved.

It doesn't build ...
it fails with 
/home/user/buildroot-2016.11.1/output/build/libwebsockets-v2.2.0/lib/lws-plat-unix.c: In function '_lws_plat_file_seek_cur':
/home/user/buildroot-2016.11.1/output/build/libwebsockets-v2.2.0/lib/lws-plat-unix.c:671:3: error: format '%ld' expects argument of type 'long int', but argument 3 has type 'lws_filepos_t' [-Werror=format=]
   lwsl_err("error seeking from cur %ld, offset %ld\n",

However the same source tarball compiles perfectly fine with the host's native x86_64 compiler.
Any thoughts ?

**Comment by lws-team** [comment]
This is already fixed if you use v2.2-stable

https://github.com/warmcat/libwebsockets/blob/v2.2-stable/lib/lws-plat-unix.c#L671

We added extra printf arg validation before v2.2, but some bugs with it only show up on specific toolchains since they end up with different arrangements for the real type of size_t etc.
