### ISSUE TITLE
How can I get parameters from handshake header?

### ISSUE THREAD

**Issue by HiAlisaYang** [warmcat/libwebsockets#853]
My lws run as a server. For example I want to get the parameter `Origin` from handshake header.
`Origin: https://XXX.XXX.XXX.XXX:7680`
How can I get it?(I have no other http packets except handshake.)

**Comment by lws-team** [comment]
Because storing the headers is expensive in memory, lws maintains a configurable number of "ah" separate from the connections, where it stores the parsed header data.  Since once they're set up connections might live for a long time, lws detaches the ah from the connection as soon as possible, so it can be reused for another connection.

For ws connections, "as soon as possible" means just after LWS_CALLBACK_ESTABLISHED... up until then and including that callback you can use lws_hdr_total_length() / lws_hdr_copy() to access any header lws recognizes (which is a lot, see WSI_TOKEN_* in libwebsockets.h).

**Comment by HiAlisaYang** [comment]
Thanks a lot.

**Comment by HiAlisaYang** [comment]
@lws-team I still have another question. If I want to get a self-defining parameter from handshake, Is there any way to get it?

**Comment by lws-team** [comment]
Lws only processes headers that it knows about, the rest are thrown away.

You can teach lws new headers, but it has a special procedure to rebuild the lexical anlyzer.

1) edit `lib/lextable-strings.h` and add the new header string at the end before the empty string (after "connect" at the moment)

2) add a matching entry in `lib/libwebsockets.h`, again after `LWS_TOKEN_CONNECT` at the moment
 
3) cd into ./lib abd run this two times

```
 $ gcc minilex.c -o minilex && ./minilex > lextable.h
```
If your header is of any interest to anyone else send a patch of the changes.
