### ISSUE TITLE
How to assign local port in libwebsocket when working in client mode?

### ISSUE THREAD

**Issue by King026** [warmcat/libwebsockets#855]
In both types of connection making functions lws_client_connect_via_info() and lws_client_connect() you guys didn't give any option to set local port. Is there any way to set local port, or libwebsocket is just avoiding it for binding issues?

**Comment by lws-team** [comment]
Well...

 - it's not necessary to specify the outgoing (ephemeral) port, the OS will pick one

 - nobody has ever asked for it until today... these two are the main reasons

 - I think IIRC colliding on the requested port isn't really an issue, because the dest ip and port must also be the same to get a problem.

Is there some use for it I missed until now?

**Comment by King026** [comment]
Ephemeral ports allocated by OS has a very wide range. I am communicating with a server which allows a certain port number, or a given port range. This situation is very common with firewall protected servers.

**Comment by lws-team** [comment]
We've been going 6 years and this is the first time someone has mentioned it, so I take from that at least amongst our users it is not that common.  If you're interested in implementing it for your own use I'll be interested to get patches though.

**Comment by King026** [comment]
Ok.. I will let you know if I implement it. Thank you.
