### ISSUE TITLE
HTTP Response with dynamic content

### ISSUE THREAD

**Issue by louisbraun** [warmcat/libwebsockets#864]
Hi,

in my webapp i use the libwebsockets HTTP server to serve dynamically created content for single user requests via ajax. I do this more or less like it is shown in your test HTTP server "send a big file by hand" example case, with one exeption: 
In the LWS_CALLBACK_HTTP callback i have to set the content_length header, and for this i need the dynamically created response content. This content is mostly gathered by database requests and is sent to the client as a Json object. To write this response i use lws_callback_on_writable() to reserve a writable slot and send the data via lws_write there. Since i do not want to gather the dynamic content twice both in the LWS_CALLBACK_HTTP and in the LWS_CALLBACK_HTTP_WRITEABLE callback, i transfer this data via an char array in the per_session_data__http struct, and this char array has a fixed size...

And now after many words my issue....hopefully everything is clear up to here :-) I don't like to use a fixed size buffer at this place...my responses could have various sizes from some bytes up to some kilobytes. If i would reserve the "maximum possible" response length, I'd have to use a large and more or less guessed value of some kilobytes. That means allocating this memory for each http request, even if it is not necessary at all...that can not be good from performance point of view, and additionally the chance that the buffer is still to small still exists. 

Do you see a possibility to get the memory for the response dynamically? Or is my design wrong and i could solve my requirement in a different way? Any ideas? 

Many thanks for reading ;)

Cheers Louis

**Comment by lws-team** [comment]
If I understand it, one way is you can replace the fixed array in the pss with a malloc'd / realloc'd buffer you allocate, manage and free yourself.  The downside is the max dynamic allocation if you have a lot of connections is hard to constrain.

Another way is actually, you don't need to have the whole response in one place at one time, you could send it in fragments in multiple writable callbacks with state vars in the pss managing what to do next.  This rather depends on if the db api lets you offset the read of the blob... if so that would let you handle arbitrary-sized blobs with just a single stack buffer, since you can prepare the next chunk of the buffer at the writable callback just before sending it.

It seems how you fetch the blob and size that buffer is the real point, not so much the lws side IIUI.

**Comment by louisbraun** [comment]
Hi,

thx, i've implemented now your first suggestion...sometimes it is too easy ;) Topic solved...

Cheers Louis
