### ISSUE TITLE
Delay before LWS_CALLBACK_ESTABLISHED on new connection

### ISSUE THREAD

**Issue by thelasthope4U** [warmcat/libwebsockets#879]
Sorry to come back to this but while continuing to invesigate, I found I was wrong in version information.  I am running version 2.1 on our server.  I thought it was 1.6 due to the release-checklist.txt file on cloned folder.  It indicates 1.6.0.  If this is the case, is the rdns feature disabled in 2.1 or do I need to do a configuration to make sure it is not used?

**Comment by lws-team** [comment]
Release-checklist is a file to remind me what to do before making a release.  Any numbers in there are just examples.  The version can be found at the top of CMakeLists.txt or better from which branch you got it from.

Your problem is your machine is misconfigured and 192.168.x.x lookups take 5s when they should return immediately.  That's your problem to fix and isn't related to lws.  Take a look again at the suggestions I gave at the end of your last issue

**Comment by thelasthope4U** [comment]
Yes you are correct, working on rdns issue, when putting clients in host file have much better performance.  Just wanted to know if same applied to this release.  Thanks again, lws is a great help!
