### ISSUE TITLE
lws_issue_raw: Assertion `0' failed.

### ISSUE THREAD

**Issue by tejendrasingh** [warmcat/libwebsockets#881]
my server is closed after this error, many time
lwsts[27069]: 0x7f98f0007f80 new partial sent 1454 from 2741 total
lwsts[27069]: ****** 0x7f98f0007f80: Sending new 2834 (×^K^N{"status": 0, "), pending truncated ...
       It's illegal to do an lws_write outside of
       the writable callback: fix your code
libwebsockets/lib/output.c:123: lws_issue_raw: Assertion `0' failed.

i also tried https://github.com/warmcat/libwebsockets/issues/816
with pt_serv_buf_size=131072 ans rx_buffer_size 256000
but same error
Please help me on this

**Comment by tejendrasingh** [comment]
i am using lwsws with count-threads = 10 and fd-limit-per-thread=1
i changed the lejp-conf.c file for set  fd-limit-per-thread from lwsws/conf file.

**Comment by lws-team** [comment]
Multiple service threads is kind of experimental... the problem disappears if you have one service thread?

**Comment by tejendrasingh** [comment]
yes works fine with count-threads=1 and fd-limit-per-thread=10...

**Comment by lws-team** [comment]
Like I said it's 'experimental'... lws is architected for it but since I have never needed it, I did not take any special care about it.

If you want to help me debug it and send patches fixing it, great.  If you want me to stop what I am doing and spend some days fixing it for you, that is not going to happen any time soon.  So in that case, just use one thread.

**Comment by tejendrasingh** [comment]
ok... but the problem is . this is not happening alway, in some case this happens... 
Is there any instruction when debugging ?

**Comment by lws-team** [comment]
In theory it should never happen, since each wsi should belong to exactly one pt (per-thread) struct, and each service thread should only be servicing things belonging to his associated pt.

So it would be a good first step to check in lws_write that for a particular wsi, if he always being called from one thread?  Eg you could add a member in the struct lws for debug purposes to store the thread id there in lws_write.  And make a log if lws_write ever sees a different thread id for that wsi.

**Comment by lws-team** [comment]
If you end up with some information from debugging, feel free to continue.
