### ISSUE TITLE
plugin with more than one source file

### ISSUE THREAD

**Issue by blondie101010** [warmcat/libwebsockets#891]
Hi,

I'm building a more complex plugin than the samples and would like to split my code in a few files to make it better organized.  How can I do that?

I'm already able to make my plugin compile as it is by adding a line in CMakeLists.txt.

Thanks!

**Comment by lws-team** [comment]
The best way to build plugins is follow the `./plugin-standalone/` example structure.  That builds the plugin as its own project, outside of lws... not sure if you are already doing this or not.

That method has its own, much simpler CMakeLists.txt... I started explaining how to modify it, but since it's cut down from the lws cmake where all plugins have one source it's easier to modify it on my side to be friendlier for what you're doing.  So I pushed a small patch on master + v2.2-stable that brings PLUGIN_NAME definition and the source list to near the top of the CMakeLists.txt file.

**Comment by blondie101010** [comment]
That is a great solution!  Thank you so much!
