### ISSUE TITLE
ESP32 Loopback 

### ISSUE THREAD

**Issue by tedwoodt25** [warmcat/libwebsockets#901]
Should I be able to run a client and server on different threads and have them communicate with each other?

I'm running FreeRTOS on an ESP32.

I have a server which I can connect to externally, but when I try to open a local client to connect to it the client times out with a LWS_CALLBACK_CLIENT_CONNECTION_ERROR callback. I get other callbacks on the client during the timeout period but it never connects.

**Comment by lws-team** [comment]
Generally, yes it should work.

But on ESP32 who knows... it's lwip underneath.

The first move is look at why the client connection failed, the callback `in` parameter will either be NULL or point to a char * describing at which point in the client sequencing it failed; you can try dumping it with eg `lwsl_notice("%s\n", (char *)in);` in CONNECTION_ERROR.

Also if your client connection info struct is on the stack, be sure you memset it to 0 before setting the members.

**Comment by tedwoodt25** [comment]
"in" is a null pointer

**Comment by lws-team** [comment]
There's no specific message if the socket simply gets closed somewhere along the line before the transaction completes, eg, other side hangs up on it.

Generic client connections work okay, -factory has them to check for updates from the remote server and I confirmed that worked.

https://github.com/warmcat/libwebsockets/blob/3cf570ec524e0b42dec94534a8b0250966c14ca4/plugins/protocol_esp32_lws_scan.c#L181

Your problem would be less of a guessing game (since only you have your code) if you also confirmed you can do normal, outgoing client GET or ws connection first.

**Comment by tedwoodt25** [comment]
Yes. normal outgoing connection - to another ESP32 running libwebsockets/lwip as a server works fine

**Comment by lws-team** [comment]
Well... it sounds like issue about lwip routing rather than lws.  Lws has no knowledge about whether the IP is externally routed or whatever.

I think no explicit loopback interface on ESP32, ie, there is no 127.0.0.1 on an interface 'lo' as you could rely on with a *nix system.  You'd have to know your IP on an external interface like WLAN (there's an api to get it) and try to connect to that from inside.  But I can imagine few people doing that on ESP32 and the way the lwip stack is configured not dealing with routing traffic from inside properly.  It would work ok on a generic linux system.

Maybe have a grep around with the lwip config options in esp-idf... there's also a 'copy packets between l2 and l3' option in sdkconfig that might be related.  Anyway it's not an lws issue by the sound of it.
