### ISSUE TITLE
How to remove a specific vhost?

### ISSUE THREAD

**Issue by leonardorufino** [warmcat/libwebsockets#919]
I'm creating some vhosts using LWS_SERVER_OPTION_EXPLICIT_VHOSTS and, at some point, I need to remove some of them.
I've seen that lws_context_destroy2 deletes all vhosts (and the context), but how can I delete a specific vhost and continue with my context and the other vhosts?

**Comment by lws-team** [comment]
There's no support for dynamic vhost deletion (because I have no use for it and nobody asked for it [1]).  The model is the same as Apache, vhosts created at start while you have privs, because generally people do not want root internet-facing processes, and for lwsws anyway 'service reload' that forks a new child using fresh config having closed old child listen sockets but left it up until all connections close when it autocloses.  A listening vhost requires external infrastructure like port forwards and firewalls,along with the ports hardcoded in scripts etc that does not make them naturally very dynamic.

If you want to send a patch for dynamic vhost closing, almost all the code is already there as you saw.  But you will probably need to mark it as about to close, so it rejects further service, logically close all wsi related to it and the listen sockets, but defer the actual destruction until service loop or other parent caller that may have a vhost pointer must have finished, eg in the periodic timeout check.  Libuv requires async object handle close with the loop still running, and you must count that all related objects were finalized by it before destroying them, or you will enter a crashy, leaky libuv hell.

[1] As a matter of fact nobody asked for multi vhost either, but I had a use for it.

**Comment by leonardorufino** [comment]
It seems like this will take more time than I have now.
I will delete the entire context and recreate all vhosts for now and maybe I change it in the future.
Thanks.

**Comment by lws-team** [comment]
No worries.  Depending on the behaviour you want you can also go the lwsws 'service reload' way, or just defeat accepts on the vhost listen socket.
