### ISSUE TITLE
Allow user to create their own openssl context

### ISSUE THREAD

**Issue by cbucht200** [warmcat/libwebsockets#924]
Looking through the API and source, it does not seem possible to create one's own SSL_CTX and use it as a server? This functionality would be very helpful so that user can tie into callbacks such as verify and the openssl psk callback.

**Comment by lws-team** [comment]
In lws every vhost you create has an SSL_CTX.

If you want to hook verify you do it using the LWS_CALLBACK_OPENSSL_PERFORM_CLIENT_CERT_VERIFICATION callback and the connection SSL object is provided there.

PSK can be passed in the vhost's context creation struct

```
	const char *ssl_private_key_password;
	/**< VHOST: NULL or the passphrase needed for the private key */
```

in short lws wraps the ssl context and makes selected things available by callback or the init struct, rather than throwing the complexity of OpenSSL init on the user code.  If there's something else useful needed, patches welcome or if it sounds useful to me I may add it.

**Comment by cbucht200** [comment]
@lws-team It is possible that one may want to accept connections with multiple PSKs. If one could hook into the PSK callback, they have the power to manage a list of PSKs and change them on the fly. Also, for a PSK cipher, I do not believe one needs to have a cert/key pair.
