### ISSUE TITLE
Fallback support for Dual stack network

### ISSUE THREAD

**Issue by selvamKrish** [warmcat/libwebsockets#926]
Hi,
This is not an issue, but I'm figuring out is there any way to fallback Ipv6 connection to Ipv4 connection in Dual stack network in case if Ipv6 connection fails. For example if Ipv6 connection fails with "Network unreachable" errno 101 then while retrying lws should try with Ipv4 connection. 

I was analysing the code there I could see #ifdef LWS_USE_IPV6 compile flag check for Ipv6 support, So if I enable Ipv6 then I don't think Ipv4 code gets compiled at same. Any information for this support will be helpful for me.

Thanks in advance.

**Comment by lws-team** [comment]
For server, the connecting client will have already come in successfully on ipv6 or ipv4 before we heard about it, so nothing to do I think.

For client... if you look at the ipv6 dns lookup code at client-handshake.c line 95, and compare it to the ipv4 version on line 147, the ipv6 does not iterate through all the results like the ipv4 version does.  It already has code to handle both ipv4 and ipv6 results.  It looks like both should actually iterate through the results if there was a failed connect() to get what you want.  Does it make sense?

**Comment by selvamKrish** [comment]
Thanks for reply, I agree with your point. But if you see at line 154 in client-handshake.c, even though you iterate inside loop for Ipv4 address, returned from getaddrinfo, once it returns first Ip then you are coming out from loop by doing break, that means connect() will always try to connect with first address returned from getaddrinfo (even if it get fails due to some temporary network failure reason) and it will never try to do connect() with other address returned from getaddrinfo. 

My proposal is something like below for dual network scenario,

#ifdef DUAL_NETWORK_ENABLE
	hints.ai_family = AF_UNSPEC; /*Ipv6 or ipv4*/ 
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_protocol = 0;	
	hints.ai_flags = AI_ADDRCONFIG;
	/* resolving host name */
	retVal = getaddrinfo(host, port, &hints, &result);
	if (retVal != 0){ 
		/* getaddrinfo FAILED */
		return -1;
	} 
	else
	{
		/* iterate all address either Ipv6 or Ipv4  returned from getaddrinfo till connect() success*/
		while(ip_is_present)
		{
					if(rp->ai_family == AF_INET)
						/* getaddrinfo resolved Ipv4 address, Try connect with IPv4 mode */
					else if(rp->ai_family == AF_INET6)
						/* getaddrinfo resolved Ipv6 address, Try connect with IPv6 mode */

					session = socket(rp->ai_family, rp->ai_socktype, 0);
			        if (session == FAILURE)
			       	   /*	FAILED to create socket, Try again with other address  */
				       continue;
	 		        else
			       		/* SUCCESS socket created successfully */
			       		       	       
				   if (connect(session, rp->ai_addr, rp->ai_addrlen) < 0)
				   {
				   		if(errno != SOME_ERRNO_CHECK) 
							/* here close socket and retry the connection*/
							return -1;
						else
							/* Retry again with other address returned from getaddrinfo */
				   }
				   else
				   {
				   		/* Connect is successful, you can continue with handshake */
				   		break;
				   }
		}
#endif

The reason behind above code is, in my dual stack network case sometimes Ipv6 connection will get fail or refused in some network ip range. So in this case even Ipv4 mapped Ipv6 address also will get fail. If we try with Ipv4 connect then it will connect successfully.

Please check above code and provide your comments. If you feel any additional changes or improvements required then I'm ready to work on that.

**Comment by selvamKrish** [comment]
Can you please check above code ? and let me know your opinion.

**Comment by lws-team** [comment]
Sorry for the delay.  I think before attempting anything on this code it needs a big cleanup which I am doing now.  Because it grew its functionality in stages, with some pieces contributed, there is quite a bit of redundancy meaning the code can be simplified which I should do first.  Otherwise it will be difficult to add another layer.

The other issue I don't really know the right answer to yet is the scheme you roughed out above doesn't take account that with nonblocking sockets, connect() may complete, or fail, asynchronously.  That means unless something is obviously unworkable, it will return EINPROGRESS and we don't know the outcome until later.

That is the case today, it works but but we only get one shot at it.

Although I did not express it well that is what I meant in my first reply "It looks like both should actually iterate through the results if there was a failed connect() to get what you want.".   What I meant is when you later learn of the failed connect, there should be a budget for returning the state machine for the connection to the point where it will retry the connection with another result from getaddrinfo if any more are usable, before really failing if none left.  However since round-robin DNS will give a different order of getaddrino() results each time, it looks like you might have to do that once, cache the result on the wsi, and iterate through the results in the cached copy.

A less ideal alternative is still get one shot at it but iterate through the results until connect() at least gives EINPROGRESS.... that's basically what your rough code is doing IIUI.

**Comment by lws-team** [comment]
I pushed the cleanup.

To help prepare for what you have been talking about there's a flag in the wsi now wsi->ipv6 which is set if ipv6 is possible (configured and enabled on the vhost).  It alone is used to decide to choose ipv6 or not for the connection in this code subsequently.

Also, I don't know if it meets what you want, but the vhost can take options at creation time (if you use the default vhost and just create the context, this == context creation time).  If ipv6 is otherwise enabled and you set `LWS_SERVER_OPTION_IPV6_V6ONLY_MODIFY | LWS_SERVER_OPTION_IPV6_V6ONLY_VALUE` this will only choose the first AF_INET6 result from getaddrinfo.

If you just set `LWS_SERVER_OPTION_IPV6_V6ONLY_MODIFY`, now it will uplevel an AF_INET address to be an AF_INET6 address.

This still goes out as ipv6, but it's routable on IPv4 networks AIUI.

Please try the cleaned up version and see if it breaks anything first.

**Comment by lws-team** [comment]
... if there's something more for me to do, please let me know.
