### ISSUE TITLE
ESP32 ranlib

### ISSUE THREAD

**Issue by tedwoodt25** [warmcat/libwebsockets#928]
When building for ESP32 on a Mac Cmake uses the native ranlib rather than the ESP32 version. I fixed it by adding a link to the ESP32 version in /usr/local/bin, which is earlier in my search path

**Comment by lws-team** [comment]
Ok... but is there anything in lws that refers to ranlib?

If not, this is an issue for esp-idf isn't it?

**Comment by tedwoodt25** [comment]
I don't thinks so. In cross-esp32.cmake there is a line:

set(CMAKE_AR "${CROSS_PATH}/bin/xtensa-esp32-elf-ar")

We added:

set(CMAKE_RANLIB "${CROSS_PATH}/bin/xtensa-esp32-elf-ranlib")
set(CMAKE_LINKER "${CROSS_PATH}/bin/xtensa-esp32-elf-ld")

Which fixed it.

**Comment by lws-team** [comment]
OK... but I dunno why esp-idf gives us eg, the right gcc, and the right everything else in my case except ar.  In your case, I guess due to the platform you get more wrong things (but again the right compiler).

I think lws shouldn't have to fake these to be correct any more than it has to (it does not have to) fake gcc to be correct.

**Comment by lws-team** [comment]
Urk... I do set gcc, I forgot about it.  But I don't need to set anything else including AR.

Can you try commenting your additions in cross-esp32.cmake and changing the end of this line there

```
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
```

to ONLY or BOTH and see if that helps.

**Comment by tedwoodt25** [comment]
Neither of them seems to fix it. When set to ONLY it fails while linking libwebsockets when set to BOTH it fails in the same place as before, at final link. 

Is it is looking for ranlib rather than xtensa-esp32-elf-gcc-ranlib that is the problem here?

**Comment by lws-team** [comment]
In a sense that's the problem it seems.

But lws has no idea about ranlib (android cmake cross file mentions it, but that's not in use here).  Either cmake generates something that wants it (without the path prefix), or the reference to it comes from esp-idf, we are using their build system on esp32.  And since I don't need any changes on Linux build platform, whatever wants ranlib only does so on mac.

Anyway I added all three cross path overrides you mentioned here (as I said though, the AR one did not exist here) and updated lws-esp32-factory with latest lws.
