### ISSUE TITLE
Question about sending a packet

### ISSUE THREAD

**Issue by sorrowhill** [warmcat/libwebsockets#932]
Hi,

I'm reading the note that describes coding with libwebsockets.

it says,

> Libwebsockets may generate additional LWS_CALLBACK_CLIENT_WRITEABLE events if it met network conditions where it had to buffer your send data internally.

because of network conditions, does this rule also apply to LWS_CALLBACK_SERVER_WRITEABLE event?

> It's quite possible you get an 'extra' writeable callback at any time and just need to return 0 and wait for the expected callback later.

and how can i assume that it is additional event or not? i can't find the example for it, perhaps i can identify the callback from the arguments?

thanks

**Comment by lws-team** [comment]
Yeah it applies to both client and server.

Generally there is no strict relationship between asking for a writable callback and getting the callback, except if you asked at least once you will get at least one callback when it eventually does become writeable.

Your code might ask ten times while the receiving side is not sending ACKs for some time, and eventually get one callback, not ten.

If lws had to buffer your last send, it generates and consumes writable callbacks internally... since your request may be consumed by these internal buffer draining activities it makes an explicit extra callback next time it's writeable after the send was completed.

So the approach in the callback should be

 - figure out if the wsi has something to send.  If not, just ignore it and return 0.

 - After sending anything, if something more to send ask for another writable callback

**Comment by sorrowhill** [comment]
Thanks for fast reply. but still, I have another question.

I prototyped the test code and understand that `lws_context` is just context for i/o looping(if it isn't, at least it doesn't do much thing in connection). anyway, I'm looking for a way to use one lws_context(it uses for i/o) per each web socket connection(one for a server, many for client connection), to make it simple.

What i want to know is, does libwebsockets guarantees that using multiple lws_context in one process?(I will also use it with libuv, SSL), I'm wondering that your options in this case.

you saved a lot of times!
Thanks.

**Comment by lws-team** [comment]
No... it's the wrong way... you should have one context, one event loop, in one thread.  The context will initialize any ssl support needed one time.  In libuv terms, the context holds the libuv loop object.  You should have one loop for everything not one per connection.  In particular, older openssl still in wide use only supports processwide library init and dedtruction, mandating exactly one context.

You can serve many connections in the one context and make multiple client connections in the one context as well.  And for server, you may create many vhosts in the one context too, each with their own ssl credentials (eg, https://libwebsockets.org and https://warmcat.com are both vhosts in a single context using lwsws).

**Comment by sorrowhill** [comment]
Thanks for advice! :+1:
