### ISSUE TITLE
Managing sockets in multithreading environment

### ISSUE THREAD

**Issue by sorrowhill** [warmcat/libwebsockets#934]
Hi,

Currently my program has a server, and can create many client sockets dynamically. With your advice, I'm managing whole sockets in one context with libuv and SSL implements. but there is a problem.

The problem is, when one of client socket is blocked or waiting response from server, the rest sockets have to wait, because of only one context runs.

My program runs only one server and must have it's own scheduler, so it cannot be disturbed by other client web socket.

So I posted again for your opinions, Is there any way to manage it concurrently? I want to run a program that a server has it's own scheduler, and each client also has it's own scheduler.

I tried to change a logic with pthread + libuv example, but it doesn't guarantees that each session has it's own scheduler.

thanks.

Edit:
I found that i can inject a callback for each socket if i can create multiple contexts with lws_create_context. but sadly, you already said that it must be one in one program.

Edit2:
I just found that a client web socket cannot be created/or connected when it's protocol is not specified in lws_context.protocols. Is there any way to do that?

Edit3:

In LibSSL document, it says

> if your program is multi-threaded, then you will need to install the static locks. The static locks are used for extensively for libssl, and used in the random number generator for libcrypto. The locks should be installed after the calling:

    SSL_library_init
    OpenSSL_add_ssl_algorithms
    OpenSSL_add_all_algorithms
    SSL_load_error_strings
    ERR_load_crypto_strings

3 of above functions are used in `lws_context_init_ssl_library`, which is in `lws_create_context`. so what if i put the static locking in `lws_create_context`? i think i can make multiple contexts if i create it carefully, is there any issues should i consider?

thanks.

**Comment by lws-team** [comment]
All of the sockets in lws are nonblocking, including client sockets.  So whatever it is you're experiencing, it is not to do with "when one of client socket is blocked or waiting response from server, the rest sockets have to wait" because of lws.  Client connection is handled in a multistep state machine which returns to the event loop between each step and between retries.  There's only one case where the system call is synchronous, which is address lookup for client.

If you still think this is caused in lws, please let me know how to reproduce using the test client.

For the rest, you seem to be mixing up network events and some not-directly-related operations you want to have happen on a set schedule.  You are never in control of network events to some internal schedule no matter what you do.  The network, including the remote peer, is in control of deciding if you can write something, and when you will receive something, not you.  So usually the thing that needs internal timing and the network actions are anyway decoupled.  If you feel you have to have a thread per connection you need to manage serializing events on that for lws or any other event loop-based networking library (ie, even libuv directly).

IIRC you can use no explicit protocol by giving a protocol of "".  These bind to protocols[0] if you don't set a different protocol as the default.  Have a look in, eg, test-server-v2.0.c for an example of how to do that.

**Comment by sorrowhill** [comment]
Thanks. I'll look the example. just worndering, does it only works in 2.0 version?

**Comment by lws-team** [comment]
2.0+ ... 2.0 introduced the new features it depends on like vhosts, per-vhost protocols and protocol options, mounts etc.

**Comment by sorrowhill** [comment]
Thanks for the info, now i can draw the picture of the library :) you saved me a lot of time, even my lack of network experience.
