### ISSUE TITLE
Ways to reduce RAM usage Esp32

### ISSUE THREAD

**Issue by johsely1234** [warmcat/libwebsockets#937]
I need to reduce my usage of RAM on the Esp32. Currently the lws initialisation uses about 31600 Byte of RAM and one Client connection uses approximately 14000 Byte. I have set the rx_buffer_size and tx_packet_size of the protocol (I only use one protocol) to 1024 Byte each. The mbedtls buffer is also 1024 Byte. The per_session_data_size is only one integer. Why does it still need 14kByte for one connection? Is there any way to reduce this further?
I measured the used heap with the xPortGetFreeHeapSize() function before a client connects and after.

What are the parameters of lws to make it use a smaller memory?

Maybe you can help me, I would really appreciate your help!

**Comment by lws-team** [comment]
Lws covers a lot of use-cases on a wide range of machines.  The fact it can work on ESP8266 and ESP32 at all shows it is pretty modest for resource consumption, but it also works well on Linux + libuv / epoll to hundreds of thousands of simultaneous connections.

There's also a problem just sampling total heap allocations, a major problem is unbounded instantaneous allocations, since the rest of ESP32 is heavily dynamically allocating from the same heap for things like lwip and even the wlan stack.  That's also an issue on busy servers, since many incoming connections at once that cause temporary heap allocations (eg, to parse http headers) can actually lead to unbounded dynamic memory usage.  LWS already favours allocations into configurable pools at init time where possible and defer handling incoming network connections when the pool is all in use.

That's not to say it's static allocation -happy, it also widely uses linked-lists which only have a pointer footprint per entry in the existing object and completely avoid needless allocations.

Many of the RAM-consuming things are configurable in the context creation info struct... for ESP32 there is a helper call to initialize it to defaults suitable for the lws test server OTA app + factory app

```
void
lws_esp32_set_creation_defaults(struct lws_context_creation_info *info)
{
	const esp_partition_t *part;

	memset(info, 0, sizeof(*info));

	lws_set_log_level(63, lwsl_emit_syslog);

	part = lws_esp_ota_get_boot_partition();
	(void)part;

	info->port = 443;
	info->fd_limit_per_thread = 30;
	info->max_http_header_pool = 3;
	info->max_http_header_data = 1024;
	info->pt_serv_buf_size = 4096;
	info->keepalive_timeout = 30;
	info->timeout_secs = 30;
	info->simultaneous_ssl_restriction = 3;
	info->options = LWS_SERVER_OPTION_EXPLICIT_VHOSTS |
		       LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;

	info->ssl_cert_filepath = "ssl-pub.pem";
	info->ssl_private_key_filepath = "ssl-pri.pem";
}
```

but your code has a chance to override things before the info is actually used in `lws_esp32_init()`.

- lws allocates a lookup table sized by `fd_limit_per_thread`, it's probably not much but you should be able to reduce this

 - `max_http_header_pool` preallocates that many `ah`, which are structs that process and hold http headers.  If your app is only making one connection, it only needs one.  `max_http_header_data` is how much total storage for known header content the ah can handle... by default (left at 0) it is 4096 to allow large cookies, the esp plat code already tries to align it to the platform restrictions by setting it to 1024.

 - Here I saw ESP32 only seems to come up with packets below some MTU around 800 bytes.  So `info.pt_serv_buf_size` can probably be cut down to, eg, 1024.

 - The actual per-connection (aksa wsi) allocation in lws is only a few hundred bytes, IIRC it's like 3- 400 on esp32.   That doesn't account for SSL allocations from the TLS stack.

 - Connections are all ssl on top... this is provided by the esp-idf openssl shim and mbedtls.  I dunno how much that is using (measing the heap lumps it all together) but there is a scary sdkconfig setting CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN=.  For the lws-esp32-test-server-demos OTA, it would not work properly without this being set to 6144.  For other apps 4096 was OK.  I assume the stack allocates this per connection.

 - You might want to temporarily force info->port to 80, AND out ~LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT from `.options`, and mark your client connection as non-SSL as a test, in order to understand how much of that global heap is related to SSL that's outside the scope of lws.

 - If you are not actually wanting to listen and serve, you should force `info.port` to CONTEXT_PORT_NO_LISTEN before creating the context + vhost.

 - If you only have client connections, you can also look at deconfigure lws server code + init allocations completely at cmake.  The lws cmake option for that is `-DLWS_WITHOUT_SERVER=1`; you can add this to the cmake command in `./components/libwebsockets/component.mk`.

That should help a bit with memory and give some pointers on where to look next.

**Comment by lws-team** [comment]
Any results to report?

**Comment by johsely1234** [comment]
Hi, I am looking into this today!
Thanks in advance!

**Comment by johsely1234** [comment]
Yes, thanks for the help!

It really seems the mbetls uses a lot of the stack. I set the MAX_CONTENT_LEN to 1024 already before but it still needs a lot.

I set the fd_limit_per_thread to 15 which helped also a little bit.

All in all it should work now.
