### ISSUE TITLE
multiple lws contexts in one process

### ISSUE THREAD

**Issue by sejvlond** [warmcat/libwebsockets#943]
As far as I understand from other issues, lws is designed to be one context / one thread / per each process. It calls SSL_library_init in its lws_create_context function, which is not reentrant and also it cleans the openssl library (e.g. EVP_cleanup) in lws_context_destroy function, which makes any other usage of openssl in the process impossible.

What is wrong about having 3 websockets on 3 different ports opened in one application? Assume I have 3 different layers that each communicates with different network service. How else shall I do it, than having 3 websockets with 3 contexts?

Also, I need to close and reopen one of the lws during the lifetime, but closing and destroying the context causes problems to the rest of the application, which needs to use openssl.

Thanks for help and clarification!
Ondrej

**Comment by lws-team** [comment]
You can have as many connections as you like handled inside one context.

"How else" you do it is create one context, then if the connections 'on different ports' were inbound, ie, lws was serving, you would create three vhosts in the one context, each listening on a different port.  Any number of inbound connections could then be handled across the vhosts like that, in one context.  If you use SSL, each vhost may be told to use different certs.

If they are outbound connections, eg, "client" connections, again any number of simultaneous outbound connections can be handled in one context.

In fact you can have any mixture of inbound and outbound connections too, handled by one context.

All the sockets are nonblocking.  If in the whole context there is nothing to do, we idle in poll() by default (or in epoll() or whatever if using libuv).  If there are multiple things to do, lws does them sequentially, and the service will not block, since all sockets are nonblocking.

One of the main services the context manages are fd mapping tables, by default up to the fd limit of the process; since fds are a processwide resource, it's another reason you want just one lws context in your process.

So the point is there is no reason to use another context.  Does this help?

**Comment by sejvlond** [comment]
Connections are inbound, lws is serving. Ok I think I understand that, it sounds good.

I guess, I can close and create new vhosts during the lifetime of the process, which responds to my question how to create/destroy new inbound connections.

May I ask you about the performance? I need one lws connection send "realtime" data, wonn't there be a problem when multiple vhosts will be in one context?

Thank you for such a quick response!
Ondrej

**Comment by lws-team** [comment]
No... vhosts are like https://warmcat.com and https://libwebsockets.org ... these are two vhosts running on one lws context, both on port 443 as it happens.  The vhost represents the listen socket that inbound connections connect to, so they are static.

You don't 'create' inbound connections... the fact somebody connected to a listen socket does that for you.  You may close them, by returning nonzero from the user callback, or by forcing them to timeout.  But you are not in control of those connections really... the remote peer is,he can close his browser window any time after all.  So lws deals with informing you when the connection closed by itself and takes care of cleaning up.

Why would there be any performance problem?  There's the same underlying amount of work to do blocking vs nonblocking, except nonblocking eliminates threading and locking by serializing it in one thread.  The kernel side, which runs the networking part continues to run asynchronously on different cores if SMP.

Please try eg test-server/test-server-v2.0.c test app provided with lws.
