### ISSUE TITLE
lws_return_http_status cause assert about "writable callback"

### ISSUE THREAD

**Issue by rickynelson1939** [warmcat/libwebsockets#952]
if I spam http requests that cause response with lws_return_http_status then sometimes (might be 30 minutes without a bug, but might be in a first second) there was an assert telling me that I did write outside of writable callback

here is stack trace:
__GI_raise() at raise.c:54 0x7ffff7a42428
__GI_abort() at abort.c:89 0x7ffff7a4402a
__assert_fail_base() at assert.c:92 0x7ffff7a3abd7
__GI___assert_fail() at assert.c:101 0x7ffff7a3ac82
lws_issue_raw() at output.c:126 0x40d193
lws_write() at output.c:533 0x40dcdf
lws_return_http_status() at header.c:256 0x414044
callback_http() at test-server-http.c:273 0x4056dc
lws_http_action() at server.c:956 0x417522
lws_handshake_server() at server.c:1,461 0x41873e

**Comment by lws-team** [comment]
Basically to be compatible with HTTP/2, which codes the headers completely differently than the body, it sends the headers separately.  But since this isn't HTTP/2, we don't actually have to do that.

I pushed a patch https://github.com/warmcat/libwebsockets/commit/6a89c7e9317cd13a20d3d45b4bf392c2196a61f0 on master that should make it immune.

**Comment by rickynelson1939** [comment]
I think it fixed it, thanks.
P.S. no more bugs for now :)

**Comment by lws-team** [comment]
OK good...
