### ISSUE TITLE
what branch is actually stable?

### ISSUE THREAD

**Issue by rickynelson1939** [warmcat/libwebsockets#954]
so there is stable v2.2, but bugs are fixed in only in master, right? does that mean that master is actually a more stable one?

**Comment by lws-team** [comment]
No.... if a bug fix seems important for previous releases, I will backport the fix as far back as reasonable.

Currently that's typically v2.0, but possibly v1.7 if it's been around that long.

But it's just fixes, we never change the api on the -stable branches or add new features.

Master on the other hand gets code for new features as well as the bugfixes.  In that sense it's not stable, since the api may change, etc.
