### ISSUE TITLE
Get timeout reason from struct lws

### ISSUE THREAD

**Issue by shenchsh** [warmcat/libwebsockets#957]
Is there any api that can be used to get timeout reason from struct lws? I am trying to get the timeout reason from LWS_CALLBACK_SERVER_WRITEABLE. 

When I try to use wsi->pending_timeout, there is a "dereferencing pointer to incomplete type 'struct lws'" error.

**Comment by lws-team** [comment]
Stuff in `struct lws` is private to lws... it may change between lws versions.

If you time out, lws will log the reason code

```
if (wsi->pending_timeout != PENDING_TIMEOUT_HTTP_KEEPALIVE_IDLE)
			lwsl_notice("wsi %p: TIMEDOUT WAITING on %d (did hdr %d, ah %p, wl %d, pfd events %d) %llu vs %llu\n",
			    (void *)wsi, wsi->pending_timeout,
			    wsi->hdr_parsing_completed, wsi->u.hdr.ah,
			    pt->ah_wait_list_length, n, (unsigned long long)sec, (unsigned long long)wsi->pending_timeout_limit);
```

Otherwise you shouldn't rely on the timeout reason being 'sticky'... if for example it's time for a keepalive ping lws will replace your timeout with one related to that.

If you want to hold state related to the connection, it should be done in a 'pss' like the example code does it.
