### ISSUE TITLE
deallocate resources

### ISSUE THREAD

**Issue by yjjnls** [warmcat/libwebsockets#975]
If a websocket client failed to connect a websocket server. `LWS_CALLBACK_CLIENT_CONNECTION_ERROR` will be called to do my logic. But I want to know how to release the allocated resources in this case. 
As I will dynamically connect to a server, if failed, I release by `lws_context_destroy(context)` and an error will occur. But I do the same thing when the process terminates and it's OK. 
How to solve this?

**Comment by lws-team** [comment]
Sorry what 'resources' are we talking about?

They are your resources?  When did you allocate them?

**Comment by yjjnls** [comment]
the source I mentioned is such as `struct lws_context *context` created by `lws_create_context`.

**Comment by lws-team** [comment]
You should have one lws_context in your app.

You can create multiple client connections, whether they fail or succeed, using the same context without having to delete it until your app exits.

Does it make sense?

**Comment by yjjnls** [comment]
The server process may run in a very long time. If the connection to another server failed as the remote websocket server crashed or just connect to wrong url. In this case, if the `lws_context` holds on until the app exits, I think it's a memory leak.

**Comment by lws-team** [comment]
It's unclear what we have been talking about, but if it is "leak when client connection fails" I fixed two cases of this Friday on master:

https://github.com/warmcat/libwebsockets/commit/003bd7dcee5bc96637f4f57ad1834b0d8f3b601f
https://github.com/warmcat/libwebsockets/commit/3562e441e3b3f150a1e80b95b1aad3e09fc88725

if there is still something leaking, you need to help me at least with how to reproduce it and preferably valgrind backtraces for what it is that is leaking.

**Comment by yjjnls** [comment]
I mean if the connection fails and I delete or destroy `lws_context` when the app exits. It won't be reported memory leak **by the tool such as valgrind**. 
But If I hold the `lws_context` of the failed connection and it won't be used any more, I think this behavior is one kind of memory leak.
And I tried to destroy the `lws_context` dynamically, but the mainloop(libuv) will report an error.

**Comment by lws-team** [comment]
OK so we gradually tick off things we are "not" talking about :-)

There is no memory leak in the usual sense.  The memory usage is tracked and cleaned by the time we exit.

If you only have one lws_context in your application, there is no difference to lws if you destroy it yourself at some point or wait to destroy it until just before the process exits.  Lws doesn't know your program is getting ready to exit.

Your issue seems to boil down to you are unable to call lws_destroy_context / 2() earlier without some kind of error coming.

So what error is coming if you do the lws_destroy_context() and lws_destroy_context2()?

**Comment by yjjnls** [comment]
I close the timeout_watcher and destroy the lws_context, but it will crash in the mainloop. I use a foreign loop in libuv and I don't know the details in the mainloop. 
In another case, the client actively close the connection and I do the same thing. But it's not crashed.
Did it do correctly? Or is there an example about do the lws_destroy_context()  not in the end?

**Comment by lws-team** [comment]
libwebsockets-test-server-libuv can do it, just move the lws_context_destroy2() up

```
diff --git a/test-server/test-server-libuv.c b/test-server/test-server-libuv.c
index df8a684..2fc8ed4 100644
--- a/test-server/test-server-libuv.c
+++ b/test-server/test-server-libuv.c
@@ -420,6 +420,9 @@ int main(int argc, char **argv)
 
                /* detach lws */
                lws_context_destroy(context);
+               /* finalize context destruction */
+
+               lws_context_destroy2(context);
 
                lwsl_notice("Please wait while the outer libuv test continues for 10s\n");
 
@@ -456,9 +459,6 @@ int main(int argc, char **argv)
                lwsl_notice("uv loop close rc %s\n",
                            e ? uv_strerror(e) : "ok");
 
-               /* PHASE 4: finalize context destruction */
-
-               lws_context_destroy2(context);
        } else
 #endif
        {
```

There is no problem running it with -f (foreign loop), but this isn't exactly your situation since no client.

Generally, if you tell me, "there is a crash" or "there is a segfault" there is zero action I can take.

If there is a simple way I can reproduce it, or you give detailed backtraces in lws (together with exact lws version so I can interpret them) I stand a chance to do something.  So if it needs failing client connection, consider a small patch adding a failing client connection to libwebsockets-test-server-libuv.c so I can "feel your pain".

**Comment by yjjnls** [comment]
I solve it. 

The sample `test-server-libuv` stop the loop firstly and then close the lws_context. But in my case, the mainloop is still running while I deal with failed lws_context. As other successful connections are still working.

I call `lws_context_destroy(context);` in the callback `LWS_CALLBACK_CLIENT_CONNECTION_ERROR` and the libuv may report an error.
Then I did this later after the callback `LWS_CALLBACK_CLIENT_CONNECTION_ERROR` finished. It worked as I expected.

**Comment by lws-team** [comment]
I'm glad you're working.... so in the end it was "can I destroy the context while a connection is getting serviced from within the context?"  "No."

**Comment by lws-team** [comment]
Actually what you wrote here is wrong:

> The sample test-server-libuv stop the loop firstly and then close the lws_context. But in my case, 

If you run `libwesockets-test-server-libuv -f` it goes to great lengths to run the "foreign" libuv loop before the lws context is created, and after it was destroyed.  The point is the `-f` making it test the 'foreign loop' that has a lifetime extending both before and after the lws context.
