### ISSUE TITLE
build failed for iOS

### ISSUE THREAD

**Issue by qq3200341** [warmcat/libwebsockets#984]
I use CMake client and toolchain build a Xcode project suceessfully, but i can not compiled into static library through the project.
Finally, i found the mistake '#define malloc' '#define realloc' in lws_config_private.h. If i delete these two lines i can compile.
But there is a problem when i use the static lib on iOS device.

**Comment by lws-team** [comment]
I don't have any Apple stuff.

If you are expecting me to do something about it, you are going to have to do better than tell me you 'have a problem' on a platform I don't have.  That's about as useful as telling me you 'have a segfault' or 'a crash'.  What action am I supposed to take with this information?

Whatever is up with the malloc defs it won't be the root cause either.
