### ISSUE TITLE
Simpler examples for client and server

### ISSUE THREAD

**Issue by PTS93** [warmcat/libwebsockets#997]
I have noticed that the examples provided by libwebsockets are very fleshed out and full featured.
As a newcomer to the library it is very hard to grasp the API from these examples within a reasonable amount of time. A LOT of reading is required to get even a hello world client going.
The test apps are great as testing tools but far too complicated to still serve as example code. Which it seems they were intended to be at some point?

I think a lot of users would appreciate a bare bone example with common settings for a server and client program.

**Comment by lws-team** [comment]
You are right, lws offers a lot of features and the test apps are trying to test them, in the process becoming opaque.

However for server this is not as bad as it may look, due to

 - test-server-v2.0.c bringing all the manual stuff into lws, eg, mounts, and the built-in dummy handler for http

 - lwsws not even requiring any code, but taking options via JSON config files; this removes the need for any customized server code for standalone serving, and,

 - "plugins" isolating user protocol code out of the server itself

If you're not integrating lws into some other code, you can ignore the old test server and follow the "2.0" / lwsws way with either no server code or heavily simplified user code.

For client the test code is more manageable.

**Comment by PTS93** [comment]
I would still call ~700 lines of code a bit daunting for a simple example client :)
I found https://github.com/iamscottmoyers/simple-libwebsockets-example/blob/master/client.c
that is nice example in about 100 lines. Maybe its worth merging into the repo?

**Comment by lws-team** [comment]
It doesn't support SSL (a few hours ago there's an issue from a guy who mangled cutting down the SSL example; this wouldn't help).  The test client supports most of what's available, including SSL and multiple client connections.

There are already a lot of examples that need maintaining.  I agree minimal examples missing things are at least arguable but they are not a shoo-in.

**Comment by dxing97** [comment]
While a barebones example program would help new users get a feel for how lws works, in the end I think that getting a good understanding of how the larger examples work goes a long way in understanding how lws is meant to be used, which is what I found when I was trying to write a client program.

**Comment by lws-team** [comment]
I don't think there's a perfect solution to this... at the moment the cost of entry is you start with a (very) functional example, and cut it down and modify it to be more suitable for your needs.  This pattern of knowing it already works from the start, and being able to confirm it's still working step by step, is actually quite powerful, if expensive at the beginning.

For server, we provide a generic solution in lwsws, so you don't need to get involved with any code about that, only plugin code for your functionality.  Users are encouraged to use that if possible or if not use the -v2.0.c sample.

Providing a no-TLS 100 line solution for client with no comments isn't really moving it forward.  So while understanding it's annoying for new users, I think the current way is good enough.
