### ISSUE TITLE
How to debug http header I send

### ISSUE THREAD

**Issue by howardguo** [warmcat/libwebsockets#998]
Hi, How to use lws_set_log_level to debug the http header that I sent? I want to know the http header I send is right or not. Any way? In fact , I add a header "Authorization", but I don't know it is added or not, and the value is right or not.

**Comment by lws-team** [comment]
If you don't use SSL / TLS, then you can use wireshark / tcpdump to look at the actual network packet with the headers.  Since you just care about watching and confirming what you send, you could disable SSL / TLS temporarily and try to connect to any non-SSL / TLS server.

The server receiving the headers might also give you a way to dump what it receives after the SSL / TLS tunnel.

If you specifically need to dump it in lws for some reason, dump the buffer from char * `sb` to char *`p`  here

https://github.com/warmcat/libwebsockets/blob/master/lib/client.c#L397
