### ISSUE TITLE
Should lws_ssl_context_destroy really deinit SSL?

### ISSUE THREAD

**Issue by micis** [warmcat/libwebsockets#999]
Hello,

The function lws_ssl_context_destroy() deinit SSL by calling functions like CRYPTO_cleanup_all_ex_data().
So, it is not anymore possible to use SSL functions after a call to lws_ssl_context_destroy().

I've seen the problem with the following case:
1-A program initialize libcurl with SSL support
2-The program then tries to create a websocket server on port 80
3-Port 80 is forbidden for user
4-lws_context_destroy() and lws_ssl_context_destroy are called ; deinitializing SSL
5-Operations using SSL from the main program now fail (can't use curl to get HTTPS)

Best regards,

**Comment by lws-team** [comment]
Hum... it's like that because standalone, the actions we did initing openssl requires us to do that de-init to be valgrind clean.  In that sense, yes, we should be doing it.

However OpenSSL multiple init in a process has been at least a mess, to the point you can only actually have one openssl init in your process (this is an openssl thing, not an lws thing).  In later (1.1?) Openssl they introduced new init / destroy apis to try to get around the problems; lws uses those if it detects them.

If you find you have to override something in lws' legit cleanup to work, I'll consider adding a context option flag to help.  But this mess is coming from processwide thing in openssl.

**Comment by micis** [comment]
Thanks for your response.

As libwebsocket is a library, it could be easily used in a program doing SSL too.
(Not important: I'm asking myself if opening 2 WSS and closing 1 is safe. Does it cleanup SSL anyway?)

In libcurl (as an example), SSL is initialized and cleanup only once. I can't tell for the exact way it is done, but 2 functions are exposed:
https://curl.haxx.se/libcurl/c/curl_global_init.html
https://curl.haxx.se/libcurl/c/curl_global_cleanup.html

In some way, curl_global_init is not mandatory as it will be called internally in libcurl when needed at first use.
curl_global_cleanup is probably mandatory to call by the user of the library to release all resources and be valgrind clean.

**Comment by lws-team** [comment]
Like I said, openssl recognized their problem and later versions of the library (1.1+) have more sane apis, eg

https://www.openssl.org/docs/man1.1.0/ssl/OPENSSL_init_ssl.html

which we use if we see we are on a suitable version.

I can't help you with what curl or openssl have done; the layer binding libs together may not be in a position to know definitively when it should init or destroy stuff for the thread, or process.  I think if you look closer you will see this is a big nasty minefield

https://wiki.openssl.org/index.php/Library_Initialization

with different versions needing different things.

If you're on openssl v1.1+ and you need something to solve an lws integration problem by all means suggest a patch that worked for you and is actionable for me and I'll try to figure out if it makes sense or can be made to make sense from lws pov.

**Comment by micis** [comment]
Understood, thanks for the explanation!
I'll retry with openssl v1.1+ later.
No more to say ; closing the issue.
